### ISSUE TITLE
Uses non-host DNS servers

### ISSUE THREAD

**Issue by popey** [canonical/multipass#1]
I'm in an office (as it turns out Canonical) where there is no access to 8.8.8.8 which is the default DNS in multipass. Nothing resolves inside my multipass machine, but external host DNS resolution is fine.

This will also affect some of the software vendors we're talking to, who may use multipass as a way to have clean build environments for their software. If the multipass instance can't see internal repositories then it will fail to build. They may also have similar restrictions to us in terms of DNS access.

**Comment by Saviq** [comment]
As a workaround, you can change the `dns-nameservers` option in ` /etc/network/interfaces.d/50-cloud-init.cfg`.

**Comment by anthonydillon** [comment]
This worked for me, thanks @Saviq!

On the host machine, run `nmcli dev show | grep 'IP4.DNS'` to get the office DNS.

In the VM edit `/etc/network/interfaces.d/50-cloud-init.cfg` with:
```
dns-nameservers {insert office DNS} 8.8.8.8
```
Then run `sudo service network restart`.

**Comment by townsend2010** [comment]
The way to go is to switch over to using dnsmasq on the host and any newly created instances will use this. For already existing instances, we'll just keep some legacy code to use the already configured static IP, etc.
