### ISSUE TITLE
Use xterm-256color

### ISSUE THREAD

**Issue by Paris** [canonical/multipass#1004]
`multipass shell` should set the `$TERM` variable to `xterm-256color` or preferrably the same value of the variable set by the environment where it was invoked, at the moment it's just `xterm` which isn't ideal.

**Comment by jsilvermoslearn** [comment]
is there a workaround for this? a way to export shell env vars that multipass passes to the login shell?

thanks

**Comment by flying-sausages** [comment]
@jsilvermoslearn you can SSH into your VM which will work the way I assume you'd expect

**Comment by uishon** [comment]
Any chance to solve this issue on Windows as well? Just tried it out on 1.4.0 and when I `multipass shell` on Windows, `TERM` is still set to `xterm` and not `xterm-256color`. If I `ssh` to that same multipass instance, `TERM` is set up correctly. But, I prefer using `multipass shell`...
