### ISSUE TITLE
file based image on macos

### ISSUE THREAD

**Issue by daviehh** [canonical/multipass#1024]
On the current release, looks like the file-based images are not supported for macos: e.g. `multipass launch file:///path/to/Fedora-Cloud-Base-30-1.2.x86_64.raw` returns

> launch failed: http and file based images are not supported 

Is there a plan to add such support to macos or is there some technical hurdle? Thanks a lot!

macos: 10.14.6 (18G95)

**Comment by Saviq** [comment]
Hi @daviehh, we currently need to provide the hypervisor with a kernel / initrd pair separate to the image, which means we can't use the kernel inside the image (or we'd have to extract it, not fun).

We are looking into making this possible, but I'm afraid there's some higher priority items on our roadmap. You can always use LXD inside the instance to run other systems with little overhead.

**Comment by lmars** [comment]
@Saviq I would also like this functionality, and I'd be happy to try to contribute to make it happen.

My use case here is taking a stock ubuntu cloud image, running some setup, and then saving that as a custom image to then launch further instances with, so I'd just be using the same kernel / initrd from the stock image.

How about adding `--kernel` and `--initrd` flags on macOS, and requiring those if a URI is passed to `multipass launch`:

```
$ multipass launch file://custom.img --kernel vmlinuz --initrd initrd.img
```
