### ISSUE TITLE
block suspend to idle on XPS-13-9380

### ISSUE THREAD

**Issue by alex-tu-cc** [canonical/multipass#1030]
refer to [LP:#1840484 linux-oem 4.15 can not suspend to idle XPS-13-9380](https://bugs.launchpad.net/ubuntu/+source/linux-signed-oem/+bug/1840484)
The system will be wake up immediately after suspend.

**Comment by Saviq** [comment]
Hi, I commented in the Launchpad bug. It's unclear to me that Multipass is to blame (as opposed to QEMU/KVM).

**Comment by alex-tu-cc** [comment]
updated on launchpad for the test result on KVM.

**Comment by Saviq** [comment]
@alex-tu-cc do you have any pointers on where to look for the cause of this?

**Comment by alex-tu-cc** [comment]
sorry, I not yet have time to debug it.

**Comment by townsend2010** [comment]
I don't believe this issue occurs anymore.  Please reopen if you find that it still happens.  Thanks!
