### ISSUE TITLE
IPv4 UNKNOWN - Hyperv Default Switch no ip

### ISSUE THREAD

**Issue by freemaths** [canonical/multipass#1052]
I'm pretty sure this is a windows 10 problem but would appreciate any advice on workarounds.

All was working fine until windows update yesterday (now  Windows 10 Pro Version 1903 Build 18362.295). I find windows updates often break hyper-v but usually a few reboots sort things out.

Since the update my virtual machine no longer gets a working ip. 

If I try to start from "multipass start" it gets:
start failed: timed out waiting for instance to respond.

If I then list or look at it in hyperv manager the instance is started but with no ip.

I've tried removing and re-adding the "Default Switch" to the instance but this make no difference. Multiple reboots have also made no difference.

If I ping vm1.mshome.net I get the IP which used to work (172.17.5.146) but "Request timed out.".

Any other logs I can look at or things I can try? Failing that any advice on the best way to log with Microsoft (technet?).

**Comment by Saviq** [comment]
I wonder if disabling and re-enabling the default switch could kick it into life… The internet [has some details](https://mikefrobbins.com/2018/11/08/managing-the-hyper-v-default-switch-in-windows-10-version-1709-and-higher-with-powershell/) about how to deal with the default switch… Maybe removing it altogether and rebooting would get it out of this bad state?

**Comment by izzuddinnatsir** [comment]
Try restart the instance, it worked for me.

**Comment by EronWright** [comment]
Be aware that "Cisco AnyConnect Secure Mobility Client" interferes with virtual adapters and might be a complicating factor.   Try unchecking "Cisco AnyConnect Network Access Manager Filter Driver" on the "vEthernet (Default Switch)" properties in Network Connections.

**Comment by pcgeek86** [comment]
Here's what worked for me:

* Uninstall Proton VPN client
* Uninstall Cisco VPN client
* ⚠ Reboot computer

Only after restarting my computer, did the Hyper-V default switch start working again.
