### ISSUE TITLE
No VMs are being created on Hyper-V

### ISSUE THREAD

**Issue by naymore** [canonical/multipass#1062]
Note: This is a nested virtualization setup (Windows Server 2019 Hyper-v on top of a Windows 10 host). Docker for Windows is working on the same Windows Server 2019 guest and WSL2 is working in a Win 10 Insiders guest image.

So virtualization is basically working.
Multipass is however not even creating a hyper-v vm as far as I can tell.

```
C:\Users\subject8473>multipass launch --name foo -vvv
launch failed: The following errors occurred:
foo: timed out waiting for response
```
(that's not exactly very verbosive...)

```
C:\Users\subject8473>multipass info  --all
Name:           foo
State:          Unknown
IPv4:           --
Release:        --
Image hash:     babd5399b947 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
```

Ok, so let's try to start it anyway...

```
[2019-09-14T11:18:43.596] [debug] [foo] Get-VM : Hyper-V was unable to find a virtual machine with name "foo".
At line:1 char:1
+ Get-VM -Name foo | Select-Object -ExpandProperty State
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (foo:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
/
  [2019-09-14T11:18:43.596] [debug] [foo] cmdlet exit status is 'false'
/
 /[2019-09-14T11:18:43.596] [debug] [foo] cmdlet: 'Get-VM -Name foo | Select-Object -ExpandProperty State'

 /[2019-09-14T11:18:43.628] [debug] [foo] Get-VM : Hyper-V was unable to find a virtual machine with name "foo".
At line:1 char:1
+ Get-VM -Name foo | Select-Object -ExpandProperty State
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (foo:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

 /[2019-09-14T11:18:43.628] [debug] [foo] cmdlet exit status is 'false'

start failed: The following errors occurred:
foo: timed out waiting for response
```

And that's right if you take a look at the Hyper-V Manager...

![image](https://user-images.githubusercontent.com/11159667/64906106-2ac4bc00-d6e2-11e9-8a49-c3cf2e26d5a5.png)

**Comment by Saviq** [comment]
Hi @naymore, I'm afraid we only currently support Windows 10 (not Server) hosts with the Hyper-V backend. The upcoming version will be more explicit about that.

Still, can you look in the Event Viewer under "Windows Logs/Application" (I just filed #1063 to log to a better place) for hopefully more information about why it failed. Let us know please what you find out!

**Comment by jaipalnair** [comment]
Hi,
I have install the multipass on Windows with virtual box, I am getting ip address 10.0.2.15 and can able to ping host machine from shell, but from host to guest (10.0.2.15) ping fails. Is there any way to change the ip address as bridge interface?. With this not reachable I am not able to login though web http://10.0.2.15:9000.

Thanks

**Comment by Saviq** [comment]
Hi @jaipalnair, we'll be working on adding support for bridged networking soon #118. In the mean time, you could add a second, bridged, network adapter either with `VBoxManage` or VirtualBox itself - you'll need to run them through `psexec.exe -s -i`.

**Comment by jaipalnair** [comment]
Thanks for the prompt reply. I have got it working in Hyper-V, the issue with the hyper-V is when I enable it on my Windows 10, I cannot start my VMware session because of an error " VMWare Workstation and Device/Credential Guard are not compatible" . I am using VMWare session for GNS3 and other OS simulations.

**Comment by Saviq** [comment]
I'll close this as we never got a reply from the original reporter. @naymore please reopen if you're still interested in getting this going :)

**Comment by kundeng** [comment]
How do you get multipass working in the nested windows 2019?  It complains hyper-V not enabled.

**Comment by Saviq** [comment]
@kundeng nested virtualization isn't universally available. You first need to ensure Hyper-V (or VirtualBox) is working, Multipass can't function without those.

Please also file a separate issue if you think there's something wrong going on.

**Comment by kundeng** [comment]
I don't think multipass supports windows 2019 server edition.  Yes,  the windows 2019 server is a VM nested inside vmware workstation with vmx enabled for that VM.

**Comment by kundeng** [comment]
see this https://github.com/canonical/multipass/issues/1323
