### ISSUE TITLE
Should filter out old, non-working Ubuntu series

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1068]
Our `multipass find` only lists supported Ubuntu releases, but with explicit `multipass launch …`, you can "force" it to use one of the unsupported ones. We should probably filter out those that don't work.

**Comment by townsend2010** [comment]
We have taken the stance that the images are there, but if they are "unsupported", then if they don't work, they don't work.  This images are not easily discoverable and we haven't seen any user issues surrounding this.
