### ISSUE TITLE
Launch stuck after switching access point and subsequently claiming network be disabled

### ISSUE THREAD

**Issue by kalikiana** [canonical/multipass#108]
I was using `multipass launch` to spin up an instance. While it was doing its thing the WiFi access point I was on lost Internet connectivity, which prompted me to switch to another one. The on-going launch got stuck. So I cancelled it and tried again. From this point on I'm getting `failed to launch: Network access is disabled.` even though connectivity is fine now.

This is on the beta channel which right now is 2017.2.3 aka revision 111.

**Comment by townsend2010** [comment]
@kalikiana, do you remember if launch was in the process of downloading a new image?

**Comment by townsend2010** [comment]
I think there are 2 issues here.  One is a bug in QNetworkAccessManager which causes the ``Network access is disabled`` issue.  See https://bugreports.qt.io/browse/QTBUG-55180.  It looks like this was merged in upstream Qt on Nov. 30, 2017, but looking at the Ubuntu package changelog, it looks like the fix may have just shown up with the snap built with the merge of #120.

The other issue that I'm not real clear on is launch getting stuck.  I'd like to know what launch was doing at the time.

**Comment by kalikiana** [comment]
Iirc there was a progressbar, so it probably was downloading an image.

**Comment by townsend2010** [comment]
@kalikiana, ok, thanks!
