### ISSUE TITLE
Fix GUI behaviour on macOS

### ISSUE THREAD

**Issue by sajith** [canonical/multipass#1082]
I guess the real issue is that I am confused by multipass-gui. :-)

Per #973, the system tray icon should provide some basic information on running instances, but it doesn't seem to do that.  It is also quite plain, with no icon:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/23618/65437282-23d83080-dde9-11e9-9d50-443b7598bec6.png">

Also, multipass-gui menu bar contains no information about currently running instances.  It has a "services" menu item, and a grayed-out "no services to apply" submenu item, and a "services preferences" submenu item, but it is unclear why they are there.  

Also: ``multipass-gui --help`` and ``multipass-gui --version`` simply launches multipass-gui instead of printing anything helpful.  I am not sure that is against macOS HIG, but it is surprising to me.

**Comment by townsend2010** [comment]
Hi @sajith,

There definitely seems to be something wrong with how the icon and gui is being presented for you.  I don't have a Mac right now and the person who does will be back next week.  We will try to reproduce next week and report back.

Thanks!

**Comment by townsend2010** [comment]
@Saviq,

When back, could you please try to reproduce the issue that @sajith is seeing.  Thanks!

**Comment by Saviq** [comment]
Hi @sajith, we're currently working on integrating the system menu item on macOS proper (#968) When you start `multipass-gui` however, you should see something akin to this on your top system menu:

![image](https://user-images.githubusercontent.com/231077/65872707-7aadaf00-e381-11e9-828f-7edcb575d389.png)

As for the `--help`, `--version` options, it is not meant for command line interaction, but we should probably add exactly that information :)

**Comment by sajith** [comment]
Ah I see, thank you!  I was confused by the application menu: it doesn't seem to do much.  Should there be an application menu without an active application window?  I am not used to that, and that perhaps was the source of my confusion.

![image](https://user-images.githubusercontent.com/23618/65894363-45986100-e36f-11e9-80df-c3664b004efc.png)

(I am at version 0.8.0 of multipass, installed using "`brew cask install multipass`", if it matters.)

**Comment by sajith** [comment]
I am not sure this matters, but, per [Apple's terminology](https://support.apple.com/guide/mac-help/menu-bar-mchlp1446/mac), things on left hand side are "app menus", and those on right hand side are "status menus".  I am also not sure if there's something called a "system tray", so perhaps that too added to my confusion.

(I just use macOS at work as a glorified ssh client.  Clearly I am not an expert, and apologies if I sound like I am posing to be one!)

**Comment by matthewpaulthomas** [comment]
The “system tray” is like the perfect programming language: programmers talk about it a lot, but in reality [there is no such thing](https://devblogs.microsoft.com/oldnewthing/20030910-00/?p=42583).

Multipass should not have an application menu as long as it doesn’t have a main window of its own.  “Hide Multipass” and “Hide Others” are both pointless in that situation, and “Quit” is already in the status menu.

**Comment by Saviq** [comment]
Totally, yes. We're in the process of integrating it _proper_ into macOS.
