### ISSUE TITLE
No ppc64el snap

### ISSUE THREAD

**Issue by paride** [canonical/multipass#1096]
The multipass ppc64el snap is not available:
```
$ uname -a
Linux axew-ppc64 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:43 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
$ sudo snap install multipass
error: snap "multipass" is not available on this architecture (ppc64el) but exists on other
       architectures (amd64, arm64, armhf).
```
Is it possible for you to enable it? Thanks!

**Comment by Saviq** [comment]
Hi @paride can you confirm that you have KVM working on your target? I'll get a testing build going ASAP.

**Comment by paride** [comment]
Hi @Saviq, yes I do. I'm fine with testing an experimental build, if that helps. Thanks!

**Comment by Saviq** [comment]
@paride have a try: `snap install multipass --channel edge/multiarch --classic`. There be dragons, though!

**Comment by paride** [comment]
There is not a lot to play with :(

```
ubuntu@axew-ppc64:~$ multipass launch
launch failed: Unsupported cloud image architecture
```

**Comment by Saviq** [comment]
@paride hmm sorry, will dig for where this bubbles up from. Will let you know!

**Comment by Saviq** [comment]
@paride somehow [our arch mapping](https://github.com/CanonicalLtd/multipass/blob/master/src/simplestreams/simple_streams_manifest.cpp#L30) fails. I'm now building a version that will actually print [what Qt thinks](https://github.com/CanonicalLtd/multipass/blob/master/src/simplestreams/simple_streams_manifest.cpp#L83) is the architecture.

You can monitor [the snap build page](https://launchpad.net/~saviq/+snap/multipass-test) to see when it's done.

**Comment by Saviq** [comment]
@paride it's built now, can you please test and check out what the unexpected architecture is? Thanks!

**Comment by paride** [comment]
The error message now is:
```
launch failed: Unsupported cloud image architecture: power64le
```

**Comment by Saviq** [comment]
@paride I've now kicked a build having added that string. This should get you further, but this is me stumbling in the dark without the hardware :)

**Comment by paride** [comment]
Thanks @Saviq! I gave it another try, but we're not there yet:
```
ubuntu@axew-ppc64:~$ multipass launch                                           
launch failed: failed to start qemu instance: chdir: No such file or directory  
```
I'm not sure on where it fails. Running it with `-vvv` doesn't add any message. I am sure KVM is working, as I have some guests running.

**Comment by Saviq** [comment]
@paride yeah that's certainly Multipass's fault, it's just the first time someone tries it on other architectures :)

I'll let you know when you can try again. I'm in the process of adding more logging in the deamon so the errors are more obvious.
