### ISSUE TITLE
[macos] failing a handful of tests

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1103]
```
# with sudo
…
[==========] 864 tests from 45 test suites ran. (8500 ms total)
[  PASSED  ] 859 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] Client.launch_cmd_custom_image_file_ok
[  FAILED  ] Client.launch_cmd_custom_image_http_ok
[  FAILED  ] ImageVault.custom_image_url_downloads
[  FAILED  ] ImageVault.invalid_image_alias_throw                                                                   
[  FAILED  ] ImageVault.http_download_returns_expected_image_info

# one more without sudo
[  FAILED  ] HyperkitBackend.creates_in_off_state
```

**Comment by townsend2010** [comment]
@saviq,

You have to run the tests with the unlock key in order for those to pass.

**Comment by townsend2010** [comment]
Not sure if this is know yet, but 4 of the test failures
```
[  FAILED  ] Client.launch_cmd_custom_image_file_ok
[  FAILED  ] Client.launch_cmd_custom_image_http_ok
[  FAILED  ] ImageVault.custom_image_url_downloads                                                          
[  FAILED  ] ImageVault.http_download_returns_expected_image_info
```
fail because we unilaterally disable that support on Mac because the kernel/initrd needed to boot images.  We either should just ignore those failures or disable those particular tests on Mac only.

**Comment by ricab** [comment]
Included in test failures tracked by #1515.

**Comment by chrsoo** [comment]
> fail because _we unilaterally disable that support on Mac_ because the kernel/initrd needed to boot images.
@townsend2010 do you have any more information on this? Currently *multipass* is the only sane alternative to run VMs on my M1 Mac and it would be great to be able to launch my own, local images...

**Comment by Saviq** [comment]
@chrsoo I think you want this one: https://github.com/canonical/multipass/issues/1396#issuecomment-989818010.

**Comment by townsend2010** [comment]
The failing issues are no longer relevant since we removed Hyperkit and the need to download kernels and initrds.
