### ISSUE TITLE
[windows] wrong handling of unicode characters

### ISSUE THREAD

**Issue by jaekook** [canonical/multipass#1111]
If I use fishshell with multipass shell, I always can see  "??(B" character.
![Cap 2019-10-04 09-35-19-871](https://user-images.githubusercontent.com/6639956/66177108-4c361980-e68a-11e9-9b90-5ca4e8e1daa1.png)

**Comment by Saviq** [comment]
Hi @jaekook can you please let us know what your host system is?

**Comment by jaekook** [comment]
Window 10 Pro, 64bit, 1903, 18362.10022

**Comment by Saviq** [comment]
Right, the same problem can be seen in some other places. I thought we had a bug for this logged but can't find it now. Thanks for letting us know?

**Comment by jfmatth** [comment]
systemctl status gives incorrect characters
