### ISSUE TITLE
Lost all multipass instances after Windows update (Win10 Pro)

### ISSUE THREAD

**Issue by markl11** [canonical/multipass#1119]
I was prompted to update my Windows 10 laptop and after the update everything seems to be fine except multipass. I have lost all the instances:

![image](https://user-images.githubusercontent.com/38077229/66398097-15873880-e9d5-11e9-976b-b84302217b23.png)

I can actually still see all the VMs in Hyper-V manager:

![image](https://user-images.githubusercontent.com/38077229/66399890-53399080-e9d8-11e9-9f7a-c446839c70d8.png)

If I compare my current windows configuration (on the left) compared with that in the 'windows.old' folder (on the right) then I see that a few files and folders seem to have been dropped during the upgrade (unless I am wrong):

![image](https://user-images.githubusercontent.com/38077229/66398757-3f8d2a80-e9d6-11e9-8a51-9491fcb324f1.png)

Any ideas how I can resolve this - can I just copy the missing folders to my current config? This is pretty urgent so any help much appreciated.

**Comment by ricab** [comment]
Hi @markl11 sorry you're experiencing this. Could you please try the following?

1. copy the new `…/AppData/Roaming/multipassd` folder somewhere safe
2. open windows service manager and stop the multipass service
3. replace the `multipassd` folder above with your old copy (the backup you mentioned)
4. restart the multipass service in the windows service manager
5. `multipass list`

**Comment by ricab** [comment]
It seems windows updates are prone to deleting files, in particular in the profile tree. These references may be relevant for anyone stumbling on this:

- https://forum.duplicati.com/t/config-gone-after-windows-10-1903-update/7319
- https://www.forbes.com/sites/gordonkelly/2018/10/06/microsoft-windows-10-update-lost-data-upgrade-windows-7-windows-xp-free-upgrade/
- https://www.makeuseof.com/tag/recover-lost-windows-10-user-profile/
- https://answers.microsoft.com/en-us/windows/forum/all/last-windows-10-update-deleted-most-of-my-files/19af7f62-7205-4cbf-b150-006ded5b47ac

I hope replacing the folder with the one in `C:\Windows.old` fixes it for you.

**Comment by Saviq** [comment]
Jeez… I wonder how we can protect against that. Maybe we should move to `C:\ProgramData` instead…

**Comment by markl11** [comment]
Unfortunately, that didn't fix the issue:

![image](https://user-images.githubusercontent.com/38077229/66413585-92271080-e9ef-11e9-8072-8271ce797a25.png)

**Comment by markl11** [comment]
If I look in Hyper-V Manager, the instances are in a 'saved' state. If I try to start them in Hyper-V Manager I get the following. Is the problem (not being able to connect/start the instances) related to a permissions issue on the copied 'multipassd' folder??

![image](https://user-images.githubusercontent.com/38077229/66414191-d4048680-e9f0-11e9-83f6-a17ae60f900f.png)

**Comment by markl11** [comment]
I tried removing the 'read-only' permissions on the 'vault' sub-folder and I am now able to start and connect to the instances - or at least one I have tried (wasn't possible before).

![image](https://user-images.githubusercontent.com/38077229/66414570-97855a80-e9f1-11e9-87e7-898e6aca830e.png)

**Comment by ricab** [comment]
Great that you managed that @markl11! 

For curiosity, could you please let us know what was the owner and permissions of the `vault` folder  in `Windows.old` and after your copy? I suspect one of the following happened, and would like to understand which:
- maybe windows removed write permissions on Windows.old?
- maybe the files you copied from Windows.old got owned by your user and then multipass/hyper-v could not write to them?

If the second explanation is the correct one, you could also fix this by restoring ownership to the SYSTEM user.

**Comment by Saviq** [comment]
Wow that's a lot of instances…

@markl11 really glad you got this going, would you care documenting the process for posterity at our discourse in the [documentation category](https://discourse.ubuntu.com/c/multipass/doc)?

**Comment by markl11** [comment]
Ok - got them all going now - permissions were actually a red herring. So this is how to resolve the issue of the missing instances and non starting instances after a windows update (at least on my Win 10 Pro machine):

1. copy the 'multipassd' folder from 'windows.old' roaming profile to the new 'windows' folder

2. at this point the instances will be visible with 'multipass list' but not startable

3. right click on the instance in Hyper-V Manager which are in a 'saved' state & click 'revert' which will error out, but will change the state to 'off'

4. right click again on the instance in Hyper-V Manager and click 'connect' then 'Start' & 'Continue' - it will error out but begin a merge process which will succeed (at least it did in my case)

5. At this point the instance will be in an 'off' state and will be startable with 'multipass start'

6. repeat steps 3-4 for each instance in a 'saved' state in Hyper-V Manager

7. Happy days :-)

**Comment by ricab** [comment]
@markl11 glat it worked out for you, thanks a lot for all the feedback and those instructions!

**Comment by richtera** [comment]
Argh this happened with the latest version again, but this time it seems to have removed the VM from Hyper-V completely since it didn't allow reinstall without uninstalling first.

**Comment by daviamiel** [comment]
Hello and thank you for opening this issue.
I have same experience of you, the latest 2004 windows update delete all my instances.
Hopefully i'm a beginner on Multipass and my work dirs are on my Host hard drives using the "mount" command.

**Comment by cloudbear** [comment]
I've just experienced this issue upgrading to Windows 10 Pro 2004. There are no multipass folders in the AppData folders in `C:\Windows.old` to copy from. The machines are visible in Hyper-V Manager but will not start. One is 'saved' and the other is 'off'.

The 'saved' machine gives the following error on starting (translated from German; {} are mine):

> **Failure in the attempt to start the selected virtual machine.**
>
> Failure in the restoration of "data".
>
> Microsoft Emulated IDE Controller (Instance-ID: {uuid}): Failure in the restoration: No vendor was found supporting virtual volumes for the given file.
>
> Failure in the opening of the system.
> "C:\Windows\Sys...\ubuntu-20.04-server-cloudimg-amd64_{uuid}.avhdx": No vendor was found supporting virtual volumes for the given file.
>
> Failure in the configuration of
> "C:\Windows\Sys...\ubuntu-20.04-server-cloudimg-amd64_{uuid}.avhdx": The {memory/store}, in which the virtual disk is, does not support the release of virtual disks.
>
> The file
> "C:\Windows\Syst...\ubuntu-20.04-server-cloudimg-amd64_{uuid}.avhdx": of type "Hard Disk Image" is not available.

The 'off' machine gives the following error when started (translated from German, {} are mine):

> **Failure in the attempt to start the selected virtual computer.**
>
> Failure in the checkpoint processing.
>
> The checkpoint cannot be created.
>
> Failure in the checkpoint processing for "laravel". (ID of the virtual machine: {uuid})
>
> Failure in the delete of the AVHD-File ...\ubuntu-18.04-server-cloudimg-amd64-{uuid}...
>
> "laravel": The {memory/store} required for the checkpoint "C:\Windows\System3...\ubuntu-18.04-server-cloudimg-amd64.vhdx" cannot be created with the virtual disk:
> The system cannot find the given path. (0x80070003) (ID of the virtual machine: {uuid}).

**Comment by cloudbear** [comment]
My mistake. I didn't realise there was an AppData folder inside system32. I copied `multipassd` from there and now the machines are listable and start without issue.

**Comment by devcircus** [comment]
Thanks @markl11 for the info. Was panicking for a while. Worked for me as well. For some reason, the first time I ran ```multipass start```, it timed out, but started successfully anyway. 🤷‍♂️

**Comment by rogerjbos** [comment]
Glad this solution worked for everyone else, but it doesn't work for me.  I fail at step 1: copy the 'multipassd' folder from 'windows.old' roaming profile to the new 'windows' folder
My folder C:\Windows.old\Users\bosr\AppData\Roaming doesn't have a folder for multipassd. The only folder in that location is Microsoft.  It is really disappointing to spend a lot of time to build some servers just to see them disappear.

**Comment by townsend2010** [comment]
Hey @rogerjbos,

Ugh, sorry this happened.  `multipassd` runs under the Adminstrator's account, so the instances will not be in your user's file hierarchy.  I've yet to see this issue myself, but perhaps the `multipassd` folder is located in `C:\Windows.old\System32\config\systemprofile\AppData\Roaming\`.  Hopefully that helps.

**Comment by rogerjbos** [comment]
Thanks @townsend2010 for the reply.  The multipassd folder was in this folder (with an extra WINDOWS from yours):
C:\Windows.old\WINDOWS\System32\config\systemprofile\AppData\Roaming\multipassd 
I already started the re-build, but from my reading I decided to re-install multipass and set the MULTIPASS_STORAGE to my G: drive.  Do you think that will prevent this from happening again?  Thanks again and with this exception I am really liking multipass.

**Comment by townsend2010** [comment]
Hey @rogerjbos,

Ok, good to know the correct full path.  Yes, setting `MULTIPASS_STORAGE` *should* avoid this issue in the future.  I hope it all works out for you and good luck!

**Comment by realet1337** [comment]
Same problem here. Upgraded to windows 10 Home ver. 2004. Here is what I tried:

Copied `C:\Windows.old\Windows\System32\config\systemprofile\AppData\Local\multipassd` to `C:\Windows\System32\config\systemprofile\AppData\Local\`

Copied `C:\Windows.old\Windows\System32\config\systemprofile\AppData\Roaming\multipassd` to `C:\Windows\System32\config\systemprofile\AppData\Roaming\`

Copied `C:\Windows.old\Windows\System32\config\systemprofile\VirtualBox VMs` to 
`C:\Windows\System32\config\systemprofile\`

After doing this, multipass has changed it's error message from saying that this instance doesn't exist to saying that I don't have access to Hyper-V (correct, as I use Windows 10 Home):

`start failed: Hyper-V is not available on this edition of Windows 10.`

I obviously don't use Hyper-V, I use VirtualBox.  `multipass list` still tells me `No instances found.` Are there any other configs that multipass is missing, maybe?

**Comment by realet1337** [comment]
Got it! Turns out that, yes, multipass was missing one more thing. Copying `C:\Windows.old\Windows\System32\config\systemprofile\.VirtualBox\` to `C:\Windows\System32\config\systemprofile` did it.

**Comment by thebalaa** [comment]
Hit this issue recently. 

After restoring the multipassd folder from Windows.old as noted above I also git the permission errors when trying to start the VM. 

I had to run the following 2 PowerShell commands to get the VM to start again:

Get VM ID
```
Get-VM 'MY-VIRTUAL-MACHINE-NAME' | Select-Object VMID
<VM_ID>
```
Fix permission issue
```
icacls "C:\PATH_TO_VHDX" /grant <VM_ID>
```

Change `MY-VIRTUAL-MACHINE-NAME` in the command above to the name of the problematic VM to get its <VM_ID>

Replace  "C:\PATH_TO_VHDX" and <VM_ID> with the appropriate values


Solution taken from Figure 6 and Figure 7  here: https://redmondmag.com/articles/2017/08/02/hyper-v-virtual-hard-disk-permission-problems.aspx

**Comment by kris7453** [comment]
I have the same problem after BSOD's. Currently I have BSOD'a from time to time, cause HyperV has a problem with some of my drivers, but there is a little problem to find newer version, especially for network card, where the producer write that they don't deliver drivers for their hardware.
There is no problem with windows update, so I don't have windows.old folder and my multipass config just disappear. I see this VM in HyperV manager, but can't see it in multipass list.
I don't know is it right or wrong, but I don't have "multipassd" folder in %appdata% folder. I have only "multipass" folder.

**Comment by townsend2010** [comment]
We've moved away from the problematic directory to one that is stable during upgrades and thus, this should not be a problem anymore.
