### ISSUE TITLE
Stopping an instance with an active mount causes multipassd to abort

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1131]
This only occurs the first time a mount is issued on a given instance.  It appears that `sshfs_server` tries to start, detects that `sshfs` is not installed in the instance and fails somewhat gracefully, ie, nothing crashes.  Then `sshfs` is installed and `sshfs_server` is then tried again.  At this point, the apparmor profile is loaded, but the somewhere during this process, it is unloaded, probably due to the first failure.

Then when the instance is stopped, it tries to unload the `sshfs_server` apparmor profile, and since it was previously unloaded, the removal fails and the code throws an exception.  This exception is not caught and so `multipassd` aborts.

There are two things here.  One is that the unload shouldn't really occur.  The second thing is that upon some research, failure to unload a profile is not considered an error.  The exception should be caught and a warning printed in the log.

I will reiterate that this only occurs the first time a mount is performed on an instance.

**Comment by townsend2010** [comment]
The issue is that the custom deleter for the the `Process` `std::unique_ptr` uses `OBject::deleteLater()`, so when `sshfs` is not found in the instance, it throws `mp::SSHFSMissingError()`, but the `unique_ptr` is not deleted until sometime later, and that is when the apparmor profile is removed.

I'm not sure how to make this happen, but the `unique_ptr` really needs to be deleted when going out of scope on error conditions within the `mp::SSHFSMounts::start_mount()` function.

**Comment by townsend2010** [comment]
Moving this to high since `multipassd` terminating because of this would cause other running instances to die when using the QEMU backend.

**Comment by Saviq** [comment]
```
$ while mp start && mp mount dev primary:dev && mp stop && mp delete -p --all; do true; done
Launched: primary
delete failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible

# vs.

$ while mp start && mp mount dev primary:dev && mp stop && mp delete -p --all; do true; done
Launched: primary
Launched: primary
Launched: primary
Launched: primary
Creating primary /^C%
```
