### ISSUE TITLE
`multipass shell` launching a VM is unexpected

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#1133]
I just typed `multipass shell` and accidentally hit Return before typing my instance name in, and was very surprised to see multipass launch a new VM. This was particularly confusing given that the short help says "Open a shell on a _running_ instance" (emphasis mine, of course), so that's what I assumed it did.

Once I'd seen this happen, I looked at the full help text, and I think we also have some confusing wording there. Specifically, "If the instance is not running, an attempt is made to start it" is inaccurate, as `multipass` did not attempt to `start` it, it instead `launch`ed a completely new VM.

**Comment by Saviq** [comment]
This is the `primary` instance (see [release notes for 0.7.0](https://github.com/CanonicalLtd/multipass/releases/tag/v0.7.0)). It's meant to be a shortcut to your default instance, which gets launched for you if you just issue a `multipass shell`.

We should probably improve the help text around it, and add a bit more feedback when first launching it.

**Comment by OddBloke** [comment]
On Tue, Oct 22, 2019 at 12:19:57AM -0700, Michał Sawicz wrote:
> This is the `primary` instance (see [release notes for
> 0.7.0](https://github.com/CanonicalLtd/multipass/releases/tag/v0.7.0)).
> It's meant to be a shortcut to your default instance, which gets
> launched for you if you just issue a `multipass shell`.

I'm unlikely to ever want a `primary` instance as an Ubuntu user (if
there's something that I just want a pet Ubuntu instance for, I have my
desktop; anything more specific and I'm going to want to choose the
Ubuntu release I launch); is there any way I can configure multipass to
disable this behaviour?

> We should probably improve the help text around it, and add a bit more
> feedback when first launching it.

Yep, to be clear, I understand why this is the behaviour; it's knowing
that this _is_ the behaviour that was missing. :)
