### ISSUE TITLE
`mount` requires a target path

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1145]
When the help states:
```
  target                           Target mount points, in <name>[:<path>]
                                   format, where <name> is an instance name, and
                                   optional <path> is the mount point. If
                                   omitted, the mount point will be the same as
                                   the source's absolute path
```

**Comment by Saviq** [comment]
This was like that since 0.7.1 at least… Sounds like we need a test…

**Comment by townsend2010** [comment]
Hmm, thinking about this some, does it really make sense to omit the target path?  We say there that it will resolve to the source's absolute path, which most times will be something like `/home/foo/blah`, but `foo` is not the user we care about in the instance.

Maybe we can try to be smart and match on `/home/foo` and replace that with `/home/ubuntu` and the rest of the path stays the same?

**Comment by Saviq** [comment]
Yeah but then we have to explain that to the users…

Maybe we default to `basename $source`?

**Comment by townsend2010** [comment]
@Saviq,

I'm not sure we can assume `basename $source`.

What if someone wanted to do something like:
`multipass mount ~/projects/foo bar:`

What we assume there?  The absolute path with be `/home/user/projects/foo` so would the source be `foo` or `projects/foo`?  This is what I meant about matching on `/home/user` and replacing with `/home/ubuntu` in order to preserve the whole path after `$HOME`.

**Comment by Saviq** [comment]
> What if someone wanted to do something like:
> `multipass mount ~/projects/foo bar:`
> 
> What we assume there? The absolute path with be `/home/user/projects/foo` so would the source be `foo` or `projects/foo`? This is what I meant about matching on `/home/user` and replacing with `/home/ubuntu` in order to preserve the whole path after `$HOME`.

I meant actual `basename` - we have to update the help one way or another if we don't think the "equal to absolute source path" makes sense. And it probably doesn't, what with Windows paths…

But `basename(source)` should be universal enough?

**Comment by townsend2010** [comment]
Oh, lol, you mean the actual `basename()` function.  Yeah, `QFileInfo` has a `baseName()` function we could use that is cross platform.  And in the help, we will note that just the source base name will be used if target is omitted.

**Comment by Saviq** [comment]
Yeah :)
