### ISSUE TITLE
multipass shell should be a login shell

### ISSUE THREAD

**Issue by simos** [canonical/multipass#115]
You can get a shell in multipass with

```
$ multipass exec myvm bash
ubuntu@myvm:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
ubuntu@myvm:~$ snap list
Name         Version  Rev   Developer  Notes
core         16-2.30  3887  canonical  core
hello-world  6.3      27    canonical  -
ubuntu@myvm:~$ hello-world
hello-world: command not found
ubuntu@myvm:~$ /snap/bin/hello-world
Hello World!
ubuntu@myvm:~$ 

```

The issue is that `multipass exec myvm bash` does not give you a login shell. A login shell is required so that /etc/profile.d/apps-bin-path.sh runs, which would set correctly the $PATH and add /snap/bin to it.

# Workaround

The workaround is to run instead the following (add -- and then --login).

```
$ multipass exec myvm -- bash --login
ubuntu@myvm:~$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ubuntu@myvm:~$ 
```

# What should happen? 

Ideally, there should be a dedicated command to get a login shell to the VM.
I suggest

```
$ multipass shell go
ubuntu@myvm:~$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ubuntu@myvm:~$ 

```

Having a `shell` subcommand would make it similar to LXD. In LXD it gives you a root login shell because LXD supports many different distributions that may not have a default non-root account.
If `multipass` is meant to ever be only for Ubuntu images, then `multipass shell myvm` should be OK to give a non-root login shell.

# References

 - [x] https://github.com/lxc/lxd/issues/4233

**Comment by Saviq** [comment]
We do have a `connect` command already:
```
$ multipass help connect
Usage: multipass connect [options] <name>
Open a prompt on the instance.
```
But we will indeed rename it to `multipass shell` to align with `lxd`.
