### ISSUE TITLE
changing number of CPUs for an instance

### ISSUE THREAD

**Issue by VasiliyS** [canonical/multipass#1158]
Is it possible to change number of CPUs available to an existing instance? What about memory?

**Comment by Saviq** [comment]
Hi @VasiliyS, I'm afraid it's not, not easily at the moment. #756 designs the experience, but it's not yet implemented.

Depending on platform, you could just edit the VM in the hypervisor (Hyper-V, VirtualBox), or stop Multipass and edit its instance database.

Let us know what your environment is and we can guide you there :)

**Comment by VasiliyS** [comment]
@Saviq - Thank you. I'm on a Mac. Where can I find the instance database?

**Comment by Saviq** [comment]
@VasiliyS here are the steps:

```bash
# stop multipassd
sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist

# edit /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
# you'll need sudo for that

# start multipassd again
sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
```

The format should be quite easy to grok:
```json
{
    "primary": {
        "deleted": false,
        "disk_space": "5368709120",
        "mac_addr": "52:54:00:5c:f4:14",
        "mem_size": "1073741824",
        "metadata": {
        },
        "mounts": [
        ],
        "num_cores": 1,
        "ssh_username": "ubuntu",
        "state": 0
    }
}
```

You want to edit `num_cores` for CPU and `mem_size` for memory :)

**Comment by VasiliyS** [comment]
@Saviq - Just tried it. The instance doesn't start - the cli times out ("timed out waiting for response").  ``` multipass info``` tells me that the state is unknown and the json file has state set to 8. ```multipass stop``` ends with "process error occurred Crashed". The state key in the json file is now 0.
<br>
After stopping the ```multipassd```, editing the ```num_cores``` key value back to 1 and re-starting the daemon, the instance starts fine.

**Comment by Saviq** [comment]
@VasiliyS hmm can you look in `/Library/Logs/Multipass/multipassd.log` for any errors? Does a new instance with 2 CPUs (`multipass launch --cpus 2`) work fine?

**Comment by VasiliyS** [comment]
@Saviq  - I was able to create a new instance with 2 cpus, worked fine.

I'm attaching 2 files with excerpts from the log. One where I've edited the cpu key to 2 and the instance  doesn't start. 
[2_cpus_doesnt_start.log](https://github.com/CanonicalLtd/multipass/files/3796082/2_cpus_doesnt_start.log)

The second one where I've changed the setting back to 1 cpu and it works. 
[1_cpu_starts.log](https://github.com/CanonicalLtd/multipass/files/3796081/1_cpu_starts.log)

**Comment by VasiliyS** [comment]
@Saviq - Update! 
I've just tried something. The instance actually starts fine, it's the cli that timeouts. 
```multipass start``` exits with a timeout message, but I'm still able to ssh into the instance, etc.
<br>
The weird thing is , now even the instance that I've ```launch```'d with ```--cpus  2``` option from scratch doesn't start normally (i.e. ```multipass start``` timeouts), but the instance actually works fine. That gave me an idea to try again with editing the ```num_cores``` key and ignore the timeout message.  Now that I know where the id_rsa is, I can login directly even when ```multipass shell/info/etc``` don't work normally. Oh well...

**Comment by townsend2010** [comment]
Hi @VasiliyS,

It looks like you are hitting #1122 when it's using 2 cpu's.  The next version of Multipass has a fix for that.  We have a release candidate for 0.9 up and can be found at https://github.com/CanonicalLtd/multipass/releases/download/v0.9.0-rc/multipass-0.9.0-rc.425+g37fa4305.mac-Darwin.pkg if you are interested.

**Comment by VasiliyS** [comment]
Hi @townsend2010  - thanks! The RC works just fine.
I guess now my original request has been met. I'm now able to change the number of CPUs  for an existing instance.<br>
Would be great to add a command to update the instance configuration via the cli, though. It's probably a common need, especially if one uses ```multipass``` to create a K8S machine and then discovers that the original resources are not sufficient.

**Comment by Saviq** [comment]
@VasiliyS glad you got it going. Yes, we'll allow changing the number of CPUs in due course :)

**Comment by sourcedelica** [comment]
And memory please.

**Comment by kramik1** [comment]
Just to save some people some time, the below is for Ubuntu 19.10.
 
sudo systemctl stop snap.multipass.multipassd.service 
sudo vi /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json 
sudo systemctl start snap.multipass.multipassd.service

**Comment by denizzzka** [comment]
@kramik1 these settings will be overwritten by previous values if snapcraft clean will be called

**Comment by denizzzka** [comment]
I drive into same problem with RAM setting: it is just too low for my snap (only 4Gb) and I can't to build anything.

**Comment by townsend2010** [comment]
Hi @denizzzka,

There are some Snapcraft environment variables you can set to tweak memory, CPU count, and disk size.  They are:
```
SNAPCRAFT_BUILD_ENVIRONMENT_CPU
SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY
SNAPCRAFT_BUILD_ENVIRONMENT_DISK
```

Hope this helps!

**Comment by denizzzka** [comment]
Thanks @townsend2010 

I tried this variables. Looks like it work inside of multipass VM, but VM itself still uses 2 cores and 2Gb of RAM (I checked this by `atop` utility)

**Comment by townsend2010** [comment]
Hey @denizzzka,

Hmm, it's not _supposed_ to work that way. :confused:

I'll run some experiments in a while and if it's not working as it should, I'll ping the Snapcraft folks as they are the ones responsible for setting up these Multipass instances.

**Comment by denizzzka** [comment]
Thanks!

Please note that I did not change /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json settings file, because this makes no sense - it is automatically overwritten every time if snapcraft repository is cleaned

**Comment by townsend2010** [comment]
Hey @denizzzka,

It seems to be working as expected here.  Here's what I did on my Ubuntu host machine:
```
$ SNAPCRAFT_BUILD_ENVIRONMENT_CPU=4 SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY=8G snapcraft
Launching a VM.
'SNAPCRAFT_BUILD_ENVIRONMENT_CPU' was set to '4' in the environment. Changing the default allocation upon user request
'SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY' was set to '8G' in the environment. Changing the default allocation upon user request
...
```
I can clearly see the snapcraft instance used to build my snap is now using 4 cores and has 8GB allocated to it.  Did you `snapcraft clean` and ensure the instance was gone via `multipass list` before trying the environment variables?

**Comment by denizzzka** [comment]
Offtopic:
I removed everything from my Debian and start again. After snapcraft was installed I faced with:
```
$ snapcraft
cannot snap-exec: cannot exec "/snap/snapcraft/4126/usr/bin/python3": no such file or directory
```
It worked previously. The experiments are postponed indefinitely.

**Comment by denizzzka** [comment]
Ok, I sucessfully reinstalled it. Works! Thanks @townsend2010 !

**Comment by acefei** [comment]
is there any effect way on windows?
The following steps (run as Administrator) are what I did, but the modification doesn't work, the VM started as before.
```
multipass.exe stop --all
Stop-Service -Name Multipass
notepad.exe 
 C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\multipassd-vm-instances.json
Start-Service -Name Multipass
multipass.exe start --all
```
multipass version
```
multipass  1.1.0+win
multipassd 1.1.0+win
```

**Comment by Saviq** [comment]
@acefei on Windows you can go to the Hyper-V manager (or `psexec.exe -s -i VirtualBox`, if using that) and change it there.

**Comment by acefei** [comment]
Thanks @Saviq , that works. 
I wanted to automate it as I did on Linux.

**Comment by Saviq** [comment]
@acefei you can do that with [PowerShell's `Set-VMProcessor` cmdlet](https://docs.microsoft.com/pl-pl/powershell/module/hyper-v/Set-VMProcessor).

**Comment by huangxuankai** [comment]
I try two solution to chage cpu, mem, disk space, learn from @kramik1 
host: ubuntu 16.04
guest: ubuntu 18.04
snap multipass: 1.2.0

```
sudo systemctl stop snap.multipass.multipassd.service

// here i only change memory and cpu 
sudo vi /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json
sudo qemu-img resize /var/snap/multipass/common/data/multipassd/vault/instances/instance_xxx/instance_xxx.img +10G

sudo systemctl start snap.multipass.multipassd.service

multipass start instance_xxx
// here runing ok
multpass info instance_xxx

```
but key `disk_space` in file `multipassd-vm-instances.json` remain not change, I don't know if there will be problems in the future

another solution
i stop all instance on multpasss
set `sudo multipass set local.driver=libvirt `
 then use virt-manager to change cpu and mem
disk space change use `sudo qemu-img resize /var/snap/multipass/common/data/multipassd/vault/instances/instance_xxx/instance_xxx.img +10G`
finally, start instance, and it run well

**Comment by santiagomoneta** [comment]
Can anyone share some light on how to do this on MacOS (Catalina). Thanks

**Comment by Saviq** [comment]
Hi @santiagomoneta, one of the first comments (https://github.com/canonical/multipass/issues/1158#issuecomment-548073024) has the steps.

**Comment by PaulFish-Radius** [comment]
I'm attempting steps on comment: https://github.com/canonical/multipass/issues/1158#issuecomment-548073024 

Running below per step 2:
`sudo vim /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`

Results in opening a blank file - do I have the command right to edit this file? Seems I can't get to this directory correctly with this command. 

OS: MacOS Catalina

**Comment by Saviq** [comment]
> `sudo vim /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`

You either need to escape the space (`Application\ Support`), or put the whole path in quotes.

**Comment by sionsmith** [comment]
The file on my machine was:
`sudo vi /var/root/Library/Application\ Support/multipassd/virtualbox/multipassd-vm-instances.json`

**Comment by magmine** [comment]
@Saviq  for your proposition in this comment: https://github.com/canonical/multipass/issues/1158#issuecomment-599195297
HyperV manager gave me an error stating that the machine I'm trying to modify can't be found, same in the HyperV manager GUI.

I created the instance using `multipass launch --name machineName`

**The error I got**
`+ Set-VMProcessor ansiblePrimary -Count 2 -Reserve 5 -Maximum 75
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VMProcessor], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMProcessor`

**Comment by Saviq** [comment]
@magmine what does the Hyper-V Manger application show?

**Comment by magmine** [comment]
@Saviq  it shows: **No virtual machine detected** + and action panel at the right of the window

**Comment by Saviq** [comment]
@magmine and you have the instance running under `multipass list`? Are you not [using the VirtualBox driver](https://multipass.run/docs/using-virtualbox-in-multipass-windows), by chance?

**Comment by magmine** [comment]
@Saviq no I'm using VirualBox driver, and `multipass list` shows the instance  running, I did also manipulated the instance directly by running `multipass shell instanceName`

**Comment by Saviq** [comment]
@magmine then you want to follow https://multipass.run/docs/using-virtualbox-in-multipass-windows and modify the instance with either VBoxManage or the VirtualBox GUI. The `Set-VMProcessor` cmdlet only works for Hyper-V instances.

**Comment by magmine** [comment]
Thank you @Saviq  that was helpful

**Comment by magmine** [comment]
@Saviq 
Now I have two other problems:
- The first: trying to configure the multipass machine on VirtualBox GUI prompts me again and again to an alert stating that the state of the current machine has changed.
- The Second: I can't restart the multipass virtual machine using multipass (currently it is suspended) even though I stopped `PsExec.exe`

**Comment by hemna** [comment]
Seems like there should be a much easier way to do this from the multipass command line itself.  
Like,
multipass stop <instance>
multipass update -c 4 <instance>
multipass start <instance>

**Comment by Saviq** [comment]
@hemna we have something like this scheduled for the near months. See #756 for details of what we want to go for.

**Comment by mconner** [comment]
@Saviq 

If we modify the cpu or memory in Hyper-V Manager, the values in multipassd-vm-instances.json are not updated.  Should we edit it to match?

**Comment by Saviq** [comment]
@mconner for Hyper-V and VirtualBox there's no need - they hold their own VM configuration.

**Comment by Saviq** [comment]
FWIW we have scheduled basic instance modification this cycle, we'll be starting on it soon.

**Comment by oldthreefeng** [comment]
Niubility...

**Comment by tuxerrante** [comment]
> 
> 
> @magmine then you want to follow https://multipass.run/docs/using-virtualbox-in-multipass-windows and modify the instance with either VBoxManage or the VirtualBox GUI. The `Set-VMProcessor` cmdlet only works for Hyper-V instances.
> 
> Note that when you can't keep the GUI open, otherwise Multipass will have trouble managing the instance (VirtualBox only allows a single entity to manage VMs at any time).

After switching to VBox I can't see them anymore, nor in  multipass list nor in VBox GUI, even after other commands of that tutorial.
Should I delete them and recreate them with the VBox driver?
Can I choose the image directory such that I can manually import them in VBox?

![immagine](https://user-images.githubusercontent.com/8364469/131461404-4c56a957-df91-49d4-987a-ee552ac3c485.png)

I was able to do it through the Hyper-v manager 
![immagine](https://user-images.githubusercontent.com/8364469/131467995-499030db-d700-4a41-8901-e71388f5e1f8.png)

**Comment by matejk** [comment]
> > `sudo vim /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`
> 
> You either need to escape the space (`Application\ Support`), or put the whole path in quotes.

With multipass 1.8.1 on macOS Monterey the configuration file is

`/var/root/Library/Application\ Support/multipassd/qemu/multipassd-vm-instances.json`

**Comment by sijakret** [comment]
For mac OS this is what helped me: https://www.atpeaz.com/change-multipass-instance-memory-and-cpu-allocation-after-launch/

it was important to unload the multipass service first:
```bash
sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
```
then modify `multipassd-vm-instances.json`

> @VasiliyS here are the steps:
> 
> ```shell
> # stop multipassd
> sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
> 
> # edit /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
> # you'll need sudo for that
> 
> # start multipassd again
> sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
> ```
> 
> The format should be quite easy to grok:
> 
> ```json
> {
>     "primary": {
>         "deleted": false,
>         "disk_space": "5368709120",
>         "mac_addr": "52:54:00:5c:f4:14",
>         "mem_size": "1073741824",
>         "metadata": {
>         },
>         "mounts": [
>         ],
>         "num_cores": 1,
>         "ssh_username": "ubuntu",
>         "state": 0
>     }
> }
> ```
> 
> You want to edit `num_cores` for CPU and `mem_size` for memory :)

then restart
```bash
sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
```

otherwise it would always reset the changes I made. (`multipass stop` was _not_ enough in my case!)

**Comment by jbosse** [comment]
I can't find `multipassd-vm-instances.json` anywhere on my M1 Mac.

**Comment by Saviq** [comment]
@jbosse it should be `/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json` - if it doesn't exist… did you launch any instances?

**Comment by jbosse** [comment]
@saviq Thank you. Mac really doesn't want you to see it in the finder or open it in VSCode. I could only make it open in nano. I had given up though and just made a new instance passing the --mem  and --cpus options I wanted.

**Comment by pauljsymonds** [comment]
> @VasiliyS here are the steps:
> 
> ```shell
> # stop multipassd
> sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
> 
> # edit /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
> # you'll need sudo for that
> 
> # start multipassd again
> sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
> ```
> 
> The format should be quite easy to grok:
> 
> ```json
> {
>     "primary": {
>         "deleted": false,
>         "disk_space": "5368709120",
>         "mac_addr": "52:54:00:5c:f4:14",
>         "mem_size": "1073741824",
>         "metadata": {
>         },
>         "mounts": [
>         ],
>         "num_cores": 1,
>         "ssh_username": "ubuntu",
>         "state": 0
>     }
> }
> ```
> 
> You want to edit `num_cores` for CPU and `mem_size` for memory :)

How would I do this on Ubuntu?

> ```shell
> # stop multipassd
> sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
> 
> # edit /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
> # you'll need sudo for that
> 
> # start multipassd again
> sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
> ```
>

**Comment by Saviq** [comment]
Anyone stumbling here, you can now try the implementation in action in #2353, with snaps under `edge/pr2353` channel and [Windows](https://github.com/canonical/multipass/pull/2353/checks?check_run_id=5887563474) and [macOS](https://github.com/canonical/multipass/pull/2353/checks?check_run_id=5887568801) packages.

**Comment by muhammad-asn** [comment]
Thank you this solution is works on macbook PRO

**Comment by lulor** [comment]
@Saviq Thank you for the update, it works great!
May I ask why both the number of cores and the memory can only be increased? It makes perfect sense for the disk, but to me it's less obvious for the other two parameters

**Comment by Saviq** [comment]
@lulor the primary reason are [blueprints](https://github.com/canonical/multipass-blueprints), which declare the minimum memory and CPU cores meaningful for a particular use case. That said, we're reconsidering whether we should be that limiting, especially that if you make a mistake and give too much, there's currently no way back.

**Comment by lulor** [comment]
@Saviq I see, thank you for the explanation

**Comment by almontes1987** [comment]
I got using another way. If you're using the VirtualBox driver, open the VirtualBox with the root account. There will be a new tab for Multipass with the instance alreade created. Just turn off the multipass instance, change the setting on the VirtualBox windows and then turn on your multipass instance again.

**Comment by daviewales** [comment]
> ```shell
> # stop multipassd
> sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
> 
> # edit /var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
> # you'll need sudo for that
> 
> # start multipassd again
> sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
> ```


How would one do this on Windows?

**Comment by sebmartin** [comment]
> I got it using another way. If you're using the VirtualBox driver, open the VirtualBox with the root account. There will be a new tab for Multipass with the instance already created. Just turn off the multipass instance, change the setting on the VirtualBox window and then turn on your multipass instance again.

FYI you can launch VirtualBox with the root account on macOS by running the following command in Terminal:

```
sudo /Applications/VirtualBox.app/Contents/MacOS/VirtualBox
```

**Comment by ricab** [comment]
@almontes1987, @daviewales, @sebmartin, `multipass set local.<instance>.cpus=<ncpus>` should be enough to get you what you need; `multipass get --keys` shows instance attributes that can be changed that way (along with other settings). Let us know if you have problems with that.
