### ISSUE TITLE
Disable interactivity when reading content from stdin

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1162]
> The problems you refer to were around the metrics question being asked, which should never be shown if we're not on a tty, or when there is anything to be read from stdin, because how do we differentiate between cloud-init being read and the answer to the question. Reading stdin and interactivity are conflicting. 

Which we don't ensure today:
```
$ multipass launch --cloud-init -
#cloud-config
One quick question before we launch … Would you like to help                    
the Multipass developers, by sending anonymous usage data?
This includes your operating system, which images you use,
the number of instances, their properties and how long you use them.
We’d also like to measure Multipass’s speed.

Creating guaranteed-goat -^C
```

We need a generic mechanism of changing the terminal mode to non-interactive if we're to read any data in from it.

_Originally posted by @Saviq in https://github.com/CanonicalLtd/multipass/pull/1161/review_comment/create_

**Comment by ricab** [comment]
But this isn't a problem unless #1161 goes in, right? Am I missing something?

**Comment by ricab** [comment]
Or does this affect other commands already?

**Comment by Saviq** [comment]
It is a problem (not a big one, it just displays the question and skips it because stdin already EOF'd).

Not affected by #1161 really.
