### ISSUE TITLE
[daemon] long image preparation gets canceled

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1168]
When the image preparation stage (e.g. conversion after download) takes too long, the process gets interrupted, but the launch process continues:
```
[warning] [Qt] QProcess: Destroyed while process ("/Library/Application Support/com.canonical.multipass/bin/qemu-img") is still running.
```

And the launch fails, including subsequent tries, because the prepared image is wrong / doesn't exist:
```
$ multipass launch snapcraft:core18 --disk 10G
launch failed: The following errors occurred:                                   
Instance stopped while starting
```

**Comment by townsend2010** [comment]
Looking at that warning, I think this occurred on a Mac, right?  If so, I think this is during the `convert` phase, which only waits 30 seconds for the process to finish.  I think it's safe to pass `-1` to `waitForFinished()` here since the risk of `qemu-img` hanging seems very, very low to me.
