### ISSUE TITLE
Command Line option to change instance launch timeouts

### ISSUE THREAD

**Issue by jaaaco** [canonical/multipass#1175]
It would be nice if we had an option to change or disable `up_timeout` and `cloud_init_timeout`.

In my case (MacOS Catalina) hardcoded timeouts don't allow me to start an instance with 20G disk nor with long running cloud-init script (installing and configuring microk8s).

https://github.com/CanonicalLtd/multipass/blob/459912a9375851bbca23c5bbd602c384dd4d4386/src/daemon/daemon.cpp#L77

https://github.com/CanonicalLtd/multipass/blob/459912a9375851bbca23c5bbd602c384dd4d4386/src/daemon/daemon.cpp#L78

**Comment by Saviq** [comment]
Hi @jaaaco we've designed a behaviour for longer waits in #1039; as for the image size we're fixing the timeout to 5m, that should be plenty of time but also not run away in the end.

We'll probably also allow any hard timeouts to be configured through #756.

**Comment by Saviq** [comment]
This is implemented with `launch --timeout` now.
