### ISSUE TITLE
console: </dev/null isn't always handled correctly

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1180]
I think the following is related. The standard way to prevent programs expecting data from stdin from blocking is to add a redirect from `/dev/null`, like this:

```
$  multipass exec testvm cat
<blocks>

$  multipass exec testvm cat </dev/null
$ # doesn't block
```

however `</dev/null` redirects behave in unexpected ways in multipass, for example:

```shell
$ multipass exec testvm noexistent # works as expected
bash: noexistent: command not found

$ multipass exec testvm noexistent </dev/null
<blocks with 100% CPU usage>

$ multipass exec testvm wget
wget: missing URL
[expected output]

$ multipass exec testvm wget </dev/null
<blocks with 100% CPU usage, the same happens with curl>

$ multipass exec testvm true </dev/null # works as expected
$ multipass exec testvm false </dev/null # works as expected
```

_Originally posted by @paride in https://github.com/CanonicalLtd/multipass/issues/667#issuecomment-509710164_

**Comment by townsend2010** [comment]
After some analysis, this only happens if any output is pushed through on `stderr`.  It seems that gets hung up in `libssh` and is never printed out and libssh gets in a loop picking up the `eof` event, but never handles the `stderr` output.

**Comment by paride** [comment]
Thanks @townsend2010 for promoting my comment to an issue of its own :) Do you think this is an upstream bug in `libssh`?

**Comment by townsend2010** [comment]
@paride,

At this point, I believe it is a `libssh` issue, but I need to dig some further to see if there is something I'm missing in how we are handling this.
