### ISSUE TITLE
[Windows 10 build 1809] error: invalid arch-independent ELF magic

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/multipass#1193]
Hi, 

Opening this bug to track and provide a record of work-arounds in Windows 10.

Bug Description:

When creating multipass VMs in Windows 10 build 1809 an error is encountered which forces the VMs into grub rescue with error:

![image](https://user-images.githubusercontent.com/7092570/69650760-fd43a980-1066-11ea-8e34-f02ce52c15f7.png)

Workarounds:

- Upgrading to Windows 10 Build 1909 fixes this issue.

Cheers

**Comment by townsend2010** [comment]
This is quite out of date now and not necessary to document.
