### ISSUE TITLE
Can't load libvirt.so

### ISSUE THREAD

**Issue by cpaelzer** [canonical/multipass#1194]
Hi,
I recently used multipass with libvirt

    $ sudo multipass set local.driver=libvirt

But today things fail for me with the following:

> $ multipass launch -v
> [2019-11-28T13:11:43.719] [warning] [libvirt-factory] Failed to open the libvirt object: libvirt.so: cannot open shared object file: No such file or directory
> 
> launch failed: The libvirt library is not loaded. Please ensure libvirt is installed and running.

I'm on
multipass             0.10.0-dev.416+g73561b3     1391   edge      canonical*          classic

I'm not sure what things are about, what would be the debug data that you need?

**Comment by ricab** [comment]
Hi @cpaelzer, thanks for pointing that out. We've recently moved to loading the host's libvirt (see #1164 for why). Could you please check if the following is enough to make it work for you?

- `apt install libvirt-bin` before disco
- `apt install libvirt-daemon-system` from disco on

We'll need to update our docs to add this and remove the build dependency.

**Comment by Saviq** [comment]
@ricab we can't rely on anything in the system - if we're missing libvirt.so, we need to ship it with the snap. When we go strict, the system's `libvirt.so` won't be available, since our rootfs will be the `core18` snap.

**Comment by ricab** [comment]
Hmm ok, I thought this was an exception to that for now.

**Comment by cpaelzer** [comment]
Hi,
I certainly have libvirt installed, see

```
$ apt-cache policy libvirt-daemon-system
libvirt-daemon-system:
  Installed: 4.0.0-1ubuntu8.13
  Candidate: 4.0.0-1ubuntu8.13
  Version table:
     4.0.0-1ubuntu8.14 400
        400 http://de.archive.ubuntu.com/ubuntu bionic-proposed/main amd64 Packages
 *** 4.0.0-1ubuntu8.13 500
        500 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     4.0.0-1ubuntu8.12 500
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     4.0.0-1ubuntu8 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

And yes, since multipass used the hosts libvirt I began to like it as I often discussed with the Team that was one of the main inhibitors before.

I didn't realize you had issues with libssh but yeah, loading a hosts .so seem to randomly ask for trouble.

**Comment by Saviq** [comment]
We have it in the snap, FWIW:
```
 ~  find /snap/multipass/current/ -name libvirt*  
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt-admin.so.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt-admin.so.0.4000.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt-lxc.so.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt-lxc.so.0.4000.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt-qemu.so.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt-qemu.so.0.4000.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt.so.0
/snap/multipass/current/usr/lib/x86_64-linux-gnu/libvirt.so.0.4000.0
/snap/multipass/current/usr/share/doc/libvirt0
```

But we're using the wrong name, without SOVERSION. What really made this work for us was `libvirt-dev` - @cpaelzer installing that should make it work for you again.

**Comment by cpaelzer** [comment]
Checked:

    `$ sudo snap refresh multipass --channel edge/pr1195`

Working again for me - thanks
