### ISSUE TITLE
Document how to change the upstream DNS server used by dnsmasq

### ISSUE THREAD

**Issue by aidanharris** [canonical/multipass#1205]
Using the snap on Ubuntu, dnsmasq wasn't using my statically configured DNS server (I don't know what it was using but it doesn't seem to obey statically configured addresses configured via NetworkManager or `/etc/resolv.conf`). This is important to me because I have my own local mirror of the Ubuntu Archives for speedy package downloads.

The fix was to add `server=192.168.0.XX` to `/etc/dnsmasq.conf`.

This works but also seems wrong (If I had a local installation of dnsmasq the snap could end up using the wrong configuration because it shares `/etc` with the host). I think it would make more sense to have a file in `$SNAP_COMMON` that dnsmasq uses for extra configuration if it's present.

Before I went down the rabbit-hole of configuring dnsmasq I initially tried to change the VM's DNS using cloud-init (https://cloudinit.readthedocs.io/en/latest/topics/examples.html#configure-an-instances-resolv-conf) but couldn't get that to work. Assuming this is supposed to work it would be great if someone who knows more about cloud-init than me could verify that this works correctly with the Ubuntu images.

**Comment by Saviq** [comment]
Hi @aidanharris, it should be relatively easy to point `dnsmasq` at a custom file indeed, care to have a stab at it?

The process arguments are defined in [`dnsmasq_process_spec.cpp#L37`](https://github.com/CanonicalLtd/multipass/blob/master/src/platform/backends/qemu/dnsmasq_process_spec.cpp#L37).

**Comment by krisstern** [comment]
Hi I would like to work on this issue @Saviq Would that be okay?

**Comment by Saviq** [comment]
Hi @krisstern, of course! Let us know please how you'd like to approach this and how we can help :)

**Comment by krisstern** [comment]
Sure @Saviq! Was working on an issue from the `microk8s` repo which got me started on `multipass`. Let me study the problem a bit more in depth before getting back to you about my planned approach, likely over the next few days. 😀

**Comment by krisstern** [comment]
Hi @Saviq! I think I will follow the plan as suggested and outlined by you in https://github.com/canonical/multipass/issues/1205#issuecomment-562115781 in a few steps: 

1. Use Qt's `QStandardPaths` to locate the path to the file in the `${XDG_DATA_HOME}/dnsmasq.d` directory as suggested.
2. Point `dnsmasq` to the custom config file in the above directory. 
3. Will need to implement some logic to also look in several places for the IP, including also `/etc/resolv.conf` and `/etc/dnsmasq.conf`. 

These should all be handled in the context of the `dnsmasq_server.cpp` file referred to in the same comment. BTW, there is a new link to the [dnsmasq_server.cpp](https://github.com/canonical/multipass/blob/main/src/platform/backends/qemu/linux/dnsmasq_server.cpp) file in the repo, as the previous/above link is now broken due to a change in the default branch name. 

If there is any fallacy in my plan please do not hesitate to point these out to me. Appreciate it!

**Comment by krisstern** [comment]
@Saviq I got a question though which is why do we use `${XDG_DATA_HOME}` for the directory containing `dnsmasq.d` subdirectory? Sorry if it seems like a rookie question.

**Comment by Saviq** [comment]
Hi @krisstern, it's just a choice allowing us to be contained and not pollute / get polluted. It could've been any random location, but that's an established pattern and allows us to just use [QStandardPaths](https://doc.qt.io/qt-5/qstandardpaths.html) in all environments.

**Comment by krisstern** [comment]
Now I see. Thanks for the explanation! Let me prepare a PR for this issue now.

**Comment by krisstern** [comment]
Hi @Saviq I have been studying the [Qt5 StandardLocation enum table](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum), and wondering if `QStandardPaths::writableLocation` is the most suitable type to use for the `QStandardPaths::locate()` member function I think is the most suitable for this use case to find the config file. Any suggestion(s)?

**Comment by krisstern** [comment]
Also, I have a feeling that the line(s) https://github.com/canonical/multipass/blob/a1ea65fb63184fc778e277d3c9e2920ef2a9fb3d/src/platform/backends/qemu/linux/dnsmasq_process_spec.cpp#L56-L57 is not working as intended.

**Comment by Saviq** [comment]
I had a stab at reproducing this and failed. I can confirm that the DNSMasq process we control _does_ respect the host's `/etc/resolv.conf`:

<pre>
$ ps aux | grep mpqemubr0
nobody   1507368  0.0  0.0  10964  3940 ?        S    13:15   0:00 /snap/multipass/6373/usr/sbin/dnsmasq --keep-in-foreground --strict-order --bind-interfaces --pid-file --domain=multipass --local=/multipass/ --except-interface=lo --interface=mpqemubr0 --listen-address=<b>10.48.45.1</b> --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/snap/multipass/common/data/multipassd/network/dnsmasq.leases --dhcp-hostsfile=/var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts --dhcp-range 10.48.45.2,10.48.45.254,infinite --conf-file=/var/snap/multipass/common/data/multipassd/network/dnsmasq-EjXOsQ.conf

$ cat /etc/resolv.conf 
nameserver <b>127.0.0.53</b>

$ dig @<b>10.48.45.1</b> example.com
# ...
;; ANSWER SECTION:
example.com.            6229    IN      A       93.184.216.34

$ echo "nameserver <b>8.8.8.8</b>" | sudo tee /etc/resolv.conf 

$ dig @<b>10.48.45.1</b> google.com
# ...
;; ANSWER SECTION:
google.com.             175     IN      A       216.58.209.14

# and from another terminal
$ sudo tcpdump -n -i any port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
13:32:21.446551 IP 10.48.45.1.35139 &gt; 10.48.45.1.53: 24402+ [1au] A? example.com. (52)
13:32:21.446667 IP 127.0.0.1.26545 &gt; <b>127.0.0.53.53</b>: 44094+ [1au] A? example.com. (52)
13:32:21.446871 IP 127.0.0.53.53 &gt; 127.0.0.1.26545: 44094 1/0/1 A 93.184.216.34 (56)
13:32:21.446950 IP 10.48.45.1.53 &gt; 10.48.45.1.35139: 24402 1/0/1 A 93.184.216.34 (56)
13:32:45.296954 IP 10.48.45.1.43737 &gt; 10.48.45.1.53: 19937+ [1au] A? google.com. (51)
13:32:45.297173 IP 10.2.0.45.5059 &gt; <b>8.8.8.8.53</b>: 2941+ [1au] A? google.com. (51)
13:32:45.297196 IP 10.2.0.45.5059 &gt; <b>8.8.8.8.53</b>: 2941+ [1au] A? google.com. (51)
13:32:45.306340 IP 8.8.8.8.53 &gt; 10.2.0.45.5059: 2941 1/0/1 A 216.58.209.14 (55)
13:32:45.306340 IP 8.8.8.8.53 &gt; 10.2.0.45.5059: 2941 1/0/1 A 216.58.209.14 (55)
</pre>

As can be seen a DNS query to the DNSMasq instance results in it asking the DNS server configured in `/etc/resolv.conf`.

**Comment by Saviq** [comment]
We've also decided against supporting/documenting how to override DNSMasq settings as it can easily lead to broken networking for Multipass instances. We _own_ that network so need to have control over it.

You can still change how instances behave, either via cloud-init or directly after they launch.
