### ISSUE TITLE
exec command instead of running a shell ?

### ISSUE THREAD

**Issue by lucj** [canonical/multipass#1217]
Hi, just a simple question.

Is there a way to achieve something like the following (this example installs Docker but this could be anything else with a similar command using a 'pipe'):

```
$ multipass exec node1 -- curl https://get.docker.com | bash -
```
or even

```
$ multipass exec node1 <<EOF
curl https://get.docker.com | bash -
EOF
```

instead of the following which works but via a shell in the VM ?

```
$ multipass shell node1

multipass@stable-alien:~$ curl https://get.docker.com | bash -
```

BTW: thanks a lot, Multipass is so great !

**Comment by Saviq** [comment]
@lucj you mixed up what gets piped in where :)

These should work:
```bash
$ curl https://get.docker.com | multipass exec node1 -- bash -

$ multipass exec node1 -- bash -c "curl https://get.docker.com | bash"

$ multipass exec node1 -- bash <<EOF
curl https://get.docker.com | bash -
EOF
```

Basically, you need to actually _run_ `bash` inside the instance and feed it the contents of the URL. What you did was either (first case) piping the output into `bash` running on your host, or (second case) piping the `curl https://get.docker.com | bash -` string into a ssh session without anything running on the other side.

**Comment by lucj** [comment]
I knew I was doing something 'newbiely' wrong here :)
Thanks a lot :)

**Comment by lucj** [comment]
In fact, this one works fine:

```
$ multipass exec node1 -- bash -c "curl -sfL https://get.docker.com | sh"
```

The 2 others commands starts correctly but hangs when reaching the end of the script.

Exemple:

```
# curl https://get.docker.com | multipass exec node1 -- bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13216  100 13216    0     0   176k      0 --:--:-- --:--:-- --:--:--  176k
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ubuntu

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.



HANGS UP....
```

**Comment by lucj** [comment]
Any ideas why the other 2 options hangs up ?

**Comment by lucj** [comment]
After some more tests, it seems it hangs when there are pipes in the instructions: If I remove the first 2 instructions below, the process does not hang.

```
multipass exec -v primary -- bash <<EOF
    curl https://get.docker.com | sh -
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    sudo apt-get update
EOF
```

Any ideas how this could be fixed ?

**Comment by lucj** [comment]
Hi, just re-opening this issue / question as I did not get it working fine with inline script.
Any ideas ?

**Comment by townsend2010** [comment]
This is because of a bug in `libssh` and I have a fix proposed.  See CanonicalLtd/libssh#1.

**Comment by lucj** [comment]
Great ! Looking forward to check this out.

**Comment by Saviq** [comment]
From #1287:

> macOS build available: [multipass-1.1.0-dev.539+g1c7da798.mac-Darwin.pkg](https://transfer.sh/lcYE7/multipass-1.1.0-dev.539+g1c7da798.mac-Darwin.pkg)
> Snap build available: `snap refresh multipass --channel edge/pr1287`

@lucj you should be able to try this now ↑

**Comment by lucj** [comment]
Hi @Saviq, I've installed the dev version

```
$ multipass version
multipass  1.1.0-dev.539+g1c7da798.mac
multipassd 1.1.0-dev.539+g1c7da798.mac
```

and run the Docker installation with HEREDOC

```
$ time multipass exec node1 -- /bin/bash << EOF
curl -fsSL https://get.docker.com | sh
EOF
...
real	6m21.030s
user	2m19.718s
sys	3m49.603s
```

That is working fine, but this is quite long and during the installation I can see multipass taking 100% of a cpu and hyperkit almost 180% (?) (the fan is on and noisy too :) )

When I run the exec, the cpu used by Multipass is almost 0%, only hyperkit is in action and no fan at all.

```
$ time multipass exec node1 -- bash -c "curl -sfL https://get.docker.com | sh"
...
real	2m0.455s
user	0m0.046s
sys	0m0.025s
```

Any idea why this difference ?

**Comment by Saviq** [comment]
@townsend2010 may have some input. At first glance it sounds as if it's spinning on one of the comm channels.

**Comment by townsend2010** [comment]
Hi @lucj,

In your first example, it's running `curl -fsSL https://get.docker.com | sh` on your host and then shoving the `stdin` through ssh into your instances `bash` command.  This is a bunch of data that is being encrypted on your host and then decrypted in your instance.  Thus, will take quite a bit of cpu time.

In your second example, your instance is running the curl command and so everything is being done in the instance and no encryption/decryption is taking place.

**Comment by lucj** [comment]
Hi @townsend2010,

Thanks, I got it then. Is there a way to use heredoc so everything is done within the instance ?

For instance, I'd like to be able to run the following

```
multipass exec node1 -- /bin/bash <<EOF
  curl -fsSL https://get.docker.com | sh -
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  sudo apt-get update
  sudo apt-get install -y kubelet kubeadm kubectl
EOF
```

instead of using an exec per command.

**Comment by townsend2010** [comment]
Hi @lucj,

I think I'm wrong about `curl` running on the host, but after a bit of debugging, it seems when using heredoc with this, it is indeed running `curl`, etc. inside the instance, but it's passing its `stdout` back to the host, ie, the `mutlipass` client and then the client  is then passing it back into the instance to `bash`.  Very inefficient: :frowning: 

I'll see if there is some other way to get this to be better.

**Comment by Saviq** [comment]
@lucj as we investigate, this should work fine:

```
multipass exec node1 -- /bin/bash -c "
  curl -fsSL https://get.docker.com | sh -
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  sudo apt-get update
  sudo apt-get install -y kubelet kubeadm kubectl
"
```

Just replace `<<EOF … EOF` with `-c` and a quoted multi-line command passed as argument to `bash`.

**Comment by lucj** [comment]
@saviq, thanks this is working fine (just need to protect the internal ")

**Comment by townsend2010** [comment]
I'm going to split out the heredoc performance issue as a different bug so we can keep track of it.  That said, this is  (once the PR lands) in the sense that it no longer hangs and "works", albeit, inefficiently.

Thanks for all of the feedback!

**Comment by townsend2010** [comment]
I opened #1291 to track the performance issue.
