### ISSUE TITLE
[primary] mount $HOME on creation

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1224]
`multipass shell` and `multipass start` should add a mount of the host's home directory into `primary:Home`.

**Comment by ricab** [comment]
Is the name `Home` final? Wouldn't `HostHome` be clearer (since this is a default)? Or HomeTunnel or something of the sort to highlight this is a mount of the outside world?

**Comment by ricab** [comment]
@Saviq I believe only `multipass launch` needs to setup the mount. It should be persistent to state changes until unmounted.

**Comment by ricab** [comment]
Actually, on `multipass launch primary` (`multipass launch` launches something else).

**Comment by townsend2010** [comment]
We also want `multipass shell` and `multipass start` (without instance names) to do the same if the primary instance does not exist, right?

**Comment by ricab** [comment]
@townsend2010 Exactly, but since they rely on launch, that's where the magic needs to happen :grin: So it really happens *on creation*, as in the title. If one later goes and umounts, no new automount happens.

**Comment by townsend2010** [comment]
@ricab, but your solution implements it in the cli's `launch` command, so the cli's `start` and `shell` commands don't get to use this since they don't use the cli's `launch` logic.

**Comment by Saviq** [comment]
@ricab I'd love a better name, I was thinking Host, HostHome… nothing very good comes to mind ATM.

And yeah it's totally a creation thing, so as long as shell and start loop back onto launch, this should work :)

**Comment by townsend2010** [comment]
Ok, sorry for the noise, I didn't realize that the cli's `shell` and `start` functions actually exec the `multipass` executable on this particular failure.  I'm surprised by that though, but that is for a different discussion.

**Comment by ricab** [comment]
Yep, after all the discussion, pet-env ended up being a client-only feature (no auto creation on install). So it is the client who needs to launch on start/shell. 

Calling an existing cmd maximizes code reuse. It already encapsulates exactly what we need (grpc, user feedback, error handling, etc.), without duplication or separate implementations :)

**Comment by ricab** [comment]
One thing I would like to point out: an important use for VMs is as a throw-away sandbox, to run dangerous things without fear of permanent effects. This adds a door to the user's data, which is concerning if they are unaware of the mount:

```console
ricab@ricab-xps13:~ $ tree a
a
└── b
    └── c
        └── d

2 directories, 1 file
ricab@ricab-xps13:~ $ multipass mount a primary:Home
ricab@ricab-xps13:~ $ multipass exec primary -- rm -rf Home
rm: cannot remove 'Home': Device or resource busy
ricab@ricab-xps13:~ $ tree a
a

0 directories, 0 files
```

**Comment by ricab** [comment]
More or less separately, another thing that occurred to me is that we could add a setting on whether or not to auto-mount.

**Comment by Saviq** [comment]
@ricab I think that's ok, as long as we make it clear (write out "Mounting $HOME in primary:Home"?) when first launching? And yes, a setting might be in order, but let's add it in a second step.

**Comment by ricab** [comment]
OK, I'll do that.
