### ISSUE TITLE
Change icon colour to white

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#1240]
I like the new systray icon but...one of these things is not like the others :-)

<img width="347" alt="Screen Shot 2019-12-17 at 11 12 54 AM" src="https://user-images.githubusercontent.com/532033/71018490-30a1b300-20be-11ea-8f98-6bb849ca2f87.png">

Could it be changed to white?

**Comment by Saviq** [comment]
Hey @hatched we'll have a look soon - it's not as simple as making it white, since people may have a light menu bar. So it needs to be monochrome, in a color that macOS interprets, or maybe there need to be different versions…

**Comment by hatched** [comment]
It looks like the icons change between white and black depending on the light/dark mode chosen. I'm not sure how this is done :-).

**Comment by bartaz** [comment]
Yes, monocolor icons change between light/dark themes.
From what I understand when reading about the topic it can be done using "template images" https://developer.apple.com/documentation/appkit/nsimage/1520017-istemplate
As far as I understand it's a monochromatic image that adapts to light/dark theme.

<img width="446" alt="Screenshot 2020-02-01 at 12 03 41" src="https://user-images.githubusercontent.com/83575/73591274-c4073a00-44ec-11ea-80e9-351150c3e594.png">
<img width="434" alt="Screenshot 2020-02-01 at 12 05 15" src="https://user-images.githubusercontent.com/83575/73591276-c4073a00-44ec-11ea-8ffd-089f3f7918c1.png">

**Comment by remcoov** [comment]
Yeah, this would be great. The colored icon really does not fit the Apple style ("...one of these things is not like the others").

**Comment by flying-sausages** [comment]
Looks like on MacOS you can just supply the black "mask" icon, and the system will automatically adjust it to the darkness on its own. https://stackoverflow.com/a/41998326

**Comment by flying-sausages** [comment]
And QT seems to have an option for this specifically https://stackoverflow.com/a/41903980

**Comment by ONLY78** [comment]
I'm really interested in a monochrome menu icon for MacOS. Is there any way I can help here?

**Comment by ONLY78** [comment]
This article is helpful in describing MacOS monochrome template images: [https://bjango.com/articles/designingmenubarextras/#colour-and-template-images](https://bjango.com/articles/designingmenubarextras/#colour-and-template-images)

_(The correct icon size should be 16x16pt)_

**Comment by townsend2010** [comment]
We are in the process of getting a new logo and with that, new icons.  We will be supporting dark and light themes with the icons.

Stay tuned!

**Comment by helmut72** [comment]
Also it's size is too big:
<img width="301" alt="Bildschirm­foto 2022-11-19 um 08 08 13" src="https://user-images.githubusercontent.com/1388751/202839387-9ed0d228-d3a3-4684-a3fb-82179e5ed9c9.png">

Just FYI and nothing new. I've started using Multipass since 1.8

Thank you.
