### ISSUE TITLE
multipass.gui starts without request and the setting to disable it is hidden in "About", violating expectations.

### ISSUE THREAD

**Issue by abentley** [canonical/multipass#1244]
Multipass is supposed to be a commandline tool.  I don't want a gui, especially an orange one.  I don't think I was prompted whether I wanted it to launch on startup, and I certainly couldn't see a way to disable it in its own menu.  I've disabled multipass until I need it again, so that the gui doesn't launch on startup.

**Comment by townsend2010** [comment]
Hi @abentley,

Which version of `multipass` are you using?  Version 1.0 has a way to disable it in the menu under `About`.  Also, you can disable it from the command line via `multipass set client.gui.autostart=false`.

**Comment by abentley** [comment]
Thanks for the tip.  I don't see the option in the About menu, and settings shouldn't be in the about menu.  It should be purely informational.

$ multipass --version
multipass  0.10.0
multipassd 0.10.0

$ snap info multipass
name:      multipass
summary:   Instant Ubuntu VMs
publisher: Canonical✓
contact:   https://github.com/CanonicalLtd/multipass/issues/new
license:   GPL-3.0
description: |
  Multipass is a tool to launch and manage VMs on Windows, Mac and Linux that
  simulates a cloud environment with support for cloud-init. Get Ubuntu
  on-demand with clean integration to your IDE and version control on your
  native platform.
  
  Launch an instance (by default you get the current Ubuntu LTS)
  
     multipass launch --name foo
  
  Run commands in that instance, try running bash (logout or ctrl-d to quit)
  
     multipass exec foo -- lsb_release -a
  
  Pass a cloud-init metadata file to an instance on launch
  
     multipass launch -n bar --cloud-init cloud-config.yaml
  
  See your instances
  
     multipass list
  
  Stop and start instances
  
     multipass stop
     multipass start
  
  Get help
  
     multipass help
commands:
  - multipass.gui
  - multipass
services:
  multipass.multipassd: simple, enabled, active
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     beta
refresh-date: today at 10:12 EST
channels:
  stable:    1.0.0                  2019-12-18 (1525) 185MB classic
  candidate: ↑                                              
  beta:      ↑                                              
  edge:      0.11.0-dev.51+g2d1b10c 2019-12-17 (1519) 185MB classic
installed:   0.10.0                            (1476) 182MB classic

**Comment by abentley** [comment]
After a `snap refresh multipass`, I get 1.0 and I do see the "Autostart on login" setting, but again, a setting shouldn't be under "about".

**Comment by Saviq** [comment]
Hey @abentley,

I agree "About" isn't the best place to have it, but it was kinda least of all evil (not having it at all, having it top level all the time, having it alone in a separate "Settings" section…). We will be growing the features available in the status menu and at some point we're likely to reorganize it.

As for autostarting it in the first place, the snap system does not currently have the ability to ask questions and we wanted to make sure people see that the menu exists now. Hopefully it's easy enough to disable now that people who don't want it will not be too angry at us.

Thanks for the feedback, appreciated!

**Comment by abentley** [comment]
I'm glad you're looking to fix it.  I disagree that putting it at the top level would be worse than putting it in "about".  Slack puts "Launch on Login" at the top level of its indicator, and it's a common pattern with Windows system tray icons.

**Comment by plashenkov** [comment]
This orange icon in menu bar drives me crazy too :)
Some aesthetics fanatics here, sorry :)

Also I think, if that's possible, it would be nice to have an option not to install GUI tool at all. It may be okay to use just command-line app for some users.

**Comment by plashenkov** [comment]
> Also I think, if that's possible, it would be nice to have an option not to install GUI tool at all.
Ah, it looks like we already have this option. Thank you :)

**Comment by plashenkov** [comment]
I've found that we have checkboxes in macOS installer (including "Multipass Status Menu" checkbox) but they are disabled and we cannot turn any of them off.

**Comment by MarcMielke** [comment]
on macos catalina logs get spammed with
```
Jun 30 19:19:54 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart): Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
Jun 30 19:19:55 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart[30925]): Service exited due to SIGABRT
Jun 30 19:19:55 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart): Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
Jun 30 19:19:56 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart[30967]): Service exited due to SIGABRT
Jun 30 19:19:56 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart): Service only ran for 0 seconds. Pushing respawn out by 1 seconds.
Jun 30 19:19:57 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart[31009]): Service exited due to SIGABRT
Jun 30 19:19:57 macmac com.apple.xpc.launchd[1] (com.canonical.multipass.gui.autostart): Service only ran for 0 seconds. Pushing respawn out by 1 seconds
```

multipass set client.gui.autostart=does not help. It also makes `ReportCrash` consume 20-40% of cpu. how to effectively disable this?

**Comment by Saviq** [comment]
> `multipass set client.gui.autostart=false` does not help. It also makes `ReportCrash` consume 20-40% of cpu. how to effectively disable this?

Hi @MarcMielke can you try running it manually and see if you get more data on why it's aborting?

**Comment by MarcMielke** [comment]
```bash
macmac:LaunchAgents root# /Applications/Multipass.app/Contents/MacOS/Multipass multipass.gui --autostarting
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abort trap: 6
```

I worked around te problem by completely disabling the launch agent in `/var/root/Library/LaunchAgents`.

**Comment by ricab** [comment]
Hi @MarcMielke, on macOS you can run the gui from the command line with `open -a Multipass`. 

The option `--autostarting` is an implementation detail, not documented or part of our interface in any way. 

To disable autostarting you can do `multipass set client.gui.autostart=false` or edit the setting on the GUI itself. Feel free to open a new issue if there is any problem with any of those methods.

**Comment by Saviq** [comment]
> ```shell
> macmac:LaunchAgents root# /Applications/Multipass.app/Contents/MacOS/Multipass multipass.gui --autostarting
> qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Abort trap: 6
> ```

OK so this is the issue, could you please run it with `QT_DEBUG_PLUGINS=1`?

**Comment by vizcay** [comment]
Not only that, in Xubuntu the menu's text is not even displayed and I had to guess how to close it!

I cannot get an screenshot as the PrintScr key doesn't work with the menu open (no idea why).

* Xubuntu 16.04.7 LTS
* multipassd 1.4.0

**Comment by Saviq** [comment]
Hi @vizcay, did you manage to disable it from the command line? That it doesn't show text etc. sounds like a compatibility issue between Xubuntu 16.04 and snaps.

However, Xubuntu 16.04 [isn't supported](https://help.ubuntu.com/community/EOL#Ubuntu_16.04_Xenial_Xerus) for more than a year now, it would be good that you upgrade soon, preferably to 20.04 already if you don't want to have to upgrade in 6 months again.

**Comment by yalon** [comment]
@Saviq here you go:

>  QT_DEBUG_PLUGINS=1 /Applications/Multipass.app/Contents/MacOS/Multipass multipass.gui
> QFactoryLoader::QFactoryLoader() checking directory path "/Library/Application Support/com.canonical.multipass/bin/multipass.gui.app/Contents/MacOS/platforms" ...
> qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

In the meantime, where can I disable it? It also makes ReportCrash starts working like crazy.

Same experience with Catalina and Big Sur unfortunately.

Thanks!

**Comment by Saviq** [comment]
@yalon are you on case sensitive APFS, by any chance?

**Comment by yalon** [comment]
Yes, I am.

**Comment by Saviq** [comment]
@yalon your bug is #1248, then.

**Comment by benatkin** [comment]
I didn't expect it to be in About. It is OK to have a separate Preferences or Settings menu item even if there is only one option.

**Comment by lukens** [comment]
I agree this would be better placed at top level, rather than under about. I only just found its was there after finally deciding to try and get rid of that damned orange icon for good.

Also, I expect that, like me, most people only want to get rid of it because it because it looks completely out of place. Replacing it with a black and white icon would be my preference for any fix. It seems this is already covered by #1240.

**Comment by Flimm** [comment]
I agree with other people here, that options should not be under an "About" menu.

**Comment by townsend2010** [comment]
This is no longer an issue with our upcoming Flutter based full GUI.  Since that is already merged into our mainline code, I'm closing this as complete.  Thank you!
