### ISSUE TITLE
Manjaro: multipass socket access denied

### ISSUE THREAD

**Issue by kemra102** [canonical/multipass#1250]
After installing Multipass on Manjaro (including setting up `snapd` as per the instructions on the snap store page) I get the following error:

```sh
➜ kemra102@iacon  ~  multipass find                 
find failed: multipass socket access denied
Please check that you have read/write permissions to '/var/snap/multipass/common/multipass_socket'
```

Even after a reboot this is still the case, though I do now get the `multipass-gui` but this fails with the same error.

Here are the permissions on the socket file listed:

```sh
➜ kemra102@iacon  ~  ls -l /var/snap/multipass/common/multipass_socket 
srw-rw---- 1 root adm 0 Dec 19 09:15 /var/snap/multipass/common/multipass_socket
```
Additional info:

```sh
➜ kemra102@iacon  ~  multipass --version
multipass  1.0.0
```

```sh
OS: Manjaro Linux x86_64 
Host: MS-7A32 1.0 
Kernel: 5.3.15-1-MANJARO 
Uptime: 9 mins 
Packages: 1308 (pacman), 4 (snap) 
Shell: zsh 5.7.1 
Resolution: 2560x1440 
DE: Plasma 
WM: KWin 
Theme: Breath [GTK2/3] 
Icons: maia [GTK2/3] 
Terminal: yakuake 
Terminal Font: Noto Mono 10 
CPU: AMD Ryzen 7 1700 (16) @ 3.000GHz 
GPU: AMD ATI Radeon RX 5700 / 5700 XT 
Memory: 1835MiB / 32123MiB
```

**Comment by Saviq** [comment]
Hi @kemra102, as you can see in your `ls` output, you need to be in the `adm` group to access it. Remember you need to log out and back in to get the groups (that, or use `sg` or `newgrp`).

Please let us know if that didn't work for you.

**Comment by kemra102** [comment]
That did the trick and got me going @Saviq  thanks.

I do wonder though if this shouldn't either be a bug or maybe just missing documentation? Ideally users shouldn't be required to do things like this, so if this can be fixed with code changes (either in `multipass` or the Snap config) that would be preferable. If that isn't possible then perhaps we're missing some documentation.

**Comment by Saviq** [comment]
@kemra102 we do want to get rid of that requirement in the near future, yes.

In the mean time we'll add a note in our install docs.
