### ISSUE TITLE
Complex `~/.ssh` may cause `multipass` to crash

### ISSUE THREAD

**Issue by sonnius** [canonical/multipass#1259]
I'm getting a segfault when running 'multipass shell'

```
bash-5.0$ multipass shell
Segmentation fault: 11
```

It works as the root user:

```
bash-5.0$ sudo multipass shell
Password:
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Dec 20 10:20:08 NZDT 2019

  System load:  0.0               Processes:             106
  Usage of /:   24.0% of 4.67GB   Users logged in:       0
  Memory usage: 12%               IP address for enp0s2: 192.168.64.3
  Swap usage:   0%


0 packages can be updated.
0 updates are security updates.


Last login: Fri Dec 20 09:36:44 2019 from 192.168.64.1
ubuntu@primary:~$
```

Running MacOS Catalina:

```
bash-5.0$ uname -a
Darwin Robs-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

**Comment by Saviq** [comment]
Huh! Hey @sonnius, I'm afraid we've never seen this happen - can you give a bit more info: how did you install, what version (`multipass version`)?

Can you see a relevant `.crash` file in `~/Library/Logs/DiagnosticReports`? If so, please upload it here.

**Comment by sonnius** [comment]
Saviq,

Installed using brew

Looking at the crash file it seems there's some issues with libssh, just wanted to mention I have a fairly large SSH config file that includes .ssh/config.d/* also.

```
~ ❯ multipass version                                                                                                                                                     
multipass  1.0.0+mac
multipassd 1.0.0+mac
[multipass_2019-12-20-101930_Robs-MacBook-Pro.crash.log]
```

Crash file (added .log extension to it)

(https://github.com/canonical/multipass/files/3985875/multipass_2019-12-20-101930_Robs-MacBook-Pro.crash.log)

**Comment by sonnius** [comment]
Moving ~/.ssh to ~/.ssh.bak works around the issue, could it be the libssh version does not understand my SSH config file syntax?

```
~ ❯ ssh -V                                                                                                                                                                    [I]
OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by Saviq** [comment]
Hi @sonnius, good digging - that may certainly be. Moreover, our libssh shouldn't even be looking into your `~/.ssh`. We'll have to configure it to look somewhere else for its config.

Thanks for reporting!

**Comment by callegar** [comment]
This is happening also on ubuntu 19.10.

Multipass shell crashes unless I move away `~\.ssh` or at least `~/.ssh/config`. This basically makes multipass unusable here.

My ssh config is not particularly complex. However, `multipass` seems to choke whenever there are entries like `proxyjump` or pointers to keys that do not exist.  The `libssh` used by multipass appears to be rather flawed since it fails ungraciously on things it cannot deal with.

Where do the diagnostic reports go in ubuntu where multipass is installed as a snap?

**Comment by callegar** [comment]
This seems to break `snapcraft` too:
```
An error occurred when trying to execute 'sudo -i env SNAPCRAFT_HAS_TTY=True snap set core refresh.hold=2019-12-26T14:05:30.283562Z' with 'multipass': returned exit code -11.
```
Please consider rising priority.

**Comment by callegar** [comment]
I have cross posted the issue to the libssh upstream tracker, as https://bugs.libssh.org/T210

The issue may be resolved there shortly, so that multipass can be fixed by updating its embedded libssh library.

**Comment by townsend2010** [comment]
Indeed, we do need to update the `libssh` version.  A couple of things.  First, we use `boringssl` from the `grpc` submodule we import for `libssh` encryption.  Second, the current commit we are using for `grpc` (and `boringssl`) does not have support that the newer versions of `libssh` is looking for.  So, we are in the process of updating the `grcp` submodule suite (see #1182), but we are running into an issue in ci where some of the builds fail to compile.

Now that we are back from the holidays, all of this will be given priority.

**Comment by townsend2010** [comment]
Could someone who is affected by this bug please provide a simple ssh config that can cause the issue?  As mentioned in #1286 (which should work around this issue), we have no way to test the workaround and so there is reluctance on merging it.

Thanks!

**Comment by townsend2010** [comment]
Also, if an affected user can follow the instructions at https://github.com/canonical/multipass/pull/1286#issuecomment-573706242 and verify that it fixes the issue for you, that would be great as well!

**Comment by quidryan** [comment]
@townsend2010 The link to multipass-1.1.0-dev.564+g65045877.mac-Darwin.pkg file is no longer valid. Where can I find another build to try out?

**Comment by townsend2010** [comment]
Hi @quidryan,

The build found [here](https://github.com/canonical/multipass/pull/1324#issuecomment-578296013) will have the bits in it that fixes this particular issue (and some unrelated issues).

Thanks!
