### ISSUE TITLE
MacOS: where is vm file location 

### ISSUE THREAD

**Issue by thomasdba** [canonical/multipass#1263]
from the instances config multipassd-vm-instances.json ,I can only find its size , is there any way to change the data file location ?  soft link ?
Thanks !

**Comment by gluxon** [comment]
Does `/var/root/Library/Application Support/multipassd/vault/instances` have what you're looking for?

**Comment by thomasdba** [comment]
yes ,thanks !

**Comment by Goldenstarc** [comment]
is it still same in multipass  1.2.1+mac version ?
i cant find it.

**Comment by Saviq** [comment]
@Goldenstarc yes, it's still in the same location. If you're using VirtualBox, it'll be `/var/root/Library/Application Support/multipassd/virtualbox/vault/instances`.

**Comment by Rocky-L** [comment]
> is it still same in multipass 1.2.1+mac version ? i cant find it.

I'm using the M1 chip Macbook Pro, mine is `/var/root/Library/Application Support/multipassd/qemu/vault/instances/{instance_name}/{image_name}.dmg`
