### ISSUE TITLE
How can I change memory (RAM) size of existing Multipass virtual machine?

### ISSUE THREAD

**Issue by pcgeek86** [canonical/multipass#1265]
I have an existing multipass virtual machine with 1 GB of RAM (the default). However, I would like to increase the amount of memory from 1 GB to 4 GB. I looked for an option to do this under `multipass get` and `multipass set`, but couldn't see any option keys that I could change. 

**Question**: How can I change the memory configuration of an existing multipass VM, without re-provisioning it from scratch?

* MacOS Catalina
* Multipass 0.10

```
~ multipass version
multipass  0.10.0+mac
multipassd 0.10.0+mac
```

**Comment by ricab** [comment]
Hi @pcgeek86, while that is not currently supported (although it is planned - #756), for now you should be able to tweak it by following [these instructions](https://github.com/canonical/multipass/issues/1158#issuecomment-548073024).

**Comment by townsend2010** [comment]
I'm going to close this particular issue as we have future plans for allowing configuration of existing instances and we have a manual workaround.  If that doesn't work for you, please reopen and we will try to help.  Thanks!

**Comment by scheung38** [comment]
Hi is this still the case as I have similar issue, and didnt want to undo all the config I did after launching:

https://github.com/canonical/multipass/issues/1881

**Comment by mostafaabuelkhair** [comment]
Hi scheung38, you increase resize HD and memory by edit this file "/var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json" while the instance is stopped, and restart multipass process after that start the instance again but it's take some time to start if it's failed to start in first time stop it and start it again. this is already tested on multipass 1.8 installed on Ubuntu 18.04

**Comment by gentooza** [comment]
[since multipass 1.10 version:](https://multipass.run/docs/modify-an-instance#heading--set-the-cpu-ram-or-disk-of-an-instance)
```
multipass set [local.<instance-name>.(cpus|disk|memory)](https://multipass.run/t/)]=[value]
```
works great

**Comment by yisonPylkita** [comment]
If your instance name is `primary` just type

```bash
multipass set local.primary.memory=4G
```

To see your instances names type `multipass list`
