### ISSUE TITLE
GUI client cannot use alternative terminal application in macOS

### ISSUE THREAD

**Issue by judaew** [canonical/multipass#1273]
###### Reproduction steps:
1. Open the context menu in the menu bar
2. Choose "Open in Shell"
3. The Shell opens in the native Terminal application.

###### Solution:

macOS does not support the concept of a default terminal. So the solution may be to read the MIME value for opening Shell scripts and prefer this application. Or implement functionality to select the default application. But I’m not sure how relevant this is since the GUI consists only of a context menu.

Example as iTerm2 can reassign the MIME value for scripts:
<img width="200" alt="Screenshot" src="https://user-images.githubusercontent.com/41125715/71486382-bd671200-281e-11ea-9846-efeb78755287.png">

**Comment by townsend2010** [comment]
Hi @judaew,

Yes, we have future plans to either allow setting which terminal application to use when running `Open Shell` and/or detecting what the preferred terminal application is.

**Comment by Saviq** [comment]
@judaew what we're doing on macOS is just using the built-in `open` with a shell script file. Do you know what we could do better so that the iTerm2 preference gets picked up?

**Comment by judaew** [comment]
Now maybe we have the following behavior: when we running `Open Shell`, then the terminal opens and the script is executed along the path `$TMPDIR/multipass-gui.xxxxxx.command`

<img width="573" alt="Screenshot 2020-01-15 at 18 30 23" src="https://user-images.githubusercontent.com/41125715/72451749-19410d00-37c5-11ea-9177-2cb152fe93e6.png">

Inside the script, the following command:
Inside `multipass-gui.xxxxxx.command ` the following:
``` console
judaew:~$ cat $TMPDIR/multipass-gui.rJNbBk.command

multipass shell chummy-hammerhead
```

As I previously learned, iTerm can reassign MIME for `.zsh` or `.sh`. So I tried the following:
``` console
judaew:~$ cat $TMPDIR/multipass-gui.xxxxxx.command > test.zsh
judaew:~$ chmod +x test.zsh
```
After that, I opened this file in the file manager. And the script was executed in iTerm2.

###### New solution:

Instead of the `*.command` extension, you should put the script in `*.zsh` or `*.sh`. If the system does not have iTerm2 or does not reassign MIME, the script will open in the system terminal.

**Comment by Saviq** [comment]
Thanks @judaew, we'll try this out!

**Comment by Saviq** [comment]
Hi @judaew, all - unfortunately the default applications handling `*.sh` and `*.zsh` files are XCode and TextEdit, so we can't use those as our defaults.

All, I've not found a way to easily change this on the command line, but you can create a `.command` file, right-click it, "Get info" and, under "Open with" select your preferred terminal and click on "Change all…".

Alternatively, you can use [`duti`](https://github.com/moretension/duti) ([available on brew](https://formulae.brew.sh/formula/duti)):
```console
$ duti -s com.googlecode.iTerm2 com.apple.terminal.shell-script all
```

**Comment by Saviq** [comment]
I've now added documentation about this:

https://multipass.run/docs/changing-macos-terminal

Please reopen this if you think we can do better than that.

**Comment by judaew** [comment]
Thank you 🌟, I consider the solution using the `duti` sufficient right now.
