### ISSUE TITLE
"info failed: bad optional access" error

### ISSUE THREAD

**Issue by callegar** [canonical/multipass#1275]
Experiencing an issue with `snapcraft`, that is using multipass behind the scenes. If snapcraft gets interrupted while launching its virtual machine with multipass, multipass often breaks and from that moment on stops working giving errors like `An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.` or `info failed: bad optional access` when trying to look at the machines.

**Comment by callegar** [comment]
Another common error is `Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible`. Looks like similar reports can be googled around, with the common suggestion to uninstall and re-install multipass to fix the issue. Is there a better way?

**Comment by Saviq** [comment]
The actual Multipass issue here seems to be `info failed: bad optional access`, we'll have to look into that.

The latter error means that Multipass died (we just fixed a crash in Multipass a couple days ago, would be good to know if this is still an issue), but there's not enough information to progress.

Please file a separate issue with the output of `journalctl -au snap.multipass*` when you get this again, thanks!

**Comment by Saviq** [comment]
As for the original issue, @callegar do you have steps to reproduce? The errors Snapcraft prints are generic, output when anything goes awry in Multipass. Looking into the journal when this happens could yield some more information.
