### ISSUE TITLE
windows can't use proxy

### ISSUE THREAD

**Issue by zy445566** [canonical/multipass#1276]
version: win10, multipass1.0
```sh
set https_proxy=http://127.0.0.1:1080
set http_proxy=http://127.0.0.1:1080
multipass launch --name m1
# output: 
# launch failed: cannot connect to the multipass socket
# Please ensure multipassd is running and 'localhost:50051' is accessible
```

**Comment by townsend2010** [comment]
Hi @zy445566,

Does multipass work OK when not setting the proxy?  That output indicates that `multipassd` is failing to run and setting those variables should have no impact on that.  It seems something else is failing.  Is there anything in the Event Viewer for `multipassd` as to why it's failing to run?

**Comment by zy445566** [comment]
it's  work OK when not setting the proxy.
I reinstall then it's work OK,but it's  not work OK when setting the proxy.

**Comment by townsend2010** [comment]
@zy445566,

I tried it and although I don't have a proxy running, it worked.  The `multipassd` daemon is set up to listen to port 50051 on `localhost` and the client tries to connect to that via https.  I assume you have a real proxy set up, so I think the client's attempted connection gets rerouted by your proxy and does not connect to the daemon.  I think you need to look at your proxy configuration in order to make the https port 50051 connection work.

**Comment by Saviq** [comment]
FWIW we have #885 about this, too.

**Comment by townsend2010** [comment]
I'm going to dup this to #885 since it appears that it caused by the same issue.

**Comment by townsend2010** [comment]
Actually, this is not a dup of #885, but I think I understand what is happening.

So in this case, the proxies are being set for the current session.  Then the `multipass` client runs using these proxy settings for it's `gRPC` connection to the daemon.  gRPC is trying to use the proxy to route it's request to the daemon.  However, the daemon is local on the computer.  I found that in order for gRPC not to use the proxy for `localhost`, you need to set the `no_proxy` variable as well.
```
set no_proxy=localhost
```

Could you please try that and make sure it now works?

**Comment by zy445566** [comment]
> 实际上，这不是[＃885的重复](https://github.com/canonical/multipass/issues/885)，但我想我知道发生了什么。
> 
> 因此，在这种情况下，将为当前会话设置代理。然后，`multipass`客户端将使用这些代理设置来运行其`gRPC`与守护程序的连接。gRPC正在尝试使用代理将其请求路由到守护程序。但是，该守护程序在计算机上是本地的。我发现为了使gRPC不使用的代理`localhost`，还需要设置`no_proxy`变量。
> 
> ```
> set no_proxy=localhost
> ```
> 
> 您能否尝试一下并确保它现在可以工作？

it's solved my problem,thx
