### ISSUE TITLE
No description about 'primary'?

### ISSUE THREAD

**Issue by moonlight16** [canonical/multipass#1288]
It would be useful to have a description about 'primary' instance.  i.e. what is it?  why is it neeed? etc...

**Comment by ricab** [comment]
Hi @moonlight16 , you're right. The help for the commands where it is used explains how we treat it, but I agree we should have a dedicated explanation, probably an entry in [our docs](https://multipass.run/docs). 

It is basically a default instance for some operations (`shell`, `start`, `stop`, `restart`, `suspend`) which is automatically launched if it does not exist (by `start` and `shell`) and gets your home auto-mounted.  For now, please try `multipass help shell|start|launch` for more details.

**Comment by moonlight16** [comment]
@ricab thanks.  It seems you can run without the primary instance.  Originally a primary was spun automatically (as you mentioned).  I then created a couple of other instances.  Then deleted the primary.  It seems to have been run okay without one.  

So I guess the only benefit of running with a primary is that the home dir is automounted?  Whereas other instances you have to manually mount dirs?

**Comment by ricab** [comment]
Yes, multipass runs just fine without `primary`. It is not required, merely offered as a convenience instance.

This is now documented in: [https://multipass.run/docs/primary-instance](). I hope it clarifies it for you.

**Comment by moonlight16** [comment]
Doc looks good.  thx!
