### ISSUE TITLE
sshfs_server not starting at boot on fresh windows 10

### ISSUE THREAD

**Issue by JayDoubleu** [canonical/multipass#1292]
Fresh install of Windows 10 ver 1909 build 18363.535.
Multipass 1.0.0 from multipass.run.
Hyper-V enabled.

On first logon it seems that sshfs_server.exe is not starting. After running multipass restart service starts up without any problems. ( this didn't seem to be the issue on fast ring insiders windows 10)

**Comment by Saviq** [comment]
Hey @JayDoubleu thanks for filing this. Can you look in Event Viewer for any problems Multipass is reporting? It's under "Windows Logs/Application" at the moment.

**Comment by townsend2010** [comment]
@JayDoubleu,

I'm a little confused...the title says `sshd_server`, but the description refers to `sshfs_server.exe`.  Could you please let us know which it is?

**Comment by JayDoubleu** [comment]
My apologies, its sshfs_server.exe on the host machine that fails to start after reboot.

**Event viewer:**

1. **Reboot**
2. **Info**: [sshfs-mounts] mounting C:/Users/devel => Home in primary
3. **Info**: [sshfs-mounts] process program 'C:/Program Files/Multipass/bin/sshfs_server'
4. **Info**: [sshfs-mounts] process arguments 'primary.mshome.net, 22, ubuntu, C:/Users/devel, Home, -2:-1,, -2:-1,'
5. **Warn**:  [sshfs-mounts] Mount 'Home' in instance "primary" has stopped unexpectedly: Process returned exit code: 1
5. **multipass shell**: ls hangs due to sshfs mount problem ( would be nice to give it timeout btw as cannot ctrl+c or z )
6. **multipass restart** : now everything works fine and I can see sshfs_server.exe in task manager.
