### ISSUE TITLE
Daemon should re/store instance state on startup

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#130]
Stopping the daemon should store the instance state and restore it again on startup.

**Comment by townsend2010** [comment]
I think once we move to using the libvirt backend by default and https://forum.snapcraft.io/t/process-lifecycle-on-snap-refresh/140/37 being fully implemented in snapd and snapcraft, we won't need to be concerned about saving instance state since the qemu process will survive through multipassd/libvirtd restarts.

As it stands right now, when the libvirt backend work is merged and using multipassd outside of snap, instance state will remain when multipassd is stopped or restarted.  For example, if an instance is running and multipassd is shut down, the instance will remain running and when multipassd starts again, it will detect via libvirtd that the instance is running and set state accordingly.

**Comment by Saviq** [comment]
Well, `multipassd` restarting is one thing, how about boot?

**Comment by townsend2010** [comment]
@Saviq,

Currently, for the QEMU driver, when multipassd receives `SIGTERM`, it will try to gracefully shut down running instances.  We do this because multipassd owns the QEMU QProcess's, so we try to avoid just yanking the VM away.  That said, if a system reboots, it sends `SIGTERM` to mulipassd, so the instances will be gracefully shutdown and thus, the running state is no longer the case.  Any opinions on how we should handle this for host reboots, etc?

**Comment by townsend2010** [comment]
Oh, I know what we should do.  On multipassd shutdown, we should try to shutdown the instances gracefully, but the saved state shouldn't bu updated, so on the subsequent multipassd start, it will start up those particular instances automatically.
