### ISSUE TITLE
Make open port accessible from host?

### ISSUE THREAD

**Issue by wiradikusuma** [canonical/multipass#1305]
I think I'm missing something obvious, as it's not mentioned anywhere in the documentation. 

Let say I install Redis Server, and it's running and listening to a port. How do I access that service from the host OS? E.g. from Windows 10.

**Comment by Saviq** [comment]
Hi @wiradikusuma except for VirtualBox, which has a limited networking setup, you can just access it on the IP addresses found in `multipass list` and `multipass info <instance>`.

I'll close this now, please reopen if you think there's more to it.

**Comment by jovyllebermudez** [comment]
Hi In my case, I was only able to access the port 80 but the other ports like 8000 8080 are not, so weird. gonna look at the ufw
