### ISSUE TITLE
What is the password of the "ubuntu" user?

### ISSUE THREAD

**Issue by akunaatrium** [canonical/multipass#1308]
Let's say I want to log in to the machine over SSH, with password authentication. By default SSH daemon is configured to disallow password authentication (`PasswordAuthentication no`) but when I change it to `yes`, restart SSH server and try to log in with SSH, it asks for a password and I have no idea what to enter.

**Comment by Saviq** [comment]
Hi @akunaatrium, the default user does not have a password at all (on purpose). You can set one via `passwd` or better yet, use SSH keys to log into the instance :)

I'll close this, please reopen if you think there's more to it.

**Comment by AvtsVivek** [comment]
Hi Saviq,
Can you please provide more info on how to set password for the default user ubuntu? How should the command line be?

**Comment by Saviq** [comment]
@AvtsVivek `sudo` is passwordless - if you want to set a password for the `ubuntu` user, run `sudo passwd ubuntu`. That won't allow ssh login with passwords (edit `/etc/ssh/sshd_config`) for that. It also won't make `sudo` require a password - for that you'd need to `sudo rm /etc/sudoers.d/90-cloud-init-users`.

**Comment by foxler2010** [comment]
If I get a password prompt and I don't have a password, can I just hit enter and it will be okay?

**Comment by ricab** [comment]
Hi @foxler2010. No, that is not how it works. A "disabled password" is different from an empty password, it really disables password authentication. Authentication is still possible by other means, namely with public key. Here is a [stackexchange discussing this](https://unix.stackexchange.com/questions/56765/creating-a-user-without-a-password).
