### ISSUE TITLE
Unable to launch on Windows: network timeout

### ISSUE THREAD

**Issue by andersonluisribeiro** [canonical/multipass#1309]
Running multipass 1.0.0 on Windows 10. When I run:

` multipass launch --name ubuntu-lts --cpus 4 --mem 6G --disk 40G`

After a while I get de following error:

` launch failed: failed to download from 'http://cloud-images.ubuntu.com/releases/server/releases/bionic/release-20200107/ubuntu-18.04-server-cloudimg-amd64.img': Network timeout`

**Comment by townsend2010** [comment]
Hi @andersonluisribeiro,

Hmm, does this happen every time you try to launch an instance?  Are you behind a proxy or any other sort of firewall that may prevent applications from downloading?  What happens if you try to download that same URL using another way such as a web browser?

**Comment by andersonluisribeiro** [comment]
Hi @townsend2010. I can download image using web browser. I can download part of iso, but after a while, about 17 percent of downoad, the error happen and my internet is not slow.

**Comment by townsend2010** [comment]
And this occurs every time the image is being downloaded?

Basically, that error is saying that a request to get a chunk of the image did not respond in 10 seconds and so the daemon determined that there is some network issue occurring and aborts the download.  We've not had any other reports that image downloads are timing out, so it really does seem network related somewhere between your machine and the image server.

That said, I'm sure we could make it more resilient to hopefully get it through such transient issues and perhaps that's what this bug should be about.

**Comment by SpacePossum** [comment]
Hi!
Thanks for `multipass`, made my life much easier!

I get this same error on some systems with poor network conditions. I'm trying to download the image now using something else and when done I'll will feed the image file to the `multipass launch-command` to see if this will work. Wondering though, maybe we could have some timeout parameters we could set?

**Comment by Saviq** [comment]
> I'm trying to download the image now using something else and when done I'll will feed the image file to the `multipass launch-command` to see if this will work.

Hi @SpacePossum it's currently unsupported (#1593) to launch "custom" images on Windows and macOS, sorry…

> Wondering though, maybe we could have some timeout parameters we could set?

We currently set the timeout to 10s, but that's a "no progress" timeout. So we timeout if the download is stuck for 10s… We could potentially increase it, or give it up for configuration, but if your network is unstable enough to stall for 10s, you'll get a bad experience whatever you do…

**Comment by SpacePossum** [comment]
Thanks for the quick reply. I'll keep a watch on the other issue, would be great to see that resolved :)
Agreed, I'm not going to have with this machine in the future with its crappy network, however for what it is and does it doesn't need any good internet connection, it is most processing some offline process.

**Comment by xiestcn** [comment]
I get same error that occurs every time when downloading the image on win 10 Home, but Win 10 Pro is OK

**Comment by Saviq** [comment]
Hi all, the image servers now got 3× the bandwidth (and we're working on bumping it 100× in the medium term). This should help with all the _Network timeout_ issues out there.

**Comment by SpacePossum** [comment]
Hi,
Great to hear about the bandwidth improvements! However, this doesn't help when your are on a very slow connection yourself. 

For example I'm trying to install on a very remote location with a very poor internet connection. I can download the image manually at another location and send it by snailmail, so would be great if it was allowed to install by file and only by internet. Is there some reason why this is not allowed currently?

**Comment by Saviq** [comment]
> Is there some reason why this is not allowed currently?

Hey, we have #1593 dealing with that. You can do it on Linux already, but we've not enabled that on Windows or macOS yet.
