### ISSUE TITLE
Windows shell long line wrapping overwrites line and doesn't wrap properly

### ISSUE THREAD

**Issue by dbrennan** [canonical/multipass#1326]
When line goes past terminal width in cmd or new Windows terminal it linefeeds, but cursor goes back to the beginning of the same line. Editing is basically messed up at that point and you can't get back to a readable version of what you've typed. Also a problem when pasting long lines in from somewhere else.

**Comment by chriswgibson** [comment]
I have the exact same issue in MacOS terminal

**Comment by ricab** [comment]
Hi @dbrennan, it seems we need to tweak our `stty` options. Meanwhile, if you issue `stty ocrnl` inside the instance's shell, does that work for you?

**Comment by ricab** [comment]
Hi @chriswgibson, did you happen to resize the window where you got this? If so, does the workaround in #1327 work for you?

**Comment by dbrennan** [comment]
I tried `stty ocrnl` and it wraps when pasting, but then if you cursor back and forth across the wrap boundary the terminal scrolls everything up a line when you cross the boundary in either direction.

**Comment by ricab** [comment]
Done and coming in the next release.

**Comment by michael-angelozzi** [comment]
> Done and coming in the next release.

What release will that be? So I can keep an eye for it. Ime using Version: 1.1.2021.0 and I also get this issue.

`stty ocrnl` makes it break at some point and leave a blank line, hard to explain, see pic below:
![image](https://user-images.githubusercontent.com/19764314/89419862-3a9e2200-d732-11ea-9277-74b1af887ad9.png)

Before `stty ocrnl` it would wrap back onto itself, before running off the current line, then wrapping properly below.
