### ISSUE TITLE
stty size not updated on macOS

### ISSUE THREAD

**Issue by jfmc** [canonical/multipass#1327]
When resizing a terminal window (both Terminal.app and iTerm2), the value returned by `stty size` is not updated w.r.t. the initial value when it is run from a `multipass shell`.

**Comment by ricab** [comment]
HI @jfmc thanks for reporting this. I confirm the columns are not getting updated. When increasing them, this results in the same thing that is described in #1326. A different solution will be needed though. 

For now, `stty cols N` should workaround the issue, where `N` corresponds to the window size shown at the terminal's title bar. Does that fix it for you?

**Comment by jfmc** [comment]
Thanks @ricab!

Resizing a terminal with an open `emacs` inside is a bit cumbersome, but this works for me:
 - whenever the terminal size change press C-z to suspend emacs
 - set new size with `stty cols N`+`stty rows M`
 - bring emacs back to foreground with the `fg` command
