### ISSUE TITLE
Multipass.app GUI steals CMD+OPTION+U shortcut

### ISSUE THREAD

**Issue by bartaz** [canonical/multipass#1329]
On macOS Cmd+Option+U shortcut is used by browsers as a shortcut for view source (both in Chrome and Firefox, possibly others as well).

Multipass.app GUI seems to be stealing this shortcut for opening terminal in primary instance.

**Comment by townsend2010** [comment]
Hey @bartaz,

Yep, this is a duplicate of #1311.  We're thinking how best to address this.

Thanks!
