### ISSUE TITLE
Change user_id?

### ISSUE THREAD

**Issue by dlehenky** [canonical/multipass#1334]
How can I mod the ubuntu install image to have a different user_id than "ubuntu"?

**Comment by ricab** [comment]
Hi @dlehenky, you can add users with [cloud-init](https://cloudinit.readthedocs.io/en/latest/topics/examples.html), e.g.:

```console
$ cat clinit
users:
  - name: foo
    shell: /bin/bash
    ssh_authorized_keys:
      - <public key>
$ multipass launch --cloud-init clinit
Launched: pithy-greenshank
$ multipass list
Name                    State             IPv4             Image
pithy-greenshank        Running           192.168.123.242  Ubuntu 18.04 LTS
$ ssh -i <private key> foo@192.168.123.242
[...]
foo@pithy-greenshank:~$
```

Changing the default user is planned but not done yet (see #929).

**Comment by dlehenky** [comment]
Thank you very much! Just an old fart geek here; this stuff is both exciting and foreign to me :) Keep on learning!

**Comment by ricab** [comment]
No problem @dlehenky, happy to help!

**Comment by bhechinger** [comment]
Is there a way to get `multipass shell` to use the alternate user?

**Comment by Saviq** [comment]
Hi @bhechinger, no, not at the moment. It would be trivial, though, to create an alias to do `multipass exec <instance> -- sudo -i -u <user>`, though.

**Comment by bhechinger** [comment]
Ok, I gave that a shot @Saviq and I'll just wait for multipass to suppose an alternate user name. Not worth the effort. ;)
