### ISSUE TITLE
Bricked instance prevents me from re-using the same name

### ISSUE THREAD

**Issue by moonlight16** [canonical/multipass#1335]
I had a multipass instance called 'myserver' running on my Macbook.  Today, I found I can no longer get it running.  I decided to delete and purge the instance and I'm no longer able to reuse the same instance name 'myserver'.  I've tried uninstall and reinstall multipass and still cannot create a 'myserver'.   I am able to create a primary instance, and any other instance with anything other than 'myserver'.  

Here's what I get if I try to create an instance with name 'myserver':

```
[~] $ multipass ls        
No instances found.
[~] $ multipass launch -c 8 -d 200G -m 16G -n myserver 
launch failed: The following errors occurred:                                   
Instance stopped while starting
[~] $ multipass ls                                      
Name                    State             IPv4             Image
myserver              Stopped           --               Ubuntu 18.04 LTS
[~] $ multipass info myserver
Name:           myserver
State:          Stopped
IPv4:           --
Release:        --
Image hash:     ae2c9391b71a (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
[~] $ multipass start myserver
start failed: The following errors occurred:                                    
Instance stopped while starting
[~] $ multipass version         
multipass  1.0.0+mac
multipassd 1.0.0+mac
```

**Comment by setempler** [comment]
same here

**Comment by setempler** [comment]
after I have cleaned up the entry of my instance `cloud` in

`/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`

the re-launch and start was going w/o problems.

**Comment by Saviq** [comment]
@setempler, @moonlight16 couldn't you `multipass remove --purge` those instances?

**Comment by moonlight16** [comment]
@Saviq I no longer have my system in that state.  However IIRC I could remove/purge the instances, but I couldn't recreate them with the same name as I described.

**Comment by Saviq** [comment]
OK I'll close this as we don't have enough info to act on it. Please reopen / report anew if anyone stumbles on this again.
