### ISSUE TITLE
Why does `vboxmanage list vms` command not show VMs started by multipass?

### ISSUE THREAD

**Issue by indrayam** [canonical/multipass#1345]
Setup:
- MacOS Catalina 10.15.3
- VirtualBox 6.1.2
- multipass  1.0.0+mac
- multipassd 1.0.0+mac

My local.driver setting is `virtualbox`. I launched a VM using multipass CLI on my Mac. `multipass list` shows a VM. I can `multipass ssh` into it. But when I run `vboxmanage list vms` command, or try to see the VM in VirtualBox UI, I do not see it.

![vboxmanage-multipass](https://user-images.githubusercontent.com/6824/74089943-47d49f80-4a74-11ea-970d-a3c7bf2d1fda.png)

Thoughts?

**Comment by Saviq** [comment]
@indrayam on macOS you need to run sudo vboxmanage list vms - the daemon runs as the root user and that's where you need to look for them.

**Comment by indrayam** [comment]
Thanks @Saviq. That indeed did the trick. However, it begs the question: Is there a way to run multipass and multipassd as a regular (non-root) user so that I do not have to run 

`vboxmanage list vms` and 
`sudo vboxmanage list vms`

to see all my VirtualBox VMs.

In any case, I do appreciate you helping me solve this riddle. I was really stumped where my VirtualBox VMs were 😄 

~Anand

**Comment by Saviq** [comment]
My answer here: https://github.com/canonical/multipass/issues/1262#issuecomment-585278027

**Comment by BugHe** [comment]
I run VirtualBox 6.1.18 on Windows 10 Pro ×64 (20H2).
The virtual machines are USER-specific, hence it is absolutely mandatory to run the command line console as the correct user, otherwise VirtualBox doesn't see any virtual machine.
Because I installed virtual machines from my normal account, I must NOT run the console with administrator privileges. It's probably very analogous on a Linux host.

**Comment by illpillow** [comment]
If anyone is running on Windows and wonder why you can't see the VMs, it's because they are running as SYSTEM account. You can view the machines by running the given command as this account, e.g. by using [PsExec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec):
```sh
PsExec64 -s vboxmanage list vms
```

**Comment by Saviq** [comment]
@illpillow this is documented here:

https://multipass.run/docs/set-up-the-driver#heading--use-virtualbox-to-view-multipass-instances-windows
