### ISSUE TITLE
Is it possible to use multipass without snap?

### ISSUE THREAD

**Issue by cbluth** [canonical/multipass#1366]
Is it possible to install multipass without snap?
Are there build instructions for running it without snap?

**Comment by Saviq** [comment]
Hi @cbluth everything you should need to build and use it is described in [our `README.md` here](https://github.com/canonical/multipass#get-involved).

We're focused on the snap version to reduce the maintenance burden of keeping multiple packaging formats.

Please reopen this if there's something missing. Thanks!

**Comment by ArtPixWebdesign** [comment]
Hello @cbluth , hello @Saviq ,
I was trying to build (won't use snaps, NEVER), and managed to do it, but only removing manually two extra ";" in a C header...
don't know if this can help, but just in case ... :
`
build/_deps/googletest-src/googlemock/include/gmock/gmock-spec-builders.h:1703
GTEST_DISABLE_MSC_WARNINGS_PUSH_(4100)
build/_deps/googletest-src/googlemock/include/gmock/gmock-spec-builders.h:1717
GTEST_DISABLE_MSC_WARNINGS_POP_()
`
Thanks everybody !

**Comment by luisee** [comment]
> 
Hello, could you detail how you managed to install it without using Snap, I'm using Debian and I don't want (and I think I can't) install Snap on it. I really appreciate you being able to detail it.

**Comment by TomashKhamlai** [comment]
Oh, snap!

**Comment by davidshare** [comment]
The problem with snap is that snap-confine is behaving like a demon right now. Can't use any snaps on my computer. It's frustrating. I had to give up tryint to use multipass because of it.

**Comment by pongnguy** [comment]
I want to use cloud-config.yaml from a different directory for creating vm, but snap confine really messes this up.  Would rather install without snap.

**Comment by georgeliao** [comment]
Hi @pongnguy 

> I want to use cloud-config.yaml from a different directory for creating vm, but snap confine really messes this up. Would rather install without snap.

If you just want to launch a vm with a custom cloud-config.yaml, you can simply use `multipass launch --cloud-init <cloud-config.yaml path>`

**Comment by ricab** [comment]
@pongnguy Note that you'd need your cloud-init file to be in your home folder, or an external drive if you `snap connect multipass:removable-media`. Snap confinement does prevent access outside those places.
