### ISSUE TITLE
[win] window size change not respected in Windows Terminal

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1370]
When running `multipass shell` in the upcoming [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701), changing the window size often results in a broken console setup.

Easiest to see with `byobu`, which fills the whole screen.

**Comment by marcodelapierre** [comment]
I am experiencing a similar issue on the mac

**Comment by Saviq** [comment]
Hi @marcodelapierre, we've just fixed this in #1354, can you please try the release candidate from https://github.com/canonical/multipass/pull/1375#issuecomment-589779268 - if that doesn't help, please file a separate issue. Thanks!

**Comment by marcodelapierre** [comment]
thanks @Saviq , just tested, my terminal resizing issue was fixed!

**Comment by townsend2010** [comment]
Boo, [console WinEvents](https://docs.microsoft.com/en-us/windows/console/console-winevents) are not being used in the new Windows Terminal.  Will have to investigate what API it is using and see if there is some way to hook into it.

**Comment by townsend2010** [comment]
Seems we're going to have to redo how we detect window size changes: https://github.com/microsoft/terminal/issues/1811

**Comment by ricab** [comment]
Yeah I was planning to take a look as part of the work to integrate on the windows terminal.

**Comment by ricab** [comment]
I've been investigating this and here are a few conclusions.

WT [supports](https://github.com/microsoft/terminal/issues/3238#issuecomment-543342919) built-in resize events. These [WINDOW_BUFFER_SIZE_EVENT](https://docs.microsoft.com/en-us/windows/console/input-record-str)s really should be triggered [whenever the viewport is resized](https://github.com/microsoft/terminal/issues/281#issuecomment-470692714). IIUC, these "events" can only be obtained from the buffer itself, mixed with the rest of the input, via [ReadConsoleInput](https://docs.microsoft.com/en-us/windows/console/readconsoleinput) or [PeekConsoleInput](https://docs.microsoft.com/en-us/windows/console/peekconsoleinput). However, we use [ReadConsole](https://docs.microsoft.com/en-us/windows/console/readconsole) to get the text, which discards those events. We also use a [flush](https://github.com/canonical/multipass-private/blob/625335bac8659eb8a8f6ad58cae4ba3cddae52c2/src/platform/console/windows_console.cpp#L118), whose purpose isn't clear to me. 

Changing the code to peek into the input events before reading or flushing, I could get the resize ones. However, reacting to a resize there means only updating when there is input. Doing it elsewhere risks loosing the events. I tried that when writing and in a separate thread that would peek periodically and they both missed the events. 

So, that did not seem very feasible. We'd have to change the way we do input reading and perhaps make it asynchronous with ssh comm...

What did work quite well was to ignore the event entirely and just check periodically whether the size had changed (in a separate thread). Timing this, each check took a few microsecond and had no usability impact. Doing it twice per second felt nice to me with both byobu and [mc](https://github.com/canonical/multipass/issues/1395). There is only a tiny delay before the resize is rendered (at most as much as the chosen period).

Alternatively, while WT does not support MSAA events (as @townsend2010 found out), it *should* support UIA, even though they [*don't guarantee anything if you're not attempting to use them for [accessibility] purposes*](https://github.com/microsoft/terminal/issues/1811#issuecomment-508807648). I did not explore this avenue yet.

**Comment by ricab** [comment]
I think I've got something working without any extra thread or accessibility extra :crossed_fingers:
