### ISSUE TITLE
general wierdness on amd

### ISSUE THREAD

**Issue by brettkoonce** [canonical/multipass#1373]
using a large number of cores (32) hung my entire computer yesterday

$ multipass restart iree
restart failed: ssh connection failed: 'Connection refused'                     
$ multipass stop iree                                           
$ multipass list
Name                    State             IPv4             Image
iree                    Running           10.160.37.115    Ubuntu 18.04 LTS
$ multipass restart iree
restart failed: instance "iree" is not running

**Comment by Saviq** [comment]
Hi @brettkoonce, thanks for reporting. Would you please supply the output from `journalctl -u snap.multipass*` so we can have a closer look?

**Comment by brettkoonce** [comment]
[multipass-log.txt](https://github.com/canonical/multipass/files/4231146/multipass-log.txt)

**Comment by brettkoonce** [comment]
bad memory!
