### ISSUE TITLE
Multipass launch with --cloud-init yaml results in initialization timeout if sudo field is set

### ISSUE THREAD

**Issue by adanaila** [canonical/multipass#1379]
**Multipass version:** _1.0.2 snap running on Ubuntu 19.10_

**Command run:**  _multipass launch -n ubuntu-lts-custom --cloud-init cloud-config.yaml_
**Error:**

> launch failed: The following errors occurred:                                   
> timed out waiting for initialization to complete

**cloud-config.yaml**
> users:
>         - name: cookie
>           sudo: true
>           ssh_authorized_keys:
>                  - <valid_key>
> 

**Snap Logs:**
> 2020-02-22T02:18:45Z multipassd[7297]: ssh failed to authenticate: 'Socket error: disconnected'
> 2020-02-22T02:18:46Z multipassd[7297]: ssh failed to authenticate: 'Socket error: disconnected'
> 2020-02-22T02:18:47Z multipassd[7297]: ssh failed to authenticate: 'Socket error: disconnected'
> 2020-02-22T02:18:48Z multipassd[7297]: ssh failed to authenticate: 'Socket error: disconnected'

The issue seems to be the **sudo: true** field. If i remove this field multipass seems to launch the vm with no errors, if I add it, I get the aforementioned errors.

**Comment by townsend2010** [comment]
Hi @adanaila,

Right, setting `sudo: true` is invalid and so cloud-init is failing inside the instance.  Per the cloud-init [docs](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#users-and-groups):

`sudo`: Optional. Sudo rule to use, list of sudo rules to use or False. Default: none. An absence of sudo key, or a value of none or false will result in no sudo rules being written for the user.

It has to to be a rule such as `ALL=(ALL) NOPASSWD:ALL` as seen in this [example](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups).
