### ISSUE TITLE
libfuse3 compatibility: unknown option(s): `-o nonempty'

### ISSUE THREAD

**Issue by fnkr** [canonical/multipass#1381]
I'm trying to mount a local directory in a Multipass VM with a custom image (Fedora).  
`multipass mount` returns the following error:

```
error mounting "foo": Process returned exit code: 1: fuse: unknown option(s): `-o nonempty'
```

This is because libfuse removed the `-o nonempty` option in v3.0.0. Mounting over non-empty directories is now always allowed.

- https://github.com/libfuse/libfuse/commit/0bef21e8543dda7f02b5f4cb3008a7292d249842
- https://github.com/libfuse/libfuse/releases/tag/fuse-3.0.0

This is currently not affecting official images since sshfs still relies on libfuse2 on Ubuntu. However Ubuntu will eventually be affected too.

- https://packages.ubuntu.com/focal/sshfs

https://github.com/canonical/multipass/blob/ad5fe284581318f2b544d546b0c5c9ab1bd45a11/src/sshfs_mount/sftp_server.cpp#L248

My proposal would be to check if FUSE library version is 3.0.0 or above and omit the `-o nonempty` parameter in that case.

```
# hostnamectl | grep "Operating System"
  Operating System: Fedora 30 (Cloud Edition)
# sshfs --version
SSHFS version 3.6.0
FUSE library version 3.6.2
using FUSE kernel interface version 7.29
fusermount3 version: 3.6.2
```

```
# hostnamectl | grep "Operating System"
  Operating System: Ubuntu 19.10
# sshfs --version
SSHFS version 2.10.0
FUSE library version: 2.9.9
fusermount version: 2.9.9
using FUSE kernel interface version 7.19
```

Steps to reproduce

```sh
multipass launch -n fedora https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.raw.xz
multipass exec fedora -- sudo dnf -y install fuse-sshfs
mkdir -p /tmp/foo
multipass mount /tmp/foo fedora:foo
```

**Comment by townsend2010** [comment]
Yep, I have #1328 that will take care of [this](https://github.com/canonical/multipass/pull/1328/files#diff-38074369bf27ac8c942d629f0cf02416R96-R98).

**Comment by Saviq** [comment]
Fixed by #1328

**Comment by fnkr** [comment]
@townsend2010 Does this mean snapd will be required in the future? I'm asking because this would increase complexity a lot (installing snapd, squashfs-tools, kernel-modules, reboot required), also test run duration would increase significantly (this will run as part of a CI pipeline, and downloading/installing several hundred megabytes of packages for snapd costs time and bandwidth).

**Comment by fnkr** [comment]
Ah, now I see: it falls back to using the distro version if snap is not found, thanks!

**Comment by fnkr** [comment]
Tried #1328, works for me, thanks!
