### ISSUE TITLE
i cant get past login

### ISSUE THREAD

**Issue by NeoMatrixYT** [canonical/multipass#1385]

**Comment by NeoMatrixYT** [comment]
so I got it running and it keeps asking me to login and I have no clue what the login is. Im new to the whole VM thing and am using the Hyper-V on my HP ProBook 450 G6. I don't really know what to to and was wondering if anyone could help.
![image](https://user-images.githubusercontent.com/61445767/75216386-d417df80-5761-11ea-845d-f82ef9c688ec.png)

**Comment by Saviq** [comment]
Hi @NeoMatrixYT I can see in the background that you have the shell working already. What are you trying to do in the Hyper-V manager?

**Comment by grybos** [comment]
I have a similar problem. I installed multipass 1.2.1+win on Windows 10 Pro version 1909 with Hyper-V 10.0.18362.1. Initially I had some problems with antivirus and firewall, but nothing serious.

Now I can create and delete instances, but I can't enter them. For example:
`C:\Users\rober>multipass ls`
`Name                    State             IPv4             Image`
`primary                 Running           172.18.17.46     Ubuntu 18.04 LTS`

`C:\Users\rober>multipass shell`
`shell failed: ssh connection failed: 'Timeout connecting to primary.mshome.net'`

`C:\Users\rober>ping primary.mshome.net`
`Pinging primary.mshome.net [172.18.17.46] with 32 bytes of data:`
`Reply from 172.18.17.46: bytes=32 time<1ms TTL=64`
`Reply from 172.18.17.46: bytes=32 time<1ms TTL=64`

`Ping statistics for 172.18.17.46:`
`    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),`
`Approximate round trip times in milli-seconds:`
`    Minimum = 0ms, Maximum = 0ms, Average = 0ms`

So the connection is OK, just the ssh session fails. The "multipass exec" command gives identical results.

When trying to connect via PuTTY, using the IP address, I get the login prompt, but when I enter the default user "ubuntu", the connection is immediately broken with the following error: "Disconnected: No supported authentication methods available (server sent: publickey)", which is fine, as the remote ssh login with passwords is probably disabled by default.

Now, the "primary" instance is visible in Hyper-V GUI and I can use  "Connect" to get a login prompt - as the OP did. However, when I try to login with default "ubuntu" user and null password, I get "Login incorrect" message.

Is there any other way to get inside those instances? Or perhaps the keys did not install correctly?

**Comment by Saviq** [comment]
Hi @grybos yeah, this suggests something went wrong with the initialization of the instance.

Please launch one with your SSH key included via `multipass launch --cloud-init` with these contents:
```yaml
ssh_authorized_keys: <your public key here>
```

You could also try this from an Admin console:
```powershell
PS> ssh -v -i C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd/ssh-keys\id_rsa ubuntu@primary.mshome.net
```

**Comment by grybos** [comment]
Great! Thanks @Saviq for such a quick response. I tried the second option - the Admin console, and it worked. Now I can play around to see what went wrong before.

Thanks a lot :)

**Comment by Saviq** [comment]
I'll close this as the OP never replied and everything seemed in order there.
