### ISSUE TITLE
run multipass exec as user

### ISSUE THREAD

**Issue by alexladerman** [canonical/multipass#1388]
I have a rather large docker-compose command that I have setup as an alias:

`alias startam="multipass start am && multipass exec -v am -- bash -c \"cd /home/am/AdvancedMatching && docker-compose -f docker-compose-local.yml build --no-cache && docker-compose -f docker-compose-local.yml up\""
`

But it I need the exec command to run as the "am" user instead of the default "ubuntu" user.
How could I do that?

Could be related to https://github.com/canonical/multipass/pull/1287

**Comment by ricab** [comment]
Hi @alexladerman, `multipass exec` itself does not support running commands as a different user, but you could execute commands that execute other commands as different users, like `su - <username> -c "<commands>"`.

**Comment by alexladerman** [comment]
Thanks @ricab 

It prompts me for the user's password, how would you pass it in with the alias? 

PS. this is only for local development so password sensitivity is not an issue

**Comment by ricab** [comment]
I am not sure, maybe you are looking for:

**Comment by alexladerman** [comment]
whatever I try appears to execute on the local machine...

```
alias tryam="multipass exec -v am -- sudo -u am echo foo $(pwd) && echo bar $(pwd)"
alias tryam="multipass exec -v am -- sudo -u am \"echo foo $(pwd) && echo bar $(pwd)\""
alias tryam="multipass exec -v am -- bash -c \"sudo -u am echo foo $(pwd) && echo bar $(pwd)\""
```

i get 

```
foo /Users/alex
bar /Users/alex
```

instead of what I want which is 

```
foo /home/am
bar /home/am
```

**Comment by Saviq** [comment]
Hi @alexladerman, neither `sudo` or `su` will change where your command is executed in. You simply have to `cd` where you want to be. But note the important difference between `sudo`, `sudo -i` and `su`:
```bash
$ multipass exec confirmed-bloodhound -- sudo su - michal bash -c "cd ~; pwd"  
/home/michal
$ mp exec confirmed-bloodhound -- sudo sudo -u michal bash -c "cd ~; pwd"
/home/ubuntu
$ mp exec confirmed-bloodhound -- sudo sudo -u michal -i bash -c "cd ~; pwd"
/home/michal
```

**Comment by alexladerman** [comment]
Almost there... except it get

```
➜  am embedam
sudo: no tty present and no askpass program specified  
```

with 

`alias webam="multipass start am && multipass exec -v am -- sudo su - am bash -c \"cd /home/am/AdvancedMatching; sudo docker-compose -f docker-compose-local.yml up --build api-gateway ui nginx\""`

probably the inner "sudo docker-compose" without which I would get

`ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?`

**Comment by Saviq** [comment]
@alexladerman it's probably better to ensure the `am` user has access to your docker installation. It's usually enough to add it to the `docker` group.

I'm going to close this issue as there is nothing wrong with Multipass here.

**Comment by alexladerman** [comment]
Adding it the user to the docker group didn't do it for me, unfortunately.

While I agree it's probably a lack of understanding on my part on how to
construct the command may I suggest something like "multipass shell vm -u
<user>" or at least describing how to do it in the documentation. It's been
a pretty steep learning curve for all the quirks that have stumped me along
the way to getting my application up and running on multipass. Whatever can
be done to give a smoother ride to others who may follow has to be of
benefit ;)
