### ISSUE TITLE
How are genareted the Windows/MacOS installers ?

### ISSUE THREAD

**Issue by touilleMan** [canonical/multipass#1390]
Hi,

I couldn't find any information on how the Windows/MacOS installers (e.g. `multipass-1.0.0+mac-Darwin.pkg` and `multipass-1.0.0+win-win64.exe) are generated.
My guess is those builds are generated by hand with scripts that are not part of the repository, so I'm wondering if there is a legal reason behind this or if your release process hasn't been streamlined yet (no insult here, we all know good softwares take times ^^).

I'm asking this because I'm curious about Windows installers and especially how to handle auto-update within complex softwares.

**Comment by Saviq** [comment]
Hi @touilleMan, we're keeping the macOS and Windows bits of Multipass closed source for now. I can tell you we're using CPack from CMake, though.

FWIW we don't have any auto-update features at the moment, we periodically check for new releases online and have the user download the new installer.

Have a look at https://winsparkle.org/ though.

Closing this for now.

**Comment by touilleMan** [comment]
thanks @Saviq ;-)
