### ISSUE TITLE
bad_optional_access on MacOS

### ISSUE THREAD

**Issue by ramkumarg1** [canonical/multipass#1391]
brew cask install multipass
==> Downloading https://github.com/CanonicalLtd/multipass/releases/download/v1.0.0/multipass-1.0.0+mac-Darwin.pkg
Already downloaded: /Users/gr3/Library/Caches/Homebrew/downloads/aac5cd1b609de9ba90392da72799eb663ba5b2a37d021fc297a49b1264d0e284--multipass-1.0.0+mac-Darwin.pkg
==> Verifying SHA-256 checksum for Cask 'multipass'.
==> Installing Cask multipass
==> Running installer for multipass; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is multipass
installer: Installing at base path /
installer: The install was successful.
🍺  multipass was successfully installed!

multipass launch --name microk8s-vm --mem 4G --disk 40G
launch failed: The following errors occurred:
bad_optional_access

**Comment by oleksdovz** [comment]
Same with me,
VM has state - starting, in vm's log file show vm is booted and ready for work, please check  attached logs
[multipassd.log](https://github.com/canonical/multipass/files/4260747/multipassd.log)
[ubuntu00001-hyperkit.log](https://github.com/canonical/multipass/files/4260750/ubuntu00001-hyperkit.log)

**Comment by Saviq** [comment]
Hi @ramkumarg1 @oleksdovz can you confirm what's your macOS version?

**Comment by ramkumarg1** [comment]
Hi, mine is Mojave 10.14.6 (18G3020)

**Comment by Saviq** [comment]
Hi again guys, @oleksdovz in your VM log we can see:
```
[  133.348372] cloud-init[746]: ci-info: ++++++++++++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++++++++++++
[  133.353282] cloud-init[746]: ci-info: +--------+------+------------------------------+-----------+-------+-------------------+
[  133.358406] cloud-init[746]: ci-info: | Device |  Up  |           Address            |    Mask   | Scope |     Hw-Address    |
[  133.362404] cloud-init[746]: ci-info: +--------+------+------------------------------+-----------+-------+-------------------+
[  133.369485] cloud-init[746]: ci-info: | enp0s2 | True | fe80::68e7:baff:fe6c:7e7d/64 |     .     |  link | 6a:e7:ba:6c:7e:7d |
[  133.373714] cloud-init[746]: ci-info: |   lo   | True |          127.0.0.1           | 255.0.0.0 |  host |         .         |
[  133.378316] cloud-init[746]: ci-info: |   lo   | True |           ::1/128            |     .     |  host |         .         |
[  133.386807] cloud-init[746]: ci-info: +--------+------+------------------------------+-----------+-------+-------------------+
```

Which shows that the VM did not receive its IP from `bootpd`. We have some [docs on troubleshooting that](https://multipass.run/docs/troubleshooting-networking-on-macos), please have a look there.

@ramkumarg1 can you confirm what `multipass list` shows in your case? Thanks!

**Comment by oleksdovz** [comment]
> Hi, mine is Mojave 10.14.6 (18G3020)

➜  
Software:
      System Software Overview:
      System Version: macOS 10.14.6 (18G3020)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

**Comment by elliottpost** [comment]
Same issue here

![Screen Shot 2020-03-03 at 3 11 44 PM](https://user-images.githubusercontent.com/3232219/75820062-4fc8ec00-5d61-11ea-8bcb-681c39aa9f64.png)

**Comment by Saviq** [comment]
Hey all, I'm going to close this now as we've fixed the `bad_optional_access` issue.

I believe yours' are one of the handful "networking" problems [documented here](https://multipass.run/docs/troubleshooting-networking-on-macos) - please go through that document and file another issue with as much details about your networking situation as possible.

Thanks!
