### ISSUE TITLE
[Win10] Midnight commander gui looks weird

### ISSUE THREAD

**Issue by legezam** [canonical/multipass#1395]
Hi,

First of all, thanks for this very nice application, i really enjoy using it.

Secondly, i found that the look and feel of mc is messed even on a fresh installation:
![image](https://user-images.githubusercontent.com/3974359/75585340-23b41f00-5a72-11ea-86a0-f1acc18146c0.png)

Windows 10 Pro insider preview Build 19564.rs_prerelease.200207-1438
I am not using any special locale, i am using EN-US everywhere.
The issue happens in all these cases:
- using win command line
- powershell
- terminal preview 0.9.433.0 (both cmd and ps)

**Comment by Saviq** [comment]
Hi @legezam, would you please try our release candidate [from here](https://github.com/canonical/multipass/pull/1375#issuecomment-592703930)?

It's likely to be an issue that we just fixed recently.

**Comment by Saviq** [comment]
Oh and thanks for the kind words! Glad you're liking it :)

**Comment by legezam** [comment]
> 
> 
> Hi @legezam, would you please try our release candidate [from here](https://github.com/canonical/multipass/pull/1375#issuecomment-592703930)?
> 
> It's likely to be an issue that we just fixed recently.

Indeed, the issue has been fixed, thanks for the quick help! :)

**Comment by legezam** [comment]
One more thing though. When i resize the window, it is messed up again:
![image](https://user-images.githubusercontent.com/3974359/75586115-e81a5480-5a73-11ea-8299-ecc758119fcf.png)

As i see it is being addressed https://github.com/canonical/multipass/issues/1370 here so there is no need for reopening the issue.

**Comment by Saviq** [comment]
Yeah, Terminal is a new player on the block, PS and cmd.exe should behave fine already.
