### ISSUE TITLE
[OSX] Multipass ubuntu won't boot into newly installed kernel

### ISSUE THREAD

**Issue by 0xSeanll** [canonical/multipass#1396]
I launched a Ubuntu instance through cloud-init on my macOS. Then I installed a new kernel (GNU/Linux 5.3.0-40-generic x86_64) using following method:
```
$ sudo apt-get update
$ sudo apt-get install linux-image-5.3.0-40-generic linux-header-5.3.0-40-generic
```
And modified grub options like this:
```
# /etc/default/grub
GRUB_DEFAULT=saved
GRUB_SAVEDEFAULT=true
GRUB_DISABLE_SUBMENU=y
```
I also checked `/etc/default/grub.d/50-cloudimg-settings.cfg` to make sure it won't overwrite the above settings.

Then update grub:
```
$ sudo update-grub
$ sudo grub-set-default 0        # I am sure 0 is the newly install kernel
$ sudo update-grub
$ sudo reboot
```

But Ubuntu keeps booting into the original kernel (GNU/Linux 4.15.0-88-generic x86_64). However, I tried the same process on my Azure instance and it worked just fine.

Then, I tried following "not recommend" methods:

1. Hard code the `GRUB_DEFAULT` option to new kernel (numbers, menuentry id, full name of kernel with or without "Advanced options for Ubuntu>", I tried them all).
1. Delete all files related to older kernel under /boot/grub.
1. Delete all the menuentry related to old in `/boot/grub/grub.cfg`.

And it still did not work. Is there any options specific to multipass that I missed? Or, is this a bug?

**Comment by Saviq** [comment]
Hi @0xSeanll, it's a limitation of our default backend on macOS - [hyperkit](https://github.com/moby/hyperkit) - it can't do UEFI booting, so we're passing the kernel and initrd directly.

We're definitely going to fix it though :)

**Comment by Saviq** [comment]
@0xSeanll you could also switch to the VirtualBox backend (see [our docs on installing on macOS](https://multipass.run/docs/installing-on-macos), where the full boot happens. You'd lose IP connectivity with the instance, though.

**Comment by 0xSeanll** [comment]
Hi @Saviq, how to access the shell after switching to the VirtualBox backend? `multipass shell` and `multipass exec` don't work after switching.

**Comment by 0xSeanll** [comment]
I got it. Just open VirtualBox and the instance are in the virtual machine list.

**Comment by Saviq** [comment]
Hey @0xSeanll `multipass *` should definitely work, you shouldn't ever need to touch VirtualBox. You have to launch new instances, though, as we're not migrating between backends.

**Comment by 0xSeanll** [comment]
Hi @Saviq , I launched an instance using `multipass launch -nus18 -c4 -d30G -m4G -v` after switched to VirtualBox backend, and multipass gave `launch failed: The following errors occurred: us18: timed out waiting for response`. Then I tried `multipass list` and saw that `us18` had been Running. So, I tried `multipass shell us18`, but I got `shell failed: ssh connection failed: 'Timeout connecting to 127.0.0.1'`

I tried several times with different disk, memory and cores allocation, and weirdly, sometimes `multipass shell` worked, sometimes it didn't.

**Comment by haad** [comment]
Any update here ?

**Comment by Saviq** [comment]
@haad you can switch to the `qemu` driver now and that will boot the kernel as installed. Note you will need to recreate your instance.

```
sudo multipass set local.driver=qemu
```

We'll be switching to the QEMU driver by default in due course.

**Comment by RishonDev** [comment]
Any update here? possible to set this as default in the next version?

**Comment by ricab** [comment]
Hi @RishonDev, yes, QEMU will be the default in the next release (but you can of course select it today if you wish).

**Comment by Zhiming-Huang** [comment]
Hi @ricab , will multipass support apple virtualization framework in the future?

**Comment by townsend2010** [comment]
Hi @Zhiming-Huang,

Yes, it already does via `qemu`.  If you need any more help, please open a new issue and we will follow up there.  Thanks!

As such, this issue no longer applies since `hyperkit` is deprecated and will be removed in the next Multipas release.
