### ISSUE TITLE
mount/unmount foreign folder bug

### ISSUE THREAD

**Issue by luis4a0** [canonical/multipass#1405]
This happens when mounting a folder in the client using a trailing slash in the destination path, issuing  `multipass mount path/to/mount diplomatic-lungfish:mountpoint/`.

When trying to unmount it, the path must have the final slash. This is, the command
`multipass umount diplomatic-lungfish:mountpoint/` will work, but
`multipass umount diplomatic-lungfish:mountpoint` won't, the command will print
`"mountpoint" is not mounted"`
`mountpoint" not found in database`.

This also happens if mounting without using a final backslash and trying to unmount using one.

This bug is related to https://github.com/canonical/multipass/issues/1378 .

**Comment by Saviq** [comment]
I think what we can do is apply [`QDir::cleanPath`](https://doc.qt.io/qt-5/qdir.html#cleanPath) to the input, this should give us enough uniformity.
