### ISSUE TITLE
Staging VM?

### ISSUE THREAD

**Issue by strarsis** [canonical/multipass#1407]
Currently, I use Hyper-V Manager for an (Ubuntu) staging VM. 
However, there are always issues with the network.
Is this multipass tool suitable for spinning up a staging VM? 
Or is this rather something for console-/developer-work like WSL?

**Comment by Saviq** [comment]
Hi @strarsis, Multipass is primarily a developer tool, but there's nothing preventing you from using the instances in whatever way you need. Hope it works for you!
