### ISSUE TITLE
Where are the keys for instances?

### ISSUE THREAD

**Issue by jfmatth** [canonical/multipass#1413]
Hello, i'd like to be able to jump from instance to instance from my primary instance (on Windows), but the not sure the best method.

ideally, i'd shell into primary and then ssh instance@mshome.net easily, but getting denied due to public key's.

Any help is appreciated.

**Comment by Saviq** [comment]
Hi @jfmatth you can (and should) install your own keys into the instances. You can use `ssh-import-id` after the instance is launched, or [using cloud-init](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ssh) through `multipass launch --cloud-init`. See [our `launch` docs](https://multipass.run/docs/launch-command) for more information.

**Comment by jfmatth** [comment]
> Hi @jfmatth you can (and should) install your own keys into the instances. You can use `ssh-import-id` after the instance is launched, or [using cloud-init](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ssh) through `multipass launch --cloud-init`. See [our `launch` docs](https://multipass.run/docs/launch-command) for more information.
> 
> A minimal `cloud-init.yaml` file for this could look like this:
> 
> ```yaml
> ssh_authorized_keys: 
> - ssh-rsa <your-key-here>
> ```

Michal, thank you so much for the ssh-import-id idea, never would have seen that.
