### ISSUE TITLE
dnsmasq.hosts: No such file or directory

### ISSUE THREAD

**Issue by Lapshin** [canonical/multipass#1415]
> Mar 09 16:27:19 H0169 dnsmasq[21518]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory

Multipass does not work until I create this file

**Comment by Saviq** [comment]
Hi @Lapshin there must be something else going on, then - `dnsmasq` creates that file on its own when it serves its first DHCP lease. Can you please show logs from when it wasn't working?

Can you give a little more info about your host?

**Comment by Lapshin** [comment]
Ubuntu 18.04
multipass 1.1.0 1784  stable canonical✓   classic

Snapcraft builds did freeze today on VM init step, I decided to reinstall multipass with --purge flag. And after that, it still was not working. Also I found this in logs

After I created the file all works fine


> Mar 09 16:26:50 H0169 systemd[1]: Stopped Service for snap application multipass.multipassd.
Mar 09 16:27:19 H0169 systemd[1]: Started Service for snap application multipass.multipassd.
Mar 09 16:27:19 H0169 multipassd[21437]: Using AppArmor support
Mar 09 16:27:19 H0169 multipassd[21515]: Applying AppArmor policy: multipass.dnsmasq
Mar 09 16:27:19 H0169 dnsmasq[21518]: started, version 2.79 cachesize 150
Mar 09 16:27:19 H0169 dnsmasq[21518]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Mar 09 16:27:19 H0169 dnsmasq-dhcp[21518]: DHCP, IP range 10.43.219.2 -- 10.43.219.254, lease time infinite
Mar 09 16:27:19 H0169 dnsmasq-dhcp[21518]: DHCP, sockets bound exclusively to interface mpqemubr0
Mar 09 16:27:19 H0169 dnsmasq[21518]: using local addresses only for domain multipass
Mar 09 16:27:19 H0169 dnsmasq[21518]: reading /etc/resolv.conf
Mar 09 16:27:19 H0169 dnsmasq[21518]: using local addresses only for domain multipass
Mar 09 16:27:19 H0169 dnsmasq[21518]: using nameserver 127.0.0.53#53
Mar 09 16:27:19 H0169 dnsmasq[21518]: read /etc/hosts - 7 addresses
Mar 09 16:27:19 H0169 dnsmasq[21518]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
Mar 09 16:27:19 H0169 multipassd[21437]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
Mar 09 16:27:19 H0169 multipassd[21437]: QIODevice::write (QFile, "/var/snap/multipass/common/cache/multipassd/vault/multipassd-image-records.json"): device not open
Mar 09 16:29:53 H0169 multipassd[22141]: Applying AppArmor policy: multipass.qemu-img
Mar 09 16:29:53 H0169 multipassd[22150]: Applying AppArmor policy: multipass.qemu-img
Mar 09 16:29:53 H0169 multipassd[22156]: Applying AppArmor policy: multipass.qemu-img
Mar 09 16:29:54 H0169 multipassd[21437]: process working dir '/snap/multipass/1784/qemu'
Mar 09 16:29:54 H0169 multipassd[21437]: process program 'qemu-system-x86_64'
Mar 09 16:29:54 H0169 multipassd[21437]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/snapcraft-factory-computer-daemon/ubuntu-18.04-minimal-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 2, -m, 2048M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:c6:b6:80, -netdev, tap,id=hostnet0,ifname=tap-98aa52ddbe0,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/snapcraft-factory-computer-daemon/cloud-init-config.iso'
Mar 09 16:29:54 H0169 multipassd[21437]: qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Mar 09 16:29:54 H0169 multipassd[22179]: Applying AppArmor policy: multipass.snapcraft-factory-computer-daemon.qemu-system-x86_64
Mar 09 16:29:54 H0169 multipassd[21437]: process started
Mar 09 16:29:54 H0169 multipassd[21437]: QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 11, "major": 2}, "package": "(Debian 1:2.11+dfsg-1ubuntu7.23)"}, "capabilities": []}}
Mar 09 16:29:54 H0169 multipassd[21437]: QMP: {"return": {}}
Mar 09 16:29:58 H0169 multipassd[21437]: QMP: {"timestamp": {"seconds": 1583760598, "microseconds": 78149}, "event": "NIC_RX_FILTER_CHANGED", "data": {"name": "net0", "path": "/machine/peripheral/net0/virtio-backend"}}
Mar 09 16:33:52 H0169 multipassd[21437]: Cannot open ssh session on "snapcraft-factory-computer-daemon" shutdown: failed to determine IP address
Mar 09 16:33:52 H0169 multipassd[21437]: Shutdown request delayed for 10 minutes
Mar 09 16:34:59 H0169 multipassd[21437]: Received signal 15 (Terminated)
Mar 09 16:34:59 H0169 multipassd[21437]: Goodbye!

**Comment by Saviq** [comment]
Hi @Lapshin I think the creation of the file was unrelated. To confirm, can you:
```
snap stop multipass
rm /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts
snap start multipass
```
Then confirm whether Multipass works still? If not, can you confirm that `dnsmasq` is running? You should be able to see it in `systemctl status snap.multipass.multipassd` under "CGroup:".

**Comment by Lapshin** [comment]
Yes, it does not reproduce with deleted file.
But when the problem was, I tried to stop/start multipass (it did not help)

I do not know how to reproduce this behavior. If it appears I will notice you. Also could you please tell me what debug will be helpful in this case?

**Comment by Saviq** [comment]
Hey @Lapshin looking at the log it's as if the instance never asked for a DHCP address… either the instance didn't boot properly or networking got messed up. Are you running any firewall software maybe?

**Comment by Saviq** [comment]
Hi @Lapshin I'll close this since we didn't get feedback in a while. Please let us know if you still have this problem and answer the questions above.

Thanks!
