### ISSUE TITLE
Multipass mounted volume frozen

### ISSUE THREAD

**Issue by ouladck** [canonical/multipass#1431]
After linking my volume for example:

`multipass mount /home/me/local instance:/home/ubuntu/remote`
every it's work as expected until now.
but when I use `npm i`
I can enter to the mounted volume but not the folder I `run npm i` in

**To Reproduce**
How, and what happened?
1.`multipass mount /home/me/local instance:/home/ubuntu/remote`
> I use zsh you need to install it
2. `multipass exec instance -- zsh`
3. `git cloning some repo I use a private one`
4. `npm i`
5. then terminal get frozen in this folder
```
➜  client git:(master) ✗ npm i
[..................] / rollbackFailedOptional: verb npm-session d373eb3d5ab7d6f9

^C
```

**Expected behavior**
to work that's it

**Logs**
no log

**Additional info**
 - OS: Ubuntu 19.10
- `multipass version` : 1.1.0

- `multipass info --all`:
```
Name:           instance
State:          Running
IPv4:           10.165.104.3
Release:        Ubuntu 18.04.4 LTS
Image hash:     3c3a67a14257 (Ubuntu 18.04 LTS)
Load:           5.00 4.99 3.95
Disk usage:     3.4G out of 4.7G
Memory usage:   356.3M out of 985.1M
Mounts:         /home/karim/local => /home/ubuntu/remote
                    UID map: 1000:default
                    GID map: 1000:default

```

**Additional context**

**Comment by Saviq** [comment]
Hi @karim88, could you please try the package from #1328: `snap refresh multipass --channel edge/pr1328`? It's using a different `sshfs` than what's in the archive - but please try in a new instance to ensure that took effect.

Could you also supply us with your `package.json` file so we can try and reproduce? Thanks!

**Comment by karim88** [comment]
Hi @Saviq thanks for answering i will try and check,
you don't need `package.json` to reproduce it,
I did reproduce it with different projects (different `package.json`),
when using `npm run` or `npm i` or even `yarn` I get the same problem and It take very long time before I can use terminal

**Comment by karim88** [comment]
Thanks alot @Saviq now everything works fine in the existing instances.
