### ISSUE TITLE
[mount] apparmor denial accessing files in a mount

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1436]
Could this be a bug?

I am running Windows 10 and see the same issue:

```
Mounts: c:/ => /c-drive
            UID map: -2:default
            GID map: -2:default
```

It looks like the cause of processes that try to access files in the mount getting 'permission denied' for Read access to files.  Here is syslog when I start named with a config file in mount:

```
Mar 17 14:28:14 mysys named[2300]: loading configuration from '/c-drive/local/named.conf'
Mar 17 14:28:14 mysys named[2300]: open: /c-drive/local/named.conf: permission denied
Mar 17 14:28:14 mysys kernel: [ 2250.379791] audit: type=1400 audit(1584473294.206:27): apparmor="DENIED" operation="open" profile="/usr/sbin/named" name="/c-drive/local/named.conf" pid=2300 comm="isc-worker0000" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000
```
I have read #1346 (and others covered by 'is:issue is:open map' ), and I don't think they are the issue.

I don't code C or it's variants, but, will be happy to collaborate from a test bed perspective if I can.

hth,

David

_Originally posted by @dbotham in https://github.com/canonical/multipass/issues/1200#issuecomment-600338835_

**Comment by Saviq** [comment]
Hi @dbotham I created a new issue from your comment.

Looking at the logs, it's AppArmor denying `named` access to that file, which suggests it's not something Multipass is doing.

Can you confirm that whatever user is running `named` can access the file OK, and that it only breaks when it's being started as a daemon? It suggests it gets an AppArmor profile applied that doesn't allow it to access that path, whether it's a mount or not.

Another way to confirm that would be to `multipass unmount mysys` and place the `named.conf` file in that same path without mounting.

**Comment by dbotham** [comment]
Hi @Saviq 

Thanks for the quick response and insight.  You are correct on the AppArmor point.  We removed the app and named had no issues (and named did have a config in /etc/apparmor.d/.  We don't need / want what AppArmor offers for our purposes, so we are good. 

If you would like though, we I can look into seeing if we can configure AppArmor to work correctly to rule out compat / bug issues with MP... Please let me know.

Thank you,

David

**Comment by Saviq** [comment]
Hi @dbotham thanks, glad you got it working. Another option would be to modify the profile to suite your needs - I don't think it can be done "globally". There is nothing specific to Multipass in this problem - if you ran on bare metal and try and have `named` access that path, it would fail in the same way.

I'll close this - please reopen if you think there's something more that we could be doing. Thanks!
