### ISSUE TITLE
snapcraft –debug weird behaviour with multipass builds

### ISSUE THREAD

**Issue by keshavbhatt** [canonical/multipass#1438]
**Describe the bug**
Hi,
I have noticed distinct behaviour of ‘snapcraft --debug’ command on ubuntu 16.04, In one case it debugs whatever is going on while building snap in VM using multipass while, sometime it shows nothing after “Launching VM…” .

Documentation says that --debug option will show text from Vm as soon as any error will occur. Which is opposite of case one where it debugs everything to host terminal.

I saw snapcraft --shell option too which is also not consistent in its behaviour. Documentation says it will open shell inside VM and will show output of process. while it does nothing after “Launching VM…”

**To Reproduce**
How, and what happened?
1. snapcraft --debug

**Expected behavior**
Consistent behaviour of --debug and --shell arguments to snapcraft

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Ubuntu 16.04.6 LTS
- `multipass version` : snapcraft, version 3.10.2+git4.g9c6d1cc0

**Comment by Saviq** [comment]
Hi @keshavbhatt, thanks for reporting.

Can you try and confirm whether Multipass itself behaves ok? Here's [a primer on basic operation](https://multipass.run/docs/working-with-instances).

Could you also say why you're using non-stable snapcraft? Could you try with the one from the `stable` snap channel?

**Comment by keshavbhatt** [comment]
I will do what you have requested and will provide updates on this shortly. 
thanks

**Comment by keshavbhatt** [comment]
I updated both multipass and snapcraft to stable, and i will be building snaps after finishing my projects. Till than am closing this issue.
