### ISSUE TITLE
Function not implemented error on os.link call

### ISSUE THREAD

**Issue by kalikiana** [canonical/multipass#144]
Snapping `demos/opencv` from the Snapcraft source tree which is mounted into the instance via `multipass mount` fails while staging the "example" part. It seems like hard linking doesn't work.

> Staging example 
> Traceback (most recent call last):
>   File "/home/ubuntu/dev/snapcraft/snapcraft/file_utils.py", line 166, in link_or_copy
>     os.link(source_path, destination, follow_symlinks=False)
> OSError: [Errno 38] Function not implemented: '/home/ubuntu/dev/snapcraft/demos/opencv/parts/example/install/usr/share/doc/libdrm-nouveau2/changelog.Debian.gz' -> '/home/ubuntu/dev/snapcraft/demos/opencv/stage/usr/share/doc/libdrm-nouveau2/changelog.Debian.gz'
> [...]
>   File "/usr/lib/python3.5/shutil.py", line 251, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/lib/python3.5/shutil.py", line 112, in copyfile
>     os.symlink(os.readlink(src), dst)
> FileNotFoundError: [Errno 2] No such file or directory: '../libdrm2/changelog.Debian.gz' -> '/home/ubuntu/dev/snapcraft/demos/opencv/stage/usr/share/doc/libdrm-nouveau2/changelog.Debian.gz'

**Comment by townsend2010** [comment]
Hard linking is an sftp extended command that uses the "hardlink@openssh.com" submessage.  Will implement this in our sftp server implementation.
