### ISSUE TITLE
Icon in title bar doesn't work at 200% scale

### ISSUE THREAD

**Issue by dhenrich** [canonical/multipass#1440]
With Multipass 1.1 on focal on a 4k display with a scale set to 200% (default) the icon doesn't scale properly and actually extends beyond the bar. Attached is a photo example.
![multipass-icon-bug](https://user-images.githubusercontent.com/326478/77261664-0ed83f00-6c5e-11ea-9064-91413636f6d0.png)

**Comment by vanvugt** [comment]
Sounds like https://bugs.launchpad.net/bugs/1832793 which has a [fix coming upstream](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/0a1b7256d90297b19b9de4acb6d07027ae09679a).

**Comment by Saviq** [comment]
@dhenrich could you please try the upcoming fix from http://deb.debian.org/debian/pool/main/g/gnome-shell-extension-appindicator/gnome-shell-extension-appindicator_33-1_all.deb ?

**Comment by 3v1n0** [comment]
This is fixed by https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/8b8455906f2b126031e5899e2b3e7ce6c247cab7

**Comment by Saviq** [comment]
Not our bug :)
