### ISSUE TITLE
Support adding a primary profile to Windows Terminal

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#1449]
The user will be able to (de)activate this via a new setting, with the key: ~~`client.windows-terminal.add-profiles`~~ `client.apps.windows-terminal.profiles` (see [this](https://github.com/canonical/multipass/issues/756#issuecomment-621127639)):
- `client.apps.windows-terminal.profiles=primary` to enable
- `client.apps.windows-terminal.profiles=none` to disable

We'll interface with Windows Terminal via its configuration file: `profiles.json`. We'll look for it in its expected location, equating its presence to whether Windows Terminal is installed. We'll then try to add/enable or hide the primary profile according to the setting.

However, the success of the set operations above will not depend on this file. Instead, the multipass CLI (GUI?) client will keep trying to honor the current setting whenever it quits, logging errors or warnings when it can't (including right after the set operation):
  - a warning will be logged if the setting is enabled but the file isn't found
  - if the file exists but is unreadable or has bad contents...
    * ... an INFO will be logged if the state is "none"
    * ... an ERROR will be logged otherwise.

As the procedure to enforce the setting itself, the error handling above will be independent of what command is executed (right?).

This scheme can be extended in the future to have profiles for all instances, with a value "all".

This setting shall only be available on Windows.

**Comment by ricab** [comment]
After many discussions, this describes what I understand is the design goal. @Saviq, could you please confirm if this matches what you have in mind? 

Also, WDYT about the points with question marks? 

In particular, on the question of when to sync. Notice that:
  - on quit &rarr; fits nicely into all commands, so nothing else needed for set, but state updating delayed for longer
  - on start &rarr; special handling needed in set (and launch, etc. in the future)
  - both &rarr; duplicated warnings/errors

And on the question of the errors/warnings being the same everywhere, that would allow us to just log in place. Otherwise, if you want different handling in different commands, we'd have to throw specific exceptions for the different cases and handle them in the commands.

**Comment by Saviq** [comment]
> an error will be logged when the file exists but is unreadable or has bad contents, irrespective of the current setting.

I'm on the fence whether we should suppress that when the setting is "none". I'm thinking of the scenario when Terminal changes its schema in an incompatible way. Disabling our integration should suppress the error I'm thinking. So if `none`, no errors / warnings logged. At least we should reduce log severity, so it doesn't show up by default.

> As the procedure to enforce the setting itself, the error handling above will be independent of what command is executed (right?).

I'm not quite sure what you mean here.

> - on quit → fits nicely into all commands, so nothing else needed for set, but state updating delayed for longer and opposite to what we do with autostart
> - on start → special handling needed in set (and launch, etc. in the future)

"On quit" makes sense for the CLI - that's when any state changes will be done. Longer term, in the GUI we should probably do it on start and periodically, too.

Are we worried about two processes writing the profiles at the same time? Probably not, if we do it atomically (write to a temp file, rename to the target). If we are worried, we may need to implement some kind of locking in a private location.

**Comment by ricab** [comment]
> I'm on the fence whether we should suppress that when the setting is "none". I'm thinking of the scenario when Terminal changes its schema in an incompatible way. Disabling our integration should suppress the error I'm thinking. So if none, no errors / warnings logged.

Right, that's a good point. Normally the user shouldn't be nagged about `profiles.json` if integration is disabled. But I think you are on the fence because that does not seem to apply generally, if you only consider the end state: if the user sets `none` to remove existing profiles and we fail to remove them, then they should be warned, don't you think? So the movement would matter.



> >   As the procedure to enforce the setting itself, the error handling above will be independent of what command is executed (right?).

> I'm not quite sure what you mean here.

In the sync function, do I log or do I throw? 

Do we want the same severity and msg in all CLI commands and in any GUI janitor? If so, I can just log in the sync operation. Testing checks the contents of mocked error streams directly. 

Or do we want to handle the same problems differently depending on further context (e.g. whether we are in the GUI or CLI, whether we are executing `set` or `launch`...) If so, the sync operation needs to throw different exceptions for different types of problems, so that they can be caught and handled higher in the stack, where that context is available. Full coverage would require testing a) that the sync operation throws the right things and b) that CLI commands (or GUI caller) log as intended, which requires mocking the streams and the sync operation itself.

> "On quit" makes sense for the CLI - that's when any state changes will be done. Longer term, in the GUI we should probably do it on start and periodically, too.

+1, let's go with that.

> Are we worried about two processes writing the profiles at the same time? Probably not, if we do it atomically (write to a temp file, rename to the target). If we are worried, we may need to implement some kind of locking in a private location.

Good point. I think we need to be worried if we want to DTRT. I am not sure about renaming, another process may be about to commit its own changes, so things would still get lost. A file lock would work for ourselves, which is something, but not Windows Terminal itself.

**Comment by Saviq** [comment]
> But I think you are on the fence because that does not seem to apply generally, if you only consider the end state: if the user sets `none` to remove existing profiles and we fail to remove them, then they should be warned, don't you think? So the movement would matter.

I'm not saying the "movement" doesn't matter, but I'm saying we shouldn't complicate it with those. And I've fell off the fence on the "reduce severity to INFO, if `none`" (of any problems with reading / parsing the file). The user would have seen the problem logged already, and likely disable the integration in response to that.

> In the sync function, do I log or do I throw?
> Do we want the same severity and msg in all CLI commands and in any GUI janitor? If so, I can just log in the sync operation. Testing checks the contents of mocked error streams directly.

Log and abort the sync (whether that's a throw that's caught after - your call of course).

Yes, same log severity.

> > Are we worried about two processes writing the profiles at the same time? Probably not, if we do it atomically (write to a temp file, rename to the target). If we are worried, we may need to implement some kind of locking in a private location.
> 
> Good point. I think we need to be worried if we want to DTRT. I am not sure about renaming, another process may be about to commit its own changes, so things would still get lost. A file lock would work for ourselves, which is something, but not Windows Terminal itself.

The thing is, they'd get lost (if at all) just until the next sync - so the likelihood of this actually becoming a problem is very small. Like, the state would have to change in between two processes reading it - and they would have to be writing it in reverse order. So for some reason the process that started later would have to finish quicker. IMO it's not worth the complexity, especially that this would only handle the case when two Multipass processes are doing it, not if it's something external.

**Comment by ricab** [comment]
> I've fell off the fence on the "reduce severity to INFO, if none" (of any problems with reading / parsing the file).

OK, I am still a bit uneasy about this, but I will do it that way.

> Log and abort the sync (whether that's a throw that's caught after - your call of course).

OK, I'll reconsider this, but probably log directly. If we report it the same way in all cases, we have all the info we need in the sync function itself.

> IMO it's not worth the complexity, especially knowing this would only handle the case when two Multipass processes are doing it, not if it's something external.

Right, ok I will ignore then.

I am updating the top description with these conclusions.
