### ISSUE TITLE
Show vm info after starting

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#145]
It would be nice if `multipass start foo` printed some info about the vm after it has started. 

My use case is that I have to run start, then info or list, to get the IP for ssh.

**Comment by Saviq** [comment]
Why do you `ssh` yourself and not use `multipass shell`?

**Comment by hatched** [comment]
So that I can take advantage of my ssh configs, forwarding etc.

**Comment by albaguirre** [comment]
@hatched, So something like `Launched: equably-united-crane at 10.125.1.2/ffff::0000 ` ?

**Comment by hatched** [comment]
Yeah that would work well for my uses, but maybe something as simple as auto-running `info` on the vm could be implemented.

**Comment by Saviq** [comment]
I don't think this is in scope after all.
