### ISSUE TITLE
snapcraft using multipass creates snaps in old directory

### ISSUE THREAD

**Issue by keshavbhatt** [canonical/multipass#1452]
**Describe the bug**
I snapped an app in [DirectoryA], then i for some reasons changed my mind and decided to snap that app in another directory [DirectoryB].
Snapcraft in this case will output the resulting snap in [DirecotryA] instead of new directory i.e, [DirectoryB].

**To Reproduce**
Described in the bug.

**Expected behavior**
Snapcraft should create new snap in changed directory.
User will have no idea where his snap is going after build.

**Additional info**
 - OS: Ubuntu 16.04
- `multipass  1.1.0
    , multipassd 1.1.0`

**Comment by Saviq** [comment]
Hi @keshavbhatt that would be a snapcraft issue, which fails to realize the source dir changed.

I've filed https://bugs.launchpad.net/snapcraft/+bug/1869604 to track it.

**Comment by keshavbhatt** [comment]
Thabks for reporting this to snapcraft.
