### ISSUE TITLE
cloud-init url

### ISSUE THREAD

**Issue by hemna** [canonical/multipass#1461]
**What are you trying to do?**
I would like to be able to use a cloud-init.yml from a url while launching a new vm 

```
multipass launch -n test -c 2 --cloud-init http://my-home.com/multipass/cloud-init.yml
```

**What's your proposed solution?**
--cloud-init should support http:// files

**Additional context**

**Comment by Saviq** [comment]
Thanks @hemna, that's something we could do indeed.

**Comment by ianbtr** [comment]
Does the URLDownloader class support HTTPS URLs as well?

**Comment by nwneisen** [comment]
It looks like this change died out due to needing tests written. I'd like to finish it up if that's alright.

**Comment by Saviq** [comment]
Sure @nwneisen, you're welcome to it :)

**Comment by krisstern** [comment]
If no one else is currently working on this issue I would like to pick this up.

**Comment by krisstern** [comment]
@Saviq Would that be okay? I don't see any activity regarding this issue since June 2021.

**Comment by Saviq** [comment]
Hey @krisstern, that would be great! You could rebase #1499, or start from scratch altogether.

**Comment by krisstern** [comment]
Yeah, cool @Saviq Let me rebase #1499 and add tests rather than starting from scratch.

**Comment by krisstern** [comment]
I see these lines in the `multipass/tests/test_image_vault.cpp` file that wasn't there when #1499 was first submitted:
https://github.com/canonical/multipass/blob/2f43d15d9963caeee3134dfafba55cb27c147f90/tests/test_image_vault.cpp#L68-L93

Will these be potentially useful for this issue @Saviq?

**Comment by Saviq** [comment]
@krisstern you'd probably be best served using the `MockUrlDownloader`:

https://github.com/canonical/multipass/blob/2f43d15d9963caeee3134dfafba55cb27c147f90/tests/mock_url_downloader.h#L27-L34

**Comment by krisstern** [comment]
Okay thanks for the tip!
