### ISSUE TITLE
Multipass can't get info, start shell, get info. Can only start and stop instance

### ISSUE THREAD

**Issue by dbrennan** [canonical/multipass#1474]
After installing Windows 10 system updates, multipass can no longer seemingly connect to my primary instance.
After playing around some more, creating another instance fixed the connection to the primary.  

Here's what I was seeing:

```
C:\>multipass list
Name                    State             IPv4             Image
primary                 Running           UNKNOWN          Ubuntu 18.04 LTS

C:\>multipass info primary
info failed: ssh connection failed: 'Timeout connecting to primary.mshome.net'

C:\>multipass shell primary
shell failed: ssh connection failed: 'Timeout connecting to primary.mshome.net'

C:\>multipass info --all
info failed: ssh connection failed: 'Timeout connecting to primary.mshome.net'

C:\>multipass version
multipass  1.1.0+win
multipassd 1.1.0+win

C:\>multipass launch -n secondary
Launched: secondary

C:\>multipass info --all
Name:           primary
State:          Running
IPv4:           192.168.72.135
Release:        Ubuntu 18.04.4 LTS
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           0.00 0.01 0.00
Disk usage:     1.9G out of 19.2G
Memory usage:   1.4G out of 1.9G
Mounts:         c:/users/daveb => Home
                    UID map: -2:default
                    GID map: -2:default

Name:           secondary
State:          Running
IPv4:           192.168.72.133
Release:        Ubuntu 18.04.4 LTS
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           0.26 0.13 0.05
Disk usage:     1001.5M out of 4.7G
Memory usage:   96.9M out of 921.3M

```

I'm not sure how to reproduce this.

**Expected behavior**
Not to lose the connection.

**Logs**
There's nothing particularly telling in the logs.  Just a similar error as the console:
[daemon] Cannot open ssh session on "primary" shutdown: ssh connection failed: 'Timeout connecting to primary.mshome.net'

**Additional info**
Windows 10 Pro 1909 18363.720

**Comment by dbrennan** [comment]
I should add I created a new user and added ssh keys in the primary instance so I could connect with ssh with X tunneling which worked.
I didn't try my alternate ssh connection because I didn't have the ip address from info, but realized I could have pulled it from HyperV.

**Comment by Saviq** [comment]
Hi @dbrennan this sounds like MS Internet Connection Sharing (which backs the instance networking) had a stale IP for `primary.mshome.net` - this is a Windows issue that happens from time to time and we've [documented ways to unclog it](https://multipass.run/docs/troubleshooting-networking-on-windows).

I'll close this for now and add a note of this to our new issue page.

**Comment by dbrennan** [comment]
Thank you for the update. It's interesting that creating a new instance unjammed it.  I'll keep an eye out for this happening again.

**Comment by ledlamp** [comment]
similar issue but I get `ssh connection failed: 'Failed to resolve hostname primary.mshome.net (No such host is known. )'`;
can't do anything with primary instance and can't open shell from tray.

stopping primary seems to take forever.

I do have a windows update running so I'll try the troubleshooting once that's all done.

**Comment by pcgeek86** [comment]
Same issue here ... deleted a bunch of entries from the Internet Connection Sharing (ICS) file, but that screwed it up worse. I went into Hyper-V Manager and deleted all the VMs. Then I had to use Multipass CLI to delete and purge the VMs. After that, I was able to proceed with creating more VMs.

**Comment by drewspanning** [comment]
I am seeing this issue on Mac OS as well

**Comment by Saviq** [comment]
@drewspanning this sounds more like #2265, please have a look there for potential solutions (firewall, vpn…).
