### ISSUE TITLE
Boot instances using UEFI

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#1477]
**What are you trying to do?**

I would like to test some of Ubuntu's UEFI configuration, but multipass still launches instances using GPT instead of UEFI.

**What's your proposed solution?**

Not exactly _mine_, but:

```
< ChrisTownsend> Odd_Bloke: After a bit of reading, we need to point qemu to the TianoCore bios in order to support that.
```

(An ideal implementation for my testing would let me select/modify the method used for boot.)

**Comment by anonymouse64** [comment]
Just an FYI this will be necessary in order to boot UC20 images at 1.0 release. We may eventually support booting with traditional bios, but for 1.0 we only will support booting with UEFI. 

AIUI this support will be made possible with future integration with LXD.
