### ISSUE TITLE
macOS: Outdated hyperkit version causing problems

### ISSUE THREAD

**Issue by bagrupe** [canonical/multipass#1484]
**Describe the bug**

When trying to install microk8s the network connection of the VM gets interrupted and ultimately crashes.

**To Reproduce**

Install multipass & microk8s with homewbrew, then run microk8s install

**Additional info**
 - OS: macOS 10.15.4
- `multipass version`
multipass  1.1.0+mac
multipassd 1.1.0+mac
**Additional context**
I found an outdated version of hyperkit:

sudo "/Library/Application Support/com.canonical.multipass/bin/hyperkit" -v
hyperkit: v0.20180621-2-g9ef4eb-dirty

According to the hyperkit github page, 0.20200224 is required for macOS Catalina.

Can you please upgrade the included hyperkit for the next release?

**Comment by Saviq** [comment]
```
According to the hyperkit github page, 0.20200224 is required for macOS Catalina.

Can you please upgrade the included hyperkit for the next release?
```

We certainly should, can you please point at where you read about this requirement? Thanks.

**Comment by bazgr** [comment]
Hi, I found at least https://github.com/moby/hyperkit/issues/267 re: Catalina

I tried to workaround the issue by manually upgrading hyperkit to no avail though. I guess there might be an additional problem with the 10.15.4 supplemental update...

**Comment by townsend2010** [comment]
Closed by https://github.com/canonical/multipass-private/commit/51bc9e88e52bbe8d1a62118ff9dc9776f293890b.
