### ISSUE TITLE
Unhelpful "bad file" error when `--cloud-init` file is missing

### ISSUE THREAD

**Issue by supreet21** [canonical/multipass#1486]
**Describe the bug**
Describe what your problem is.
C:\Windows\system32>multipass launch -n ubuntu-lts-custom --cloud-init cloud-config.yaml
error loading cloud-init config: bad file

**Comment by Saviq** [comment]
Hi @supreet21, can you please attach your `cloud-config.yaml`?

**Comment by supreet21** [comment]
can u guide me to the how to get the cloud-config.yam? unable to get it.

**Comment by townsend2010** [comment]
Hey @supreet21,

The `cloud-config.yaml` is where ever you created it.  If you _didn't_ create one, then don't use the `--cloud-init cloud-config.yaml` option during `launch`.

**Comment by Saviq** [comment]
Oh so this suggests the "bad file" error just means the file doesn't exist… We should have a clearer error.

**Comment by supreet21** [comment]
ok, thanks @townsend2010 I got the problem. sorry to bother you for this

**Comment by Saviq** [comment]
@supreet21 we'll keep this issue about the error, which should have told you that the file doesn't exist.

**Comment by townsend2010** [comment]
Closed via c80b31f.
