### ISSUE TITLE
Use local mirrors

### ISSUE THREAD

**Issue by just1689** [canonical/multipass#1487]
**What are you trying to do?**
Downloading the Ubuntu iso

**What's your proposed solution?**
Ensure when Multipass downloads the ISO it uses the local mirrors.

**Comment by townsend2010** [comment]
Hi @just1689,

We do not download ISO images during `launch`. We download [cloud images](https://cloud-images.ubuntu.com/) and there are no mirrors for those. If you are using `multipass launch http://some.download.place`, then you are in control of the URL here.
