### ISSUE TITLE
Access to DEV and RC for MacOS

### ISSUE THREAD

**Issue by dsvmacdonald** [canonical/multipass#1498]
**What are you trying to do?**
I have issue with building VMs when CPUs specified.  I see that this was fixed in a DEV build but daily builds are not available for MacOS. 

**What's your proposed solution?**
Please create MacOS install packages for DEV and RC builds.

**Comment by genevera** [comment]
Running into this myself; there are no instructions for building on macos and I can't compile it in linux given that ubuntu via multipass /was/ my linux vm.

**Comment by Saviq** [comment]
Hi @dsvmacdonald, @genevera, the current development version is always published on [the latest commit in master](https://github.com/canonical/multipass/commit/f1d51cd8f8918178292795bbd3235184e7bca09d#comments):

![image](https://user-images.githubusercontent.com/231077/79830965-d33cac00-83a6-11ea-8717-36b209324aba.png)

The same for [the `release/*` branch](https://github.com/canonical/multipass/commits/release/1.2):

![image](https://user-images.githubusercontent.com/231077/79831069-03844a80-83a7-11ea-8759-d25aa71a69a3.png)

Just click on the ![image](https://user-images.githubusercontent.com/231077/79831116-18f97480-83a7-11ea-9235-83c338032614.png) icon to get to the commit by @multipass-ci-bot :)

**Comment by genevera** [comment]
Thank you!
