### ISSUE TITLE
Disable sshfs file caching when mounting a folder. 

### ISSUE THREAD

**Issue by RoelTiny** [canonical/multipass#1502]
I would like to easily be able to disable sshfs file caching when mounting a folder. 
Reason being that changes to files often take between 10 to 20 seconds to register for the vm.

Currently I've set up a script that creates a nfs folder mount from the vm to the host machine but this is kind of cumbersome and requires me to re-run the script when I switch network.

Maybe this can be fixed by adding the ability to add extra options to the 'multipass mount' command.

**Comment by jasonmccallister** [comment]
We are seeing the same on our project that uses multipass, it would be great if we could run something like `multipass set sshfs.cache.enabled=false`.

It might be helpful to also use `set` for all the options and when `mount` is used it pulls from what is set in the config.

Another benefit of using `set` is keeping the `mount` command rather simple and only overriding settings when needed.

Some items that would be helpful would be:

- `cache`
- `cache_max_size`
- `cache_timeout`
- `cache_X_timeout`
- `cache_clean_interval`

**Comment by jasonmccallister** [comment]
@RoelTiny would you mind sharing that script so we can perform some local testing?

**Comment by RoelTiny** [comment]
@jasonmccallister of course, it is working on macOS 10.15.

I wanted to add to bash scripts but that's not allow and after failing a bit with adding it as code in this text field....

Please find 2 docx file attached, hope it helps.

[createyourvm.docx](https://github.com/canonical/multipass/files/4734632/createyourvm.docx)
[provisioningyourvm.docx](https://github.com/canonical/multipass/files/4734633/provisioningyourvm.docx)

**Comment by townsend2010** [comment]
I have a PR up at #1654 that sets the cache timeout to 3 seconds.  This is looking like it could be a good compromise between performance and getting file updates until we can develop a better solution using a configuration-type system.
