### ISSUE TITLE
Failed to start instance: virtio_net: Could not create vmnet interface

### ISSUE THREAD

**Issue by asevans** [canonical/multipass#1505]
**Describe the bug**
I'm unable to start any multipass instances

**To Reproduce**
How, and what happened?
1. plug a TOTU 8-in-1 USB-C Hub into computer
1. `multipass launch --name foo --mem 4G --disk 40G`

**Expected behavior**
Instance should start

**Logs**
From /Library/Logs/Multipass/multipassd.log:
```
[2020-04-22T15:48:52.377] [info] [foo] fcntl(F_PUNCHHOLE) failed: host filesystem does not support sparse files: Operation not permitted
[2020-04-22T15:48:52.381] [info] [foo] virtio_net: Could not create vmnet interface, permission denied or no entitlement?

[2020-04-22T15:48:52.382] [info] [foo] process state changed to NotRunning
[2020-04-22T15:48:52.382] [info] [foo] process finished with exit code 1
```

**Additional info**
 - OS: macOS 10.15.4
```
❯ multipass version
multipass  1.1.0+mac
multipassd 1.1.0+mac
```

**Additional context**
Removing the USB C hub allows multipass to successfully launch containers again

**Comment by Saviq** [comment]
Hi @asevans, what about if you use a different `--name`? Or skip it altogether?

We've seen this issue a couple times, but couldn't get what's going on. I'm starting to think it's reusing the name that's ultimately causing this.

**Comment by asevans** [comment]
@Saviq neither using a unique `--name` nor omitting it makes any difference.  Same error.

**Comment by asevans** [comment]
I forgot to note in the original report, this problem also applies to restarting previously created instances.  If I have an instance stopped and plug in my USB-C hub, they can't start anymore.

Unfortunately, I don't have any other USB-C hub to test with.

**Comment by Saviq** [comment]
Thanks @asevans… this is a bit crazy. Your hub has Ethernet in it, which somehow must make macOS / hyperkit confused about the networking setup. Have you tried rebooting with the dock plugged in? Or restarting Multipass when it is plugged in?

```console
$ sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
$ sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
```

**Comment by asevans** [comment]
@Saviq I tried restarting with the hub plugged in and also restarting multipassd: no luck.

**Comment by fesplugas** [comment]
Same problem here but no USB-C hub involved. I've uninstalled TunnelBlick just in case but I still have the same issue. As a workaround I've installed VirtualBox but I'm not getting an IPv4.

```shell
$ multipass list            
Name                    State             IPv4             Image
moving-lab              Running           N/A              Ubuntu 20.04 LTS
```

**Comment by fesplugas** [comment]
Fixed by disabling the "Internet Sharing" option.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2720/81973470-79857580-9624-11ea-9333-16d6d07b02a2.png">

**Comment by asevans** [comment]
Disabling "Internet Sharing" for my "USB 10/100/1000 LAN" fixed the problem.  I'm not sure why that was turned on, because it wasn't intentional.

If this is a hyperkit issue, it might be worth at least documenting this issue.

**Comment by Saviq** [comment]
@asevans we obviously will!

Thanks @fesplugas for this hint!

**Comment by jen20** [comment]
I've just observed the same here on macOS 10.15.4 - disabling internet sharing allows Multipass to start instances.

**Comment by AdamTheLang** [comment]
This is infuriating. Keeping me from using multipass on my server. Is there any inkling of a workaround?

**Comment by Saviq** [comment]
@AdamTheLang did you see the comments above? Disabling Internet Sharing in the Sharing settings should make it go away.

**Comment by AdamTheLang** [comment]
@Saviq I did in fact see it. It's not an option for me, as I use that server as a gateway machine for its own subnet. Unless you can suggest some other way of configuring a Mac as a router/DHCP server that does not cause this issue?

**Comment by Saviq** [comment]
@AdamTheLang the only option would be [using VirtualBox](https://multipass.run/docs/using-virtualbox-in-multipass-macos), then.

This option enabled prevents the use of the default hyperkit backend.

**Comment by ameenbadri7** [comment]
> Fixed by disabling the "Internet Sharing" option.
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/2720/81973470-79857580-9624-11ea-9333-16d6d07b02a2.png">

I LOVE YOU MAN you save my whole month

**Comment by giuliazanchi** [comment]
Internet sharing is already mentioned as one of the possible causes / factors interfering with networking, so I'm marking this as closed.
