### ISSUE TITLE
Folders are mounted a bit late

### ISSUE THREAD

**Issue by plashenkov** [canonical/multipass#1508]
Hi!

At first, Multipass is a great tool! Thank you, developers, for it!

I'm trying to adapt it for web development as a web server and services provider. Web sites/apps/services I'm working on are mounted from my host machine and Apache is used to serve them. I've found that during VM booting shared folders are not yet ready when Apache tries to start. If to start Apache later, manually, everything is okay. Is there a proper way to fix this? Or maybe it's not possible to workaround this and it should be fixed in Multipass code.

Thank you!

P.S. I've tried to ask this on Discourse first, but it seems I cannot post there—just get an error message.

**Comment by plashenkov** [comment]
I've tried to add to `/etc/fstab` these lines:
```
:/path/on/host /path/on/guest fuse.sshfs defaults,slave,transform_symlinks,allow_other 0 0
```
but no luck.

**Comment by Saviq** [comment]
Hi @plashenkov - that won't work exactly like that, but you can certainly have a custom mount set up like this. You will have to prefix `:/path/on/host` with your host's IP or hostname, and set up your own SSH keys as needed.

Another option to try is to use systemd's dependencies - every mount creates a `path-on-guest.mount` - you may be able to depend on that in your Apache config. Or maybe have a separate one-shot service that will reload Apache when the mount shows up.

**Comment by plashenkov** [comment]
Hi @Saviq!
Thank you for your answer. I still have some questions:
1. Is there any chance Multipass will mount folders earlier right out of the box? Or is current situation optimal for some reason? I think it's very common situation when some services depend on shared folders so it would be a good choice if folders were mounted as early as possible.
2. Regarding `path-on-guest.mount` and Apache config: do you mean to depend systemd Apache service start event on this file created? (I'm not a pro in systemd yet unfortunately. Do I have to specify some rule in corresponding `.service` file?)
3. I've also noticed that `multipass restart` (outside the VM) and `sudo reboot` (inside the VM) sometimes make shared mounts totally empty. If I have two mounts, `multipass restart` can lose one of them (another one is successfully mounted), or both. In this case missing folders are not displayed in `mount` command listing (multipass 1.2.1+mac, Ubuntu 18.04 as a guest OS). Restarting via `multipass stop && multipass start` doesn't have this issue. Should I open a separate issue for that?

**Comment by Saviq** [comment]
Hey,

1. There's currently no way for Multipass to mount stuff earlier, as we need to wait for SSH to be up.
2. Yes, that would be adding something along the lines of:
   ```ini
   [Unit]
   After=path-on-guest.mount
   Requires=path-on-guest.mount
   WantedBy=
   WantedBy=path-on-guest.mount
   ```
   in `systemctl edit apache2.service`. You'll have to experiment.

   You could also have a service like so:
   ```ini
   [Unit]
   After=path-on-guest.mount

   [Service]
   Type=oneshot
   ExecStart=/usr/bin/systemctl restart apache2

   [Install]
   WantedBy=path-on-guest.mount
   ```
3. Please file as a separate issue, yes. Ideally with exact steps that lead to missing mounts. Thanks!

**Comment by plashenkov** [comment]
Thank you! The idea is totally clear. But I can't find the file `path-on-guest.mount`. I've searched entire disk (for symbols from real mount name) and can't see that file. But I can see `/etc/systemd/system/snap-multipass\x2dsshfs-134.mount` file. Maybe something has changed and now `path-on-guest.mount` files are not created?

**Comment by Saviq** [comment]
It's not a file, look at `systemctl status` to find the exact name of the unit.

**Comment by plashenkov** [comment]
Sorry :) yes, `systemctl | grep mount` gives me that unit, it's exactly named like you said. So:

```bash
sudo systemctl edit apache2.service
```

Added:
```ini
[Unit]
After=path-on-guest.mount
Requires=path-on-guest.mount
WantedBy=
WantedBy=path-on-guest.mount
```
Saved. Restarted VM:
```bash
multipass stop && multipass start && ssh primary
```
Still no luck for some reason, Apache is unavailable after VM restart.

Nevertheless, I found this works (instead of binding to `path-on-guest.mount`):
```ini
[Service]
Restart=always
RestartSec=5
```
Well, it works for now. I'll try to investigate why your variant doesn't work for me. Maybe I do something wrong (but hm...)

Let's close it now. Thanks for your time, really appreciate!

**Comment by Saviq** [comment]
@plashenkov sorry, this should have been:
```ini
[Unit]
After=path-on-guest.mount
Requires=path-on-guest.mount

[Install]
WantedBy=path-on-guest.mount
```

But again, untested, so YMMV :)

**Comment by plashenkov** [comment]
Thanks! I've tried it—no success unfortunately. I also tried `Wants=` in `[Unit]`, no success as well. I have two mounts (both are used by Apache in two virtual hosts), so I've tried to specify them all divided by space, still doesn't work. Leaving just one virtual host doesn't solve the problem too. So, I do not know :) Autorestarting of the service works though I do not know if this variant is optimal (but why not—we don't depend on mount names and can connect them without limits and we don't have to touch the service configuration).

**Comment by kilianc** [comment]
For whoever comes here with a similar problem:

```
[Service]
...
ExecStartPre=/bin/sh -c 'while [ ! -f "/path/to/mount/.mounted" ]; do sleep 1; done'
...
```

And put a `.mounted` in your folder, this will wait until the file can be read.
