### ISSUE TITLE
Windows install prompts for Windows Store 

### ISSUE THREAD

**Issue by jfmatth** [canonical/multipass#1510]
**What are you trying to do?**
Install 1.20 on Windows 10 Pro

**What's your proposed solution?**
Windows 10 looks to make sure apps are certified, and if not, prompts to install from the Windows store.  Without it being verified, I have to click "install Anyway".

**Additional context**
Not a huge deal, but not sure how much effort it takes to get the .EXE validated by MS

**Comment by Saviq** [comment]
Hi @jfmatth, are you seeing this with the installer from [our releases page](https://github.com/canonical/multipass/releases)? It's signed, so this is what you should see:

![image](https://user-images.githubusercontent.com/231077/80313712-0ccd4700-87ed-11ea-82ff-beafc69d3de4.png)

Our release candidates are not signed, since they originate from CI directly, maybe you picked up one of those?

**Comment by jfmatth** [comment]
I just downloaded 1.21 from the releases page

![image](https://user-images.githubusercontent.com/289202/80314459-7e35d700-87a6-11ea-9d1c-c9e05777f3bf.png)

And received the same error @Saviq 

When i run the 1.21 .EXE, i still get this

![image](https://user-images.githubusercontent.com/289202/80314501-a6bdd100-87a6-11ea-9d71-62c7269d8696.png)


HTH

**Comment by Saviq** [comment]
OK this is something new completely. Thanks @jfmatth we'll look into it.

**Comment by alazymeme** [comment]
This is a setting within windows and isn't anything to do with the exe being signed or not. It's a features that's turned on by default in Windows 10. Basically it warns you or stops you from installing applications if they aren't from the Windows Store:
![image](https://user-images.githubusercontent.com/12804673/83933014-6cedda80-a7e8-11ea-98e2-5c4c25192c53.png)

**Comment by jfmatth** [comment]
@alazymeme  thank you for the explination.

Would be really cool if this were in the Store since it's such a great product.  For now though, i'll close the ticket.

thanks again for researching.
