### ISSUE TITLE
multipass 1.2.0 falsely claims that Windows 10 Education does not support Hyper-V

### ISSUE THREAD

**Issue by ceri** [canonical/multipass#1511]
**Describe the bug**
Attempt to start a multipass shell on the primary instance using multipass 1.2.0 and Windows 10 Education.  This used to work on 1.1.0.

**To Reproduce**

Steps below captured from within a Windows Subsystem for Linux zsh shell.  I use some shortcuts and aliases which I include for your reference.
The behaviour is not different using the multipass GUI, but it is impossible to capture the output that way.
Hyper-V does work on this system, I can manually start the primary instance using Hyper-V Manager but multipass does not then pick up its IP address so I cannot use that as a workaround.
```
{ceri@ymir}-{~} % mp shell
start failed: Hyper-V is not available on this edition of Windows 10. Please upgrade to Pro or Enterprise edition.
{ceri@ymir}-{~} % psl get-windowsedition -online


Edition : Education



{ceri@ymir}-{~} %

{ceri@ymir}-{~} % mp version
multipass  1.2.0+win
multipassd 1.2.0+win
{ceri@ymir}-{~} % ls -l bin/mp bin/multipass
lrwxrwxrwx 1 ceri ceri  9 Feb 10 09:50 bin/mp -> multipass
lrwxrwxrwx 1 ceri ceri 48 Feb  5 13:41 bin/multipass -> '/mnt/c/Program Files/Multipass/bin/multipass.exe'
{ceri@ymir}-{~} % alias psl
psl='powershell -Command '
```

**Expected behavior**
I expected to get a shell on the primary instance.

**Logs**

See mp.xlsx attached.  Short version, there are no errors in it.

**Additional info**
 - Windows 10 Education, build 19041
```powershell
PS C:\Users\ceri\AppData\Roaming\multipass-gui> multipass version
multipass  1.2.0+win
multipassd 1.2.0+win
PS C:\Users\ceri\AppData\Roaming\multipass-gui> multipass info --all
Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     3c3a67a14257 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         C:/Users/ceri => Home
                    UID map: -2:default
                    GID map: -2:default
```

**Additional context**
N/A
[mp.xlsx](https://github.com/canonical/multipass/files/4538443/mp.xlsx)

**Comment by ceri** [comment]
Apologies for the shell stuff being struck out, I don't really know why that happens but it's a display artefact.

**Comment by Saviq** [comment]
Hi @ceri, we've not changed anything in how this is being determined.

What's your output from these commands?
```powershell
PS> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V
PS> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor
```

NB: [GitHub uses MarkDown](https://guides.github.com/features/mastering-markdown/) for formatting, `~text~` results in ~strike-through~.

**Comment by ceri** [comment]
Hi @Saviq, neither of those commands return any output, but neither does a bunch of nonsense.

PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -online -featurename Microsoft-Hyper-V
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -online -featurename Microsoft-Hyper-V-Hypervisor
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -online -featurename SomethingIJustMadeUp
PS C:\WINDOWS\system32>

It does work though.
PS C:\WINDOWS\system32> get-vm

Name    State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
----    ----- ----------- ----------------- ------   ------             -------
primary Off   0           0                 00:00:00 Operating normally 9.0

PS C:\WINDOWS\system32> start-vm primary
PS C:\WINDOWS\system32> get-vm

Name    State   CPUUsage(%) MemoryAssigned(M) Uptime           Status             Version
----    -----   ----------- ----------------- ------           ------             -------
primary Running 3           1024              00:00:01.8130000 Operating normally 9.0

PS C:\WINDOWS\system32>

**Comment by ceri** [comment]
<img width="480" alt="thatsnotright" src="https://user-images.githubusercontent.com/112671/80360382-287d2f80-8877-11ea-856c-051dd0896c72.png">

OK, so there seems to be a problem with whatever service is supposed to manage this on my machine, so I will go away and worry about that.

Could you please change the error message though?  Windows 10 Education does support Hyper-V and we often have to correct our users when they claim that they need Pro.

**Comment by Saviq** [comment]
@ceri ACK, thanks for looking into it. I will add "Education" to that message now and we'll also work on the checks we make so we're less exclusive.

Maybe it's enough to check that `Get-VM` is a valid cmdlet before going on the hunt for Windows versions and Hyper-V availability.

**Comment by ceri** [comment]
Thanks @Saviq, much appreciated.
