### ISSUE TITLE
Download of Multipass.exe

### ISSUE THREAD

**Issue by Teslassian** [canonical/multipass#1514]
The multipass.exe file repeatedly fails to download/downloads at a few bytes per second. My internet connection is up and running though.

**Comment by Saviq** [comment]
Hi @Teslassian do you mean this url?

https://github.com/canonical/multipass/releases/download/v1.2.1/multipass-1.2.1+win-win64.exe

As you can see it comes from Github, which actually keeps it on Amazon S3… Could it have been a temporary network problem somewhere?

**Comment by Teslassian** [comment]
Indeed, that exact link.  I have made multiple attempts at downloading the .exe, it fails every time – it has been stuck like this for 6 hours already:  It definitely isn’t a problem with my network, everything else works perfectly. You don’t maybe have another download mirror/link where I can download multipass? It would be appreciated immensely! Regards, From: Michał SawiczSent: Wednesday, 29 April 2020 18:29To: canonical/multipassCc: Teslassian; MentionSubject: Re: [canonical/multipass] Download of Multipass.exe (#1514) Hi @Teslassian do you mean this url?https://github.com/canonical/multipass/releases/download/v1.2.1/multipass-1.2.1+win-win64.exeAs you can see it comes from Github, which actually keeps it on Amazon S3… Could it have been a temporary network problem somewhere?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Teslassian** [comment]
solved
