### ISSUE TITLE
Silent installation instructions for Canonical Multipass via Scoop package manager

### ISSUE THREAD

**Issue by pcgeek86** [canonical/multipass#1521]
**What are you trying to do?**

When setting up a new PC, or refreshing my existing PC, I would like to fully automate the installation and configuration of all my applications, including Multipass. I use the [Scoop package manager](https://scoop.sh/) on Windows 10 to install my core set of development tools, and Multipass currently isn't configured as an installable package through Scoop.

**What's your proposed solution?**

Create a silent installation mechanism for Multipass, provide documentation for silent deployment of Multipass en masse, and configure it as a [Scoop manifest](https://github.com/lukesampson/scoop/wiki/Creating-an-app-manifest).

https://github.com/lukesampson/scoop

**Comment by Saviq** [comment]
Hi @pcgeek86, if you can pass arguments to the installer, [/S would mean "silent"](https://nsis.sourceforge.io/Docs/Chapter4.html#silent).

**Comment by pcgeek86** [comment]
Thanks, I will try adding a new Scoop manifest to the ["extras" bucket](https://github.com/lukesampson/scoop-extras). That way, for a fresh install, you should be able to do something like:

```
scoop bucket add extras
scoop install multipass
```

**Comment by gianluca-sabena** [comment]
I install today, but scoop doesn't install multipassd service on windows

How can I install the service multipassd with scoop?

**Comment by gianluca-sabena** [comment]
Done https://github.com/ScoopInstaller/Main/issues/4870
