### ISSUE TITLE
Connection to multipass instance port refused

### ISSUE THREAD

**Issue by binghaong** [canonical/multipass#1529]
## Description
- Installed ElasticSearch on multipass instance (Ubuntu 18.04)
- Installation went successfully
- Was able to reach the ElasticSearch node via curl **within** the instance by running `curl -X GET "localhost:9200/?pretty"`
- The output of the above command is shown below:
```
{
  "name" : "es",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "s3AHvmBuRnOpRcpDr3pJ_w",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

## Problem
- When I try to contact the ElasticSearch instance from **outside** the instance (i.e. via host machine), the connection to the port was refused
- The command I ran was `curl -X GET "<IP_ADDR_OF_INSTANCE>:9200/?pretty"`
- The error I got was 
```
curl: (7) Failed to connect to 10.31.175.205 port 9200: Connection refused
```

## Expected Behaviour
- I had expected the same JSON response as stated above since I should have been able to contact the ElasticSearch instance via the instance IP
- The fact that I was able to contact ElasticSearch within the instance shows that ElasticSearch is running fine.

## Logs
- The multipass logs are attached.
- I noticed that `Mar 03 10:04:12 dexter-0 multipassd[24282]: Unable to determine subnet for the mpqemubr0 subnet` at the start of the logs. Not sure if it is important.

Appreciate any help I can get to resolve this. Never used to have this problem.

## Additional Info
- multipass version: 1.2.0
- multipassd version: 1.2.0
[multipass.log](https://github.com/canonical/multipass/files/4613453/multipass.log)

**Comment by Saviq** [comment]
Hi @binghaong, this is most likely due to ElasticSearch's configuration, which, for security reasons, listens on localhost only.

Run this:
```console
$ multipass exec <instance> -- sudo netstat -anp | grep :9200
```

If it says "localhost", you need to reconfigure ES.

**Comment by binghaong** [comment]
Thanks @Saviq! I will give it a go. Thanks for your advice!
