### ISSUE TITLE
Smarter Windows 10 Home onboarding

### ISSUE THREAD

**Issue by AntonOfTheWoods** [canonical/multipass#1536]
**What are you trying to do?**
Get started as a new Windows 10 Home user. Currently the instructions on the website https://multipass.run/ in the section "Getting Started" make no suggestion you need to perform extra steps with Windows 10 Home. When you follow the instructions per the website, you get the message:

` launch failed: Hyper-V is not available on this edition of Windows 10. Please upgrade to Pro or Enterprise edition.`

**What's your proposed solution?**

multipass can obviously detect that it is being installed on a Windows 10 Home at install time. It can also set the default `local.driver` to virtualbox if it detects it is on Windows 10 Home and also finds an install of VirtualBox.

At the very least, when multipass detects it is on Windows Home, it should print better instructions for getting it up and running rather than "upgrade to Pro", which is obviously not *required* to get it working.

**Additional context**
This should be very easy to implement, and will provide a smoother onboarding experience for new Windows 10 Home users.

**Comment by Saviq** [comment]
Hi @AntonOfTheWoods, thanks for your report. We're actually working on a better installer workflow for this, that will let you know that Hyper-V is unavailable, and let you choose VirtualBox in that case.

**Comment by hsluo** [comment]
1.3.0 installer just disables Hyper-V option on Windows 10 Home, while it can be enabled https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/915
As of 1.2.1 it works.
Are there any known issues that resulted in this decision?

**Comment by AntonOfTheWoods** [comment]
@hsluo , do you mean that you can activate Hyper-V on Win10 Home? If so, I'm pretty sure that is a bug, not a feature, and you should only ever develop hacks like that for your own personal use. That said, I don't really understand why anything needed to get disabled - it could have just defaulted to virtualbox.
That said, I ended up paying full price for a Pro licence - virtualisation is currently very broken with everything except Hyper-V on Win10 (VMWare appear to be getting close), though Hyper-V seems to be a little flakey for me too to be honest (regular Ubuntu 20.04 borks, requiring guest reboot)...

**Comment by hsluo** [comment]
You can activate Hyper-V on Win10 Home. I did that and 1.2.1 works fine. However in 1.3.0 the installer won't let you select the option if you're on Home
![image](https://user-images.githubusercontent.com/780788/85308959-7cf20380-b4e4-11ea-97e0-ac9b957270a0.png)
![image](https://user-images.githubusercontent.com/780788/85307845-fdb00000-b4e2-11ea-9ece-41d374f83632.png)
What I expect is checking Hyper-V availability instead of Windows edition. If it's for some reason (bug or licence issue), I'm totally fine with other options.

**Comment by Saviq** [comment]
@hsluo Hyper-V is _not supported_ on Windows 10 Home, the thread you linked says:

> If I remember correctly it used to be available on the 10 Home edition at one point during a testing phase, but was made a "pro" feature in a later update. You can still enable it on Windows 10 Home, but it takes a couple extra "legally grey area" steps.

In any case, the installer just uses `multipass set local.driver=virtualbox` at the end, when VirtualBox is selected. Some more docs on using VBox with Multipass can be found [in our docs](https://multipass.run/docs/using-virtualbox-in-multipass-windows).

**Comment by madalinignisca** [comment]
HyperV is 100% available on WindowsHome since update version 2004, and with last fixes making it totally stable from 20H2.

I don't understand why the people involved in this project are still talkning about what was on older Windows 10 Home.

Look at Docker for Windows, it even automates the activation of hyperv.

**Comment by AntonOfTheWoods** [comment]
@madalinignisca , that's simply not true. https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

You do realise that Canonical is a company, right? That even if there were some hack to get around Microsoft not wanting people to activate Hyper-V on Win10 Home, they couldn't talk about it, because contrary to you (and me!), they actually do care whether Microsoft's lawyers think something is Ok or not.

That said, as (I guess) you are trying to point out, it may not be necessary for Hyper-V to be "100% available" for multipass to be able to use the underlying Hyper-V infrastructure, as docker does. That's a different thing to what you are claiming but very relevant nonetheless.

@joedborg ?

**Comment by madalinignisca** [comment]
That is not a hack. The docs are not updated. Before you keep referencing to old information, would you please look at what Microsoft did with WSL2, collaborated with Docker to get it working on HyperV and also why it ended up adding hyperv to Windows Home with no hacks?

You do not need Hyper-V Role to use Hyper-V in Windows 10 Home. That is the only component missing that tops up with Hyper-V manager.

Why did Docker manage to get such a nice user experience and with Microsoft's help bring Docker on Windows Home with Hyper-V?

WSL2 works strictly on Hyper-V. Please check updated information from Microsoft.

You can start from here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq
That is also on Microsoft docs website and look at statement: 

> WSL 2 is available on all SKUs where WSL is currently available, including Windows 10 Home.
>
> The newest version of WSL **uses Hyper-V** architecture to enable its virtualization. This architecture will be available in the 'Virtual Machine Platform' optional component._

You are testing against an optional extra component of HyperV which is not needed to get a VM started with it.

**Comment by AntonOfTheWoods** [comment]
@madalinignisca "100% available" implies you can do things like install Windows or FreeBSD. Can you do that with what is available in Windows home without hacks? You can with normal HyperV. That's what 100% means, at least in English!

**Comment by Saviq** [comment]
What WSL2 and docker are using is [Windows Hypervisor Platform](https://docs.microsoft.com/en-us/virtualization/api/), _not_ the Hyper-V feature. "uses Hyper-V architecture" does not mean that complete Hyper-V support is available.

All that said, we are actively looking into using WHP above to support all Windows SKUs. It's not trivial, though, if we want to maintain feature parity.

**Comment by madalinignisca** [comment]
Oh. Now I get it. You've been using the Hyper-V role manager's api to spin instances instead of using Hypervizor Platform api. So multipass is dependent on the manager and not on the lower level platform.

I guess that Virtualbox and VMware used [this](https://docs.microsoft.com/en-us/virtualization/api/) to be able to spin up HyperV based virtual machines on Windows Home also (which actually works).

Well, I do hope there's will be some progress in the near future.

**Comment by user670** [comment]
Sorry to dig up an old post

Just installed it on Windows 10 Home with the installer. Installer had the VirtualBox option, and I *have* selected that option in the installer, but multipass still tries to use Hyper-V when I try to `multipass launch` and tell me that Hyper-V is not available in Home. Can the installer just `multipass set local.driver=virtualbox` if that setting is selected in the installer?

**Comment by ricab** [comment]
Hi @user670, sorry you experienced that, it's a [known bug](https://github.com/canonical/multipass/issues/2179) that is in our roadmap to fix within the next couple of releases.

**Comment by AntonOfTheWoods** [comment]
@ricab did this ever get "fixed"? If so, should it be closed? I ended up buying Win pro and then moving back to Linux so I have no idea whether this is still relevant...

**Comment by Saviq** [comment]
@AntonOfTheWoods our installer checks whether Hyper-V is available now and informs that you need to install VirtualBox if that's selected on install, so indeed this is fixed. Thanks for following up!
