### ISSUE TITLE
[Windows] Multipass spams the Event Viewer with Information-level entries

### ISSUE THREAD

**Issue by grybos** [canonical/multipass#1540]
**Describe the bug**
Multipass logs at least three Information-level events PER SECOND for each instance (either running or stopped). The entries are (in chronological order):

1. [primary] cmdlet: 'Get-VM -Name primary | Select-Object -ExpandProperty State'
2. [primary] Running
3. [primary] cmdlet exit status is 'true'

This seems to be a bit excessive.

**To Reproduce**
1. Start multipass with at least one instance
1. check the Event Viewer -> Windows Logs -> Application

**Expected behavior**
Logging only the important information or changes in status.

**Additional info**
 - OS: Windows 10 Pro ver. 1909
- `multipass version`
multipass  1.2.1+win
multipassd 1.2.1+win
- `multipass info --all`
Name:           primary
State:          Running
IPv4:           172.18.17.43
Release:        Ubuntu 18.04.4 LTS
Image hash:     3b2e3aaaebf2 (Ubuntu 18.04 LTS)
Load:           0.34 0.08 0.03
Disk usage:     1002.6M out of 4.7G
Memory usage:   106.4M out of 921.3M

**Comment by Saviq** [comment]
Hi @grybos you're right, we need to bump those to trace severity, which would not be logged by default.

**Comment by grybos** [comment]
Perfect! Can't wait for the next release. Let me close this :)

**Comment by Saviq** [comment]
Not there just yet ;)

**Comment by piksel** [comment]
This still happens in v1.6.2:
![image](https://user-images.githubusercontent.com/807383/119227922-a1999580-bb10-11eb-8c70-fb39b03ce6f3.png)
At least it's gone down from three to two messages... 😅

**Comment by ricab** [comment]
You're right @piksel, thanks for pointing it out.
