### ISSUE TITLE
Update GUI icon color as monochrome.

### ISSUE THREAD

**Issue by lukeholder** [canonical/multipass#1542]
**What are you trying to do?**
Have the application feel native to the platform. (Windows and Mac)

The GUI menubar icon currently looks like this:
![image](https://user-images.githubusercontent.com/133571/82147908-97044a80-9883-11ea-859a-b22290c839d2.png)

**What's your proposed solution?**
Replace the icon with a monochrome version, or give the GUI app a preference to set the icon to monochrome.

**Comment by Saviq** [comment]
Duplicate of #1240
