### ISSUE TITLE
Static ip address

### ISSUE THREAD

**Issue by bahram-hodjaev** [canonical/multipass#1545]
**What are you trying to do?**
I would like to use a multipass machine with vs code during development.
But from time to time the ip address of the virtual machine is changing.

**What's your proposed solution?**
Offer static ip address for virtual machines

**Additional context**
![Annotation 2020-05-20 094859](https://user-images.githubusercontent.com/3465733/82414084-2e81bd00-9a7f-11ea-8429-27ff91282278.png)

**Comment by Saviq** [comment]
Hi @bahram-hodjaev, is this on Windows? If that's the case, you can use `<instance name>.mshome.net` instead of straight IP address.

And you're right, the IP changes because Windows does not keep a static subnet over reboots, unfortunately.

**Comment by Saviq** [comment]
That said, with bridged networking we'll be adding soon (#118) you'll be able to use a static IP, too.

**Comment by Saviq** [comment]
Duplicate of #1293

**Comment by bahram-hodjaev** [comment]
@Saviq thank you very much!!

**Comment by bahram-hodjaev** [comment]
> Hi @bahram-hodjaev, is this on Windows? If that's the case, you can use `<instance name>.mshome.net` instead of straight IP address.
> 
> And you're right, the IP changes because Windows does not keep a static subnet over reboots, unfortunately.

Yeah, this is happening on Windows
