### ISSUE TITLE
windows: launch asks a question with `stdin=subprocess.DEVNULL`

### ISSUE THREAD

**Issue by cjp256** [canonical/multipass#1553]
**Describe the bug**
On third launch, multipass will ask snapcraft "One quick question..."

**To Reproduce**
How, and what happened?

snapcraft
snapcraft clean
snapcraft
snapcraft clean
snapcraft

**Expected behavior**
What did you expect to happen?

Launch to occur without prompting.

**Additional info**
 - OS: Windows 10
- `multipass version`
1.2.1+win

**Comment by Saviq** [comment]
For reference:
[The relevant piece of code in Snapcraft](https://github.com/snapcore/snapcraft/blob/7d1f7fb24e7f832ad2ccb82d6178dc4a69b6502e/snapcraft/internal/build_providers/_multipass/_multipass_command.py#L46).

A simple reproducer would be something along the lines of:
```python
import subprocess
subprocess.check_call(["multipass", "launch"], stdin=subprocess.DEVNULL)
```
