### ISSUE TITLE
Can't shell into instance - ssh failed to authenticate: 'Socket error: disconnected'

### ISSUE THREAD

**Issue by eliot-akira** [canonical/multipass#1557]
This is not a bug report, but user-caused error. I'm wondering if it's possible to recover from this state.

I edited `/etc/passwd` in the instance to give a new user SSH access, and rebooted. However, I believe I corrupted the file (wrong syntax), and now the `multipass shell` command is not able to SSH into the instance. It (and other commands like `info` and `restart`) displays:

```
ssh failed to authenticate: 'Socket error: disconnected'
```

Could you recommend if/how I could recover this instance? Perhaps there's way, from the outside, to edit that specific file in the instance without starting it..

**Comment by eliot-akira** [comment]
I found what broke it: editing `/etc/ssh/sshd_config` in the instance to add a directive `AllowUsers`. I listed only the additional user, but not `ubuntu` or any other. That makes sense that SSH from host is now failing.

I'm guessing that it's not possible from the host to edit files in an unstarted instance. Fortunately, I already started on a container-based workflow, so I can start over with a new VM.

**Comment by Saviq** [comment]
Hi @eliot-akira it is possible to recover, depending on your host OS. Search for "mount qcow2 image" for your operating system. Let us know if you find something and we can guide you where to find the image (please let us know your OS version).

**Comment by eliot-akira** [comment]
Hi @Saviq, great to hear it's possible to mount an unstarted instance. It gives me hope that I may be able to recover from my mistake. :)

I found a gist for [How to mount a qcow2 disk image](https://gist.github.com/shamil/62935d9b456a6f9877b5), but it's Debian-oriented.

The host is running macOS 10.14.3. I ran `brew install qemu` to install the main command needed, `qemu-nbd`.

The instructions start with `modprobe nbd max_part=8`, Enable NBD on the Host. I see, NBD stands for "Network Block Device". On macOS, I couldn't find `modprobe` - apparently the equivalent is `kextutil`, ah right, it deals with kernal extensions.

Looking at the [manual for `qemu-ndb`](https://www.qemu.org/docs/master/tools/qemu-nbd.html), I think I'm getting closer.

**Comment by Saviq** [comment]
Hey @eliot-akira there's another potential option - since you created an extra user, did you set a password, too?

If so, you may be able to use [GNU screen](https://formulae.brew.sh/formula/screen) to log in to the instance:
```console
# replace ${INSTANCE} with your instance name
$ multipass start ${INSTANCE}
# in another terminal
$ sudo screen /var/root/Library/Application\ Support/multipassd/vault/instances/${INSTANCE}/pty
```

Pressing Enter should give you a login prompt.

**Comment by eliot-akira** [comment]
Thanks for the suggestion - unfortunately, I hadn't setup password yet for the new user. Although, the user should have SSH access (as the only user who can). I'm not able to `multipass start` on the instance, since it fails with socket disconnected.

I did find inside `/var/root/Library/Application\ Support/multipassd/vault/instances/${INSTANCE}` the .img file that (I'm guessing) I'd need to mount with `qemu-nbd`. I'll keep looking to see how to achieve it on macOS.

**Comment by eliot-akira** [comment]
OK, I did manage to start a qemu-nbd process by running:

```sh
sudo qemu-nbd --format=qcow2 --fork --snapshot /var/root/Library/Application\ Support/multipassd/vault/instances/{$INSTANCE}/ubuntu-18.04-server-cloudimg-amd64.img
```

Looks like it runs at port 10809 by default.

Now I apparently need an NBD client to create a device like `dev/nbd0` and mount it.

---

In the [qemu-nbd docs](https://git.qemu.org/?p=qemu.git;a=blob;f=docs/tools/qemu-nbd.rst;h=667861cb22e970d87b4a551818da6c291896abb4;hb=master) I see:

```
Bind a /dev/nbdX block device to a QEMU server (on Linux).
```

..and in options:

```
-c, --connect=DEV   Connect *filename* to NBD device *DEV* (Linux only)
```

Seems like I'll need to find a different way to mount the device.

---

Aah, according to an in-depth (albeit a bit old) [documentation](https://qemu.weilnetz.de/doc/qemu-doc.html#disk_005fimages_005fnbd), I found that I can expose NBD over a unix socket.

```sh
sudo qemu-nbd --socket=/tmp/nbdsocket0 --format=qcow2 --fork --snapshot /var/root/Library/Application\ Support/multipassd/vault/instances/{$INSTANCE}/ubuntu-18.04-server-cloudimg-amd64.img
```

(I'm not sure about running with `sudo` but looks like I need it.)

Then, a new command to connect to the unix socket.

```sh
sudo qemu-system-x86_64 -hdb nbd+unix://?socket=/tmp/nbdsocket0
```

Ooh, it opened a window, trying to boot. It failed at the end, but I think I need to pass it more parameters.

**Comment by eliot-akira** [comment]
I tried running the image directly with qemu-system-x86_64, rather than go through NBD (which seems like it won't work on macOS).

```sh
sudo qemu-system-x86_64 -m 2048 -drive file={IMAGE_FILE}
```

It got further along than before, but ended with:

```
qcow2: Marking image as corrupt: Preventing invalid allocation of refcount block at offset 0; further corruption events will be suppresse
```

Ah, well, it was a good try and I learned a few things.

**Comment by eliot-akira** [comment]
Success!  Since the instance started, although I couldn't log in to the shell (due to my misconfiguration), the server I had installed on it was running again. From one of its site's web frontend, I was **able to recover the data** I had lost access to.

Interestingly, the QEMU processes are stopped but Multipass lists the instance as running. I wasn't able to `start` it - but now it's magically running - and I still can't `shell` into it or display `info`, they all end with "ssh failed to authenticate".

Well, I think this issue can be closed now. I'm relieved to have recovered the data, it was a couple days worth of work. Thank you for the suggestion to search for "mount a qcow2 image", that was the hint I needed.

I had an idea for a Multipass feature, to **mount an unstarted instance** so its files can be edited from the host. I found that `qemu-img` can copy the image, so I'll continue exploring how that's possible on macOS.

**Comment by Saviq** [comment]
Hey @eliot-akira, glad you got this working. As for your feature idea, the problem is that _mounting_ is wildly different between the different OSs we support, maintaining that would be difficult.

An alternative idea we had was to have a `multipass recover <instance>` or so that would launch a temporary instance with the _<instance>_'s drive hooked up. This way you could transfer/modify data of the broken instance and, in your case, start it again.

Thanks for the report!
