### ISSUE TITLE
Manual inspection and send of usage data

### ISSUE THREAD

**Issue by abitrolly** [canonical/multipass#1561]
I am trying to see what exactly `multipass` is sending. It doesn't allow me this.
```
Send usage data (yes/no/Later)? 
```

**What's your proposed solution?**
Let user send the stats manually, automatically and review what is being sent, as well as see the reports.

**Additional context**
https://data.syncthing.net/

**Comment by townsend2010** [comment]
Hi @abitrolly,

Currently, we are not sending much of anything.  That said, it's all in the code and in particular, here: https://github.com/canonical/multipass/blob/99276d6140b97ef6b3bbcda07f0fb444f20430da/src/metrics/metrics_provider.cpp#L188-L211

When we do add more, we will add an option to allow the user to inspect what will be sent before agreeing to send it.

I'm going to go ahead and close this, but if my answer is not satisfactory, please reopen for further discussion.  Thanks!

**Comment by abitrolly** [comment]
@townsend2010 just take a look at how Syncthing handles this when you're ready. The `multipass_id`, `tags`, `uuid` and `credentials` don't look like anonymous stats to me. If anonymous stats Syncthing style doesn't make any sense for your purposes, maybe the purposes need to be communicated more clear.

**Comment by townsend2010** [comment]
@abitrolly,

I'll expand a bit further what those values really contain.

- `multipass_id` is a randomly generated uuid made via https://doc.qt.io/qt-5/quuid.html#createUuid and then saved in a local file for subsequent sending of data.
- `tags` is a `QJsonObject` that *only* contains the aforementioned `multipass_id` key with the uuid value.
- `uuid` is just a repeat of `multipass_id`. This is just a requirement of what the server accepts.
- `credentials` is an empty string.

IMO, all of those are anonymous, but we'll give Syncthing a look when it comes time to actually collect any real data.
