### ISSUE TITLE
multipass disk full

### ISSUE THREAD

**Issue by gokhankocak** [canonical/multipass#1569]
Hello,
Where does multipass store its data on Mac OS?
My disk is full and I want to move multipass data to another drive.
Thanks.

**Comment by Saviq** [comment]
Hi @gokhankocak, unfortunately there's currently no easy way to move the data away.

It's stored in `/var/root/Library/Application Support/multipassd`, you would have to symlink / use bindfs to have it stored in another location.

**Comment by Saviq** [comment]
Duplicate of #566
