### ISSUE TITLE
Mount completion finishes on non-empty folders

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#157]
```
$ multipass mount /<Tab><Tab>
/bin    /dev    /home   /lib32  /lxd    /mnt    /proc   /run    /snap   /sys    /usr
/boot   /etc    /lib    /lib64  /media  /opt    /root   /sbin   /srv    /tmp    /var
$ multipass mount /hom<Tab>
$ multipass mount /home <Tab>
```
In the last step, note there's a space after `/home`, meaning the completion for the source path finished.

I wonder, do we really need the bash completion script to be a script? Couldn't the `multipass` command return valid options and pass it up to bash via a wrapper? It feels like encoding all this logic inside a bash script is bound to result in such issues, getting out of sync etc.

**Comment by townsend2010** [comment]
I'm not familiar on how to accomplish bash completion via other methods besides bash completion scripts.  Do you have any examples of how this would be accomplished by the method you propose?

I think we just need to take better care of the bash completion script when we add and/or change functionality.

**Comment by Saviq** [comment]
Well, I just mean the "bash completion script" could just do `multipass complete $CURRENT_CMDLINE` or some such, and read an array of possible completions from it.

Ideally those would come from the command definitions themselves and such, it's utopic I know, but not impossible ;)

**Comment by townsend2010** [comment]
Ah, ok, I thought you had seen some ways of doing this:)

Maybe something to consider way in the future when we are running low on things to work on;)
