### ISSUE TITLE
Windows Powershell ABNT2 keyboard

### ISSUE THREAD

**Issue by levmatta** [canonical/multipass#1573]
**Describe the bug**
ABNT2 keyboard does not work correctly, changing the keyboard in Ubuntu does not solve the problem. Powershell accepts characters correctly.

**To Reproduce**
How, and what happened?
1. `multipass shell ...`
2. type "ç" does not input anything (sometimes it insert spaces, or breaks the line)
3.  sudo dpkg-reconfigure keyboard-configuration      (and configure correctly)
4. STILL does not work

**Expected behavior**
What did you expect to happen?
"ç" and accented characters should work like "á"

**Additional info**
 - OS: Windows 10 
- multipass  1.2.1+win
- `multipass info --all`
PS C:\WINDOWS\system32> multipass info --all
Name:           crack-flatfish
State:          Running
IPv4:           172.17.35.168
Release:        Ubuntu 18.04.4 LTS
Image hash:     298fa2e49d00 (Ubuntu 18.04 LTS)
Load:           0.08 0.02 0.01
Disk usage:     1.1G out of 4.7G
Memory usage:   517.7M out of 927.3M

**Comment by ricab** [comment]
Hi @levmatta , sorry that you are experiencing that. Could you please tell us what you get from the following in powershell?

- `chcp`
- `[console]::InputEncoding`
- `[console]::OutputEncoding`
- `$OutputEncoding`

Do you experience the same issue in `cmd.exe`?

**Comment by levmatta** [comment]
Hello, and thank you (being a dev and a user I know that it is probably my fault).
And yes: same issue in CMD.EXE

Output:
```powershell
PS C:\WINDOWS\system32> chcp
Active code page: 850
PS C:\WINDOWS\system32> [console]::InputEncoding


IsSingleByte      : True
BodyName          : ibm850
EncodingName      : Western European (DOS)
HeaderName        : ibm850
WebName           : ibm850
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 850



PS C:\WINDOWS\system32> [console]::OutputEncoding


IsSingleByte      : True
BodyName          : ibm850
EncodingName      : Western European (DOS)
HeaderName        : ibm850
WebName           : ibm850
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 850



PS C:\WINDOWS\system32> $OutputEncoding


IsSingleByte      : True
BodyName          : us-ascii
EncodingName      : US-ASCII
HeaderName        : us-ascii
WebName           : us-ascii
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 20127



PS C:\WINDOWS\system32>
```

**Comment by ricab** [comment]
Thanks @levmatta. No, it's not your fault at all. We have a release coming soon which fixes this :smiley: stay tuned!

I am closing now, but please reopen if by any chance you get the same with the next release.
