### ISSUE TITLE
launch failed: failed to download from 'https://cloud-images.ubuntu.com/releases/server/releases/bionic/release-20200519.1/ubuntu-18.04-server-cloudimg-amd64.img': Network timeout

### ISSUE THREAD

**Issue by nengbowan** [canonical/multipass#1577]
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. multipass launch ubuntu
1.

**Expected behavior**
What did you expect to happen?
start normal

**Logs**
[2020-06-06T19:35:19.431] [warning] [VMImageHost] Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/minimal/releases/xenial/release/ubuntu-16.04-minimal-cloudimg-amd64-disk1.img': Host cloud-images.ubuntu.com not found

**Additional info**
 - OS: macos  10.13.6 (17G66)
multipass  1.2.1+mac
multipassd 1.2.1+mac

**Additional context**
if  i can download img from internet use other way , copy that  img to this place . 
that program should recognize it and load it . the same as offline .

**Comment by Saviq** [comment]
Hi @nengbowan, can you actually download that image? Are you using a proxy or a VPN?

Something must be preventing Multipass from downloading that file.

**Comment by nengbowan** [comment]
ssr that I use before , but I have stopped it now , and restart for many times , but it still not work

**Comment by nengbowan** [comment]
that host can ping , but slowly 

PING cloud-images.ubuntu.com (91.189.88.89): 56 data bytes
64 bytes from 91.189.88.89: icmp_seq=0 ttl=51 time=312.120 ms
64 bytes from 91.189.88.89: icmp_seq=1 ttl=51 time=313.405 ms
Request timeout for icmp_seq 2
64 bytes from 91.189.88.89: icmp_seq=3 ttl=51 time=286.951 ms
64 bytes from 91.189.88.89: icmp_seq=4 ttl=51 time=309.938 ms
64 bytes from 91.189.88.89: icmp_seq=5 ttl=51 time=315.247 ms
64 bytes from 91.189.88.89: icmp_seq=6 ttl=51 time=312.191 ms

**Comment by Saviq** [comment]
Can you download the file with `wget` or Safari?

**Comment by nengbowan** [comment]
I can  , what I should do next .

**Comment by Saviq** [comment]
It looks like your connection to cloud-images… is too slow and unstable I'm afraid. Right now my only recommendation is to try later, sorry.

**Comment by nengbowan** [comment]
ok

**Comment by nengbowan** [comment]
what should i do , next

**Comment by Saviq** [comment]
Hi @nengbowan did you manage to get past this issue in the end?

**Comment by nengbowan** [comment]
no , still not work

**Comment by nengbowan** [comment]
I will try another os like windows , try it again , thanks

**Comment by Amyt-tech** [comment]
I faced the same problem. After downloading the image with wget used the following command
multipass launch file:///home/my_username/ubuntu-16.04-server-cloudimg-amd64-disk1.img
Where the image file "ubuntu-16.04-server-cloudimg-amd64-disk1.img" was stored at /home/my_username directory. That worked.

**Comment by Rav317** [comment]
I too the error while performing the following command:
multipass launch --name ubuntu-vm

It reached around 40% and then showed the following error:
launch failed: failed to download from 'https://cloud-images.ubuntu.com/releases/server/releases/focal/release-20200804/ubuntu-20.04-server-cloudimg-amd64.img': Network timeout

System description:
Ubuntu-20.04 LTS
multipass  1.4.0
multipassd 1.4.0

**Comment by Saviq** [comment]
@Rav317 see above, on Linux, you can download the image with `wget` and then use `multipass launch file:///…`.

**Comment by vignesh-codes** [comment]
Im not sure why this did not work the first time when I tried. 
I then connected to a different wifi network and tried, it worked fine. There is another option to manually download the image and set the path in the cmd line. You could try that too.

**Comment by Soot3** [comment]
Are you manually downloading and launching on windows? got this on my system "launch failed: http and file based images are not supported". and it's apparently a standard issue. https://github.com/canonical/multipass/issues/1029

**Comment by cyal1** [comment]
> 您好@nengbowan，您可以实际下载该图像吗？您正在使用代理还是VPN？
> 
> 必须采取某种措施阻止Multipass下载该文件。

I also encountered this problem

**Comment by ruolan267** [comment]
Experience the same issue.

launch failed: failed to download from 'https://cloud-images.ubuntu.com/releases/server/releases/focal/release-20210429/ubuntu-20.04-server-cloudimg-amd64.img': Network timeout

**Comment by ruolan267** [comment]
I download the img through the browser and run the multipass launch file:////Users/username/Downloads/ubuntu-20.04-server-cloudimg-amd64.img and got the launch failed: http and file based images are not supported error.

**Comment by townsend2010** [comment]
Hi @ruolan267,

The `Network timeout` means that the `multipassd` downloader did not receive a reply from the server in 10 seconds.  It's not clear if you were able to download any of the image before the timeout occurred.  Did you see any progress like `Retrieving image: 1%`?  Are you on a slow connection?

Also, have you possibly switched networks since `multipassd` started?  You may want to try to restart multipass if you have.  I'm not sure what your host OS in order to give you the command on how to do that.

**Comment by ruolan267** [comment]
Hi @townsend2010 Thank you for your reply. Yeah, it turns out it's the network that causes this issue. I switch my networks and it works now. As to the second question. My host OS is macOS. It's the same issue mentioned in [#1029](https://github.com/canonical/multipass/issues/1029) and it seems that it has not been fixed yet.
