### ISSUE TITLE
Unable to start vm

### ISSUE THREAD

**Issue by supermario9590** [canonical/multipass#1578]
I am trying to build a snap using multipass but I keep getting an error

1. I ran `snapcraft`
2. It said that it was retrieving the image
3. After it did that it gave an error saying `qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /build/qemu-Ytr1xz/qemu-2.11+dfsg/target/i386/kvm.c:1906: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.`

It should have started the vm and built the snap.

This is the latest log
`Jun 06 13:36:14 anish-snap-machine systemd[1]: Started Service for snap application multipass.multipassd.
Jun 06 13:36:15 anish-snap-machine multipassd[6129]: Unable to determine subnet for the mpqemubr0 subnet
Jun 06 13:36:15 anish-snap-machine multipassd[6129]: Using AppArmor support
Jun 06 13:36:15 anish-snap-machine multipassd[6289]: Applying AppArmor policy: multipass.dnsmasq
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: started, version 2.79 cachesize 150
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-det>
Jun 06 13:36:15 anish-snap-machine dnsmasq-dhcp[6291]: DHCP, IP range 10.204.57.2 -- 10.204.57.254, lease time infinite
Jun 06 13:36:15 anish-snap-machine dnsmasq-dhcp[6291]: DHCP, sockets bound exclusively to interface mpqemubr0
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: using local addresses only for domain multipass
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: reading /etc/resolv.conf
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: using local addresses only for domain multipass
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: using nameserver 127.0.0.53#53
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: read /etc/hosts - 7 addresses
Jun 06 13:36:15 anish-snap-machine dnsmasq[6291]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
Jun 06 13:36:15 anish-snap-machine multipassd[6129]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
Jun 06 13:36:15 anish-snap-machine multipassd[6129]: QIODevice::write (QFile, "/var/snap/multipass/common/cache/multipassd/vault/multipassd-image-records.json"): >
Jun 06 13:36:15 anish-snap-machine multipassd[6129]: Starting Multipass 1.2.0
Jun 06 13:36:15 anish-snap-machine multipassd[6129]: Daemon arguments: /snap/multipass/2114/bin/multipassd --verbosity debug --logger platform
Jun 06 13:37:07 anish-snap-machine multipassd[6468]: Applying AppArmor policy: multipass.qemu-img
Jun 06 13:37:08 anish-snap-machine multipassd[6477]: Applying AppArmor policy: multipass.qemu-img
Jun 06 13:37:08 anish-snap-machine multipassd[6483]: Applying AppArmor policy: multipass.qemu-img
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: process working dir '/snap/multipass/2114/qemu'
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: process program 'qemu-system-x86_64'
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/d>
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Jun 06 13:37:09 anish-snap-machine multipassd[6542]: Applying AppArmor policy: multipass.snapcraft-my-snap-name.qemu-system-x86_64
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: process started
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 11, "major": 2}, "package": "(Debian 1:2.11+dfsg-1ubu>
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
                                                     qemu-system-x86_64: /build/qemu-Ytr1xz/qemu-2.11+dfsg/target/i386/kvm.c:1906: kvm_put_msrs: Assertion `ret ==>
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: 
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: process error occurred Crashed program: qemu-system-x86_64; error: Process crashed
Jun 06 13:37:09 anish-snap-machine multipassd[6129]: error: program: qemu-system-x86_64; error: Process crashed
Jun 06 13:37:11 anish-snap-machine multipassd[6129]: instance "snapcraft-my-snap-name" does not need stopping`

**Additional info**
 - OS: Ubuntu 20.04 LTS
- Multipass version: `multipass  1.2.0`
- Multipassd version: `multipassd 1.2.0`
- `multipass info --all`: Name:           snapcraft-my-snap-name
State:          Stopped
IPv4:           --
Release:        --
Image hash:     9e1601b0eb0a (Ubuntu Snapcraft builder for Core 18)
Load:           --
Disk usage:     --
Memory usage:   --

**Comment by Saviq** [comment]
Hi @supermario9590 are you running under VMWare by any chance? I believe we've seen this error when CPU counters were not virtualized.

**Comment by supermario9590** [comment]
Yes I am.

**Comment by supermario9590** [comment]
Thanks! It worked!

**Comment by sam-sre** [comment]
Hi @supermario9590 
What did you do to solve this?
I had the same issue and am running Multipass on a VMWare workstation as well..
