### ISSUE TITLE
How to forward xgui from a multipass container

### ISSUE THREAD

**Issue by nipunpruthi** [canonical/multipass#1591]
https://askubuntu.com/questions/1246368/how-to-forward-xgui-from-a-multipass-container

I frequently install(build) buggy software(source code). So, I frequently runs into problem. And every once-in-a-while, I broke my OS stack and need to reinstall it(ubuntu 18.04).

I recently installed Multipass by canonical. Now, I can install(experiment) new source code with less fear as it is kind of docker but provide better hardware support. In-short, it works like charm. But, still, only application that doesn't requires GUI could be run on a Multipass container. I searched how to forward GUI (they call it "X forward") from a Multipass container to my system. I found some incomplete and inconsistent tutorials. Could someone please mentions the steps for "X forward" from a Multipass container to my system. Thanks in Advance

**Comment by ricab** [comment]
Hi @nipunpruthi, X forwarding isn't supported by multipass itself, but you should still be able to achieve it. Did you see these instructions by @luis4a0?

https://discourse.ubuntu.com/t/graphical-desktop-in-multipass/16229
https://discourse.ubuntu.com/t/stand-alone-windows-in-multipass/16340
