### ISSUE TITLE
launch failed: http and file based images are not supported outside of Linux

### ISSUE THREAD

**Issue by MilanMasek** [canonical/multipass#1593]
**Describe the bug**
This is regarding feature of launching images as described at https://multipass.run/docs/launch-command.

At Windows hosts, 'url' or 'file' argument of 'multipass launch' command fails reporting that "http and file based images are not supported".

Similarly, as commented at https://discourse.ubuntu.com/t/new-way-to-launch-images-other-than-cloud-images-from-simplestreams/6282/2 , such issue exists on MacOS as well.

**To Reproduce**
How, and what happened?
1. 
```
PS C:\> multipass.exe launch --name vm1-ubuntu18 "file://C:\ubuntu-core-18-amd64.img.xz"
launch failed: http and file based images are not supported

PS C:\> multipass.exe launch --name vm1-ubuntu18 "http://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-amd64.img.xz"
launch failed: http and file based images are not supported
```

**Expected behavior**
Working feature of launching images other than cloud images from SimpleStreams.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
```
PS C:\> multipass.exe launch --name vm1-ubuntu18 "file://C:\ubuntu-core-18-amd64.img.xz" -vvvv
[2020-06-16T13:59:52.378] [debug] [ubuntu2004] Got VMState: poweroff

[2020-06-16T13:59:52.429] [debug] [primary] Got VMState: poweroff

launch failed: http and file based images are not supported
```

**Additional info**
 - OS: Microsoft Windows 10 Enterprise, OS Version: 10.0.18362 N/A Build 18362
- `multipass version`: multipass  1.3.0+win, multipassd 1.3.0+win

**Additional context**
N/A

**Comment by jingj5** [comment]
I have the same problem.

**Comment by mikegrima** [comment]
Have any reasons been provided for why macOS and Windows don't support this feature? At the very least the docs should reflect this.

**Comment by OnnoH** [comment]
+1 on this bug/feature. Please add support for Mac OS as well.

**Comment by pcgeek86** [comment]
Hey @Saviq any news on this? I'd really like to be able to specify a local file or URI to pull an image from.

**Comment by dimasanwaraziz** [comment]
`multipass launch --name ubuntu-lts file://ubuntu-18.04.4-desktop-amd64.iso`
`launch failed: http and file based images are not supported`

Windows 10 still

**Comment by mfernandes61** [comment]
+1 on this. Would be really useful to create training instances from a base plus tools & data for bioinformatics training for Mac & windows learners

**Comment by MilanMasek** [comment]
Just wondering if this will get ever higher priority, if it is complicated to resolve, or if there is some kind of political reasoning behind.
Re-trying time to time. Persists with 1.6.0rc
`PS C:\Users\masmil> date; multipass.exe version; multipass.exe -vvv launch --name ubuntu1910 file://.\software\ubuntu-core-18-amd64.img.xz

Sunday, January 17, 2021 4:07:14 PM
multipass  1.6.0-rc.478+g3114b643.win
multipassd 1.6.0-rc.478+g3114b643.win
launch failed: http and file based images are not supported`

**Comment by bxtx999** [comment]
+1 for this feature

**Comment by waketzheng** [comment]
> I agree with some of the comments here.
> 
> The documentation mentions nowhere that http and file based images are not supported on certain platforms. This needs to be updated in the documentation.

**Comment by waketzheng** [comment]
polarapfel commented on Mar 6, 2020
I agree with some of the comments here.

The documentation mentions nowhere that http and file based images are not supported on certain platforms. This needs to be updated in the documentation.

https://github.com/canonical/multipass/issues/1029#issuecomment-595675099
