### ISSUE TITLE
When Ubuntu terminal open in cmd it doesn't take any Input

### ISSUE THREAD

**Issue by Abhishekumar-me** [canonical/multipass#1595]
when shell starts I counld not type anything there.
```
C:\Windows\system32>multipass sh
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 System information disabled due to load higher than 1.0

 * MicroK8s gets a native Windows installer and command-line integration.

     https://ubuntu.com/blog/microk8s-installers-windows-and-macos

0 packages can be updated.
0 updates are security updates.


Last login: Sat Jun 13 19:53:44 2020 from 10.0.2.2
 ]0;ubuntu@primary: `~ubuntu@primary:~$
```
please help me!!

**Comment by Saviq** [comment]
Hi @Abhishekumar-me, this sounds like something went wrong with the console and/or encoding.

What's your codepage?
```cmd
chcp
```

Does this same happen in PowerShell?

**Comment by Abhishekumar-me** [comment]
Yes it happens in powershell also.

**Comment by ricab** [comment]
Hi @Abhishekumar-me , thanks for reporting. Could you please fill in the bits below, so we can try to reproduce/understand the issue?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`

**Comment by ricab** [comment]
Also, did you install multipass directly from the package in https://multipass.run/ or some other way? Did you bring instances from a previous version? What does `multipass get local.driver` say?

**Comment by Abhishekumar-me** [comment]
Hi @ricab 
Here what you ask..
```
C:\Windows\system32>multipass version
multipass  1.3.0+win
multipassd 1.3.0+win

C:\Windows\system32>multipass info --all
Name:           primary
State:          Running
IPv4:           N/A
Release:        Ubuntu 18.04.4 LTS
Image hash:     55646c02a8bc (Ubuntu 18.04 LTS)
Load:           0.66 0.33 0.13
Disk usage:     1007.5M out of 4.7G
Memory usage:   72.1M out of 985.1M
```
OS : Microsoft Windows 7 Ultimate 
```
C:\Windows\System32>multipass get local.driver
virtualbox
```
I got multipass from there official website  https://multipass.run/ and  I haven't bring instances from a previous version.

Sorry I cloudn't find the log file.
I don't know the log location.

**Comment by ricab** [comment]
I am afraid Windows 7 is not supported. I suspect it does not provide the same console interaction methods. 

However, if you find everything else works well enough for you, you can try to workaround this issue by accessing the instance through VirtualBox directly. Here are [some instructions](https://multipass.run/docs/using-virtualbox-in-multipass-windows) you may find helpful.

**Comment by Abhishekumar-me** [comment]
Thanks for your help...
