### ISSUE TITLE
'multipass exec' hangs in some cases (race condition?)

### ISSUE THREAD

**Issue by simos** [canonical/multipass#16]
If you try

`multipass exec myVM -- uname -a`

several times, it hangs (around one out of three times).
You would need to stop, then restart the virtual machine in order to continue.

I managed to get

`multipass exec myVM pwd`

to hang by trying it about 15 times. Therefore, it does not matter which command it is. But some commands are too prone to hang than others.

**Comment by Saviq** [comment]
Confirmed:
```
⟫ while ./build/bin/multipass exec premium-jaguar -- uname -a; do true; done                                                                                 
Linux premium-jaguar 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux premium-jaguar 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux premium-jaguar 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# hang
```
When this happens, the `multipassd` client has this in gdb: [gdb.txt](https://github.com/CanonicalLtd/multipass/files/1560747/gdb.txt)
