### ISSUE TITLE
Users defined in cloud-init can break multipass

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#160]
Latest edge
installed:              2017.2.3-96-g6cecd17 (165) 66MB classic

just vanilla launch works ok
multipass launch 17.10
Launched: intrepid-eft                                                          

yaml with ssh key 
multipass launch 17.10 --cloud-init cinit_key.yaml                
failed to launch: ssh: Access denied. Authentication that can continue: publickey

multipass list                                                    
Name                    State       IPv4             Release
intrepid-eft            RUNNING     10.122.122.77    Ubuntu 17.10
punctual-firefly        RUNNING     10.122.122.145   Ubuntu 17.10

VM was created and started, just incorrect error message

**Comment by Saviq** [comment]
Actually it's not just an incorrect error message, as `multipass shell intrepid-eft` won't work then - we're setting up our own key with the default user that you overrode.

We need to come up with a plan of dealing with that - maybe a dedicated `multipass` user added would be best, avoiding any clashes and letting you configure the remaining users as you please.

That said, with `multipass shell` we need to know what user to open the shell for - maybe we interpret the user data passed in and use the first user... Or maybe we connect as `multipass` by default but add support for `user@`?

We long discussed creating a user matching your username on the host inside the instance, which would make the inside of the instance more "familiar" in a way.

**Comment by albaguirre** [comment]
@marosg42 What are the contents of the yaml? (redacted of course :) )

Multiple keys are supposed to work but we could have broken that.
