### ISSUE TITLE
Can't launch after update

### ISSUE THREAD

**Issue by devcircus** [canonical/multipass#1606]
**Describe the bug**
Launching instance no longer works after updating to latest version - 1.3.0

**To Reproduce**
multipass launch --cpus 2 --disk 50G --mem 12G --name UbuntuFF 20.04

```bash
launch failed: The following errors occurred:
UbuntuFF: timed out waiting for response
```

**Expected behavior**
Instance launches normally as it did before upgrade.

**Logs**
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Multipass" /> 
  <EventID Qualifiers="0">1</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-06-17T21:15:02.8122244Z" /> 
  <EventRecordID>1194</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>HOMEOFFICE-9ZT</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>[UbuntuFF] Trying SSH on UbuntuFF.mshome.net:22</Data> 
  </EventData>
  </Event>
```

**Additional info**
 - OS: Windows 10 Build 20150.rs_prerelease.200612-1734
- multipass version: 1.3.0
- multipass info --all
```bash
Name:           UbuntuFF
State:          Stopped
IPv4:           --
Release:        --
Image hash:     fa1a86cdcf79 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
```

I've used multipass simultaneously with WSL2 for several weeks now. The only other change in my system before upgrading to 1.3.0 was installing the latest Windows insider release.

**Comment by devcircus** [comment]
Downgraded to 1.2.1 and everything works as expected again.
I tried installing 1.3.0 again and noticed it fails when trying to enable hyper-v. In 1.2.1, there's no problems.

**Comment by Saviq** [comment]
Hi @devcircus, sorry this seems to have slipped through our inboxes.

Are you still having this issue?

**Comment by devcircus** [comment]
I'm still unable to use 1.3. 1.2 throws an error during installation that hyper-v can't be started. Switching to virtualbox, the install completes and upon "launch", the machine is built, but fails to start (timed out waiting for response). 

Going back to 1.2, everything works as expected on hyper-v.

**Comment by devcircus** [comment]
I have multipass set up and running on my linux box, so if you don't feel like it is a bug, feel free to close. I just can't figure what changed that causes the issue with 1.3 on windows.

**Comment by Saviq** [comment]
@devcircus we'd love to know, too. Could you please have a look at [the logs](https://multipass.run/docs/accessing-logs) when it does fail, to see if there's any errors? You could also, in Services, stop the service and start with `--verbosity trace` to get a bit more logging and ship a whole session to us.

**Comment by devcircus** [comment]
So I sat down today to gather logs and paste them here and everything worked perfectly as if I'd dreamed it all up. Again, I have no idea what changed between now and 4 days ago, but it is now working on Hyper-V using version 1.3. 

Thanks for your time.

**Comment by devcircus** [comment]
Maybe it was something as simple as a reboot between installing multipass and using multipass. ¯\_(ツ)_/¯
