### ISSUE TITLE
Mounted shared files are accessible but not visible or executable

### ISSUE THREAD

**Issue by CptAsgard** [canonical/multipass#1607]
**Description**
I've mounted a shared folder which seems accessible to a certain extent. I can not execute files in it but I can read them. I can't see them in _ls_ however even with _--all_ or _-d_ flags.

**To Reproduce**
```
ubuntu@sanctified-pintail:~$ ls
snap
ubuntu@sanctified-pintail:~$ cd /home/asgard
ubuntu@sanctified-pintail:/home/asgard$ ls
shared
ubuntu@sanctified-pintail:/home/asgard$ cd shared
ubuntu@sanctified-pintail:/home/asgard/shared$ ls
ubuntu@sanctified-pintail:/home/asgard/shared$ cd lab1
ubuntu@sanctified-pintail:/home/asgard/shared/lab1$ ls
ubuntu@sanctified-pintail:/home/asgard/shared/lab1$ file lab1
lab1: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=43af309d3735b17cef57f70cb997eebafd17ebf2, not stripped
ubuntu@sanctified-pintail:/home/asgard/shared/lab1$ ./lab1
-bash: ./lab1: No such file or directory
```

**Expected Behaviour**
I expect `ls` to list the folder _lab1_ and the files that are in that folder; _lab1, lab2, lab3_.

**Additional Information**
- OS: Ubuntu 20.04 Focal Fossa
- Multipass: 1.3.0
- multipass info --all
```
Name:           sanctified-pintail
State:          Running
IPv4:           10.142.78.36
Release:        Ubuntu 18.04.4 LTS
Image hash:     55646c02a8bc (Ubuntu 18.04 LTS)
Load:           0.08 0.02 0.01
Disk usage:     1.2G out of 4.7G
Memory usage:   95.4M out of 985.1M
Mounts:         /home/asgard/shared => /home/asgard/shared
                    UID map: 1000:default
                    GID map: 1000:default
```

**Comment by Saviq** [comment]
Hi @CptAsgard, can you see any AppArmor denials in `dmesg`? Any [logs](https://multipass.run/docs/accessing-logs) that may suggest what the issue is?

Did this start with the 1.3.0 release? We moved to a strict snap, so that could cause some of this.

**Comment by CptAsgard** [comment]
I haven't used multipass before 1.3 so I'm not sure about that. I do see AppArmor = DENIED messages in dmesg. I have copied my [logs here](https://gist.github.com/CptAsgard/2473c877e3b529667950ef4010167903). I can see in the logs as well that AppArmor is throwing up issues but I'm not sure what to do.

**Comment by Saviq** [comment]
@CptAsgard could you please paste the DENIED lines that mention Multipass?

**Comment by CptAsgard** [comment]
Ah of course. [Here it is](https://gist.github.com/CptAsgard/c2370ec92cc493a5e27e165a44e2866b).

**Comment by CptAsgard** [comment]
Ah of course. [Here it is](https://gist.github.com/CptAsgard/e5d6532224ebe5d9fde906bcc1bc4b50).

**Comment by Saviq** [comment]
No, none of those explain your troubles… Could you please `stat` the folder that is being mounted, the subfolder, and the files - both from outside and inside the instance?

**Comment by CptAsgard** [comment]
No problem. [Paste](https://gist.github.com/CptAsgard/0a85c3374e00ba06a56c76b552b41f16).

**Comment by Saviq** [comment]
Hmm @CptAsgard the only thing that stands out is the "133" group ownership… but I've been unable to reproduce even with a similar directory structure… Is this issue persistent across instance restarts? Re-mounting? Other folders?

Pretty stumped here :)

**Comment by CptAsgard** [comment]
I was playing around with those permissions to see if it had any effect. Thanks for the assistance, I'll assume that it's a local issue then. I will try to re-install and some other things I haven't tried yet, as I've tried to restart, remount, and tried other folders already too.

**Comment by CptAsgard** [comment]
I have done a completely fresh install of my OS and the issue has disappeared. I'm going to assume it was some strange local behaviour and not a bug. Thanks for the assistance.

**Comment by CptAsgard** [comment]
Actually @Saviq could you try executing lab1 from the following files on an instance and see if they work for you?

http://security.cs.rpi.edu/courses/binexp-spring2015/lectures/4/lab1.zip

**Comment by CptAsgard** [comment]
Confirmed. If you run into an issue with bash not seeing your files but you are certain they're there, try following these steps: https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit

It fixed this issue for me and it can be considered close, and not an issue with multipass regardless.
