### ISSUE TITLE
build 20150.rs_prerelease.200612-1734 windows 10 insider preview, creative cloud problem

### ISSUE THREAD

**Issue by xhoele** [canonical/multipass#1608]
adobepcbroker.exe - bad image error, error status 0xc000012f,
adobe creative cloud and related programs stopped working after this update
![Screenshot (28)](https://user-images.githubusercontent.com/66778106/85038989-89462b80-b187-11ea-8536-8ddf7400ef09.png)

**Comment by townsend2010** [comment]
Hi @xhoele,

Sorry, I'm not sure I understand what the problem is.  Are you saying that `adobepcbroker.exe` broke after updating to Multipass version 1.3?

**Comment by Saviq** [comment]
Not a Multipass issue.
