### ISSUE TITLE
Shorter alias 

### ISSUE THREAD

**Issue by ghost** [canonical/multipass#1620]
**What are you trying to do?**
Use a shorter alias instead of typing `multipass`

**What's your proposed solution?**
I want to have something like `mp` or `mlp`

**Comment by Saviq** [comment]
Hi @bahram-hodjaev you should be able to do this with your shell (or with `snap alias` if using snaps). We'd rather not risk potential conflicts with other commands.

I'll close this for now, please report back if you have arguments for including such an alias.

**Comment by bahram-hodjaev** [comment]
Hi,@Saviq. Yeah, I knew it. No problem. I just wanted to have a working alias from the box ;)
