### ISSUE TITLE
[hyper-v] No Internet access in instances

### ISSUE THREAD

**Issue by bibinphilip** [canonical/multipass#1633]
Hi,
After launching Ubuntu via multipass (latest version), when I connect this VM via Hyper-V (Windows 10 Pro), it's asking for credential. During the installation no such credentials were set. Kindly guide what to provide. PFA image for reference.
![Ubuntu Login](https://user-images.githubusercontent.com/35682900/86606105-33fe7c80-bfc5-11ea-94f2-ec2f5e3ffb7c.PNG)

**Comment by Saviq** [comment]
Hi @bibinphilip, you should use [`multipass shell …`](https://multipass.run/docs/shell-command) to access the instance, rather than going through Hyper-V.

**Comment by Saviq** [comment]
I'll close this for now, please report back if something else is broken for you.

**Comment by bibinphilip** [comment]
Hi Saviq,

Please find attached log. It seems ssh connection is failing. Please note, I the network adapter setting in Hyper-V is set to External switch having Wi-Fi adapter.

[multipass shell log.txt](https://github.com/canonical/multipass/files/4882504/multipass.shell.log.txt)

Please share your suggestions.

**Comment by Saviq** [comment]
> Please find attached log. It seems ssh connection is failing. Please note, I the network adapter setting in Hyper-V is set to External switch having Wi-Fi adapter.

That's your problem… We need the instances to be on the "Default Switch" so we can find and reach them.

> Please share your suggestions.

Rather than changing the first interface, add another connected the way you want. You'll have to [enable it through netplan](https://netplan.io/examples#connecting-multiple-interfaces-with-dhcp), too.

If you can wait, though, we're implementing support for that directly into Multipass now (#118).

**Comment by bibinphilip** [comment]
Thanks @Saviq , I reverted it to Default Switch and its working. But unfortunately, its not connecting to the internet via Wi-Fi. Digging further... Thanks for your guidance :)

**Comment by Saviq** [comment]
Hi @bibinphilip that suggests something is wrong with the Default Switch, have a look at [our network troubleshooting doc](https://multipass.run/docs/troubleshooting-networking-on-windows), hopefully removing the switch (and rebooting) will help.

There's also a chance something is blocking access, do you have a firewall set up or a VPN connection active?

**Comment by bibinphilip** [comment]
Thank you @Saviq , the link helped. I just now have to figure out how to have a static IP for this VM. 

Thank you for your help :)

**Comment by Saviq** [comment]
@bibinphilip you can use `<instance name>.mshome.net` to always get the current IP.

With the with we're doing for bridging, you'll be able to add any interface with a static IP, too.

Glad you got it going :)
