### ISSUE TITLE
[simplestreams] Fetching manifest data blocks daemon and can cause the client to appear slow

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1637]
Currently, there is a single shot `QTimer` that fires when an `ImageHost` is created on daemon start up.  With all non LXD backends, this is not a problem since the timer finally runs _after_ initialization is complete.  However, with LXD, when we do a `lxd_request` for querying information from LXD, Qt will decide the run the timer from the event queue when we have made a call into `NetworkAccessManager` which then delays initialization and blocks connections to the daemon with `EPERM` since the socket permissions are not yet set.

I have never really been satisfied with the `QTimer` approach here and would prefer to have a separate thread do manifest updates so as not to block the daemon during `update_manifest` operations.

**Comment by ricab** [comment]
This happens with qemu too. I see ~10s elapsing while contacting the remotes here, in:

```
$ multipass version
multipass  1.7.0-rc.899+g38dcd724
multipassd 1.7.0-rc.899+g38dcd724
```
