### ISSUE TITLE
How do I install the ubuntu 18.04 SERVER version

### ISSUE THREAD

**Issue by cpapir** [canonical/multipass#1643]
It appears that following your instructions I install the desktop version NOT the server version. How do I install the server version?

ALSO I will need to install the most current version of Mosquito MQTT server. Is there a way to do it all at onece?

**Comment by luis4a0** [comment]
Hi @cpapir,

You are on the safe side, Multipass always installs the server version. Ubuntu 18.04 Server can be launched with `multipass launch bionic`.

Note you can launch a VM containing the Mosquitto appliance by running `multipass launch appliance:mosquitto`, without the need of launching first a full Ubuntu VM. This should work in Multipass 1.3.0 (older versions did not have support for launching appliances).

I'm not sure this is what you need, but let us know if I didn't answer your questions.

**Comment by luis4a0** [comment]
Closing the issue, don't hesitate in contacting us again if you still need help.
