### ISSUE TITLE
qemu-system-x86_64 is hard coded in the error string and is confusing if using a different qemu executable

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1650]
the error message here trying this is now a little confusing, I can't tell if it's trying to use qemu-system-x86_64 or not ...

```
$ sudo multipass launch focal
launch failed: Internal error: qemu-system-x86_64 failed getting vmstate (Process returned exit code: 1) with output:
qemu-system-aarch64: -nographic: No machine specified, and there is no default
Use -machine help to list supported machines

```

_Originally posted by @anonymouse64 in https://github.com/canonical/multipass/issues/1376#issuecomment-660261746_

**Comment by will-rkr** [comment]
+1 on this one as I am eager to take advantage of A1 metal server on AWS. Tried to Google this a few times with no luck.

**Comment by townsend2010** [comment]
This should be fixed during the QEMU backend refactoring.
