### ISSUE TITLE
Lost multipass instances on macOS

### ISSUE THREAD

**Issue by luispimo** [canonical/multipass#1658]
After a multipass crash and system restart the instances have disappeared.

[multipassd-last2000lines.log](https://github.com/canonical/multipass/files/4970444/multipassd-last2000lines.log)

**Additional info**
- OS: macOS 10.15.5
- multipass  1.3.0+mac

**Comment by ricab** [comment]
Hi @luispimo, I'm sorry for your trouble. Could you please try `sudo VBoxManage list vms`?  Do you see the VMs if you `sudo VirtualBox`?

---

I spent a while wringing that log. Here are some conclusions for future reference:

- ... to 05:43:24 -> gui running and polling daemon for instance states, once per second
- 05:43:54 to 07:43:02 -> `VBoxManage` commands become unresponsive within the default 30s timeout of `QProcess::waitForFinished`; 
  * We throw, the `QProcess` object gets destroyed while it is still accounted as running
  * Qt logs a warning saying as much (via installed message handler).
- 07:42:28 -> daemon gets SIGTERMed
- 07:44:03 -> one of the running `VBoxManage` processes get forcefully terminated, and we throw
- 07:44:04 -> daemon restarts (this is where the issue happens)
  * qt logs more internal problems
  * when creating the VM objects, we try to get info from virtualbox again, now in a different place (VM c'tor); it times out
  * we now interpret the failure as a signal the VM needs to be created...  we ask virtualbox to create the VM
  * unfortunately that also times out, we throw, the corresponding QProcess gets destroyed, which kills the vm creation... (not sure what vbox sees at this point)
  * the daemon catches that, interprets it as a failure to create the VM and [removes it](https://github.com/canonical/multipass/blob/0d74fa3510e7f57c443cb9a4264fa4a7893b70aa/src/daemon/daemon.cpp#L727) from the vault
- later on, the daemon is restarted, but the instances are no longer there

So, the machine got into some bad state where daemon forks for vbox commands could not do their thing and Qt had internal troubles. But there is a good chance the VMs are still untouched as far as VirtualBox is concerned (those forks don't seem to have accomplished much anyway).

**Comment by luispimo** [comment]
Hi @ricab 
> Could you please try sudo VBoxManage list vms? Do you see the VMs if you sudo VirtualBox?

No 😞

> 07:42:28 -> daemon gets SIGTERMed
> 07:44:03 -> one of the running VBoxManage processes get forcefully terminated, and we throw

Multipass did not respond so I had to forcefully finish it.

In the future, it would be convenient to provide a simple way to backup and restore VM instances. 

Thanks

**Comment by ricab** [comment]
Right, the vault removal will delete the VM's image, so it doesn't matter whether VirtualBox will have lingering records. We'll have to think how to best handle such situations.

For backups, you could backup `/var/root/Library/Application\ Support/multipassd`, but the real issue is that VMs shouldn't be removed when the backend proves unusable.

**Comment by ricab** [comment]
I thought about this some more. Here's a tentative approach to deal with this (upon daemon startup):

- in the backends
  * distinguish absent vms (e.g. removed directly from backend) from other errors
  * report removed vms with a specific exception
- in the daemon
  * react by cleaning a vm from the vault only when that specific exception is caught
  * otherwise, abort daemon entirely, since:
    + our vault is now out-of-sync with our object tree
    + can't accomplish much  if we can't work with backends properly
    + best fail early

A lateral consideration is that the VBox backend still does not use the process-factory API, which would make the first step easier...

@townsend2010, @luis4a0, @Saviq , I'd like your feedback on this.

**Comment by luis4a0** [comment]
Hi @ricab , some thoughts on this.

- Raising an exception to report removed VM's seems to me good approach.
- I agree that it's better to fail early, but we won't avoid the user to run another VM which is not broken. Moreover, we should report to the user upon startup the VM's which were removed from the list (not only in the logs).
- It shouldn't be hard to make the VirtualBox backend to user the process factory stuff.

**Comment by ricab** [comment]
Thanks @luis4a0,

> I agree that it's better to fail early, but we won't avoid the user to run another VM which is not broken. 

Right, so I think we should try to distinguish errors that are likely to be specific to a VM from the rest, and then only abort on the latter. The system would restart the daemon a number of times. If that fixes the issue, great, if not, it would eventually become unavailable.

Another idea - which might or might not be made to intersect with the above - would be to move such VMs to the trash, instead of removing entirely.

> Moreover, we should report to the user upon startup the VM's which were removed from the list (not only in the logs).

That would be nice. It would require additional functionality, to cache issues and report to the CLI on the first occasion.

**Comment by townsend2010** [comment]
Another thing I can think of is to introduce a `BROKEN` state when something like this happens.  In this case, the user can try to start it again, use some other way to recover it, etc.  Also, if it's in this state, the user can delete/purge the instance and start over if they please.

**Comment by luis4a0** [comment]
+1 @ricab , @townsend2010 !

**Comment by paulhanatupstart** [comment]
I also lost instances on macOS.  This happens quite frequently.   Every time i do a reboot on my mac (Catalina), it seem to delete one or two vms out of 4.

**Comment by PdrNG** [comment]
yes, seems very much the same #1658 and #1832 
thanks for de-duplicate (i did not found this)

BUT !
seriosly !!!
more than 3 months with this issue ??
losing instances without posibility of recovery, dammm

**Comment by townsend2010** [comment]
@PdrNG,

Yes, we've kind of dropped the ball on this...we are a small team trying to implement new features and fix other bugs.  That said, this is really bad behavior, so I'm going to work on it, but it will take some careful thought to make sure we cover all cases and not regress other behaviors.

**Comment by PdrNG** [comment]
sure you are doing a great job, do not bad-understanding me, multipass is great, but this behavior is simple unacceptable. Neither I pretend to say you how to do your job, but a simple search for “delete file” and change it to “rename file” is a must that takes few minutes.

**Comment by vijesh12** [comment]
Faced simillar issue on macOS bigSur when I had to shutdown.. Lost VMs running. This is what I saw in the logs


`
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524`

Logs:

`[2021-04-17T08:41:12.040] [info] [consul-server0] /var/root/Library/Application Support/multipassd/vault/instances/consul-server0/cloud-init-config.iso: fcntl(F_PUNCHHOLE) Operation not permitted: block device will not support TRIM/DISCARD
[2021-04-17T08:41:12.043] [info] [consul-server0] virtio_net: Could not create vmnet interface, permission denied or no entitlement?

[2021-04-17T08:41:12.282] [info] [consul-server0] process state changed to NotRunning
[2021-04-17T08:41:12.282] [info] [consul-server0] process finished with exit code 1
[2021-04-20T17:13:05.035] [info] [daemon] Received signal 15 (Terminated: 15)
[2021-04-20T17:13:06.741] [info] [daemon] Goodbye!
[2021-04-20T17:32:34.417] [info] [update] Failed to fetch update info: failed to download from 'https://multipass.run/static/latest-release.json': Host multipass.run not found
[2021-04-20T17:32:34.687] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket, SSL:on
[2021-04-20T17:32:34.689] [info] [image vault] Source image 20.04 is expired. Removing it from the cache.
[2021-04-20T17:32:35.598] [info] [daemon] Starting Multipass 1.6.2+mac`

**Comment by mrtimp** [comment]
Can confirm that upgrading from 1.6.2 to 1.7.0 on macOS Big Sur fixes the issue where multipass VM's states are out of sync with VirtualBox. Thanks for sorting this out team its been causing me all sorts of pain over the past week :-)

**Comment by wingpang-gz** [comment]
I also lost vm instance on mac os . can u help me recover it . i lost some data. thx
