### ISSUE TITLE
multipass should include installation of tzdata in its user-data

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#1665]
**Describe the bug**

When launching a minimal Ubuntu image, cloud-init will report failure to set the given timezone (because tzdata is not installed).

**To Reproduce**
How, and what happened?
1. `multipass launch -n reproducer https://cloud-images.ubuntu.com/daily/server/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64.img`
1. `multipass exec reproducer -- cloud-init status --long`

This gives:

```
status: error
time: Tue, 28 Jul 2020 14:20:23 +0000
detail:
('timezone', OSError('Invalid timezone America/Toronto, no file found at /usr/share/zoneinfo/America/Toronto',))
```

**Expected behavior**

It should give:

```
status: done
...
```

**Additional context**

(This was discussed with @townsend2010 and @Saviq on IRC earlier today; not sure if there are logs anywhere.)

**Comment by OddBloke** [comment]
(If `tzdata` is already installed, cloud-init will handle that gracefully.)

**Comment by townsend2010** [comment]
We moved from the minimal images to buildd images which does include `tzdata`.  With that, I'm going to close this.
