### ISSUE TITLE
'multipass list' command showing incorrect IPv4 address

### ISSUE THREAD

**Issue by NelsonSharma** [canonical/multipass#1669]
**Describe the bug**
using version **1.3.0+win**
I created 4 VMs and started all of them. Using the 'multipass list' command is showing incorrect IPv4 addresses in its output. Please refer attached screenshot.

**To Reproduce**
How, and what happened?
Not Sure how to recreate. VMs specs are
Name	RAM	CPUs	os
ux01	300M	1	18.04
ux02	400M	2	20.04
ux03	300M	1	18.04
ux04	400M	2	20.04

**Expected behavior**
Show correct IPv4s

**Logs**
using multipass version **1.3.0+win** on Windows 10 64-bit
I am not sure if its a known issue. Please let me know if u need logs.
![err_multipass](https://user-images.githubusercontent.com/65968697/89227023-95346280-d5fa-11ea-868e-9af94e1c02bb.png)

**Comment by Saviq** [comment]
Hi @NelsonSharma, can you please check what do those names resolve to?

```powershell
PS> ping ux01.mshome.net
# etc…
```

It's probable that Windows's Internet Connection Sharing leases got confused, have a look at [our docs on the topic](https://multipass.run/docs/troubleshooting-networking-on-windows).

**Comment by NelsonSharma** [comment]
actually I was looking for static IPs for configuring hadoop nodes. But I understand now that it's not possible yet with multipass. hadoop always ssh using ip address instead of fqdn. this is such an annoyance. can u suggest something?

**Comment by Saviq** [comment]
Hey @NelsonSharma you could configure the network interfaces to have static secondary IPs, as long as they're all in the same subnet, it should work fine.

**Comment by NelsonSharma** [comment]
yes. thanks.
I have it figured out now.
