### ISSUE TITLE
Existing mounts lost on multipass upgrade

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#1674]
**Describe the bug**
Existing instance mounts were not restored when upgrading multipass from 1.3 to 1.4 (RC). The mounts were be listed as being up, but sshfs wasn't running inside the instances. I experienced this a couple of times. The issue seems to be that the daemon thinks "primary needs starting" at the wrong occasion (see logs).

**To Reproduce**
1. `multipass shell`
1. upgrade multipass
1. verify that `multipass info primary` lists the mount, but there is nothing in the folder.

**Expected behavior**
The mounts would be preserved/reinstated after the upgrade.

**Logs**
Attached.

**Additional info**
- OS: win 10 + virtualbox
- `multipass version`: 1.3 -> 1.4 RC

[multipass_mostly.zip](https://github.com/canonical/multipass/files/5042905/multipass_mostly.zip)

**Comment by townsend2010** [comment]
There has been a great deal of work around handling mounts better and this may have been fixed in all of that.  Going to close for now...

**Comment by ricab** [comment]
For the record, I just tried and I no longer see anything like this.
