### ISSUE TITLE
The connection to the VM is getting lost

### ISSUE THREAD

**Issue by bahram-hodjaev** [canonical/multipass#1675]
**Describe the bug**
After `sudo reboot` I can't reconnect to the primary.mshome.net

**To Reproduce**
How, and what happened?
1. `sudo reboot`
2. `ssh primary.mshome.net` or `multipass shell primary`

**Expected behavior**
Connect to the vm

**Additional info**
 - OS: Win 10 Pro 2004, 19041.388
- `multipass  1.3.0+win`

**Additional context**
I used cloud-init file to provision the box, maybe the problem is here

   #cloud-config
   package_update: true
   hostname: web01
   fqdn: web01.example.com

**Comment by Saviq** [comment]
> hostname: web01
> fqdn: web01.example.com

That exactly will be the problem. We're identifying the instance by hostname, and you've given it a `web01` hostname. You'll see that `ssh web01.mshome.net` should work.

If you want your instance to be called `web01`, just use `multipass launch --name web01`.

Let us know please if anything is unclear.

**Comment by bahram-hodjaev** [comment]
Hi, @Saviq, what service is used for name resolution here? Is it windows' or hyper-v's service?

**Comment by Saviq** [comment]
> Hi, @Saviq, what service is used for name resolution here? Is it windows' or hyper-v's service?

It's Internet Connection Sharing, set up by Windows on the Default Switch.
