### ISSUE TITLE
sshfs_server gets in tight loop if host mount directory is missing on instance start

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1677]
If a mount is defined and running and then the mounted host directory is removed, but the mount is still defined, subsequent starts of the instance will lead to `sshfs_server` taking 100% CPU time.

**Comment by jedahan** [comment]
Any way we can help debug or workaround this?

**Comment by jedahan** [comment]
I unmounted all directories with `multipass unmount`, then kill -9 sshfs_server and now it is happy

**Comment by alex-necula** [comment]
It happens to me too when using VS Code with Remote SSH to multipass
