### ISSUE TITLE
Use xterm-256color in `multipass shell` on Windows

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1687]
Any chance to solve this issue on Windows as well? Just tried it out on 1.4.0 and when I `multipass shell` on Windows, `TERM` is still set to `xterm` and not `xterm-256color`. If I `ssh` to that same multipass instance, `TERM` is set up correctly. But, I prefer using `multipass shell`...

_Originally posted by @uishon in https://github.com/canonical/multipass/issues/1004#issuecomment-673991509_

**Comment by Saviq** [comment]
We fixed this for Linux / macOS, but need to also make this happen for Windows.

**Comment by davidkrauser** [comment]
The current implementation _should_ set TERM in the Multipass session to whatever is set in the calling environment (maybe this isn't working in Windows? Probably worth an investigation). I don't have access to a Windows machine, but I'm curious to know what TERM is set to in the calling environment. I wonder if that value also depends on which terminal emulator is being used?

**Comment by davidkrauser** [comment]
Ignore my previous comment - the original fix only applies to the code that handles terminal connections on Unix systems.

**Comment by uishon** [comment]
Any chance you can give priority to this one? _(I was hoping it would get into 1.5...)_
It's really annoying so in case it's an easy fix - it'd be nice.
Thanks!

**Comment by Saviq** [comment]
Hi @uishon, this will be part of the next release (1.6.0).

**Comment by uishon** [comment]
Great. Thanks!
