### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by jslawler** [canonical/multipass#1691]
**Describe the bug**
Installer fails to install product.

**To Reproduce**
How, and what happened?
1. Double-click installer
2. Proceed through default installation instructions
3. Installer fails at install stage

**Expected behavior**
Product installs

**Logs**
[Install.log](https://github.com/canonical/multipass/files/5077965/Install.log)

**Additional info**
 - OS: macOS 11.0 Beta (20A5343j)
- `multipass version` 1.4.0

**Comment by puccaso** [comment]
ditto

**Comment by Saviq** [comment]
Duplicate of #1664

I'll collect all the macOS 11 issues under this one: #1664

**Comment by Saviq** [comment]
Duplicate of #1664
