### ISSUE TITLE
Configuration error with 00-snapd-config.yml

### ISSUE THREAD

**Issue by johncadengo** [canonical/multipass#1692]
#### Describe the bug
I am just starting the snap, literally the first step is to set up the network. I press "done" and receive this error.

#### To Reproduce
1. Boot into image for the first time
2. Press "Done" for the network configuration
3. Error

#### Expected behavior
I expect to be able to proceed to the next step

#### Screenshots
<img width="1159" alt="Screen Shot 2020-08-14 at 8 47 44 PM" src="https://user-images.githubusercontent.com/561587/90306475-79df1800-de82-11ea-96c7-ac109e76f395.png">

#### OS/snapd/snap version
I'm using Windows 10 Pro. Hyper-V. And Multipass. It happens with any appliance I try to launch with multipass.

Used this page to get started: https://ubuntu.com/appliance/nextcloud/vm#windows

Tried starting from scratch 3 times, and each time, I get the same error.

**Comment by Saviq** [comment]
Hi @johncadengo, with Multipass, you don't need to go into Hyper-V at all.

Just find the IP of the instance:
```
$ multipass list
```

And go to the appliance's URL for further setup. In the case of nextcloud, it's just [http://&lt;instance IP&gt;/]().

I'm going to close this, please reopen if you think that's not enough.

**Comment by johncadengo** [comment]
Hi, @Saviq, is going into Hyper-V not supported?

**Comment by Saviq** [comment]
> Hi, @Saviq, is going into Hyper-V not supported?

We try to make it unnecessary.

Here's an upstream subiquity bug (which is what you see on screen there) that you may want to comment on / subscribe to:

https://bugs.launchpad.net/subiquity/+bug/1879521

**Comment by johncadengo** [comment]
Are you saying you don't support Hyper-V or that your dependency on subiquity has a bug? Or both?
