### ISSUE TITLE
Multipass will no longer run on my Windows 10 

### ISSUE THREAD

**Issue by tosvfl** [canonical/multipass#1695]
**Describe the bug**
I installed multipass, and for a while it worked as expected.

Then suddenly it became impossible to run anything in an instance or get a shell. The only thing that happens is the following message: **[2020-08-17T14:55:30.132] [warning] [windows console] Could not read console input; error code: 1**

I have uninstalled multipass completely and reinstalled it again (actually twice now), but I end up with same result: **[2020-08-17T14:55:30.132] [warning] [windows console] Could not read console input; error code: 1.**

**To Reproduce**

Well, I can do nothing but reproduce, but it worked fine for a while after first install. Then suddenly this error happened, and there is nothing specific I can connect it to. So I can reproduce over and over, but I have no idea how to make someone else reproduce this. It worked, worked, and then it didn't. I did nothing strange, just stopping and starting.

How, and what happened?
1. `multipass shell` and `multipass exec` results in above message and no prompt nor anything executed!

**Expected behavior**
Commands executed with resulting output. For "shell" I expect to get a shell prompt, but that doesn't happen.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

### Log 1

```Loggnamn:      Application
Källa:         Multipass
Datum:         2020-08-17 14:42:41
Händelse-ID:   1
Aktivitetskategori:Ingen (activity)
Nivå:          Fel (level)
Nyckelord:     Klassiskt (keyword)
Användare:     Saknas ( user, value: missing)
Dator:         DESKTOP-OJBJFGO (computer: name)
Beskrivning: (description)
[VMImageHost] illegal value

Händelsens XML-data: (Event XML)
\<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"\>
  <System>
    <Provider Name="Multipass" />
    <EventID Qualifiers="0">1</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-17T12:42:41.522773500Z" />
    <EventRecordID>11144099</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-OJBJFGO</Computer>
    <Security />
  </System>
  <EventData>
    <Data>[VMImageHost] illegal value
</Data>
  </EventData>
</Event>```

### Log 2 

```Loggnamn:      Application
Källa:         Multipass
Datum:         2020-08-04 16:42:40
Händelse-ID:   1
Aktivitetskategori:Ingen
Nivå:          Fel
Nyckelord:     Klassiskt
Användare:     Saknas
Dator:         DESKTOP-OJBJFGO
Beskrivning:
[VMImageHost] illegal value

Händelsens XML-data:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Multipass" />
    <EventID Qualifiers="0">1</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-04T14:42:40.125910200Z" />
    <EventRecordID>11133863</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-OJBJFGO</Computer>
    <Security />
  </System>
  <EventData>
    <Data>[VMImageHost] illegal value
</Data>
  </EventData>
</Event>```

**Additional info**

- Windows 10 Professional, 64 Bit, 32 GB memeory.

```$ multipass info --all
Name:           hilarious-alewife
State:          Running
IPv4:           192.168.108.116
Release:        Ubuntu 18.04.5 LTS
Image hash:     3a1d9b89d5e8 (Ubuntu 18.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.0G out of 4.7G
Memory usage:   3.2G out of 3.9G
```

**Comment by Saviq** [comment]
Hi @tbs-fllabs-com what version of Multipass are you running? Did you upgrade recently? Can you think of anything that has changed between when it worked and when it stopped?

_Could not read console input_ suggests something with the console set up. Maybe code page? You seem to be using a Swedish locale, was that always the case?

**Comment by tbs-fllabs-com** [comment]
1.4.0+win (reinstalled it today)

**Comment by tbs-fllabs-com** [comment]
Yes, I'm using swedish locale, and have had swedish locale the whole time. 

I have asked myself the same question "what has changed?", but the only answer I come up with is "nothing". 

Do note that I'm using Windows 10 Hyper-V and not VirtualBox.

**Comment by tbs-fllabs-com** [comment]
After having ununstalled multipass there were some leftovers in Hyper-V. I removed them before reinstalling.

**Comment by Saviq** [comment]
> 1.4.0+win (reinstalled it today)

Could you please downgrade to [v1.3.0](https://github.com/canonical/multipass/releases/tag/v1.3.0) to see if 1.4.0 is what's at fault? Or can you confirm you used the new release fine?

> Do note that I'm using Windows 10 Hyper-V and not VirtualBox.

> After having ununstalled multipass there were some leftovers in Hyper-V. I removed them before reinstalling.

If you've switched from Hyper-V to VirtualBox after having used Hyper-V first, there may be leftovers, yes. But they should not matter.

When reinstalling, did you ask the uninstaller to purge everything? Or do you have data you'd like to recover?

Could you try another terminal application? Things like cmd.exe, PowerShell and Windows Terminal (normally) work fine.

**Comment by tbs-fllabs-com** [comment]
> > 1.4.0+win (reinstalled it today)
> 
> Could you please downgrade to [v1.3.0](https://github.com/canonical/multipass/releases/tag/v1.3.0) to see if 1.4.0 is what's at fault? Or can you confirm you used the new release fine?

I downloaded and installed version 1.3.0 after uninstalling again. Then did a launch:

```
tommy@DESKTOP-OJBJFGO MINGW64 ~
$ multipass launch -c 4 -m 4G --name test4
launch failed: The following errors occurred:
test4: timed out waiting for response

tommy@DESKTOP-OJBJFGO MINGW64 ~
$ multipass list
Name                    State             IPv4             Image
test4                   Running           UNKNOWN          Ubuntu 18.04 LTS

tommy@DESKTOP-OJBJFGO MINGW64 ~
$ multipass shell test4
shell failed: ssh connection failed: 'Failed to resolve hostname test4.mshome.net (unknown host)'

```

This is a different message / error than before!

> 
> > Do note that I'm using Windows 10 Hyper-V and not VirtualBox.
> 
> > After having ununstalled multipass there were some leftovers in Hyper-V. I removed them before reinstalling.
> 
> If you've switched from Hyper-V to VirtualBox after having used Hyper-V first, there may be leftovers, yes. But they should not matter.

I've only used Hyper-V! I have a virtualbox installation that I used for something else earlier, but not for Multipass.

> 
> When reinstalling, did you ask the uninstaller to purge everything? Or do you have data you'd like to recover?

I told it to purge.
> 
> Could you try another terminal application? Things like cmd.exe, PowerShell and Windows Terminal (normally) work fine.

Same in powershell.

**Comment by Saviq** [comment]
> ```
> tommy@DESKTOP-OJBJFGO MINGW64 ~
> $ multipass shell test4
> shell failed: ssh connection failed: 'Failed to resolve hostname test4.mshome.net (unknown host)'
> ```
> 
> This is a different message / error than before!

Indeed, and much different.

Can you please look through [our network troubleshooting docs](https://multipass.run/docs/troubleshooting-networking-on-windows) to see if removing the default switch / clearing the leases file helps?

> I've only used Hyper-V! I have a virtualbox installation that I used for something else earlier, but not for Multipass.

Sorry, misread what you wrote above.

It's still unclear why 1.4.0 wouldn't work, the only recent change to Windows console handling we did in 1.3.0 already…

**Comment by tbs-fllabs-com** [comment]
Content of hosts.ics:
```
192.168.108.113 DESKTOP-OJBJFGO.mshome.net # 2025 8 6 16 12 50 56 958
192.168.108.116 hilarious-alewife.mshome.net # 2020 8 1 24 12 50 56 958
192.168.108.121 mytest.mshome.net # 2020 8 1 24 12 13 22 995
192.168.108.125 primary.mshome.net # 2020 8 1 24 12 36 34 93
192.168.108.122 test2.mshome.net # 2020 8 1 24 12 6 43 741
```
Note that _test4_ created by version 1.3 never got added to hosts.ics. The others are probably still here due to that I never removed them before uninstalling.

**Comment by Saviq** [comment]
> Note that _test4_ created by version 1.3 never got added to hosts.ics. The others are probably still here due to that I never removed them before uninstalling.

Did you try removing the Default Switch and rebooting, to try and reset it? Could also confirm in Hyper-V that _test4_ is connected to it.

FWIW the stale ones are fine, they will get cleared in due time.
