### ISSUE TITLE
instances lossing after windows updated

### ISSUE THREAD

**Issue by cpu100** [canonical/multipass#1698]
These directories `C:\Windows\System32\config\systemprofile\AppData\*\multipassd\` will be removed after windows big-updates, so it's a bad idea to store related data at there.

**Comment by Saviq** [comment]
Hi, we are tracking this here:

Duplicate of #1119

**Comment by Saviq** [comment]
Duplicate of #1119

**Comment by Saviq** [comment]
FWIW they're not getting removed, they get moved to `C:\Windows.old…`, but that doesn't change the fact we need a better place.
