### ISSUE TITLE
`multipass mount` allows mounting over instance rootfs

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#17]
`multipass mount $PWD instance:/` is accepted (although it did crash on me once), `sshfs` is running inside the instance, but rootfs is fortunately safe.

When it did mount, trying to `multipass umount instance` sent the daemon into a loop somewhere.

Still, we should sanitize the target path somewhat.

**Comment by townsend2010** [comment]
Ok, we definitely shouldn't allow mounting over the VM's root.  So along with sanitizing '/', which other paths should we sanitize?  Perhaps '/dev', '/proc', '/sys', and ?????

**Comment by townsend2010** [comment]
Anyone have any any other input as to what paths in the VM we should not mount over???

**Comment by Saviq** [comment]
$HOME seems problematic, too?

**Comment by townsend2010** [comment]
Yes, currently $HOME is a problem since that effectively removes the multipass generated ssh key and causes issues for mounts and connect/exec.

**Comment by townsend2010** [comment]
So, filter out '/' and '$HOME'.  Any others?

**Comment by Saviq** [comment]
Well, yeah, `/sys`, `/proc`, `/dev` as well. Others I think are safe.

**Comment by townsend2010** [comment]
Ack, thanks, just want to make sure:)

**Comment by townsend2010** [comment]
Also, I think for /sys, /proc, and /dev, we should not allow any mounts under those directories either.

**Comment by Saviq** [comment]
Right, so the matches would roughly be:
```
^/$
^/dev/
^/proc/
^/sys/
^/home/ubuntu/$
```
