### ISSUE TITLE
Failed to launch on  Virtualboxed Windows 10

### ISSUE THREAD

**Issue by biocyberman** [canonical/multipass#1707]
**Describe the bug**
I installed Multipass version 1.4 on Windows 10. This Windows 10 is a evaluation installation for Windows 10 enterprise. Multipass failed to launch or start VMs

**To Reproduce**
How, and what happened?

```
 multipass launch -vvv 20.04
[2020-08-26T05:53:00.779] [debug] [Hyper-V Health Check] powershell arguments '-NoProfile, -NoExit, -Command, -'

[2020-08-26T05:53:00.779] [debug] [Hyper-V Health Check] powershell working dir ''

[2020-08-26T05:53:00.779] [debug] [Hyper-V Health Check] powershell program 'powershell.exe'

[2020-08-26T05:53:00.779] [debug] [Hyper-V Health Check] powershell state changed to Starting

[2020-08-26T05:53:00.779] [debug] [Hyper-V Health Check] powershell state changed to Running

[2020-08-26T05:53:00.791] [debug] [Hyper-V Health Check] powershell started

[2020-08-26T05:53:05.317] [debug] [Hyper-V Health Check] powershell state changed to NotRunning

[2020-08-26T05:53:05.317] [debug] [Hyper-V Health Check] powershell finished with exit code 0

launch failed: The following errors occurred:
brimming-gudgeon: timed out waiting for response
[2020-08-26T05:55:34.310] [warning] [winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.

```
**Expected behavior**

Virtual machine is launched successfully.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Freshly installed Windows 10 Enterprise version 2004. Build 19041.450
- `multipass version`: multipass  1.4.0+win
- `multipass info --all`
```
 multipass info --all
Name:           brimming-gudgeon
State:          Stopped
IPv4:           --
Release:        --
Image hash:     896d13fcadd1 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
````

**Additional context**
I want to install multipass on windows to see how it works on Windows. But I do not have a windows computer therefore I create a virtualbox windows machine and test Multipass there in. I don't know if this could be a problem.

**Comment by Saviq** [comment]
Hi @biocyberman, what you're asking for is nested virtualization. While possible (modulo host OS and hypervisor), it's irritably unstable and not something Multipass can do anything about.

VirtualBox [claims it can do it](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html), but we've been unable to get it to work.

If you get it working, please report back, but I'll close this issue as there's nothing we can do about it.

**Comment by biocyberman** [comment]
@Saviq Thanks for the info. I don't understand the last debug message:

`[winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.` 

It will be helpful if you could shed some light on it.

**Comment by Saviq** [comment]
> @Saviq Thanks for the info. I don't understand the last debug message:
> 
> `[winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.`
> 
> It will be helpful if you could shed some light on it.

That's just information that you have the [Windows Terminal](https://github.com/Microsoft/Terminal) integration enabled (because it's the default), but Terminal itself isn't installed. The message wouldn't be there without `-vvv`.
