### ISSUE TITLE
Flooding in the events log

### ISSUE THREAD

**Issue by ruv** [canonical/multipass#1712]
**Describe the bug**
Too many superfluous records in the log: the message "Got VMState: running" was added every second.

**To Reproduce**
It seems, the command that triggered this flood, was either
`multipass launch --name ubuntu-lts`
or
`multipass shell ubuntu-lts`
(that has **hung** — it didn't read input/stdin, and the corresponding multipass process was killed after that)

**Expected behavior**
Avoid utterly useless messages in the log.

**Logs**
Export from Event viewer in "CSV" format, the last event at the top, several thousands "Got VMState: running" lines in the middle are removed: [events.filtered.csv.log](https://github.com/canonical/multipass/files/5154256/events.filtered.csv.log)

**Additional info**
 - OS: Windows 7
- `multipass version`
  - multipass  1.4.0+win
  - multipassd 1.4.0+win
- VirtualBox 6.0

**Comment by Saviq** [comment]
Hi @ruv, you're right, we should move that line to `trace` level. Thanks for reporting.

**Comment by marblerun** [comment]
One year on, state is unchanged

Application log is being flooded with and event every second, Could do a bit better

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Multipass" /> 
  <EventID Qualifiers="0">1</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-09-17T09:17:22.7320338Z" /> 
  <EventRecordID>28615128</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>*********</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>[phlegmatic-drum] Got VMState: poweroff</Data> 
  </EventData>
  </Event>
