### ISSUE TITLE
File/directory ownership unmapped if changed with `chown`

### ISSUE THREAD

**Issue by facundobatista** [canonical/multipass#1718]
```bash
$ multipass launch -n test
$ mkdir foo
$ ls -ld foo
drwxrwxr-x 2 michal michal 2 wrz  3 14:10 foo
# correct ownership on host

$ multipass mount foo test:foo --uid-map 1000:0 --gid-map 1000:0
$ multipass exec test -- ls -ld foo
drwxrwxr-x 2 root root 2 wrz  3 14:10 foo
# correct ownership inside the instance

$ multipass exec test -- sudo chown 0:0 foo
$ ls -ld foo
drwxrwxr-x 2 root root 2 wrz  3 14:10 foo
# this should be michal:michal still!
```

**Comment by facundobatista** [comment]
Just found that if internally I copy the stuff by doing `cp -r --preserve=mode,timestamps otherdir/stuff/ somedir/`, internally I see them as `root`, but from outside everything is owned by `facundo`!!

**Comment by Saviq** [comment]
> Just found that if internally I copy the stuff by doing `cp -r --preserve=mode,timestamps otherdir/stuff/ somedir/`, internally I see them as `root`, but from outside everything is owned by `facundo`!!

Yes, it all suggests we forget to make a reverse ownership mapping when `chown` happens.

**Comment by BenWibking** [comment]
Is there any update on this?

**Comment by Saviq** [comment]
@BenWibking thanks for the bump. We'll schedule this to fix, soon.

**Comment by BenWibking** [comment]
Did this get fixed in version 1.7?

**Comment by townsend2010** [comment]
Hey @BenWibking!

We started to work on it, but found that it had more implications that need consideration such as security, etc. and did not want to block the release for this.

That said, we are going to discuss internally how best to handle this and it should be addressed in the next release.

**Comment by yingshaoxo** [comment]
I could suggest you guys use this to make sure all the permission is right in side of multipass:

```bash
sudo chown -R $(whoami):$(whoami) .
sudo chmod g+rw .
```
