### ISSUE TITLE
Recover shell access to instance after removing .ssh directory

### ISSUE THREAD

**Issue by pierrestoffe** [canonical/multipass#1721]
I accidentally removed the ~/.ssh directory of an instance today. My issue is that I have a few important files on this instance and would like to recover them, but...
- I can't SSH into it since the authorized_keys file is gone
- I can't use `multipass exec` commands (Access denied for 'publickey')
- I can't use `multipass mount` commands (Access denied for 'publickey')
- I basically can't use any multipass command, the access is always denied

Is there another way to log into the instance, so I could recover some files? Or a way to only read files? Or, even better, a way to push new files to the instance without SSH authentication, so I could create a new ~/.ssh directory and authorized_keys file?

Thanks in advance!

**Comment by Saviq** [comment]
Hi @pierrestoffe, SSH is how we access the instance, too, so removing that folder severed that connection.

Currently the easiest way would be to mount the image file and manipulate it directly. It's trivial if you're on Linux, less so on macOS and Windows.

We have #131 talking about with this, and [there's documentation on how to do this on Linux](https://www.kumari.net/index.php/system-adminstration/49-mounting-a-qemu-image).

I'll close this one, let's continue the discussion on #131.

**Comment by pierrestoffe** [comment]
Thanks @Saviq, it lead me to a solution.

My host is running macOS and I was able to regain (read) access to the files from the image. It took many attempts so if you're running into the same issue, here is what you can try:

1. Copy the .img file from _/var/root/Library/Application\ Support/multipassd/vault/instances/{my-instance}_ to a temporary folder that can be easily accessed, such as your Desktop. The _/var/root_ directory can only be accessed from the Terminal, which isn't the most practical for what follows.

2. Install a few things:
    - Virtual Box (https://www.virtualbox.org)
    - FUSE (https://osxfuse.github.io)
    - Paragon VMDK Mounter (https://macdownload.informer.com/paragon-vmdk-mounter) → you will need a serial but the app is discontinued… luckily you can easily find one using Google
    - `brew install qemu ext4fuse`

Then restart your computer (it's important).

3. Convert the .img file to a .raw file
`qemu-img convert ~/Desktop/{my-image}.img -O raw ~/Desktop/{my-image}.raw`

4. Convert the .raw file to a .vpi file
`VBoxManage convertfromraw ~/Desktop/{my-image}.raw --format vdi ~/Desktop/{my-image}.vdi`

5. Open the .vpi file with Paragon VMDK Mounter. From this point on, the disk should be mounted on your Mac, but not browsable yet. You can verify this by typing `diskutil list` in your terminal. The last disk should contain a Linux Filesystem partition. Write down the identifier of that partition. In my case it is `disk3s1`.

6. Mount the partition to a Volume with this command: `ext4fuse /dev/{partition-identifier} /Volumes/tmpfolder`. You should now be able to visit the _/Volumes/tmpfolder_ directory and access the data from your previously-inaccessible instance.

One note: I had to go through all these steps because I had disabled password authentication on the instance. People who didn't disable password authentication could simply load the image with `sudo qemu-system-x86_64 -m 2048M -no-reboot ~/Desktop/{my-image}.img`.
