### ISSUE TITLE
Mount does not follow symlinks

### ISSUE THREAD

**Issue by clubh** [canonical/multipass#1722]
Mounting using sshfs does not follow symlinks on Mac.

If ~/www is a symlink then the mounting succeeds to create localsrv:/www,  but the directory is empty.

multipass mount ~/www localsrv:/www

Is there a way to enable follow_symlinks when mounting?

- OS: OSX Catalina
- Multipass: 1.4

**Comment by Saviq** [comment]
Hi @clubh, symlinks are reflected as-is within the mount, but I agree we should resolve the source of the mount at mount time, if it's a symlink.

Note this would mean that if you changed the symlink while the mount is active, it wouldn't be reflected until the mount was restarted. WDYT?

**Comment by clubh** [comment]
Hi @Saviq,

Correct, changing the symlink while the mount is active does not change anything. Restarting the instance changed the mount.

Is there a way to force sshfs to always follow symlinks?

**Comment by Saviq** [comment]
> Is there a way to force sshfs to always follow symlinks?

It would be our internal SFTP server, not sshfs itself, and no - not at the moment. We _could_ make it an option on `mount` if there was interest, but that would be a separate issue than this bug.

**Comment by clubh** [comment]
I fixed it like this:

multipass mount $(readlink /www) localsrv:/www

**Comment by surahman** [comment]
Has this issue been resolved? If not, am I correct in my assessment that it needs to be handled here:
https://github.com/canonical/multipass/blob/7a1e2bae571ccf236b98c3a55b2e051388879caf/src/sshfs_mount/sftp_server.cpp#L969-L1001
?
