### ISSUE TITLE
Downloading ubuntu instances is very slow!

### ISSUE THREAD

**Issue by YousefSaber** [canonical/multipass#1726]
downloading Ubuntu instances is very slow my connection can reach up to 30 Mbps and downloading Ubuntu instances takes only 1.5 Mbps of my bandwidth !!!!

my connection is very good there is no packet loss or whatsoever

**Comment by Saviq** [comment]
Sorry @YousefSaber, we're downloading directly from http://cloud-images.ubuntu.com/, unless you get higher speeds downloading e.g. this URL:

http://cloud-images.ubuntu.com/releases/releases/20.04/release/ubuntu-20.04-server-cloudimg-amd64.img

There's nothing we (Multipass) can do about it...

I'll close this for now, please reopen if you confirm Multipass is at fault.

**Comment by rnz** [comment]
Multipass is unusable with this slow downloading from http://cloud-images.ubuntu.com

**Comment by YousefSaber** [comment]
@Saviq as far as I know Canonical develops both Ubuntu and Multipass you may want to reach out to the correct team and report this issue to them.

**Comment by Saviq** [comment]
Can you guys confirm the speeds you get when downloading a random file from there? It is a known issue, we have recently tripled the bandwidth available there (to 3Gbps), I suppose that may still not be enough from time to time. There's a plan to put it on an even faster link, but I can't give you the timelines.

**Comment by dilchenko** [comment]
I just ran into this as well. Blazing fast download of http://cloud-images.ubuntu.com/releases/releases/20.04/release/ubuntu-20.04-server-cloudimg-amd64.img in the browser, maybe 10 seconds to download it. I cancelled `multipass launch` after 30 minutes and 40%.

**Comment by townsend2010** [comment]
Hey @dilchenko,

Canonical has been experiencing some infrastructure issues.  Depending on which mirror it's been routed to, the download is very slow.  I've experienced slow downloads with both my browser and Multipass.

**Comment by dilchenko** [comment]
Interesting. This morning the download went blazing fast. Thanks.
