### ISSUE TITLE
Transparency and clear communication that services are started/running

### ISSUE THREAD

**Issue by jnnksdev** [canonical/multipass#1728]
**What are you trying to do?**
VirtualBox Machines fail to start with the following log entry:
```
ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={The console is not powered up}, preserve=false aResultDetail=0
```
Maybe this is clear for more experienced users, but I had trouble finding the cause for it. Multipass was running in the background.

**What's your proposed solution?**
Lazy launching multipass when actually requested by the user.
Or clearly communicating a launch at system start.

**Additional context**
Snapcraft uses multipass to manage build VMs. After building a snap package, multipass was still active and even after a full reboot running in the background. Snapcrafts start on login was turned off at that point.

VirtualBox suddenly refuses to boot virtual machines with an ambiguous error message.

I suppose `/snap/multipass/2531/usr/bin/qemu-system-x86_64` was blocking system resources, leading to the access denied error message.

Since this might be more of a snapcraft issue, please refer me to the correct place to report this, if not applicable.

**Comment by Saviq** [comment]
Hi @jnnksdev, on boot, we only start the instances that were running when Multipass was shut down (so, prior to rebooting). If you had a `snapcraft-*` instance running, that suggests a bug (Snapcraft uses a delayed shutdown mechanism to not cycle the instances unnecessarily) either in Multipass, or in Snapcraft.

And yes, KVM and VirtualBox unfortunately don't work together.

**Comment by jnnksdev** [comment]
Ah I see. I had the impression there were no running VMs before shutting down, which lead to my confusion.
The behaviour I experienced suggested, that Multipass was launching on system start without reason.

At the time a notification would have been nice, but considering the circumstances it's not necessary.

I will open another ticket if the issue is reproducible.

Thanks for the info.
