### ISSUE TITLE
Is it possible to run multipass client inside docker to control multipassd on host

### ISSUE THREAD

**Issue by moondev** [canonical/multipass#1731]
**What are you trying to do?**
I want to orchestrate multipass on the host machine from the multipass client inside a docker container. Similar to how host docker socket can be mounted inside a container to launch containers on the host.

**What's your proposed solution?**
Is this possible? I have multipass client installed in the container, but I am not having luck mounting the host socket. Can this be done over tcp or is unix socket needed?

**Additional context**
If this is possible, what volumes should be mounted inside the container?

I want to orchestrate multipass without ssh. Any thoughts on this?

**Comment by Saviq** [comment]
Hi @moondev, you should be able to mount the multipass socket (`/var/snap/multipass/common/multipass_socket`) and have the client talk there (provided you don't have the daemon running inside).

Alternative would be to provide a TCP socket for Multipass to listen on:
```bash
 snap run multipass.multipassd --help 
Usage: /snap/multipass/2531/bin/multipassd [options]
multipass service daemon

Options:
  -h, --help                                        Displays this help.
  -v, --version                                     Displays version
                                                    information.
  --logger <platform|stderr>                        specifies which logger to
                                                    use
  -V, --verbosity <error|warning|info|debug|trace>  specifies the logging
                                                    verbosity level
  --address <server_name:port>                      specifies which address to
                                                    use for the multipassd
                                                    service; a socket can be
                                                    specified using
                                                    unix:<socket_file>
```

And then set `MULTIPASS_SERVER_ADDRESS` to `<ip>:<port>` on the host. Note we've not documented this because we've not given it much testing. You'll still need direct network paths to the instances for some commands to work, too.

**Comment by moondev** [comment]
Thanks @Saviq ! Marking this as closed.

**Comment by theko2fi** [comment]
Hi @moondev, did you manage to get this working ? I want to achieve the same thing. Running multipass commands from a docker container.
