### ISSUE TITLE
[Reference] Multipass instances not launching on windows and how to fix it

### ISSUE THREAD

**Issue by flying-sausages** [canonical/multipass#1732]
I've had issues after a recent Windows update, where My WSL2 didn't start and neither did my multipass instances. I saw messages like the ones below.

![image](https://user-images.githubusercontent.com/23618693/93083486-f851f400-f692-11ea-8f10-21bbe3751a05.png)

I followed the steps outlined in this comment on the WSL repo and managed to fix both issues with multipass and WSL2

https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294

Hope this helps the next person struggling with this.

**Comment by Saviq** [comment]
Thanks @flying-sausages! We'll work it into our docs.
