### ISSUE TITLE
Mounting breaks when ubuntu user has a password set

### ISSUE THREAD

**Issue by flying-sausages** [canonical/multipass#1734]
**Describe the bug**
After setting a password for the `ubuntu` user using `passwd`, it is no longer to perform certain operations like `multipass mount`.

**To Reproduce**
How, and what happened?
1. `multipass shell <primary>`
2. `sudo passwd ubuntu`
3. `exit` back to the parent shell
4. `multipass mount <primary> ./`
   - --> Returns: ```error mounting "C:/Users/me/directory": Process returned exit code: 1: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper```

**Expected behavior**
A succesful `multipass mount`

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

```
PS C:\Users\me> multipass mount .\dir -vvv
[2020-09-15T12:06:24.554] [debug] [mount cmd] ..\src\client\cli\cmd\mount.cpp:232 multipass::cmd::Mount::parse_args(): adding default uid/gid mapping
[2020-09-15T12:06:24.595] [info] [sshfs-mounts] mounting C:/Users/me/dir => C:/Users/me/dir in primary

 /[2020-09-15T12:06:24.595] [info] [sshfs-mounts] process program 'C:/Program Files/Multipass/bin/sshfs_server'

 /[2020-09-15T12:06:24.596] [info] [sshfs-mounts] process arguments 'primary.mshome.net, 22, ubuntu, C:/Users/me/dir, C:/Users/me/dir, -2:-1,, -2:-1,'

 /[2020-09-15T12:06:24.596] [debug] [basic_process] starting: C:/Program Files/Multipass/bin/sshfs_server primary.mshome.net 22 ubuntu C:/Users/me/dir C:/Users/me/dir -2:-1, -2:-1,

 /[2020-09-15T12:06:25.048] [debug] [C:/Program Files/Multipass/bin/sshfs_server] sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper


 /[2020-09-15T12:06:25.051] [warning] [sshfs-mounts] Mount C:/Users/me/dir' in instance "primary" has stopped unexpectedly: Process returned exit code: 1

mount failed: The following errors occurred:
error mounting "C:/Users/me/dir": Process returned exit code: 1: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

**Additional info**
 - OS: Windows 10
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎13/‎2019
OS build	19042.508
Experience	Windows Feature Experience Pack 120.2212.31.0
```
- `multipass version`
```
multipass  1.4.0+win
multipassd 1.4.0+win
```
- `multipass info --all`
```
Name:           primary
State:          Running
IPv4:           172.19.23.42
Release:        Ubuntu 20.04.1 LTS
Image hash:     995771784f85 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     2.8G out of 4.7G
Memory usage:   286.0M out of 916.9M```

**Additional context**
Add any other context about the problem here.

**Comment by Saviq** [comment]
It's not about setting password via `passwd`, did you change something in `/etc/sudoers.d`? That's where the `ubuntu` user should have no-password `sudo` permissions:

```
$ sudo cat /etc/sudoers.d/90-cloud-init-users
# Created by cloud-init v. 20.2-45-g5f7825e2-0ubuntu1~20.04.1 on Tue, 15 Sep 2020 11:06:40 +0000

# User rules for ubuntu
ubuntu ALL=(ALL) NOPASSWD:ALL
```

**Comment by Saviq** [comment]
I just confirmed setting a password does not break mounts. As long as you can `sudo` without a password as the `ubuntu` user, the mounts work.

I'll close, please reopen if you find otherwise.

**Comment by flying-sausages** [comment]
Yes, you're right. My setup script made the sudo password-ed.

But if this `multipass mount` logic relies on there being a password-less sudo, could this have some undesired security/usability implications? i.e. if I have to have a password-less sudo to mount, does that mean that `ubuntu` accounts without password-less are unsuported? What would happen if a user were to delete the `ubuntu` user and make their own instead?

Wouldn't it make sense to have this sshfs mount established through the root account instead? You could easily establish a connection into the VM's root account with a key-based SSH and issue whatever commands necessary, instead of relying on the `ubuntu` user?

I'm more curious than anything else, so thanks in advance if you find the time time to explain the way you guys do things.

**Comment by Saviq** [comment]
> I'm more curious than anything else, so thanks in advance if you find the time time to explain the way you guys do things.

Correct, we currently rely on password-less `sudo`. SSH-ing as `root` is always an irk (with sudo you get a log of _who_ it was that executed a `sudo` command). You could also limit the password-less `sudo` to just some commands that you're OK with. We've not spent the time to do this as it's a corner-case.

**Comment by flying-sausages** [comment]
Thanks for the explanation! I have a lot more questions but I'll ask them someplace else some other time :)

What about a dedicated system user without a shell created in the VM after launch (the same way `ubuntu` is created, I suppose? cloudinit?) called `multipass-worker` or something of the like, through which you can can administer the machine without relying on a user that is exposed to the end-user as well?

Traceability scope through `auth.log` would be the same if not slightly better as you can see what was done by end-user and what was done via `multipass` commands. The end-user would then also have complete freedom over what they want to do with the `ubuntu` user, their home directory, references to them in `sudoers` files etc.

I don't know if it's the case that the `ubuntu` user is a standard non-root sudoable account that shouldn't be touched but I assume that if I'm given passwordless access to an account that isn't called `root`, I feel like I have full control over it and can use it as "my own". If that is the case here, it would be nice to have that somewhat communicated/doc'd too, or guide users to make their own accounts after `launch` the same way mounts are communicated after `launch`.

**Comment by Saviq** [comment]
> What about a dedicated system user without a shell created in the VM after launch (the same way `ubuntu` is created, I suppose? cloudinit?) called `multipass-worker` or something of the like, through which you can can administer the machine without relying on a user that is exposed to the end-user as well?

Yes, that's one of the options we're looking at. Another is to connect to the instance through a dedicated socket fed out to the host (i.e. [vsock](https://www.man7.org/linux/man-pages/man7/vsock.7.html) when available.

> Traceability scope through `auth.log` would be the same if not slightly better as you can see what was done by end-user and what was done via `multipass` commands. The end-user would then also have complete freedom over what they want to do with the `ubuntu` user, their home directory, references to them in `sudoers` files etc.

Yes, that's entirely true.

> I don't know if it's the case that the `ubuntu` user is a standard non-root sudoable account that shouldn't be touched but I assume that if I'm given passwordless access to an account that isn't called `root`, I feel like I have full control over it and can use it as "my own". If that is the case here, it would be nice to have that somewhat communicated/doc'd too, or guide users to make their own accounts after `launch` the same way mounts are communicated after `launch`.

The `ubuntu` account is following the cloud "standard", so we're unlikely to remove it (by default). You can always configure additional users, and we will probably allow configuration of the default username in due time.
