### ISSUE TITLE
multipass launch failed with qemu-img error on Win 10 home

### ISSUE THREAD

**Issue by surendrasah** [canonical/multipass#1746]
I am trying to launch the  multipass from windows 10 Home.

 multipass set local.driver=virtualbox   was ok
C:\WINDOWS\system32> multipass --version
multipass  1.4.0+win
multipassd 1.4.0+win
C:\WINDOWS\system32> multipass launch
launch failed: Conversion of image to VDI failed (program: qemu-img; error: Process operation timed out) with the following output:

I tried these command on powershell using admin right. please advise on the launch failed

**Comment by Saviq** [comment]
Hi @surendrasah,

> Process operation timed out

This means the image conversion took more than 30s. We had that timeout at a more realistic 5 minutes, but a recent refactor lost that value.

Thanks for reporting, we'll fix in the next release.

**Comment by Saviq** [comment]
Hi @surendrasah, you can try the build [from here](https://github.com/canonical/multipass/commit/01db733739b4120daadcbb7ac8e9b35102db5a71#commitcomment-42585979) to confirm that fixes it for you.
