### ISSUE TITLE
Errors after installation on Mac: “Failure retrieving instances” and “find failed: multipass socket access denied”

### ISSUE THREAD

**Issue by aviflax** [canonical/multipass#1749]
### Describe the bug

I installed via `brew cask install multipass` — it installed `1.4.0+mac` and seemed to have succeeded.

But maybe not.

When I run the Multipass Mac “app” via Spotlight, the menubar icon shows up, but `Start` and `Stop` are grayed out, and below `Stop` I see `Failure retrieving instances`. (The whole menu is also flashing at about 1hz, so I assume some operation is continually retrying and failing.)

When I run the CLI tool I get a different error:

```shell
$ multipass find -vvvv    
find failed: multipass socket access denied
Please check that you have read/write permissions to '/var/run/multipass_socket'
```

### To Reproduce

How, and what happened?

I covered this above.

### Expected behavior

Not sure, I’m a new user. I guess I wanted to be able to list images, launch instances, etc?

### Logs

```shell
$ sudo cat /Library/Logs/Multipass/multipassd.log
Password:
[2020-09-22T12:00:18.305] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket, SSL:on
[2020-09-22T12:00:18.307] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Caches/multipassd/vault/multipassd-image-records.json"): device not open
[2020-09-22T12:00:18.309] [info] [daemon] Starting Multipass 1.4.0+mac
[2020-09-22T12:00:18.309] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug
[2020-09-22T12:00:20.411] [debug] [update] Latest Multipass release available is version 1.4.0
[2020-09-22T18:00:18.297] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Caches/multipassd/vault/multipassd-image-records.json"): device not open
[2020-09-22T18:00:18.298] [debug] [image vault] Checking for images to update…
```

### Additional info

 - OS: macOS 10.15.6
- `multipass version` → `multipass  1.4.0+mac`
- `multipass info --all` → 
   ```
   info failed: multipass socket access denied
   Please check that you have read/write permissions to '/var/run/multipass_socket'
   ```

I checked the above:

```shell
$ ls -al /var/run/multipass_socket
srw-rw----  1 root  admin  0 Sep 22 12:00 /var/run/multipass_socket
```

So it looks to me like I *do not* have read/write permission to that path.

### Additional context

* Maybe the problem is that my MacOS user account is not an admin account?
  * Seems likely
* I guess I could change the permissions on that path, but before I do that, I’d love to hear from the team.
  * It seems to me that the installer should take care of things like this.

**Comment by Saviq** [comment]
Hi @aviflax, you're exactly right, the user running `multipass` needs to have admin privileges at the moment. The reason for that is that the Multipass daemon runs as root, and you can `multipass mount` any folder into the instance, thus access files you would normally not have access to.

We have ideas about locking things down, just never go there yet.

**Comment by aviflax** [comment]
ok, thanks.

Even if this isn't a technical bug, isn't it a UX bug? A clearer error message would have saved us both time and effort.

**Comment by Saviq** [comment]
You mean for this message:
> Please check that you have read/write permissions to '/var/run/multipass_socket'`

To be more explicit about privileges?

**Comment by aviflax** [comment]
Yes, I suggest changing “check” to “ensure” and adding some more guidance, something like “You could try sudo chmod 777 /var/run/multipass_socket” or “Please see this page <url> for more help”.

Also, it’d be great to have the installer and/or the CLI explicitly check for this situation — whether or not the current user is an admin — and proactively give the user a warning and some guidance about it.

**Comment by dmuiX** [comment]
This seems to help with this error:
`
sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist && sudo launchctl load /Library/
LaunchDaemons/com.canonical.multipassd.plist
`
