### ISSUE TITLE
AMD Ryzen on Ryzentosh - Error - Your CPU does not have the features necessary for Multipass. Installation cannot proceed.

### ISSUE THREAD

**Issue by paulomcnally** [canonical/multipass#1754]
**Mi PC**:

https://valid.x86.fr/238hc7

**The install command**:

`brew cask install multipass`

**The error**
Error - Your CPU does not have the features necessary for Multipass. Installation cannot proceed.

**Comment by Saviq** [comment]
Hi @paulomcnally, what's your host OS? We only support macOS via `brew`…

**Comment by Saviq** [comment]
Oh ryzentosh, sorry we can't support this as Apple doesn't.

**Comment by dmarkey** [comment]
Is there a way to bypass, and just say YMMV for the user?

**Comment by Saviq** [comment]
@dmarkey unless `sysctl -n kern.hv_support` returns "1", virtualization just doesn't work, so there's no point in even installing Multipass.

**Comment by dmarkey** [comment]
Well Virtualbox is a valid backend right? And it works as I'm using it.

**Comment by Saviq** [comment]
@dmarkey you can always hack the installer with `pkgutil` if you wish.
