### ISSUE TITLE
Support suspend on macOS / hyperkit

### ISSUE THREAD

**Issue by ehrktia** [canonical/multipass#1758]
**multipass version details**
```  ~ multipass --version
multipass  1.4.0+mac
multipassd 1.4.0+mac
```
issue:
```
➜  ~ multipass suspend primary -v
suspend failed: suspend is currently not supported
```

**Comment by Saviq** [comment]
Hi @ehrktia, if you'd like, you can [use VirtualBox](https://multipass.run/docs/using-virtualbox-in-multipass-macos) with Multipass to get suspend working.

**Comment by ehrktia** [comment]
thanks very much for quick help will follow the same.
