### ISSUE TITLE
New instance won't start due to firewall

### ISSUE THREAD

**Issue by huwshimi** [canonical/multipass#177]
I tried to create a new instance, but it wouldn't start due to the error: `start failed: failed to determine IP address`.

It turns out this due to my firewall, so running `sudo ufw disable` allowed it to work.

If it's possible it may be helpful if multipass was able to provide some kind of hint as to why it can't determine the IP address.

**Comment by townsend2010** [comment]
Hello @huwshimi,

Are you using Multipass from edge or beta?  edge *should* have a fix for this, so if you are using that channel, then we need to dig further into why the firewall is blocking your VM from obtaining an IP from dnsmasq.

**Comment by albaguirre** [comment]
@townsend2010 it was beta 2018.2.1, which has the firewall fix (7413dd3c).

**Comment by townsend2010** [comment]
@albaguirre,

Oh, I was going by the announcement @Saviq sent out referencing #150 as being part of HEAD and not in the beta release, but the git tag says otherwise:)

**Comment by Saviq** [comment]
Does it though? The release was branched at b5c814fb and only ee146779 got added on top https://imgur.com/a/iSj94 - 7413dd3c is like 10 commits further in master.

**Comment by albaguirre** [comment]
Oh yeah I was misreading tig's log.

So then should be fixed in edge then like @townsend2010 said.
