### ISSUE TITLE
[win10] How can I move the instance to custom folder?

### ISSUE THREAD

**Issue by ahaoboy** [canonical/multipass#1786]
**Describe the bug**
Describe what your problem is.
I want to move the instance to D://multipass, because it's too big, but I don't find any docs or commands.
![image](https://user-images.githubusercontent.com/19884146/95293566-3f07c800-08a6-11eb-9598-f248f7342df5.png)

**Expected behavior**
What did you expect to happen?
I can set the folder where the instance is created or I can move it to custom folder

**Comment by Saviq** [comment]
Hi @ahaoboy, this is discussed in #1215.

**Comment by Saviq** [comment]
Duplicate of #1215

**Comment by Saviq** [comment]
Hi @ahaoboy, I've described a workaround in https://github.com/canonical/multipass/issues/1215#issuecomment-705408845.
