### ISSUE TITLE
launch with file:// does not use absolute path

### ISSUE THREAD

**Issue by kmcd** [canonical/multipass#1794]
**Describe the bug**

Multipass raises an error when launching from a disk image with an absolute file path.

**To Reproduce**

How, and what happened?

1. `multipass launch --name foo xenial`
1. `cp /var/snap/multipass/common/data/multipassd/vault/instances/foo/ubuntu-16.04-server-cloudimg-amd64-disk1.img /tmp/test.img`
1. `multipass launch file:///tmp/test.img`

:boom: 

```shell 
launch failed: Custom image `/tmp/test.img` does not exist. 
```

**Expected behavior**

Launch an instance with the file path passed.

**Additional info**

 - OS: ubuntu 1804
- `multipass version 1.4.0`
- `multipass info --all`

```
Name:           ace-pup
State:          Running
IPv4:           10.62.245.15
Release:        Ubuntu 16.04.7 LTS
Image hash:     ef5bafec76cc (Ubuntu 16.04 LTS)
Load:           0.08 0.02 0.01
Disk usage:     907.8M out of 4.8G
Memory usage:   35.9M out of 992.0M
```

**Additional context**

Confusingly, I get a different error when I try to launch an instance in my app ...

e.g. 

```shell
multipass -v launch file:///mnt/data-storage/images/image-d8de17f4136245562c666c9fa6053eb36e651e0205624f184c586cda0d6b0bb8.img --name instance-36745807`

launch failed: Cannot read image format: qemu-img failed (Process returned exit code: 1) with output:
qemu-img: Could not open '/var/snap/multipass/common/data/multipassd/vault/instances/instance-36745807/image-d8de17f4136245562c666c9fa6053eb36e651e0205624f184c586cda0d6b0bb8.img': Could not open '/var/snap/multipass/common/data/multipassd/vault/instances/instance-36745807/image-d8de17f4136245562c666c9fa6053eb36e651e0205624f184c586cda0d6b0bb8.img': No such file or directory
```

In this case, a work around is to copy the image to the instance directory:

```shell
sudo cp /mnt/data-storage/images/image-d8de17f4136245562c666c9fa6053eb36e651e0205624f184c586cda0d6b0bb8.img /var/snap/multipass/common/data/multipassd/vault/instances/instance-36745807/
```

Looking at the source, I'm thinking this could be the culprit: 

https://github.com/canonical/multipass/blob/76c691b5c3415ccd2f8d533583cbcf47f46ea8f9/src/utils/vm_image_vault_utils.cpp#L31

Should this not be the absolute path instead of the base name?

https://doc.qt.io/archives/qt-4.8/qfileinfo.html#absoluteFilePath

:thinking:

**Comment by Saviq** [comment]
Hi @kmcd, the problem isn't in Qt or anywhere, it's actually in the fact that Multipass is snap-confined, and the `/tmp` it sees is not the one you're looking at.

You have to put the file somewhere under `/home` or `/mnt`, `/media`, refer to Snap documentation [on the home](https://snapcraft.io/docs/home-interface) and [the removable-media](https://snapcraft.io/docs/removable-media-interface) interfaces. Make sure those are connected with `snap connect multipass:<interface>`.

Please reopen if you still find this not enough.

**Comment by Saviq** [comment]
@kmcd I filed #1795 to remind us to improve those error messages.

**Comment by kmcd** [comment]
Thanks @Saviq !

Are you sure that the `removable-media` interface is enabled? `/mnt` isn't available ...

`error: snap "multipass" has no plug named "removable-media"`

```shell
$ snap connections multipass
Interface          Plug                         Slot                Notes
firewall-control   multipass:firewall-control   :firewall-control   -
home               multipass:all-home           :home               -
home               multipass:home               :home               -
kvm                multipass:kvm                :kvm                -
libvirt            multipass:libvirt            -                   -
lxd                multipass:lxd                -                   -
multipass-support  multipass:multipass-support  :multipass-support  -
network            multipass:network            :network            -
network-bind       multipass:network-bind       :network-bind       -
network-control    multipass:network-control    :network-control    -
unity7             multipass:unity7             :unity7             -
wayland            multipass:wayland            :wayland            -
x11                multipass:x11                :x11                -
```

**Comment by Saviq** [comment]
> Are you sure that the `removable-media` interface is enabled? `/mnt` isn't available ...

Sorry, forgot I only just [added it last week](https://github.com/canonical/multipass/commit/8d1a034839a1de79d15f27bbdb9af03838774a4f#diff-5fde7a6d86053f0e1d88c0a2a238941f), you can use the `edge` channel, or wait for our upcoming release (we're planning to release later this week).

**Comment by kmcd** [comment]
:+1:  Great stuff - thanks! I'll use the `edge` channel. 

![b251d9d05c903c3023441ee793732b67dd6647c39f7033b09769b483426e74be](https://user-images.githubusercontent.com/8568/95761652-875b2780-0ca4-11eb-9c96-378f3ce25fbb.jpg)
