### ISSUE TITLE
20.10 image available?

### ISSUE THREAD

**Issue by ubulinu** [canonical/multipass#1815]
Q: Are there only LTS versions available, or is there going to be a 20.10 image?
(VirtualBox on Win10)

**Comment by Saviq** [comment]
Hi @ubulinu, we'll be releasing Multipass 1.5.0 this week, which will include a 20.10 image. Stay tuned!

**Comment by Saviq** [comment]
@ubulinu if you want to try, we've Release Candidate up: https://github.com/canonical/multipass/pull/1813#issuecomment-717600227

**Comment by Saviq** [comment]
This is now released.
