### ISSUE TITLE
launch failed: Could not generate a new UUID

### ISSUE THREAD

**Issue by tengqian** [canonical/multipass#1816]
**Describe the bug**
I Use VirtualBox model.
launch failed: Could not generate a new UUID: Process failed to start: 系统找不到指定的文件。

**To Reproduce**
Execute `shell multipass launch ` after installation.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
![image](https://user-images.githubusercontent.com/25736019/97381199-8ad8ea80-1903-11eb-99c4-8b18dc11c72c.png)

**Additional info**
 - OS: window 10 Home (2004)
 - 
![image](https://user-images.githubusercontent.com/25736019/97381444-0f2b6d80-1904-11eb-8c98-48b8ee17d89c.png)

**Comment by tengqian** [comment]
![image](https://user-images.githubusercontent.com/25736019/97381548-47cb4700-1904-11eb-832c-0c483066651f.png)

**Comment by Saviq** [comment]
Hi @tengqian, where is your VirtualBox installation? When you're in an admin's PowerShell, can you execute `VBoxManage` OK? If not, please try adding your installation path to the system PATH variable.

**Comment by tengqian** [comment]
Thanks for your help.The System PATH Variable already exists. So it's not what you said
![image](https://user-images.githubusercontent.com/25736019/97519104-9c89c300-19d3-11eb-808e-d2c47bbcf5b9.png)
![image](https://user-images.githubusercontent.com/25736019/97518783-e7570b00-19d2-11eb-86c0-42a3849618a2.png)

**Comment by Saviq** [comment]
Hi @tengqian, that doesn't confirm that's in the _system_ `PATH` (as opposed to the user one). Can you please run `multipass launch -vvvv` to get a bit more detail?

According to Google Translate, the error is "The system can not find the file specified", so it suggests Multipass can't find the VBoxManage executable.

**Comment by tengqian** [comment]
Hi @Saviq ,When I run `multipass launch -vvvv`,  The multipass is working.Thanks for your help.
![image](https://user-images.githubusercontent.com/25736019/97649054-4ed39000-1a91-11eb-980b-0631c80088ab.png)
![image](https://user-images.githubusercontent.com/25736019/97649064-53984400-1a91-11eb-8e59-78e2307e8533.png)

**Comment by Saviq** [comment]
Oh? And if you launch without `-vvvv` now? Any chance you rebooted in the mean time and the PATH variable got applied?

**Comment by tengqian** [comment]
No need `-vvvv`,It's running.  I Added `VirtualBox installation ` to `USER PATH` and `SYSTEM PATH` then reboot compute and run `multipass launch -vvvv` .
![image](https://user-images.githubusercontent.com/25736019/97670711-ca4d3580-1ac1-11eb-8fd1-4e3e34a98067.png)

**Comment by tengqian** [comment]
Thanks again! @Saviq

**Comment by jiangwh** [comment]
I got the same problem,and can't slove it!
![Uploading image.png…]()

**Comment by Saviq** [comment]
Hi @jiangwh, where is your VirtualBox installed? Is it on your _system_ path?

**Comment by Darrenchenn** [comment]
Hi， @Saviq I got the same issue when i try to run the primary instance.Here is the info when i run "multipass launch -vvv"
![image](https://user-images.githubusercontent.com/50362974/210296203-8a7ba8aa-0a43-46d0-8613-b0874ad6aa9a.png)
Can't solve it,looking forward for u reply,thx!

**Comment by tengqian** [comment]
> Hi， @Saviq I got the same issue when i try to run the primary instance.Here is the info when i run "multipass launch -vvv" ![image](https://user-images.githubusercontent.com/50362974/210296203-8a7ba8aa-0a43-46d0-8613-b0874ad6aa9a.png) Can't solve it,looking forward for u reply,thx!

@Darrenchenn `win+R` input `SystemPropertiesAdvanced`；Configure `user variables` and `system variables` in environment variables. This is how I solved it
检查下你的环境变量。我是在系统变量和用户变量都加入`VirtualBox`和`multipass`之后成功的。

**Comment by Darrenchenn** [comment]
> 

![image](https://user-images.githubusercontent.com/50362974/210297469-311fb373-5c14-4dbd-b856-34f78ef4987b.png)
![image](https://user-images.githubusercontent.com/50362974/210297476-2590317a-5703-438b-8600-727a1d3f96aa.png)
It's already set, still cannot solve run it.

**Comment by xiewensheng** [comment]
@Darrenchenn ,I hope this article can help you.
 https://forums.virtualbox.org/viewtopic.php?f=25&t=97412

**Comment by Darrenchenn** [comment]
> 

Thank for ur advice! I've tried to modify the local setting to virtualbox,it showed the different error. I have not try your method,but i think what i did is the same to the method? Do your konw why the new error happened? Thx again.
![image](https://user-images.githubusercontent.com/50362974/210324673-dd7fb0b1-e385-4d7e-b022-dc1c993e4a02.png)
@xiewensheng

**Comment by xiewensheng** [comment]
@Darrenchenn ,You can restart your computer. Hyper-V and virtualbox are conflicting. You need to close your computer's Hyper-V

**Comment by Darrenchenn** [comment]
> @Darrenchenn ,You can restart your computer. Hyper-V and virtualbox are conflicting. You need to close your computer's Hyper-V

Actually,there is no hyper-v service is running, i still cannot figure it out.

**Comment by NanoNM** [comment]
I have same problem .I add all to system path and user path not work then i reinstall multipass and new problem come out sad.
![image](https://user-images.githubusercontent.com/42882446/229316218-bfd75eaa-a482-43ea-aa7f-e92200b870c0.png)
Previously, I used HyperV everything is ok.
