### ISSUE TITLE
DNS configuration in Multipass instances

### ISSUE THREAD

**Issue by nmofonseca** [canonical/multipass#1822]
# Configure DNS in multipass instances
Since I am runing on a enterprise network and behind both a proxy and vpn I need to be able to setup my DNS properly.

Being able to change this config using --cloud-init  option which doesn't seem to work.

In [issue 933](https://github.com/canonical/multipass/issues/933) it is mentioned that --cloud-init should be used but no direction was given on how to do it or could this be found in multipass documentation.

**Comment by cedric-lamalle** [comment]
This is a little hackish, but works with Ubuntu:

Create a cloud-init file `resolv-conf.yaml`
```
#cloud-config
bootcmd:
    - printf "[Resolve]\nDNS=8.8.8.8" > /etc/systemd/resolved.conf
    - [systemctl, restart, systemd-resolved]
```

Launch the vm:
```
multipass launch -n node1 --cloud-init resolv-conf.yaml
```

Now DNS works in the VM:
```
multipass shell node1
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-53-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Nov 18 00:09:32 -03 2020

  System load:  0.76              Processes:               124
  Usage of /:   26.5% of 4.67GB   Users logged in:         0
  Memory usage: 20%               IPv4 address for enp0s2: 192.168.64.77
  Swap usage:   0%


1 update can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable


To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@node1:~$ ping www.google.com
PING www.google.com (172.217.30.4) 56(84) bytes of data.
64 bytes from rio01s23-in-f4.1e100.net (172.217.30.4): icmp_seq=1 ttl=113 time=29.0 ms
64 bytes from rio01s23-in-f4.1e100.net (172.217.30.4): icmp_seq=2 ttl=113 time=32.9 ms
64 bytes from rio01s23-in-f4.1e100.net (172.217.30.4): icmp_seq=3 ttl=113 time=35.1 ms
^C
--- www.google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 28.999/32.330/35.116/2.526 ms
```

**Comment by Saviq** [comment]
@nmofonseca I now added a section in our docs on this: [Using a custom DNS](https://multipass.run/docs/using-a-custom-dns).

Thanks @cedric-lamalle! I had a look whether the [write-files module](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#write-files) could make it less _hacky_, but it seems to run too early and gets overwritten, as far I can tell. I have included your approach in the above documentation.

**Comment by nmofonseca** [comment]
Hello @Saviq , thank you so much for that,
