### ISSUE TITLE
Timeout on fresh install of multiples

### ISSUE THREAD

**Issue by trevorhardy** [canonical/multipass#1826]
**Describe the bug**
`multipass shell` times-out on a newly created (and never successfully launched) instances (both primary and my new instance `tesp`).

**To Reproduce**
How, and what happened?
1. `multipass shell` or `multiples shell tesp`

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/5478513/multipassd.log)
[primary-hyperkit.log](https://github.com/canonical/multipass/files/5478514/primary-hyperkit.log)
[tesp-hyperkit.log](https://github.com/canonical/multipass/files/5478515/tesp-hyperkit.log)

**Additional info**
 - OS: 10.14.6
- `multipass version` = 1.5.0+mac
- `multipass info --all`
```
Name:           primary
State:          Unknown
IPv4:           --
Release:        --
Image hash:     1a03f686493f (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           tesp
State:          Unknown
IPv4:           --
Release:        --
Image hash:     1a03f686493f (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
```

**Additional context**
Fresh install of `multipass`, launching and using it for the very first time.

**Comment by Saviq** [comment]
Hi @trevorhardy do you have a VPN enabled? Or some firewall software (Little Snitch is known to block Multipass)?

Have a look at our [guide on network issues on macOS](https://multipass.run/docs/troubleshooting-networking-on-macos) to see if it helps.

**Comment by trevorhardy** [comment]
Yes, I was using Cisco AnyConnect to connect to my company's network. Retesting with the VPN disconnect, `multipass launch` reports no errors but `multipass shell` still fails with the same error (`primary: timed out waiting for response`). Is this expected even when disconnected from the VPN?

**Comment by trevorhardy** [comment]
I've been working with the IT folks here and though we haven't found a smoking gun, one of them was able to successfully get the software working on his machine. One difference we found was that his home network hands out 192.168.x.x addresses while mine uses 10.0.x.x. 

I manually set my local machine IP to 192.169.0.1 (without changing the rest of my home network, putting my computer in a separate subnet and effectively loosing all access to the rest of the home network) but that `multipass shell` still timed-out.

**Comment by trevorhardy** [comment]
Any input?

**Comment by Saviq** [comment]
Hi @trevorhardy, your home network should not have any bearing on things.

If you look at the instance logs (see [our docs on Accessing logs](https://multipass.run/docs/accessing-logs)), do you see it boot fine? Do you see it list an IP? Can you reach that IP via `ping` at all?

Apple's `bootpd` gives out IPs in the 192.168.64.0/24 subnet.

Can you confirm again that `launch` works fine, but `shell`, not? That would suggest somehow `multipassd`, the service managing the VMs, can access it, but your user, not so.

**Comment by trevorhardy** [comment]
I'm seeing the following in the log file for the instance making me think it is getting an IP:
```
[   23.009085] cloud-init[555]: ci-info: +++++++++++++++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++++++++++++++
[   23.013074] cloud-init[555]: ci-info: +--------+------+------------------------------+---------------+--------+-------------------+
[   23.014493] cloud-init[555]: ci-info: | Device |  Up  |           Address            |      Mask     | Scope  |     Hw-Address    |
[   23.017342] cloud-init[555]: ci-info: +--------+------+------------------------------+---------------+--------+-------------------+
[   23.018914] cloud-init[555]: ci-info: | enp0s2 | True |         192.168.64.7         | 255.255.255.0 | global | 36:cc:36:86:56:f6 |
[   23.020499] cloud-init[555]: ci-info: | enp0s2 | True | fe80::34cc:36ff:fe86:56f6/64 |       .       |  link  | 36:cc:36:86:56:f6 |
[   23.021988] cloud-init[555]: ci-info: |   lo   | True |          127.0.0.1           |   255.0.0.0   |  host  |         .         |
[   23.023374] cloud-init[555]: ci-info: |   lo   | True |           ::1/128            |       .       |  host  |         .         |
[   23.024914] cloud-init[555]: ci-info: +--------+------+------------------------------+---------------+--------+-------------------+
[   23.026347] cloud-init[555]: ci-info: +++++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++++
[   23.027734] cloud-init[555]: ci-info: +-------+--------------+--------------+-----------------+-----------+-------+
[   23.029317] cloud-init[555]: ci-info: | Route | Destination  |   Gateway    |     Genmask     | Interface | Flags |
[   23.030708] cloud-init[555]: ci-info: +-------+--------------+--------------+-----------------+-----------+-------+
[   23.032038] cloud-init[555]: ci-info: |   0   |   0.0.0.0    | 192.168.64.1 |     0.0.0.0     |   enp0s2  |   UG  |
[   23.033709] cloud-init[555]: ci-info: |   1   | 192.168.64.0 |   0.0.0.0    |  255.255.255.0  |   enp0s2  |   U   |
[   23.035157] cloud-init[555]: ci-info: |   2   | 192.168.64.1 |   0.0.0.0    | 255.255.255.255 |   enp0s2  |   UH  |
[   23.036721] cloud-init[555]: ci-info: +-------+--------------+--------------+-----------------+-----------+-------+
```

`multipass shell tesp` still failed (`tesp: timed out waiting for response`)

`multipass launch` failed as well:
```
launch failed: The following errors occurred:                                   
acceptable-canvasback: timed out waiting for response 
```

**Comment by townsend2010** [comment]
Hi @trevorhardy,

Yes, indeed it looks like the instance is getting an IP address.  This leads me to believe that *something* on your host is blocking access to that subnet.  Outside of Multipass, are you able to ping `192.168.64.7` when the instance is, in theory, up and running?  

Given both that the client and service cannot reach the IP/subnet, it really leads to believe there is some firewall/VPN rule in place either blocking **all** access to the subnet or blocks access to non-whitelisted process such as `multipass` and `multipassd`.

**Comment by trevorhardy** [comment]
How do I know when the instance is up and running? As far as I can tell I've never reached a state where that was the case.

**Comment by townsend2010** [comment]
That cloud-init output indicates that it is running.  The reason Multipass is not able to tell is that it relies on a `ssh` connection to be available and since it cannot reach the instance on the `bootp` network, it can't figure out what the state is.

**Comment by trevorhardy** [comment]
OK.

I started `multipass shell` and then immediately in another shell started pinging `192.168.64.7`; multipass failed and I never saw anything from ping but  `Request timeout for icmp_seq xxx`.

**Comment by townsend2010** [comment]
Ok, just to make sure, you confirmed in the logs like you posted above that the instance you just started did indeed get an IP address and it is `192.168.64.7`?

**Comment by trevorhardy** [comment]
Ahh, good catch. `primary` was assigned `192.168.64.9`; I pinged that just now and it timed out.

And to be super-sure, I redid the test watching the log file to see which IP it got assigned. As soon as I saw the IP, I started pinging it and it timed out as before.

**Comment by townsend2010** [comment]
Ok, then it's pretty much confirmed something, maybe Cisco AnyConnect (even when disconnected), has blocked access from your host (even outside of Multipass) to the `bridge100`/`bootp` network.  Unfortunately, aside from what's in our macOS network troubleshooting guide, we don't have anymore experience with what is happening.  If you do figure out what is going on, please let us know and we can incorporate it in our guide.

**Comment by trevorhardy** [comment]
Working with my IT team here, we found that force quitting `multipassd` (which automatically restarts itself) with Cisco AnyConnect not running (that is, after quitting it), allowed me to get a prompt when running `multipass shell`. If/when it breaks again, I'll try more testing to see if quitting AnyConnect is necessary or if this was just a coincidence.

Thanks for your helping it narrowing down the problem.
