### ISSUE TITLE
Toolbar icon malformed - OSX 11.0.1

### ISSUE THREAD

**Issue by Hermanverschooten** [canonical/multipass#1837]
**Describe the bug**
I have multiple monitors, the toolbar icon for Mutlipass is squashed on the inactive monitors.
When screen is active:
<img width="54" alt="Schermafbeelding 2020-11-13 om 10 52 48" src="https://user-images.githubusercontent.com/91784/99059147-71d86680-259e-11eb-9d69-18c831e2f1df.png">
When screen is inactive:
<img width="41" alt="Schermafbeelding 2020-11-13 om 10 53 08" src="https://user-images.githubusercontent.com/91784/99059153-74d35700-259e-11eb-832e-9ec435b85e7e.png">

**To Reproduce**
Click on any app on the second monitor

**Expected behavior**
The icon should be dimmed.

**Additional info**
 - OS: macOS 11.0.1
- `multipass version` 1.5.0+mac

**Comment by townsend2010** [comment]
We have moved away from Qt w/ a new GUI written in Flutter.  This has been merged in our mainline code and will be available in our upcoming 1.14 release.  I'm going to go ahead and close this as complete, but if the new Flutter based icon displays the same behavior, then either please reopen this issue or open a new issue.  Thanks!
