### ISSUE TITLE
multipass socket should be `sudo` owned

### ISSUE THREAD

**Issue by MariusQuabeck** [canonical/multipass#184]
Hey,
I'm aware that you have to install `slang` on Solus [1] to get the snap to work and I did that.
Still, I have issues starting the snap:
`marius@Lenovo-Carbon-X1-3rd ~ $ multipass launch
failed to launch: Connect Failed`

running
`sudo snap run multipass launch` and every other multipass command works tho if you start it with `sudo snap run multipass X`

this wasn't needed on Solus the last time I've tried it, a few weeks ago.
Might be PATH related.

This is on Solus 3, running multipass  2018.2.1 from the beta channel, same happens on edge

Cheers
Marius

[1] https://community.ubuntu.com/t/beta-release-multipass/2696/12

**Comment by Saviq** [comment]
What does `systemctl status snap.multipass.multipassd.service` say?

**Comment by MariusQuabeck** [comment]
@Saviq 
`marius@Lenovo-Carbon-X1-3rd ~ $ systemctl status snap.multipass.multipassd.service 
● snap.multipass.multipassd.service - Service for snap application multipass.multipassd
   Loaded: loaded (/etc/systemd/system/snap.multipass.multipassd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-03-21 09:02:56 CET; 1h 17min ago
 Main PID: 782 (multipassd)
    Tasks: 9 (limit: 4915)
   CGroup: /system.slice/snap.multipass.multipassd.service
           ├─ 782 /snap/multipass/170/bin/multipassd
           └─1392 dnsmasq --keep-in-foreground --strict-order --bind-interfaces --except-interface=lo --interface=mpbr0 --listen-address=10.195.0.1 --dhcp-no-override --dhcp-autho>

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
`

**Comment by Saviq** [comment]
Can you see if `/run/multipass_socket` exists? And what are its permissions?

We've switched to a file socket for security reasons:
```
$ ls -la /run/multipass_socket
srw-rw---- 1 root adm 0 mar 20 21:50 /run/multipass_socket
```

Does Solus have the "adm" group? Are you in it?

**Comment by MariusQuabeck** [comment]
`marius@Lenovo-Carbon-X1-3rd ~ $ ls -la /run/multipass_socket
srw-rw---- 1 root adm 0 21. Mär 09:03 /run/multipass_socket`
`
marius@Lenovo-Carbon-X1-3rd ~ $ groups
marius dialout audio video cdrom lpadmin sudo scanner plugdev users lxd fuse
`
so my user is not in "adm"

**Comment by ikeydoherty** [comment]
@Saviq there is no purpose for `adm` group within Solus. Administrative users are only in the `sudo` group which takes the place of `wheel`. I'm surprised the socket would be owned by `adm` and not something more in keeping with tradition. This also exposes the fatal flaw of classic snaps, that they can never be portable. I'd really rather not introduce `adm` into Solus, but if I'm left with no choice I will. However I would much rather the architectural decisions of the Debian & Ubuntu world do not impact that of Solus.

Is there a reason this needs to be classic? So we can get past the issue.

**Comment by Saviq** [comment]
@ikeydoherty `adm` wasn't a great choice indeed, we'll move it under `sudo` ASAP. We will also go strictly confined soon, but we need a bit of work in snapd for that. And even more than that, we're working on an authentication / encryption mechanism so we can expose Multipass on the network socket.
