### ISSUE TITLE
Invalid digital signature for latest windows release (1.5.0)

### ISSUE THREAD

**Issue by jdossett** [canonical/multipass#1850]
**Describe the bug**
The latest windows release (1.5.0) has an invalid digital signature

**To Reproduce**
How, and what happened?
1. The digital signature for the file shows as invalid.  The certificate used to sign the latest release expired on 10/15/2020 and the latest release was signed on 10/30/2020, resulting in an invalid digital signature.

**Comment by Saviq** [comment]
Hi @jdossett, weird that we didn't get that notice neither when signing or when installing (must be because we accepted the certificate before already).

Thanks for letting us know!

**Comment by Saviq** [comment]
This is fixed, the artifact on the release has been updated.

**Comment by jdossett** [comment]
👍 Thanks so much @Saviq
