### ISSUE TITLE
launch failed: failed to download from . . . Network timeout

### ISSUE THREAD

**Issue by balibebas** [canonical/multipass#1856]
**Describe the bug**
Launch command is unforgiving for low network connections. The Wi-Fi in my area has been up and down all day. I've had image downloads get to 12% and die only to have to start over when the connection is still alive—just going slow.

**To Reproduce**
How, and what happened?
1. Hop on a slow network
1. `multipass launch`
1. Watch download start.
1. Wait for below error

```
error pulling image configuration: Get https://registry-1.docker.io/v2/archlinux/base/blo
bs/sha256:a79c9d41e4acae48b507e191b1df318efafae0b670be78382f35e2e4fc62e742: net/http: TLS
 handshake timeout
```

**Expected behavior**
CLI doesn't give up on slow network connections. If it does, downloads resume where they left off or alternative methods for getting the images (P2P for example) are made available to help remove bottlenecks.

**Logs**
n/a

**Additional info**
 - OS: Darwin 20.2.0
- `multipass version` 1.5.0+mac
- `multipass info --all` ` ` (literally empty)

**Additional context**
I've used similar tools like Archuro (for Arch Linux boxes) and that tool relies on Docker to get the image files and it doesn't give up on a download just because the connection is poor.

**Comment by Saviq** [comment]
Hi @balibebas can you comment on what exactly timed out? The error you pointed out doesn't look like it's coming from Multipass…

**Comment by balibebas** [comment]
The issue is that multipass launch doesn't complete and throws an error on slow internet connections. It failed at the progress indicator `/ — \ | / — \ |`. There was no other debugging information provided when multipass failed. That's all I got. The ask here is to fail more gracefully when the internet connection is slow.

**Comment by balibebas** [comment]
I'm wrapping up shop on helping improve this repo. Good luck.
