### ISSUE TITLE
Improved instructions for macOS installation

### ISSUE THREAD

**Issue by ghost** [canonical/multipass#1858]
**What are you trying to do?**
Run multipass using the instructions provided on https://multipass.run/docs/installing-on-macos.

Instructions make it look like you'll automatically be using `hyperkit` but do not instruct users to `get` the `local.driver` to verify first. These instructions should be updated to have users check their driver first and switch to hyperkit if desired:

```shell
sudo multipass get local.driver # this may return `virtualbox`
sudo multipass set local.driver=hyperkit
```

Otherwise users may start encountering VBox issues like:

```shell
Kernel Driver Not Installed (rc=-1908)” Error on a Mac
```

Which are completely unrelated and have nothing to do with `hyperkit`. (Info to fix that here: https://www.howtogeek.com/658047/how-to-fix-virtualboxs-%E2%80%9Ckernel-driver-not-installed-rc-1908-error/)

**What's your proposed solution?**

When they were expecting `hyperkit` to be the default driver (but it's not). So at a minimum it's useful you update the instructions to provide the info UP FRONT for getting and setting the `hyperkit` driver.

**Additional context**

None

**Comment by ricab** [comment]
Hi @balibebas, I am not sure I understand what you mean. The default driver *is* hyperkit. There is no way it would be set to virtualbox without the user requesting that. Did you perhaps do that in an earlier install? Or copy-pasted a command by mistake perhaps?

Note: we used to support `MULTIPASS_VM_DRIVER` env var, but that is now ignored and a warning is issued if it's set.

**Comment by balibebas** [comment]
Today after I set up the driver did indeed change to VBox through no work off my own. Hence the issue. This occurred on the Big Sur Beta (latest version) without running any `set` command on the driver.

What I can tell you is that the driver didn't change itself until after my first successful launch and that it did happen unattended.

**Comment by balibebas** [comment]
It could be the presence of `kind` had something to do with the wonk. Regardless, I still feel the docs should be more explicit.

**Comment by ricab** [comment]
The first (non-title) sentence in the docs you linked says:

> The default backend on macOS is hyperkit

What could be more explicit there? That default is hardcoded and it's not clear to me what enhancement you are proposing.

**Comment by balibebas** [comment]
When the pull quotes come out on such trivial feedback I will do you a favor and bail. You've heard the feedback. Do with it what you will.
