### ISSUE TITLE
failed to auto mount?

### ISSUE THREAD

**Issue by winkee01** [canonical/multipass#1867]
I mount a local dir `/tmp/config` to multipass's instance. But when I stop the instance and restart it, the mount disconnected, when I try to re-mount it, it will pop out the error message saying:

```
mount failed: The following errors occurred:
"primary:/tmp/config" is already mounted"
```

to solve this, I just have to execute `multipass unmount primary`.

I was wandering is there a better way to overcome this error? either auto unmount when I stop the instance, or auto re-mount when I restart the instance.

**Comment by Saviq** [comment]
Hi @winkee01, could you please give a bit more context about your host operating system and Multipass version?

What you're describing sounds like a bug indeed, with the exception that `/tmp` on Linux (under snap confinement) is special - the snap doesn't see the same `/tmp` that you do.

**Comment by townsend2010** [comment]
Hi @winkee01,

By default, it should auto re-mount on instance start.  How are you restarting the instance?  And when the instance has been restarted, when you view the mounted directory from within the instance, there is nothing in the mounted directory until you do the `unmount`/`mount` dance?

**Comment by winkee01** [comment]
> Hi @winkee01,
> 
> By default, it should be auto re-mount on instance start. How are you restarting the instance? And when the instance has been restarted, when you view the mounted directory from within the instance, there is nothing in the mounted directory until you do the `unmount`/`mount` dance?

Hi, I type `multipass stop primary` and  `multipass start primary` to restart the stopped instance.
After I restarted and shell into the instance, the mount directory is still there. So I have to manually unmount it first before I can mount it again.

**Comment by townsend2010** [comment]
Hi @winkee01,

Ok, thanks.

> After I restarted and shell into the instance, the mount directory is still there.

Does it contain the data in it you expect or is it empty and only unmounting and mounting shows the data you expect?

**Comment by winkee01** [comment]
yes, it preserves files.

**Comment by townsend2010** [comment]
Ok, then it is working as expected and there is no need to manually unmount and mount this unless I'm really misunderstanding your use case.

**Comment by winkee01** [comment]
> Ok, then it is working as expected and there is no need to manually unmount and mount this unless I'm really misunderstanding your use case.

Well! Interesting, everything suddenly works now!

Initially, this may turn out to be a bug from `podman` I guess. because I use the instance as a podman server. when I start the instance, and I use podman to restart a container in the instance, the container will ready some data from the mounted directory. But it failed after I restart the instance and then restart the container. But now it seems to work correctly.

**Comment by winkee01** [comment]
> Ah, ok, on instance start up, there could be a race between Multipass mounting the directory and podman starting and needing that directory available. I'm going to close this bug, but feel free to reopen if you believe Multipass is at fault.

You are exactly true, there must be a race because I have tried again many times, and the errors are gone. Many thanks!
