### ISSUE TITLE
Disk Size flag is being ignored in Windows 10

### ISSUE THREAD

**Issue by danmac** [canonical/multipass#1870]
I have multipass 1.5.0 installed on Windows 10. I have installed both from releases and using winget and it seems to affect both versions. 

Whenever I try to launch a new VM with the -d flag it gets ignored and all VMs only have 2G of space. All other flags work fine (eg -c and -m). 

I originally installed it over 1.4.0 and let it auto uninstall the previous version. 

Here is an example shell:

```
PS C:\Users\danma> multipass launch -d 8G
Launched: ardent-plover
PS C:\Users\danma> multipass info ardent-plover
Name:           ardent-plover
State:          Running
IPv4:           172.18.22.9
Release:        Ubuntu 20.04.1 LTS
Image hash:     6efe465cfbc0 (Ubuntu 20.04 LTS)
Load:           0.95 0.29 0.10
Disk usage:     **1.2G out of 2.0G**
Memory usage:   159.2M out of 916.9M
```

**Comment by Saviq** [comment]
Hi @danmac can you please confirm whether you're using Hyper-V or VirtualBox? And in [the logs](https://multipass.run/docs/accessing-logs#windows), do you see any relevant info?

**Comment by danmac** [comment]
Using Hyper-V. 

I am also using PowerShell 7.1.0 from within Windows Terminal, but I tried it with classic PowerShell and it did the same thing.

I checked event viewer and saw this line: 
``
Log Name:      Application
Source:        Multipass
Date:          4/12/2020 8:25:43 PM
Event ID:      1
Task Category: None
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      dexpwin
Description:
[shrewd-prawn] Cmdlet failed with program: powershell.exe; error: Process operation timed out: Resize-VHD -Path C:/Windows/system32/config/systemprofile/AppData/Roaming/multipassd/vault/instances/shrewd-prawn/ubuntu-20.04-server-cloudimg-amd64.vhdx -SizeBytes 8589934592

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Multipass" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-12-04T09:55:43.0331826Z" />
    <EventRecordID>19954255</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>dexpwin</Computer>
    <Security />
  </System>
  <EventData>
    <Data>[shrewd-prawn] Cmdlet failed with program: powershell.exe; error: Process operation timed out: Resize-VHD -Path C:/Windows/system32/config/systemprofile/AppData/Roaming/multipassd/vault/instances/shrewd-prawn/ubuntu-20.04-server-cloudimg-amd64.vhdx -SizeBytes 8589934592
</Data>
  </EventData>
</Event>``

**Comment by danmac** [comment]
I just reverted to 1.4.0 and it seems to be doing it as well. 

I've only just switched to Hyper-V from using VirtualBox if that's of any use. I also turned on WSL2 and have Docker installed, which is why I switched.
