### ISSUE TITLE
Multipass for windows: timed out waiting for response

### ISSUE THREAD

**Issue by heagan01** [canonical/multipass#1872]
**Describe the bug**
I can't seem to set up a VM of every ubuntu version, but I can launch the appliances in windows.

**To Reproduce**
How, and what happened?
1. `multipass launch -n my-test-vm --cloud-init cloud-init.yaml`

**Expected behavior**
What did you expect to happen?

**Logs**
[asdf.zip](https://github.com/canonical/multipass/files/5646589/asdf.zip)

**Additional info**
 - OS: Windows 20H0
- multipass  1.5.0+win, multipassd 1.5.0+win
- Name:           my-test-vm                                                                                              
State:          Stopped                                                                                                 
IPv4:           --                                                                                                      
Release:        --                                                                                                      
Image hash:     6efe465cfbc0 (Ubuntu 20.04 LTS)                                                                         
Load:           --                                                                                                      
Disk usage:     --                                                                                                      
Memory usage:   --  

**Additional context**
I used multipass launch -n my-test-vm --cloud-init cloud-init.yaml, and then multipass start my-test-vm.

**Comment by Saviq** [comment]
Hi @heagan01, can you post your `cloud-init.yaml`?

That some instances launch fine, but others don't, suggests there may be something in there.

Did you try launching without `--cloud-init`?

**Comment by heagan01** [comment]
Yes, I launched it with --cloud-init this is my cloud-init.yaml

[cloud-init.zip](https://github.com/canonical/multipass/files/5652180/cloud-init.zip)

**Comment by Saviq** [comment]
OK yes, your `cloud-init.yaml` is what's causing normal Ubuntu instances to fail. Appliances / Ubuntu Core instances launch fine because they treat users/groups slightly differently.

Just remove this part of your YAML, and you should be good. I just launched an instance with the rest of your YAML fine.
```yaml
groups:
  - ubuntu: [root,sys]
  - cloud-users
```

Please reopen if you find that not working still!

**Comment by Saviq** [comment]
@heagan01 FWIW this is the `cloud-init` bug that's the direct cause of your problems:

https://bugs.launchpad.net/cloud-init/+bug/1870310

**Comment by heagan01** [comment]
can't seem to start still this is my cloud-init.yaml
[cloud-init.zip](https://github.com/canonical/multipass/files/5656221/cloud-init.zip)

**Comment by Saviq** [comment]
@heagan01 you didn't say if it works _without_ the cloud init file altogether?

**Comment by heagan01** [comment]
I mean i got the same problem tried multipass start my-test-vm and created a new vm altogether multipass launch my-asdf --cloud-init cloud-init.yaml

**Comment by Saviq** [comment]
Yes, but did you try *without* the `cloud-init.yaml`? Just `multipass launch -n my-asdf`? Does that work?

**Comment by heagan01** [comment]
Nope, still the same thing

**Comment by ricab** [comment]
Hi @heagan01 , does it work if you do not specify a name (just `multipass launch`)?

Windows sometimes [keeps stale IPs](https://multipass.run/docs/troubleshooting-networking-on-windows) in `C:\WINDOWS\System32\drivers\etc\hosts.ics`.

**Comment by heagan01** [comment]
It's the same, i tried multipass launch

**Comment by Saviq** [comment]
Hi @heagan01, sorry this isn't working for you. Can you confirm that appliances still launch fine?

In your logs, I can see the image resize operation timing out. What hardware are you running on? This operation should be near instant, but in your case it seems to time out after 30s...

**Comment by heagan01** [comment]
Hi @Saviq I tried multipass launch appliance:nextcloud, but it doesn't work now it says timed out waiting for responses, the hardware I'm running on is the asus n43sl laptop, I used the i5-2430m processor, for the log this is the file
[multipass launch -vvvv.txt](https://github.com/canonical/multipass/files/5759806/multipass.launch.-vvvv.txt)

**Comment by Saviq** [comment]
Hi @heagan01, In Hyper-V manager, do you see the instance at all? It should be named "pro-kookaburra". From the logs you sent it's as if it's actually getting stuck way before creating the instance…

**Comment by heagan01** [comment]
What is the Hyper-V manager? Is that the logo of multipass on the taskbar?

**Comment by Saviq** [comment]
No, it's a Windows program, the main GUI for the [Hyper-V hypervisor](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) included in Windows 10. Multipass uses that technology behind the scenes.

**Comment by heagan01** [comment]
Hmm weird, i've formatted my hard drive, and fresh install windows, it works now

**Comment by Saviq** [comment]
Oh wow, that's a drastic solution if I know one… But glad it helped.
