### ISSUE TITLE
Stuck with unresponsive VM if halted

### ISSUE THREAD

**Issue by KHIT93** [canonical/multipass#1887]
**Describe the bug**
Unable to interact with a VM is `sudo systemctl restart poweroff.target` is executed by mistake

**To Reproduce**
Create a VM, or use an existing one.
Then execute `sudo systemctl restart poweroff.target`
The connection to the VM is now dropped and stop, suspend, restart, shell actions are no longer working. The only fix currently seems to be deleting, and purging, the VM and starting over.

**Expected behavior**
In such case, I would expect that if a graceful shutdown, using SSH, does not work, the VM is shutdown by force (like unplugging the power if it was a physical machine)

**Additional info**
 - OS: Pop_OS 20.10 64-bit as well as Ubuntu 20.10 64-bit
- `multipass version`
multipass  1.5.0
multipassd 1.5.0

- `multipass info --all`
Name:           careful-wagtail
State:          Running
IPv4:           10.51.21.152
Release:        Ubuntu 20.04.1 LTS
Image hash:     36403f956294 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.2G out of 19.2G
Memory usage:   161.8M out of 3.8G

Name:           direct-humpback
State:          Stopped
IPv4:           --
Release:        --
Image hash:     f136639410c3 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

The VM that had the issue has now been deleted, but I thought that it would be a good idea to mention this

**Comment by Saviq** [comment]
Thanks, indeed we should maybe have a `--force` option to `multipass stop` and `multipass restart`, which would not require the VM to be in a good state.
