### ISSUE TITLE
purge should be able to specify instance

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#189]
Maybe I miss something. If I delete an instance, I want it deleted, why should I run purge?
If the intention is to have safeguards, then purge should be able to specify --all or --name <x>
Reason - If I want to recreate an instance, I delete and launch, but launch complains that instance already exists, I have to purge. But purge will purge all deleted instances. Does not make sense.
(I would say, remove purge concept, what is deleted is gone immediately)

**Comment by Saviq** [comment]
Think of "deleted" instances as ones put in trash, you can purge trash as a whole. If you want to purge a single instance, you can `multipass delete --purge` it.

That said, I suppose we can add an optional `name` argument to purge, and we should improve the user experience when trying o "replace" a deleted instance.

**Comment by andrei-toterman** [comment]
`delete --purge <instance-name>` also works on already deleted instances, so it can cover the same use-case as `purge <instance-name>`
