### ISSUE TITLE
[FEATURE] Choose disk location and change size of instance + cache apt/apt-get + change method install multipass on ubuntu

### ISSUE THREAD

**Issue by letanloc1998** [canonical/multipass#1898]
**What are you trying to do?**
Does you add feature
    + Select where disk location to save my instance
    + Change size disk/ram/cpu of instance. I can't change it after create instance => delete if limit ~~
    + Change method install on ubuntu because some reason I can't install via snapd (does any way manual install via source code, apt/apt-get?)
**What's your proposed solution?**

**Additional context**

**Comment by letanloc1998** [comment]
It's very good if have dynamic ram/disk/cpu
And could you support cache when apt/apt-get install

**Comment by ricab** [comment]
Hi @letanloc1998,

You can use the environment variable `MULTIPASS_STORAGE` to change where Multipass stores things. Instructions for the different platforms in [this comment](https://github.com/canonical/multipass/pull/1789#issuecomment-704991752) and the two below.

There are already long-standing plans (#756) to support changing instance properties like disk/ram/cpus. In the meantime, there are workarounds you can use (see for example #1158).

As for different means of installing, I don't think that's something we'd want to do. You can of course compile from source if you are on Linux. But is there anything we can help with to install the snap? The [docs](https://multipass.run/docs/installing-on-linux) may be helpful.

**Comment by letanloc1998** [comment]
Thank you
