### ISSUE TITLE
state unknown, after restart of the vm with sudo shutdown -r

### ISSUE THREAD

**Issue by usovitsj** [canonical/multipass#1907]
**Describe the bug**
I am not able to start the instance anymore. The state gives unknown after the command:
multipass start vm1 
start failed: The following errors occurred:                                    
vm1: timed out waiting for response

multipass list
Name                    State             IPv4             Image
vm1                 Unknown           --               Ubuntu 18.04 LTS

I am still able to create new instances and these work fine. But I would like very much be able to access the data stored on vm1. And I would love to avoid this error a second time.

**To Reproduce**
I entered the instance with:
multipass shell vm1
Up to now everything was fine. The system reminded me to restart the virtual machine, because new updates should take place. I used the command 
sudo shutdown -r
which would usually restart without any problems.

**Expected behavior**
I did not experience any problems up to this point. It seems like some updates in the virtual machine did not go well.

**Logs**
I will definitely support you on providing the logs, but right now I do not know where to start.

**Additional info**
 - OS: Ubuntu 18.04
- `multipass version` 1.5
multipass  1.5.0
multipassd 1.5.0
- `multipass info --all`
Name:           vm1
State:          Unknown
IPv4:           --
Release:        --
Image hash:     04a92109979d (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

**Additional context**
Is it possible to access the data stored in the instances?

**Comment by Saviq** [comment]
Hi @usovitsj, one way to recover is to run the VM manually. When it's in the `Unknown` state, see `ps aux | grep qemu` and find the line for the `qemu-system-x86_64` process and copy it. You'll then need to `multipass stop vm1`, which might return an error. Make sure that the above process is gone with another `ps…` call, and `sudo kill -9` it, if still there.

Remove `-nographic` from the arguments passed to QEMU and run `sudo qemu…` (you need `qemu-system-x86` installed). That should give you a window with the VM booting. You should be able to choose recovery mode in GRUB and you'll get a root prompt in which you should be able to introspect what went wrong.

**Comment by usovitsj** [comment]
Hi Saviq, 
> You should be able to choose recovery mode in GRUB and you'll get a root prompt in which you should be able to introspect what went wrong.
I managed to mount the image. I found the following errors:
corrupted or uncleanly shut down renaming and replacing
and
print_req_error i/o dev fd0, sector 0
after shutdown -r
only
print_req_error i/o dev fd0, sector 0
remained.
After the errors I am able to enter my password for maintenance
which prompts me to:
root@vm1:~# 

How do I enter the grub in the qemu?

Probably the error 'print_req_error i/o dev fd0, sector 0' is not the error which stops the vm1 from booting. Are there some ideas how to make the instance vm1 bootbale again with multipass?

**Comment by usovitsj** [comment]
Hi Saviq,
Wll I managed to find the issue. It looks like multipass doe not like the swapfile. Removing and disabling this got back the instance!
0. Did apt-get upgrade
and apt-get update
1. I disabled the swap <- Probably this one was the most important step
swapoff -a
and placed # before the line
: /swapfile    none    swap    sw      0 0
in /etc/fstab
2. I deleted the bad journal files
4. then I shutdown -h now
5. after starting the qemu manually I was prompted this time to enter the login information
6. Now I could use the command ssh multipass shell vm1

May you elaborate on my findings on how to avoid this in the future?
For example I would like to use a swapfile in future. Are there special rules how to reboot the virtual machine without facing the same problem again? Note, the swapfile was there since the launch of the virtual machine / since the beginning.
Best,
Johann

If you encounter

**Comment by Saviq** [comment]
Hi @usovitsj, this sounds like the swap file was configured wrong? Did you create the swapfile? When you manually `swapon /swapfile`, does it work or return an error?

This seemed to work fine for me:
```
 multipass exec primary sudo dd if=/dev/zero of=/swapfile bs=1024 count=65536
65536+0 records in
65536+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 0.192046 s, 349 MB/s
 multipass exec primary sudo chmod 600 /swapfile                             
 multipass exec primary sudo mkswap /swapfile                                
Setting up swapspace version 1, size = 64 MiB (67104768 bytes)
no label, UUID=3cb02e09-f773-4a76-88be-7242fd8588d7
 echo "/swapfile       none    swap    discard 0       0" | multipass exec primary -- sudo tee -a /etc/fstab
/swapfile       none    swap    discard 0       0
 multipass exec primary -- sudo reboot        
 multipass exec primary -- sudo free -m       
              total        used        free      shared  buff/cache   available
Mem:            981         131         581           0         268         702
Swap:            63           0          63
```

I'm going to close this issue, then.
