### ISSUE TITLE
[snap] Cannot chance font in terminals launched from the GUI

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#1908]
**Describe the bug**
When running from a snap, the `xterm` that is launched by the GUI has a very small font in hiDPI screens and changing that font with ctrl+right-click doesn't work. Additionally, the terminal fails to open entirely when there are special font configurations.

**To Reproduce**
1. multipass.gui
1. open a shell from the Multipass GUI
1. try to select a font with ctrl+right-click
1. hear a bell and read complaints like (among others):

```
/snap/multipass/3092/usr/bin/xterm: Failed to open input method
Warning: Unable to load any usable fontset
```

And

1. Add font configurations to `~/.Xresources`:
```
$ cat > ~/.Xresources << EOF
> xterm*faceName: fixed
> xterm*faceSize: 10
> EOF
```
2. `xrdb -merge ~/.Xresources`
3. `multipass.gui`
4. Open Shell
5. Confirm that the shell fails to open, and read a bunch of error messages about fonts

**Expected behavior**
Fonts would be changeable.

**Additional info**
 - OS: Ubuntu 20.04
 - `multipass version`
```
multipass  1.6.0-dev.243+gf2c175f7
multipassd 1.6.0-dev.243+gf2c175f7
```

**Comment by ricab** [comment]
The ultimate fix would probably be #899, but perhaps we could find a workaround in the meantime.

**Comment by ricab** [comment]
We get the following AppArmor denial when trying to open xterm:

```
= AppArmor =
Time: Jan  8 13:20:57
Log: apparmor="DENIED" operation="open" profile="snap.multipass.gui" name="/etc/X11/app-defaults/XTerm" pid=40435 comm="xterm" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /etc/X11/app-defaults/XTerm (read)
```

**Comment by townsend2010** [comment]
Closing this since 1) We switched to using xfce-terminal along the way and 2) the upcoming release removes the external terminal and uses a terminal from within the GUI.
