### ISSUE TITLE
Troubleshooting networking on Windows

### ISSUE THREAD

**Issue by tpdeliezer** [canonical/multipass#1916]
Multipass doesnot connect the internet on windows

**Comment by Saviq** [comment]
@tpdeliezer please have a look at [our documentation on the topic](https://multipass.run/docs/troubleshooting-networking-on-windows), and if nothing there helps, file a new issue completing this template:

https://github.com/canonical/multipass/issues/new?labels=bug&template=bug_report.md&title=Troubleshooting%20networking%20on%20Windows

Thanks!
