### ISSUE TITLE
spark worker cannot connect to spark master, trying to reconnect after succesful connection

### ISSUE THREAD

**Issue by sudip06** [canonical/multipass#1936]
**Describe the bug**
I have a setup of 1 master and 1 worker, both on centos 7

**To Reproduce**
How, and what happened?
1. On master, here's the spark-env.sh
```
export STANDALONE_SPARK_MASTER_HOST='10.0.0.6'
export SPARK_MASTER_HOST='10.0.0.6'
#export SPARK_EXECUTOR_CORES=1
export JAVA_HOME='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64'

```
Here's the slaves file (conf/slaves)
```
[sudip@localhost sbin]$ cat ../conf/slaves
10.0.0.20
[sudip@localhost sbin]$ 


```On master,
```
[sudip@localhost sbin]$ hostname
localhost.localdomain
[sudip@localhost sbin]$ 

```
When I execute start-all.sh, here's the log on slave(10.0.0.20)
```
[sudip@localhost sbin]$ 
[sudip@localhost sbin]$ cat /opt/spark/logs/spark-sudip-org.apache.spark.deploy.worker.Worker-1-localhost.localdomain.out
Spark Command: /usr/java/jdk1.8.0_271-amd64/bin/java -cp /opt/spark/conf/:/opt/spark/jars/* -Xmx1g org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://10.0.0.6:7077

========================================
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/01/25 19:18:33 INFO Worker: Started daemon with process name: 4683@localhost.localdomain
21/01/25 19:18:33 INFO SignalUtils: Registered signal handler for TERM
21/01/25 19:18:33 INFO SignalUtils: Registered signal handler for HUP
21/01/25 19:18:33 INFO SignalUtils: Registered signal handler for INT
21/01/25 19:18:33 WARN Utils: Your hostname, localhost.localdomain resolves to a loopback address: 127.0.0.1; using 10.0.0.20 instead (on interface enp5s0)
21/01/25 19:18:33 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
21/01/25 19:18:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/01/25 19:18:34 INFO SecurityManager: Changing view acls to: sudip
21/01/25 19:18:34 INFO SecurityManager: Changing modify acls to: sudip
21/01/25 19:18:34 INFO SecurityManager: Changing view acls groups to: 
21/01/25 19:18:34 INFO SecurityManager: Changing modify acls groups to: 
21/01/25 19:18:34 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(sudip); groups with view permissions: Set(); users  with modify permissions: Set(sudip); groups with modify permissions: Set()
21/01/25 19:18:34 INFO Utils: Successfully started service 'sparkWorker' on port 44221.
21/01/25 19:18:35 INFO Worker: Starting Spark worker 10.0.0.20:44221 with 8 cores, 22.3 GiB RAM
21/01/25 19:18:35 INFO Worker: Running Spark version 3.0.1
21/01/25 19:18:35 INFO Worker: Spark home: /opt/spark
21/01/25 19:18:35 INFO ResourceUtils: ==============================================================
21/01/25 19:18:35 INFO ResourceUtils: Resources for spark.worker:

21/01/25 19:18:35 INFO ResourceUtils: ==============================================================
21/01/25 19:18:35 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
21/01/25 19:18:35 INFO WorkerWebUI: Bound WorkerWebUI to 0.0.0.0, and started at http://10.0.0.20:8081
21/01/25 19:18:35 INFO Worker: Connecting to master 10.0.0.6:7077...
**21/01/25 19:18:35 INFO TransportClientFactory: Successfully created connection to /10.0.0.6:7077 after 52 ms (0 ms spent in bootstraps)**
21/01/25 19:18:50 INFO Worker: Retrying connection to master (attempt # 1)
21/01/25 19:18:50 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:19:05 INFO Worker: Retrying connection to master (attempt # 2)
21/01/25 19:19:05 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:19:20 INFO Worker: Retrying connection to master (attempt # 3)
21/01/25 19:19:20 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:19:35 INFO Worker: Retrying connection to master (attempt # 4)
21/01/25 19:19:35 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:19:50 INFO Worker: Retrying connection to master (attempt # 5)
21/01/25 19:19:50 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:20:05 INFO Worker: Retrying connection to master (attempt # 6)
21/01/25 19:20:05 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:21:33 INFO Worker: Retrying connection to master (attempt # 7)
21/01/25 19:21:33 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:23:01 INFO Worker: Retrying connection to master (attempt # 8)
21/01/25 19:23:01 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:24:29 INFO Worker: Retrying connection to master (attempt # 9)
21/01/25 19:24:29 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:25:57 INFO Worker: Retrying connection to master (attempt # 10)
21/01/25 19:25:57 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:27:25 INFO Worker: Retrying connection to master (attempt # 11)
21/01/25 19:27:25 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:28:53 INFO Worker: Retrying connection to master (attempt # 12)
21/01/25 19:28:53 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:30:21 INFO Worker: Retrying connection to master (attempt # 13)
21/01/25 19:30:21 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:31:49 INFO Worker: Retrying connection to master (attempt # 14)
21/01/25 19:31:49 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:33:17 INFO Worker: Retrying connection to master (attempt # 15)
21/01/25 19:33:17 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:34:45 INFO Worker: Retrying connection to master (attempt # 16)
21/01/25 19:34:45 INFO Worker: Connecting to master 10.0.0.6:7077...
21/01/25 19:36:13 ERROR Worker: All masters are unresponsive! Giving up.
[sudip@localhost sbin]$ 

```











**Expected behavior**
worker slave should stay connected to master and not able to reconnect

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: centos7
- `multipass version`
- `multipass info --all`

**Additional context**
Add any other context about the problem here.

**Comment by Saviq** [comment]
Hi @sudip06, what does `multipass info --all` say? Where did you get the `10.0.0.*` addresses?

**Comment by sudip06** [comment]
Hi Michael,
thanks for your reply.

It shows nothing on master:
[sudip@localhost sbin]$ multipass info --all

[sudip@localhost sbin]$

And, these are the ip addresses received from dhcp server, master got
10.0.0.6, worker 10.0.0.20.

**Comment by Saviq** [comment]
@sudip06 where are the Multipass instances, then?

**Comment by sudip06** [comment]
well, should there be mandatory multipass instances?cause my worker and
master are on diff machines, not vm's, both are running centos, master on
centos 7, worker on centos 8. I am new to multipass, so don't have
knowledge of it. please let me know some pointers to fix this issue. all I
expect is that I should see the worker information in http:<master
ip>:8080, where I am seeing nothing, then I see the log of the worker,
where it shows it's able to connect to master then again trying to
reconnect.

Thanks for your help

**Comment by Saviq** [comment]
@sudip06 this repository is for Multipass only, you want to report to Spark upstream instead.
