### ISSUE TITLE
Not able to find the "networks" command in multipass

### ISSUE THREAD

**Issue by sankar454** [canonical/multipass#1970]
I am using below versions of multipass
multipass  1.5.0+win
multipassd 1.5.0+win

Please help me with the below situations.

1. When I execute "multipass --help" I am not able to see the "networks" command in the list of available commands.
2.  When I execute "multipass list" getting output as below
`Name                    State             IPv4             Image`
`novel-mule              Running           N/A              Ubuntu 20.04 LTS`
I could see that IPv4 is N/A, help me to get a value to it.

Thanks,
Shankar

**Comment by Saviq** [comment]
@sankar454 `networks` is only available since 1.6.1:

https://github.com/canonical/multipass/releases/tag/v1.6.1

It's not yet linked from the main web page because we've a bugfix release incoming.
