### ISSUE TITLE
Cannot launch multipass: The computer needs to be rebooted in order for Hyper-V to be fully available (Hyper-V is fully installed)

### ISSUE THREAD

**Issue by ghost** [canonical/multipass#1972]
**Describe the bug**
Describe what your problem is.

When I try to launch a vm with multipass I get the error `The computer needs to be rebooted in order for Hyper-V to be fully available`

I have rebooted multiple times and can confirm that Hyper-V is enabled through the enabled features gui as well as I can run an Ubuntu VM through Hyper-V with no problem.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1. `The computer needs to be rebooted in order for Hyper-V to be fully available`

**Expected behavior**
What did you expect to happen?

Launch VM

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform. - I cannot find logs in Event Viewer.

**Additional info**
 - OS: [e.g. macOS 10.15] Windows 10 Pro 20H2
- `multipass version` multipass 1.5.0+win
- `multipass info --all` (no return)

**Additional context**

**Comment by tylerwolf35** [comment]
I have been able to fix this by running the following command: `bcdedit /set hypervisorlaunchtype auto`
