### ISSUE TITLE
shell failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'

### ISSUE THREAD

**Issue by tylerwolf35** [canonical/multipass#1973]
**Describe the bug**
Describe what your problem is.

When I run `multipass shell $INSTANCE` I get the error `shell failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'`.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1. `multipass shell $INSTANCE`
2. `shell failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'`

**Expected behavior**
What did you expect to happen?

I expect to be given the shell of my instance.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

[multipass.zip](https://github.com/canonical/multipass/files/5982112/multipass.zip)

**Additional info**
 - OS: [e.g. macOS 10.15] `Windows 10 Pro 20H2 19042.804`
- `multipass version` `1.5.0+win`
- `multipass info --all` `info failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'`

**Additional context**

This was working fine last night, I also was able to SSH into the instance last night but now get the same error. The IP address of the instance seemed to have changed based on running a command to show it, although this may just happen every time an instance is restarted.

**Comment by Saviq** [comment]
Hi @tylerwolf35 did you do anything to `~/.ssh/` inside the instance? If you launch a new instance, does it result in the same issue?

**Comment by tylerwolf35** [comment]
I did not do anything to `~/.ssh/` in the instance. By that I am assuming that this error refers to the ssh files missing. If I launch a new instance I do not get this error.

**Comment by tylerwolf35** [comment]
I have decided to delete the instance and create a new one, I did not have much on my previous one and did not thing that this was fixable.

**Comment by cvalarezo-rbi** [comment]
Actually to sort this out, I followed these steps:
- Create a ssh for "ubuntu user": 
- Copy the public ssh to the clipboard
- `multipass shell <instance-name>`
- Once inside the instance: `vi ~/.ssh/authorized_keys`
- Paste at the end the public ssh copied earlier
- `ssh ubuntu@ipoftheinstance`
