### ISSUE TITLE
Windows 10 still no IPv4 using Virtual Box (latest version multipass  1.6.2+win)

### ISSUE THREAD

**Issue by jmcausing** [canonical/multipass#1979]
Hi guys!

I thought this is support using the latest version:

Support for bridged networking (#118, #1886, #1912, #1921)

But when I tested this using my Windows 10 (Virtual Box), it's still not getting an IP address (IPv4 n/a)

I am using virtual box because I am also using VMWare at the same time so I have to disable Hyper-V in order for me to use VMware and Multipass at the same time.

Please see screenshot below.

Thank you/

![image](https://user-images.githubusercontent.com/10601417/108681676-6516c780-752a-11eb-9fbd-013e436d895c.png)

**Comment by Saviq** [comment]
You have to tell which interface to go out on using the `--network` option:

https://multipass.run/docs/additional-networks

The first interface will never have a meaningful IP, as it's a VirtualBox-internal network.

I'll close this for now, please reopen if something still isn't working for you.

**Comment by jmcausing** [comment]
Perfect. Thank you very much! 
![image](https://user-images.githubusercontent.com/10601417/108683253-56311480-752c-11eb-8bd2-2b162072e4eb.png)

**Comment by maliswe** [comment]
The link of the page is 404 
![image](https://github.com/canonical/multipass/assets/98175456/81b6150e-16da-4153-9d94-27bef83c590b)

**Comment by maliswe** [comment]
![image](https://github.com/canonical/multipass/assets/98175456/5b076ad7-a1ae-400a-ab31-be694f1682a3)
It gave the vM localhost ip address which I can use it

**Comment by JoshuaT35** [comment]
@wodeweilai This worked for me:
<img width="436" alt="Screenshot 2024-09-26 211017" src="https://github.com/user-attachments/assets/d1d9258b-6db4-4d2e-95ca-be0a179890b7">
