### ISSUE TITLE
How to use VM that was created with hyperkit after switch to virtualbox driver?

### ISSUE THREAD

**Issue by ranshe** [canonical/multipass#1984]
sudo multipass set local.driver=virtualbox

multipass list      
No instances found.

sudo multipass set local.driver=hyperkit
multipass list                          
Name                    State             IPv4             Image
db                      Stopped           --               Ubuntu 20.04 LTS
proxy                   Stopped           --               Ubuntu 20.04 LTS
web                     Stopped           --               Ubuntu 20.04 LTS

I already built some functionality on these, how can I re-purpose them to be used in virtualbox driver?

**Comment by Saviq** [comment]
Hi @ranshe, the VMs have different disk formats, so it's not trivial. We don't currently support such conversions.

You could convert the images with the `qemu-img` tool, and copy/modify the instances JSON accordingly.

Remember to shut Multipass down while doing that.

**Comment by ranshe** [comment]
> You could convert the images with the `qemu-img` tool, and copy/modify the instances JSON accordingly.
Any pointers on the command format, JSON changes, and where are the images stored?
I can't find /var/root/Library/Application\ Support/multipassd as some posts suggest

**Comment by Saviq** [comment]
You will have to fix the image location in JSON file under `vault/`. In `-instances.json` you'll need to fix `mac_addr`, so note that from the hyperkit instances (`multipass exec <instance> -- ip link show`).

Unless you used `MULTIPASS_STORAGE` (https://github.com/canonical/multipass/pull/1789#issuecomment-705393264) to change the location, it is:

```plain
# JSON locations
/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
/var/root/Library/Application Support/multipassd/virtualbox/multipassd-vm-instances.json

# image locations
/var/root/Library/Application Support/multipassd/vault/
/var/root/Library/Application Support/multipassd/virtualbox/vault/
```

To convert, use `qemu-img -O vdi <old> <new>`.

**Comment by townsend2010** [comment]
Since this is Hyperkit-specific and we are deprecating and removing Hyperkit soon, I'm closing this request.  Thanks!
