### ISSUE TITLE
Need to cache relevant image info when downloading an image

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#199]
Recently, many older bionic daily images have disappeared from the cloud-images simplestreams database, so when multipass tries to look up image information for a particular instance via simplestreams, the information for that hash is missing, which causes multipass to throw an error and break `list` and `info`.

We need to do two things here:
1. Cache the relevant image info for the downloaded image and then copy that when an instance is created.
2. Still allow `list` and `info` to work and not bubble up the thrown exception and instead perhaps fill in the missing fields with something like "MISSING" or "NA".

**Comment by Saviq** [comment]
> Cache the relevant image info for the downloaded image

I don't think we need to be doing that,

> and then copy that when an instance is created.

this should be enough - on launch, copy the whole dataset from streams to instance data?

**Comment by townsend2010** [comment]
Just copying on instance launch may not be enough, in particular for instances that are launched using a hash.  We persist these types of images and if for some reason the corresponding image is removed from cloud-images (like almost all bionic images recently), then we'll be in the same situation we are now.

**Comment by Saviq** [comment]
OK, we probably mean the same thing - whatever image we have cached (via launch, or via cache refreshes), we store all data for it, yes.

**Comment by townsend2010** [comment]
Reopening due to #201 only partially fixing what is needed.
