### ISSUE TITLE
`list` fails when interrogating instances fails

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1992]
With the `list` command now trying to interrogate instances for IP numbers, whenever ssh to the instance fails, the `list` command does, too:

```plain
$ multipass ls
list failed: ssh connection failed: 'Timeout connecting to 127.0.0.1'
$ multipass ls
list failed: [ssh proc] failed to open session channel: ''
$ multipass ls
# worked this time
```

**Comment by luis4a0** [comment]
Hey @Saviq, should we just return an empty list of IP's and log in this case?

**Comment by Saviq** [comment]
> Hey @Saviq, should we just return an empty list of IP's and log in this case?

If we know the management IP, show that, otherwise yes - empty.
