### ISSUE TITLE
Multipass list, shell command not working

### ISSUE THREAD

**Issue by AnkurSaini07** [canonical/multipass#1994]
I have installed multipass on windows and when I use `multipass list` command it throws following error
`list failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'`

I have reinstall multipass several times but still getting same issue.

**Comment by Saviq** [comment]
Hi @AnkurSaini07, can you please show the output of:

`multipass list -vvvv`?

How did you launch the instance, did you maybe use cloud-init to add SSH keys to the instance?

**Comment by AnkurSaini07** [comment]
Hi @Saviq , following is the output of `multipass list -vvvv`

`[2021-03-05T12:42:49.640] [debug] [manager] [13304] Cmdlet: 'Get-VM -Name manager | Select-Object -ExpandProperty State'`
`[2021-03-05T12:42:49.679] [trace] [manager] Running`

`[2021-03-05T12:42:49.679] [trace] [manager] [13304] Output: Running`

`[2021-03-05T12:42:49.679] [debug] [manager] [13304] Cmdlet exit status is 'true'`

`list failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'`

and i use `multipass launch -n manager -c 2 -d 10G -m 2G` command to launch vm

**Comment by Saviq** [comment]
Hey, when reinstalling, did you remove all data?

That `list` isn't working in this case is #1992, we're working on a fix. You could downgrade to [1.5.0](https://github.com/canonical/multipass/releases/tag/v1.5.0) to avoid it.

But why would the instance not allow you in, that I don't know, yet.

Can you reproduce? You can remove the broken instance with `multipass delete --purge manager` to get `list` working again.

**Comment by AnkurSaini07** [comment]
`multipass delete --purge manager` Thanks this worked for me.

**Comment by AnkurSaini07** [comment]
I think when I uninstalled multipass i didn't remove all the data of VMS, After installing it again when I did `multipass ls`  it shows no instances but after launching the instance with same name this issue occurred.

**Comment by Saviq** [comment]
@AnkurSaini07 after removing the broken instance, were you able to launch a new instance OK?

**Comment by AnkurSaini07** [comment]
@Saviq , yes it worked fine but when i did multipass list after reinstalling it didn't show the broken vms and i had to repeat the same steps for all other vms.

**Comment by Saviq** [comment]
Right, that's the #1992 bug I mentioned.
