### ISSUE TITLE
MacosBigSur `list` error

### ISSUE THREAD

**Issue by HenryJi529** [canonical/multipass#1996]
**Describe the bug**
"list" error
**To Reproduce**
How, and what happened?
1. shutdown the machine
2. `multipass list`

**Expected behavior**
```bash
list failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible
```

**Additional info**
 - OS: macOS 10.15
- `multipass version: `multipass  1.6.2+mac
- `multipass info --all`:
info failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible

**Comment by Saviq** [comment]
Hi @HenryJi529, can you please try with this version?

https://multipass-ci.s3.amazonaws.com/multipass-1.7.0-dev.367.ci918%2Bgef914982.mac-Darwin.pkg

**Comment by HenryJi529** [comment]
Thanks a lot
