### ISSUE TITLE
VirtualBox stuck with "locked" VM

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2006]
@Saviq 
Now I have two other problems:
- The first: trying to configure the multipass machine on VirtualBox GUI prompts me again and again to an alert stating that the state of the current machine has changed.
- The Second: I can't restart the multipass virtual machine using multipass (currently it is suspended) even though I stopped `PsExec.exe`

_Originally posted by @magmine in https://github.com/canonical/multipass/issues/1158#issuecomment-799494429_

**Comment by Saviq** [comment]
@magmine I split this issue into a separate one.

By "can't restart" do you mean you're getting VirtualBox dialogs about the VM being locked? Sounds like the VirtualBox GUI is still running, despite PsExec being stopped? You may need to stop the VirtualBox.exe process from the process manager.

A reboot, while a big hammer, should resolve it all.

For that reason using `VBoxManage` is a safer choice, btw.

**Comment by magmine** [comment]
@Saviq I can't restart after stopping PsExec and closing VirtualBox GUI (maybe the process is still running in the background not sure)
- so after stopping both PsExec and VBox when I try `multipass start myVM` either It runs very fast but then trying to get into the shell does not work or it times out:
`shell failed: ssh connection failed: 'Timeout connecting to 127.0.0.1'`
- And even `multipass list` times out
`start failed: The following errors occurred:
myVM: timed out waiting for response` 

For your information (HyperV is still enabled for me since before using VBox as driver I used hyperV)

**Comment by Saviq** [comment]
@magmine that sounds like the instance no longer starts properly. What did you change in its configuration?

To stop the GUI prompt, you can stop the Multipass icon that polls the VM for its state periodically.

When you start the VM in VirtualBox, does it look like it's booting normally?

**Comment by magmine** [comment]
> When you start the VM in VirtualBox, does it look like it's booting normally?

@Saviq  it boots normally but just in the small window at the right side, I guess because of desktop tools not installed.
>To stop the GUI prompt, you can stop the Multipass icon that polls the VM for its state periodically.

I can't see how ? all I can do is press enter fast enough to escape both the alert message and configuration GUI

> What did you change in its configuration?

The NAT only

**Comment by Saviq** [comment]
> > To stop the GUI prompt, you can stop the Multipass icon that polls the VM for its state periodically.
> 
> I can't see how ? all I can do is press enter fast enough to escape both the alert message and configuration GUI

By "the icon" I mean the Multipass icon (![image](https://user-images.githubusercontent.com/231077/111181272-18189500-85ae-11eb-83d1-07caccca12d8.png)) in your system tray. Right-click, Quit.

> > What did you change in its configuration?
> 
> The NAT only

That would do it. Multipass talks to the instance on the first network interface. If you want to expose the instance on your network, see here:

https://multipass.run/docs/additional-networks

**Comment by magmine** [comment]
- I disabled HyperV and restarted, The alert message is not prompting anymore.
- After I changed the configuration to use  the default one (Using VBox Manager GUI prompted by running PsExec). I and tried to start myVM using `multipass start myvm` got the following error:
`multipass start myVM
start failed: Could not start VM: Waiting for VM "myVM" to power on...
VBoxManage.exe: error: apic#0: Config mismatch - uApicMode: saved=2 config=3 [ver=5 pass=final] (VERR_SSM_LOAD_CONFIG_MISMATCH)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole`

**Comment by Saviq** [comment]
Disabling Hyper-V was likely what's causing this. VBox can't now start the VM that was created under Hyper-V…

**Comment by magmine** [comment]
Is the only solution to remove this current instance and start another one under VirtualBox Driver (Given that I created this instance after choosing VBox as the driver)

**Comment by Saviq** [comment]
@magmine that, or re-enabling Hyper-V should do, too.

**Comment by magmine** [comment]
Thanks a lot @Saviq

**Comment by Saviq** [comment]
I'm going to close this as this isn't, in fact, a Multipass issue.
