### ISSUE TITLE
multipass error

### ISSUE THREAD

**Issue by Ash577** [canonical/multipass#2015]
**Describe the bug**
Did not find any supported products in "appliance"

**Expected behavior**
Expected to run  multipass

**Logs**
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Could not update manifest 
Mar 19 07:35:54 ash-G31M-ES2L dnsmasq[1131]: reading /etc/resolv.conf
Mar 19 07:35:54 ash-G31M-ES2L dnsmasq[1131]: using local addresses only for domain multipass
Mar 19 07:35:54 ash-G31M-ES2L dnsmasq[1131]: using nameserver 127.0.1.1#53
Mar 19 15:48:22 ash-G31M-ES2L multipassd[886]: Did not find any supported products in "appliance"

**Additional info**
 - OS: [Ubuntu 16.04.7 LTS i686]
- `multipass version 1.6.2`
- an icon of multipass appeared but that also displays same error
- [multipassError2.txt](https://github.com/canonical/multipass/files/6170691/multipassError2.txt)

**Additional context**
 - earlier there was an error of 
 `cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory`

**Comment by Saviq** [comment]
Hi @Ash577, your actual problems are this:

```plain
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/releases/streams/v1/index.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/daily/streams/v1/index.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Did not find any supported products in "appliance"
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Could not update manifest: failed to download from 'http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Host cdimage.ubuntu.com not found
Mar 19 07:35:45 ash-G31M-ES2L multipassd[886]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img': Host cloud-images.ubuntu.com not found
```

Something is wrong with your networking?

**Comment by Ash577** [comment]
- there is nothing wrong in hardware
- how do I find what is wrong?
 
![Screenshot from 2021-03-19 18-29-29](https://user-images.githubusercontent.com/62878695/111786156-7eb9ed80-88e3-11eb-9d9d-f84e8146a5fc.png)

**Comment by Saviq** [comment]
@Ash577 that crash is from Xorg, not related to Multipass.

But, is your machine i386? Sorry, we don't support that architecture any more. Can you upgrade? 16.04 is almost out of support, too.

**Comment by Ash577** [comment]
Thanks for help
