### ISSUE TITLE
Ability to quickly re-launch an instance

### ISSUE THREAD

**Issue by brettplarson** [canonical/multipass#2018]
**What are you trying to do?**
I am trying to use cloud-config scripts and want to be able to quickly re-launch my instances, as I troubleshoot my scripts however the process is quite annoying , I have to delete the instance and run `multipass purge` each time.

**What's your proposed solution?**
A parameter like `multipass relaunch --name test01 --cloud-init test01.yaml` would be great as I could test my cloud-config scripts without having to run 3 commands to delete, purge, and re-launch.

**Comment by Saviq** [comment]
Hi @brettplarson, you can use `multipass delete --purge test01 && multipass launch --name test01 --cloud-init test01.yaml`, we'd rather not introduce a special command for that :)
