### ISSUE TITLE
Cannot open Multipass shell on Windows

### ISSUE THREAD

**Issue by pmillspaugh** [canonical/multipass#2026]
**Describe the bug**

I am having trouble with my Ubuntu VM. I set it up a few weeks ago on Windows Home using VirtualBox, and it was working well, then I ran into myriad issues starting yesterday (3/24/2021).

At first my shell was open and I kept running into errors, but now I cannot open my shell at all. As a disclaimer, I am new to all this, so apologies if I've missed something straightforward when going through all the other issue threads. Thank you all in advance for the help here!

**To Reproduce**

1. I first noticed the problem when trying to git clone. This was the error message:
```
> git clone 'repo-i-want-to-clone`
fatal: unable to access 'repo-i-want-to-clone' Could not resolve host: github.com
```
2. When I tried to reset my http(s) proxy, I got this error:
```
> git config --global --unset http.proxy
> git config --global --unset https.proxy
error: could not lock config file /home/ubuntu/.gitconfig: Read-only file system
```
3. At another point, trying to clone returned this error:
```
> git clone 'repo-i-want-to-clone`
fatal: could not create work tree dir 'repo-i-want-to-clone': Read-only file system
```
4. As mentioned above, I cannot even open my shell now. When I try, this is the error log:
```
PS C:\Users\pdm8d> multipass shell primary -vvvv
[2021-03-25T08:44:04.066] [debug] [primary] Got VMState: running

[2021-03-25T08:44:04.106] [debug] [primary] Got VMState: running

shell failed: [ssh client] channel creation failed: ''
```

**Expected behavior**

As mentioned, my shell was working well for a few weeks (I had successfully cloned repos before). Here are some other things I tried:

- `apt upgrade` and `apt update`
    - Many of the actions failed to fetch (let me know if this is worth investigating, and I can post the error output)

- `git config --global --unset http.proxy`
    - Didn't work because Read-only file system

- I tried changing the permissions on my home/ubuntu to be writable to address the 'Read-only file system' error
    - Didn't let me change permissions

- I uninstalled and reinstalled Multipass to no avail

- `Get-VMSwitch`
    - No output (PowerShell did not recognize cmd)

- `Get-HNSNetwork | ? Name -Like "Default Switch" | Remove-HNSNetwork`
    - No output (PowerShell did not recognize cmd)

**Logs**

I looked through my event viewer, which contained many Multipass errors and warning messages, including:

    `[sshfs-mounts] Mount 'Home' in instance "primary" has stopped unexpectedly: Process returned exit code: 9`

    `[daemon] Error updating images: Remote "" is unknown or unreachable.`

    *There are many more warning messages, so let me know if it would be helpful to add them all in here*

**Additional info**
- OS: Windows 10 Home (version 1909)
- `multipass version`
```
multipass  1.6.2+win
multipassd 1.6.2+win
```
- `multipass info --all`
```
info failed: [ssh proc] failed to open session channel: ''
```

**Additional context**

Below I've listed some recent actions I've taken this week leading up to the problem, which may or may not be related.

1. Windows system updates:

    - Update for Windows 10 Version 1909 for x64-based Systems (KB4589211)
        - Installed on 3/24/2021
    - Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Windows 10 Version 1909 for x64 (KB4601556)
        - Installed on 3/24/2021

2. SSH

    - Generated new SSH keys for GitHub and for cloud server
    - *Many of the errors I'm seeing seem to relate to ssh, so I suspect this may be part of the problem?*

3. Nginx

    - Installed nginx on a cloud server using my Multipass Ubuntu VM

**Comment by pmillspaugh** [comment]
I realized I did not mean to add the `bug` label to this issue (not sure how to delete the label) – apologies!

**Comment by Saviq** [comment]
Hi @pmillspaugh, no worries about the label.

This is what looks suspect:

> `/home/ubuntu/.gitconfig: Read-only file system`

Your Ubuntu filesystem seems to have gotten corrupted. You can try and open a recovery console [with VirtualBox directly](https://multipass.run/docs/using-virtualbox-in-multipass-windows) to see if you can repair it.

**Comment by pmillspaugh** [comment]
Thank you for the prompt help, @Saviq!

My VM is back up and running, although it is a completely blank slate (~/.ssh is empty, my C: drive isn't mounted, etc). Here are the steps I've taken since my initial post:

1. I installed another Windows update (Feature update to Windows 10, version 20H2) and restarted my computer. After doing so, Multipass returned this error when I tried to open the shell:

    ```
    launch failed: Hyper-V is not available on this edition of Windows 10. Please upgrade to one of Pro, Enterpriseor Education editions.

    [process exited with code 2]
    ```

2. I think this meant that my machine reverted to using Hyper-V as hypervisor instead of VirtualBox, so I ran this command again:

    ```
    PS> multipass set local.driver=virtualbox
    ```

3. To check my Multipass instances in VirtualBox, I followed the directions in the link you sent, using this command:

    ```
    PS> & $env:USERPROFILE\Downloads\PSTools\PsExec.exe -s $env:VBOX_MSI_INSTALL_PATH\VBoxManage.exe list vms
    ```

    - The output showed no instances of Multipass running at all, and neither did the VirtualBox GUI
    - I launched a primary shell on multipass, which opened successfully, then ran `multipass list` to confirm that it was running

I'll take a functional shell over no shell, even if that means I have to repeat the setup I've done over the past few weeks. Please do let me know, though, if you have a recommendation for recovering the initial shell. If not, I'll close this request pleased with the fix :)

Appreciate your help.

**Comment by Saviq** [comment]
Hi @pmillspaugh, you've probably now been caught by #1119 - Windows updates move things around to `C:\Windows.old`, so both Multipass and VirtualBox have had their rug swept from under them.

Head there to see how to recover things.

**Comment by pmillspaugh** [comment]
Thanks, @Saviq. I'll check that thread and report back.

**Comment by pmillspaugh** [comment]
I copied the multipassd and VirtualBox folders from Windows.old, which did recover my instance, but some of the initial problems have recurred.

Multipass still times out when I try to open it, presenting this error:

```
shell failed: [ssh client] channel creation failed: ''

[process exited with code 2]
```

It did work once for me. In that instance, I can see the ssh keys I had before in ~/.ssh, so that's good, but my C: drive isn't mounted (not worried about that because I can mount again). But the main issue seems to be opening a session channel.

When I try `multipass list`, this error occurs:

```
list failed: [ssh proc] failed to open session channel: ''
```

In the shell that successfully opened, it said 3 updates were available, but when I try to run `apt upgrade` I am getting lots of errors. These errors seem to have three common structures, like the following:

```
Err:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 udev amd64 245.4-4ubuntu3.5
  Temporary failure resolving 'archive.ubuntu.com'
W: Problem unlinking the file /var/cache/apt/archives/partial/udev_245.4-4ubuntu3.5_amd64.deb - PrepareFiles (13: Permission denied)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.5_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
```

It seems like my shell connection is faulty. For example, pinging works in a different shell, but in Multipass this is what I get:

```
~ $ ping google.com
ping: google.com: Temporary failure in name resolution
```

Let me know how best to proceed. Thank you, @Saviq.

**Comment by pmillspaugh** [comment]
I decided to start fresh with a clean shell, so I'll close this issue. I was going in circles trying to debug, but on the bright side I feel more equipped to troubleshoot should another issue arise. Appreciate the help @Saviq.
