### ISSUE TITLE
Multipass 1.6.2+win64 fails to launch powershell on Win10 20H2

### ISSUE THREAD

**Issue by felixkasza** [canonical/multipass#2038]
Nothing works except getting help and finding instances; I have appended the trace for a "multipass networks" run. The instant interacion with Hyper-V is required, things break. That begins with setup which declares itself unable to enable Hyper-V (it _is_ enabled, and the Default Switch exists, and I recreated that twice already).

This:

```Get-HNSNetwork | ? Name -Like "Default Switch" | Remove-HNSNetwork```

followed by a reboot, does what it says. Regrettably, it doesn't help.

I thought about debugging through the failure, but a quick glance didn't turn up sources for the Windows port. Neither could I find any settings that modify the way multipass locates powershell binaries and the like.

Multipass sounds like just the ticket for what I am doing (learning deployment with cloud-init), and any help or a pointer to the Windows sources would be very much appreciated. Thanks!

```C:\tmp> multipass -vvvv networks
[2021-04-04T17:12:16.648] [trace] [Hyper-V Switch Listing] PowerShell arguments: Get-VMSwitch, |, Select-Object, -Property, Name,SwitchType,NetAdapterInterfaceDescription, |, ConvertTo-Csv, -NoTypeInformation, |, Select-Object, -Skip, 1, |, foreach, {, $_, -replace, '^"|"$|"(?=,)|(?<=,)"','', }

[2021-04-04T17:12:16.648] [trace] [Hyper-V Switch Listing] PowerShell working dir ''

[2021-04-04T17:12:16.648] [trace] [Hyper-V Switch Listing] PowerShell program 'powershell.exe'

[2021-04-04T17:12:16.664] [debug] [Hyper-V Switch Listing] [0] PowerShell error occurred FailedToStart

[2021-04-04T17:12:16.664] [warning] [Hyper-V Switch Listing] Could not start PowerShell

[2021-04-04T17:12:16.664] [trace] [Hyper-V Switch Listing] [0] Output:


networks failed: Could not determine available networks - error executing powershell command.```

**Comment by ricab** [comment]
Hi @felixkasza, I'm sorry you're experiencing those issues. The Windows specific source bits are not open, but it looks like Multipass is just unable to find or execute PowerShell, which it needs to do all sorts of things. That would explain all the problems you mention, including the ones at install.

Do you have the PowerShell executable available in your system PATH? Any special policies? Is it executable by the System/NT authority)? What happens if you run [`psexec.exe -s powershell.exe`](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) from an admin shell?

**Comment by felixkasza** [comment]
Hi @ricab, and thank you for taking the time to help me!

> Do you have the PowerShell executable available in your system PATH?

Well, _that_ is embarrassing: No, I don't.

Apparently, that PATH entry got lost in the shuffle between the Powershell version that ships with Windows and the later 5/6/7.x versions. And I never noticed because (a) I prefer a different shell and (b) when I do use Powershell, I run it interactively, and the Powershell installers register what amounts to an alias such that an invocation of the executable is automatically amended to include the full path:
```
C:\tmp> echo Wildcarded, won't use app aliases: %@search[p*w*sh*.exe]
Wildcarded, won't use app aliases:

C:\tmp> echo Not wildcarded, will use aliases: %@search[pwsh.exe]
Not wildcarded, will use aliases: "C:\Program Files\PowerShell\7\pwsh.exe"

C:\tmp> echo Not wildcarded, will use aliases: %@search[powershell.exe]
Not wildcarded, will use aliases: C:\WINDOWS\system32\WindowsPowerShell\v1.0\PowerShell.exe
```
I'll send off this confession, together with my abject apologies and heartfelt thanks; then I'll put on my dunce cap and go stand in the corner. And _then_ I'll make another go at multipass.

Thanks again,
Felix.

**Comment by ricab** [comment]
No worries at all @felixkasza! I hope things work well for you now :smile:
