### ISSUE TITLE
Multipass hard codes LXD storage pool name

### ISSUE THREAD

**Issue by morphis** [canonical/multipass#2041]
**Describe the bug**

My system does not have a LXD storage pool named `default`. Without that Multipass fails to create VMs.

**To Reproduce**

```
$ multipass launch              
Retrieving image: 86%
launch failed: Operation completed with error: (400) Failed creating instance record: Failed initialising instance: Failed loading storage pool: No such object
$ lxc storage ls
+-----------+--------+------------------+---------+---------+
|   NAME    | DRIVER |   DESCRIPTION    | USED BY |  STATE  |
+-----------+--------+------------------+---------+---------+
| nvme      | zfs    |                  | 2       | CREATED |
+-----------+--------+------------------+---------+---------+
| nvme-work | zfs    |                  | 16      | CREATED |
+-----------+--------+------------------+---------+---------+
```

**Expected behavior**

It would be great if multipass either doesn't hard code the storage pool name in its code and lets me adjust the `multipass` LXD profile to use a different one or provides a configuration option to customize the storage pool it uses.

Not having a LXD storage pool named `default` is quite common and even if it exists it might not be the best choice.

**Logs**

n/a

**Additional info**

OS: Ubuntu 20.04

```
multipass version
multipass  1.6.2
multipassd 1.6.2
```

**Additional context**

n/a

**Comment by townsend2010** [comment]
Yep, this needs to be fixed.  Instead of hard-coding this at each instance launch, we'll add this instead to the `multipass` profile, so at the very least, it can be edited to fit different cases.

Perhaps too when we do create the `multipass` profile, we can default to the first storage pool seen in the storage pool list and then users can change that how they see fit.

**Comment by Saviq** [comment]
@townsend2010 IIRC the recommendation from @stgraber was to _create_ a (`multipass`?) dir-based pool if there wasn't a `default` one? I don't think we should step on random pools.

:+1: on adding it to the profile.

**Comment by townsend2010** [comment]
@Saviq,

That's right, looking back at the chat, that's what was recommended, so that's what we'll do :smile:
