### ISSUE TITLE
[cli] missing input validation for `--cpus`

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2045]
**Describe the bug**
We can `multipass launch --cpus many`. We shouldn't be able to.

**To Reproduce**
How, and what happened?
1. `multipass launch --cpus many`
1. `Launched: …`

**Expected behavior**
It should error out.

**Comment by surahman** [comment]
I have added checks for alpha, alphanumeric, decimal, and zero-valued inputs.
