### ISSUE TITLE
Ubantu 2004 is missing in Multipass 1.6.2

### ISSUE THREAD

**Issue by oliverchan** [canonical/multipass#2052]
Hi
My version of multipass doesnt give me ubantu 20.04. Below is the trace.

```
root@qadev4:~# snap install multipass
multipass 1.6.2 from Canonical✓ installed
root@qadev4:~# multipass find
Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20200812         Ubuntu Core 18
appliance:adguard-home                        20200812         Ubuntu AdGuard Home Appliance
appliance:mosquitto                           20200812         Ubuntu Mosquitto Appliance
appliance:nextcloud                           20200812         Ubuntu Nextcloud Appliance
appliance:openhab                             20200812         Ubuntu openHAB Home Appliance
appliance:plexmediaserver                     20200812         Ubuntu Plex Media Server Appliance
root@qadev4:~#
```

**Comment by Saviq** [comment]
Hi @oliverchan that looks like something went wrong retrieving the image manifests.

Can you please post your multipassd logs ([here](https://multipass.run/docs/accessing-logs#linux)'s how to get them)?

**Comment by oliverchan** [comment]
@Saviq You are right. Here is log when I execute the multipass command. Not sure if this something the FW is blocking. Is there a way to confirm or bypass it?

root@qadev4:~# multipass find
Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20200812         Ubuntu Core 18
appliance:adguard-home                        20200812         Ubuntu AdGuard Home Appliance
appliance:mosquitto                           20200812         Ubuntu Mosquitto Appliance
appliance:nextcloud                           20200812         Ubuntu Nextcloud Appliance
appliance:openhab                             20200812         Ubuntu openHAB Home Appliance
appliance:plexmediaserver                     20200812         Ubuntu Plex Media Server Appliance


Apr 19 00:01:33 qadev4 multipassd[799]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img': SSL handshake failed
Apr 19 00:01:33 qadev4 multipassd[799]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/releases/streams/v1/index.json': SSL handshake failed
Apr 19 00:01:33 qadev4 multipassd[799]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/daily/streams/v1/index.json': SSL handshake failed

**Comment by Saviq** [comment]
@oliverchan do you have a proxy that you need to go through? Can you `curl -I https://cloud-images.ubuntu.com/` normally? Any chance your date/time are offset?

**Comment by oliverchan** [comment]
@Saviq 

This is what I have. it looks like there's an offset in the time. Will that help if I set it to be the same zone?

root@qadev4:~# curl -I https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img
HTTP/1.1 200 OK
Date: Mon, 19 Apr 2021 03:35:16 GMT
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Wed, 11 Nov 2020 12:44:46 GMT
ETag: "11620000-5b3d429022b80"
Accept-Ranges: bytes
Content-Length: 291635200
Connection: Keep-Alive

root@qadev4:~# date
Mon 19 Apr 2021 11:35:07 AM +08
root@qadev4:~#

**Comment by oliverchan** [comment]
@Saviq This is what I got. There's a change of my local time. but that just to reflect my timezone. 

root@qadev4:~# curl -I https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img
HTTP/1.1 200 OK
Date: Mon, 19 Apr 2021 03:30:11 GMT
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Wed, 11 Nov 2020 12:44:46 GMT
ETag: "11620000-5b3d429022b80"
Accept-Ranges: bytes
Content-Length: 291635200
Connection: Keep-Alive

root@qadev4:~# date
Mon 19 Apr 2021 11:34:46 AM +08

**Comment by Saviq** [comment]
Hi @oliverchan, all that seems fine. Something on your network must be preventing Multipass from accessing those. Do you have a proxy that rewrites HTTPS certificates maybe? You'd need to use `snap set multipass proxy.http/https <proxy>` to have Multipass get those.

**Comment by devspyrosv** [comment]
Hi!
I believe the same is true for windows too. The command "find" does not list all remote images properly.
Event Viewer has no messages logged  about a possible failed connection or a connection that timed out. 
I can access https://cloud-images.ubuntu.com/releases/streams/v1/index.json .
I can launch VMs like "bionic", so the images are downloading fine.
Having the firewall and AV stopped  and not using any kind of proxy, the only images "find" finds are the following:

```
PS C:\Users\user1> multipass find --verbose
[2021-04-22T14:45:54.693] [warning] [VMImageHost] Could not update manifest: unterminated object

Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20200812         Ubuntu Core 18
snapcraft:core18                              20201111         Snapcraft builder for Core 18
snapcraft:core20                              20201111         Snapcraft builder for Core 20
appliance:adguard-home                        20200812         Ubuntu AdGuard Home Appliance
appliance:mosquitto                           20200812         Ubuntu Mosquitto Appliance
appliance:nextcloud                           20200812         Ubuntu Nextcloud Appliance
appliance:openhab                             20200812         Ubuntu openHAB Home Appliance
appliance:plexmediaserver                     20200812         Ubuntu Plex Media Server Appliance

PS C:\Users\user1> multipass version
multipass  1.6.2+win
multipassd 1.6.2+win

```
