### ISSUE TITLE
Instances were gone after not using for 2-3 week.

### ISSUE THREAD

**Issue by amylily1011** [canonical/multipass#2053]
**Describe the bug**
My multipass does this weird thing that when I haven't used it for 3 weeks, all the instances that I created was gone. This happens about 3 times in separate occasions.

**To Reproduce**
I came back to multipass after 3 weeks and did
`multipass list`
and nothing was there. 

**Expected behavior**
I would expect all instances would be there even if I'm not using multipass for a period of time.
[multipassd.log](https://github.com/canonical/multipass/files/6310945/multipassd.log)

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/6310945/multipassd.log)

**Additional info**
 - OS: [macOS 11.2.3 Big Sur]
- `multipass  1.6.2+mac` 
```
Name:           dotrun
State:          Running
IPv4:           N/A
Release:        Ubuntu 20.04.2 LTS
Image hash:     075cbdf6b7d1 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.7G out of 4.7G
Memory usage:   131.9M out of 981.3M
```

**Additional context**

**Comment by Saviq** [comment]
Hi @amylily1011, the instance you're missing is probably `snap-maas`, is it? It's unclear to me where it disappeared, the only thing comes to mind is that Multipass crashed and lost the instance as part of that.

The instance itself may well still be around, have a look at our docs on this: https://multipass.run/docs/using-virtualbox-in-multipass-macos - if you run `sudo VirtualBox`, under "Multipass" you should see all the instances that we created. And there may be some we lost context of…

I see you only just upgraded to v1.6.2, let us know please if it happens again with this new version.

**Comment by amylily1011** [comment]
Hi @Saviq , yes snap-maas it the latest one that was missing. I had v1.4 with 2 other instances and 1.5 with another 2 instances that was lost. Back then I thought if I upgrade multipass it will be gone but didn't 😆 . 

I'll let you know if v1.6 also has this problem 😄 .
