### ISSUE TITLE
cannot launch instance on s390x

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#2063]
**Describe the bug**
Cannot launch VM on s390x. Error message mentions qemu-system-x86_64 which is wrong architecture in this case.

**To Reproduce**
```
$ sudo snap install multipass
multipass 1.6.2 from Canonical✓ installed
$ multipass launch 20.04 -n test
launch failed: Internal error: qemu-system-x86_64 failed getting vmstate (program: qemu-system-s390x; error: execve: No such file or directory) with output:
```

**Expected behavior**
Launch VM without any issue.

**Logs**
attached

**Additional info**
- OS: 21.04 dev on s390x
```
$ multipass version
multipass  1.6.2
multipassd 1.6.2
$ multipass info --all
```
**Additional context**
Tests before releasing 21.04

**Comment by Saviq** [comment]
Hi @marosg42 sorry, we're lacking some documentation here. You need to use the `lxd` driver for it to work: `sudo snap connect multipass:lxd lxd; sudo multipass set local.driver=lxd`.

We'll be moving to LXD as the default, soon.

Please reopen if that doesn't help.
