### ISSUE TITLE
Question: how to launch Ubuntu 21.04 instance?

### ISSUE THREAD

**Issue by linux-china** [canonical/multipass#2069]
I have multipass 1.6.2 installed. I execute `multipass find` and get following output: 

```
snapcraft:core18                              20201111         Snapcraft builder for Core 18
snapcraft:core20                              20201111         Snapcraft builder for Core 20
snapcraft:core                                20210416         Snapcraft builder for Core 16
18.04                       bionic            20210415         Ubuntu 18.04 LTS
20.04                       focal,lts         20210415         Ubuntu 20.04 LTS
20.10                       groovy            20210415.1       Ubuntu 20.10
```

Ubuntu 21.04 has been released today, and I want to do io_uring testing with Kernel 5.11 under Unbuntu 21.04.  Any idea to launch Ubuntu 21.04 with multipass?

**Comment by townsend2010** [comment]
Hi @linux-china,

21.04 has not been been officially released as a cloud-image yet.  I'm not exactly sure when they plan on releasing the official 21.04 cloud-image, but I imagine it will be soon.

**Comment by linux-china** [comment]
@townsend2010  a question, I can find  Ubuntu Cloud Images 21.04  on  https://cloud-images.ubuntu.com/hirsute/current/   If I download the image file into my disk, and how to run it with mulitpass?

**Comment by townsend2010** [comment]
@linux-china,

Right, that's the daily build of 21.04.  Looking at your `multipass find` output, it appears you are running Multipass on macOS and unfortunately, it's not [currently possible](#1024) to launch instances from a file.

**Comment by linux-china** [comment]
@townsend2010  you are kind and thanks for your explain.   :)

**Comment by Saviq** [comment]
@linux-china you should be able to `multipass launch 21.04` now :)

**Comment by linux-china** [comment]
@Saviq  did you use multipass Mac?  still no 21.04 found on Mac.

**Comment by Saviq** [comment]
Hi @linux-china, the image is out there, will be in our next Multipass release (due in a couple weeks).
