### ISSUE TITLE
[lxd] instance creation timeout too low

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2095]
https://github.com/canonical/multipass/blob/139481994133dc253163e6eb523f1a09455855ac/src/platform/backends/lxd/lxd_virtual_machine.cpp#L177

It may well take longer than the 30s given for LXD to prepare the image and create the instance. The error is also uninformative:

```plain
launch failed: The following errors occurred:
failed to determine IP address
```

**Comment by townsend2010** [comment]
A workaround was introduced in #2116.  The real fix is to somehow get time outs passed into the LXD instance creation.
