### ISSUE TITLE
Add info about mounting to `info` even if nothing is mounted to instance

### ISSUE THREAD

**Issue by flying-sausages** [canonical/multipass#2108]
**What are you trying to do?**
Figure out if an instance has mounts enabled and active or not

**What's your proposed solution?**
Add a "row" to `multipass info` which would say that there are no mounts present

**Additional context**
Info about mounts is _only_ shown when mounts are active. The "absence" of active mounts is on its own not necessarily evident when it is not shown. For a good while I was convinced there must be a different place to check if mounts are active or not, but I couldn't figure out where to check because nothing explicitly told me "There are no mounts active"

**Comment by Saviq** [comment]
To anyone wanting to contribute, the relevant code is here:

https://github.com/canonical/multipass/blob/89f73fb8debf41a496d1ab058308f9764cc038dc/src/client/cli/formatter/table_formatter.cpp#L96-L99

**Comment by surahman** [comment]
The proposed solution is the following output when mounts are unavailable:
```
Mounts:         --
```
