### ISSUE TITLE
[regression] LXD instances are deleted on daemon startup

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2121]
Due to 725713a81, all LXD instances are deleted on daemon start up.  This is due to LXD instances not having a path and as such, the `QFile::exists()` will always return `false` and the daemon will delete it.

**Comment by ricab** [comment]
WOops. Perhaps we should instead have a `VirtualMachine::verify_preconditions`. Are you working on this yet @townsend2010 ? Otherwise I'll assign myself.

**Comment by townsend2010** [comment]
Hey @ricab, yeah, I'm working on a fix.  Should have something up shortly.

**Comment by ricab** [comment]
Ack, thanks.
