### ISSUE TITLE
Enabled Multipass conflicts with Ubuntu 20 hotspot

### ISSUE THREAD

**Issue by LanVukusic** [canonical/multipass#2133]
**Description**
It seems that Ubuntu 20's hotspot clashes with Multipass hypervisor since I can't start the hotspot when Multipass runs in the background.

**To Reproduce**
* Reboot Ubuntu20 laptop with Multipass installed.  
* Try to enable Hotspot  
It will not work / it will be greyed out.
* quit Multipass  
* Enable hotspot (it now works)

** Expectations **
No conflicts between Multipass and Ubuntu's hotspot.

**Additional info**
multipass  1.6.2
multipassd 1.6.2

**Comment by townsend2010** [comment]
Hi @LanVukusic,

I indeed see this issue as you described.  However, upon further research, this is a bug in Gnome.  See https://askubuntu.com/questions/1236823/system-policy-prohibits-use-as-a-hotspot-when-trying-to-turn-on-wifi-hotspot/1239405#1239405 for the workaround.

I'm going to close this, but feel free to reopen if the workaround doesn't work for you.
