### ISSUE TITLE
multipass  Unable to start instance on windows 10

### ISSUE THREAD

**Issue by leganck** [canonical/multipass#2140]
**Describe the bug**
Describe what your problem is.
 
Version: multipass  1.6.2+win   multipassd 1.6.2+win

I use hyper-v, to start the instance normally when I boot. When I stop the instance and turn it on again,prompt me to "start failed: Multipass support for Hyper-V requires Windows 10".

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
windows 10 pro 19042
Version: multipass  1.6.2+win   multipassd 1.6.2+win

**Additional context**

**Comment by nikhiljohn10** [comment]
@leganck  You need to go to "Turn Windows features on or off" in "Programs and Features" from App Settings and turn on "Hyper-V" option and apply. After you restart your system, multipass will work.

I think you can close this now.

**Comment by Saviq** [comment]
@leganck does your username contain unicode characters by chance? Otherwise, could you please look in Event Viewer for any relevant errors? See https://multipass.run/docs/accessing-logs#windows for more details.

**Comment by leganck** [comment]
My problem is solvedm,Because I'm using the latest [PSReaderLine](https://github.com/PowerShell/PSReadLine) ,MultiPass works fine after PSReadline is uninstalled

**Comment by leganck** [comment]
> @leganck does your username contain unicode characters by chance? Otherwise, could you please look in Event Viewer for any relevant errors? See https://multipass.run/docs/accessing-logs#windows for more details.

No, My Windows user name is Leganck
