### ISSUE TITLE
Nothing happens after `multipass start kane`

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2143]
hey! i downloaded multipass and installed the image but when i write `multipass start kane`, nothing happens 
can someone tell me why this happens?

_Originally posted by @kane906 in https://github.com/canonical/multipass/issues/1372#issuecomment-866048199_

**Comment by Saviq** [comment]
@kane906 what do you mean "installed an image" and what do you expect to happen after `multiapss start kane`?

What's `multipass info --all` say?

**Comment by kane906** [comment]
it says
Name - kane
State -  Running
Ipv4 - Na
Release - Ubuntu 20.04.2 LTS
Image Hash - xxxxxxxxxxx]
Load - 000000000

**Comment by kane906** [comment]
but there is no screen showing ubuntu

**Comment by kane906** [comment]
thank you very much sir
