### ISSUE TITLE
Multipass should have a restart command next to start and stop

### ISSUE THREAD

**Issue by morphis** [canonical/multipass#217]
At times you really just want to restart a machine multipass manages. At the moment you have to do a `multipass stop my-machine && multipass start my-machine`. Having a short version of this as `multipass restart my-machine` would be pretty handy.

**Comment by morphis** [comment]
Doing a stop/start in our scripts right now. But yeah, exec would reduce that to a single line ;-)

**Comment by pekof** [comment]
I could do this

**Comment by Saviq** [comment]
@pekof great, looking forward to your PR!

**Comment by ricab** [comment]
Hi, I actually started working on this a couple of days ago. @pekof only now did I notice you had proposed doing the same thing, sorry about that.

**Comment by ricab** [comment]
@pekof again, I'm sorry about this, I did not announce I was working on the issue because I wanted to be sure I reached a solution prior to that. The issue was dormant for so long, I did not expect someone else to want to do the same, but I suppose it is a natural starter's choice. 

Anyway, I wanted to assure you I did not see your comment here and apologize for any inconvenience.

**Comment by pekof** [comment]
@ricab that was my first idea was to issue stop and start from client.
But that's not good solution because if client dies before issuing start machine would be stopped.
**restart** needs to be supported by server.

**Comment by ricab** [comment]
Hi @pekof, I see your point, but limiting changes to the client minimizes complexity by maximizing code reuse. By approaching restart as a pure combination of existing server functionality we can keep the server interface "as simple as possible, but no simpler". 

True, a client-contained restart lacks the transactional character, but that did not seem like a requirement for this issue. I am not sure how important it would be. But there is a benefit in having one command less to support in the server from now on.

**Comment by ricab** [comment]
Hi @pekof, are you still working toward a server-side solution? If so, I will leave it to you. Otherwise, please let me know.

**Comment by pekof** [comment]
@ricab I'm getting familiar with daemon side.
I can do that on another issue  if you want to solve this one.

**Comment by ricab** [comment]
Alright, sounds good. I'll have a look into this later on.
