### ISSUE TITLE
Multipass error: error while loading shared libraries: libQt5Core.so.5

### ISSUE THREAD

**Issue by njayakrishna** [canonical/multipass#2178]
I am getting an error when starting multipass using latest snapd. This is on Centos 7 platform:
Steps:

sudo yum install snapd
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap
~ > sudo snap install multipass
2021-07-19T18:37:23+05:30 INFO Waiting for automatic snapd restart…
multipass 1.7.0 from Canonical\u2713 installed

~ > multipass
/snap/multipass/5078/bin/multipass: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

Can you please help me how to overcome this error?

More info:
~ > uname -a
Linux 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

~ > sudo snap version
snap 2.51-1.el7
snapd 2.51-1.el7
series 16
centos 7
kernel 3.10.0-1160.31.1.el7.x86_64

~ > sudo snap info multipass
name: multipass
summary: Instant Ubuntu VMs
publisher: Canonical\u2713
store-url: https://snapcraft.io/multipass
contact: https://github.com/CanonicalLtd/multipass/issues/new
license: GPL-3.0
description: |
Multipass is a tool to launch and manage VMs on Windows, Mac and Linux that simulates a cloud
environment with support for cloud-init. Get Ubuntu on-demand with clean integration to your IDE
and version control on your native platform.

Launch an instance (by default you get the current Ubuntu LTS)

 multipass launch --name foo
Run commands in that instance, try running bash (logout or ctrl-d to quit)

 multipass exec foo -- lsb_release -a
Pass a cloud-init metadata file to an instance on launch

 multipass launch -n bar --cloud-init cloud-config.yaml
See your instances

 multipass list
Stop and start instances

 multipass stop
 multipass start
Get help

 multipass help
commands:

multipass.gui
multipass
services:
multipass.multipassd: simple, enabled, inactive
snap-id: mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking: latest/stable
refresh-date: today at 18:50 IST
channels:
latest/stable: 1.7.0 2021-07-19 (5078) 324MB -
latest/candidate: 1.7.0 2021-07-19 (5078) 324MB -
latest/beta: \u2191
latest/edge: 1.7.0-dev.1049+g4a4a7710 2021-07-10 (5048) 324MB -
installed: 1.7.0 (5078) 324MB -

**Comment by njayakrishna** [comment]
Looks like libQt5Core.so uses Linux kernel 3.17.0, but Centos 7 uses linux kernel 3.10 and hence not compatible? Please correct me if I am wrong. Thanks.

~ > uname -a
Linux 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

~ > find -L /var/lib/snapd/snap/multipass*/*/usr/lib/*-linux-gnu -type f -iname 'libQt5Core.so*' -print0 2>/dev/null | xargs -0 -I{} file '{}' | grep -Z 'ELF' | grep -Z 'for GNU/Linux ' | sort -z -fuV | grep -Z -Eva 'for GNU/Linux (2\.6\.[0-9]+|3\.2\.0)'

/var/lib/snapd/snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=e54a6cea97c3942fbcec1973574545fb3ad74015, for **GNU/Linux 3.17.0**, stripped
/var/lib/snapd/snap/multipass/current/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=e54a6cea97c3942fbcec1973574545fb3ad74015, for **GNU/Linux 3.17.0**, stripped

**Comment by Saviq** [comment]
Hi @njayakrishna, I can't be certain that things will work otherwise with this old kernel and such, but no, what you found I don't think is the problem.

Can you post the output of:

```plain
$ snap run --shell multipass.multipassd
# then, inside the new shell
$ ldd $SNAP/bin/multipassd | grep libQt
        libQt5Network.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f6d35513000)
        libQt5Gui.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f6d34b9a000)
        libQt5DBus.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f6d34a7f000)
        libQt5Core.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f6d34534000)
```

**Comment by njayakrishna** [comment]
~ > snap run --shell multipass.multipassd
~ >  ldd $SNAP/bin/multipassd | grep libQt
	libQt5Network.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f523bb6f000)
	libQt5Gui.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f523b1f6000)
	libQt5DBus.so.5 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f523b0db000)
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found

**Comment by Saviq** [comment]
> libQt5Core.so.5 => not found

So yeah, that's the problem. Does the file not exist?

```plain
$ ls /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
$ snap run --shell multipass.multipassd ldd /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

**Comment by njayakrishna** [comment]
The lib does exist:




~ > ls /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
/snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5@
~ > snap run --shell multipass.multipassd ldd /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
	linux-vdso.so.1 (0x00007ffd0c7cc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7d00771000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7d00755000)
	libicui18n.so.66 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007f7d00456000)
	libicuuc.so.66 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f7d00270000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7d0026a000)
	libpcre2-16.so.0 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007f7d001e5000)
	libdouble-conversion.so.3 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007f7d001cf000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f7d000a6000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7cffec5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7cffd76000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7cffd5b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7cffb67000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7d00d02000)
	libicudata.so.66 => /snap/multipass/5078/usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f7cfe0a6000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f7cfe033000)

**Comment by Saviq** [comment]
While in a `snap run --shell ...`, can you please see if you can tweak `LD_LIBRARY_PATH` so that Qt5Core gets found? It's unlikely, since other libs are found in that location...

It seems to me that the "File not found" error is actually hiding some incompatibility between Qt5Core and your kernel indeed.

**Comment by Saviq** [comment]
And this would confirm:

https://stackoverflow.com/questions/49449748/ldd-cannot-find-library

**Comment by Saviq** [comment]
You'll just have to upgrade to something more recent.

**Comment by njayakrishna** [comment]
It looks like kernel being old. The LD_LIBRARY_PATH seems fine. Thanks for you help. I will upgrade.

~> echo $LD_LIBRARY_PATH 
/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/multipass/5078/lib:/snap/multipass/5078/lib/x86_64-linux-gnu:/snap/multipass/5078/usr/lib:/snap/multipass/5078/usr/lib/x86_64-linux-gnu:/snap/multipass/5078/lib:/snap/multipass/5078/usr/lib:/snap/multipass/5078/lib/x86_64-linux-gnu:/snap/multipass/5078/usr/lib/x86_64-linux-gnu

**Comment by iamajohn** [comment]
I am facing this issue even with the latest kernel as well. Reopening this bug:
`# uname -r
3.10.0-1160.62.1.el7.x86_64

# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

# snap --version
snap    2.54.4-1.el7
snapd   2.54.4-1.el7
series  16
centos  7
kernel  3.10.0-1160.62.1.el7.x86_64`

`# multipass launch -n test1
/snap/multipass/6130/bin/multipass: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

# snap run --shell multipass.multipassd
bash-5.0# ldd $SNAP/bin/multipassd | grep libQt
	libQt5Network.so.5 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f3b28ba4000)
	libQt5Gui.so.5 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f3b2822b000)
	libQt5DBus.so.5 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f3b28109000)
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found

bash-5.0# echo $LD_LIBRARY_PATH
/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/multipass/6130/lib:/snap/multipass/6130/lib/x86_64-linux-gnu:/snap/multipass/6130/usr/lib:/snap/multipass/6130/usr/lib/x86_64-linux-gnu:/snap/multipass/6130/lib:/snap/multipass/6130/usr/lib:/snap/multipass/6130/lib/x86_64-linux-gnu:/snap/multipass/6130/usr/lib/x86_64-linux-gnu

bash-5.0# ldd /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
	linux-vdso.so.1 (0x00007ffc780ff000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1ccbff5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1ccbfd9000)
	libicui18n.so.66 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007f1ccbcda000)
	libicuuc.so.66 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f1ccbaf4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1ccbaee000)
	libpcre2-16.so.0 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007f1ccba69000)
	libdouble-conversion.so.3 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007f1ccba53000)
	libglib-2.0.so.0 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f1ccb92a000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1ccb748000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1ccb5f9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1ccb5de000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1ccb3ea000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1ccc568000)
	libicudata.so.66 => /snap/multipass/6130/usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f1cc9929000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f1cc98b6000)`

**Comment by townsend2010** [comment]
Hi @iamajohn,

According to your output, you are running an older incompatible kernel as it's based off of 3.10.  Unfortunately, you need a newer version of CentOS with a newer kernel.

**Comment by iamajohn** [comment]
@townsend2010 I am using the latest available kernel version in CentOS 7.9
If possible can you specify which kernel version should i use?

**Comment by townsend2010** [comment]
@iamajohn,

I'm not sure about the exact CentOS kernel version, but looking at the `file` info for `libQt5Core.so.5.12.8` which is in the Multipass snap, it needs to be at least kernel version 3.17.

You might be able to install a newer kernel following the instructions at https://phoenixnap.com/kb/how-to-upgrade-kernel-centos.

**Comment by iamajohn** [comment]
@townsend2010 Sweet!!
Thank you for this info. I hope this will help 🙌

**Comment by molo76** [comment]
> @iamajohn,
> 
> I'm not sure about the exact CentOS kernel version, but looking at the `file` info for `libQt5Core.so.5.12.8` which is in the Multipass snap, it needs to be at least kernel version 3.17.
> 
> You might be able to install a newer kernel following the instructions at https://phoenixnap.com/kb/how-to-upgrade-kernel-centos.

This worked for me. Thanks!
