### ISSUE TITLE
[workflows] Add ability to specify which architecture(s) the Workflow will run on

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2181]
Some Workflows may only run on specific architectures such as `amd64`.  In preparation for Apple M1 support, a definition needs to be added to the Workflows to specify the architecture(s) it runs on such as:
```yaml
runs-on:
- amd64
```

**Comment by ricab** [comment]
How about we make the name a bit more general, so that it can be used to express other preconditions we may need in the future? I am thinking maybe `requires` instead of `runs-on`. WDYT?

**Comment by Saviq** [comment]
> How about we make the name a bit more general, so that it can be used to express other preconditions we may need in the future? I am thinking maybe `requires` instead of `runs-on`. WDYT?

How do you express `OR` in such a situation? I mean, I've just [submitted a fix](https://github.com/canonical/multipass-workflows/pull/2) for the `minikube` workflow that makes it work on all arches (upstream permitting).

IMO architectures warrant a dedicated field. I'm not married to `runs-on:` FWIW.

**Comment by ricab** [comment]
Hmm, right, I see your point. I guess I thought `runs-on` was kind of half-way: it seems to afford "windows" or "hyperkit" values if we want to add them. But I see generic fields are prone to this `OR`/`AND` ambiguity.

So yeah, I think you're right. We can always extend the YAML with new fields for any preconditions we may need. But then should we actually be *more specific* and clearly identify that it is an architecture that this field expects (perhaps `arch`)? 

I guess we need a specific enough field that its values are mutually exclusive. Then only `OR` makes sense, so it is implied (you can't have an "ARM AND x86" use-case, but you can have "ARM AND macOS"`).
