### ISSUE TITLE
Multipass with Dynamic Memory reports free memory mostly used

### ISSUE THREAD

**Issue by mconner** [canonical/multipass#2182]
**Describe the bug**
When creating a VM, it uses Dynamic Memory under Hyper-V. After a while, free and other utilities report that most memory is in use.

**To Reproduce**
Windows 10 (running GitBash):

**Create a vm on windows 10 with Hyper-V using:**
`multipass launch --name dar01 --mem 6G --disk 80G --cpus 3`
This creates a VM using dynamic memory. 

If I then shell into it and do a free -m, at first I see:
```
ubuntu@dar01:~$ free
              total        used        free      shared  buff/cache   available
Mem:        6060056      241520     5514856        1044      303680     5574360
Swap:             0           0           0
```
However, after about 4 minutes, I get:
```
ubuntu@dar01:~$ free
              total        used        free      shared  buff/cache   available
Mem:        6060056     5200232      556128        1044      303696      615636
Swap:             0           0           0
```
That is, it reports as mostly used.  top and htop report similar values, though if I add up the resident memory of the processes reported in top, they do not add up to anywhere near the supposed used memory.

If I stop the vm, `multipass stop dar01`, and then in Hyper-V Manager, disable Dynamic Memory, I do _not_ have this problem. 

**Expected behavior**
The used memory should report the same, whether the vm is configured for dynamic or static.

**Logs**
I tried exporting the event logs as csv, but the upload says it doesn't support it (then lists csv as allowed type), so changed it to .txt.
[multipass-events-dynamic-mem.csv.txt](https://github.com/canonical/multipass/files/6865378/multipass-events-dynamic-mem.csv.txt)

**Additional info**
 - OS: Windows 10 Enterprise
 - $ multipass --version
multipass  1.6.2+win
multipassd 1.6.2+win
- 
- $ multipass info --all

Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     075cbdf6b7d1 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         C:/Users/mike.conner => Home
                    UID map: -2:default
                    GID map: -2:default

Name:           dar01
State:          Running
IPv4:           172.17.10.228
Release:        Ubuntu 20.04.2 LTS
Image hash:     b03047b147b6 (Ubuntu 20.04 LTS)
Load:           0.01 0.01 0.00
Disk usage:     1.4G out of 77.4G
Memory usage:   243.1M out of 5.8G

**Additional context**

**Comment by luis4a0** [comment]
Hi @mconner,

Thanks for your report. When using dynamic memory, it is managed by Hyper-V and the instance's kernel. The amount of memory reported inside the instance does not necessarily match the real allocation the hypervisor does. I won't see this as a bug unless it really affects the performance.

On the other hand, we have requests to control dynamic memory, https://github.com/canonical/multipass/issues/604. And maybe it makes sense for us to disable it at all.

HTH!

**Comment by luis4a0** [comment]
I'm closing this, but #604 remains anyway open.
