### ISSUE TITLE
Multipass snap cannot store data in mounted folder

### ISSUE THREAD

**Issue by shabiel** [canonical/multipass#2184]
**Describe the bug**
Followed the instruction here: https://github.com/canonical/multipass/pull/1789 to change where multipass stores its virtual machines. However, the snap cannot access the directory that I want it to use.

**To Reproduce**
How, and what happened?
```
snap stop multipass
snap connect multipass:removable-media  
snap connect multipass:all-home
mkdir -p /extra/multipass-files/
mkdir /etc/systemd/system/snap.multipass.multipassd.service.d/
tee /etc/systemd/system/snap.multipass.multipassd.service.d/override.conf <<EOF
[Service]
Environment=MULTIPASS_STORAGE=/extra/multipass-files/
EOF
systemctl daemon-reload
snap start multipass
exit # root
```

**Expected behavior**
Multipass doesn't work.

**Logs**
```
Caught an unhandled exception: unable to create directory '/extra/multipass-files/cache'
```

**Additional info**
 - OS: Ubuntu 20.04.2 LTS
- multipass  1.7.0
- Multipass currently inoperative; cannot give you `info --all`.

**Comment by Saviq** [comment]
@shabiel I'm afraid that's by design. If you `snap connect multipass:removable-media`, you'll be able to use external drives. See https://snapcraft.io/docs/removable-media-interface for details.

By default, you can use `/home/*`.

**Comment by shabiel** [comment]
Thank you.

**Comment by andrealcantara** [comment]
i try make a folder /extra/multipass-files/ chmod 777 and work.
