### ISSUE TITLE
Lost ssh connection to running instance

### ISSUE THREAD

**Issue by abstract-thinking** [canonical/multipass#2187]
**Describe the bug**

Can not reach multipass instance anymore over ssh.

`multipass list`
Name                    State             IPv4             Image
primary                 Stopped           --               Ubuntu 20.04 LTS
playbox                 Running           N/A              Ubuntu 20.04 LTS

**To Reproduce**
1. `multipass shell playbox`
shell failed: [ssh client] channel creation failed: ''

**Expected behavior**

I would expect that I can login on the instance over shell or hopefully another way..

**Logs**
Added windows event log.

**Additional info**
 - OS: Windows 10
- `multipass version`
multipass  1.7.0+win
multipassd 1.7.0+win
- `multipass info --all`
info failed: [ssh proc] failed to open session channel: ''

**Additional context**
I installed VirtualBox and then multipass. Now it worked one week. Unfortenately Windows made some updates and the instance playbox was still running. Now the connection to the box seems to be lost (Primary works but this was in the state stopped and not running. After googling around I'm afraid that the data are lost on playbox.

**Comment by Saviq** [comment]
Hi @abstract-thinking, have a look at this:

https://multipass.run/docs/using-virtualbox-in-multipass-windows

You should be able to access the VM, see if it boots at all. You can also hook the drive up to another instance launched and recover from there.

Note you may want to stop the Multipass icon on your system tray as VirtualBox has some weird locking around different clients accessing the same instance.

**Comment by abstract-thinking** [comment]
Hey @Saviq, thanks a lot.

I was able to stop the box but then I could not restart it.

I gave up and reinstalled Multipass.
