### ISSUE TITLE
Every time I ignore the multipass for windows update prompt, it queues an additional event handler. All of them fire at once when I actually click it

### ISSUE THREAD

**Issue by parktheredcar** [canonical/multipass#2188]
**Describe the bug**
On windows, multipass update notifier is opening the github releases page many times when I click the update notification prompt - one tab for every time I didn't click it previously.

**To Reproduce**
How, and what happened?
1.  Install multipass for windows
2. Wait for a new release and ignore the update prompt notification
3. Maybe ignore the notification when it pops up a few more times. Keep count of how many times you ignored it (N times)
4. Finally, click the update notification. It opens the same multipass github releases page in N duplicate tabs
5. Close all the extra tabs

**Expected behavior**
Clicking the update notification one time opens one single tab.

**Logs**
n/a
**Additional info**
Windows 10 20H2

**Additional context**
n/a

**Comment by Saviq** [comment]
Hi @parktheredcar, you should never ignore it, then! ;)

But for real, I believe the issue is that we indeed connect the action multiple times, we need to disconnect first:

https://github.com/canonical/multipass/blob/2126b95a23af6d7c97457d0c08fd47392bfe6a56/src/client/gui/gui_cmd.cpp#L252-L253

**Comment by surahman** [comment]
@Saviq I was poking around the documentation and found a method to [check if a signal is connect](https://doc.qt.io/qt-5/qobject.html#isSignalConnected):
```c++
        const auto connection_check = QMetaMethod::fromSignal(&QSystemTrayIcon::messageClicked);
        if (!isSignalConnected(connection_check))
        {
            QObject::connect(&tray_icon, &QSystemTrayIcon::messageClicked,
                             [this] { QDesktopServices::openUrl(QUrl(update_action.whatsThis())); });
        }
```
I am not sure if this will alleviate the issue.

**Comment by Saviq** [comment]
@surahman thanks, that indeed looks like it will do the trick, can you put up a PR and we can take it from there?
