### ISSUE TITLE
Bridging not working on Windows with VirtualBox

### ISSUE THREAD

**Issue by LosBagros** [canonical/multipass#2189]
**Describe the bug**
I don't know how to assign ipv4 adress to bill.
In docs is nothing about it.

**Additional info**
 - OS: Windows 10
- Virtualbox

![image](https://user-images.githubusercontent.com/45005533/127932350-205cb891-4314-4431-bafc-49b0d4881f22.png)

**Comment by Saviq** [comment]
Hi @LosBagros, with VirtualBox you need to add a bridged network interface, as VirtualBox's networking doesn't allow for communication between the host and instance.

See https://multipass.run/docs/additional-networks for more details.

I'll close, please reopen if something else is at fault.

**Comment by LosBagros** [comment]
OK, what should I do?
![image](https://user-images.githubusercontent.com/45005533/127981288-223522c3-c712-426e-9751-059be375d428.png)

**Comment by Saviq** [comment]
To `launch --network` you need to pass the _Name_ of the network listed in `multipass networks`:

```powershell
PS > multipass launch --network "Ethernet 2"
```

**Comment by LosBagros** [comment]
That didn't work
![image](https://user-images.githubusercontent.com/45005533/127986839-3037f394-0758-4ea2-bf0c-c713ac37a580.png)

**Comment by Saviq** [comment]
OK that _should_ work. I'll reopen and repurpose the issue then.

**Comment by ricab** [comment]
Hi @LosBagros, what does `ip -br link` say inside the instance? Do you have a firewall that could be blocking DHCP?

**Comment by LosBagros** [comment]
i deleted multipass and virtualbox, than restarted pc, than I installed agan and now it is working
