### ISSUE TITLE
Downloaded image hash does not match 

### ISSUE THREAD

**Issue by ChinYikMing** [canonical/multipass#2194]
`$ multipass launch --name foo`
`launch failed: Downloaded image hash does not match`

I have tried the steps in [link](https://github.com/canonical/multipass/issues/1714), but still not work

**Additional info**
 - `OS: popOS 21.04`
- `multipass version: 1.7.0`

**Comment by Saviq** [comment]
Hi @ChinYikMing did you manage to resolve your problem? It usually suggests something between you and the image hosts, like a proxy that gives up different versions of images.

**Comment by Saviq** [comment]
Duplicate of #2172

**Comment by ChinYikMing** [comment]
I simply reinstall the multipass on the next day, then it works... kind of weird, thanks
