### ISSUE TITLE
Daemon bails on start when starting an instance fails

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2197]
When the daemon starts and there are instances to start, if the instance fails to start, Qt will complain about an exception being thrown in an even handler, and then the daemon complains about an unhandled exception and then bails.  This leaves the daemon in an unstartable state.

**Comment by Saviq** [comment]
The relevant piece of code is here:

https://github.com/canonical/multipass/blob/a24cc2cf2547d1852e97538969f2852ca6e16f0b/src/daemon/daemon.cpp#L984-L987

The `->start()` likely needs wrapping in a try-catch block, with a custom non-fatal exception caught from backends.

**Comment by Saviq** [comment]
And a good exception candidate:

https://github.com/canonical/multipass/blob/a24cc2cf2547d1852e97538969f2852ca6e16f0b/include/multipass/exceptions/start_exception.h#L26-L41

Backends need reviewing for throwing that exception and potentially converting more generic ones into this one, where applicable.
