### ISSUE TITLE
Windows and Mac 1.7 release should support 21.04

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2201]
The 1.7 release for Windows and Mac should allow launching 21.04 instances.  We missed this in the release.

**Comment by Anand-Moghe** [comment]
I am unable to figure out how to install multipass on Windows. Could not find a link to installer or exe on the github page.

**Comment by Anand-Moghe** [comment]
OK. Found it ! the assets were collapsed, and the installer was hidden.

**Comment by Saviq** [comment]
Fixed in [v1.7.2](https://github.com/canonical/multipass/releases/tag/v1.7.2).
