### ISSUE TITLE
Mac OSX for Multipass 

### ISSUE THREAD

**Issue by book-s** [canonical/multipass#2211]
Last login: Sun Aug 22 00:17:32 on ttys001
/var/folders/7w/sls739ln7fxbg5kszp7mn6br0000gn/T/multipass-gui.fUxKIj.command ; exit;
apple@zhanglikaideMacBook-Pro ~ % /var/folders/7w/sls739ln7fxbg5kszp7mn6br0000gn/T/multipass-gui.fUxKIj.command ; exit;

[2021-08-22T00:25:10.164] [error] [primary] Could not unregister VM: execvp: No such file or directory
launch failed: Could not generate a new UUID: execvp: No such file or directory 
Saving session...                                                               
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Saviq** [comment]
@book-s it looks like you're using the VirtualBox backend? Do you have VirtualBox installed, and `VBoxManage` on your `PATH`?

If you don't require VirtualBox, change back with `sudo multipass set local.driver=hyperkit`.

See https://multipass.run/docs/using-virtualbox-in-multipass-macos for more details.

Please reopen if none of this helps.

**Comment by book-s** [comment]
`sudo multipass set local.driver=hyperkit`
Problem solving

thanks！！1
