### ISSUE TITLE
`multipass find` return find failed: Operation canceled

### ISSUE THREAD

**Issue by taicaile** [canonical/multipass#2212]
Hello, the `multipass find` command return error `find failed: Operation canceled`.

```bash
>>> multipass version
multipass  1.7.1
multipassd 1.7.1
```

multipass find -vvvv didn't provide more info.

May I know the possible reason?

**Comment by ricab** [comment]
Hi @taicaile, it's hard to say without a little more info. What does the daemon log say? Is the machine online? Any firewall in play? What OS are you in? Does a daemon restart help? What happened before that? Any specific steps to reproduce?

**Comment by taicaile** [comment]
> Hi @taicaile, it's hard to say without a little more info. What does the daemon log say? Is the machine online? Any firewall in play? What OS are you in? Does a daemon restart help? What happened before that? Any specific steps to reproduce?

Hello,

Here are some logs:

```bash
>> journalctl --unit snap.multipass*
Aug 23 09:49:21 li multipassd[332283]: Checking for images to update…
Aug 23 11:57:51 li multipassd[332283]: "No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnectio>
Aug 23 12:01:10 li multipassd[332283]: "No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnectio>
Aug 23 12:02:42 li multipassd[332283]: "No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnectio>
Aug 23 15:49:21 li multipassd[332283]: Checking for images to update…
```

The machine is online, and the lxc container is working, can download image.

No firewall.

I am using Ubuntu 20.04 LTS.

`multipass restart` is not successful
```bash
>> multipass restart -v
restart failed: The following errors occurred:                                  
instance "primary" does not exist
```

I don't know how to reproduce it, it is my first time to install multipass and it reports this error.

**Comment by ricab** [comment]
You can restart the multipass daemon with `snap restart multipass`. If you wait for ~10 sec after that and issue another `multipass find`, what does it say?

**Comment by taicaile** [comment]
> You can restart the multipass daemon with `snap restart multipass`. If you wait for ~10 sec after that and issue another `multipass find`, what does it say?

Hello, it is working now.

Thank you.
