### ISSUE TITLE
Wrong parameter parsing

### ISSUE THREAD

**Issue by luis4a0** [canonical/multipass#2224]
**Describe the bug**
Issuing `multipass launch -n asdf -mem 2048M` gives
```
launch failed: '2048M' is not a supported alias. Please use `multipass find` for supported image aliases.
```

**Expected behavior**
`-mem` should be recognized as a wrong parameter, _before_ checking the validity of `2048M` as an alias.

**Comment by townsend2010** [comment]
Hey @luis4a0,

Thanks for entering this.  For the expected behavior, I'm not sure if this is what you meant, but `-mem` itself is itself a valid option (the `-m` part of it is the option), it's just that `em` is not a valid memory size and that is what needs to be validated.  Same goes for all other options.

For example, it's possible someone may enter `-cpus` and that would be parsed as `-c` with `pus` being the number of CPUs given at launch.

**Comment by luis4a0** [comment]
The fact that `-mem` is a valid option escaped me. Thanks for pointing this out!

Now I see it's not a trivial fix. We need to parse in two stages (analogous to lex and yacc): first we generate tokens from all the options in the command line (that is, one for each unit separated by spaces) and then we parse the those tokens, combined in the order given. Maybe there is a simpler way to do it, I'll think about it.

**Comment by townsend2010** [comment]
Hey @luis4a0, ok, cool.

It should actually be quite trivial to fix.  In `validate_create_arguments()`, instead of calling `validate_image()` early, call it after all of the other options have been validated. :wink:

**Comment by ricab** [comment]
Perhaps this could be dealt with in the client: confirm it is a valid MemorySize before adding it to the request. That's already done for CPUs.

**Comment by luis4a0** [comment]
Thanks for your insights @townsend2010 and @ricab! I implemented the latter, it proved to be easier. In fact, I didn't remove check code for the daemon because it is still needed to check that the requested size is bigger than the minimum.

**Comment by Saviq** [comment]
> I didn't remove check code for the daemon

You also can't _trust_ the client to have done the validation :)

**Comment by ricab** [comment]
> > I didn't remove check code for the daemon
> 
> You also can't _trust_ the client to have done the validation :)

Yep, the daemon of course needs to validate the contents of RPC requests (to be sure, I did not mean to suggest otherwise).
