### ISSUE TITLE
Multipass starts a scope every 2 seconds

### ISSUE THREAD

**Issue by oskarvid** [canonical/multipass#2232]
**Describe the bug**
Every two seconds multipass writes an entry in `/var/log/syslog` of this format:  
`Sep 10 15:17:35 hostname systemd[1798]: Started snap.multipass.multipass.9977d1eb-0cc3-49d2-8cf1-0b90ab7e9a2c.scope.
Sep 10 15:17:35 hostname systemd[1798]: snap.multipass.multipass.9977d1eb-0cc3-49d2-8cf1-0b90ab7e9a2c.scope: Succeeded.`

**To Reproduce**
1. Install multipass
1. Check `/var/log/syslog`

**Expected behavior**
Multipass should start the scope once and for all instead of every 2 seconds. 

**Logs**
Here's the log from journalctl: https://pastebin.com/KVr2rXKW
Here's part of the syslog: https://pastebin.com/7cThwisd

**Additional info**
- OS: Ubuntu 20.04.3
- `multipass version`: 1.7.1
- `multipass info --all`: This only returned an empty line

**Comment by luis4a0** [comment]
Hi @oskarvid, thanks for the report.

One possibility is that you updated the snap and the old GUI is still running. In that case, you can just quit the GUI and start it again from the applications menu.

Other possibility is that you have some script running, which polls Multipass each two seconds (like `watch -n2 multipass list`). In that case, this script is the cause of your issue.

Hope this helps!

**Comment by oskarvid** [comment]
Looks like I was running `watch multipass list`, thanks for the support and a great tool!
