### ISSUE TITLE
Issuing `exec` on a non-running instance should automatically start the instance

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2236]
If I execute an alias on an instance and that instance is not running, I would expect the instance to be automatically started and then the alias executes.  A message should be printed out saying what is happening.

**Comment by luis4a0** [comment]
Hey @townsend2010!

The alias execution is currently defined as a shortcut to `exec`. `exec` itself does not start the VM. Your thought makes sense, and I think we could add a parameter to `exec` indicating that the VM should be started, and use that when executing an alias. WDYT?

**Comment by townsend2010** [comment]
Yeah, I think adding it to `exec` makes sense.  We try to be nice to the user, so aside from aliases, if a user tries `exec`ing something, they most likely intend to have the instance running, so we can do that for them :smile: 

I'll change the title of this to reflect `exec`.

**Comment by luis4a0** [comment]
I think starting the VM must not be the default, in order to be consistent with older versions. I'd add a flag like `exec --start`.

**Comment by townsend2010** [comment]
Not sure I understand why you think it can't be the default?  I don't see how doing so would break anything.

**Comment by luis4a0** [comment]
The scenario I thought of is a script which takes some action if a VM is stopped, otherwise it runs the command. Is this unlikely to happen?

**Comment by townsend2010** [comment]
Well, the only thing I can think of in a script running `exec` would be that if it failed due to the instance not running, it would in turn start the instance and our change would do that for them, but it shouldn't break their script.

**Comment by townsend2010** [comment]
I really don't think it makes any sense.  I can't think of a scenario where a user/script that runs `exec` would want the instance to not be running.  That would be insanity! :laughing:

**Comment by luis4a0** [comment]
Ok, so we silently change the behavior of `exec`, making it start the VM if it's stopped.

@ricab @Saviq Are you OK with this?

**Comment by Saviq** [comment]
+1 from me, the intention is clear - of they only want to `exec` if it's started already, best check the instance state anyway

**Comment by ricab** [comment]
Makes sense to me. 

For the record, and as in other cases, I am only unsure of the impact on versioning. We never specified whether the instance had to be running for `exec`, but we did error out saying so. IOW, this effectively changes pre/post conditions in part of our interface.

**Comment by TwoLeggedCat** [comment]
> I really don't think it makes any sense.  I can't think of a scenario where a user/script that runs `exec` would want the instance to not be running.  That would be insanity! :laughing: 

What about a script that performs a final action before shutting down an instance like notifying another server or stopping a process in a way that a shutdown wouldn't accomplish? I can see someone `exec`ing that and not wanting the instance to start. I'm not saying it can't change, but, IMHO, there should be an option to retain the old behavior.

**Comment by luis4a0** [comment]
Should we add a timeout for starting the instance? Do we need to add a `--timeout` argument to the `exec` command on the RPC ot just use the default timeout?

**Comment by Saviq** [comment]
@luis4a0 I don't think we can sanely solve this. `exec --timeout …` sounds like it would limit the execution time. So a `--start-timeout` would make more sense. But then you still can't provide it for aliases.

IMO this should be solved by way of a configurable default timeout instead.

**Comment by luis4a0** [comment]
Thanks @Saviq, configurable timeout looks like the right thing to do. But in another PR though.

**Comment by luis4a0** [comment]
Hi @TwoLeggedCat, I think it's an unlikely scenario. As suggested earlier, it's possible to check if the instance is running before `exec`.
