### ISSUE TITLE
3D acceleration / failed to open the GUI

### ISSUE THREAD

**Issue by suikei-wang** [canonical/multipass#2244]
**Describe the bug**
I tried to use multipass to build my ROS system. However, when I built the Gazebo interface GUI, it failed. I googled and they said in VM, we can disable the 3D acceleration to solve this problem. However, I couldn't find the option for 3D acceleration in mlutipass. Is there any way to disable the 3D acceleration so that I can run my GUI? Thanks!

**Additional info**
 - OS: macOS 11.4
- `multipass version` 1.7.0+mac
- `multipass info --all` 
Name:           lucid-calf
State:          Running
IPv4:           192.168.64.4
Release:        Ubuntu 20.04.3 LTS
Image hash:     10f8ae579fbf (Ubuntu 20.04 LTS)
Load:           0.00 0.15 0.28
Disk usage:     4.9G out of 11.5G
Memory usage:   160.2M out of 981.3M
Mounts:         /Users/sukays/ros_workspace => /Users/sukays/ros_workspace
                    UID map: 501:default
                    GID map: 20:default

**Comment by luis4a0** [comment]
Hi @suikei-wang,

Multipass doesn't support at the moment video output. Thus, there is 3D acceleration. If you want video output, you can use X forwarding (as explained [here](https://discourse.ubuntu.com/t/stand-alone-windows-in-multipass/16340)) or using Mir and EGMDE (like [here](https://discourse.ubuntu.com/t/a-simple-gui-shell-for-a-multipass-vm/20439)).
