### ISSUE TITLE
Please support vmware fusion backend for multipass

### ISSUE THREAD

**Issue by gilbahat** [canonical/multipass#2245]
**What are you trying to do?**
I am trying to use multipass with vmware fusion backend

**What's your proposed solution?**
Develop the necessary support to run multipass using vmware backend

**Additional context**
VMware fusion is a commercial virtualization solution for MacOS. While expensive, it offers performance benefits over virtualbox and hyperkit. In particular in light of significant issues with hyperkit experienced by docker users (https://github.com/docker/for-mac/issues/5116), it may be a good idea to offer additional high-performing backends as an alternative.

**Comment by Saviq** [comment]
Hi @gilbahat, we're unlikely to add VMWare support any time soon, unless it proves to be significantly better in some respects.

In https://github.com/canonical/multipass/issues/1857#issuecomment-918362245 we're adding macOS support through QEMU using the native [Apple Hypervisor.framework](https://developer.apple.com/documentation/hypervisor). With hyperkit receiving so little work, we're most likely to replace it with QEMU altogether.

Do you have any particular issue with Multipass's hyperkit backend? Could you try if using the QEMU driver with this version helps?

https://multipass-ci.s3.amazonaws.com/pr403/multipass-1.8.0-dev.832.pr403%2Bgf82d7995.mac.x86_64-Darwin.pkg

You need to `sudo multipass set local.driver=qemu` to use it (you won't lose any hyperkit or virtualbox instances).

**Comment by gilbahat** [comment]
I'll be happy to try.
Overall the hyperkit experience has become worse as time goes and it has made docker desktop unusable for me (as the reports in the linked bug go).
I'd rather not find myself out of options should this regression start impacting multipass as well.

Using minikube, I have seen better performance under vmware (and parallels) compared to other backends, but (admittedly) not necessarily worth pursuing unless something bad happens with multipass as well.

**Comment by Saviq** [comment]
I'm going to close this for now. We don't plan to add VMware support, and it's unclear whether there's any advantage in doing so.
