### ISSUE TITLE
Launch failed: Operation canceled after interrupting image download

### ISSUE THREAD

**Issue by nav9** [canonical/multipass#2288]
**Describe the bug**
Ran `multipass launch --name node1`. It started downloading Ubuntu. I realised I already had an Ubuntu ISO on disk, so pressed Ctrl+C to stop the download. Since then, everytime I try running the same command, I get the error `Launch failed: Operation canceled`.  
How could you guys not allow us to use a local ISO? And once an operation is canceled, why wont you allow it to work again?

**Additional info**
 - OS: Ubuntu 20.04.1
- `multipass version 1.7.1`

**Comment by nav9** [comment]
Thank you. So it would help to add the following string to the error message "Please run `snap restart multipass` to try again.

**Comment by nzagorsky** [comment]
Can confirm similar behavior on MacOS. There is no snap so I'm not sure what to restart.

**Comment by JSC0DE** [comment]
Thanks @nav9 for the multipass service restart workaround. 

@nzagorsky for macOS the commands are: 

```
sudo launchctl stop com.canonical.multipassd
sudo launchctl start com.canonical.multipassd
```

**Comment by luojia65** [comment]
Can reproduce on windows. Anyone have workarounds? :)

**Comment by Saviq** [comment]
@luojia65 if you're still stuck, a `Restart-Service Multipass` should help.

**Comment by awaissaeedforenax** [comment]
On windows, restarting Multipass service from Task Manager resolved my issue.

**Comment by thanhminhmr** [comment]
Can confirm that this is currently still a problem in Ubuntu 20.04.3 LTS and lastest snap of multipass.

**Comment by townsend2010** [comment]
Hi @nottrobin,

We are currently in the process of the getting the 1.9 release out which includes this fix.  If you'd like to ~~test~~ try the release candidate, you can do `$ snap refresh multipass --beta`.

Hopefully, we will officially release 1.9 soon.
