### ISSUE TITLE
[snap] auto-refresh wreaking havoc if kill time out hits

### ISSUE THREAD

**Issue by Airren** [canonical/multipass#2316]
All the vms became UNKNOW status.
![image](https://user-images.githubusercontent.com/14846116/139187270-7206dc7d-8436-45e0-953d-1bbf125cf77f.png)

I try to modify this file, reset the status of vms.
`sudo vi /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json`
and set "machine_type" to "pc-i440fx-bionic" for the broken instance, and then I start one of the instances.

1. start one instance
![image](https://user-images.githubusercontent.com/14846116/139187669-e02025fe-94a9-4f2b-814d-a7d536088183.png)

2. the log of multipassd, in the log is waiting for ssh to be up.

![image](https://user-images.githubusercontent.com/14846116/139187613-89eec02b-3acc-4023-ae1d-c03775f32bad.png)

3.  through the log, we can get the IP of the instance `t-istio-edge-1`. 
![image](https://user-images.githubusercontent.com/14846116/139187793-e83ab862-3143-4a9b-92c0-26207b50f74e.png)

4. But finally, the result is
```
start failed: The following errors occurred:
t-istio-edge-2: timed out waiting for response

```
![image](https://user-images.githubusercontent.com/14846116/139188341-c841e39b-9bca-4a0c-8d70-2d30e849000a.png)

```

ubuntu@sdewan:~$ m shell primary-node-2
shell failed: Cannot retrieve credentials in unknown state

```
actually the VM is running

-- other logs 
![image](https://user-images.githubusercontent.com/14846116/139197248-1693d4a2-6927-49ee-9548-c0a040d672d5.png)
![image](https://user-images.githubusercontent.com/14846116/139197321-5313dc2a-cd68-469d-843d-4bd035899dc8.png)

**Comment by jonathanbossenger** [comment]
I hope you all don't mind me using this space to ask, but is there currently a workaround available? I get this problem either after I shut my machine down, or when an update happens.

Is the best solution, for now, to ensure to stop all multipass instances before shutting down/attempting an update?

**Comment by Saviq** [comment]
@jonathanbossenger you can try raising [`TimeoutStopSec`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStopSec=) to a (significantly) higher value than the default 30s.

Use `sudo systemctl edit snap.multipass.multipassd.service` and put something along those lines in:

```ini
[Service]
TimeoutStopSec=300
```

**Comment by jonathanbossenger** [comment]
@Saviq thanks kindly, I will give this a bash. Recently discovered multipass and love it, I have to create a bunch of VMs for work purposes, and being able to script a new virtual Ubuntu server through --cloud-init with multipass is a dream. Kudos to the entire team!

**Comment by luis4a0** [comment]
This bug is also related to https://github.com/canonical/multipass/issues/2374; timeout does not seem to be the only issue.
