### ISSUE TITLE
Multipass hang while working on instance

### ISSUE THREAD

**Issue by mostafaabuelkhair** [canonical/multipass#2319]
**Multipass hang while working on instance**
after start instance and login to instance and when working on it within 20 mins from start suddenly instance hanged and didn't response to any order, so should restart the the virtual machine again and most of time can't start the instance, and  it shown time out or run this command `sudo snap refresh multipass --edge` and restart the machine many times to begin response and start it again or revert back to last snap shot of the machine

**To Reproduce**
How, and what happened?
1. `multipass launch --name master-k8s --cpus 2 --mem 3072M --disk 30G`
2. `multipass shell master-k8s`
3. `multipass launch --name infra-k8s --cpus 2 --mem 3072M --disk 30G`
4. `multipass shell infra-k8s`
5. `multipass launch --name worker1-k8s --cpus 2 --mem 3072M --disk 30G`
6. `multipass shell worker1-k8s`
7. `multipass launch --name worker2-k8s --cpus 2 --mem 3072M --disk 30G`
8. `multipass shell worker2-k8s`

**Logs**
Please provide logs
[journalctl-unit-snap-multipass.txt](https://github.com/canonical/multipass/files/7449680/journalctl-unit-snap-multipass.txt)
 from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [Ubuntu 18.04]
- `multipass version`
```plain
p8admin@cloudpak:~$ sudo snap info multipass
[sudo] password for p8admin:
name:      multipass
summary:   Instant Ubuntu VMs
publisher: Canonical✓
store-url: https://snapcraft.io/multipass
contact:   https://github.com/CanonicalLtd/multipass/issues/new
license:   GPL-3.0
description: |
  Multipass is a tool to launch and manage VMs on Windows, Mac and Linux that simulates a cloud
  environment with support for cloud-init. Get Ubuntu on-demand with clean integration to your IDE
  and version control on your native platform.

  Launch an instance (by default you get the current Ubuntu LTS)

     multipass launch --name foo

  Run commands in that instance, try running bash (logout or ctrl-d to quit)

     multipass exec foo -- lsb_release -a

  Pass a cloud-init metadata file to an instance on launch

     multipass launch -n bar --cloud-init cloud-config.yaml

  See your instances

     multipass list

  Stop and start instances

     multipass stop
     multipass start

  Get help

     multipass help
commands:
  - multipass.gui
  - multipass
services:
  multipass.multipassd: simple, enabled, active
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     latest/stable
refresh-date: today at 20:24 CET
channels:
  latest/stable:    1.8.0                   2021-10-27 (6130) 133MB -
  latest/candidate: 1.8.0                   2021-10-29 (6130) 133MB -
  latest/beta:      ↑
  latest/edge:      1.9.0-dev.113+g7a58f849 2021-10-29 (6140) 134MB -
installed:          1.8.0                              (6130) 133MB -
```
```plain
$ multipass info --all`
Name:           infra-k8s
State:          Stopped
IPv4:           --
Release:        --
Image hash:     db49f99b5162 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           master-k8s
State:          Stopped
IPv4:           --
Release:        --
Image hash:     db49f99b5162 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           worker1-k8s
State:          Stopped
IPv4:           --
Release:        --
Image hash:     db49f99b5162 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           worker2-k8s
State:          Stopped
IPv4:           --
Release:        --
Image hash:     db49f99b5162 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

**Comment by Saviq** [comment]
Hi @mostafaabuelkhair instances hanging like that is often a sign of resource strain. Any chance the instances ran out of memory?

Looking at the logs they boot fine, get an IP and all. Have you tried starting just one of them, in case it's strain on your host system? When they go into this unresponsive state, you can't ping them even?

One thing you're victim of is #2316 - when you refresh the snap, systemd does not give enough time to Multipass to suspend the instances, so it kills them. It should generally not be fatal to them, though.

**Comment by Saviq** [comment]
So far it doesn't look like a Multipass issue, but rather what you do inside the instances. Will reopen if we find otherwise.

**Comment by mostafaabuelkhair** [comment]
i running K8s cluster have 4 nodes to install IBM Cloud pak for Automation

**Comment by mostafaabuelkhair** [comment]
can I increase memory by edit this file
/var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json
in ubuntu

**Comment by Saviq** [comment]
@mostafaabuelkhair yes, if you need to, `snap stop multipass`, edit that file, and `snap start multipass` again.

We're working on making this easier soon.

**Comment by Uzorp** [comment]
Hello everyone, i am having a similar issue on my multipass installation for MAC os, any ideas on how to troubleshoot or resolve this?

**Comment by luis4a0** [comment]
Hi @Uzorp, thanks for reporting. We are looking the bug you mention in Mac, [here](https://github.com/canonical/multipass/issues/2840). Please follow the issue there, we are trying to get an idea of what is wrong.

**Comment by luis4a0** [comment]
Hi @Uzorp, thanks for reporting. We have had problems with overcommiting resources on macOS. Is this the case? Do you have instances with large amount of memory? Do you have many instances running?

**Comment by nserpiot** [comment]
Hello everyone, i am having a similar issue on my multipass installation for MAC  and on Window os also. Even with one VM that is running normally, suddenly stops with msg: [debug] [base_vm] Error getting extra IP addresses: ssh connection failed: 'Timeout connecting to x.x.x.x " . Any ideas ?

**Comment by wolfch-elsevier** [comment]
Just wondering why this issue is closed without a documented fix or workaround on MacOS?  I am having this issue now.  I only have three instances and only the primary is running and can't stop it.
