### ISSUE TITLE
Multipass does not play well with VirtualBox on MacOS

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2322]
I followed the instructions here: https://multipass.run/docs/using-virtualbox-in-multipass-macos and here: https://multipass.run/docs/installing-on-macos but multipass refuses to launch anything, claiming that:

```
launch failed: Conversion of image to VDI failed (Process returned exit code: 1) with the following output:
qemu-img: Unknown file format 'vdi'
```

I have updated VirtualBox on my Mac to the latest version earlier today.

I have tried the download-a-package route and (separately) the Homebrew route.

I have tried brew installing hyper kit before brew installing multipass.

I have tried running everything using sudo.

The problem seems to be the instruction:

```
$ sudo multipass set local.driver=virtualbox
```

Once this command has been executed, multipass is useless.

I instead executed this command to undo the one above:

```
$ sudo multipass set local.driver=hyperkit
```

Using hyperkit seems to work, but using virtualbox does not.

_Originally posted by @Wee-Free-Scot in https://github.com/canonical-web-and-design/multipass.run/issues/195_

**Comment by Saviq** [comment]
Hey @Wee-Free-Scot, we have a prerelease package fixing this, if you'd like to try:

https://multipass-ci.s3.amazonaws.com/ci2808/multipass-1.8.1+mac-Darwin.unsigned.pkg

**Comment by DiyazY** [comment]
Hello. I have the same issue. Tried to download pkg with a given link, but it doesn't work  
`<Code>AccessDenied</Code>` 
Could you provide a pkg or give an accessible link, please? 
Thank you 😀!

**Comment by Saviq** [comment]
@DiyazY fixed the link, sorry!

**Comment by ajamous** [comment]
> @DiyazY fixed the link, sorry!

I think it's not fixed, gives access denied.

**Comment by Saviq** [comment]
@ajamous this fix is now live in the released version: https://multipass.run/

If you're seeing issues with VBox with current Multipass, please file a new issue:

https://github.com/canonical/multipass/issues/new?labels=bug&template=bug_report.md
