### ISSUE TITLE
Multipass activity icon out of place on macOS

### ISSUE THREAD

**Issue by hpidcock** [canonical/multipass#2324]
**What are you trying to do?**
Enjoy working on macOS with Multipass. The icon is distracting and doesn't fit in with macOS design.

**What's your proposed solution?**
Redesign the icon for macOS to fit into the space better (add padding) and also drop the ubuntu colour circle to have a more native visual.

**Additional context**
<img width="285" alt="image" src="https://user-images.githubusercontent.com/4424127/140021809-cab65b2b-444f-43de-a8f8-cb109d37b3e1.png">

**Comment by hpidcock** [comment]
Docker icon for context 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/4424127/140023198-5131e91b-0472-4eeb-a0be-ac4cc24db6e2.png">

**Comment by Saviq** [comment]
Thanks for the reminder @hpidcock, we'll try and get to this for our next release.

**Comment by Saviq** [comment]
Duplicate of #1240
