### ISSUE TITLE
multipass launch/find fail when using PAC file (needs Qt 6)

### ISSUE THREAD

**Issue by pboushy** [canonical/multipass#2325]
**Describe the bug**
When running `multipass launch` or `multipass find` it fails because it can't retried a PAC script. 

**To Reproduce**
1. `multipass launch --verbose`

mutipass fails with:
`launch failed: Remote "" is unknown or unreachable.`

**Expected behavior**
MultiPass should have been able to download the needed files.

**Logs**
[2021-11-03T15:36:55.248] [warning] [Qt] Execution of PAC script at "http%3A%2F%2Fwpad.example.com%2Fwpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1002.)
[2021-11-03T15:37:05.789] [warning] [url downloader] Error getting https://codeload.github.com/canonical/multipass-workflows/zip/refs/heads/main: Network timeout - trying cache.

**Additional info**
 - OS: macOS 10.14
- `multipass version`
multipass   1.8.0+mac
multipassd  1.8.0+mac
- `multipass info --all`
n/a

**Additional context**
Mac client is running Cisco AnyConnect.
Cisco AnyConnect tells the client to use a PAC file as shown by running `scutil --proxy`:
```
<dictionary> {
  ProxyAutoConfigEnable : 1
  ProxyAutoConfigURLString : http://wpad.example.com/wpad.dat
}
```

Note - I also have http_proxy and https_proxy set, but it looks like those are ignored.

**Comment by Saviq** [comment]
@prbsparx the error message suggests the PAC URL (http://wpad.example.com/wpad.dat) is not reachable, can you confirm you can download the PAC file?

**Comment by Saviq** [comment]
Looking closer at this, and trying some things out, I believe the problem lies in Qt, it's trying to load a url-escaped URL (`http%3A%2F%2Fwpad.example.com%2Fwpad.dat`). I was able to successfully use a static proxy with Multipass, but not through a PAC file (when the same PAC file worked fine in a browser).

Could you try setting a static proxy instead of a PAC file?

**Comment by Saviq** [comment]
I've filed a Qt bug for this:

https://bugreports.qt.io/browse/QTBUG-98024

**Comment by prbsparx** [comment]
> the PAC URL (http://wpad.example.com/wpad.dat) is not reachable
It definitely is from the network I was using.

> Could you try setting a static proxy instead of a PAC file?
I actually had run a function `proxye` that I wrote to configure my proxy variables... and noticed it didn't read those.
Cisco AnyConnect configures the proxy settings and I can't change them from my end. Our vpn admins would have to create a unique profile for me to test that.

> I saw they already have a commit that will fix this and it's going to be included in Qt 6 supposedly.

What does that mean regarding timing for the issue actually being fixed?

**Comment by Saviq** [comment]
Hi @prbsparx,

> I actually had run a function proxye that I wrote to configure my proxy variables... and noticed it didn't read those.

Right, the system wide preferences are used.

> What does that mean regarding timing for the issue actually being fixed?

It will require us to switch to Qt 6 so not a "tomorrow" thing. We'll look into it for our next release, though.

**Comment by dirien** [comment]
FYI: Run into the same problem @Saviq.

**Comment by gkarthiks** [comment]
I am also facing the same problem when trying to start the microK8s on multipass. Any update or workaround is much appreciated 🙏

**Comment by dirien** [comment]
@gkarthiks, I just remove the PAC temp. :(

**Comment by Rinfore** [comment]
> @gkarthiks, I just remove the PAC temp. :(

Would it be possible to elaborate on how this workaround works? I'm facing the same issue

**Comment by dirien** [comment]
> Would it be possible to elaborate on how this workaround works? I'm facing the same issue

I use a macbook, and under Network -> Proxies I just uncheck the checkbox for automatic proxy configuration.

**Comment by Saviq** [comment]
Hi all, Qt 5.15.3 was released recently and includes the fix for this. It won't make [our upcoming 1.9.0 release](https://discourse.ubuntu.com/t/call-for-testing-release-1-9/27688), but we'll try and get it into the next one a number of weeks later.

**Comment by dirien** [comment]
Great @Saviq!

**Comment by fuatkarakus** [comment]
Same here

**Comment by minhio** [comment]
![](https://media3.giphy.com/media/tN1lvnT4M6nte/giphy.gif?cid=790b761126381620d49d6a87ba5ceca882bea2702ebb7323&rid=giphy.gif&ct=g)

**Comment by jojomgithub** [comment]
New to Multipass. Downloaded version 1.11.1+mac. My company uses PAC file for determining the right proxy behind VPN. And I'm experiencing this issue. Maybe I missed it, but I did not see any fix or workaround described here. Any help is greatly appreciated.

**Comment by townsend2010** [comment]
This is fixed in the development version and will be in the 1.13 release.

**Comment by fernandokbs** [comment]
Same error 1.13.1. brand new mac. Any ideas?

**Comment by craftzneko** [comment]
I have the same error, no proxies

**Comment by hellboy0621** [comment]
I have the same error, no proxies on Mac Sonoma 14.2.1

**Comment by pierreh** [comment]
opening a new terminal window helped for me on a mac sonoma 14.4.

**Comment by craftzneko** [comment]
I gave up on ever getting this to work on mac, just stuck with using VM's. Will keep an eye on here in case progress ever occurs on the bug

**Comment by jmillerv** [comment]
Disabled proxies and having the same issue

Sonoma 14.6.1
multipass 1.14.0
