### ISSUE TITLE
convert hyperkit instance to qemu instance on macOS

### ISSUE THREAD

**Issue by BenWibking** [canonical/multipass#2326]
**What are you trying to do?**
I want to convert my primary instance from hyperkit to qemu. I already have a lot of packages and data installed in the instance. This way I can use newer kernels, and also prepare for a possible upgrade to an M1-based MacBook.

**What's your proposed solution?**
Create a conversion utility for hyperkit instances.

**Additional context**
N/A.

**Comment by Saviq** [comment]
Hi @BenWibking, we plan to add such a migration tool later in our dev cycle (we want to drop hyperkit altogether, as qemu is a better solution for us all around).

**Comment by townsend2010** [comment]
I will add, any x86_64 QEMU based instance will **not** run on the M1, so upgrading to an M1 will still make your instances inaccessible.

**Comment by BenWibking** [comment]
Great, looking forward to it.

@townsend2010 I didn't realize this, thanks for the warning. I see now that Rosetta2 doesn't work for VMs :/

**Comment by epitstickpan** [comment]
> I will add, any x86_64 QEMU based instance will **not** run on the M1, so upgrading to an M1 will still make your instances inaccessible.

Why would that be? I don't know how it's being used in this project but QEMU would generally handle that quite well. If you only plan to support the native architecture then wouldn't it make more sense to use the native [virtualization framework](https://developer.apple.com/documentation/virtualization)?

**Comment by Saviq** [comment]
> Why would that be? I don't know how it's being used in this project but QEMU would generally handle that quite well. If you only plan to support the native architecture then wouldn't it make more sense to use the native [virtualization framework](https://developer.apple.com/documentation/virtualization)?

We _are_ using the native [hypervisor framework](https://developer.apple.com/documentation/hypervisor) through QEMU. Running foreign architectures is something completely different, though - and we plan to look into how feasible it would be. But emulation is never going to be as good as virtualization, and we don't _currently_ support it, so that's why just upgrading to a new architecture won't work.
