### ISSUE TITLE
Multipass can not launch VM with VirtualBox on macOs

### ISSUE THREAD

**Issue by DiyazY** [canonical/multipass#2328]
I want to run VN on macOS using VirtualBox. I have been trying to do that for a week 😅. Previously, I had a problem which is solved [here](https://github.com/canonical/multipass/issues/2322). However, I have another one:
`>multipass launch -n node1     
launch failed: Could not start VM: VBoxManage: error: The virtual machine 'node1' has terminated unexpectedly during startup because of signal 10
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
Waiting for VM "node1" to power on...`
When I ran any particular VM via virtualBox, it runs and works, but I can not achieve the same thing with multipass. 
Note: VirtualBox was reinstalled, so there are no configs from the previous installations.

**Comment by Saviq** [comment]
Hi @DiyazY, see https://github.com/canonical/multipass/issues/2322#issuecomment-962413119, there's a prerelease package with a fix there and we'll be pushing the release out asap.

**Comment by Saviq** [comment]
Duplicate of #2322

**Comment by DiyazY** [comment]
@Saviq Yeah, I have already installed prerelease pkg. My installation proceeds a bit further and fails with a different exception. That's why I'm reporting it here. If the next release solves all issues, I'm waiting for that 😀
Thank you for a quick reply and what you are doing! It's great 👍

**Comment by Saviq** [comment]
Oh @DiyazY sorry, did not see that properly. Can you please attach `multipassd.log`? See https://multipass.run/docs/accessing-logs#macos for instructions.

**Comment by DiyazY** [comment]
Hi! Here is the log file!
[multipassd.log](https://github.com/canonical/multipass/files/7497682/multipassd.log)
Thank you!

**Comment by Saviq** [comment]
@DiyazY unfortunately there's nothing helpful there… all the instances fail to start with:

```plain
[2021-11-08T16:23:04.030] [debug] [test-instance] Running: VBoxManage, startvm, test-instance, --type, headless
[2021-11-08T16:23:04.686] [debug] [test-instance] VBoxManage failed - errorString: Unknown error, exitStatus: 0, exitCode: 1
```

Are you on macOS Monterey maybe? This suggests there's a problem with VirtualBox there:

https://forums.virtualbox.org/viewtopic.php?t=104249

**Comment by DiyazY** [comment]
@Saviq yes, I'm on Monterey, and it seems that problem is in Monterey+VirtualBox. Thank you for pointing it out.

**Comment by Saviq** [comment]
@DiyazY is qemu / hyperkit working for you though?

**Comment by DiyazY** [comment]
Hi @Saviq ! Yes, it works. I just got used to using VirtualBox. Is there any crucial difference between hyperkit and VirtualBox drivers? I was not able to find any straightforward answers on the Internet.

**Comment by Saviq** [comment]
@DiyazY with hyperkit and qemu you can directly access the instance via IP. OTOH VirtualBox allows for [`--network`](https://multipass.run/docs/additional-networks), which the former currently don't (we'll implement it for qemu soon).

Other than that, (by design) there isn't a significant difference. VirtualBox you have to install yourself, the others you don't - and they run on the native macOS [Hypervisor.framework](https://developer.apple.com/documentation/hypervisor).

VirtualBox is also unlikely to support the Apple M1 CPU, which qemu does already. Hyperkit we'll deprecate in a couple releases.

**Comment by DiyazY** [comment]
@Saviq Thank you for a brief explanation!

**Comment by sepsol** [comment]
Running into the same exact issue. I am on macOS Monterey as well and was able to run my VM using `hyperkit`. But when I tried to create a bridged connection using the `virtualbox` driver and `--network` option, I got the exact error message specified above.

**Comment by tunkul** [comment]
Getting the exact same thing. Everything was installed today (both vbox and multipass, on macOS). It ran fine with the default hyperkit. I was able to create instances no problem. Did the: 
```
$ sudo multipass set local.driver=virtualbox
```
And nothing. The previous instances disappeared, multipass list shows nothing, and trying to create new instances fails as below. When i revert to using hyperkit, my previous instances reappear.
```
$ multipass launch -n dude
launch failed: Could not start VM: VBoxManage: error: The virtual machine 'dude' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

**Comment by Saviq** [comment]
@tunkul the instances don't transfer between drivers (they're incompatible), so switching back to `hyperkit` you'll find your instances again. I would suggest trying the `qemu` driver though, together with [v1.9.0-rc](https://github.com/canonical/multipass/releases/tag/v1.9.0-rc) you have the best feature coverage through that. We'll be deprecating `hyperkit` soon and VirtualBox should be unnecessary.

That said, the error comes straight from VirtualBox, are you able to run instances under `sudo VirtualBox` manually? See https://multipass.run/docs/using-virtualbox-in-multipass-macos for more details.
