### ISSUE TITLE
Virtualisation check is not being run correctly.  launch failed: The check_kvm_support script failed to start. Ensure it is in multipassd's PATH.

### ISSUE THREAD

**Issue by oreillymj** [canonical/multipass#2336]
***Description of the bug***
On systems with virtualisation disabled, the check_kvm script either does not run when launching a VM or the return code is misinterpreted. I would expect the check_kvm script to tell the user that the system needs virtualisation enabled.

***To Reproduce***
I tried this on both an on-prem box and AWS cloud instance running Ubuntu 20.04
I am running as root...

```plain
$ multipass launch -n test1
launch failed: The check_kvm_support script failed to start. Ensure it is in multipassd's PATH.
```

Adding the snap's bin folder to the path made no difference.
```plain
$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/multipass/current/bin"
```

Adding the snap path to the systemd service made no difference.
```plain
$ cat /etc/systemd/system/multipath-tools.service
[Unit]
Description=Device-Mapper Multipath Device Controller
<snipped>

[Service]
<snipped>
Environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/multipass/current/bin"
```

Running the command manually displays the correct output.
```plain
$ /sbin/check_kvm_support
KVM (vmx) is disabled by your BIOS.
Enter your BIOS setup and enable Virtualization Technology (VT).
```

Which matches the output from
```
$ kvm-ok
> INFO: /dev/kvm does not exist
> HINT: sudo modprobe kvm_intel
> INFO: Your CPU supports KVM extensions
> INFO: KVM (vmx) is disabled by your BIOS
> HINT: Enter your BIOS setup and enable Virtualization Technology (VT),
> and then hard poweroff/poweron your system
> KVM acceleration can NOT be used
```

Enabling virtualisation fixed the issue.
```plain
$ multipass launch -n test1
Launched: test1
$ kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

***Expected behavior***
I would expect the VM to fail to launch with the error output from check_kvm_support when virtualisation is disabled. The error message provided is confusing.

***Logs***
Unfortunately the system was rebooted to enable virtualisation and I do not have logs from the time of the issue.

***Additional info***
```plain
$ uname -a
Linux  5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ multipass version
multipass   1.8.0
multipassd  1.8.0

$ multipass info --all
Name:           test1
State:          Running
IPv4:           xxx.xxx.xxx.xxx
Release:        Ubuntu 20.04.3 LTS
Image hash:     939be728cbc7 (Ubuntu 20.04 LTS)
Load:           0.12 0.07 0.09
Disk usage:     1.3G out of 4.7G
Memory usage:   130.5M out of 981.2M
Mounts:         --
```

**Comment by Saviq** [comment]
Thanks @oreillymj, that's weird indeed. Note the service you modified is _not_ `multipassd` but `multipath-tools`. The right one can be edited with `systemctl edit snap.multipass.multipassd.service`.

Regardless, that error message needs fixing, we're not executing that script using `PATH`, but by calling it by full path.

We'll look into it.

**Comment by Saviq** [comment]
I can reproduce by `sudo rmmod kvm_intel kvm`:

```plain
$ multipass sh -vvvv
[2021-11-15T13:11:07.975] [debug] [/snap/multipass/6130/bin/check_kvm_support] [1680850] started: /snap/multipass/6130/bin/check_kvm_support 
launch failed: The check_kvm_support script failed to start. Ensure it is in multipassd's PATH.
```

**Comment by townsend2010** [comment]
The problem is when `check_kvm_support` tries to load the kvm modules, apparmor denies the `kmod` calls:
```Nov 15 09:59:22 Ghost audit[563552]: AVC apparmor="DENIED" operation="exec" profile="snap.multipass.multipassd" name="/usr/bin/kmod" pid=563552 comm="check_kvm_suppo" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Nov 15 09:59:22 Ghost audit[563552]: AVC apparmor="DENIED" operation="exec" profile="snap.multipass.multipassd" name="/usr/bin/kmod" pid=563552 comm="check_kvm_suppo" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Nov 15 09:59:22 Ghost audit[563555]: AVC apparmor="DENIED" operation="exec" profile="snap.multipass.multipassd" name="/usr/bin/kmod" pid=563555 comm="check_kvm_suppo" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Nov 15 09:59:22 Ghost audit[563555]: AVC apparmor="DENIED" operation="exec" profile="snap.multipass.multipassd" name="/usr/bin/kmod" pid=563555 comm="check_kvm_suppo" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
```
Need to see if there is a Snap connection where are missing.  If there isn't one, then need to redo the `modprobe` part in the script to account for the denial.

**Comment by OrBin** [comment]
@townsend2010 when do you expect to release a version including the fix to this problem?

**Comment by Saviq** [comment]
@OrBin we'll release towards the end of this month. You can use the `edge` channel in the mean time. But since it's just a problem with _detection_, as long as you have virtualization enabled, you can stick with stable.
