### ISSUE TITLE
Cloning Linux kernel git repo is slow and never finishes in primary

### ISSUE THREAD

**Issue by ikitayama** [canonical/multipass#2341]
While it can be done on my MacBook Pro M1. Any way to speed up the check-out process?

**Comment by ikitayama** [comment]
```
Cloning into 'linux'...
remote: Enumerating objects: 8467398, done.
error: index-pack died of signal 9467398), 3.11 GiB | 3.82 MiB/s
fatal: index-pack failed
```

There's enough space under the / partition.

**Comment by Saviq** [comment]
@ikitayama hey, so it's not _speed_  that's the issue, is it? I tried with `--depth=1` just now and it took about the same time that it did directly on the host.

I'm trying a full clone now, but it's a lot to download…

**Comment by ikitayama** [comment]
Hi
I tried the “workaround”, but isn’t multi pass designed to not compromise
the performances?

**Comment by Saviq** [comment]
@ikitayama how much memory did you give your instance? The `died of signal…` message is an indication of running out of memory inside the instance. Try launching your instance with `--mem 4G` or more:

```plain
$ multipass launch -n primary -d 40G -m 8G
Launched: primary
Mounted '/Users/michal' into 'primary:Home'

$ time multipass exec primary -- git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Cloning into 'linux'...
remote: Enumerating objects: 913, done.
remote: Counting objects: 100% (913/913), done.
remote: Compressing objects: 100% (379/379), done.
remote: Total 8467398 (delta 654), reused 645 (delta 531), pack-reused 8466485
Receiving objects: 100% (8467398/8467398), 2.25 GiB | 9.84 MiB/s, done.
Resolving deltas: 100% (6939853/6939853), done.
Updating files: 100% (74304/74304), done.
multipass exec primary -- git clone   0,05s user 0,08s system 0% cpu 8:35,79 total
```

I'll close this for now, please reopen if you find that not enough.

**Comment by ikitayama** [comment]
Thank you very much @Saviq !

**Comment by ikitayama** [comment]
Before you @Saviq go, when do you plan to support existing instances configuration changes via the multipass sub commands? I did manually change the json file to give more memory to the primary.

**Comment by Saviq** [comment]
@ikitayama we're working on it now, but will likely be into the new year.

**Comment by ikitayama** [comment]
@saviq looking forward to it!
