### ISSUE TITLE
Replace primary's Ubuntu kernel with the upstream one 

### ISSUE THREAD

**Issue by ikitayama** [canonical/multipass#2349]
Is this supported in the new year's release?

**Comment by Saviq** [comment]
Provided you use the `qemu` driver (`sudo multipass set local.driver=qemu`), you can use the mainline builds from here:

https://wiki.ubuntu.com/Kernel/MainlineBuilds

```plain
ubuntu@primary:~$ uname -a
Linux primary 5.16.0-051600rc1-generic #202111142330 SMP Sun Nov 14 23:34:59 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by ikitayama** [comment]
After installing upstream kernel .deb files on to primary, it never boots:

```
Starting primary 
```

it gets stuck there forever.

**Comment by Saviq** [comment]
@ikitayama there's a good chance there's missing hardware support in those builds, like networking. Examine a working instance with `lsmod` if you want to see what's loaded and make sure the kernel you install has them.

**Comment by ikitayama** [comment]
Ah then I should build a kernel using the ocnfig atop of Ubuntu’s then
primary will boot, right?

**Comment by Saviq** [comment]
Or use the mainline builds I linked above, those work fine, and are verbatim upstream kernels built by Ubuntu's kernel team.

**Comment by ikitayama** [comment]
I used one of those mainline builds by the way

**Comment by ikitayama** [comment]
Michal, is using multipass for a kernel dev supported or considered when
designing this platform?

**Comment by ikitayama** [comment]
In my install experiments (twice), a 64K page kernel broke, a normal? 4K page kernel worked. Ubuntu built the binaries.

**Comment by ikitayama** [comment]
> In my install experiments (twice), a 64K page kernel broke, a normal? 4K page kernel worked. Ubuntu built the binaries.

I forgot that M1 Max's page size is 16KB. Sorry.

**Comment by Saviq** [comment]
> Michal, is using multipass for a kernel dev supported or considered when designing this platform?

I think the biggest problem with this will be access to the console, and recovery, if things break. We currently don't support accessing the console (it's not trivial to do cross-platform / cross-hypervisor) and so that may limit its usefulness. As for recovery we discussed (#1910) a way to have a second machine as a recovery helper at some point.

**Comment by ikitayama** [comment]
Yes, indeed, that was my worry. However, in the meantime I can use it as a
build VM.
