### ISSUE TITLE
Can't utilize all 10 cores on Apple M1 Pro/Max

### ISSUE THREAD

**Issue by AwlsomeAlex** [canonical/multipass#2350]
**Describe the bug**
When trying to create a new instance with `--cpus 10`, the following error occurs:
`launch failed: The following errors occurred:                                   
qemu-system-aarch64: Number of SMP CPUs requested (10) exceeds max CPUs supported by machine 'mach-virt' (8)`

**To Reproduce**
How, and what happened?
1. `multipass launch --name test --cpus 10 -m 8G -d 50G impish`
2. Instance is created, but error message above is outputted.

**Expected behavior**
Instance with 10 cores should be created and launched.

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/7576688/multipassd.log)

**Additional info**
 - OS: macOS 12.0.1
- 1.8.1+mac

Name:           test
State:          Stopped
IPv4:           --
Release:        --
Image hash:     063fa690f56b (Ubuntu 21.10)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

**Comment by ikitayama** [comment]
2 of them are efficiency cores.

**Comment by Saviq** [comment]
@ikitayama @AwlsomeAlex thanks for reporting, in fact the number of physical CPUs doesn't matter, the virtual CPUs are just threads on the physical CPU. That said, there's a compiled-in maximum of threads the virtual machine supports, and bumping that is something that we would need to look into:

https://github.com/canonical/qemu/blob/multipass/include/hw/intc/arm_gic_common.h#L32-L33

**Comment by AwlsomeAlex** [comment]
@Saviq I opened an issue to upstream QEMU [here](https://gitlab.com/qemu-project/qemu/-/issues/743).

**Comment by mlb5000** [comment]
Has there been any progress on this? I have a 12 core M2 Pro that is also running up against the 8 core limitation.

**Comment by ckato3** [comment]
My M2 Max also cannot allocate all 12 cores.   There are CPUs like the M1 Ultra with 20 cores, so I hope there will be a patch that will allow all cores to be used.

**Comment by townsend2010** [comment]
`qemu` version 8.0 fixes this and we will work to get this into the upcoming 1.12 release.
