### ISSUE TITLE
instances do not start: crashed program qemu-system-x86_64

### ISSUE THREAD

**Issue by ShinobiX9X** [canonical/multipass#2354]
**Describe the bug**
Launching an instance hangs: timed out waiting for response
Starting that instance gives error

**To Reproduce**
How, and what happened?
1. `multipass start foo`
1. `
[2021-11-24T17:18:57.155] [error] [foo] process error occurred Crashed program: qemu-system-x86_64; error: Process crashed
[2021-11-24T17:18:57.156] [error] [foo] error: program: qemu-system-x86_64; error: Process crashed
start failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
`

**Expected behavior**
What did you expect to happen?
Start the instance without an error

**Logs**
see attached file
[multipass.multipassd.logs.txt](https://github.com/canonical/multipass/files/7597255/multipass.multipassd.logs.txt)

**Additional info**
 - OS: Arch Linux (kernel 5.15.4-arch1-1)
- `multipass(d) 1.8.0`
- `
Name:           foo
State:          Stopped
IPv4:           --
Release:        --
Image hash:     91740d72ffff (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
`

**Comment by Saviq** [comment]
Hi @ShinobiX9X, is that all the logs that you got? There's nothing in the logs about the instance being launched / started.

Can you try a fresh `multipass launch -vvvv`?

**Comment by ShinobiX9X** [comment]
Hello, was quick
`multipass launch -vvv`: 
[multipass.launch-vvv.txt](https://github.com/canonical/multipass/files/7597376/multipass.launch-vvv.txt)
and then `snap logs multipass.multipassd`
[multipass.multipassd.logs.txt](https://github.com/canonical/multipass/files/7597386/multipass.multipassd.logs.txt)

thank you

**Comment by Saviq** [comment]
Oh so no crash now. @ShinobiX9X do you have a firewall enabled? You need to let traffic on `mpqemubr0` through. Have a look at #1448 and possibly #1236 for some more details.

I'll close this for now, will reopen if you find it's not that.
