### ISSUE TITLE
Lost all multipass instances after a Mac reboot

### ISSUE THREAD

**Issue by karthikeyan23** [canonical/multipass#2362]
I'm running multipass   1.8.1+Mac on macOS Monterey v12.0.1. I had four instances setup for running a local Kubernetes (learning purpose) and when I restarted my Mac all the instances were lost!. I'm not sure if this is a known/reoccurring issue. Setting up the instances again is bit of a pain, so kindly provide me some pointers on restoring back the lost instances or what should I do to avoid this issue in future.

PS: I'm using the native multipass virtualisation not virtual box.

**Comment by Saviq** [comment]
Hi @karthikeyan23 sorry about that, can you please provide [the logs](https://multipass.run/docs/accessing-logs#macos) so we can see what went wrong?

**Comment by karthikeyan23** [comment]
Added the logs of the 3 instances + multipassd 
[k8s-node-m1-hyperkit.log](https://github.com/canonical/multipass/files/7649963/k8s-node-m1-hyperkit.log)
[k8s-node-w1-hyperkit.log](https://github.com/canonical/multipass/files/7649964/k8s-node-w1-hyperkit.log)
[k8s-node-w2-hyperkit.log](https://github.com/canonical/multipass/files/7649965/k8s-node-w2-hyperkit.log)
[multipassd.log](https://github.com/canonical/multipass/files/7649966/multipassd.log)
)

**Comment by Saviq** [comment]
@karthikeyan23 can you please also let us know which instances were lost? And when, roughly?

Can you please also post the contents of `/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json` and the output of `sudo find /var/root/Library/Application Support/multipassd`?

**Comment by karthikeyan23** [comment]
@Saviq thanks for the help, I lost all instances yesterday ```[2021-12-02]``` around ```5:30 PM```, these are the ones that I would like to recover are ```k8s-node-m1, k8s-node-w1, k8s-node-w2```.

This is the content of the multipassd-vm-instances.json - 
[multipassd-vm-instances.json.txt](https://github.com/canonical/multipass/files/7651606/multipassd-vm-instances.json.txt)

This is the output of the find command 

`/var/root/Library/Application Support/multipassd
/var/root/Library/Application Support/multipassd/registered-certs
/var/root/Library/Application Support/multipassd/ssh-keys
/var/root/Library/Application Support/multipassd/ssh-keys/id_rsa
/var/root/Library/Application Support/multipassd/multipass-unique-id
/var/root/Library/Application Support/multipassd/certificates
/var/root/Library/Application Support/multipassd/certificates/localhost_key.pem
/var/root/Library/Application Support/multipassd/certificates/localhost.pem
/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json
/var/root/Library/Application Support/multipassd/multipassd-send-metrics.yaml
/var/root/Library/Application Support/multipassd/vault
/var/root/Library/Application Support/multipassd/vault/instances
/var/root/Library/Application Support/multipassd/vault/instances/ubuntu-linux-lab
/var/root/Library/Application Support/multipassd/vault/instances/ubuntu-linux-lab/pty
/var/root/Library/Application Support/multipassd/vault/instances/ubuntu-linux-lab/cloud-init-config.iso
/var/root/Library/Application Support/multipassd/vault/instances/ubuntu-linux-lab/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
/var/root/Library/Application Support/multipassd/vault/instances/ubuntu-linux-lab/ubuntu-20.04-server-cloudimg-amd64.img
/var/root/Library/Application Support/multipassd/vault/instances/ubuntu-linux-lab/ubuntu-20.04-server-cloudimg-amd64-initrd-generic
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-m1
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-m1/pty
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-m1/cloud-init-config.iso
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-m1/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-m1/ubuntu-20.04-server-cloudimg-amd64.img
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-m1/ubuntu-20.04-server-cloudimg-amd64-initrd-generic
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w2
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w2/pty
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w2/cloud-init-config.iso
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w2/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w2/ubuntu-20.04-server-cloudimg-amd64.img
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w2/ubuntu-20.04-server-cloudimg-amd64-initrd-generic
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w1
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w1/pty
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w1/cloud-init-config.iso
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w1/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w1/ubuntu-20.04-server-cloudimg-amd64.img
/var/root/Library/Application Support/multipassd/vault/instances/k8s-node-w1/ubuntu-20.04-server-cloudimg-amd64-initrd-generic
/var/root/Library/Application Support/multipassd/vault/instances/primary
/var/root/Library/Application Support/multipassd/vault/instances/primary/pty
/var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso
/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img
/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-initrd-generic
/var/root/Library/Application Support/multipassd/vault/multipassd-instance-image-records.json
/var/root/Library/Application Support/multipassd/saved_metrics.json`


Kindly let me know if any other input is needed.

**Comment by townsend2010** [comment]
Hi @karthikeyan23,

Looking through the log, it looks like you switched from using the `hyperkit` driver to using the `virtualbox` driver.  Hyperkit images are not compatible with VirtualBox.  Please try switching back to the `hyperkit` backend:

`$ sudo multipass set local.driver=hyperkit`

**Comment by karthikeyan23** [comment]
@townsend2010 Thanks a lot!! I got the instances back. But I'm not sure how the driver got changed to virtualbox, have not done it myself. 
I always use CLI to start/stop instances, but lately I tried using the multipass UI agent for Mac and also tried starting "primary" instance via the UI, But I'm not sure how the drivers got changed.

Thanks again @townsend2010  @Saviq  for you help!!
