### ISSUE TITLE
Removing All Images

### ISSUE THREAD

**Issue by the-nodus** [canonical/multipass#2363]
Is there an easy way to remove all of the images from multipass. After running `multipass find`, I found a lot of images that I do not need to use. I am on MacOS by the way. Thank you all.

**Comment by Saviq** [comment]
@the-nodus this is just a list of available images, they won't be downloaded until you ask to launch an instance with them.

There's no way to hide images from `multipass find` and we don't have plans to allow that.

**Comment by yukal** [comment]
@the-nodus maybe these commands will help you:
- `multipass info`
- `multipass delete`
- `multipass purge`

You can read about each command following these commands (before launching them):
- `multipass info --help`
- `multipass delete --help`
- `multipass purge --help`
