### ISSUE TITLE
networks failed: The networks feature is not implemented on this backend. OSX M1

### ISSUE THREAD

**Issue by gamelife1314** [canonical/multipass#2364]
**Describe the bug**
networks failed: The networks feature is not implemented on this backend.

**To Reproduce**
How, and what happened?
1. `multipass networks`

**Expected behavior**
What did you expect to happen?

list available network interface 

**Logs**
networks failed: The networks feature is not implemented on this backend.

**Additional info**
![image](https://user-images.githubusercontent.com/10297148/144711851-f06cdeab-9d29-4635-a166-1889d7ab5d7e.png)

**Additional context**

**Comment by Saviq** [comment]
Hi @gamelife1314 indeed, we don't yet support extra networks on the M1. We'll work on that soon after the new year, though.

**Comment by gamelife1314** [comment]
oh, thank you

> Hi @gamelife1314 indeed, we don't yet support extra networks on the M1. We'll work on that soon after the new year, though.

**Comment by Saviq** [comment]
Hey all, we have an in-progress package for you to try:

https://multipass-ci.s3.amazonaws.com/pr444/multipass-1.10.0-dev.577.pr444%2Bg5c874a52.mac-Darwin.pkg

```plain
$ uname -vp
Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:42 PST 2022; root:xnu-7195.141.26~1/RELEASE_ARM64_T8101 arm

$ multipass networks
Name     Type         Description
bridge0  bridge       Network bridge with en1, en2
en0      wifi         Wi-Fi
en1      thunderbolt  Thunderbolt 1
en2      thunderbolt  Thunderbolt 2
en3      ethernet     Ethernet Adaptor (en3)
en4      ethernet     Ethernet Adaptor (en4)

$ multipass launch --network en0
Launched: exalting-gnatcatcher

$ ping exalting-gnatcatcher
PING exalting-gnatcatcher.local (10.2.0.39): 56 data bytes
64 bytes from 10.2.0.39: icmp_seq=0 ttl=63 time=7.727 ms
64 bytes from 10.2.0.39: icmp_seq=1 ttl=63 time=15.083 ms
64 bytes from 10.2.0.39: icmp_seq=2 ttl=63 time=15.719 ms
^C
--- exalting-gnatcatcher.local ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 7.727/12.843/15.719/3.627 ms

$ multipass list
Name                    State             IPv4             Image
exalting-gnatcatcher    Running           192.168.66.41    Ubuntu 20.04 LTS
                                          10.2.0.39
```

Have fun :)

**Comment by techmore** [comment]
Wow! M1 networks is working for me on the lan with the command below. Tested a rails app, accessible from multiple machines on my lan. This is huge!!!

multipass launch --network en0 test-01

**Comment by plaidpowered** [comment]
I apologize for what I'm certain is a newb question - but is there a way to change the network interface on existing instances, not just new ones? I can't find any documentation, but if there is some, please point me there! Thank you

**Comment by Saviq** [comment]
@plaidpowered not at the moment, no. It's planned, but not on any immediate roadmap. Depending on driver, you could use the hypervisor tools to modify the VM.

**Comment by pauljsymonds** [comment]
I get the same message on `Ubuntu 22.04 LTS (GNU/Linux 5.15.0-27-generic x86_64)`

```
multipass networks
networks failed: The networks feature is not implemented on this backend.
```

is this implemented in the next release?

**Comment by jarrodu** [comment]
It looks like I am getting the same issue was @pauljsymonds.

```
Operating System: Ubuntu 22.04 LTS
Kernel: Linux 5.15.0-30-generic
Architecture: x86-64
Hardware Vendor: Lenovo
Hardware Model: ThinkPad X1 Carbon Gen 8
multipass   1.9.2
multipassd  1.9.2
```

```
> multipass networks
networks failed: The networks feature is not implemented on this backend.
```

**Comment by jarrodu** [comment]
I think I might make a new issue. This one is for OSX M1

**Comment by jarrodu** [comment]
#2597

**Comment by magnetikonline** [comment]
> Hey all, we have an in-progress package for you to try:
> 
> https://multipass-ci.s3.amazonaws.com/pr444/multipass-1.10.0-dev.577.pr444%2Bg5c874a52.mac-Darwin.pkg

Hey @Saviq - this works **awesome** in the final `1.10.0` release. Using this for a Unifi controller running under Docker, within a Multipass guest/VM.

Without this - the controller is unable to see my local network/access points/etc.

What is a shame - this new `--network` switch didn't seem to make the release notes here?

https://github.com/canonical/multipass/releases/tag/v1.10.0

Feels worthwhile to tack this on - as for me, this is a killer feature addition for macOS/M1/ARM machines that can't use the existing VirtualBox network drivers - and to be honest, I _love_ being totally free of VirtualBox now! 😄

**Comment by townsend2010** [comment]
Hi @magnetikonline!

Glad it works well for you!

> What is a shame - this new --network switch didn't seem to make the release notes here?

That's because this feature was released in [1.9.0](https://github.com/canonical/multipass/releases/tag/v1.9.0).  See number 2 under "There are some significant additions to this release:" :slightly_smiling_face:

**Comment by ricab** [comment]
@pauljsymonds, @jarrodu: have a look at https://multipass.run/docs/networks-command, the networks feature is only supported on certain OS/driver combinations.

**Comment by weberc2** [comment]
I still get this error on 1.11.1+mac (intel, not m1); is this expected? I installed from homebrew.

**Comment by townsend2010** [comment]
Hi @weberc2,

You need to switch to the `qemu` driver to get this functionality:
`$ multipass set local.driver=qemu`

**Comment by weberc2** [comment]
I think I was using the qemu driver, but I just figured out that virtualbox driver supports it.

https://github.com/canonical/multipass/blob/cd1a651bc54d2f43c277542c6c4fd113d666fb32/src/platform/backends/qemu/qemu_platform.h#L59

```cpp
    // qemu_platform.h
    virtual std::vector<NetworkInterfaceInfo> networks() const
    {
        throw NotImplementedOnThisBackendException("networks");
    };
```

**Comment by townsend2010** [comment]
If you didn't actually switch the driver from when you installed it from Homebrew, then you were using the `hyperkit` driver which does **not** support additional networks.

That code you pointed out is from the `QemuPlatform` base class, but the macOS qemu implementation does add support for networks- I added it roughly a year ago.

**Comment by weberc2** [comment]
Ah, that makes sense. Thanks for explaining.
