### ISSUE TITLE
getting an error (warning) when using cloud-init to install ubuntu-desktop on ubuntu 20.04

### ISSUE THREAD

**Issue by uishon** [canonical/multipass#2377]
**Describe the bug**
Installing `ubuntu-desktop` on an ubuntu 20.04 image to be launched using the `--cloud-init` option. Getting the following error in `/var/log/cloud-init-output.log`
```
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
Error is indeed ignored and VM is eventually launched but that's not nice (and might be the reason why the launching process takes a couple of minutes).

**To Reproduce**
How, and what happened?
1. create a `my-cloud-init.yml`
```
#cloud-config

users:
  - default

packages:
  - ubuntu-desktop
```
2. `multipass launch --cloud-init my-cloud-init.yml`

**Expected behavior**
No errors.

**Additional info**
 - OS: Windows 11 Pro version 10.0.22000 Build 22000
- `multipass version`
```
multipass   1.8.0+win
multipassd  1.8.0+win
```
- `multipass info --all`
```
Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     27cecebaf8c6 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           unanimous-spidermonkey
State:          Running
IPv4:           172.17.76.195
Release:        Ubuntu 20.04.3 LTS
Image hash:     27cecebaf8c6 (Ubuntu 20.04 LTS)
Load:           3.36 2.06 0.88
Disk usage:     4.1G out of 4.7G
Memory usage:   264.9M out of 916.9M
Mounts:         --

Name:           venus
State:          Running
IPv4:           172.17.77.68
                172.17.0.1
                172.18.0.1
Release:        Ubuntu 20.04.3 LTS
Image hash:     27cecebaf8c6 (Ubuntu 20.04 LTS)
Load:           0.28 0.24 0.38
Disk usage:     10.4G out of 30.8G
Memory usage:   4.5G out of 17.5G
Mounts:         --
```

**Additional context**
Installed other packages (e.g., python related) and did NOT get this error. Seems like a specific issue with `ubuntu-desktop`.

**Comment by Saviq** [comment]
Hi @uishon, it's package post-install scripts that print this, benign, warning - _if_ libeatmydata isn't installed.

This makes the warning go away:

```plain
$ multipass launch --cloud-init - <<EOF
packages:
  - eatmydata
  - ubuntu-desktop
EOF
```

Read more about eatmydata [on its manpage](https://manpages.ubuntu.com/manpages/trusty/man1/eatmydata.1.html).

Not a bug, really, and not a Multipass for sure.
