### ISSUE TITLE
Set the problem that the hosts file is recovered after restart

### ISSUE THREAD

**Issue by youaodu** [canonical/multipass#2385]
**Describe the bug**
I want to set the hosts file so that I can access node1 and change the request address to 192.168.64.2. However, after I modify the file, it takes effect, but after I exit, restart the second instance with multipass restart. After restarting, I found that the modified part of the hosts file was cleared

**To Reproduce**
How, and what happened?
1. multipass start node1 node2
2. multipass shell node1
3. sudo vi /etc/hosts
4. enter 192.168.64.2 node1
5. :wq
6. ping node1
7. .....
8. exit
9. multipass restart node2
10. multipass shell node2
11. cat /etc/hosts

**Expected behavior**
What did you expect to happen?
I think if I Ping node2 again, it will prompt success. As a result, it will prompt failure

**Additional info**
 - OS: M1 OSX 12.0.1
- `multipass version` 
    - multipass   1.8.1+mac
    - multipassd  1.8.1+mac
- `multipass info --all`
    
![image](https://user-images.githubusercontent.com/49941556/147815818-3451628c-4a7a-435e-a998-0888a0f8bd96.png)

**Comment by thanhnnict** [comment]
@youaodu : I still have same issue with you. Please share with me solution for resolve this issue. Thanks!

**Comment by asukamae** [comment]
Hi, @thanhnnict, it is commented
_# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data_

If you edit the template, the change remains.
