### ISSUE TITLE
Instance freezes and cd command is so slow in mounted directory area

### ISSUE THREAD

**Issue by SupianIDz** [canonical/multipass#2386]
**Describe the bug**
I'm using multipass for web development purposes and for a few reasons.

But 20-30 minutes after starting, apache2 on multipass does not respond, then the terminal will freeze. I tried to wait a while, but 10 minutes I waited, it's not back to normal.

I tried to run `multipass shell octopy` again on a different terminal, however it can't connect anymore to the instance, unless I restart `multipass restart octopy`

And the last problem, when switching mounted directories with the `cd` command, it takes about a second each command.

**To Reproduce**
How, and what happened?
1. Create multipass with Ubuntu 20.04
2. `apt install apache2 mysql-server-8.0 php8.0 php8.0-{fpm,imagick,zip,mbstring,mysql,dom,intl,dev}`
3. `multipass mount $HOME/Sites octopy:/var/www/html`

**Expected behavior**
1. The `cd` command does not take much time when going to or in the mounted directory
2. Instances don't freeze for a long time. No problem freezing in a few seconds, it's tolerable.

**Logs**
[https://gist.github.com/SupianIDz/58e676b18c34d175b6c301eafe6dfa2f](https://gist.github.com/SupianIDz/58e676b18c34d175b6c301eafe6dfa2f)

**Additional info**
 - OS: macOS Monterey 12.1
- `multipass version`
  - multipass   1.8.1+mac
  - multipassd  1.8.1+mac 
- `multipass info --all`
```Name:           octopy
State:          Running
IPv4:           192.168.64.15
Release:        Ubuntu 20.04.3 LTS
Image hash:     f83575f6791e (Ubuntu 20.04 LTS)
Load:           0.07 0.07 0.02
Disk usage:     4.2G out of 4.7G
Memory usage:   550.3M out of 1.9G
Mounts:         /Users/supianidz/Sites => /var/www/html
                    UID map: 501:default
                    GID map: 20:default
```
## Screenshot from `htop` I used 3 cores
<img width="1141" alt="Screen Shot 2022-01-02 at 04 18 38" src="https://user-images.githubusercontent.com/37969970/147859412-a4641db8-5fbf-475d-8a89-fe3b011980fb.png">

**Comment by townsend2010** [comment]
Hi @SupianIDz,

Sorry to hear about your issue.  In order to help me reproduce, are you actually connecting to the instance's Apache server and do you have anything of note in your host's `Sites` directory?  Is this reproducible with just a simple site in the host directory?

**Comment by townsend2010** [comment]
Also, macOS has a quite low max open file limit that has caused us problems in the past (#1933).  You could try increasing the `maxfiles` limit and see if that helps.

**Comment by SupianIDz** [comment]
> Hi @SupianIDz,
> 
> Sorry to hear about your issue. In order to help me reproduce, are you actually connecting to the instance's Apache server and do you have anything of note in your host's `Sites` directory? Is this reproducible with just a simple site in the host directory?

- In `Sites` directory installed 2 Laravel project.
- In MySQL there are 2 databases from the Laravel project, both of which are about 1 GB in size.

And the problem I found recently, when I reload the page quite often (I use `LiveReload` from `webpack`), then `Sites` can't be opened at all, from `apache` log `/var/ www/html` where the mount of `Sites` was not found. So forced to `unmount` then `remount` to fix it. This happened several times.

I have to reboot macOS when `Ubuntu` freezes, because `multipass restart octopy` doesn't work at all, just spins for a long time.

I am very grateful for this multipass, it really helps me. I appreciate it with all the flaws that exist, thanks.

**Comment by SupianIDz** [comment]
> Also, macOS has a quite low max open file limit that has caused us problems in the past (#1933). You could try increasing the `maxfiles` limit and see if that helps.

Thanks, i'll try it.

**Comment by townsend2010** [comment]
Great!  Please let me know if increasing the limit makes it any better or if the problem persists.  Thanks!

**Comment by SupianIDz** [comment]
Perfect, thanks
