### ISSUE TITLE
Support VMs other than Ubuntu

### ISSUE THREAD

**Issue by dnegreira** [canonical/multipass#24]
I am unable to find any information regarding this.

Thanks.

**Comment by Saviq** [comment]
Multipass is currently limited to images published on [cloud-images](https://cloud-images.ubuntu.com/), and those only include Ubuntu images. That said, as long as the image would have [cloud-init](http://cloudinit.readthedocs.io/) installed, there's no reason why other images wouldn't work.

**Comment by dnegreira** [comment]
I guess then that there is the need for multipass to support first the definition of multiple 'remotes' where one could point to other repositories besides the default Ubuntu ones, right ?

**Comment by Saviq** [comment]
We already have the notion of remotes, `release:` and `daily:`, to support the default Ubuntu ones. There's also [the linuxcontainers remote](https://images.linuxcontainers.org) as configured in LXD, but we have not tried them out yet.
The other reason to have remotes is you might have a remote of your own, either caching the images in your enterprise or only having blessed ones etc.

**Comment by townsend2010** [comment]
When #249 is merged, you'll be able to specify either a local image file or a URL to an image which can be, for example, a Fedora cloud image found at https://alt.fedoraproject.org/cloud/.

We will follow up later with a way to specify other remotes.
