### ISSUE TITLE
Creating instance with LXD fails after snap refresh

### ISSUE THREAD

**Issue by luis4a0** [canonical/multipass#2401]
**Describe the bug**
After succesfully creating an instance, trying to create a new one failed.

**To Reproduce**
This situation showed up randomly, I'm not sure how to reproduce. In my case, I first created a VM with
`multipass launch -c 1 -d 10G -n testfs1lxd`

Then, trying to create a new one with
`multipass launch -c 4 -d 10G -n testfs4lxd`
gave
```
[2022-01-20T14:34:55.777] [error] [lxd request] Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
launch failed: Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
```

**Expected behavior**
A new instance running would be expected. However, `multipass list` shows the new instance in `unknown` state.

**Logs**
[Here](https://pastebin.ubuntu.com/p/hNCGCf6mvF/)

**Additional info**
Ubuntu 21.10
```
multipass version
multipass   1.9.0-dev.338+ga1ea65fb
```

**Additional context**
```
lxd --version
4.22
```

**Comment by Saviq** [comment]
Looks like we're doing something wrong with the `root` device pool:

```json
"root":{"path":"/","pool":"","size":"10737418240","type":"disk"}
```

**Comment by Saviq** [comment]
Steps to reproduce:

```plain
$ sudo snap install multipass
multipass 1.8.0 from Canonical✓ installed
$ sudo multipass set local.driver=lxd
$ multipass launch
Launched: lenient-sauger
$ sudo snap run --shell multipass.multipassd -c 'touch $SNAP_COMMON/snap_refresh'
$ sudo snap restart multipass
$ multipass launch
[2022-01-21T18:24:44.367] [error] [lxd request] Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
launch failed: Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
```

**Comment by townsend2010** [comment]
I determined that if the snap refreshes with running LXD instances, it will not detect the storage pool since `hypervisor_health_check()` is not called (which sets up the `storage_pool` variable) when there are running instances.  The logic does not `stop` instances when a snap refresh is detected. :facepalm:
