### ISSUE TITLE
[set] fix handling of empty passphrases

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2410]
```plain
$ sudo multipass set local.passphrase=
# or
$ sudo multipass set local.passphrase  # pass empty twice
Please enter passphrase:
Please re-enter passphrase:
$ sudo multipass get local.passphrase  # bug https://github.com/canonical/multipass/issues/2398
d72c87d0f077c7766f2985dfab30e8955c373a13a1e93d315203939f542ff86e73ee37c31f4c4b571f4719fa8e3589f12db8dcb57ea9f56764bb7d58f64cf705
$ multipass register ""
```

This shouldn't work. Setting an empty passphrase should set the internal representation to empty, and so it should never work.

Not sure if interactive `set` should ever allow empties.

**Comment by townsend2010** [comment]
@Saviq,

Ok, I agree we shouldn't be accepting an empty passphrase as a legitimate passphrase, but should setting an empty passphrase disable the passphrase altogether like when no initial passphrase is set?  I think it should if an admin doesn't want another client to be able to connect no matter what.  Or have the ability to disable the passphrase when we support doing this in `multipassd set local.passphrase`?

**Comment by Saviq** [comment]
> but should setting an empty passphrase disable the passphrase altogether like when no initial passphrase is set?

I wrote:
> Setting an empty passphrase should set the internal representation to empty, so it should never work.

By "it" I meant `multipass register`. If the stored hash is empty, no hash sent over will ever match, so no way to register. And yeah, messaging that the passphrase is not set is good.

> Or have the ability to disable the passphrase when we support doing this in multipassd set local.passphrase?

What do you mean by that?

**Comment by townsend2010** [comment]
> By "it" I meant `multipass register`. If the stored hash is empty, no hash sent over will ever match, so no way to register. And yeah, messaging that the passphrase is not set is good.

Ah, ok, I was thought "it" meant setting an empty passphrase should not work, but I get it now.

> What do you mean by that?
Since I was confused by the aforementioned "it", I was suggesting we need some way to unset the passphrase and thought the `multpassd set local.passphrase` (notice the `d' there) may be a place to do it since I thought you were suggesting that the normal way should not work :wink:

I think we're all straight here.
