### ISSUE TITLE
Can't switch back to hyperkit from qemu

### ISSUE THREAD

**Issue by xluffy** [canonical/multipass#2431]
**Describe the bug**

I switch hypervisor from `hyperkit` to `qemu`, and switch back, throw invalid driver

```bash
> sudo multipass set local.driver=hyperkit
Invalid setting 'local.driver=hypekit': Invalid driver
```
This is my current driver

```bash
> sudo multipass get local.driver
qemu
```

**To Reproduce**
How, and what happened?
1. `sudo multipass set local.driver=qemu`
2. `sudo multipass set local.driver=hyperkit`

**Expected behavior**
What did you expect to happen?

Switch back to hyperkit hypevisor

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 11.6]
- `multipass version`
- `multipass info --all`

```
$ multipass version
multipass   1.8.1+mac
multipassd  1.8.1+mac

$ multipass info --all
Name:           idealistic-jennet
State:          Stopped
IPv4:           --
Release:        --
Image hash:     0ab8c37e5d3c (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           novel-raven
State:          Stopped
IPv4:           --
Release:        --
Image hash:     0ab8c37e5d3c (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

```

**Additional context**

**Comment by xluffy** [comment]
I try to delete all VM and purge, stil error

```
> mp ls
Name                    State             IPv4             Image
idealistic-jennet       Stopped           --               Ubuntu 20.04 LTS
novel-raven             Stopped           --               Ubuntu 20.04 LTS

> mp delete idealistic-jennet novel-raven
> mp purge
> sudo multipass set local.driver=hyperkit
Invalid setting 'local.driver=hyperkit': Invalid driver

**Comment by Saviq** [comment]
@xluffy hey, and you're on an Intel Mac, or an M1?

**Comment by xluffy** [comment]
@Saviq that is M1 chipset.

**Comment by Saviq** [comment]
@xluffy not a bug, then. Hyperkit doesn't support the M1 architecture. We'll be phasing it out soon, too.

Any reason you wanted to switch?

**Comment by xluffy** [comment]
I'm not sure default hypervisor, as your commend, default hypervisor on macOS M1 is `qemu`? I think default hypervisor is `hyperkit`, so I try to switch for testing, no special reason

**Comment by Saviq** [comment]
On the M1 `qemu` is the default, yes. In fact, it's the only available one.
