### ISSUE TITLE
Issues with unicode characters in image path

### ISSUE THREAD

**Issue by mohamedsayed18** [canonical/multipass#2442]
**Describe the bug**
When using the `snapcraft` command to build a snap, I face the following error:
```
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-pub-sub" does not exist
launch failed: Cannot read image format: qemu-img failed (Process returned exit code: 1) with output:
qemu-img: Could not open '/var/snap/multipass/common/cache/multipassd/vault/images/snapcraft-core18-٢٠٢٠١١١١/bionic-server-cloudimg-amd64-disk.img': Could not open '/var/snap/multipass/common/cache/multipassd/vault/images/snapcraft-core18-٢٠٢٠١١١١/bionic-server-cloudimg-amd64-disk.img': Permission denied

An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

**To Reproduce**
How, and what happened?
Typing the `snapcraft` command

**Expected behavior**
The expected behavior is to build a snap

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: ubuntu 18.04
- `multipass   1.8.0`
- `multipass info --all`

**Additional context**
I made a fix around it by changing the language format of the system settings -> region & Language -> Formats, change it to US or UK or any other English format, I think it has a problem reading a directory with Arabic characters.

**Comment by Saviq** [comment]
Hi @mohamedsayed18, thanks for the report. Could you please provide the output of `multipass launch snapcraft:core18 --name snapcraft-pub-sub -vvvv`? I don't understand where the extra characters are coming from, there should just be numbers there:

```plain
$ ls /var/snap/multipass/common/cache/multipassd/vault/images/
snapcraft-core18-20201111
```

**Comment by mohamedsayed18** [comment]
> there should just be numbers there:

Yes this numbers are Hindi-Arabic numerals `٢٠٢٠١١١١`, but as I mentioned when I switched to English it worked fine and the output of the above commands are
```
$ multipass launch snapcraft:core18 --name snapcraft-pub-sub -vvvv
launch failed: instance "snapcraft-pub-sub" already exists
```
```
$ ls /var/snap/multipass/common/cache/multipassd/vault/images/
focal-20220207  snapcraft-core18-20201111
```
These outputs are after I switched the language of the system to English

**Comment by Saviq** [comment]
Right, so it sounds like we're unnecessarily translating between ascii and the local language somewhere. We should be able to reproduce locally.
