### ISSUE TITLE
Windows: launch: timed out waiting for response

### ISSUE THREAD

**Issue by joedborg** [canonical/multipass#2444]
**Describe the bug**
Trying to launch VMs on Windows with Hyper-V.  The VM comes up and I can access it via the Hyper-V console, but not via Multipass due to following errors.

**To Reproduce**
How, and what happened?
1. `multipass launch --name test-uk8s`
1. `timed out waiting for response` (even though VM is up in hyper-v console).
1. `multipass shell test-uk8s`
1. `shell failed: ssh connection failed: 'Timeout connecting to test-uk8s.mshome.net'` 

**Expected behavior**
VM to start.

**Logs**
https://pastebin.ubuntu.com/p/FCW2BffjXN/

**Additional info**
 - OS: Windows 11 Pro
- `multipass version` 
`1.8.0+win`
- `multipass info --all` 
`info failed: ssh connection failed: 'Timeout connecting to test-uk8s.mshome.net'`

**Additional context**
Used to work fine, not sure I've changed anything.

**Comment by ricab** [comment]
Hi @joedborg, to be sure, you don't just see the VM running in Hyper-V manager but can actually log into the VM in the Hyper-V console, correct? And the same cloud-init used to work? Could you be experiencing any of the [known issues](https://multipass.run/docs/troubleshooting-networking-on-windows) on Windows? 

Also, did you happen to filter only "Information" and higher level messages in that log? It would be interesting to see debug messages too, if you have them.

**Comment by joedborg** [comment]
Ah thanks @ricab, I'd only tried to fix "Default Switch going awry" and missed off "Stale Internet Connection Sharing lease", which turned out to be the issue.
