### ISSUE TITLE
Multipass, cannot shell instance, shell failed: [ssh client] channel creation failed: ''

### ISSUE THREAD

**Issue by RMIRANDA9** [canonical/multipass#2457]
**Describe the bug**
Describe what your problem is.

Hello, Multipass community! I have been using multipass for the last couple of months, great tool, have not had problems with it.

Recently I installed an update in my windows 11 pc and I cannot longer shell into one of my instances ( I have 2 instances), the other one is working just fine.

This is the error I get when I try to shell into the instance:

shell failed: [ssh client] channel creation failed: ''

or if I try the following command:

> multipass info --all
info failed: [ssh proc] failed to open session channel: ''

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [Windows 11]
- multipass version
multipass   1.8.0+win
multipassd  1.8.0+win
- `multipass info --all`

**Additional context**

**Comment by Saviq** [comment]
Hi @RMIRANDA9 are you using Multipass through Hyper-V (the default) or VirtualBox?

Either way, it sounds like the instance isn't starting up properly. You could open the VM in Hyper-V ([or VBox](https://multipass.run/docs/using-virtualbox-in-multipass-windows) and see if there's any clue there.

You can also interrupt the boot process tapping Tab / Shift as soon as you power it on there to do any recovery.

**Comment by RMIRANDA9** [comment]
I am using multipass with VirtualBox

**Comment by Saviq** [comment]
@RMIRANDA9 whenever interacting with the VMs through VirtualBox, then, make sure to stop the Multipass tray GUI, or even `Stop-Service Multipass` altogether to avoid them fighting each other.

**Comment by RMIRANDA9** [comment]
Hello @Saviq, appreciate it. How can I do that? I am not familiar with the virtualbox gui. Or how to interact with the multipass instances from the Virtualbox gui. I am following the link you sent [using VB with multipass on Windows](https://multipass.run/docs/using-virtualbox-in-multipass-windows)

**Comment by Saviq** [comment]
@RMIRANDA9 to stop the Multipass GUI, click on the orange M icon in your system tray (if it's even there) and Quit it.

To stop the service, use `Stop-Service Multipass` in an PowerShell as Adminstrator.

Once you have the VirtualBox GUI open, the instances should be there under "Multipass" and you should be able to control them as usual, there's plenty of guides out there.

**Comment by RMIRANDA9** [comment]
Ok Done!. I see my instances in the VirtualBox GUI now. I stopped all the services with 
`Stop-Service Multipass` in PS. Now how do I restart the service in PS or cmd?

**Comment by Saviq** [comment]
@RMIRANDA9 `Start-Service Multipass`, but did you confirm already what's gone wrong with your instance? If there's nothing important in the instance, it may be easiest to `multipass delete --purge` it and start anew?

**Comment by RMIRANDA9** [comment]
no my friend I have not been able to tell what's wrong with the instance. I am restarting the service to see if I can start the instance and get into the shell.

**Comment by RMIRANDA9** [comment]
I got to revive the instance, got important stuff in there.

**Comment by RMIRANDA9** [comment]
start failed: The following errors occurred:
                  : timed out waiting for response

**Comment by RMIRANDA9** [comment]
I cannot see the virtual machine window in VirtaulBox, tried reinstalling VirtualBox, it did not work. I am still trying to figure this out. Need to see the host machine window screen in order to debug and recover the instance.

**Comment by RMIRANDA9** [comment]
This is the new error when I try to shell
`shell failed: ssh connection failed: 'Timeout connecting to 127.0.0.1'`

**Comment by Saviq** [comment]
> I cannot see the virtual machine window in VirtaulBox

What do you mean by that? You can't see the instance in question there? Can you post exact steps you took and a screenshot of what you got, and what did you expect?

**Comment by svhy** [comment]
> 这是我尝试外壳时的新错误 `shell failed: ssh connection failed: 'Timeout connecting to 127.0.0.1'`

Too many such questions

**Comment by ricab** [comment]
Hi @svhy, if you open a new issue and fill in the requested details, we can try to help you find what the problem is. [This](https://multipass.run/docs/troubleshoot-networking) may also be helpful.

Closing this issue as stale now.

**Comment by sinke237** [comment]
I have this same issue. However, i am on Ubuntu 20.04

`multipass stop more-human
stop failed: [ssh proc] failed to open session channel: ''
`

It was working just fine and then this.
when i execute an instance, I am not able to run any command inside of it.
