### ISSUE TITLE
IPv4: N/A

### ISSUE THREAD

**Issue by tom055** [canonical/multipass#2459]
When I execute the following command, the ip address is empty, how to solve this problem

os: windows10 enterprise

![20220225155046](https://user-images.githubusercontent.com/17687356/155676458-af75824d-0d2d-4dfe-8b7a-c59007473eb5.png)

**Comment by tom055** [comment]
When I specify the network, but IPv4 is still null,and enp0s8 is DOWN ,Can you help me look again? Thank you.
![3333](https://user-images.githubusercontent.com/17687356/155917474-94aaf64e-8a4b-49bc-bd72-145e5d3e7771.png)

**Comment by Saviq** [comment]
@tom055 you asked for `mode=manual`, you need to configure the IP yourself in that case.

Or use the default, `mode=auto` instead.

**Comment by ranjanprj** [comment]
This worked for me on Windows Enterprise with Oracle Virtualbox

List all network
```
multipass networks
Name                    Type      Description
Ethernet                ethernet  Intel(R) Ethernet Connection (7) I219-LM
Npcap Loopback Adapter  ethernet  Npcap Loopback Adapter
Wi-Fi                   wifi      Intel(R) Wireless-AC 9560
```

Then select the network name and launch
```multipass launch --network Wi-Fi```

Then shows ipv4 address

```
C:\>multipass info legitimate-finch
Name:           legitimate-finch
State:          Running
IPv4:           192.168.1.11
Release:        Ubuntu 22.04.2 LTS
Image hash:     9bbe9364e298 (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.28 0.08 0.03
Disk usage:     1.5GiB out of 4.7GiB
Memory usage:   180.9MiB out of 953.5MiB
```

**Comment by whmcquaid** [comment]
I was able to get an IP for my instances using my windows 11 machine.  I had to 'multipass set local.bridged-network' to the network I am using. Then add '--bridged' to the end of the 'multipass launch' command.
