### ISSUE TITLE
Multipass installer shows "Warning! PATH too long installer unable to modify PATH!"

### ISSUE THREAD

**Issue by bobcode99** [canonical/multipass#2460]
**Describe the bug**
When i running Multipass installer, came out with "Warning! PATH too long installer unable to modify PATH!"

**To Reproduce**
How, and what happened?

0. Using Windows 10
1. Install VirtualBox
2. download the multipass installer (multipass-1.8.0+win-win64.exe)
3. run it

**Expected behavior**

I'm not sure others Windows device install Multipass will get this error.

![image](https://user-images.githubusercontent.com/39816893/155838230-087273c4-561a-4f61-8afc-41f0723a05c8.png)

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [Windows 10 Home Single Language, version: 21H2]

**How to solve**
Add `C:\Program Files\Multipass\bin` to the user variables PATH manually.

**Comment by Saviq** [comment]
Hi @bobcode99, looks like your PATH is just too long for the installer to deal with. As you say, the solution is to add it yourself. We won't be able to fix that unless we redo our installer significantly…
