### ISSUE TITLE
Multipass requires a reinstall after every reboot on Windows 11

### ISSUE THREAD

**Issue by pfworks** [canonical/multipass#2468]
**Describe the bug**
I updated to Windows 11 from Windows 10. multipass could not find any of my instances, nor could multipass commands connect to the daemon. I uninstalled multipass and re-installed it (removing all data). This made it work. However, when I reboot, I encounter the same issue, and have to re-install to get multipass to work again, and I lose my instances.

**To Reproduce**
How, and what happened?
1. update from Win 10 to Win 11
2. Try to start any instance or run any multipass command
3. re-install multipass (remove all data)
4. repeat step 2, it works
5. reboot
6. goto step 2

**Expected behavior**
What did you expect to happen?
I expect that not only after a reboot would my instances be available and running, as they were before, but I would not also have to re-isntall multipass and my images after every reboot.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
Next time I reboot I will do this.

**Additional info**
 - OS: Windows 11 Pro 21H2
- PS C:\Users\micro> multipass version
multipass   1.8.0+win
multipassd  1.8.0+win
- PS C:\Users\micro> multipass info --all
Name:           test
State:          Running
IPv4:           172.18.87.174
Release:        Ubuntu 20.04.4 LTS
Image hash:     3d7282d3e92b (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     14.0G out of 96.7G
Memory usage:   6.8G out of 7.8G
Mounts:         --

**Additional context**

**Comment by Saviq** [comment]
Hi @pfworks, this sounds very much like #1119, even though it should not happen over reboots… When it does (after a reboot), can you look in `C:\Windows\system32\config\systemprofile\` for Multipass files? In Hyper-V ([or VirtualBox](https://multipass.run/docs/using-virtualbox-in-multipass-windows)), do you see the instances and can you boot them?

**Comment by pfworks** [comment]
There are no files, just an AppData directory. In hyper-v, the instance says it is running. multipass is just in a restart loop as it can't find files.

**Comment by pfworks** [comment]
Also, the first several reboots I did had updates. I did a few reboots w/o updates and it was fine, and now just took a set of updates, and the problem is here again.

**Comment by pfworks** [comment]
Here is where the files are: Windows/System32/config/systemprofile/AppData/Roaming/multipassd
Any ETA on when this can get fixed? Having to uninstall/reinstall multipass and my instances gets kind of old. Thx

**Comment by Saviq** [comment]
@pfworks the 1.9.0 release will use `%PROGRAMDATA%\Multipass` for its storage. It won't migrate existing instances, so when uninstalling, ask it to remove all data. It's in candidate phase, you can try it here:

https://github.com/canonical/multipass/releases/tag/v1.9.0-rc

**Comment by Saviq** [comment]
Fixed by #2485

**Comment by pfworks** [comment]
Great, right before my next updates, I’ll get this (or the actual released one if it’s out).

thx

**Comment by pfworks** [comment]
Installed, we'll see how we do after the next updates. Thx
