### ISSUE TITLE
configurable instances directory location

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#247]
It would be nice to have a config option which allows to specify a path where multipass would allocate instances

**Comment by Saviq** [comment]
I'll mark this as a duplicate of one that has more details:

Duplicate of #1215

**Comment by Saviq** [comment]
Duplicate of #1215

**Comment by Saviq** [comment]
Hi @marosg42, I've described a workaround in https://github.com/canonical/multipass/issues/1215#issuecomment-705408845.
