### ISSUE TITLE
Invalid handling of Windows ReleaseId value

### ISSUE THREAD

**Issue by L-607** [canonical/multipass#2474]
![image](https://user-images.githubusercontent.com/36064720/157262808-0f3c01c1-f9eb-48fe-ac02-5368ab304cdc.png)
Windows 10 version is 19043 but not working

**Comment by Saviq** [comment]
Hi @607qwq, it's likely some unicode (#1314) that's throwing us off :/

Could you please run the command with `-vvvv` so we can see what information we can get?

**Comment by 607qwq** [comment]
Hi,@Saviq ，this is screenshot.But I selected virtualbox
![image](https://user-images.githubusercontent.com/36064720/157349612-9f3eceee-0add-461c-831e-cc535adc3044.png)

**Comment by Saviq** [comment]
@607qwq one more `v` please, so we can see the output of those commands :)

**Comment by 607qwq** [comment]
![image](https://user-images.githubusercontent.com/36064720/157431887-c38db815-6ca4-4b2a-ae94-8b1a3b2f0fa2.png)

**Comment by ricab** [comment]
Hi @607qwq, about the selection of virtualbox not working, did you select it in the installer? If so, you may have fallen prey to #2179. `multipass set local.driver=virtualbox` should do it.

**Comment by Saviq** [comment]
Either case, we're assuming `ReleaseId` will be an integer, and making sure that's higher than `1803`. Obviously `21H1` is not…

**Comment by 607qwq** [comment]
Hi @ricab ,I  select it in the installer. I use  "multipass get local.driver" this is screenshot
![image](https://user-images.githubusercontent.com/36064720/157435465-6dfe51ae-19c2-4870-8a13-4b6ca2f03023.png)

**Comment by Saviq** [comment]
@607qwq restart the `Multipass` service or reboot, the bug @ricab mentioned means that the service did not notice the driver change, and is defaulting to Hyper-V. Running `multipass set…` would also cause the service to restart.

**Comment by 607qwq** [comment]
I reboot the computer and it worked😂😂😂

**Comment by 607qwq** [comment]
I reboot  computer， but got a new problem
![image](https://user-images.githubusercontent.com/36064720/157438551-38b528f2-c05c-4b71-b5db-9b04d4fd58ed.png)

**Comment by Saviq** [comment]
@607qwq sorry for the late reply. Could you please translate the error message?

**Comment by 607qwq** [comment]
"The system cannot find the file specified"

**Comment by Saviq** [comment]
Oh. Do you have VirtualBox installed? At what path?

**Comment by 607qwq** [comment]
I installed at E: ，not at C：

**Comment by Saviq** [comment]
@607qwq you'll need to add that location to the system PATH, then (and reboot or stop/start the Multipass service), so that Multipass can find it.

**Comment by 607qwq** [comment]
> I installed at E: ，not at C：



> @607qwq you'll need to add that location to the system PATH, then (and reboot or stop/start the Multipass service), so that Multipass can find it.

Cool its working，thanks @Saviq

**Comment by 607qwq** [comment]
> 

Cool its working，thanks @Saviq
