### ISSUE TITLE
Flag to accept usage data to be sent ?

### ISSUE THREAD

**Issue by lucj** [canonical/multipass#2478]
**What are you trying to do?**
I use Multipass in many scripts and from time to time the script cannot launch VM as it waits for an input regarding usage data sending.

```
root@luc:~# multipass launch -n demo
One quick question before we launch … Would you like to help
the Multipass developers, by sending anonymous usage data?
This includes your operating system, which images you use,
the number of instances, their properties and how long you use them.
We’d also like to measure Multipass’s speed.

Send usage data (yes/no/Later)?
```

That is not a problem when VM are launched in a terminal but that is painful when automated in a script.

**What's your proposed solution?**

Adding a flag to accept usage data to be sent to developers ?

**Comment by townsend2010** [comment]
Hi @lucj,

This whole thing will be going away once we merge #2466.  Since that is inflight, I'm just going to close this report.  Thanks!

**Comment by lucj** [comment]
Thanks @townsend2010.
Do you know when the next release, containing that merge, will be delivered ?

**Comment by townsend2010** [comment]
Hey @lucj,

We are currently preparing the next release which will include that merge and will hopefully have it released in the next few weeks.

**Comment by lucj** [comment]
Hi @townsend2010, out of curiosity, in the current version, how often does Multipass ask for sending usage data ? I'm just trying to find a way to make sure my scripts are not stopped (which would happen in case Multipass waits for user input) :)

**Comment by Saviq** [comment]
@lucj every 3 launches until you answer either yes or no.
