### ISSUE TITLE
Multipass does not add iptables rules on Ubuntu 21.10

### ISSUE THREAD

**Issue by tse77** [canonical/multipass#2488]
Me and my colleague  which recently installed Multipass with LXD backend on our Ubuntu 20.04 machines have no issues launching a VM with for example 20.04 image, and listing iptables rules we can see Multipass (or LXD) have added some rules.

But two other colleague which are running Ubuntu 21.10 can not launch VM with Multipass. It get stuck waiting for SSH to be up:

`2022-03-24T11:01:52+01:00 multipassd[135826]: Waiting for SSH to be up`

It get stuck in a loop spamming entries to syslog which eating disk space as well

After some investigation we could see that no iptables rules were added on those two Ubuntu 21.10 laptops and we can figure out why. Is it a bug or have we missed something?

Using the following versions installed through snap:
`lxd version 4.24`
`multipass   1.8.0`

**Comment by Saviq** [comment]
@tse77 hey, did you look at both `iptables-legacy -S` and `iptables-nft -S`?

Either way, if you're using the LXD driver, it's LXD that manages the tables, Multipass is hands off in this case.

**Comment by tse77** [comment]
Thanks for the reply. It must be related to the switch to nftables in Ubuntu 21.10 some how. I have not had time to do further investigation yet but hopefully have this week but as you mentioned it is LXD which manages the tables so we should start look there.

I guess that you can close this issue now.
