### ISSUE TITLE
Multipass can't delete LXD instances that go into Error state

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2492]
**Describe the bug**
When using the LXD backend, after a failed launch where the instance gets into an error state (112 from LXD, translated to unknown in multipass), multipass is unable to delete the instance:

```
$ multipass delete --purge --all
[2022-03-24T17:29:10.900] [error] [lxd request] Operation completed with error: (400) The instance cannot be cleanly shutdown as in Error status
delete failed: Operation completed with error: (400) The instance cannot be cleanly shutdown as in Error status
```

We would need to give LXD the equivalent of the `--force` flag in such cases. 

**To Reproduce**
Because of https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1935880 , a pretty reliable way to get a LXD vm in error state is just
1. `multipass launch --cpus 2`
    - Until the remainder of #2250 is fixed, this will loop until timeout, leaving the instance in unknown state
1. `multipass delete --purge <instance>` then fails as above

**Expected behavior**
Multipass would be able to delete the instance.

**Comment by oscarmparedes** [comment]
I had the same issue and restarting lxd via snap fixed the issue.

**Comment by aatrcoutinho** [comment]
the same problem happened to me today. And now, How can I remove the VM?

**Comment by ricab** [comment]
Hi @aatrcoutinho, until we get this fixed, you can delete instances in LXD directly: `lxc delete <instance-name> --project=multipass`

**Comment by holta** [comment]
> Hi @aatrcoutinho, until we get this fixed, you can delete instances in LXD directly: `lxc delete <instance-name> --project=multipass`

Lifesaver !!  This worked for me too:

```
lxc delete deb12 --project=multipass --force
```

Huge Thanks @ricab as Multipass accidentally does serious damage (blocking deletion of the VM, and even blocking the host machine from rebooting) when Multipass effectively loses control of VM's like this one:

```
multipass launch -n deb12 https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2
```

CLARIF: The above worked in recent weeks, but no longer works today, painfully freezing out many/most all Multipass actions.  Even `snap restart multipass.multipassd` does not help.  Not even a forced reboot of the entire host PC helped.

Hence the need to **_force_** the deletion of a Multipass VM using LXD.  As Multipass itself is unfortunately not capable of reliably deleting its own VM's:

```
# multipass info deb12
info failed: ssh connection failed: 'Connection refused'

# multipass stop deb12
Stopping deb12 \[2022-11-05T12:19:34.936] [error] [lxd request] Timeout getting response for GET operation on unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operations/94e4dd5b-67a6-47d1-ae91-1083e0e96044/wait?project=multipass
[2022-11-05T12:19:34.937] [error] [lxd request] Timeout getting response for GET operation on unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operationstop failed: Timeout getting response for GET operation on unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operations/94e4dd5b-67a6-47d1-ae91-1083e0e96044/wait?project=multipass

# multipass delete deb12
[2022-11-05T12:35:55.949] [error] [lxd request] Timeout getting response for GET operation on unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operations/8d951713-031f-461f-8512-93d907fa1d09/wait?project=multipass
[2022-11-05T12:35:55.949] [error] [lxd request] Timeout getting response for GET operation on unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operations/8d951713-031f-461f-8512-93d907fa1d09/wait?project=multipass
delete failed: Timeout getting response for GET operation on unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operations/8d951713-031f-461f-8512-93d907fa1d09/wait?project=multipass
```

*This lifesaving trick should be better documented within https://multipass.run/docs e.g. at [remove-an-instance](https://multipass.run/docs/remove-an-instance) or some similar space, Thanks All!*

**Comment by holta** [comment]
To CLARIFY the above, even this very latest Edge Channel version of Multipass cannot reliably delete its own VM's / instances:

```
# multipass --version
multipass   1.12.0-dev.379+g6cfdc875
multipassd  1.12.0-dev.379+g6cfdc875

# snap info multipass
...
  latest/edge:      1.12.0-dev.379+g6cfdc875 2022-10-30 (8154) 112MB -
installed:          1.12.0-dev.379+g6cfdc875            (8154) 112MB -
```

**Comment by ricab** [comment]
@holta, Multipass is designed to launch Ubuntu VMs, not Debian. You can try, of course, but you're on your own then. It might work, but it is no surprise that it doesn't.

**Comment by holta** [comment]
Just FYI Debian 12 instances worked fine with Multipass in the past.

The Much Larger Point (this ticket!) is that Multipass accidentally sabotages the host PC (preventing the "reboot" command from working, etc) when any instance encounters everyday such testing errors.

_So your original request is quite important:_ Multipass indeed needs to evolve to be able to delete dysfunctional instances -- according to the instructions it provides: https://multipass.run/docs/remove-an-instance

**Comment by holta** [comment]
Just FYI this bug has become substantially more severe in recent weeks.  I don't know why.

Certainly Multipass instances (e.g. Ubuntu 22.04 and Ubuntu 23.04 pre-release) frequently fail to start.  FYI the Host PC is Ubuntu Server 22.04.

The only workaround I've found so far is to repeatedly reboot the Host PC (rebooting it twice would appear to be often necessary) until the Multipass instance in question...finally boots cleanly.
