### ISSUE TITLE
[multipassd-vm-instances.json] Empty file

### ISSUE THREAD

**Issue by dreamwhite** [canonical/multipass#2494]
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. Tried to edit configuration of a VM I launched on `/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`

**Expected behavior**

The file should have contained stuff but it's actually empty: `{}`

**Logs**
There's no log to be fair

**Additional info**
 - OS: macOS Monterey 12.3
- `multipass version`: 

```
multipass   1.8.1+mac
multipassd  1.8.1+mac
```
- `multipass info --all`:

Name:           InvalidArgument
State:          Running
IPv4:           192.168.64.6
Release:        Ubuntu 21.10
Image hash:     96768217b9b5 (Ubuntu 21.10)
Load:           0.13 0.37 0.19
Disk usage:     1.7G out of 19.2G
Memory usage:   139.6M out of 3.8G
Mounts:         --

Is this a bug on my side or multipass on macOS contains bugs?

**Comment by Saviq** [comment]
@dreamwhite did you stop Multipass first? There's steps on how to do this in #1158.

I'm going to close, please reopen if you find that you can't see the contents still (note on Apple M1, or if you switched to the `qemu` driver, there's an extra `qemu` in the path).

**Comment by dreamwhite** [comment]
Hi @Saviq thank you so much for the reply.
I firstly stopped multipass using `multipass stop --all` and double checked `multipass list` that reports every VM is stopped.

Then I checked `/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json` but it's still empty as you can see in the following screenshot...

![image](https://user-images.githubusercontent.com/17933708/160298715-c14a4082-3961-44dc-90d4-f7b28656060f.png)

> (note on Apple M1, or if you switched to the `qemu` driver, there's an extra `qemu` in the path).

Regarding this point what do you mean? I've used `sudo multipass set local.driver=qemu` to switch to `QEMU` driver and the VMs correctly start with QEMU. Am I missing something? I've followed the official instructions available [here](https://multipass.run/docs/using-libvirt) under the paragraph `Switching Back`.

Also, and I don't think it's a multipass related issue but rather a QEMU implementation on macOS, despite I give 4GB of RAM to my VM, it uses up to 8GB. Is this behaviour known to you/the dev team, and eventually how should I proceed? I wanna make clear that I don't care much about RAM usage since I have 16GBs, but it's kinda frustrating abusing of my RAM chips haha

**Comment by Saviq** [comment]
@dreamwhite you need to stop Multipass, not just its instances.

E.g.:
```plain
$ sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
```

> Regarding this point what do you mean?

Exactly, so the correct path is (`qemu/` emphasized):
<pre>/var/root/Library/Application\ Support/multipassd/<b>qemu/</b>multipassd-vm-instances.json</pre>

> despite I give 4GB of RAM to my VM, it uses up to 8GB.

How do you measure that?

**Comment by dreamwhite** [comment]
> @dreamwhite you need to stop Multipass, not just its instances.

Oh okay, so I was completely missing the right file. Now I see content in `/var/root/Library/Application\ Support/multipassd/qemu/multipassd-vm-instances.json` with all the configuration stuff.

> How do you measure that?

By simply using `Activity Monitor.app` I see that `qemu-system-x86_64` most of the time uses up to twice the pre-allocated RAM size. 

In this screenshot it uses more RAM than the allocated (4.3GB) and the Virtual Memory size is 37GB. Is this an issue of QEMU or what?

![image](https://user-images.githubusercontent.com/17933708/160359816-35e31589-28a5-4f4b-931f-a8bfff835f84.png)

**Comment by Saviq** [comment]
@dreamwhite note that real memory use is notoriously hard to measure, even more so . QEMU does not pre-allocate all the memory you tell it to give the VM. The host kernel does a lot of things to optimize the use of RAM (using all the available RAM it is _not_ abuse, it's a performance optimization).

In any case, unless you see the instance getting more total memory (`free -m`) and there's the right `-m <amount>` value on the qemu command line, Multipass is doing the right thing. If you want to follow up on this, qemu itself would be the right forum.

For reference, here's a SO question talking about the same:

https://serverfault.com/questions/954663/qemu-process-memory-usage-greater-than-guest-memory-usage

**Comment by dreamwhite** [comment]
Okay thank you so much and thanks for the effort :D
