### ISSUE TITLE
Interfaces missing in `multipass networks` on Windows

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2500]
Hello, 

Would it be possible to have a detailed example on how to set a brdige network with multipass?  I am currently running multipass on `Windows` and I am having trouble exposing my service on the network.

So far I have been trying the following (I am using Hyper-V): 
```powershell
# List of available network interfaces (I wonder if the ones of interest are not missing?)
PS C:\Windows\system32> multipass networks
Name            Type    Description
Default Switch  switch  Virtual Switch with internal networking
WSL             switch  Virtual Switch with internal networking

PS C:\Windows\system32> multipass set local.bridged-network="Default Switch"
PS C:\Windows\system32> multipass launch --bridged
Launched: compatible-chicken
PS C:\Windows\system32> multipass list
Name                    State             IPv4             Image
compatible-chicken      Running           172.20.227.149   Ubuntu 20.04 LTS
                                          172.20.237.96
```

Making sure I can access the service from the host: 
```powershell
PS C:\Windows\system32> curl http://172.20.227.149:32218/ -UseBasicParsing
StatusCode        : 200
StatusDescription : OK
Content           : Hello, world!
                    Version: 1.0.0
                    Hostname: hello-world-57fbf88c7-xx6p5

RawContent        : HTTP/1.1 200 OK
                    Content-Length: 67
                    Content-Type: text/plain; charset=utf-8
                    Date: Wed, 30 Mar 2022 03:05:01 GMT

                    Hello, world!
                    Version: 1.0.0
                    Hostname: hello-world-57fbf88c7-xx6p5

Forms             :
Headers           : {[Content-Length, 67], [Content-Type, text/plain; charset=utf-8], [Date, Wed, 30 Mar 2022 03:05:01 GMT]}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 67
```

FYI the service is running in `microk8s` but I do not think this is really relevant as I am already able to access the service from the host.

Thanks

_Originally posted by @maximehyh in https://github.com/canonical/multipass/issues/118#issuecomment-1082573152_

**Comment by Saviq** [comment]
@maximehyh I made this into a new issue.

What does `Get-NetAdapter` in PowerShell return for you?

**Comment by maximehyh** [comment]
```powershell
[2022-03-30T08:35:50.570] [debug] [powershell.exe] [10208] started: powershell.exe Get-VMSwitch | Select-Object -Property Name,SwitchType,NetAdapterInterfaceDescription | ConvertTo-Csv -NoTypeInformation | Select-Object -Skip 1 | foreach { $_ -replace '^"|"$|"(?=,)|(?<=,)"','' }
[2022-03-30T08:35:52.045] [debug] [Hyper-V Switch Listing] [10208] PowerShell finished successfully
Name            Type    Description
Default Switch  switch  Virtual Switch with internal networking
WSL             switch  Virtual Switch with internal networking
[2022-03-30T08:35:52.049] [warning] [winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.

```

**Comment by Saviq** [comment]
@maximehyh we'll try and trace what's going on, at least your Ethernet connection should be there in `multipass networks`. In the mean time, you can [create an External Switch in the Hyper-V manager](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/create-a-virtual-switch-for-hyper-v-virtual-machines) and that should be available in `multipass networks` straight away.

**Comment by maximehyh** [comment]
Ok great thanks a lot. Once I create this external switch I can just do the following? 

```
PS C:\Windows\system32> multipass set local.bridged-network="NEW_SWITCH"
PS C:\Windows\system32> multipass launch --bridged
Launched: NEW_VM
PS C:\Windows\system32> multipass list
Name                    State             IPv4             Image
NEW_VM      Running           SOME_IP   Ubuntu 20.04 LTS
                                          SOME_IP   
```

Will II then be able to see an IP provided by the same DHCP as the host in `multipass list`?

**Comment by ricab** [comment]
Hey @maximehyh, glad you managed to work around this, and thanks for reporting. 

To help us understand what is going on, could you please post the output of `Get-NetAdapter -physical | Select-Object -Property Name,MediaType,PhysicalMediaType,InterfaceDescription`?

Also, I am puzzled that `Get-NetAdapter` doesn't show in `multipass networks -vvvv` for you. Are you sure you pasted the full output? Would you mind repeating the command, making sure to use 4 'v's? Thanks in advance.

**Comment by maximehyh** [comment]
Here they are: 

```powershell
PS C:\Windows\system32> Get-NetAdapter -physical | Select-Object -Property Name,MediaType,PhysicalMediaType,InterfaceDescription

Name              MediaType PhysicalMediaType InterfaceDescription
----              --------- ----------------- --------------------
CPU SLOT 3 Port 2 802.3     802.3             Basler GigE Vision Adapter
Ethernet          802.3     802.3             Intel(R) Ethernet Connection X722 for 10GBASE-T
Ethernet 2        802.3     802.3             Intel(R) Ethernet Connection X722 for 10GBASE-T #2
CPU SLOT 3 Port 1 802.3     802.3             Basler GigE Vision Adapter #1
```

```powershell
PS C:\Windows\system32> multipass networks -vvvv
[2022-03-30T11:05:15.620] [trace] [nearby-harrier] [12632] Cmdlet: 'Get-VM -Name nearby-harrier | Select-Object -ExpandProperty State'
[2022-03-30T11:05:15.654] [trace] [nearby-harrier] Running
[2022-03-30T11:05:15.654] [trace] [nearby-harrier] [12632] Output: Running
[2022-03-30T11:05:15.654] [trace] [nearby-harrier] [12632] Cmdlet exit status is 'true'
[2022-03-30T11:05:15.654] [trace] [Hyper-V Switch Listing] PowerShell arguments: Get-VMSwitch, |, Select-Object, -Property, Name,SwitchType,NetAdapterInterfaceDescription, |, ConvertTo-Csv, -NoTypeInformation, |, Select-Object, -Skip, 1, |, foreach, {, $_, -replace, '^"|"$|"(?=,)|(?<=,)"','', }
[2022-03-30T11:05:15.654] [trace] [Hyper-V Switch Listing] PowerShell working dir ''
[2022-03-30T11:05:15.654] [trace] [Hyper-V Switch Listing] PowerShell program 'powershell.exe'
[2022-03-30T11:05:15.654] [trace] [Hyper-V Switch Listing] [0] PowerShell state changed to Starting
[2022-03-30T11:05:15.657] [trace] [Hyper-V Switch Listing] [0] PowerShell state changed to Running
[2022-03-30T11:05:15.658] [debug] [powershell.exe] [17460] started: powershell.exe Get-VMSwitch | Select-Object -Property Name,SwitchType,NetAdapterInterfaceDescription | ConvertTo-Csv -NoTypeInformation | Select-Object -Skip 1 | foreach { $_ -replace '^"|"$|"(?=,)|(?<=,)"','' }
[2022-03-30T11:05:20.346] [trace] [Hyper-V Switch Listing] [17460] PowerShell state changed to NotRunning
[2022-03-30T11:05:20.347] [debug] [Hyper-V Switch Listing] [17460] PowerShell finished successfully
[2022-03-30T11:05:20.347] [trace] [Hyper-V Switch Listing] [17460] Output:
Default Switch,Internal,
WSL,Internal,
ExternalSwitch,External,Intel(R) Ethernet Connection X722 for 10GBASE-T
Name            Type    Description
Default Switch  switch  Virtual Switch with internal networking
ExternalSwitch  switch  Virtual Switch with external networking via "Intel(R) Ethernet Connection X722 for 10GBASE-T"
WSL             switch  Virtual Switch with internal networking
[2022-03-30T11:05:20.352] [warning] [winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.
```

**Comment by ricab** [comment]
Puzzling! It's like multipass is not even calling `Get-NetAdapter`... Would you be able to attach the output of:

```
Get-EventLog -Source Multipass -log application -After "11:05:00" | select -property timegenerated,entrytype,replacementstrings | format-list
```

And thanks again for helping with this. We've already had a [related issue](https://github.com/canonical/multipass/issues/2195) that we couldn't get enough info on. It looks like something is amiss, but we were so far unable to narrow it down.

**Comment by ricab** [comment]
Hey @maximehyh, thanks for the info, I am afraid we're still clueless :/ The one thing that may be able to help us at this point is to run the Multipass daemon manually to get its full output. If you could, that would be great :smile: Here are the steps:

Install [PsExec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) if you don't have it already. If you have the Multipass GUI running (tray icon), quit it (to avoid spamming logs). Then, open two PowerShells, one admin and one regular. In the regular powershell do:

1. `Start-Transcript mp.log`
1. `multipass stop --all` (to avoid spamming the log)

Then, in the admin PowerShell:

1. `Start-Transcript mpd.log`
1. `Stop-Service multipass`
1. `. "$HOME\Downloads\PSTools\PsExec.exe" -s 'C:\Program Files\Multipass\bin\multipassd.exe' --verbosity trace --logger stderr`
1. let it run for 10s or so

Back in the non-admin shell, do:

1. `multipass list` (so we get a reference to compare against)
1. `multipass networks`
1. `Stop-Transcript`

And back to the admin shell:

1. Ctrl+C
1. `Stop-Transcript`
1. `Start-Service multipass`

Upload mp.log and mpd.log, please.

**Comment by ricab** [comment]
BTW, what Multipass, PowerShell, and OS versions do you have? 

Oh and if you could look for any (non-multipass) events that may appear related in Event Viewer->Windows Logs->Application, around the same time when you issue networks (e.g. any failed process launch? any limit reached? any permission denied?). Thanks a lot for your time!

**Comment by maximehyh** [comment]
```powershell
multipass: 1.7.2+win
PSVersion: 5.1.19041.1320
Windows: 
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19043  0
```

**Comment by maximehyh** [comment]
I tried to do the process you described but I cannot `list` or `networks` (as I stopped Multipass service?). I get 
`list failed: cannot connect to the multipass socket`

Also now I cannot launch multipass anymore. I guess rebooting the machine should relaunch the service. 

```powershell
PS C:\Users\User>  Start-Service multipass
Start-Service : Failed to start service 'Multipass Service (multipass)'.
At line:1 char:2
+  Start-Service multipass
+  ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommand
   Exception
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

```

**Comment by ricab** [comment]
Ahha! Glad it's sorted. 

@maximehyh the the `PsExec` line in those instructions is meant to run the same thing as the service. Anyway, you should be able to restart it as per the last step: `Start-Service multipass`.

**Comment by maximehyh** [comment]
Nice thanks a lot for everything!

**Comment by maximehyh** [comment]
It looks like my system is forcing me to install 1.7.2 even when downloading 1.8 or 1.9beta. Is there a minimal windows release necessary?

**Comment by Saviq** [comment]
> It looks like my system is forcing me to install 1.7.2 even when downloading 1.8 or 1.9beta.

What do you mean "forcing you"?

> Is there a minimal windows release necessary?

Windows 10 1803 (so three years old), and that hasn't changed in ages.

**Comment by Saviq** [comment]
Ah yes, the installer goes through uninstall first.

Sorry for the reopen, fat fingers.

**Comment by maximehyh** [comment]
FYI here is what I see now: 
```
PS C:\WINDOWS\system32> multipass networks
Name            Type    Description
Default Switch  switch  Virtual Switch with internal networking
WSL             switch  Virtual Switch with internal networking
Wi-Fi           wifi    Intel(R) Wi-Fi 6E AX210 160MHz
```

And the output of ` Get-NetAdapter`

```
Wi-Fi                     Intel(R) Wi-Fi 6E AX210 160MHz               13 Up           F4-46-37-D1-C1-DA       650 Mbps
vEthernet (WSL)           Hyper-V Virtual Ethernet Adapter #2          36 Up           00-15-5D-4C-CA-A2        10 Gbps
Bluetooth Network Conn... Bluetooth Device (Personal Area Netw...      12 Disconnected F4-46-37-D1-C1-DE         3 Mbps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             23 Up           00-15-5D-04-BE-98        10 Gbps
```

**Comment by ricab** [comment]
Hey @maximehyh, Multipass considers only physical interfaces (`-physical` to `Get-NetAdapter `).
