### ISSUE TITLE
Add Ubuntu 22.04 on Windows and macOS

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2511]
When 22.04 gets released, we need to enable it on Windows and macOS

**Comment by bermi** [comment]
Since [22.04 release announcement](https://ubuntu.com/blog/ubuntu-22-04-lts-released) states

> For Windows and macOS developers, Multipass provides Ubuntu 22.04 LTS VMs on demand with full cloud-init for cloud prototyping at home.

Should this be prioritized?

**Comment by Saviq** [comment]
@bermi, all, you can already get it with the [1.9.0 RC](https://github.com/canonical/multipass/releases/tag/v1.9.0-rc), final coming next week:

```plain
$ multipass find
Image                       Aliases           Version          Description
# ...
22.04                       jammy             20220420         Ubuntu 22.04 LTS
# ...
```

**Comment by bermi** [comment]
Thanks @Saviq will try the RC. Having #1260 in place would also allow to work around this limitation in the future.
