### ISSUE TITLE
[qemu] daemon starting instance twice if triggered on startup

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2520]
When an instance gets started on Multipass startup, but a client requests a start as well, daemon may try and start it twice:

```shell
$ multipass start
$ snap stop multipass
$ snap start multipass; while true; do multipass start; done
start failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
# ...
start failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
Starting primary \^C
```

Log excerpt:
```plain
Apr 12 13:19:47 nuc multipassd[320423]: primary needs starting. Starting now...
Apr 12 13:19:48 nuc multipassd[320423]: [322406] started: qemu-system-x86_64 --enable-kvm -cpu host -nic tap,ifname=tap-1e376645a40,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:be:37:3d -device virtio-scsi-pci,id
=scsi0 -drive file=/var/snap/multipass/common/data/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp
 stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/snap/multipass/common/data/multipassd/vault/instances/primary/cloud-init-config.iso -loadvm suspend -machine pc-i440fx-focal
Apr 12 13:19:48 nuc multipassd[320423]: Waiting for SSH to be up
Apr 12 13:19:48 nuc multipassd[320423]: QProcess: Destroyed while process ("qemu-system-x86_64") is still running.
Apr 12 13:19:48 nuc multipassd[320423]: QIODevice::read (QProcess): device not open
Apr 12 13:19:48 nuc multipassd[320423]: QMP:
Apr 12 13:19:48 nuc multipassd[320423]: QIODevice::read (QProcess): device not open
Apr 12 13:19:48 nuc multipassd[320423]: QMP:
Apr 12 13:20:18 nuc multipassd[320423]: process state changed to NotRunning
Apr 12 13:20:18 nuc multipassd[320423]: [322981] started: qemu-system-x86_64 -nographic -dump-vmstate /tmp/multipassd.wmJFCU
Apr 12 13:20:18 nuc multipassd[320423]: Applied AppArmor policy: multipass.primary.qemu-system-x86_64
Apr 12 13:20:18 nuc multipassd[320423]: process state changed to Starting
Apr 12 13:20:18 nuc multipassd[322984]: Caught an unhandled exception: Failed to apply AppArmor policy multipass.primary.qemu-system-x86_64: errno=2 (No such file or directory)
Apr 12 13:20:18 nuc multipassd[322984]: QSocketNotifier: Invalid socket 30 and type 'Read', disabling...
Apr 12 13:20:48 nuc multipassd[320423]: Qemu failed to start: program: qemu-system-x86_64; error: Process operation timed out
Apr 12 13:20:48 nuc multipassd[320423]: Caught an unhandled exception: failed to start qemu instance: program: qemu-system-x86_64; error: Process operation timed out
```

AFAICS it tried to dump vmstate on a running vm.

[multipassd.log](https://github.com/canonical/multipass/files/8473264/multipassd.log)

**Comment by ricab** [comment]
Hey @sharder996, were you able to reproduce this at all? I tried a few times, but I could not reproduce this on edge.

BTW, IIUC *vmstate* appears to be some sort of internal QEMU misnomer for virtualization info pertaining to the platform, not any particular VM. However, it is fetched before each start – there's an opportunity to optimize instance starts – to update instance metadata, except when resuming from suspended, which is why it only shows up in the log the second time.

**Comment by ricab** [comment]
OK, I was finally able to reproduce but, to my utter surprise, only after refreshing the snap to #2711 :no_mouth: I eventually realized that's using the same version as edge, so I suppose the PR snap has expired...

What I am puzzled about is that there seem to be 2 daemons running... Even in the logs above, there are 2 different pids: 320423 and 322984 :orangutan: At first I thought this could be another thread, but that doesn't seem to be the case. Fork gone wrong? Strange though

**Comment by sharder996** [comment]
Hey @ricab As you've found, I was able to reproduce this issue fairly reliably using the bash command.

In regard to `vmstate`, I'm seeing the same thing where we seem to be doing file i/o to fetch data that isn't necessarily changing on every instance start.

As for the different pids, I'm as stumped as you as. Not sure what's going on there.
