### ISSUE TITLE
[osx] `set failed: The Instance modification feature is not implemented on this backend` when trying to change Disk Size

### ISSUE THREAD

**Issue by Rocky43007** [canonical/multipass#2524]
**Describe the bug**
Expanding the disk size through multipass using the latest build from #2353 leads to the following error: `set failed: The Instance modification feature is not implemented on this backend`. Looks to be an error on Hyperkit from looking at logs.

**To Reproduce**
How, and what happened?
1. `multipass stop KC-Dev`
2. `multipass set local.KC-Dev.disk=40G`
Return message: `set failed: The Instance modification feature is not implemented on this backend.`

A general version would be:
1. `multipass stop <Instance Name>`
2. `multipass set local.<Instance Name>.disk=<New Disk Size>`
Return message: `set failed: The Instance modification feature is not implemented on this backend.`

**Expected behavior**
Disk Size expands to the set size through `multipass set local.<Instance Name>.disk=<New Disk Size>`.

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/8487637/multipassd.log)
[KC-Dev-hyperkit.log](https://github.com/canonical/multipass/files/8487638/KC-Dev-hyperkit.log)

**Additional info**
 - OS: MacOS 12.2.1
 - Mulitpass Version: `multipass   1.10.0-dev.1045.pr2353+g6bce41ab.mac`
 - Mulitpassd Version: `multipassd   1.10.0-dev.1045.pr2353+g6bce41ab.mac`
 
VM Info:
Name:           KC-Dev
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 20.04.4 LTS
Image hash:     b77c612dddae (Ubuntu 20.04 LTS)
Load:           0.02 0.08 0.05
Disk usage:     17.4G out of 19.2G
Memory usage:   141.6M out of 1.9G
Mounts:         --

**Comment by Saviq** [comment]
@Rocky43007 hyperkit is being deprecated, please move to the qemu driver instead:

```
$ sudo multipass set local.driver=qemu
```

If you need to, you can use the steps from https://github.com/canonical/multipass/issues/62#issuecomment-1093170620 to resize a hyperkit disk.
