### ISSUE TITLE
fixed the instance's ip

### ISSUE THREAD

**Issue by lqllife** [canonical/multipass#2538]
**What are you trying to do?**
I'd like to get a fixed ip when launching instance, it's easy for testing.

**What's your proposed solution?**
fixed ip ...

**Comment by luis4a0** [comment]
Hi @lqllife, getting a fixed IP can be obtained with network bridging, see [here](https://multipass.run/docs/additional-networks) for details. For this, you must use a backend/platform combination which supports bridging.

**Comment by Saviq** [comment]
Duplicate of #567
