### ISSUE TITLE
cannot start VM without an image

### ISSUE THREAD

**Issue by johnsca** [canonical/multipass#254]
My multipass seems to be in a stuck state.  I was trying to launch a xenial VM and a couple of times got an error that it failed to launch due to a network timeout.  On the third or so attempt, it looked like it was going to succeed but then failed with:

```
[johnsca@murdoch:~] ?:- $ multipass launch xenial
failed to launch: cannot start VM without an image                              
```

It now just returns that error almost immediately every time I try to launch a xenial VM.  I assume there is a bad image cached somewhere but I don't see any commands or info on how to clean it out.

**Comment by townsend2010** [comment]
@johnsca, even though it cleared up for you, I still think Multipass did something wrong here.  I'll try to dig further and figure out what may have happened and how to handle that.

**Comment by townsend2010** [comment]
I think I found the root cause of this issue.  Will push a PR soon.
