### ISSUE TITLE
Using Multipass in production

### ISSUE THREAD

**Issue by JCzz** [canonical/multipass#2547]
I am unable to create topics in [discourse](https://discourse.ubuntu.com/c/multipass/21/none)

And I asked in Libera.Chat but as Guest it is confusing if the message event got sent - so nothing there.

Sorry, therefore I am asking here.

I am considering using the next 1.9 release on Apple Silicon - do you know if anyone is using it in production. 
I am aware it is very powerfull for development, but I am curious if it could be used in production?

I have seen tutorials like [this](https://thenewstack.io/deploy-a-kubernetes-desktop-cluster-with-ubuntu-multipass/) saying "You certainly won’t be using Multipass as a production environment".

Thanks in advance
Regards

**Comment by nathan-j-hart** [comment]
Hi JCzz,
We've developed Multipass with the idea in mind that it would be a development tool. It has great ease of use for local testing, but may be lacking some features you would want in production. I'd be happy to learn more about your use case and give some more guidance if you'd like. Reach out anytime: nathan.hart@canonical.com

**Comment by JCzz** [comment]
Thanks I will

**Comment by JCzz** [comment]
Thanks

I am considering the following setup:
- 2 Apple Silicon Mac Studio machines.
- Running Kubernetes cluster nodes in Ubuntu VM's using Multipass.
- Metallb or nginx as load balancer.

Scenarios down the line:
- Updating Multipass on each server separately(downtime).
- Updating Kubernetes nodes with the ease of using Multipass

Obviously I am concerned with security, stability and maintainability.

**Comment by nathan-j-hart** [comment]
Hi JCzz,
That seems like the kind of scenario Multipass is designed for. The caveat is as I mentioned above - we aren't really aware of anyone using Multipass for this kind of thing in production. If ease of use is important to you I'd recommend prototyping on Multipass, and you could potentially migrate to QEMU down the line if you hit roadblocks. Multipass is built on QEMU on the M1 platform. Keep me posted on how it's going! 

By the way, I did get your email. We've just been very busy at our product roadmap sprint so I didn't have the time to address it until now. Feel free to keep in touch there if you prefer

**Comment by JCzz** [comment]
Hi @nathan-j-hart 

No worries and thanks you for you reply.

Sounds like a good plan, and thank you for the info, I missed that "Multipass is built on QEMU on the M1 platform". [Found it after reading you reply](https://multipass.run/docs/installing-on-macos#heading--check-prerequisites) ;-)

Finding that out, I am going full steam using Multipass. 
As mentioned I am going to run Kubernetes nodes, and just found [cloud-init](https://cloud-init.io) and this [script](https://github.com/sciabarracom/terraform-kubernetes-multipass/blob/master/multipass/script/cloud-init.yaml
) Just in case you have a better script or process on getting Kubernetes installed on the VMs?

Thanks Nathan - Multipass is great work, and looking forward to see what comes out of the "product roadmap" :-)

**Comment by Saviq** [comment]
Hi @JCzz, with regards to k8s installation - one thing to maybe look at would be our own microk8s:

https://microk8s.io/

**Comment by JCzz** [comment]
Thanks @Saviq I will give microk8s a try:

1. Do you know if I can set --config stuff like with [Kubeadm](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/) I need to set some serverCertSANs.
2. I need network bridgets from each k8s node, do you know if that is possible.
3. If not, I will stick to Multipass and install bare K8s or maybe MicroK8s - what do you think?

**Comment by Saviq** [comment]
@JCzz you'll need to find that out from the microk8s folk - try the website and their forum:

https://discuss.kubernetes.io/c/general-discussions/microk8s/26

**Comment by JCzz** [comment]
Right, thanks @Saviq
