### ISSUE TITLE
Unable to install Beta on Apple silicon

### ISSUE THREAD

**Issue by JCzz** [canonical/multipass#2548]
Looking forward to 1.9 incl. new Network support for Apple Silicon.

In the [beta release](https://github.com/canonical/multipass/releases) it says: "Windows and macOS installers are available below, and the Snap in the beta [snap channel](https://snapcraft.io/multipass):"

1. Snap
Installing [snapcraft](https://snapcraft.io/docs/installing-snapcraft) on Apple Silicon:
`brew install snapcraft`

2. Multipass
```
snap install multipass --beta
Interacting with snapd is not yet supported on darwin.
This command has been left available for documentation purposes only.
```

How do you test the Beta on Apple Silicon?

**Comment by Saviq** [comment]
Hi @JCzz, you can install the latest release candidate from here:

https://github.com/canonical/multipass/releases/tag/v1.9.0-rc

I've added a task for ourselves to document this better.

**Comment by JCzz** [comment]
Thanks
