### ISSUE TITLE
local.driver setting lost on Snap update

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2557]
The update apparently also lost my local.driver setting...  Took me a long while to figure THAT one out.  Somehow it got (re)set to qemu, whereas for me (on Fedora) it only works if I set it to libvirt.

_Originally posted by @derekatkins in https://github.com/canonical/multipass/issues/2552#issuecomment-1118967703_

**Comment by townsend2010** [comment]
Hey @derekatkins,

I wonder if something went wrong during the snap upgrade.  The config file that contains this key is in `/var/snap/multipass/current/config/multipassd/multipassd.conf` where the data is copied on snap upgrade.

If you'd like to pursue this further, could you please output the following:
 - `$ snap changes`
 - `$ snap tasks --last=refresh`
 - `$ tree -I common -P config -P current /var/snap/multipass`
 - `$ sudo find /var/snap/multipass/ -name multipassd.conf -type f | xargs awk 'FNR==1{print FILENAME; }{ print }'`

Thanks!

**Comment by derekatkins** [comment]
Note that I already re-installed multipass and fixed the problem, so....  Unclear if the underlying issue was here.  It started with the authentication issue.
```
# snap changes
ID   Status  Spawn                   Ready                   Summary
11   Done    yesterday at 12:26 EDT  yesterday at 12:26 EDT  Remove "multipass" snap
12   Done    yesterday at 12:27 EDT  yesterday at 12:27 EDT  Install "multipass" snap
13   Done    yesterday at 13:38 EDT  yesterday at 13:42 EDT  Running service command
14   Done    yesterday at 14:20 EDT  yesterday at 14:20 EDT  Running service command
15   Done    yesterday at 15:05 EDT  yesterday at 15:10 EDT  Running service command
16   Done    yesterday at 15:10 EDT  yesterday at 15:10 EDT  Running service command
# snap tasks --last=refresh
error: no changes of type "refresh" found
# tree -I common -P config -P current /var/snap/multipass
/var/snap/multipass
├── 6920
│   ├── config
│   │   └── multipassd
│   └── data
│       └── glib-2.0
│           └── schemas
└── current -> 6920

7 directories, 0 files
# find /var/snap/multipass/ -name multipassd.conf -type f | xargs awk 'FNR==1{print FILENAME; }{ print }'
/var/snap/multipass/6920/config/multipassd/multipassd.conf
[General]
local.driver=libvirt
```

**Comment by townsend2010** [comment]
Hi @derekatkins,

Ok, thanks for that, but yeah, it looks like anything useful for debugging is long gone.  I think the `local.driver` issue stemmed from removing the snap and then installing fresh.  That setting will not be preserved in such a case.  Please reply if you feel the `local.driver` setting was wiped *before* uninstalling the snap.

**Comment by townsend2010** [comment]
Ok, well, I've tried to reproduce this a few times and could not, so I think I'll close this due to the removal of the snap.  We can reopen or open a new issue if there other occurrences.

**Comment by derekatkins** [comment]
I'm the only person that uses this laptop, but the change was that I rebooted since I first installed snapd + multipass (+ snapcraft)..  And when I rebooted and logged in there was a snap icon in my nav box on my desktop titlebar, and at that point I had the authentication error when running multipass or snapcraft from the command line.  Eventually I used the snapd icon to quit, restarted snapd a couple times, then eventually uninstalled and reinstalled multipass, and that got past the authentication error but then my snapcraft builder VM wouldn't run -- and that's when I discovered the local.driver setting was reverted from libvirt back to qemu (which for whatever reason doesn't work on Fedora).

**Comment by townsend2010** [comment]
Ok, thank you for the additional info. I wonder if there is something different with respect to paths in Fedora that we didn't account for.

**Comment by derekatkins** [comment]
I am happy to report on anything you need.
