### ISSUE TITLE
failed to launch: Attempt to access value of a disengaged optional object

### ISSUE THREAD

**Issue by johnsca** [canonical/multipass#256]
I got the above error when attempting to launch a bionic instance:

More details:
```
johnsca@wilty:~$ multipass launch bionic -n test
failed to launch: Attempt to access value of a disengaged optional object
johnsca@wilty:~$ multipass launch bionic -n test -v -v -v
Verbose level: 3
failed to launch: instance "test" already exists
johnsca@wilty:~$ multipass list
Name                    State       IPv4             Release
test                    UNKNOWN     --               Ubuntu 18.04 LTS
johnsca@wilty:~$ multipass delete -p test
johnsca@wilty:~$ multipass launch bionic -n test -v -v -v
Verbose level: 3
failed to launch: Attempt to access value of a disengaged optional object
```

**Comment by townsend2010** [comment]
@johnsca,

Thanks for posting this report.  It seems somewhere we have missed checking to make sure an optional object indeed has an object associated with it.  To help narrow this down, could you give the output of:
`$ sudo snap get multipass -l`

**Comment by townsend2010** [comment]
@johnsca,

Also, the `-v` options are currently a no-op:(  See #155.

**Comment by johnsca** [comment]
```
johnsca@wilty:~$ sudo snap get multipass -l
error: snap "multipass" has no configuration

johnsca@wilty:~$ snap info multipass
name:      multipass
summary:   Ubuntu at your fingertips
publisher: canonical
license:   unknown
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch` and it'll do all the setup for
  you. Check out `multipass find` for a list of available images. More details you can find under
  `multipass help`.
commands:
  - multipass
  - multipass.virsh
services:
  multipass.libvirt-bin: simple, enabled, inactive
  multipass.multipassd:  simple, enabled, active
snap-id:   mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:  beta
refreshed: 2018-04-27T12:55:24Z
installed:   2018.4.2             (200) 94MB classic
channels:                               
  stable:    –                               
  candidate: –                               
  beta:      2018.4.2             (200) 94MB classic
  edge:      2018.4.2-22-g6bc5c82 (226) 97MB classic
```

I wondered why it didn't add anything useful.  :)

**Comment by johnsca** [comment]
Odd.  I switched to edge and tried again, and got this:

```
johnsca@wilty:~$ multipass launch bionic -n test
Launched: test
johnsca@wilty:~$ multipass list
Name                    State       IPv4             Release
test                    UNKNOWN     --               Ubuntu 18.04 LTS
johnsca@wilty:~$ multipass shell test
shell failed: instance "test" is not running
```

**Comment by johnsca** [comment]
Ah.  I have maas running on that machine with dhcp enabled so that must be causing a conflict.

**Comment by townsend2010** [comment]
@johnsca,

Yeah, looking at she maas source, it looks like it provides a DHCP/DNS server on all interfaces.  Even further, the maas Debian packaging conflicts with dnsmasq, probably for that reason.

I'll focus on the disengaged optional object issue, but in the end, the result will be the same in that you will not be able to connect to a multipass instance.  I wonder if/how LXD deals with this...

**Comment by townsend2010** [comment]
@johnsca,

Looking at the code, I don't see an obvious place where we are trying to access the object when it isn't defined.  When this occurs, does it happen almost immediately or do you see the message "Starting" with the spinner for a while?

**Comment by townsend2010** [comment]
@johnsca,

Ah, I missed the fact that you didn't get the disengaged optional object error when using edge.

Thanks!
