### ISSUE TITLE
Services don't restart when macOS is restarted

### ISSUE THREAD

**Issue by jonathanbossenger** [canonical/multipass#2572]
**Describe the bug**
I am running Multipass on an M1 Pro MacBook. I have a Multipass instance configured with a LAMP web development environment. Whenever I need to restart the MacBook, the Multipass instances restarts, but the Apache service does not. I have to SSH into the Multipass instance, and manually restart the Apache service.

**To Reproduce**
How, and what happened?
1. Use an M1 Pro MacBook
2. Set up a multipass instance with the Apache web server
2. Restart the Macbook

**Expected behavior**
I expected the Apache server to restart when the Multipass instance restarts

**Logs**
[multipass.log](https://github.com/canonical/multipass/files/8706526/multipass.log)

**Additional info**
 - OS: macOS 12.2.1
- `multipass version`: 1.8.1+mac
- `multipass info --all`: 
Name:           triangle
State:          Running
IPv4:           192.168.64.2
Release:        Ubuntu 20.04.4 LTS
Image hash:     039c9c950da5 (Ubuntu 20.04 LTS)
Load:           0.22 0.22 0.16
Disk usage:     3.2G out of 4.7G
Memory usage:   558.1M out of 970.0M
Mounts:         /Users/jonathanbossenger/development/websites => /home/ubuntu/sites
                    UID map: 501:default
                    GID map: 20:default
                /Users/jonathanbossenger/ssl-certs            => /home/ubuntu/ssl-certs
                    UID map: 501:default
                    GID map: 20:default

**Comment by townsend2010** [comment]
Hey @jonathanbossenger,

This seems like an issue with the Apache config or Apache itself.  I'm no Apache expert, but searching for similar issues about Apache not starting and found this: https://askubuntu.com/questions/1251681/ubuntu-20-04-apache-does-not-start-at-boot

Hopefully that will help, but if not, I saw many other postings about Apache not starting after boot.  Closing this as it isn't an issue with Multipass itself.

**Comment by jonathanbossenger** [comment]
Hey @townsend2010 thanks for checking this out. On further investigation, this appears to be a problem with how directories are mounted, and the multipass instance booting up. I hope you could bear with me here while I explain.

After you closed the ticket with the SO link, I launched a new instance, with just Apache installed, and everything worked as expected. So I ran the following command on my existing instance, to see if Apache was reporting any errors.

`systemctl status apache2.service`

The error reported was 

```
May 18 08:29:23 triangle systemd[1]: Starting The Apache HTTP Server...
May 18 08:29:23 triangle apachectl[4359]: AH00112: Warning: DocumentRoot [/home/ubuntu/sites/multisite] does not exist
May 18 08:29:23 triangle apachectl[4359]: AH00526: Syntax error on line 17 of /etc/apache2/sites-enabled/multisite-ssl.conf:
May 18 08:29:23 triangle apachectl[4359]: SSLCertificateFile: file '/home/ubuntu/ssl-certs/multisite.test.pem' does not exist or is empty
May 18 08:29:23 triangle apachectl[4356]: Action 'start' failed.
May 18 08:29:23 triangle apachectl[4356]: The Apache error log may have more information.
May 18 08:29:23 triangle systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
May 18 08:29:23 triangle systemd[1]: apache2.service: Failed with result 'exit-code'.
May 18 08:29:23 triangle systemd[1]: Failed to start The Apache HTTP Server.
```

In my case, I have the following two local directories mounted inside instance

~/development/websites mounted to /home/ubuntu/sites
~/ssl-certs mounted to /home/ubuntu/ssl-certs

When I check those locations in the Multipass instance, they are empty, so I re mount them from macOS

```
jonathanbossenger@Jonathans-MacBook-Pro ~ % multipass mount ~/development/websites triangle:/home/ubuntu/sites
mount failed: The following errors occurred:                                    
There is already a mount defined for "triangle:/home/ubuntu/sites"
jonathanbossenger@Jonathans-MacBook-Pro ~ % multipass mount ~/ssl-certs triangle:/home/ubuntu/ssl-certs
mount failed: The following errors occurred:                                    
There is already a mount defined for "triangle:/home/ubuntu/ssl-certs"
```

When I restart Apache on the instance, everything works.

Then I stopped the instance and started it. Again apache is not starting with the same error. However, this time when I check the mounted locations on the instance, everything is there. I restart Apache, and things work as expected.

This leads me to believe that the mounting of the local directories inside the instance takes place after any instance services (like Apache) are started, which is causing the issue?

**Comment by townsend2010** [comment]
Hey @jonathanbossenger,

Ah, ok, I see.  So in Multipass controlled mounts, it is done late in process, ie, after the instance is booted and `multipassd` deems the instance is in a good state.  This won't play nice with services that start on boot that rely on the mount to be there already.  The only thing I can think of if there is some way to modify `apache2.service` to wait on a `systemd` unit to run.

For example, when I mount my `home` directory in an instance, the following `systemd` unit is active in the instance:
`home-ubuntu-Home.mount                                             loaded active mounted   /home/ubuntu/Home `

Maybe something like that would work?  Otherwise, I'm not sure how we could manage making the mount active really early in the boot process.

**Comment by jonathanbossenger** [comment]
OK, thanks, @townsend2010. I'll look into what's possible here.
