### ISSUE TITLE
MacOS Arm64 - unsupported ifname 'bridge0'

### ISSUE THREAD

**Issue by JCzz** [canonical/multipass#2581]
Env: 

```
MacOS Arm64
multipass   1.9.0+mac
multipassd  1.9.0+mac

```
From here: https://multipass.run/docs/additional-networks

I am trying to create a VM that will bridge to my network:

```
multipass launch --network en0 --network name=bridge0,mode=manual 
launch failed: The following errors occurred:                                   
qemu-system-aarch64: -nic vmnet-bridged,ifname=bridge0,model=virtio-net-pci,mac=52:54:00:4a:fa:c9: unsupported ifname 'bridge0', expected one of [ en6 en0 ]
```

multipass networks:
```
Name     Type         Description
bridge0  bridge       Network bridge with en1, en2, en3
en0      wifi         Wi-Fi
en1      thunderbolt  Thunderbolt 1
en2      thunderbolt  Thunderbolt 2
en3      thunderbolt  Thunderbolt 3
en4      ethernet     Ethernet Adapter (en4)
en5      ethernet     Ethernet Adapter (en5)
en6      usb          USB 10/100/1000 LAN
en7      ethernet     Ethernet Adapter (en7)
```

local.bridged-network:
```
get local.bridged-network
<empty>

```
ifconfig:
```
ifconfig bridge0
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether <xx:xx:xx:xx:xx:xx>
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 11 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 12 priority 0 path cost 0
	Address cache:
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
```

**Comment by JCzz** [comment]
Update: `multipass launch --network en0` gets me an ip on my network, but still from the example:

I get:

```
multipass launch --network en0 --network name=bridge0,mode=manual 
launch failed: The following errors occurred:                                   
qemu-system-aarch64: -nic vmnet-bridged,ifname=bridge0,model=virtio-net-pci,mac=52:54:00:4a:fa:c9: unsupported ifname 'bridge0', expected one of [ en6 en0 ]
```

It says `-network name` is [hostname](https://multipass.run/docs/additional-networks#heading--network-specification)
 is that for the instance to have a hostname from the bridge name multipass creates? 

I guess the bridge name number is a consecutive number?

What is `networksetup -listnetworkserviceorder` vs `multipass networks` vs ifconfig?

Sorry for the basic network questions, I am learning networking together with multipass.

Thanks for the good work

**Comment by townsend2010** [comment]
Hi @JCzz!

Sorry for your troubles with this.  First, are you trying to bridge the Multipass instance to a Thunderbolt network?  That is what `bridge0` is for- the Thunderbolt network.

Second, it appears the virtual network adapter in QEMU does not allow using the bridging feature with actual bridges.  I will need to look into that to see if there is an update to QEMU or if there is a different mode that is needed to make that work.

**Comment by JCzz** [comment]
Thanks @townsend2010

Ahh, _"QEMU does not allow using the bridging feature with actual bridges."_ and yes, right, got it `bridge0` is Thunderbolt network - thanks ;-) We will see if/when QEMU updates it.

From the [documentation](https://multipass.run/docs/additional-networks#heading--network-specification) What also  confused me is this line:
`multipass launch --network en0 --network name=bridge0,mode=manual`
I missed the documentation saying`The --network option can be given multiple times` and got confused, for some reason.

I am good to go without QEMU woking with an "actual bridge". I will close this.

Thanks for taking the time and man this tool is good stuff.

**Comment by townsend2010** [comment]
Cool, thanks for the kind words @JCzz.  We're glad you enjoy Multipass :slightly_smiling_face:
