### ISSUE TITLE
Networks failed: The networks feature is not implemented on this backend. Linux x86-64

### ISSUE THREAD

**Issue by jarrodu** [canonical/multipass#2597]
It looks like I am getting the same issue was @pauljsymonds.

```
Operating System: Ubuntu 22.04 LTS
Kernel: Linux 5.15.0-30-generic
Architecture: x86-64
Hardware Vendor: Lenovo
Hardware Model: ThinkPad X1 Carbon Gen 8
multipass   1.9.2
multipassd  1.9.2
```

```
> multipass networks
networks failed: The networks feature is not implemented on this backend.
```

_Originally posted by @jarrodu in https://github.com/canonical/multipass/issues/2364#issuecomment-1139333862_

**Comment by townsend2010** [comment]
Hi @jarrodu,

Since you are on Intel Mac, it is using the `hyperkit` driver by default and additional networks are not supported nor will ever be supported.  In order to use `--network`/`networks`, you'll need to switch to the `qemu` driver:
```
$ multipass set local.driver=qemu
```
Please note that if you already have `hyperkit` instances, these instances will be hidden, but not lost.  We plan on deprecating Hyperkit support this year and use QEMU exclusively, but the part that is not trivial is developing a way to migrate Hyperkit instances into QEMU instances.

**Comment by jarrodu** [comment]
Hi, and thanks for the quick response. I am actually running Ubuntu on a ThinkPad. It also looks like I am using `qemu`.

```
> multipass get local.driver
qemu
```

Do you mind taking another quick look at the issue?

Thanks again.

**Comment by townsend2010** [comment]
Oh, sorry, I got confused about it originally being in a Mac issue.

Ok, yes, the `qemu` driver on Linux doesn't currently support additional networks.  The `lxd` driver does and our intent was to move to LXD by default on Linux.  However, I think QEMU will be staying and I'm thinking we should add additional networks for the `qemu` driver in due time.

Long story short, use the `lxd` driver on Linux if you need additional networks.

**Comment by jarrodu** [comment]
Okay. Perfect.

Just out of curiosity, is there somewhere I can learn more about why Multipass is not going to `lxd` by default? I am a big `lxd` fan. Especially, after 5.0 came out.

BTW: I am also a big Multipass fan. :-)

**Comment by townsend2010** [comment]
Oh, we will still probably move to LXD as the default driver.  It's just that we've had a few issues with images that we need to support that didn't integrate well with LXD, but that is getting sorted out.  I meant that we'll still keep `qemu` as an option and not drop support for it.

That said, the `lxd` driver should work for most purposes and is fully supported by us.  Feel free to switch to it and report any issues that you may find.

Glad to hear you like Multipass so much :slightly_smiling_face:
