### ISSUE TITLE
macOS M1 launch issues

### ISSUE THREAD

**Issue by fsecuritynz** [canonical/multipass#2599]
multipass launch
launch failed: The following errors occurred:
qemu-system-aarch64: -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:3a:8d:e3: cannot create vmnet interface: conflict, sharing service is in use
honeyed-swine: shutdown called while starting

**Comment by Saviq** [comment]
Hi @fsecuritynz, you'll need to disable "Internet Sharing" under Settings > Sharing.
