### ISSUE TITLE
[qemu] nesting on VMWare Fusion breaks with a counter error

### ISSUE THREAD

**Issue by kengreenlee** [canonical/multipass#2603]
I'm running nested VMs.  Host is macOS 12.4 running VMWare Fusion 12.2.3.  Guest VM is Ubuntu 22.04.  I know the host hardware and VMWare Fusion support nested VMs because this works perfectly on the same environment running RHEL 8.6 as the guest VM in Fusion.  I've verified that I have the same VMWare Fusion settings that work on the RHEL VM when compared to the Ubuntu VM.

I get this error when trying to launch a Multipass VM:

```
$ multipass launch --name foo

launch failed: The following errors occurred:                                   
qemu-system-x86_64: error: failed to set MSR 0x48d to 0x5600000016
qemu-system-x86_64: /build/qemu-0Dw8aG/qemu-4.2/target/i386/kvm.c:2691: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
```

Switching to libvirt has the same issue.

**Logs**
[multipass-logs.txt](https://github.com/canonical/multipass/files/8815284/multipass-logs.txt)

**Additional info**
```
$ multipass version
multipass   1.9.2
multipassd  1.9.2
```

```
multipass info --all
Name:           foo
State:          Stopped
IPv4:           --
Release:        --
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

**Comment by kengreenlee** [comment]
@Saviq Virtualized Counters don't exist in VMWare Fusion Player.  From what I can tell, it's only in VMWare Fusion Pro.

**Comment by Saviq** [comment]
Actually I jumped to a conclusion here, sorry. Now I remember we discussed this before and the problem was the CPU we select. We use `-cpu host` as that gets us the closest mapping between the host CPU and the guest, but counters are a problematic bit.

Can you please try with `multipass set local.driver=lxd` to see if their defaults fare better?

**Comment by Saviq** [comment]
For reference, here are some other related issues:

https://github.com/canonical/multipass/issues?q=is%3Aissue+nmsrs+is%3Aclosed

It may be possible that we do something like `-cpu host,*=off` to disable the problematic CPU feature.

**Comment by kengreenlee** [comment]
Not sure what you want me to try next.

**Comment by kengreenlee** [comment]
@townsend2010 You are correct. On my laptop (specs listed in original post), Multipass runs perfectly when guest OS is RHEL 8.6, but Multipass does not run when guest OS is Ubuntu 22.04.

**Comment by townsend2010** [comment]
@kengreenlee, ok, very interesting.  I don't have much experience running Multipass on RHEL.  Is the Multipass snap installed with classic or strict confinement on RHEL?

Also, do you see any `apparmor` denials in the Ubuntu guest system journal when this occurs?  I'm wondering if AppArmor is at play here.

**Comment by townsend2010** [comment]
The guest kernel could very well be at play in this as well.  Are you running the most up to date 22.04 kernel on your guest?

**Comment by kengreenlee** [comment]
@townsend2010 My Ubuntu guest kernel is `5.15.0-35-generic`.

**Comment by townsend2010** [comment]
Ok, I've done some digging including reproducing this on my Mac.  I found that this issue afflicts many folks.  For example, I found https://github.com/minishift/minishift/issues/3533 and https://communities.vmware.com/t5/VMware-Fusion-Discussions/Attempting-to-do-nested-virtualization/td-p/2308242 as a couple of examples.

Considering this works for you using RHEL 8.6, but not Ubuntu, I imagine the kernel is at play here.  Out of curiosity, what kernel version are you running in RHEL?

In the end, this isn't a Multipass issue, but most likely a kernel issue, but I've no idea where to start on how that would be addressed.

**Comment by kengreenlee** [comment]
@townsend2010 My kernel version on RHEL 8.6 is 4.18.0-372.9.1.el8.x86_64.

**Comment by townsend2010** [comment]
Ok, that's a fairly old base kernel, although I know Red Hat has patched it greatly, but I'm sure the skew between that kernel and the 5.15.0-35-generic in Ubuntu 22.04 is quite large.

Unfortunately, there isn't more that we can do to help.  This is either a kernel and/or VMWare Fusion issue.

**Comment by kengreenlee** [comment]
Thanks for all the help.  I really appreciate it.
