### ISSUE TITLE
multipass cloud-init appears to fail to run echo commands in runcmd that have whitespace before alphanumeric characters

### ISSUE THREAD

**Issue by richardatlateralblast** [canonical/multipass#2606]
I'm not entirely sure if this is to do with multipass or cloud-init, but multipass cloud-init appears to fail to run echo commands in runcmd that have whitespace before alphanumeric characters.

To reproduce this you just need to have echo command in runcmd section of a cloud-init config file that have white space before any alphanumeric characters.

For example the following runcmd stanza successfully updates /etc/motd:

```
runcmd:
  - echo '############' > /etc/motd
  - echo 'Test Message' >> /etc/motd
```

The follow runcmd stanza fails to execute the commands:

```
runcmd:
  - echo '  ############' > /etc/motd
  - echo '  Test Message' >> /etc/motd
```

These fail to run whether there is a single quotation mark or double quotation mark. It also appears to fail if it's a tab rather than a space, e.g. \t

Not sure what logs to provide here, the cloud-init logs inside the VM are probably the most pertinent I would suspect as in both cases the VM build completes, it's just the commands are not run in one case, but I suspect the following lines in the cloud-init-output.log file in /var/log may be relevant:

```
/var/lib/cloud/instance/scripts/runcmd: 12: Syntax error: Unterminated quoted string
2022-06-06 06:09:45,045 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2022-06-06 06:09:45,045 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
```

Versions:

```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G5037d

$ multipass version
multipass   1.9.1+mac
multipassd  1.9.1+mac
```

Info:

$ multipass info --all

```
Name:           ubuntu2204vm03
State:          Running
IPv4:           192.168.64.64
Release:        Ubuntu 22.04 LTS
Image hash:     b206efe08ff4 (Ubuntu 22.04 LTS)
Load:           0.32 0.23 0.09
Disk usage:     2.3G out of 19.2G
Memory usage:   165.6M out of 961.9M
Mounts:         --
```

**Comment by richardatlateralblast** [comment]
I've managed to reproduce this problem using cloud-init on KVM, so I'll close this and log the bug with cloud-init people

**Comment by sitsofe** [comment]
(In case anyone is wonder Richard did file with cloud-init and you can read the outcome on https://github.com/canonical/cloud-init/issues/3983)
