### ISSUE TITLE
Unable to access instaces after upgrading to 1.9.1 on macOS Monterey

### ISSUE THREAD

**Issue by jonathanbossenger** [canonical/multipass#2607]
**Describe the bug**
Today I upgraded to 1.9.1, and ever since upgrading, I can no longer access information about instances, or connect to the instance shell.

For example, running `multipass list`
 
```       
list failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
```

I tried searching for open or closed issues related to this and came across this Discourse post

https://discourse.ubuntu.com/t/unable-to-authorize-the-client-and-cannot-set-a-passphrase-workaround/28321

However, the macOS instructions provided did not resolve the issue.

Fortunately, my instances appear to be running, I just cannot access them or do start/stop them, or run most commands.

**Logs**
[multipassd.log](https://gist.github.com/jonathanbossenger/2151df86302b7270e11026cca8ea51ea)

**Additional info**
 - macOS 12.4
- `multipass version`: multipass   1.9.1+mac
- `multipass info --all`: cannot list (see below)

```
info failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
```

**Comment by jonathanbossenger** [comment]
Never mind, this time it worked.

**Comment by townsend2010** [comment]
Hi @jonathanbossenger!

I was just replying to you :slightly_smiling_face: Glad you got it working, but sorry for the initial troubles.
