### ISSUE TITLE
Publish windows installer source

### ISSUE THREAD

**Issue by qm3ster** [canonical/multipass#2609]
I was unable to find any scripts to build the installer, allegedly it's made with NSIS in CanonicalLtd/multipass-private.
Is there a legal reason for that?

(In my case, I wanted to avoid the check for Windows edition to default to `hyperv`)

**Comment by ricab** [comment]
Hi @qm3ster, yes, I'm afraid we keep Windows specifics closed source.

Duplicate of #1390.
