### ISSUE TITLE
mount failed: cannot connect to the multipass socket Please ensure multipassd is running and 'localhost:50051' is accessible

### ISSUE THREAD

**Issue by mnacfil** [canonical/multipass#2619]
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`

**Additional context**

**Comment by luis4a0** [comment]
Hi @mnacfil, can you please provide us more details, like platform, OS, version, when does this occur and, more important, the logs as described [here](https://multipass.run/docs/accessing-logs)? Thank you!

**Comment by xiaoxiaozhang3** [comment]
> 你好@mnacfil，您能否向我们提供更多详细信息，例如平台、操作系统、版本、何时发生，更重要的是，[此处](https://multipass.run/docs/accessing-logs)描述的日志？谢谢！

multipass version 1.9.1+win  microsoft Windows10。multipass cannot run after the computer is restarted

**Comment by ricab** [comment]
I don't think there is much we can follow up without more info.
