### ISSUE TITLE
multipass.gui quit unexpectedly.

### ISSUE THREAD

**Issue by ghost** [canonical/multipass#2622]
**Describe the bug**
Describe what your problem is.
macOS Monterey 12.4 M1

**To Reproduce**
How, and what happened?
1. delete files in ~/Library/Logs/DiagnosticReports
2. multipass will crash

**Expected behavior**
What did you expect to happen?
Multipass should not crash

**Comment by luis4a0** [comment]
Hi @altitudedashboard, how did it crash? What do you see in the logs in `/Library/Logs/Multipass`?
