### ISSUE TITLE
Update to Qt6

### ISSUE THREAD

**Issue by yogurtearl** [canonical/multipass#2627]
Update to use QT ~5.15.5~ 5.15.3 or later
https://www.qt.io/blog/commercial-lts-qt-5.15.5-released

Contains a fix for this proxy issue: 
https://github.com/canonical/multipass/issues/2325#issuecomment-1097681715

**Comment by minhio** [comment]
![](https://media3.giphy.com/media/tN1lvnT4M6nte/giphy.gif?cid=790b761126381620d49d6a87ba5ceca882bea2702ebb7323&rid=giphy.gif&ct=g)

**Comment by townsend2010** [comment]
Yes, we can update to this version on Windows and macOS, but on Linux, it's more tricky.  When building the Multipass snap with the `core20` base, we are stuck at Qt version 5.12.8.  If we were to move to the `core22` base, we then get Qt version 5.15.3, so still not new enough.  Qt6 is available when using the `core22` base but switching over all of our Qt code to use Qt6 will be a fairly big effort.

**Comment by minhio** [comment]
> Yes, we can update to this version on Windows and macOS, but on Linux, it's more tricky. When building the Multipass snap with the `core20` base, we are stuck at Qt version 5.12.8. If we were to move to the `core22` base, we then get Qt version 5.15.3, so still not new enough. Qt6 is available when using the `core22` base but switching over all of our Qt code to use Qt6 will be a fairly big effort.

@townsend2010 thank you for the update/context

**Comment by yogurtearl** [comment]
@townsend2010  just updating on Windows and macOS would be a great help for us. 
This is a hard showstopper for us using multipass, and I haven't found a workaround. :/

**Comment by minhio** [comment]
> @townsend2010 just updating on Windows and macOS would be a great help for us. This is a hard showstopper for us using multipass, and I haven't found a workaround. :/

ditto

**Comment by yogurtearl** [comment]
Looks like 5.15.10 is out.

https://www.qt.io/blog/commercial-lts-qt-5.15.10-released

**Comment by townsend2010** [comment]
Hi @yogurtearl and @minhio,

What platforms are you using Multipass on?  If it's *not* Linux, then we can address this.  On Linux, we are just constrained by what the Ubuntu archive provides for the Qt version without a bunch of heavy lifting on our part such as the aforementioned move to `core22`/Qt6 or building Qt from source.

**Comment by minhio** [comment]
> Hi @yogurtearl and @minhio,
> 
> What platforms are you using Multipass on? If it's _not_ Linux, then we can address this. On Linux, we are just constrained by what the Ubuntu archive provides for the Qt version without a bunch of heavy lifting on our part such as the aforementioned move to `core22`/Qt6 or building Qt from source.

I'm on a M1 Mac

**Comment by yogurtearl** [comment]
Well... so far we aren't using it, because of #2325 😅

Our potential use case would be for Windows and macOS (both Intel and Apple Silicon).

**Comment by yogurtearl** [comment]
>  If we were to move to the core22 base, we then get Qt version 5.15.3, so still not new enough.

Actually I think this could work for `core22` as well. 

Looks like 5.15.3 contained the needed fix: 

https://invent.kde.org/qt/qt/qtbase/-/blob/c8989ca20fa5798f7853f07df6e150cc407c64a4/src/network/kernel/qnetworkproxy_mac.cpp#L211

**Comment by townsend2010** [comment]
Oh, I see, those newer versions are commercial versions which we are not using.  We use the fully open source version which is currently 5.15.2.  We need to wait for Qt to release a newer open source version before we can get this in Qt5.  If we were to do this today, we'd need to move to Qt6.

**Comment by townsend2010** [comment]
Well, after I said that, I looked at what brew provides and it's 5.15.5, so maybe there is hope.  I need to dig a little further.

**Comment by yogurtearl** [comment]
Source code for `v5.15.5` is available: 
https://code.qt.io/cgit/qt/qt5.git/tag/?h=v5.15.5-lts-lgpl

Also, here: 
https://download.qt.io/official_releases/qt/5.15/5.15.5/

**Comment by yogurtearl** [comment]
Also, Arch Linux has 5.15.5: 
https://archlinux.org/packages/extra/x86_64/qt5-base/

**Comment by minhio** [comment]
> Well, after I said that, I looked at what brew provides and it's 5.15.5, so maybe there is hope. I need to dig a little further.

@townsend2010 thoughts on if 5.15.5 will make it into any of the upcoming windows/macos release? thanks!

**Comment by townsend2010** [comment]
Hey @minhio,

Yeah, I'm targeting that version for Multipass 1.11 on Windows & macOS only at this time.

**Comment by minhio** [comment]
> Hey @minhio,
> 
> Yeah, I'm targeting that version for Multipass 1.11 on Windows & macOS only at this time.

![](https://createifwriting.com/wp-content/uploads/2019/04/celebrate-gif.gif)
