### ISSUE TITLE
`multipass authenticate` and `multipass set local.passphrase` circle each other

### ISSUE THREAD

**Issue by only-a-user** [canonical/multipass#2628]
**Describe the bug**

When trying to use multipass in any way, for example:
```zsh
$ multipass list
```
I get the following output:
```zsh
list failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
```

Then trying
```zsh
$ multipass authenticate
```
results in:
```zsh
Please enter passphrase: 
authenticate failed: Passphrase is not set. Please `multipass set local.passphrase` with a trusted client.
```
```zsh
$ multipass set local.passphrase
```
results in
```zsh
Please enter passphrase: 
Please re-enter passphrase: 
set failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
```

Because of this I am basically unable to use multipass.

**Additional info**
- OS: MacOS 12.4
- multipass   1.9.2+mac
- multipass info --all failed with described bug.
- Installed with `homebrew`

**Comment by townsend2010** [comment]
Hi @Only-a-User,

Sorry you are having this trouble.  Did you already have Multipass installed and updated it and saw this issue or is this a clean install?  Also, see https://multipass.run/docs/authenticating-clients#heading--in-case-client-cannot-authorize-and-the-passphrase-cannot-be-set for how to recover from this situation.

**Comment by Only-a-User** [comment]
i installed it with homebrew so the solution doesnt really apply

**Comment by townsend2010** [comment]
> Did you already have Multipass installed and updated it and saw this issue or is this a clean install?

Could you please answer this?  If you installed 1.9.2 clean, then I'm really concerned because 1.9.1/1.9.2 is supposed to fix this on upgrades from 1.8.

Also, https://discourse.ubuntu.com/t/unable-to-authorize-the-client-and-cannot-set-a-passphrase-workaround/28321 has better instructions, but replace the `/var/root/...` paths with your Homebrew install paths.

**Comment by Only-a-User** [comment]
I installed it a while ago (~2 months)with brew but didn't use it up until now. After it didn't work at first I un- and reinstalled it via brew.

**Comment by Only-a-User** [comment]
also the `multipassd/` directory doesn't exist

**Comment by townsend2010** [comment]
Hi @Only-a-User,

Hmm, ok.  One thing to try is to make sure the Multipass GUI, ie, the "M" in the orange circle in the system tray is closed and not running and then do `brew uninstall --zap multipass` and then try reinstalling it again via `brew`.

**Comment by Only-a-User** [comment]
the problem persists. also i discovered, that the gui crashes when i try to open it. before i always used the cli

**Comment by townsend2010** [comment]
Urgh...so I installed the Homebrew version of Multipass and then followed the instructions I posted at https://discourse.ubuntu.com/t/unable-to-authorize-the-client-and-cannot-set-a-passphrase-workaround/28321 under the "How to recover on macOS" and it worked.  Please try these instructions one more time.

**Comment by rmelick-muon** [comment]
I have just hit this issue with a fresh install of multipass on Mac OS, not an upgrade.  

Output of `multipass version`
```
multipass   1.10.1+mac
```

MacOS version info
```
12.6 (21G115)
MacBook Pro (14-inch, 2021)
Apple M1 Pro
```

Errors I'm seeing
```
% multipass list
list failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.

% multipass authenticate
Please enter passphrase: 
authenticate failed: Passphrase is not set. Please `multipass set local.passphrase` with a trusted client.

% multipass set local.passphrase
Please enter passphrase: 
Please re-enter passphrase: 
set failed: The client is not authenticated with the Multipass service.
```

**Comment by townsend2010** [comment]
Hi @rmelick-muon,

Did you happen run `multipass` with `sudo` the first time?  To confirm, please try running `sudo multipass list` and see if it works.  If it does, then you'll need to set the `local.passphrase` using `sudo` and then `authenticate` with your normal user.

**Comment by rmelick-muon** [comment]
I had not used `sudo` to run it the first time.  Maybe `brew` is somehow running it with `sudo`?  Unfortunately I already followed the discourse instructions so I can't quite replicate the problem again.

**Comment by danielefavi** [comment]
> Urgh...so I installed the Homebrew version of Multipass and then followed the instructions I posted at https://discourse.ubuntu.com/t/unable-to-authorize-the-client-and-cannot-set-a-passphrase-workaround/28321 under the "How to recover on macOS" and it worked. Please try these instructions one more time.

Thank you! It worked!!!
