### ISSUE TITLE
Can't create directory in /proc/sys/net

### ISSUE THREAD

**Issue by wnow20** [canonical/multipass#2634]
**Describe the bug**
I want to make a dir 'bridge' in /proc/sys/net but failed, multipass instance shell told me:
`mkdir: cannot create directory ‘/proc/sys/net/bridge’: No such file or directory`

here is the snapshot:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/6159049/175779041-232d6636-b4ed-4a97-bd85-8c6f237548e3.png">

**To Reproduce**
How, and what happened?
1. `multipass shell [instance name]`
2. sudo -i
3. `mkdir -p /proc/sys/net/bridge`

**Expected behavior**
What did you expect to happen? make the dir created.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
[multipassd.log](https://github.com/canonical/multipass/files/8984984/multipassd.log)

**Additional info**
 - OS: macOS 12.3.1
- `multipass version`
```text
multipass   1.9.2+mac
multipassd  1.9.2+mac
```
- `multipass info --all`
```text
Name:           master
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 20.04.4 LTS
Image hash:     75a04c7eed58 (Ubuntu 20.04 LTS)
Load:           0.12 0.08 0.09
Disk usage:     2.2G out of 28.9G
Memory usage:   198.5M out of 7.8G
Mounts:         --

Name:           node1
State:          Running
IPv4:           192.168.64.4
Release:        Ubuntu 20.04.4 LTS
Image hash:     75a04c7eed58 (Ubuntu 20.04 LTS)
Load:           0.00 0.03 0.05
Disk usage:     1.4G out of 28.9G
Memory usage:   164.7M out of 7.8G
Mounts:         --

Name:           node2
State:          Running
IPv4:           192.168.64.5
Release:        Ubuntu 20.04.4 LTS
Image hash:     75a04c7eed58 (Ubuntu 20.04 LTS)
Load:           0.00 0.01 0.00
Disk usage:     1.4G out of 28.9G
Memory usage:   171.9M out of 7.8G
Mounts:         --
```

**Additional context**

**Comment by townsend2010** [comment]
The `proc` filesystem is special and cannot be written to by users.  See `man proc` and this StackExchange post (amongst many others): https://stackoverflow.com/questions/47839139/cannot-mkdir-proc-sys-somedir-though-proc-sys-exists
