### ISSUE TITLE
[macOS] Menu bar icon is too large

### ISSUE THREAD

**Issue by yakovmanshin** [canonical/multipass#2650]
**Describe the bug**
multipass GUI client’s icon in menu bar is too large, compared to others (both first- and third-party), and doesn’t have any space on the top and bottom.

**To Reproduce**
1. Launch the GUI client.

**Expected behavior**
The icon in menu bar is smaller and has padding (at least on its top and botton).

**Additional info**
* macOS 12.4
* multipass v1.10 RC

**Screenshots**
![](https://user-images.githubusercontent.com/4648742/178255199-a71fe00c-13d9-4e0b-a8a3-23b43eb02176.jpeg)

**Comment by ONLY78** [comment]
I've noticed this also. It would be great if the MacOS menubar icon was sized correctly (16x16).

This article is helpful in sizing the menubar icon: [https://bjango.com/articles/designingmenubarextras/](https://bjango.com/articles/designingmenubarextras/)

**Comment by townsend2010** [comment]
Hello @yakovmanshin,

We are in the process of switching to the new Multipass logo and getting new icons for this.  We'll make sure the icon fits correctly in the menu bar.

**Comment by asandoval** [comment]
@townsend2010 any updates to be had here?

Would it be possible to squash this (#2650), #1240, and #1733 into #2675 for easier tracking? Thanks!

**Comment by townsend2010** [comment]
Hi @asandoval!

We are still trying to get the new icon assets from the folks that produce these.  These icons are not only intended for macOS, but we have to get new ones for Windows and Linux as well.  There was some initial miscommunication on the matter and it appears they are quite overburdened with work, so it's slow going.

Regarding squashing those bugs into one, I think at this point, I prefer to leave them all separate so I can more easily track what these new icons need to fix when we do receive them.

Thanks!
