### ISSUE TITLE
Multipass support for Hyper-V requires Windows 10 or newer

### ISSUE THREAD

**Issue by andrewsergheev** [canonical/multipass#2655]
Having the issue with launching Multipass which fails and says Multipass support for Hyper-V requires Windows 10 or newer. Tried everything what says here git and tried everything from google. Checked bios too for virtualisation. Compared everything possible with colleagues who's installation was success all the same. Please help.

OS: Microsoft Windows 10 Pro OS Version:                10.0.19044 N/A Build 19044
Hyper V installed and works, tried even installing windows VM on it.

![multi](https://user-images.githubusercontent.com/67071522/178771691-6d1871cc-3ae5-4326-a3d6-9563b3c2ff27.PNG)

**Comment by luis4a0** [comment]
Hi @andrewsergheev, is Hyper-V enabled on your Windows? To check, go to "Turn Windows features on or off", and check that the box labelled "Hyper-V" is ticked. Thanks!

**Comment by andrewsergheev** [comment]
Yes Hyper-V is enabled and even tested with creating windows VM. As I said before we have tried everything we manage to find in google and still shows that error.

**Comment by andrewsergheev** [comment]
I have removed all the screen readers I had and tried everything else in those issue forums nothing helped. Is there anything else can what can help?

**Comment by ricab** [comment]
Hey @andrewsergheev, if you open a PowerShell and run `Get-ItemProperty -Path'HKLM:\\Software\\Microsoft\\Windows NT\\CurrentVersion'`, what does it say? Also could you paste the output you get with an extra `-v`: `multipass launch -vvvv`?

**Comment by andrewsergheev** [comment]
The problem been solved by full reset of a machine and wiping all data from it. Unfortunately that was a last resort in order to proceed.

**Comment by ricab** [comment]
Sorry you had to go that far :confused: I'm closing this now, but please reopen if you have any more relevant info.
