### ISSUE TITLE
How can I create an instance from my local iso

### ISSUE THREAD

**Issue by currycooky** [canonical/multipass#2657]
**What are you trying to do?**
I download "ubuntu-22.04-live-server-arm64.iso" in my Mac, but when I want to create an instance, i must download again, how can i direct used my local iso?

**Comment by luis4a0** [comment]
Hi @currycooky! Launching virtual machines from local image files is supported only on Linux at the moment. However, Multipass will download each image once. You don't need to download Ubuntu images by hand, Multipass will do it for you.

If you absolutely want to launch a virtual machine from your image, [this comment](https://github.com/canonical/multipass/issues/1260#issuecomment-1152222880) will give you an idea of how to proceed. Doing so is currently unsupported, but can help you.

**Comment by luis4a0** [comment]
@currycooky Another detail I missed in my previous answer: not any image is suitable to be used by Multipass. It must be a qcow2 image, with cloud-init already installed on it. I don't think the iso you mentioned will work with Multipass.
