### ISSUE TITLE
`primary` replaced ater stopping in the middle of `apt upgrade`

### ISSUE THREAD

**Issue by ikitayama** [canonical/multipass#2666]
**Describe the bug**
I've accumulated lots of data on primary, which amounts to 100 GB or so, that is no longer accessible and new primary
is an instance with the default 5 GB of storage 

**To Reproduce**
How, and what happened?

Not reproducible. The primary instance got shutdown during apt upgrade.

**Expected behavior**
What did you expect to happen?

Find primary image.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`

**Additional context**

**Comment by luis4a0** [comment]
Hi @ikitayama, could you please provide the logs, as described [here](https://multipass.run/docs/accessing-logs)? Thanks!

I assume the instance ran out of space and hang up, but I can't see why it disappeared.

**Comment by ikitayama** [comment]
I only find multipassd.log there. A quick glance, I am not sure if this has the relevant crash log.

**Comment by ikitayama** [comment]
I am happy to send the log off list if someone can take a look.

**Comment by luis4a0** [comment]
@ikitayama yes, please send the multipassd.log file. Thanks!

**Comment by ikitayama** [comment]
To you?

**Comment by ikitayama** [comment]
[multipassd.log](https://github.com/canonical/multipass/files/9179351/multipassd.log)

**Comment by ricab** [comment]
Hi @ikitayama. I couldn't find any evidence of a VM crash in that log file. 

To try to better understand the issue you experienced, what exactly did you observe when your 100G `primary` instance stopped being "accessible". You're on an M1 mac, correct? So you ran `apt upgrade` inside the instance, then what happened? And how was that instance replaced with a new `primary` with 5G?

**Comment by ikitayama** [comment]
All I recall is: I did upgrade to the latest release, and the vm crashed in the middle of apt upgrade. Then my M1 Max started reporting 1TB of storage was almost full; so I tried to remove unnecessary files and binaries.

**Comment by ricab** [comment]
Hi @ikitayama. So could the lack of disk space have prevented `apt` from going on with the upgrade? And did you manually remove the instance when deleting those *unnecessary* files? How do you think Multipass should have done differently?

**Comment by ikitayama** [comment]
> Hi @ikitayama. So could the lack of disk space have prevented `apt` from going on with the upgrade? And did you manually remove the instance when deleting those _unnecessary_ files? How do you think Multipass should have done differently?

Possibly, and I am not certain if I removed the instance. Sorry.
