### ISSUE TITLE
Improved MacOS App Icon

### ISSUE THREAD

**Issue by ONLY78** [canonical/multipass#2675]
The Multipass MacOS app-icon currently doesn't conform to Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/) (HIG). [1]

Specifically, it's circular in shape.

As such, it does not integrate well with the current 1st party & 3rd party icon-set.

Here is how Apple describes their latest guidelines for their [macOS](https://www.apple.com/macos/monterey/) platform:

> **MacOS.** In macOS, app icons share a common set of visual attributes, including a rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow. 
> 
> **Use the drop shadow in the icon-design template.** The app-icon [template](https://developer.apple.com/design/resources/#macos-apps) [2] includes the system-defined drop shadow that helps your app icon coordinate with other macOS icons.
> 
> **Consider using interior shadows and highlights to add definition and realism.** For example, the Mail app icon uses both shadows and highlights to give the envelope authenticity and to suggest that the flap is slightly open. Shadows and highlights should suggest a light source that faces the icon, positioned just above center and tilted slightly downward.
> 
> **Avoid defining contours that suggest a shape other than a rounded rectangle.** In rare cases, you might want to fine-tune the basic app icon shape, but doing so risks creating an icon that looks like it doesn’t belong in macOS. If you must alter the shape, prefer subtle adjustments that continue to express a rounded rectangle silhouette.

![iWork-Trio-Feature](https://user-images.githubusercontent.com/105243642/180146583-f830eb94-5eb3-44ce-9a3e-f9b86f44c998.jpg)

**What's your proposed solution?**
In order to help Multipass feel native to the MacOS platform, I've created a new [icon.icns](https://media.macosicons.com/parse/files/macOSicons/7ae4922877f1c10b316f2cbdc41a86c1_Multipass.icns) that follows Apple's HIG.

It was designed using Apple's latest template, and exported using https://github.com/jordanbaird/createicns

![Multipass](https://user-images.githubusercontent.com/105243642/180156962-0ce26753-7878-489b-b78c-70683f3c549e.jpg)

Multipass on MacOS now fits right in with all 1st party and 3rd party apps:

![MacOS Dock](https://user-images.githubusercontent.com/105243642/180158162-5daa287e-5304-4507-8d9f-c26ec62d325f.jpg)

I hope that the project devs see this thread, and consider this improvement.

MacOS users can update app-icons themselves, by following this guide: [https://macosicons.com/#/how-to](https://macosicons.com/#/how-to)

**Artwork file**
[Download MacOS .ICNS](https://media.macosicons.com/parse/files/macOSicons/7ae4922877f1c10b316f2cbdc41a86c1_Multipass.icns)

**Additional context**
Here are the two Apple resources I referenced:

[1] https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/
[2] https://developer.apple.com/design/resources/#macos-apps

**Comment by nathan-j-hart** [comment]
Thanks for the input @ONLY78; we are working to get the macOS icons in better shape soon. We have the tray icon ready to go, and I just submitted a request to get a suitable app icon made as well. Once web + design has capacity we will be rolling out our new logo across the board.

**Comment by lyubomir-popov** [comment]
I've created an icon using the tools mentioned by @ONLY78. Can you please check if they work? First time using this workflow so best if someone more familiar with it reviews them. https://assets.ubuntu.com/v1/26263075-multipass-app-icon.icns 

Screenshot: 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/2741678/185985795-717a16bd-d4a2-485b-99b7-0eaa1cda44b0.png">

**Comment by ONLY78** [comment]
I've just checked over your work @lyubomir-popov – correctly output, perfectly sized, looks great.

<img width="372" alt="multipass-dock" src="https://user-images.githubusercontent.com/105243642/185990311-1a9196ad-b45d-45bd-857e-49a93167f336.png">

I would just note, that your drop-shadow looks slightly more diffuse than my output (and other MacOS apps). 

<img width="1021" alt="1" src="https://user-images.githubusercontent.com/105243642/185991736-f74ec622-c46f-46fc-b405-b5255d8ed4a7.png">
<img width="1021" alt="2" src="https://user-images.githubusercontent.com/105243642/185991805-77fa526d-3a70-4e3d-b013-12a8d5e1f60f.png">

This is a very minor point, however to compare notes.. 

1) I used the "[Sketch](https://devimages-cdn.apple.com/design/resources/download/macOS-12-Production-Templates-Sketch.dmg)" template from Apple, and imported the Sketch file into Figma (Dashboard > Import file). 

2) I then placed a hi-res logo PNG onto the Figma canvas and positioned it on the largest tile (512x512@2x).

3) I then selected the 512x512@2x layer, and selected Export to PNG. 

4) I then output to ICNS using the createicns tool.

Let me know if you'd like any assistance.

**Comment by lyubomir-popov** [comment]
Hi @ONLY78, thank you for QA'ing this. I used the photoshop template, maybe that's where the difference in shadows stems from. I've redone it directly in sketch, hopefully this matches your version closer: https://assets.ubuntu.com/v1/57178481-multipass-icon-exported-from-sketch-new.icns
Can you please compare and let me know.

**Comment by ONLY78** [comment]
I've inspected your latest file, again it all looks great (and now identical to my version).

<img width="373" alt="multipass-dock" src="https://user-images.githubusercontent.com/105243642/186364638-3ed4d4bb-5929-45e7-84e5-b29d6c3c8896.png">

I amended my post yesterday, as after closer inspection of both 1st party and 3rd party apps I realised that there was subtle variance across the board with regards to the drop-shadow, and I attribute this to variance in Apple's templates.

Both the 1st version and the 2nd version are perfectly suitable, though I guess I slightly prefer the more defined drop-shadow present in the latest version. In the end, it just comes down to your personal preference @lyubomir-popov 

It's so minor, nobody using the product will know the difference :)

**Comment by lyubomir-popov** [comment]
Thanks for looking into this again @ONLY78. Sketch does it with a drop shadow, photoshop wiht a gaussian blur, both use 10px... so any difference would be a matter of the respetive app's implementation. 

To be honest I think the background colour of the app has more of an effect on how the shadow is perceived - white (as in the photos app) makes the shadow look crisper, because of the higher contrast between the shadow and the white. Orange, especially with an orange desktop wallpaper behind it, looks like it blends in because the shadow darkens the wallpaper and it brings it closer to the colour of our icon.

**Comment by nathan-j-hart** [comment]
Thank you both for the work and feedback here. I think the new icon looks great! Agreed that the different shadows are quite subtle, the latest version works great from my point of view. I'd say this is ready to go!

**Comment by ralgozino** [comment]
Any chance of getting a black&white version of the icon for the tray bar?

The current one looks out of place:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/6362698/216615876-0a88b6b5-2f30-47f4-9250-f2a13e5080c5.png">

**Comment by townsend2010** [comment]
Hi @ralgozino,

Yes, we are currently refreshing our logo and icons and we will have a proper light/dark icon for the status bar.
