### ISSUE TITLE
Port for UWP/Xbox Consoles

### ISSUE THREAD

**Issue by Pedro1234-code** [canonical/multipass#2679]
**What are you trying to do?**
I want to get a port for the Universal Windows Plataform

**What's your proposed solution?**
Port it

**Additional context**

**Comment by townsend2010** [comment]
Hi @Pedro1234-code,

Could you please provide more detail as to what you trying to accomplish with Multipass and what you need?

Thanks!

**Comment by Pedro1234-code** [comment]
I am trying to get linux somehow on the Xbox consoles, when I first saw that there was a build of this program for Windows, I started think that we could port it to UWP and run.

**Comment by townsend2010** [comment]
Oh, that is definitely not in the scope of Multipass.  Hyper-V or Virtualbox would need to run on the XBox in order for Multipass to be able to create virtual machines and I'm quite certain those will not run on XBox.
