### ISSUE TITLE
Please do not restart the existing VM while the snap refresh.

### ISSUE THREAD

**Issue by Airren** [canonical/multipass#2682]
Hi,
Multipass is a very convenient software to manage the VM, but It annoys me every time the snap auto-refreshes the multipass from the `latest/stable` channel to the latest version.  

Because the refreshing will restart all of my VM, that leads to my status application in the VM losing data.

- Can you add the specific version channel to the snap?
- Or,  is there any way to disable snap auto-refresh multipass?
- Or, can I auto refresh it in a time I can control, or tell me the multipass needs an update so that I can back up the VM or reduce my loss before the VM restart.

Thanks.

**Comment by townsend2010** [comment]
Hi @Airren,

Sorry for your troubles with this.  We don't have control of this as it's something that `snapd` controls.  However, it's somewhat possible to control this by adjusting some values via this doc: https://snapcraft.io/docs/keeping-snaps-up-to-date

Other than this, this is a subject often discussed on the Snap forums for various snaps.

**Comment by Airren** [comment]
Thanks for your information. It's useful.
