### ISSUE TITLE
`-bash: /usr/bin/df: Input/output error`

### ISSUE THREAD

**Issue by ikitayama** [canonical/multipass#2686]
**Describe the bug**
Unable to conduct filesystem operations

**To Reproduce**
How, and what happened?
In a VM (primary), df does not return a proper result.

**Expected behavior**
df returns a current usage.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: macOS
- multipass   1.10.1+mac
   multipassd  1.10.1+mac
- `multipass info --all` 
```Name:           primary
State:          Running
IPv4:           192.168.64.20
Release:        Ubuntu 20.04.4 LTS
Image hash:     0f1a20bcda28 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver`

**Additional context**

**Comment by ikitayama** [comment]
Is there a way to recover from read-only filesystem?

**Comment by ricab** [comment]
Hi @ikitayama, are you perhaps hitting disk space limits again?

**Comment by ikitayama** [comment]
Not this time

**Comment by ricab** [comment]
Hi @ikitayama, do you have any idea how this came about? Any logs we could look at? What makes you think this is a Multipass problem?

**Comment by ikitayama** [comment]
The multipass instance is quite fragile; terminal gets disappeared while
using it etc

**Comment by ikitayama** [comment]
> Hi @ikitayama, do you have any idea how this came about? Any logs we could look at? What makes you think this is a Multipass problem? 

Does multipass provide it's instances a tool to fix file system issues?

**Comment by ricab** [comment]
No, not at the moment, but it is something that we're considering: #1910 .

**Comment by ikitayama** [comment]
For now, I just fix the QEMU image manually by mounting it to another vm as
you proposed there?

**Comment by ricab** [comment]
Hi @ikitayama, yes, you could try to [mount the image](https://gist.github.com/CodeBrauer/827ac03eab15215d36aaa773e740ecee) and see what you can recover inside. Have a look at `/var/root/Library/Application\ Support/multipassd/{qemu/,}vault/instances` for the image files.

**Comment by ikitayama** [comment]
@ricab In that directory, I've done converting it to raw, then converting back to qcow2 again.

```
sh-3.2# qemu-img check ubuntu-20.04-server-cloudimg-arm64.img
No errors were found on the image.
306976/2097152 = 14.64% allocated, 0.00% fragmented, 0.00% compressed clusters
Image end offset: 20125450240
```

However, Ubuntu reports it is a read-only filesystem still.

**Comment by ricab** [comment]
The idea was to mount the image so that you could recover data from it. 

Other than that, I don't know why the filesystem would go read-only. If you have any ideas of how to reproduce the issue or logs of when it happened, I can look into it.

**Comment by ikitayama** [comment]
Is Multipass implemented so that if there's no default image, .img file in that directory, delete all the other irrelevant files and create a new image file?

**Comment by ricab** [comment]
No @ikitayama, that image file contains the instance's data. Without it, the instance is gone. You can of course always create new instances with the same release.
