### ISSUE TITLE
Multipass fails to launch "primary" Instance

### ISSUE THREAD

**Issue by vrv501** [canonical/multipass#2688]
**Describe the bug**
I installed multipass on Windows 10 Home with driver set to virtualBox. When I try to launch the primary instance it fails with the following message:
```
[2022-07-31T21:11:33.121] [error] [primary] Could not unregister VM: VBoxManage.exe: error: Cannot unregister the machine 'primary' while it is locked
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp

launch failed: Could not start VM: Waiting for VM "primary" to power on...
VBoxManage.exe: error: Could not open the medium 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\primary\ubuntu-20.04-server-cloudimg-amd64.vdi'.
VBoxManage.exe: error: VD: error VERR_PATH_NOT_FOUND opening image file 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\primary\ubuntu-20.04-server-cloudimg-amd64.vdi' (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium
```

Both multipass and vitualbox are installed in the following directory:
`D:\Program Files\` (not C: drive)

**To Reproduce**
How, and what happened?
1. Open Shell from multipass system tray
2. Multipass fails to launch the instance

**Expected behavior**
Working primary Instance with proper configuration

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Win10 Home 19044
- Version: 1.10.1-win
- Driver: virtualbox

**Additional context**

**Comment by SqlSusan** [comment]
Same for me with:
Windows: 10.0.22621
VirtualBox: 7.0.6 r155176
Multipass: 1.11.1-win

**Comment by vrv501** [comment]
Switched to virtualbox
