### ISSUE TITLE
Multipass fails to detect extra IP on jammy - works on bionic and focal

### ISSUE THREAD

**Issue by chaddupuis** [canonical/multipass#2694]
**Describe the bug**
On Mac (haven't tested elsewhere)

% multipass launch bionic -n btest --network en0
Launched: btest                                                                 
% multipass launch focal -n ftest --network en0
Launched: ftest                                                                 
% multipass launch jammy -n jtest --network en0
Launched: jtest                                                                 

% multipass ls
Name                    State             IPv4             Image
btest                   Running           192.168.64.16    Ubuntu 18.04 LTS
                                          192.168.0.169
ftest                   Running           192.168.64.17    Ubuntu 20.04 LTS
                                          192.168.0.170
jtest                   Running           192.168.64.18    Ubuntu 22.04 LTS

* note no bridged network on jammy, but fine on bionic and focal.

**To Reproduce**
see steps above

**Expected behavior**
Get a bridged network in all cases

**Logs**
no errors

**Additional info**
% multipass version
multipass   1.10.1+mac
multipassd  1.10.1+mac

**Comment by ricab** [comment]
Hi @yyhmsg, I just tried that and confirm that `multipass ls` is not showing the extra ip on a Jammy instance, even though it is there. Could you please try `multipass exec jtest -- ip -c -br a` and confirm that you see the extra IP as well?

**Comment by ricab** [comment]
This is not particular to macOS, I get the same on Linux.

**Comment by yyhmsg** [comment]
@ricab sure enough it is there - thanks for looking into this!
% multipass exec preferable-escolar -- ip -c -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp0s1           UP             192.168.64.22/24 metric 100 fdd7:97cc:4676:c1fb:5054:ff:feca:8d2d/64 fe80::5054:ff:feca:8d2d/64 
enp0s2           UP             192.168.0.160/24 metric 200 fe80::5054:ff:fe86:f560/64

**Comment by ricab** [comment]
OK, thanks for letting us know. I am guessing some format change is tripping our parsing. We'll share as we find more about it. Thanks again for reporting!

**Comment by ricab** [comment]
Hey @yyhmsg, just to let you know that this is solved and the fix will be available in the next release.

**Comment by antyung88** [comment]
I have multipass running lxd on macos and uses brew lxc remote to access vms.

not sure if this is related but I am unable to ping lxc containers running in multipass from macOS.

```
PING 192.168.64.162 (192.168.64.162): 56 data bytes
ping: sendto: No route to host
Request timeout for icmp_seq 0
ping: sendto: Host is down

```
