### ISSUE TITLE
multipass launch docker not install docker in vm instance

### ISSUE THREAD

**Issue by xiaoxipangren** [canonical/multipass#2697]
Runing 'multipass launch docker' in git-bash on windows 11 doesn't initialize docker environment in vm instance, 'bash: line 1: docker: command not found' was got when 'multipass exec docker docker', and running docker after multipass shell docker just get suggestiong for installing docker.

  
user@windows:~>mp launch docker
Launched: docker
Skipping mount due to disabled mounts feature

user@windows:~>mp exec docker docker
bash: line 1: docker: command not found

user@windows:~>mp shell docker
Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.0-41-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Aug  6 14:24:00 CST 2022

  System load:  0.17236328125     Processes:             109
  Usage of /:   4.3% of 38.58GB   Users logged in:       0
  Memory usage: 7%                IPv4 address for eth0: 172.25.188.86
  Swap usage:   0%

36 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sat Aug  6 14:23:38 2022 from 172.25.176.1
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@docker:~$ docker
Command 'docker' not found, but can be installed with:
sudo apt install docker.io      # version 20.10.12-0ubuntu4, or
sudo apt install podman-docker  # version 3.4.4+ds1-1ubuntu1

**Comment by townsend2010** [comment]
Hi @xiaoxipangren,

Sorry for your troubles.  It seems your instances are unable to resolve host names and as such, it failed installing docker, etc. inside the instance.  This networking is all provided by Hyper-V, so it seems there is some setting or network configuration on your host that is interfering with this.  Without knowing if you have a VPN, proxy, etc. running, perhaps something in https://multipass.run/docs/troubleshoot-networking#heading--troubleshoot-networking-on-windows will help you sort it out.

Thanks!
