### ISSUE TITLE
`docker-compose` alias does not behave the same as local `docker-compose`

### ISSUE THREAD

**Issue by ObliviousHarmony** [canonical/multipass#2707]
**Describe the bug**
I was hoping to utilize Multipass' Docker preset [with `wp-env`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/) but have run into problems because a `docker-compose` alias doesn't behave the same way that a local `docker-compose` with the `DOCKER_HOST` environment variable set. 

When I run the `wp-env start` command, internally, it runs `child_process.spawn()` on `docker-compose`. This bypasses the local shell and just passes the arguments directly to the target executable. When I run this using a `docker:docker-compose` alias, I get the following error:

```
bash: -c: line 1: syntax error near unexpected token `('
bash: -c: line 1: `'cd' '/Users/obliviousharmony/Code/WordPress/gutenberg/packages/env'&&'docker-compose' '-f' '/Users/obliviousharmony/.wp-env/fcc19ccf5624bfb3d7f4b1258f0d4ea7/docker-compose.yml' 'run' '-T' 'tests-cli' 'bash' '-c' "set -eo pipefail && wp core install --url="localhost:8889" --title="env" --admin_user=admin --admin_password=password --admin_email=wordpress@example.com --skip-email && wp config set WP_DEBUG false --anchor="define( 'WP_DEBUG'," --raw && wp config set SCRIPT_DEBUG false --anchor="define( 'WP_DEBUG'," --raw && wp config set WP_ENVIRONMENT_TYPE "local" --anchor="define( 'WP_DEBUG'," && wp config set WP_PHP_BINARY "php" --anchor="define( 'WP_DEBUG'," && wp config set WP_TESTS_EMAIL "admin@example.org" --anchor="define( 'WP_DEBUG'," && wp config set WP_TESTS_TITLE "Test Blog" --anchor="define( 'WP_DEBUG'," && wp config set WP_TESTS_DOMAIN "localhost" --anchor="define( 'WP_DEBUG'," && wp config set WP_SITEURL "http://localhost:8889/" --anchor="define( 'WP_DEBUG'," && wp config set WP_HOME "http://localhost:8889/" --anchor="define( 'WP_DEBUG',""'
```

**To Reproduce**
How, and what happened?

1. Use the `docker` workflow to set up a Docker environment
2. Shell into the `docker` container and install NodeJS, I used v14 for this reproduction
3. Use `multipass alias docker:docker` to set up a local alias
4. Create a file named `2707-repro.js` in your home directory with this content:
```javascript
const { spawn } = require('child_process');

const test = spawn('docker', [
    'run',
    'ubuntu',
    'bash',
    '-c',
    `echo "test: ('complete')"`
]);

let output = '';
test.stdout.on('data', (data) => {
    output += data;
});

let errOutput = '';
test.stderr.on('data', (data) => {
    errOutput += data;
});

test.on('close', () => {
    console.log(output);
    if (errOutput != '') {
        console.error(errOutput);
        process.exit(-1);
    }
});

```
5. `cd` into your home directory on the host and run `node 2707-repro.js`. You should see the same error experienced with `wp-env`.
6. `cd` into the mapped home directory from a shell in the `docker` VM and run the above command again. You should see the `ls -la` and `echo` output from within the `ubuntu` Docker container without any error.

**Expected behavior**
I _was_ expecting it to behave exactly like running `docker-compose` locally. The [potentially relevant documentation](https://multipass.run/docs/exec-shells) seems to indicate that it should be processed in the same way that I expect, but, in practice, something seems to be going wrong.

**Logs**
This doesn't really seem related to be honest, everything is working perfectly fine!

**Additional info**
`multipass version`
```
multipass   1.10.1+Mac
multipassd  1.10.1+Mac
```
- `multipass info --all`
```
Name:           docker
State:          Running
IPv4:           192.168.64.2
                172.17.0.1
                172.18.0.1
Release:        Ubuntu 22.04.1 LTS
Image hash:     4247b344c976 (Ubuntu 22.04 LTS)
Load:           0.11 0.13 0.16
Disk usage:     4.8G out of 38.6G
Memory usage:   539.1M out of 3.8G
Mounts:         /Users/obliviousharmony => /Users/obliviousharmony
                    UID map: 501:default
                    GID map: 20:default
```
- `multipass get local.driver`
```
qemu
```

**Comment by luis4a0** [comment]
Hi @ObliviousHarmony, thanks for your input. This must be an argument passing problem. Does the command work correctly if executed inside the instance?

**Comment by ObliviousHarmony** [comment]
Hi @luis4a0,

I'm currently on parental leave but will have an opportunity to check next week.

Thanks!

**Comment by ObliviousHarmony** [comment]
Hi @luis4a0,

When I run the `wp-env start` command from inside the Docker instance it works as expected.

**Comment by ObliviousHarmony** [comment]
Hi @luis4a0,

Now that I've returned from parental leave, I have created a minimal reproduction and updated the reproduction steps in the issue. You can play around with the `echo` output in the script and you'll note that even without the parentheses it removes everything in the single quotes. Hopefully this helps with diagnosing and fixing the issue!

**Comment by ObliviousHarmony** [comment]
Hi @luis4a0,

I took a look at the internals of `multipass` and I have some thoughts. In the initial issue I noted that Node's `child_process.spawn()` does not use a shell to execute the command by default. When `docker` is installed natively this doesn't cause any issues because we're passing the desired input to Docker verbatim. When using an alias or `multipass exec` however, the command is executed using `ssh`. This ends up passing the input through a shell, but, nothing was escaped with the expectation being that it would bypass the shell.

I would imagine there's probably a way to detect whether or not the command is being executed using a shell. If that's the case we could then escape the input so that the resulting command runs as-expected on the guest operating system. I haven't invested a ton of time into how best to solve this problem, but, I'm open to suggestions if you have any! As an aside, while I can look at contributing a solution, I haven't used C++ in quite some time. I don't really have an environment available for it, but, I'd set it up if it meant being able to move this along sooner.

**Comment by ObliviousHarmony** [comment]
Hi @luis4a0,

I've spent some more time digging and I think it's because of [the behavior of `quote_for()` here](https://github.com/canonical/multipass/blob/e02fff4d99c91855fcd597de2c152a1069d5657c/src/utils/utils.cpp#L60). `child_process.spawn()` is passing `echo "test: ('complete')"` as a string argument containing both single and double quotes. This causes the input to be wrapped in double quotes, but, the double quotes already in the string don't get escaped. These quotes aren't added when executing the script from the `docker` VM and this difference leads to the issue. 

I think the solution here would be to make `quote_for` more robust. I would take a swing at a fix, but, I don't have a development environment that I can use to develop the fix, let alone test it. Even that aside, I don't know that I have enough context to be able to make the change. Current users of `multipass exec` are likely already escaping strings in whatever way makes them function and we need to be careful not to break those existing workflows.

I hope all of this helps and was a reasonable investment of my time. I'd really like to see this fixed so that I can use an alias instead of my current workaround!

**Comment by ObliviousHarmony** [comment]
Hey @townsend2010,

I hate to be _that guy_, but, it would be great to get some feedback on this issue from someone!

**Comment by luis4a0** [comment]
Hey @ObliviousHarmony,

sorry for the delay, I am investigating your issue. Thanks for the deep study of the problem, that certainly helps!

**Comment by ObliviousHarmony** [comment]
Thanks for the update @luis4a0!

**Comment by luis4a0** [comment]
Hi @ObliviousHarmony! Can you please try with [this package](https://multipass-ci.s3.amazonaws.com/pr3050/multipass-1.13.0-dev.530.pr3050%2Bg13b7d2ac.mac-Darwin.pkg) and see if the error was fixed? Thanks!

**Comment by ObliviousHarmony** [comment]
Hi @luis4a0,

I receive this error from `multipass` after installing that package:

```
dyld[73791]: Library not loaded: /opt/homebrew/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: <20125C65-4337-39C3-AA99-0FF6D03CA12A> /Library/Application Support/com.canonical.multipass/lib/QtCore.framework/Versions/5/QtCore
  Reason: tried: '/opt/homebrew/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/opt/homebrew/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/usr/lib/libgthread-2.0.0.dylib' (no such file, not in dyld cache)
zsh: abort      multipass
```

**Comment by luis4a0** [comment]
Hi @ObliviousHarmony, that issue is unrelated to the fix itself. We are working on solving it and will let you know when it's done. Sorry for the inconvenience and thanks for your patience!
