### ISSUE TITLE
multipass networks -- doesnt do anything

### ISSUE THREAD

**Issue by hubbertsmith** [canonical/multipass#2708]
(base) root@u6:/home/hubbert/multipass3# multipass networks --all
Unknown option 'all'.
(base) root@u6:/home/hubbert/multipass3# multipass networks demo-i4ops
This command takes no arguments
(base) root@u6:/home/hubbert/multipass3# multipass networks
networks failed: The networks feature is not implemented on this backend.
(base) root@u6:/home/hubbert/multipass3#

**Comment by townsend2010** [comment]
Hi @hubbertsmith!

It's not clear if you are on macOS or Linux for your host, but as the error states, the driver you have running doesn't support additional networks.  See https://multipass.run/docs/networks-command for the list of supported drivers.

To see which driver you are running, you can issue `$ multipass get local.driver`.  If you are on Linux, you need to use the `lxd` driver and if you are on macOS, you need to use the `qemu` driver.

FYI, we may support additional networks with the `qemu` driver on Linux in the future.

**Comment by hubbertsmith** [comment]
Hi Chris
I am on Ubuntu focal    thanks for the response!!

not quite there .. here is what I see

(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass networks
networks failed: The networks feature is not implemented on this backend.
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass get local.driver
qemu
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# apt install lxd
Reading package lists... Done
Building dependency tree
Reading state information... Done
lxd is already the newest version (1:0.10).
The following packages were automatically installed and are no longer
required:
afterstep-data libafterimage0 libafterstep1 libfwupdplugin1 menu menu-xdg
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass set local.driver=lxd
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass get local.driver
get failed: cannot connect to the multipass socket
Please ensure multipassd is running and
'/var/snap/multipass/common/multipass_socket' is accessible
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass stop --all
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass set local.driver=lxd
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3# multipass get local.driver
get failed: cannot connect to the multipass socket
Please ensure multipassd is running and
'/var/snap/multipass/common/multipass_socket' is accessible
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#
(base) ***@***.***:/home/hubbert/multipass3#

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by townsend2010** [comment]
You definitely want to install the LXD snap. The Debian package version is transitional and doesn't do anything.
`$ sudo snap install lxd`

Once that is installed and initialized via `lxd init` (the defaults are usually fine), then you need to connect multipass to the lxd interface:
`$ sudo lxd init`
and
`$ sudo snap connect multipass:lxd lxd`

If multipass still has issues connecting to lxd, then try restarting multipass:
`$ sudo snap restart multipass`

Hope this helps!

**Comment by hubbertsmith** [comment]
Hurray it worked
thanks so much for your help
CLI multipass networks now works

I am also able to install and run zerotier networks from within MP instance
p-cool

now, if I could just get to desktop X11-Wayland to cooperate
(not asking you to do anything, just staying on your radar)

thanks a TON. I hope I can return the favor soon
cheers



***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by townsend2010** [comment]
Ok, great!  Gonna close this then.

**Comment by hubbertsmith** [comment]
(no big deal, just fyi) switching from QEMU to LXD nuked the instances I
made with QEMU

kinda weird -- I started Multipass on a ubuntu system ... it complained,
error messages saying my bios wasnt configured tof VMs
after I installed LXD, that error message went away and its behaving

thanks a ton

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by townsend2010** [comment]
Those `qemu` instances are still there, but "hidden" and would be visible again if you switched back to the `qemu` driver.  It's not so straight forward to convert our qemu instances into LXD ones which is why we hide them.

Weird about the BIOS error going away after using LXD. :man_shrugging:
