### ISSUE TITLE
Multipass crashes on `delete -p` when using the LXD driver

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2714]
**Describe the bug**
Multipass crashes with an exception reaching a forbidden boundary when trying to purge-delete an instance. This happens after the instance has been successfully deleted in LXD and Multipass requests its state again. Presumably, that's coming out of [here](https://github.com/canonical/multipass/blob/main/src/platform/backends/lxd/lxd_virtual_machine.cpp#L199).

```
$ mp delete -p primary
delete failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
```

And this in the log, after the instance is deleted:

```
ago 23 17:28:12 ricab-xps13 multipassd[77722]: Requesting LXD: GET unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/virtual-machines/primary/state?project=multipass
ago 23 17:28:12 ricab-xps13 multipass.multipassd[77722]: terminate called after throwing an instance of 'multipass::LXDNotFoundException'
ago 23 17:28:12 ricab-xps13 multipass.multipassd[77722]:   what():  LXD object not found
```

**To Reproduce**
How, and what happened?
1. `multipass set local.driver=lxd`
1. `multipass launch`
1. `multipass delete -p <instance>`

**Comment by ricab** [comment]
`mp::top_catch_all` may come in handy for this.

**Comment by holta** [comment]
ASIDE/FYI:

`multipass delete` with LXD fails regularly when trying to delete several (and especially when to delete lots of instances).

Typically only 1 of the instances is deleted, with a very ambiguous error message.

(Certainly this happened repeatedly in recent days, when running the edge channel of Multipass on Ubuntu 22.04)

**Comment by townsend2010** [comment]
Hey @holta,

Yes, it's a regression introduced recently.  We are working on the fix and should have a PR up soon.  Thanks!
