### ISSUE TITLE
BUG - multipass doesn't work on Windows with VirtualBox

### ISSUE THREAD

**Issue by matheusjaraujo** [canonical/multipass#2728]
**Describe the bug**
When I use multipass on Windows with VirtualBox it just doesn't work.

**To Reproduce**
Command: ``multipass launch``

**Expected behavior**
I expected multipass to download the Ubuntu server image, set a generic name for the VM and start it.

**Logs**
[dump.zip](https://github.com/canonical/multipass/files/9457572/dump.zip)

Output Prompt of Command:
> ``
[2022-08-30T22:09:59.211] [error] [credited-frogmouth] Could not unregister VM: VBoxManage.exe: error: Could not find a registered machine named 'credited-frogmouth'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMName).raw(), machine.asOutParam())" at line 150 of file VBoxManageMisc.cpp
``

**Additional info**
Windows 10 Pro x64 21H2 (19044.1889)
VirtualBox 6.1.36 r152435 (Qt5.6.2)

Command: ``multipass info --all``
> empty (it doesn't show anything in the cli).

Command: ``multipass get local.driver``
> virtualbox

Command: ``multipass version``
> multipass   1.10.1+win
> multipassd  1.10.1+win

**Additional context**
I also tested with the command prompt in user mode with administrative privileges and common user, in both cases the bug persists.

**Comment by luis4a0** [comment]
Hi @matheusjohannaraujo, can you please send us the logs, as described [here](https://multipass.run/docs/accessing-logs#heading--windows)? Thanks!

**Comment by matheusjohannaraujo** [comment]
@luis4a0

Done, I added above the log file `dump.evtx`.

**Comment by luis4a0** [comment]
Hi @matheusjohannaraujo, thanks for the logs. It seems there is an instance running; what does `multipass list` return? Do you have enough disk space to allocate a new instance?

**Comment by matheusjohannaraujo** [comment]
Hi @luis4a0.

In virtualbox I mapped to instantiate the machines on my SSD drive in `D:`, it's a volume that has a lot of free space!

**Comment by luis4a0** [comment]
Hey, that was it! You need to set the `MULTIPASS_STORAGE` environment variable in order to point to a folder in `D:`. No need to change the folder in the VirtualBox interface (moreover, you should roll back the folder change in VirtualBox before setting `MULTIPASS_STORAGE`, so the previous instances can be seen by Multipass).

**Comment by luis4a0** [comment]
Since there was no answer, I close the ticket for now. Don't hesitate in reopening if the issue persists. Thanks.
