### ISSUE TITLE
sudo modprobe vcan  not find modprobe: FATAL: Module vcan not found in directory /lib/modules/5.15.0-46-generic

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [canonical/multipass#2730]
**What are you trying to do?**
A description of what you want to happen.
I want use socketCAN such as vcan in mutilpass
**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.

**Additional context**

**Comment by townsend2010** [comment]
Hi @wangwenqiangGitHub,

You need to install the extra kernel modules via `sudo apt-get install linux-modules-extra-5.15.0-46-generic`.
