### ISSUE TITLE
How can I increase disk_space 

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [canonical/multipass#2736]
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: mac M1
multipass --version
multipass   1.10.1+mac`

**Additional context**

**Comment by luis4a0** [comment]
Hi @wangwenqiangGitHub, this can be done through the command-line interface, as decribed [here](https://multipass.run/docs/modify-an-instance#heading--set-the-cpu-ram-or-disk-of-an-instance).

**Comment by wangwenqiangGitHub** [comment]
> Hi @wangwenqiangGitHub, this can be done through the command-line interface, as decribed [here](https://multipass.run/docs/modify-an-instance#heading--set-the-cpu-ram-or-disk-of-an-instance).

![image](https://user-images.githubusercontent.com/28779327/188638372-2421a3d0-69c4-415f-af4e-986f593abb67.png)

**Comment by townsend2010** [comment]
Hi @wangwenqiangGitHub,

Your screen grab doesn't show where you are trying to increase disk space as the bug describes.  I do see that you have an instance in an `Unknown` state indicating that your instance is not getting an IP address from macOS's `bootp` server.  Is that the problem you are trying to indicate?  If so, please include logs as outlined [here](https://multipass.run/docs/accessing-logs).

**Comment by townsend2010** [comment]
Ok, it seems there is some issue with the instance itself where it won't boot.  Running out of disk space unfortunately can cause this problem and there really isn't much Multipass can do about that once it is fully out of disk space.  Are you able to just start over again with this instance or is there critical data on the instance you need?
