### ISSUE TITLE
Unable to upgrade instance

### ISSUE THREAD

**Issue by hutger** [canonical/multipass#2739]
**Describe the bug**
Not being able to upgrade instance cpu and memory.

**To Reproduce**
Trying to upgrade an instance, I've got the error below:

```shell
multipass set local.k3s.memory=8gb         
set failed: The Instance modification feature is not implemented on this backend.
```
When moving the instance to quem driver, I'm required to authenticate first:
```shell
sudo multipass set local. Driver=qemu                

Password:
set failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
```
Even after being authenticated, still not able to upgrade instance to quem.

```shell
$ multipass authenticate                                                              
Please enter passphrase:

sudo multipass set local. Driver=quem     

Password:
set failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
```
**In a nutshell, I'm not able to upgrade instance resources.**

**Expected behavior**
Being able to upgrade instance resources.

**Additional info**
 - OS: `macOS 12.4` 
```
multipass version`
multipass   1.10.1+mac
multipassd  1.10.1+mac
``` 

``` 
- `multipass info --all`
Name:           k3s
State:          Stopped
IPv4:           --
Release:        --
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
``` 
``` 
multipass get local. Driver
hyperkit
``` 

**Additional context**

**Comment by townsend2010** [comment]
Hi @hutger,

Yes, we made a conscious decision not to implement instance modification for the `hyperkit` driver due to plans to deprecate and eventually remove support for it.  There is a `qemu` driver for macOS and we are currently working on a [solution](https://github.com/canonical/multipass/issues/2326) for migrating the Hyperkit instances to Qemu instances along with the Hyperkit deprecation.

**Comment by townsend2010** [comment]
Oh, also, regarding setting the driver, you do **not** need to use `sudo` and you also mistyped `qemu`.  All you need to do is this:

`$ multipass set local.driver=qemu`
