### ISSUE TITLE
launch failed: Downloaded image hash does not match                             

### ISSUE THREAD

**Issue by unnimona** [canonical/multipass#2747]
multipass launch focal

launch failed: Downloaded image hash does not match                             

multipass launch jammy

launch failed: Downloaded image hash does not match                             

please fix the error

**Comment by townsend2010** [comment]
Looks like you've hit #1714.  It's a bug in Qt that isn't fixed.  You didn't say what platform you are running Multipass on, so I can't tell you how to work around this.

**Comment by townsend2010** [comment]
Duplicate of #1714

**Comment by unnimona** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by townsend2010** [comment]
You need to do the following:
- `$ sudo rm /var/snap/multipass/common/cache/multipassd/network-cache`
- `$ sudo snap restart multipass`

If that doesn't clear it up, then there is something wrong with the download of the image where it's being corrupted and that would be something with your network, computer, etc.

**Comment by Javabender333** [comment]
Hello @townsend2010 how will I work around this on a mac m1
