### ISSUE TITLE
Accessing multipassd through gRPC

### ISSUE THREAD

**Issue by ethicnology** [canonical/multipass#2764]
**Describe the bug**
Following the [remote multipass](https://multipass.run/docs/how-to-use-multipass-remotely-a-preview) guide.
When I use the CLI I can access to it:
```
MULTIPASS_SERVER_ADDRESS=pop-os:51005 multipass find
```
**I'm not able to access multipassd through gRPC (using [gRPCurl](https://github.com/fullstorydev/grpcurl))…**

**To Reproduce**
How, and what happened?
1. edit snap.multipass.multipassd.service and place content along these lines (replace <hostname> with the hostname or the IP you want it to listen on) in:
```
[Service]
ExecStart=
ExecStart=/usr/bin/snap run multipass.multipassd --address <hostname>:51005
```
2. restart multipassd
3. Try to ping it via gRPC
```sh
$ grpcurl -insecure -proto multipass.proto -d '' pop-os:51005 multipass.Rpc/ping
ERROR:
  Code: Unauthenticated
  Message:
```
```sh
$ grpcurl -proto multipass.proto -d '' pop-os:51005 multipass.Rpc/ping
Failed to dial target host "pop-os:51005": x509: certificate relies on legacy Common Name field, use SANs instead
```
```sh
$ grpcurl -plaintext -proto multipass.proto -d '' pop-os:51005 multipass.Rpc/ping
Failed to dial target host "pop-os:51005": context deadline exceeded
```

**Expected behavior**
In a local environment, I expect to get a response like the CLI.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: popOS 22.04
- multipass   1.10.1
```
Name:           select-llama
State:          Running
IPv4:           10.80.103.83
Release:        Ubuntu 22.04.1 LTS
Image hash:     0fcb96fbfd71 (Ubuntu 22.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.6G out of 4.7G
Memory usage:   168.9M out of 969.5M
Mounts:         --
```
- qemu

**Additional context**

**Comment by luis4a0** [comment]
Hi @ethicnology, thanks for bringing this. For the moment, the RPC interface is not open. The only methods we support for communicating with the daemon are the GUI and the CLI.
