### ISSUE TITLE
System Data taking more than 500GB of 1TB Flash Storage on M1

### ISSUE THREAD

**Issue by ikitayama** [canonical/multipass#2765]
I encounter this situation before and I had to delete the Multipass instance(s) to write data to the storage.

How do I check the real size that Multipassd is using on M1? If it's using that amount of storage, there's something wrong with Multipass as I have only one VM of size 100GB.

Can experts advise as to what I can do to get the usage normal?

**Comment by ikitayama** [comment]
Rebooting Mac had the system understood the true disk usage.

**Comment by ricab** [comment]
Good to know it got sorted, @ikitayama.
