### ISSUE TITLE
False error: timeout on start VM from template

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/multipass#2772]
**Describe the bug**
When start a VM from a template multipass exits with non zero telling that it has timed out.
However, template timeout is 1200s (20 min). Real execution process was 486s

**To Reproduce**
1. `multipass launch charm-dev -n name-vm -m 8g -c 3 -d 30G`

Get:
![20221004_11-59-06](https://user-images.githubusercontent.com/51964909/194072614-fd6a1a98-7182-4eff-b02b-99fb6692e540.png)

When shell to the machine:
![20221004_12-10-09](https://user-images.githubusercontent.com/51964909/194072706-66489741-6578-4b52-b9f3-9f568d8fe6be.png)

**Expected behavior**
No timeout error, normal start

**Additional info**
 - OS: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

- `multipass version`
multipass   1.10.1
multipassd  1.10.1

- `multipass info --all`
```
Name:           charm-dev
State:          Running
IPv4:           10.112.13.105
                10.135.56.1
                10.1.157.64
Release:        Ubuntu 20.04.4 LTS
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           0.78 0.85 1.01
Disk usage:     15.7G out of 19.2G
Memory usage:   2.3G out of 7.8G
Mounts:         /home/maksim/git/fastapi-demo => /fastapi-demo
                    UID map: 1000:default
                    GID map: 1000:default

Name:           operator-day
State:          Stopped
IPv4:           --
Release:        --
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           prometheus-vm
State:          Running
IPv4:           10.112.13.235
                10.66.176.1
                10.1.91.192
Release:        Ubuntu 22.04.1 LTS
Image hash:     0fcb96fbfd71 (Ubuntu 22.04 LTS)
Load:           0.46 0.55 0.37
Disk usage:     10.3G out of 28.9G
Memory usage:   1.7G out of 7.8G
Mounts:         /home/maksim/git/prometheus-k8s-operator => /prometheus-k8s-operator
                    UID map: 1000:default
                    GID map: 1000:default

Name:           vivid-kakapo
State:          Stopped
IPv4:           --
Release:        --
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           zinc-vm-bare
State:          Stopped
IPv4:           --
Release:        --
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

- `multipass get local.driver`
qemu

**Logs**
[logs.txt](https://github.com/canonical/multipass/files/9716090/logs.txt)

**Comment by luis4a0** [comment]
Hi @beliaev-maksim, thanks for reporting this. If I understand correctly, you hit the 20 minute timeout but in the logs it says it took 486 seconds, right?

**Comment by beliaev-maksim** [comment]
@luis4a0 
that is correct

and my wall clock also told me that it took definitely less than 20min

**Comment by taurus-forever** [comment]
I am able to reproduce the same issue on Ubuntu 22.10, multipass 1.11.0, lxd 5.10-b392610:
```
multipass launch charm-dev # starts without any issues on my laptop

multipass launch -c 8 -m 8G -n my-dev charm-dev # timeout error
```
While logs reports, all OK:

```
ubuntu@my-dev:~$ tail -1 /var/log/cloud-init-output.log
The system is finally up, after 365.66 seconds
```

**Comment by taurus-forever** [comment]
I have monitored the command `time multipass launch charm-dev`  and `tail -1 /var/log/cloud-init.log` (in the separate windows), it is a really simple timeout issue:
 1) `multipass launch` aborts with timeout ~5 minutes
 2) in several seconds `cloud-init.log` reports all done "The system is finally up, after 365.66 seconds". 

It looks like the [timeout](https://github.com/canonical/multipass-blueprints/blame/main/v1/charm-dev.yaml#L27) inside blueprint is simply ignored and `multipass launch` always aborted after ~5 minutes:

```
> time multipass launch --cpus 2 --memory 4Gb --disk 50Gb -n test-time charm-dev
launch failed: The following errors occurred:                                   
timed out waiting for initialization to complete
                                                                                
real	5m22.930s
user	0m0.083s
sys	0m0.140s

> time multipass launch --cpus 2 --memory 4Gb --disk 50Gb -n test-time --timeout 12000 charm-dev
Launched: test-time                                                             
                                                                                
real	6m20.926s
user	0m0.116s
sys	0m0.139s
```

Q: the blueprint timeout has been [bumped previously](https://github.com/canonical/multipass-blueprints/pull/20) to high enough value 20 minutes. I guess it did the job for previous multipass version, but broken for current version `1.11.0`?

P.S. We are [using](https://github.com/canonical/mysql-k8s-operator/pull/148) `multipass launch` in our charm documentation and need to avoid timeout in the first command in manuals? :-)
