### ISSUE TITLE
Support Ubuntu Core 20 and 22 images

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2776]
**What are you trying to do?**
To `multipass launch core20`, and `core22`.

**What's your proposed solution?**
Now that UEFI is more broadly supported in Multipass, we should be able to add the images in.

**Additional context**
- #2395 has it added for LXD, it should be possible to use for Hyper-V and QEMU now? VirtualBox?

**Comment by andrei-toterman** [comment]
Hi, @Saviq! This was addressed in #2698 :smile:

**Comment by Saviq** [comment]
Fixed by #2698, then! :)
