### ISSUE TITLE
Where download img file ? 

### ISSUE THREAD

**Issue by nulllpoint** [canonical/multipass#2787]
I found three files multipass images dir,
- ubuntu-20.04-server-cloudimg-amd64-initrd-generic
- ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
- ubuntu-20.04-server-cloudimg-amd64.img 

multipass images file: 
<img width="902" alt="WechatIMG255" src="https://user-images.githubusercontent.com/42410451/197336592-c5a53c52-289b-40b8-a882-7003bf20b73e.png">

while image url is `https://cloud-images.ubuntu.com` by doc and I intercepted, but i  try to download them and  `ubuntu-20.04-server-cloudimg-amd64.img` doesn't work, other two file no problem.
 Then I found that the size of two files is inconsistent.

[ubuntu cloud images](http://cloud-images.ubuntu.com/releases/focal/release-20221018): 
<img width="1110" alt="WechatIMG256" src="https://user-images.githubusercontent.com/42410451/197336736-e793e96f-9027-41d1-8239-5f64023064c6.png">

please , why or where should I download it? 
thanks , very much , if can reply.

**Comment by ricab** [comment]
Hi @nulllpoint, I think you went to the right place. It is just that we need to post-process the image after we download it, which is why you see a different size.

I am closing this now, please reopen if you think there is still anything to follow up.

**Comment by nulllpoint** [comment]
> Hi @nulllpoint, I think you went to the right place. It is just that we need to post-process the image after we download it, which is why you see a different size.
> 
> I am closing this now, please reopen if you think there is still anything to follow up.

OK, thanks for your answer.
