### ISSUE TITLE
Mutipass

### ISSUE THREAD

**Issue by Ronniesmith3** [canonical/multipass#2788]
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**

**Comment by townsend2010** [comment]
Sorry, you have provided any details of what your problem is. I'm going to close, but please feel free to reopen with more details or open a new issue with details.  Thanks!
