### ISSUE TITLE
What is the default driver for Linux?

### ISSUE THREAD

**Issue by mkgvt** [canonical/multipass#2792]
According to [the main page](https://multipass.run/), Linux uses LXD. But according to [the driver setup page](https://multipass.run/docs/set-up-the-driver) it uses Qemu by default but can be switched to libvirt. The two pages seem to be inconsistent.

(Migrated from web site issue [#272](https://github.com/canonical/multipass.run/issues/272).)

**Comment by luis4a0** [comment]
Hi @mkgvt, thanks for reporting this. The website is not telling the complete truth, which is a bit more complex than that. The default in Linux is QEMU for x86_64 and LXD for the rest of architectures (as replied [here](https://github.com/canonical/multipass.run/issues/272#issuecomment-1290593845) . The documentation on the driver setup page was updated, although midifying the website is out of our scope.
