### ISSUE TITLE
Multipass not accessing Remote "" is unknown or unreachable

### ISSUE THREAD

**Issue by chrisaww** [canonical/multipass#2794]
**Describe the bug**
Installed multipass and on first use with launch it successfully downloaded ubuntu image and ran.
having used primary I then deleted that image and applied to lad a new primary.
The following is from my console:
multipass launch -n primary
launch failed: Remote "" is unknown or unreachable. 

multipass version
multipass   1.10.1
multipassd  1.10.1

multipass info --all
Name:           smiling-whitebait
State:          Running
IPv4:           10.3.13.247
Release:        Ubuntu 22.04.1 LTS
Image hash:     4d8d5b95082e (Ubuntu 22.04 LTS)
Load:           0.00 0.00 0.03
Disk usage:     2.0G out of 4.7G
Memory usage:   176.3M out of 969.5M
Mounts:         --

from local journal I noted the following
Checking for images to update…
Sep 19 11:49:26 chris-Inspiron multipassd[49018]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz: Network access>
Sep 19 11:49:26 chris-Inspiron multipassd[49018]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd6>
Sep 19 11:49:26 chris-Inspiron multipassd[49018]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img>
Sep 19 11:49:26 chris-Inspiron multipassd[49018]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server>
Sep 19 11:49:26 chris-Inspiron multipassd[49018]: Error updating images: Remote "" is unknown or unreachable.

I checked the first address in my browser 
and got the following
Not Found

The requested URL was not found on this server.

Please advise next step

**Comment by townsend2010** [comment]
Hi @chrisaww,

Did you happen to switch networks?  This is a problem in Qt networking that shows up from time to time.  A restart of the Multipass service will hopefully clear it up.  It's not clear which host platform you are using, so I'm unable to provide any instructions on how to do that.  Restarting the computer should help as well.

**Comment by chrisaww** [comment]
Chris Townsend suggested a restarti. Firstly I tried just stopping and restarting the snap instance of Multipass which corrected the problem :)
It does mean there is something in the code causing the problem. whilst I have not reached a repeatable position I sense it could be to do with deleting the 'primary' instance that is mounted as this was the last operation before the issue arose.
Thanks for the speedy response.
