### ISSUE TITLE
Nested virtualization on Windows with Hyper-V

### ISSUE THREAD

**Issue by vvavrychuk** [canonical/multipass#2795]
Nested virtualization is not supported on Windows under Hyper-V currently:
```
$ grep -c -w "vmx\|svm" /proc/cpuinfo
0
```

Please add support of it.

Hopefully this is doable since for WSL nested virtualization works.

**Comment by townsend2010** [comment]
Hi @vvavrychuk,

Nested virtualization is supported in Hyper-V, it's just that a user needs to enable it: https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization

Please let us know if this solves it for you.  Thanks!

**Comment by vvavrychuk** [comment]
solved works well, thank you
