### ISSUE TITLE
Testing 1.11 RC

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2800]
Backends to test the RC on:

- [x] linux:
  * [x] qemu (Scott)
  * [x] libvirt (Luis)
  * [x] lxd (Andrei)
- [x] macOS
  * [x] M1
    + [x] qemu (Luis)
  * [x] Intel
    + [x] qemu (Ricardo)
    + [x] hyperkit (Ricardo)
    + [x] virtualbox (andrei)
- [x] Windows (Luis)
  * [x] hyperv
  * [x] virtualbox

Non bug fix PR's to merge:
- ~~https://github.com/canonical/multipass/pull/2793~~

Regressions found:
- ~~https://github.com/canonical/multipass/issues/2796~~
  - https://github.com/canonical/multipass/pull/2798
- https://github.com/canonical/multipass/issues/2797
  - https://github.com/canonical/multipass/pull/2803
- https://github.com/canonical/multipass/issues/2799
  - https://github.com/canonical/multipass/pull/2804
- ~~https://github.com/canonical/multipass/issues/2801~~
  -   https://github.com/canonical/multipass/pull/2802
- https://github.com/canonical/multipass/issues/2807

**Comment by townsend2010** [comment]
As the RC is now all tested and ready for package signing, I'm closing this.
