### ISSUE TITLE
[regression] Repeated mount not refused when instance is stopped

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2807]
**To Reproduce**
How, and what happened?
1. `multipass launch -n test`
1. `multipass mount foo test:foo`
2. `multipass mount bar test:foo`
    ```
    mount failed: The following errors occurred:
    "test:foo" is already mounted
    ```
1. `multipass stop test`
2. `multipass mount --type native bar test:foo`
(no error)

**Expected behavior**
Multipass would refuse the repeated mount.

**Additional info**
 - OS: macOS 10.16
- `multipass version`: 1.11 RC
- `multipass get local.driver`: `qemu`

**Comment by ricab** [comment]
Actually, simpler:

```
$ multipass launch -n test
$ multipass stop test
$ multipass mount a test:foo
$ multipass mount b test:foo
$ echo $?
0
```

**Comment by townsend2010** [comment]
Does this also occur in 1.10.1?

**Comment by ricab** [comment]
Nope, I just tried it and Multipass correctly rejected the mount in 1.10. So regression.
