### ISSUE TITLE
`info` Disk Usage breaks when shell = fish

### ISSUE THREAD

**Issue by theothermatt** [canonical/multipass#2819]
**Describe the bug**
When using fish as the shell for the default ubuntu user, the command `multipass info` doesn't show the disk usage:

```
multipass info fish-test
Name:           fish-test
State:          Running
IPv4:           192.168.64.28
Release:        Ubuntu 22.04.1 LTS
Image hash:     c363ebe92173 (Ubuntu 22.04 LTS)
Load:           0.31 0.08 0.03
Disk usage:     --
Memory usage:   151.8M out of 961.9M
Mounts:         --
```

**To Reproduce**
How, and what happened?
1. Launch a new multipass instance with this cloud init file:
    ```
    #cloud-config

    packages:
      - fish

    system_info:
      default_user:
        shell: /usr/bin/fish
    ```
1. Run `multipass info` on the newly created VM.

Running `multipass info -v` gives me the following error:

```
[warning] [utils] no output after running 'df --output=used `awk '$2 == "/" { print $1 }' /proc/mounts` -B1 | sed 1d'
```
I'm guessing this is due to the backticks?

**Expected behavior**
Expected the `info` command to include the disk usage of the VM.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: macOS 12.6.1
- `multipass version`: 1.10.1+mac
- `multipass info --all`
- `multipass get local.driver`: qemu

**Additional context**

**Comment by luis4a0** [comment]
Hi @theothermatt, thanks for reporting. Yes, the reason it fails is that the backticks are not recognized by fish. The backticks should be replaced by parentheses in fish.

However, Multipass supports bash as a shell, for Ubuntu uses bash by default.

**Comment by luis4a0** [comment]
Hey @theothermatt, thinking again about this and discussing with other project members, we see that replacing backticks with `$()` would do the job. I am reopening this ticket and leaving it open until someone wants to implement this solution which would work with all POSIX-compliant shells.

Thanks!

**Comment by sharder996** [comment]
Hey @theothermatt, we have a PR in flight that will make multipass' internal shell commands POSIX-compliant which will hopefully support a larger number of shells.

However, we can't effectively support fish in this case as the version of fish that comes with a `Ubuntu 22.04` release does not support POSIX-compliant strings. You would have to use a `22.10` release to get a version of fish that supports this.
