### ISSUE TITLE
Update ip for running instance 

### ISSUE THREAD

**Issue by Tatskaari** [canonical/multipass#2834]
**What are you trying to do?**
I have updated the IP address of an instance to be statically assigned however multipass is still looking for the server at the old IP address. This means things like `multipass shell` aren't working. 

**What's your proposed solution?**
Have an option to update the ip address that multipass has for an instance. This should update the DNS record too, so `*.multipass` domains are still accessible. 

**Additional context**
I can work around this for now by sshing directly with `sudo ssh -i /var/snap/multipass/common/data/multipassd/ssh-keys/id_rsa <ip address>` but this is a bit too grungy.

**Comment by ricab** [comment]
Hi @Tatskaari, Multipass needs that old IP to stay untouched. If you want to add a static IP to your instance, you can do so by [adding another network interface](https://multipass.run/docs/create-an-instance#heading--create-an-instance-with-multiple-network-interfaces) when you launch, with `multipass launch --network ...`.

**Comment by Tatskaari** [comment]
> Hi @Tatskaari, Multipass needs that old IP to stay untouched. If you want to add a static IP to your instance, you can do so by [adding another network interface](https://multipass.run/docs/create-an-instance#heading--create-an-instance-with-multiple-network-interfaces) when you launch, with `multipass launch --network ...`.

Fair enough, but not on the qemu backend. I ended up just bridging the network and statically assigning the old IP but that sucks. I guess you guys are trying to be like a cloud provider which makes sense, except not all features work on all backends. If I was on the LXC backend I would have similar controls to gcp like you say.

**Comment by ricab** [comment]
Hi @Tatskaari, you're right, you'd need to move to the LXD backend for that. We mostly try to stay away from backend-specific features, but on some cases we need to prioritize other work. In this case, we found that the cost of implementing on all backends was better spent on other work. Hopefully it is something we can improve on at some point.
