### ISSUE TITLE
Why command 'multipass ls' so slow？

### ISSUE THREAD

**Issue by luanshaotong** [canonical/multipass#2837]
**Describe the bug**
![image](https://user-images.githubusercontent.com/14962503/203927578-6e4c8c84-ebd3-4c93-9eea-698cff53ef44.png)

**To Reproduce**
How, and what happened?
1. `sudo multipass ls`

**Expected behavior**
Return faster

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

I found the following problems in `sudo multipass ls -vvvv`

![image](https://user-images.githubusercontent.com/14962503/203929703-8d7588a5-4eb1-4ef7-9a13-8cbe69697732.png)
![image](https://user-images.githubusercontent.com/14962503/203929619-cf844165-ccd7-4039-905e-f40ccee790c6.png)

**Additional info**
 - OS: ubuntu 18.04
- `multipass version`
  - 1.10.1
- `multipass info --all`
![image](https://user-images.githubusercontent.com/14962503/203928229-5de6f138-3857-413a-88ea-2fc0871d3eb4.png)

- `multipass get local.driver`
lxd

**Additional context**

**Comment by andrei-toterman** [comment]
Hi, @luanshaotong! When listing running instances, we have to ssh into each one of them in order to get their IPs, and since you have a lot of running instances, it's not surprising it takes a while.
