### ISSUE TITLE
Non-Ubuntu images can't be launched

### ISSUE THREAD

**Issue by wyan** [canonical/multipass#2838]
**Describe the bug**
Non-Ubuntu images can't be launched

**To Reproduce**
`multipass launch https://url.to.image`

**Expected behavior**
Image is downloaded and a new VM is launched

**Logs**
Logs mention
```
[2022-11-25T22:31:56.362] [debug] [qemu-system-aarch64] [59759] started: qemu-system-aarch64 --version
```
before multipass returning:
```
launch failed: http and file based images are not supported
```
No other messages logged.

**Additional info**
 - OS: macOS 13.0.1
 - multipass   1.10.1+mac
 - multipassd  1.10.1+mac
 - local driver: qemu

**Additional context**
Previous bug reports #1029 #1593 have been closed without fix or explanation

**Comment by ricab** [comment]
Hi @wyan, Multipass is for launching Ubuntu VMs only, and http/file launching is currently only supported on Linux,
