### ISSUE TITLE
Does an sdk exist for other languages to call directly?

### ISSUE THREAD

**Issue by 239573049** [canonical/multipass#2842]
**What are you trying to do?**
Does an sdk exist for other languages to call directly?

The Docker-like sdk provides an api that I can use to manipulate multipass through other languages

**Comment by sharder996** [comment]
Hi @239573049,

Unfortunately Multipass does not provide a publicly documented API that can be used to interact with its daemon. However, if you are willing to get your hands a bit dirty and go spelunking through the code base, it is possible to find and create the correct gRPC calls used to communicate with the Multipass backend. [Here](https://pastebin.canonical.com/p/YWhDN6tHJk/) is an example of a Python script that another user has posted in a separate issue doing just this.
