### ISSUE TITLE
I want to know how multipass can change the storage directory where the instance is created

### ISSUE THREAD

**Issue by 239573049** [canonical/multipass#2843]
**What are you trying to do?**
I want to know how multipass can change the storage directory where the instance is created

**Comment by sharder996** [comment]
Hi @239573049, 

Official documentation is currently being written for this feature and should be showing up in the  [Multipass docs](https://multipass.run/docs) soon. In the meantime, you can reference [this thread](https://github.com/canonical/multipass/pull/1789#issuecomment-704991752) and execute the commands specified for your host OS.

**Comment by 239573049** [comment]
> Hi @239573049,
> 
> Official documentation is currently being written for this feature and should be showing up in the [Multipass docs](https://multipass.run/docs) soon. In the meantime, you can reference [this thread](https://github.com/canonical/multipass/pull/1789#issuecomment-704991752) and execute the commands specified for your host OS.

I want to know the details of the progress?

**Comment by sharder996** [comment]
I wanna say the docs should be up by the end of this week.

**Comment by 239573049** [comment]
> I wanna say the docs should be up by the end of this week.

Thank you. That's good

**Comment by sharder996** [comment]
Hi @239573049, the document page is up [here](https://multipass.run/docs/configure-multipass-storage)! If you're on Linux and using the snap, there is an upcoming bug fix that will be included in v1.11.0.

**Comment by 239573049** [comment]
> Hi @239573049, the document page is up [here](https://multipass.run/docs/configure-multipass-storage)! If you're on Linux and using the snap, there is an upcoming bug fix that will be included in v1.11.0.

thank you

**Comment by eparisis** [comment]
Hi there, possibly a very stupid question but I cant figure it out.

I'm trying to change the location on MacOS but there is no `/Library/LaunchDaemons/com.canonical.multipass.plist` and `/Library/LaunchDaemons/setenv.MULTIPASS_STORAGE.plist` to modify in my `/Library/LaunchDaemons/` folder, so the command in the docs don't work. There is only a `com.canonical.multipassd.plist` file.  

I installed multipass through the .pkg installation and runs fine. Is there another way for MacOS now?

**Comment by ricab** [comment]
> I'm trying to change the location on MacOS but there is no `/Library/LaunchDaemons/com.canonical.multipass.plist`

Hi @eparisis, I believe that's a typo. It should say `com.canonical.multipassd.plist`.

>  and /Library/LaunchDaemons/setenv.MULTIPASS_STORAGE.plist

Correct, that one is created by the command in the instructions.

**Comment by melutovich** [comment]
@sharder996 Please note the linked page in the documentation only mentions linux and not windows nor macos
