### ISSUE TITLE
Stale hosts listings in hosts.ics

### ISSUE THREAD

**Issue by saxomoose** [canonical/multipass#2861]
**Describe the bug**
I see stale listings being re-added to `hosts.ics`. The documentation recommends deleting them manually, but to no avail. The stale entries are being re-inserted when a multipass command is executed.

This bug was mentioned in #1321 but this is not yet remedied in version  `1.10.1+win`.

The windows specific code bits not being available, it is impossible to diagnose the cause of the issue.

**To Reproduce**
How, and what happened?
1. `multipass launch --name orchestrator`
2. `multipass delete orchestrator --purge`
3. Check `C:\Windows\System32\drivers\etc\hosts.ics` file and find the entry of the deleted vm.

**Expected behavior**
No entry for the deleted vm in `C:\Windows\System32\drivers\etc\hosts.ics`.

**Additional info**
 - OS: Windows 11 - 10.0.22621 Build 22621
- `multipass version`: 1.10.1+win
- `multipass get local.driver`: hyperv

**Comment by ricab** [comment]
Hi @saxomoose, Multipass does not touch that file at all, it is managed by Microsoft's Internet Connection Sharing and Hyper-V apparently corrupts it from time to time. Here is [someone with the same issue](https://learn.microsoft.com/en-us/answers/questions/632301/hyper-v-default-switch-corrupts-hostsics-and-dns-s.html).
