### ISSUE TITLE
Multipass version 1.10.1+win doesn't have the --recursive option when doing multipass transfer

### ISSUE THREAD

**Issue by jqi2844** [canonical/multipass#2863]
For some reason, this version of multipass doesn't have the recursive option built in, even though it's already been fixed by previous revisions.

`:\Users\jqi>multipass transfer --r
Unknown option 'r'.

C:\Users\jqi>multipass version
multipass   1.10.1+win
multipassd  1.10.1+win`

**Comment by andrei-toterman** [comment]
Hi, @jqi2844! The `-r` flag will come to the `transfer` command only in version 1.11. Do you have a source for it being included in an earlier version? Maybe we've misdocumented it somewhere.

**Comment by jqi2844** [comment]
oh, I just reread the docs, and it says _[since version 1.11.0]_ which hasn't been released yet.
A bit misleading, but otherwise seems fine.
I've been trying to use regular cp to move some files around, but haven't had any luck doing so.

**Comment by andrei-toterman** [comment]
Yeah, I understand the confusion. In the meantime, you can try to use the `scp` tool, which should come preinstalled with recent versions of Windows. It requires a bit of setup though.

First, find your instance's IP address:
```
C:\Users\andrei>multipass ls
Name                    State             IPv4             Image
primary                 Running           172.28.156.176   Ubuntu 22.04 LTS
```
Then, if you don't have an SSH key, generate one (you can stick with the defaults, just press Enter):
```
C:\Users\andrei>ssh-keygen
```
Now, copy your public key into the instance:
```
C:\Users\andrei>multipass transfer .ssh\id_rsa.pub primary:
C:\Users\andrei>multipass exec primary -- sh -c "cat id_rsa.pub >> .ssh/authorized_keys"
```
Now you should be able to SSH into the instance using your own key, so you can also use `scp` with the instance's IP:
```
C:\Users\andrei>scp -r <local_source> 172.28.156.176:<remote_target>
C:\Users\andrei>scp -r 172.28.156.176:<remote_source> <local_target> 
```

I hope this helps! I'm gonna close this issue now, but feel free to ask if you have any other questions.
