### ISSUE TITLE
No IPv4 address, multipass launch timeout

### ISSUE THREAD

**Issue by apiszcz** [canonical/multipass#2866]
multipass 1.10.1
Windows 10
Hyper-V manager shows instance was creating, can connect to Ubuntu login prompt, (don't know username/password).

Verified the host.ics file has no stray characters.
multipass list shows N/A for IPv4

multipass launch
launch failed: The following errors occurred:
amicable-chihuahua: timed out waiting for response

Reviewed other posts, reinstalled/restarted a few times. 

Is there a recent approach to diagnose this issue?

**Comment by ricab** [comment]
Hi @apiszcz, have you looked in our [troubleshooting](https://multipass.run/docs/troubleshoot-networking#heading--troubleshoot-networking-on-windows) guide?

**Comment by apiszcz** [comment]
Will do, DNS issues likely, thank you.
________________________________
