### ISSUE TITLE
How to mount NFS folder in Linux instance when I have shared folder on macOS?

### ISSUE THREAD

**Issue by jamesli2021** [canonical/multipass#2872]
When replying, I get Server error 500, and frustrating to get NFS working for the last few day, so I need your urgent help.
https://discourse.ubuntu.com/t/how-to-improve-mounts-performance-in-multipass/26638/3

I have macOS host and Ubuntu instance, I don't understand this line and I couldn't get it working in Linux, what is the real example I should type? Google on the web is messy and I wonder why even Multipass documentation is not helpful too.

Probably, would be nice to know if this are a dummy example that should be replace according to my actual info?

- HOST_IP
- /my_path
- /omunt_folder
- host_user
- instance_uid
- instance_gid

How do I fill it if my macOS IP is 192.168.1.7?

```
sudo mount -t nfs HOST_IP:/my_path /mount_folder -o user=host_user,uid=instance_uid,gid=instance_gid
```

**Comment by luis4a0** [comment]
Hi @jamesli2021, thanks for asking. We maybe need to update the information in the documentation.

The MacOS IP is in fact the `HOST_IP`. The MacOS command `id`  will give you your UID and GID (which are `instance_uid` and `instance_gid`. `host_user` is the name of your user in MacOS (obtained if you need with the command `whoami` in MacOS). `/my_path` is the path you shared in MacOS and want to mount in the instance. `/mount_folder` is the path to the folder in the instance.

Does this solve your issue?

**Comment by jamesli2021** [comment]
In the parameter I've added into `/etc/exports`
```
/Users/s/macos_folder -mapall=s -network 192.168.64.7 -mask=255.255.0.
```

On macOS, I could see the mounted NFS:
```
Exports list on localhost:
/Users/s/macos_folder                              192.168.64.7
```

The info are based on my query on macOS
- `HOST_IP` -> 192.168.64.7 (on macOS and even tried 192.168.1.7 from ifconfig)
- `/my_path` -> /Users/s/macos_folder
- `/omunt_folder` -> /ubuntu_folder
- `host_user` -> s (macOS account login name)
- `instance_uid` -> 1000 (Based on `id -u`)
- `instance_gid` -> 1000 (Based on `id -g`)

When attempt to mount in Ubuntu instance:
``
ubuntu@primary:~$ sudo mount -t nfs 192.168.64.7:/Users/s/macos_folder /ubuntu_folder -o user=s,uid=1000,gid=1000
mount.nfs: an incorrect mount option was specified
```

Could not understand the generic error message.

**Comment by jamesli2021** [comment]
On macOS Venturem, when I removed `gid` and `uid`, set `nfsvers=3`, I could see new error message.
```
ubuntu@primary:~$ sudo mount -t nfs 192.168.1.7:/Users/s/macos_folder /ubuntu_folder -o nfsvers=3,user=s
mount.nfs: access denied by server while mounting 192.168.1.7:/Users/s/macos_folder
```

**Comment by jamesli2021** [comment]
Problem solved, thanks!

**Comment by luis4a0** [comment]
Hey @jamesli2021, great news! I am curious now, I was just trying to reproduce your issue. Can you please share what was the solution to your problem. Thanks!

**Comment by jamesli2021** [comment]
In macOS `/etc/export` I learnt that `192.168.0.0` is the correct IP that will be used by client on any IP in 192.168.x.x, I was assume that we need to change to the correct IP address.

In Linux, removed `gid` and `uid` works.
```
ubuntu@primary:~$ sudo mount -t nfs 192.168.1.7:/Users/s/macos_folder /ubuntu_folder -o user=s
```

Some development tool .g. (https://vitejs.dev/) is unable to detect when files are modified on host's shared folder, I did `lookupcache=none` and other approach to disable attributes didn't solve it. Similar problem with SSHFS.
```
ubuntu@primary:~$ sudo mount -t nfs 192.168.1.7:/Users/s/macos_folder /ubuntu_folder -o user=s,lookupcache=none
```

If I could make Vite works perfectly with SSHFS on host, I can save the hassle of setting up NFS.
