### ISSUE TITLE
MacOS rebooting VM causes VM to go into an unknown state

### ISSUE THREAD

**Issue by twovican** [canonical/multipass#2873]
**Describe the bug**
Rebooting a VM on macOS from inside the VM causes the VM to go into an unknown state.  This is making it difficult to prototype projects and use multipass effectively.

**To Reproduce**
Launch an LTS instance

`$ multipass launch lts`

Shell into the instance when created

`$ multipass shell sharp-billfish`

> Enter the VM and run a reboot

`ubuntu@sharp-billfish:~$ sudo shutdown -r now`

> Exit the VM

You can see that the instance is in a starting state:

```
$ multipass ls
Name                    State             IPv4             Image
sharp-billfish          Starting          --               Ubuntu 22.04 LTS
```

```
$ multipass shell sharp-billfish
Starting sharp-billfish -
```

Eventually, the shell command will timeout

```
$ multipass shell sharp-billfish
start failed: The following errors occurred:
sharp-billfish: timed out waiting for response
```

Then the state becomes unknown,

```
$ multipass ls                                                                                                     
Name                    State             IPv4             Image
sharp-billfish          Unknown           --               Ubuntu 22.04 LTS
```

**Expected behavior**
VM to restart in a known good state.

**Logs**
Please provide logs from the daemon; see [accessing logs](https://multipass.run/docs/accessing-logs) for where to find them on your platform.

**Additional info**
 - OS: MacOS 13.1
 
```
$ multipass version
multipass   1.10.1+mac
multipassd  1.10.1+mac
```

```
$ multipass info --all
Name:           sharp-billfish
State:          Unknown
IPv4:           --
Release:        --
Image hash:     3100a27357a0 (Ubuntu 22.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

```
$ multipass get local.driver
hyperkit
```

Let me know if there is additional information required or changes to the driver to make this work

**Comment by ricab** [comment]
Hey @twovican, sorry about that, looks like a bug in our `hyperkit` backend. Development on Hyperkit has stalled and so our backend will also soon be deprecated, which means we're not devoting a lot of attention to it anymore (apart from the ongoing work to migrate to the `qemu` backend).

Here are a few things you could try today:

1. Ask Multipass to restart the VM: `multipass restart sharp-billfish`. Does this work for you, or do you get the same thing?
    1. otherwise, what about `multipass stop sharp-billfish && multipass start sharp-billfish`
1. You can also try one of the other backends on macOS: `qemu` and `virtualbox` (e.g. `multipass set local.driver=qemu`).

I hope one of these options works for you.

**Comment by twovican** [comment]
@ricab I have tried option one and have had no luck.  Changing the driver to qemu works successfully.  

Should we update the documentation on at least https://multipass.run/ to remove hyperkit and provide instructions on setting qemu or VirtualBox as the default?

**Comment by twovican** [comment]
@ricab sounds good around documentation.  the starting would hang and be thrown into an unknown state.  Switching to qemu is perfect for me and preferred.

I will close this ticket out, as it will be addressed in future releases.

Thanks for the support!
