### ISSUE TITLE
[regression] multipass transfer on windows - colon in the local/destination path now throws error

### ISSUE THREAD

**Issue by jasonumiker-sysdig** [canonical/multipass#2891]
On Windows, local paths by definition have to include a colon after the drive letter. And when you use that, even via $HOME, or ~ in git bash, it now throws the error "Cannot specify an instance name for both source and destination". It only started doing this with the latest version 1.11.0.

I have a number of scripts that worked before and now throw the above error and so I have reverted to 1.10.1 to keep things working for now.

**Comment by ricab** [comment]
Hey @jasonumiker-sysdig, thanks for the reply. We have a [tentative fix](https://multipass-ci.s3.amazonaws.com/pr2893/multipass-1.12.0-dev.132.pr2893%2Bg67bfc6b4.win-win64.exe). If you were able to try that package and confirm it worked for you, we'd appreciate it. Thanks!

**Comment by xnlcasad** [comment]
Just confirming the same issue here.

**Comment by jasonumiker-sysdig** [comment]
Hi @ricab - that fixed it for me. Thanks!

**Comment by ricab** [comment]
Great, thanks @jasonumiker-sysdig! We'll have a proper patch release fixing this and a couple other things soon.
