### ISSUE TITLE
VM is too small

### ISSUE THREAD

**Issue by popey** [canonical/multipass#29]
Within a few minutes of sparking up a default 16.04 VM I'd run out of space. I think 2GB is a little too small to be actually useful. Perhaps 5G should be a default?

**Comment by Saviq** [comment]
Yeah, the default size from cloud-images is a bit small, and since they're `qcow2` images we can default bigger and that doesn't steal your storage straight away (only as you use it).

**Comment by BearzRobotics** [comment]
What if you expose qemu-img in multipass as an expand option to resize the disk. Right now what I did was sudo qemu-img resize /var/snap/multipass/common/data/multipassd/vault/instances/devOps/ubuntu-16.04-server-cloudimg-amd64-disk1.img +10G   

This will add 10 Gbs to the image. Also this was using a local install of qemu on solus.

**Comment by townsend2010** [comment]
@Saviq, what should we make the default virtual disk size be during launch?

**Comment by Saviq** [comment]
Yeah let's just default to `5GB` for now and we'll make it configurable.

**Comment by mritd** [comment]
Is there any progress?

**Comment by Saviq** [comment]
@mritd we've designed what the experience will be like in #756 - we've not gotten around to implementing that just yet.

You can use `qemu-img` or the native hypervisor-specific tools to resize the images when the instance is stopped, and cloud-init should resize the root partition on the next boot.

**Comment by mritd** [comment]
@Saviq Ok,thanks for your answer.

**Comment by haikarainen** [comment]
Just nuke this whole repository alltogether. Multipass is the dumbest waste of time I've ever experienced in my life.

Jesus christ people.

**Comment by angrybrad** [comment]
@haikarainen you seem nice.

**Comment by haikarainen** [comment]
@angrybrad  Thank you, I try.

**Comment by kennethxu** [comment]
For windows host, use Resize-VHD utility in PowerShell: https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=win10-ps

**Comment by michaelgthomas** [comment]
> For windows host, use Resize-VHD utility in PowerShell: https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=win10-ps
> 
> Disk image location: C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\

Thanks for this.

**Comment by winkeesail** [comment]
can I resize VM after the instance has been created? I run into a situation that my VM is using up the initial space.

**Comment by steve-gale** [comment]
> can I resize VM after the instance has been created? I run into a situation that my VM is using up the initial space.

as @Saviq said, you can use `qemu-img` to do this.
Here is an example of what I did on a macOS 11.1 host:
first make sure the multipass VM is shut down, then open a local terminal
`brew install qemu` install the qemu CLI tools
`sudo su -` become root
`cd '/var/root/Library/Application Support/multipassd/vault/instances/primary'` move into directory where the virtual disk files are stored
`qemu-img resize ubuntu-20.04-server-cloudimg-amd64.img +10G` (I only needed 10 more gigs, but you can use however much you want)
Then start up the multipass VM. A `df -h` will show you that the root filesystem has auto-expanded to consume the newly allocated space.

**Comment by jeanbispo** [comment]
> For windows host, use Resize-VHD utility in PowerShell: https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=win10-ps
> 
> Disk image location: C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\

Tks, work for me.

**Comment by Cordelya** [comment]
> For windows host, use Resize-VHD utility in PowerShell: https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=win10-ps
> 
> Disk image location: C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\

Reporting in that this workaround worked for me on Windows 10 Pro, where editing the disk in Hyper-V Manager did not - because snapshots were enabled for my VM and therefore Hyper-V Manager refuses to allow disk size editing via the gui.

**Comment by kasir-barati** [comment]
# How to increase the image size in ubuntu:

1. ` sudo apt-get install qemu-utils`
2. find the location of your multipass by `find . -type d -name multipassd`. for me it was in: `/var/snap/multipass/common/data/multipassd/vault/instances`.
3. `cd /var/snap/multipass/common/data/multipassd/vault/instances/instance-name`
4. stop the vs by `multipass stop instance-name`
5. resize the image by `sudo qemu-img resize ubuntu-20.04-server-cloudimg-amd64.img +20G`
6. start the instance again by `multipass start instance-name`

**Comment by gaborcsardi** [comment]
For the record, the images are here for me on macOS aarch64:
```
/System/Volumes/Data/private/var/root/Library/Application Support/multipassd/qemu/vault/instances
```
also linked here:
```
/private/var/root/Library/Application Support/multipassd/qemu/vault/instances
```

**Comment by daviewales** [comment]
> For windows host, use Resize-VHD utility in PowerShell: https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=win10-ps
> 
> Disk image location: C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\

Note: This path appears to have changed to:

```
C:\ProgramData\Multipass\data\vault\instances
```

**Comment by rehypothecation** [comment]
> > can I resize VM after the instance has been created? I run into a situation that my VM is using up the initial space.
> 
> as @Saviq said, you can use `qemu-img` to do this. Here is an example of what I did on a macOS 11.1 host: first make sure the multipass VM is shut down, then open a local terminal `brew install qemu` install the qemu CLI tools `sudo su -` become root `cd '/var/root/Library/Application Support/multipassd/vault/instances/primary'` move into directory where the virtual disk files are stored `qemu-img resize ubuntu-20.04-server-cloudimg-amd64.img +10G` (I only needed 10 more gigs, but you can use however much you want) Then start up the multipass VM. A `df -h` will show you that the root filesystem has auto-expanded to consume the newly allocated space.

I am getting this error:

`-sh: qemu-img: command not found`

However, `qemu-img` works when not elevated. Any ideas?

**Comment by gaborcsardi** [comment]
@rehypothecation check your `PATH`.

**Comment by rehypothecation** [comment]
> @rehypothecation check your `PATH`.

Thanks! I had to add `/opt/homebrew/bin`to my `PATH`.

**Comment by wangwenqiangGitHub** [comment]
> > can I resize VM after the instance has been created? I run into a situation that my VM is using up the initial space.
> 
> as @Saviq said, you can use `qemu-img` to do this. Here is an example of what I did on a macOS 11.1 host: first make sure the multipass VM is shut down, then open a local terminal `brew install qemu` install the qemu CLI tools `sudo su -` become root `cd '/var/root/Library/Application Support/multipassd/vault/instances/primary'` move into directory where the virtual disk files are stored `qemu-img resize ubuntu-20.04-server-cloudimg-amd64.img +10G` (I only needed 10 more gigs, but you can use however much you want) Then start up the multipass VM. A `df -h` will show you that the root filesystem has auto-expanded to consume the newly allocated space.

```
localhost:ubuntu2204 root# qemu-img resize ubuntu-22.04-server-cloudimg-arm64.img +10G
qemu-img: Can't resize a v2 image which has snapshots

```
How Can I delte snapshots

**Comment by Saviq** [comment]
@wangwenqiangGitHub you need to _stop_ the instance rather than suspending it.

**Comment by wangwenqiangGitHub** [comment]
> @wangwenqiangGitHub you need to _stop_ the instance rather than suspending it.

<img width="926" alt="截屏2022-09-05 19 38 40" src="https://user-images.githubusercontent.com/28779327/188440452-44aa36d4-9b7b-4f58-a87d-28f787f9b3ab.png">

**Comment by Quan-DeFi** [comment]
any update on a simple way to resize the instance via multipass?

**Comment by ricab** [comment]
Hi @Quan-DeFi, this has been implemented for a while now :slightly_smiling_face: 

https://multipass.run/docs/modify-an-instance#heading--set-the-cpu-ram-or-disk-of-an-instance
