### ISSUE TITLE
Launching via icon spawns new tray processes

### ISSUE THREAD

**Issue by nathan-j-hart** [canonical/multipass#2900]
**Describe the bug**
If I pin Multipass to the dock, any time I click on it, it creates a new tray icon and process. The same thing happens when launching the app from the app launcher more than once.

**To Reproduce**
How, and what happened?
1. Click Multipass icon in application launcher (e.g. press super key + search multipass)
2. Do it again, or click "open shell", pin dock icon that appears, then click the dock icon.

**Expected behavior**
Only open one tray icon at most. If one is already open, do nothing.

**Additional info**
 - OS:Ubuntu 22.04
- `multipass version` 
multipass   1.12.0-dev.96.pr2899+g5e6f277a
multipassd  1.12.0-dev.96.pr2899+g5e6f277a

**Additional context**
![image](https://user-images.githubusercontent.com/77587653/214312610-75ff65a0-8311-4960-b1ff-64cb8905bdc4.png)

**Comment by andrei-toterman** [comment]
Hey, @nathan-j-hart! Yup, unfortunately the tray icon app is not aware that other like it are running. Luckily, there should be an easy fix for it. Thanks for pointing that out!
