### ISSUE TITLE
[windows] Permission denied when native-mounting folders owned by "NT AUTHORITY\SYSTEM"

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2902]
**Describe the bug**
Multipass can't create native mounts for folders owned by "NT AUTHORITY\SYSTEM". These include the "home folder" on Windows (C:\Users\<username>).

```
PS C:\Users\ricab> multipass mount --type native . test:Home
Please enter your user password to allow Windows mounts:
mount failed: The following errors occurred:
error mounting "Home": Error: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

**To Reproduce**
1. `multipass mount --type native "C:\Users\<username>" test:Home`

**Expected behavior**
What did you expect to happen?

 - OS: Windows
- `multipass version`: `1.12.0-dev.131.pr498+g7fb15eaf.win` (after fix for #2901)
- `multipass get local.driver`: `hyperv`

**Additional Info**
I tried with `psexec -s`, but it then seems unable to request a user password. If I add `-i`, a console pops up requesting the password, but still fails, the console closing too quickly to read any message that may have appeared. I did not pursue any further.

**Comment by ricab** [comment]
Actually, I just tried with a "super-privileged" shell: run admin shell, `psexec -s -i powershell` inside, find the multipass executable in the shell that opens up (not in PATH) and run it. I get the same permission denied...

**Comment by gianluca-sabena** [comment]
I still have this problem on windows with hyperv

```
multipass --version
multipass   1.12.0+win
multipassd  1.12.0+win

```
Dmesg error

```
[53645.968491] CIFS: Attempting to mount \\*********\a9e23237-bfce-4d40-868d-0569e60290d4_hyperv-ubuntu:
[53645.995204] CIFS: Status code returned 0xc000006d STATUS_LOGON_FAILURE
[53645.995211] CIFS: VFS: \\********* Send error in SessSetup = -13
[53645.995306] CIFS: VFS: cifs_mount failed w/return code = -13
```
