### ISSUE TITLE
`delete` should force-stop running instances when a regular `stop` isn't enough

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2906]
**Describe the bug**
If multipass can't stop an instance normally, it will keep running even after deleted.

**To Reproduce**
1. `multipass shell`
2. inside the instance:
    1. `sudo fsfreeze --freeze /`
    2. `sudo ip link set ens3 down`
3. back outside, `multipass stop`
4. observe the instance still running after the command exits (which, by the way...)
5. `multipass delete primary`
6. `pgrep -fa qemu` and observe the process still running
7. `multipass recover primary`
8. `multipass list` observe primary still running

**Expected behavior**
Delete would kill the instance if regular stopping did not work.

**Additional info**
 - OS: Linux
- `multipass version` 1.12.0-dev.123+gdc4cbef6
- `multipass get local.driver` QEMU

**Additional context**
This should be fixable by force-stopping after #1909 is in.

**Comment by sharder996** [comment]
This is also closely related to #2492 and may be addressed by #1946. That PR might need some work to make sure its inline with what we want, but it should be a good starting point.

**Comment by ricab** [comment]
This should be taken care of now.
