### ISSUE TITLE
[macOS] Inconsistent mounting when using `mount --type native` on restart

### ISSUE THREAD

**Issue by magnetikonline** [canonical/multipass#2917]
**Describe the bug**

Hello team. Really love the new `mount --type native` option that landed in `1.11.0` - nice to not have SSHFS along for the ride. But I've found a little bug/quirk - that I can now reproduce.

I noted that after modifying an existing instance to re-mount using `mount --type native` - I noted that on restart of the instance - the native mount would fail sometimes.

Turns out I've been able to isolate it to when the instance is either shutdown/restart within the instance itself - rather than using `multipass stop` / `multipass restart`.

**To Reproduce**

1. `multipass start INSTANCE_NAME`
2. `multipass shell INSTANCE_NAME`
3. Confirm mount point exists
4. `sudo shutdown now -P`
5. `multipass start INSTANCE_NAME`
6. `multipass shell INSTANCE_NAME`
7. Mount will no longer exist....
8. Now `multipass stop INSTANCE_NAME`
9. `multipass start INSTANCE_NAME`
10. `multipass shell INSTANCE_NAME`
11. Mount is now back 🎉 

Can also use `multipass restart` as well to "fix" an image broken via `shutdown / reboot` operations from within the instance itself.

Sorry, hope that's clear!

**Expected behavior**

The native mount continues to work on restart of instance.

**Additional info**

- OS: macOS `12.6.3`
- `multipass version`: `multipass   1.11.1+mac`
- `multipass info --all`

```
Name:           magnetik-docker
State:          Running
IPv4:           192.168.65.2
                192.168.0.61
                172.19.0.1
                172.18.0.1
                172.21.0.1
                172.17.0.1
                172.23.0.1
                172.20.0.1
                172.22.0.1
                172.24.0.1
Release:        Ubuntu 20.04.5 LTS
Image hash:     0f1a20bcda28 (Ubuntu 20.04 LTS)
CPU(s):         1
Load:           0.27 0.08 0.03
Disk usage:     8.1GiB out of 9.5GiB
Memory usage:   182.6MiB out of 970.2MiB
Mounts:         /Users/magnetik => /Users/magnetik
                    UID map: 501:default
                    GID map: 20:default
```

**Comment by townsend2010** [comment]
Hi @magnetikonline!

Thanks for reporting this bug!  We'll be working on a fix and should be in 1.12 release.

**Comment by magnetikonline** [comment]
Not a problem @townsend2010 👍 

Yeah I really like the new native mounts - was just annoying it seemed to randomly fail. I gave it another look - and at least now I can reliably reproduce and fix the issue.

I hope the steps to reproduce are clear - to put it another way (if that helps).

I can "break" native mounts by logging into an instance (guest) and run either of the following commands:

```sh
sudo reboot
# or...
sudo shutdown now -P
```

but at the same time,  I can easily "fix" a broken instance from the (host) via:

```sh
multipass stop INSTANCE_NAME && multipass start INSTANCE_NAME
# or...
multipass restart INSTANCE_NAME
```

Thanks again Chris 👍

**Comment by townsend2010** [comment]
Hey @magnetikonline!

We are able to reproduce and are currently working on a fix.  Thanks for good bug report :+1:

**Comment by magnetikonline** [comment]
> We are able to reproduce and are currently working on a fix. Thanks for good bug report

Ah fantastic @townsend2010 - always nice to know its not a case of "works on my machine" 😄.

**Comment by magnetikonline** [comment]
Awesome - thanks @townsend2010 & @andrei-toterman for turning this one around so quick!

**Comment by magnetikonline** [comment]
Hey @townsend2010 / @andrei-toterman - just to circle back.

Istalled https://github.com/canonical/multipass/releases/tag/v1.12.0 the other day - can confirm `sudo reboot/shutdown` issued from a Ubuntu Multipass VM, multiple times - `--type native` mounts survive the restart perfectly every time. 👍
