### ISSUE TITLE
[cli/info] `multipass info --all` does not list deleted instances

### ISSUE THREAD

**Issue by andrei-toterman** [canonical/multipass#2936]
**Describe the bug**
Listing information about all instances does not include deleted instances. `multipass info` works on a deleted instance, `multipass ls` includes deleted instances, so `multipass info --all` should include the deleted instances info as well.

**To Reproduce**
1. `multipass launch -n test`
1. `multipass delete test`
1. `multipass info test` shows info about deleted instance
1. `multipass info --all` does not show info about the deleted instance

**Expected behavior**
Show info about all instances on `multipass info --all`

**Additional info**
- OS: any
- `multipass version` 1.11.1
- `multipass get local.driver` any

**Comment by Aryansingh0103** [comment]
I would like to work on this can you please assign me this work @andrei-toterman

**Comment by Aryansingh0103** [comment]
Sir can you help me by suggesting where this file is as I am searching for it, I just want to know where the file is

**Comment by andrei-toterman** [comment]
Sure! You should look inside `src/daemon/daemon.cpp`.

**Comment by georgeliao** [comment]
Since **multipass info --all** does show the state of the instance, it makes sense to show the deleted instances as well. Apart from that, the fact that you manually run it and find it out this behavior does not seem to be right. My wondering is that whether this can be unit tested. If so, maybe unit tests should be added.

**Comment by ricab** [comment]
Indeed, this should be covered by unit tests. We have been steadily improving our test coverage over the years, but there are still blind spots. I agree that implementing tests for this should be part of fixing this issue.

**Comment by Aryansingh0103** [comment]
thankyou sir, I think my code will work but it has some flaws also in it but I'm still trying to improve it .
