### ISSUE TITLE
Provide method for opening browser on Windows when applications call xdg-open

### ISSUE THREAD

**Issue by worldofgeese** [canonical/multipass#2943]
WSL users can make use of the third-party `wslopen` to pass xdg-open requests to the native Windows browser. I'd like to see a similar feature built-in to Multipass.

Consider the use-case of `gh auth login` (the code is already expired in this example):

```sh
ubuntu@garden-dev:~$ gh auth login
? What account do you want to log into? GitHub.com
? What is your preferred protocol for Git operations? HTTPS
? Authenticate Git with your GitHub credentials? Yes
? How would you like to authenticate GitHub CLI? Login with a web browser

! First copy your one-time code: D37F-B950
Press Enter to open github.com in your browser...
! Failed opening a web browser at https://github.com/login/device
  exec: "xdg-open,x-www-browser,www-browser,wslview": executable file not found in $PATH
  Please try entering the URL in your browser manually
```

**Comment by andrei-toterman** [comment]
Hi, @worldofgeese! Unfortunately this sounds like something that's outside the scope of Multipass, and would be better handled by a 3rd party tool, just like `wsl-open`. For Linux, you could build a rudimentary tool as follows:
1. Create a script inside the instance with the following content:
```sh
HOST=`echo $SSH_CLIENT | cut -d " " -f1`
ssh <your-host-username>@$HOST DISPLAY=:0 firefox $@ # or your browser of choice
```
2. add `export BROWSER=<path to the above script>` to the instance `.bashrc` (or whatever the path of the file is in your case)

Now if you do `xdg-open https://www.google.com` inside the instance, it will use the `$BROWSER` variable and run the script, which will ssh back into the host and open the browser.

A similar process could be tried for Windows and macOS, but unfortunately it would probably be more complicated to open windows in them through ssh.

There is also the alternative of running the browser directly inside the instance and connecting to it from the host: https://multipass.run/docs/set-up-a-graphical-interface
