### ISSUE TITLE
Mount SD card

### ISSUE THREAD

**Issue by asyba** [canonical/multipass#2945]
How I can mount a sd card?

Im on Mac OS M1, having multipass Ubuntu.
I want tu mount the sdcard  but not the folder that mac interprets.
since this is a raspberry sdcard mac os does't detect the complete file structure **ext4** (two folders boot and other more)

```
Filesystem       Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk4s1    255Mi   32Mi  223Mi    13%       0         0  100%   /Volumes/boot
```

```
multipass mount /dev/disk4s1 /dev/sdcard1
Source path "/dev/disk4s1" is not a directory
```

**Comment by andrei-toterman** [comment]
Hi, @asyba! Unfortunately mounting external devices is not supported in Multipass, and it's currently not in our plans to add support for it. Sorry!
