### ISSUE TITLE
snapcraft images contain backports repo by default

### ISSUE THREAD

**Issue by jocado** [canonical/multipass#2956]
**Describe the bug**
It seems some snapcraft images contain the backports repo by default.  Verified for snapcraft:core20 at least.
This causes issues at snapcraft build time, as the backports repo is removed at some point [ probably by snapcraft itself ].

There is a bug about it here: https://bugs.launchpad.net/snapcraft/+bug/1982420

I thought I would log an issue here too to discuss, as including backpacks by default seems like a slightly odd decision.  I don't know if the images are maintained by the same team that looks after the multipass code however, so please redirect me if this is not the correct place to discuss.

**To Reproduce**
How, and what happened?
```
multipass launch -n test-20 -d 10g snapcraft:core20
```
```
root@test-20:~# dpkg -l |grep devmapper
ii  libdevmapper1.02.1:amd64       2:1.02.175-2ubuntu4~ubuntu20.04.1 amd64        Linux Kernel Device Mapper userspace library
```
```
root@test-20:~# apt-get update
```
```
root@test-20:~# cat /etc/apt/preferences.d/backports 
Package: *
Pin: release a=*-backports
Pin-Priority: 500
```
```
root@test-20:~# apt-cache policy libdevmapper1.02.1
libdevmapper1.02.1:
  Installed: 2:1.02.175-2ubuntu4~ubuntu20.04.1
  Candidate: 2:1.02.175-2ubuntu4~ubuntu20.04.1
  Version table:
 *** 2:1.02.175-2ubuntu4~ubuntu20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     2:1.02.167-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

```

**Expected behavior**
What did you expect to happen?
Ideally, `/etc/apt/preferences.d/backports` would not be included in the image setup process at all by default.

**Comment by sharder996** [comment]
Hi @jocado, this image is maintained by another group and you can file a bug at https://bugs.launchpad.net/cloud-images

**Comment by jocado** [comment]
Joining the dots, in case anyone else follows this: https://bugs.launchpad.net/cloud-images/+bug/2009871
