### ISSUE TITLE
Launch multipass inside wsl2

### ISSUE THREAD

**Issue by cloudbackenddev** [canonical/multipass#2962]
**Describe the bug**
  Trying to launch multipass within WSL2. I have built the binaries from source. When i launch the multipassd daemon it is not launching correctly within WSL2

**To Reproduce**
How, and what happened?
1. Binaries are build and available inside WSL2
~/tools/multipass/build/bin$ ls
grpc_cpp_plugin  mocks  multipass  multipass.gui  multipass_tests  multipassd  protoc  protoc-3.21.6.0  sshfs_server  test_data  text_to_string_array

2. Launching multipassd but the process is not launched
~/tools/multipass/build/bin$ ./multipassd&
[1] 8673
~/tools/multipass/build/bin$
[1]+  Exit 1                  ./multipassd
~/tools/multipass/build/bin$

**Expected behavior**
Ability to launch multipass VM's inside WSl2

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 Microsoft Windows 10 Enterprise
10.0.19042 Build 19042
I don't have systemd available in WSL2 as it is available in Windows 11 versions

C:\Windows\system32> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2

**Additional context**
I don't know if multipass can be launched inside WSL2 similar to how we launch in a standard ubuntu installation. Just checking if this is feasible

**Comment by ricab** [comment]
Hi @cloudbackenddev, you can try to run the daemon with `sudo ./multipassd --logger=stderr -V debug` and see how it goes. That said, there is no guarantee that the environment that WSL provides is enough to run Multipass, and I wouldn't be surprised if Hyper-V gets all confused trying to nest VMs in this way.

**Comment by ricab** [comment]
It looks like whatever `dnsmasq` it's picking up doesn't like our command line. What does `dnsmasq --version` say?

What are you running in WSL? On Ubuntu, `apt get install dnsmasq-base dnsmasq-utils` provides what we need.

**Comment by cloudbackenddev** [comment]
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.

**Comment by ricab** [comment]
OK, this is what our `dnsmasq` says:

```
$ /snap/multipass/8889/usr/sbin/dnsmasq --version
Dnsmasq version 2.86  Copyright (c) 2000-2021 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```

You might have to match that. Have you installed both of the packages I mentioned above?

**Comment by cloudbackenddev** [comment]
Thanks @ricab but as of now i proceeded further with multipass native installation in windows and able to procced further with that. Will try the wsl part subsequently

**Comment by cloudbackenddev** [comment]
@ricab The issue was with --dhcp-ignore-clid option. It seems this is a newly introducted in latest versions of dnsmasq. The default stable versions which gets insalled with apt-get are older and hence the issue

**Comment by cloudbackenddev** [comment]
issue due to lower version of dnsmasq

**Comment by ricab** [comment]
OK, thanks. FWIW I don't remember having this issue when I was back on focal nor am I aware of others experiencing this. But I could just be forgetful.
