### ISSUE TITLE
Help text should explain what instance names are acceptable

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#2976]
[...] "--name" has no help dialog; It would be useful to know what the naming restrictions are. For example, `multipass launch --name "00340599maas"` failed, but `multipass launch --name "case00340599"` works.

_Originally posted by @pjmattingly in https://github.com/canonical/multipass/issues/255#issuecomment-1472760189_

**Comment by sharder996** [comment]
There is already a github issue for this here #1277
Can we close one of them @ricab?

**Comment by ricab** [comment]
Oops, thanks for pointing it out!

Duplicate of #1277.
