### ISSUE TITLE
mount are not working anymore

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#2989]
**Describe the bug**
After changing some settings (changing cpus to 4 from 1 and ram from 1 to 8) mounts are not working anymore.

**To Reproduce**
How, and what happened?
1. `multipass launch --name primary --mount <some disk>:\:/mnt/<some disk>_host`
2. start multipass
3. mounts not working

**Expected behavior**
mounts should work.

**Logs**
[multipass_logs.txt](https://github.com/canonical/multipass/files/11069219/multipass_logs.txt)

**Additional info**
 - OS: Windows 11 pro
- multipass   1.11.1+win
- `[2023-03-25T17:12:45.658] [error] [client] Caught an unhandled exception:  is not a valid memory size - need a non-negative integer (in base 10) followed by the desired unit (e.g. 1234B, 42MiB)`
- `virtualbox`

**Additional context**

**Comment by luis4a0** [comment]
Hi @soredake, inspecting your logs, I think you hit #2986. The memory size is a separate issue, which you can report separately if you manage to isolate it.
