### ISSUE TITLE
zlib.dll error on installing 

### ISSUE THREAD

**Issue by Rogerss301** [canonical/multipass#2997]
**Describe the bug**
on installing 1.11.1 the installer cant find zlib.dll. and give an error with abort or proceed 

**To Reproduce**
How, and what happened?
1. uninstall 1.11.0 and run installer for 1.11.1
1.

**Expected behaviour**
What did you expect to happen? it to find the file and not state there is an issue

**Comment by luis4a0** [comment]
Hi @Rogerss301, which version of Windows you are using? Did you do something between uninstalling 1.11.0 and installing 1.11.1? When in the install process does the installer fail? Thanks

**Comment by townsend2010** [comment]
I'm going to close this as there was no response from the original author and we've not seen any other reports of this.
