### ISSUE TITLE
multipass mount doesn't work - bash: sshfs: command not found

### ISSUE THREAD

**Issue by popey** [canonical/multipass#30]
Created new VM, then made a directory I want to use between the VM and my host. I then tried to mount and it failed. 

```
$ multipass mount  /home/alan/tmp/electron electron:/home/ubuntu/electron
mount failed: The following errors occured:
bash: sshfs: command not found
```

It appears to create the folder inside the VM, but then doesn't connect the two. Installing sshfs in the VM and then re-running the command worked.

**Comment by Saviq** [comment]
Weird, we're asking `cloud-init` to install it and still try and make sure it's there on each mount... I suppose we need to make surer.

**Comment by gerboland** [comment]
If you try mounting before cloud-init has finished, this can happen. IMO we need to block commands like this until cloud-init finished

**Comment by Saviq** [comment]
@popey would you say you were trying this very soon (say, within a minute) after the instance got started? If so, then at least we have an explanation (and a plan to resolve it).

**Comment by popey** [comment]
No, some time after. Took me a while to grok the docs before I even tried.

**Comment by townsend2010** [comment]
Well, currently, we just set cloud-init to install sshfs in the VM and forget about it. So in this particular case, cloud-init was unable to install sshfs for some reason (non-functional networking, archive not available, etc.).  So yeah, we need to add logic to check what's happening when mount fails and try to do something about it.

**Comment by volomike** [comment]
This bug is not fixed on Mac OS 10.14.6 Mojave. And when I restart the shell and try to do:

````
sudo su
apt-get update
apt-get install multipass-ssh
````

It won't work because the `apt-get update` fails to reach the server and I can't even ping archive.ubuntu.com.

**Comment by volomike** [comment]
I just resolved my problem on the Mac. I edited `/etc/resolv.conf` and added `nameserver 1.1.1.1` as the top line above the other nameserver line. I could then do `dig google.ie` properly. At that point, I could do `apt-get update` and then could run `apt-get install sshfs`

**Comment by sinke237** [comment]
This problem is currently happening to me today, at the time of making this comment. 
I suspect my network connectivity but I would appreciate if I could get a clear message as to why it happened.
```
[2024-09-24T12:48:59.298] [error] [sshfs-mount-handler] Failed to install 'multipass-sshfs': error: unable to contact snap store
mount failed: Error enabling mount support in 'aks-cluster-vm'
```

**Comment by georgeliao** [comment]
@sinke237 
It does look like a network connectivity problem. Is it an intermittent thing? 
Also thanks for the error message feedback, it definitely can be improved.
