### ISSUE TITLE
Can I choose where multipass data is stored?

### ISSUE THREAD

**Issue by gentooza** [canonical/multipass#3001]
**What are you trying to do?**
I'm using ubuntu 22.04, since I worked 6.10 and others distros I used -and still- to separate my home partition from the system one.
This is useful for recovering systems, take better care of space, avoid data loss, etc. 
My system partition is small compared to the home one, as all my data is there, and linux packages are normally really optimized in space.

**the problem I face is multipass, installed by snap, stores all it's data in the "system" partition** folder /var/snap/multipass...
So it makes me to reorganice my partitions table.

**What's your proposed solution?**
For my, the perfect option would be to have data in my home folder, as every program installed via 'apt', ie: /home/me/.multipass/data

**Additional context**
Thanks a lot for the project, it's very useful for testing environments and configurations, I'm using it now in University for MPICH programming!

**Comment by luis4a0** [comment]
Hi @gentooza, changing where Multipass stores its external data is described in [this document](https://multipass.run/docs/configure-multipass-storage).

Don't hesitate in reopening if that doesn't help. Thanks!

**Comment by gentooza** [comment]
Hi @luis4a0!

thanks for the reponse! 

I've just seen also the issue: #1215 . It seems not to be easy yet **to migrate** to a new storage folder:
I follow the steps you provided but I get systemd errors about not found folders if I try to move my */var/snap/multipass* data to */home/me/multipass* .

But it's working perfectly if I clear everything and start again creating instances.

:-/ I guess it need to be polished?

thanks

**Comment by luis4a0** [comment]
Hi @gentooza, unfortunately, we don't have a way to move existing data to the new folder. But, as you said, starting from scratch works. I hope this wasn't a big blocker for you. Thanks!
