### ISSUE TITLE
Multipass failed

### ISSUE THREAD

**Issue by LaraHo** [canonical/multipass#3019]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/129280358/230047404-7c106bfb-c75d-4f96-9a6f-6e5c4b7435df.png">
my multipass has frequently encountered errors as shown in the picture. I can fixed by delete the vm instance and re-created it again, but the effect is only temporarily, and the same problem would happen just few days later.

**Comment by andrei-toterman** [comment]
Hi, @LaraHo! Can you please provide more details about the issue? More specifically:
- Your version of Multipass (`multipass version`)
- The used backend (`multipass get local.driver`)
- Your operating system version
- Logs (https://multipass.run/docs/accessing-logs)
- If possible, some steps to reproduce the issue
- Any other useful context

**Comment by LaraHo** [comment]
Hi! @andrei-toterman . Hope these information helps
- multipass version 
multipass   1.11.1+mac
multipassd  1.11.1+mac

- The used backend
hyperkit

- operating system version
macOS Monterey

[multipassd.log](https://github.com/canonical/multipass/files/11172969/multipassd.log)

**Comment by LaraHo** [comment]
@andrei-toterman 
When my vm instance works, there are also frequently have error on "sudo apt update", and I can only fixed it by recreate the instance too. Are the two problem related?

**Comment by LaraHo** [comment]
@andrei-toterman 
Hi, this is the problem I mentioned about the "sudo apt update".
<img width="566" alt="image" src="https://user-images.githubusercontent.com/129280358/232092674-b6ed3fce-a107-4df7-8368-a8f5c5816eaf.png">

**Comment by LightningRhino** [comment]
This problem occurs when the date/time differs too much from the host system.
I managed to bypass this by adding "sudo hwclock -s" in the .bashrc of the vm.

**Comment by townsend2010** [comment]
This occurred using the `hyperkit` driver which is now deprecated.  If you haven't already, please update to 1.12.2, switch to the `qemu` driver as instructed when interacting with Multipass and see if this issue still occurs.  If it does, either please reopen this issue or open a new issue.  Thanks!
