### ISSUE TITLE
Publish to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3040]
**What are you trying to do?**
Publishing multipass to microsoft store in msix format will make installing/updating very easy or automatic, which is nice.

**What's your proposed solution?**
multipass publish to microsoft store in msix format

**Additional context**
Example benefits of msix format:
https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features

**Comment by sharder996** [comment]
Hi @soredake, this is something that is on our roadmap and are working towards this. Thanks for recording this in a Github issue and we will update it as progress is made towards including Multipass in the Microsoft Store.
