### ISSUE TITLE
Number of CPUs and amount of memory limitations in apple silicon

### ISSUE THREAD

**Issue by ckato3** [canonical/multipass#3043]
**Describe the bug**

On a Apple MacBookPro M2Max 96GB machine, we cannot allocate more than 8 cores of CPU and 64GB of memory to multipass virtual ubuntu.
All M2Max cores (12) and more than 64GB of memory (up to 96GB) are required to perform my heavy computations.
This bug seems to come from a limitation of *** qemu ***, how should I deal with it?

**To Reproduce**

$ multipass launch --name ubuntu-virtm1 --cpus 10 --memory 32G --disk 120G 22.04
launch failed: The following errors occurred:                                   
qemu-system-aarch64: Number of SMP CPUs requested (10) exceeds max CPUs supported by machine 'mach-virt' (8)

$ multipass launch --name ubuntu-virtm2 --cpus 8 --memory 80G --disk 120G 22.04
launch failed: The following errors occurred:                                   
qemu-system-aarch64: Addressing limited to 36 bits, but memory exceeds it by 18253611008 bytes

**Comment by townsend2010** [comment]
Hi @ckato3!

Yes, sorry about the limitations in qemu.  They have [applied a fix upstream](https://patchwork.kernel.org/comment/25245565/), but it is not yet available in a qemu release.

When a new qemu release is available, we will get this fix and will be available in a subsequent Multipass release.

**Comment by ckato3** [comment]
I understand that we need to work on (1) releasing the patch in qemu, and (2) releasing multipass in response to this.

We look forward to the release work being done as soon as possible.

**Comment by ckato3** [comment]
Since Multipass on ARM (Apple Silicon) is still limited in the amount of memory and number of CPUs, I switched to UTM.app.

In UTM.app with *** Apple Virtualization Framework ***, which allowed us to use more than 64 GB of memory and more than 8 CPUs.

Also, compared to QEMU 7.2 , the Apple Virtualization Framework seemed to be faster at file sharing (virtiofs ?), and I was able to get 50% more compute speed !!!

The multipass was completely erased from my computer.

**Comment by EricJayHartman** [comment]
Hello @townsend2010 , I see this is closed as completed; however, I just tried to create an Ubuntu 24.04 LTS vm with 96GB of RAM on the lastest version of Multipass and MacOS (MacOS Sequoia 15.5), and I'm getting the error:

"The following errors occurred: qemu-system-aarch64: Addressing limited to 36 bits, but memory exceeds it by 35433480192 bytes"

Any advice on how to upgrade the qemu driver and provision more RAM for my VM would be greatly appreciated.
