### ISSUE TITLE
[Feature request] Create setup-multipass on GitHub action similar to lxd

### ISSUE THREAD

**Issue by talregev** [canonical/multipass#3051]
>**What are you trying to do?**
A description of what you want to happen.

Run a multipass on linux on github action. 

>**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.

Create setup-multipass on github action similar to lxd
https://github.com/canonical/setup-lxd

>**Additional context**

**Comment by townsend2010** [comment]
After I replied, it was pointed out to me that Github Actions runners don't support nested virtualization, so using Multipass in a Github Action isn't even possible.

**Comment by talregev** [comment]
How it done using lxd?

**Comment by townsend2010** [comment]
The LXD Github Action uses a container, not a virtual machine.

That said, it does appear that Github Actions do support nested virtualization: https://github.com/actions/runner-images/issues/183#issuecomment-1406892747

So it may be possible for someone to make a Multipass Github Action.

**Comment by townsend2010** [comment]
Oh, the nested virtualization is *only* available to Github Enterprise, so it doesn't really make sense then for someone to develop a Multipass-based Github Action.
