### ISSUE TITLE
How to use multipass offline or on limited networking

### ISSUE THREAD

**Issue by ryanrain2016** [canonical/multipass#3052]
**What are you trying to do?**
My windows PC can't connect to cloud-images.ubuntu.com and cdimage.ubuntu.com for some reasons. So I download the image it metioned when launching an instance, and I transfor the image file to my PC. But I don't know how to launch an instance with the image file.

**What's your proposed solution?**
Some commandlines can help me to use the image to launch an instance or import the image to multipass.
Or maybe there are some proxy settings in multipass.

**Additional context**
To use multipass offline or on limited networking

**Comment by ricab** [comment]
Hi @ryanrain2016, I am afraid we don't support launching from a file on Windows at the moment, so you need a working internet connection for Multipass to be able to fetch images. You could try to set `HTTP_PROXY` environment variable with something like:

```
PS> Stop-Service Multipass
PS> Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\Session Manager\Environment" -Name HTTP_PROXY -Value "http://..."
PS> Start-Service Multipass
```

Let us know how this goes for you!

**Comment by ryanrain2016** [comment]
Sorry for late response. I find an other way to use proxy to connect to the server.

**Comment by townsend2010** [comment]
Going to close this as it seems the issue has been overcome.
