### ISSUE TITLE
Lack of information when `copy-files` fails

### ISSUE THREAD

**Issue by morphis** [canonical/multipass#306]
I am trying to copy files into a multipass VM via

    $ multipass copy-files $HOME/Downloads/drive-download-20180702T095043Z-001.zip binder-test:/home/ubuntu

It fails all the time with `copy-files failed: ssh:`. Entering the VM with `multipass shell binder-test` works.

Using revision 334 of the mutlipass snap and tracking the beta channel.

**Comment by Saviq** [comment]
@morphis we switched to a dedicated `multipass` user so `/home/ubuntu` doesn't exist.

`multipass copy-files $HOME/Downloads/drive-download-20180702T095043Z-001.zip binder-test:` should work fine.

**Comment by morphis** [comment]
@Saviq ah great, didn't noticed that. What is with VMs created before that change?

**Comment by Saviq** [comment]
@morphis old instances keep the `ubuntu` name and should work fine. Just don't hardcode `/home/ubuntu` (or `/home/multipass` for that matter!) in your scripts, mounts and file copies are always relative to $HOME.

**Comment by albaguirre** [comment]
#389 improves error messaging around ssh commands.
