### ISSUE TITLE
multipass_socket has the wrong permissions

### ISSUE THREAD

**Issue by johnnygerard** [canonical/multipass#3073]
**Describe the bug**
multipass_socket uses the root group.

```bash
$ ls -l /var/snap/multipass/common/multipass_socket
srw-rw-rw- 1 root root 0 May 15 12:32 /var/snap/multipass/common/multipass_socket
```

**To Reproduce**
sudo snap install multipass

**Expected behavior**
It should have the group sudo, adm or admin.

**Additional info**
 - OS: Ubuntu 23.04 (lunar)
 - multipass v1.11.0
 - local.driver: qemu

**Comment by johnnygerard** [comment]
Changing permissions solves the issue but this is only a workaround because permissions are reset everytime the snap is restarted.

```bash
sudo chgrp sudo /var/snap/multipass/common/multipass_socket
```

**Comment by townsend2010** [comment]
Hi @johnnygerard!

We made [changes in Multipass v1.9.0](https://multipass.run/docs/authenticate-command) which makes what you report the correct behavior.  The change allows *any* user regardless of group permissions to connect  to the Multipass daemon as long as they have authenticated their clients via a passphrase set by the administrator.  That said, the socket will have permissions you expect the first time Multipass is installed and will automatically accept the client connection if the user is part of the `sudo` group.

**Comment by johnnygerard** [comment]
Thanks for clarifying.

So if I understand, `local.passphrase` must be set after installation and then the user authenticates each time before accessing a VM.

There is no mention of this in [How to install Multipass on Linux](https://multipass.run/docs/installing-on-linux) or in [Install Multipass](https://multipass.run/install).

**Comment by johnnygerard** [comment]
Thanks again for clarifying.

I still have issues but I think it is related to the network.
I will open a separate issue.
