### ISSUE TITLE
multipass vm - curl from command line

### ISSUE THREAD

**Issue by kpoonku** [canonical/multipass#3079]
I have set up ssh for my multipass when lauching it. I have a webserver running in the multipass vm. I am trying to curl the webserver from the host machine. Before ssh, I was able to do it, but after ssh no luck.

Host Machine MacOs Ventura M1 
Host vm : multipass VM
vm Ip address : 192.168.64.12

I . curl https://192.168.64.12:8444 -k | jq

Error message: 
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 192.168.64.12:8444 

II. curl http://192.168.64.12:8001 | jq  

Error message: 
curl: (52) Empty reply from server

**Comment by townsend2010** [comment]
Hi @kpoonku!

I'm really not sure what you mean by "I have set up ssh for my multipass when lauching it."  `sshd` is already set up in a Multipass instance. so could you please explain what you have done and what you trying to accomplish?

**Comment by townsend2010** [comment]
Going to close this since there has been no reply by the author.
