### ISSUE TITLE
launch failed: cannot connect to the multipass socket                            Please ensure multipassd is running and '/var/run/multipass_socket' is accessible

### ISSUE THREAD

**Issue by ChrisForti** [canonical/multipass#3084]
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**

**Comment by topher4D** [comment]
I got it, just reinstalled. then cleaned up any extra slag. TY MB

**Comment by townsend2010** [comment]
Hi @topher4D,

Just to make sure before I close this, you got this working, right?

**Comment by topher4D** [comment]
yes sir, it is all good. I believe I caused it. I was changing some preferences on my Mac this weekend. I must have deleted one of the support programs, on accident. thank you for your quick response though.

**Comment by townsend2010** [comment]
Ok, glad you got it all sorted out.  Thanks for letting us know!
