### ISSUE TITLE
need to be authenticated but passphrase is not set

### ISSUE THREAD

**Issue by yaunsine** [canonical/multipass#3103]
**Describe the  #bug**
Like #2628.

**To Reproduce**
How, and what happened?
I need to configure new storage location, and try the command from [https://multipass.run/docs/configure-multipass-storage#heading--windows](https://multipass.run/docs/configure-multipass-storage#heading--windows) docs.
when I stop the multipass service, it wait for more time and cannot stop it. Therefore I use `ctrl+c` to force stop command.
When I restarted the service and almost of all multipass command trying has not done. The figure as following:
![image](https://github.com/canonical/multipass/assets/54234422/e19a5413-d689-43b6-8997-d172e7b103f4)
1. `multipass authenticate`
![image](https://github.com/canonical/multipass/assets/54234422/85099482-27fc-4b13-b45f-004490f9ac95)
2.`multipass set local.passphrase`
![image](https://github.com/canonical/multipass/assets/54234422/cdd5ec47-8708-400c-908e-612c136f9c6e)

**Expected behavior**
What did you expect to happen?
Change storage location

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
![image](https://github.com/canonical/multipass/assets/54234422/96f4dead-c1a5-40e7-b5d0-807fc26694ec)

![image](https://github.com/canonical/multipass/assets/54234422/032a3ade-8f7e-4185-b4d7-462429da3d81)

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`
- `multipass get local.driver`
![image](https://github.com/canonical/multipass/assets/54234422/5104e9a9-7f1b-4a9d-b210-aa8f4f1c2636)
![image](https://github.com/canonical/multipass/assets/54234422/1460922e-1f41-4053-9b0a-177d95bf848c)

**Additional context**

**Comment by yaunsine** [comment]
no file `E:\data\vm\data\cache\vault\multipassd-image-records.json` is generated.
![image](https://github.com/canonical/multipass/assets/54234422/8b295df0-642f-43d5-b76f-a4185e557148)

**Comment by yaunsine** [comment]
has found the problem, which change storage location occur to exception multipass service access.

**Comment by yaunsine** [comment]
It could be solved by manually copying or cutting files from the path `C:\ProgramData\Multipass`. And then restart service.

**Comment by ricab** [comment]
Hi @yaunsine, glad you managed to sort it out :)
