### ISSUE TITLE
Provide information on valid instance name

### ISSUE THREAD

**Issue by agileshaw** [canonical/multipass#3110]
**What are you trying to do?**
When launching a new instance with an invalid instance name, multipass shows an error message similar as the following:
```
launch failed: Invalid arguments supplied                                       
Invalid instance name supplied: 29-test
```
However, neither the error message nor the output of `multipass launch --help` explains what formats of instance name are or aren't allowed. It would be nice if more information can be provided.

**What's your proposed solution?**
Include the valid format of instance name in both `multipass launch` command's `help` output and in the error message of a failed command execution (due to unaccepted name input)

**Comment by luis4a0** [comment]
Hi @agileshaw, thanks for your suggestion. As you may have guessed, the instance name cannot start with a digit. Although this depends on the driver being used, it would be a good idea to add in the documentation which names are valid for the instances.

**Comment by RoastBeefKazenzakis** [comment]
I have also generated an error of this type without using a leading digit:

Using Ansible to pass the following command using the shell module:

Host OS: Ubuntu Server
Driver: QEMU
Command: multipass launch --name "{{ instance_name }}" \
      --memory 8G \
      --cpus 2 \
      --network br0
      --cloud-init /home/guy/cloud-init.yaml

The instance_name variable is set to: "pibrain.homenetwork.net"

The error output is:
launch failed: Invalid arguments supplied
Invalid instance name supplied: pibrain.homenetwork.net", "stderr_lines": ["launch failed: Invalid arguments supplied", "Invalid instance name supplied: pibrain.homenetwork.net"

**Comment by luis4a0** [comment]
Hi @RoastBeefKazenzakis! The rule is that instance names must be valid (non-qualified) host names. The dots are thus not allowed. This will be documented soon, thanks for pointing it out!

**Comment by akauppi** [comment]
I'd really like `+` and `_` to be allowed, but that's likely not going to happen.

On "valid (non-qualified) host names", please observe this (especially since OP's issue was a name starting with a digit):

>However, a subsequent specification ([RFC 1123](https://www.rfc-editor.org/rfc/rfc1123)) **permitted hostname labels to start with digits**. No other symbols, punctuation characters, or white space are permitted.

I really don't know if that's relevant. [Source](https://en.wikipedia.org/wiki/Hostname) via a [StackOverflow answer](https://stackoverflow.com/a/3523068/14455)

**Comment by giuliazanchi** [comment]
Documentation is available here: https://multipass.run/docs/instance-name-format
