### ISSUE TITLE
Bad argument parsing on `exec` on Windows

### ISSUE THREAD

**Issue by luis4a0** [canonical/multipass#3120]
**Describe the bug**
Executing a command containing quotes and a space inside the quotes fails on Windows.

For example, the command `multipass exec instance -- bash -c 'ls -la'` would fail on Windows because the list of arguments passed through SSH contains the following elements: `bash`, `-c`, `'ls`, `-la'`. On Linux and Mac this doesn't fail, because the shell interprets the quoted text and returns the list `bash`, `-c`, `ls -la`.

**To Reproduce**
`multipass exec instance -- bash -c 'ls -la'`

**Expected behavior**
Execute `bash -c 'ls -la'` in the instance.

**Logs**
No relevant information on the logs.

**Additional info**
 - OS: Windows 10
- `multipass version`: 1.11.1 and 1.12.0
- `multipass info --all`: not needed
- `multipass get local.driver`: hyperv and virtualbox

**Comment by luis4a0** [comment]
Hi @rkr-kununu, thanks for reporting. The issue you mention was already reported in #3119. Please check there the status of the fix, which will be released in a bugfix release soon.

**Comment by ricab** [comment]
Hey @luis4a0, I just found this issue again. 

I don't think this is a bug. When you call `multipass exec instance -- bash -c 'ls -la'` in bash, Multipass is invoked with the string `ls -la` in the last `argv` element. The equivalent on the Windows Command Prompt would be `multipass exec instance -- bash -c "ls -la"`. Cmd wants double quotes to call Multipass with the same `argv`.

Our documentation may need to be generalized for the Windows case though. Let me know if you know of particular docs need fixing!

Does this make sense to you? Are you OK with closing this now?

**Comment by luis4a0** [comment]
Hey @ricab, I'm not sure. We discussed on this but I don't remember the outcome. There is not much we can do, AFAICS. Maybe we have to explain carefully the situation in the docs and then yes, closing this.

**Comment by ricab** [comment]
Hey @luis4a0, I believe the outcome was that this just needs to be covered in the docs (I am doing part of that right now). 

But here's another argument to try to convince you. Imagine a Multipass user that calls our CLI from *FancyStarShell*, a shell where quoting is done with stars. Should Multipass try to parse `'ls`, `-la'` there too? Or should the user say `multipass exec instance -- bash -c *ls -la*`, has their shell prescribes? If we decide to cover that shell in our documentation, should Multipass now handle `*ls` & `-la*` in other shells too? For that matter, should multipass attempt to handle double quotes in bash as they are handled on the Command Prompt?

I hope this makes it clearer where the boundary between shell and multipass is. I am going to close now, but please let me know if there is anything you still think needs to be addressed (documentation in particular).

**Comment by ricab** [comment]
I've updated https://multipass.run/docs/exec-shells to better reflect this.
