### ISSUE TITLE
Add Version Number to macOS Application Bundle 

### ISSUE THREAD

**Issue by harryhmtse** [canonical/multipass#3122]
**Describe the bug**
macOS Application Bundle does not report version number

**To Reproduce**
1.  Examine Get Info on Multipass.app or examine Multipass.app/Contents/Info.plist
2. Version field is blank or undefined

**Expected behavior**
Version field is defined and bumped accordingly with each subsequent release

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/11731588/multipassd.log)

**Additional info**
macOS 13.4
multipass   1.12.0+mac
multipassd  1.12.0+mac
qemu

**Additional context**
While the issue is not functional and appear largely cosmetic, Management Frameworks use the metadata reported in Info.plist to report software inventory installed on the system.  While it is possible to get this data via `multipass version` it is outside the norm of what is expected for macOS application reporting, and also a more expensive operation. Also the other metadata in Info.plist could be normalized and included for completeness.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string></string>
    <key>CFBundleIdentifier</key>
    <string></string>
    <key>CFBundleName</key>
    <string>Multipass</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
    <key>CFBundleIconFile</key>
    <string>icon.icns</string>

    <key>LSUIElement</key>
    <true/>

    <key>NSHighResolutionCapable</key>
    <true/>

</dict>
</plist>
```

<img width="377" alt="Screenshot 2023-06-12 at 11 55 10 PM" src="https://github.com/canonical/multipass/assets/5060483/8fbb6f94-5d52-435f-95ee-0ec8388c5789">

**Comment by ricab** [comment]
Fixed by #3504
