### ISSUE TITLE
allow using multiple key-value pairs in `multipass set`

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3131]
**What are you trying to do?**
```
multipass set client.gui.autostart=no,local.privileged-mounts=yes
Bad key-value format.
```

**What's your proposed solution?**
Allowing multiple key-value pairs with `multipass set`

**Additional context**
If this is implemented i can convert this:
```
sudo multipass set local.driver=virtualbox
multipass set local.privileged-mounts=yes
multipass set client.gui.autostart=no
```
to this:
```
sudo multipass set local.driver=virtualbox,local.privileged-mounts=yes,client.gui.autostart=no
```

Which is shorter.

**Comment by georgeliao** [comment]
@soredake, an interesting enhancement you have proposed. we will discuss within the team and come back to you.

**Comment by georgeliao** [comment]
Based on the roadmap of the multipass, a `config` on setting feature was planned which will give user more advanced setting options.
