### ISSUE TITLE
Editing MULTIPASS_SERVER_ADDRESS results in cannot connect to the multipass socket ?

### ISSUE THREAD

**Issue by zippy-zebu** [canonical/multipass#3132]
**Describe the bug**
I installed multipass on dedicated root server (ubuntu server 20.04) running on linode. How does this supposed to work with MULTIPASS_SERVER_ADDRESS=0.0.0.0:51005 ? I edited the systemd file as described [here](https://multipass.run/docs/how-to-use-multipass-remotely-a-preview). 

But after restarting multipassd, multipass find simply doesn't work.

```sh
sudo snap stop multipass
sudo snap start multipass
```

```sh
sudo netstat -plnt | grep multipass
tcp6       0      0 :::51005         :::*                    LISTEN      1297086/multipassd  
```

```sh
MULTIPASS_SERVER_ADDRESS=0.0.0.0:51005 multipass find
find failed: cannot connect to the multipass socket
```

```
/var/snap/multipass/common # ls -l
total 16
drwxr-xr-x 3 root root 4096 Jun 19 23:01 apparmor.d
drwxr-xr-x 3 root root 4096 Jun 19 23:01 cache
drwxr-xr-x 3 root root 4096 Jun 19 23:01 data
-rw-r--r-- 1 root root   51 Jun 19 23:01 snap_config
```

**Additional info**
 - OS: Ubuntu 20.04
- `multipass version` - 1.12

Everything works if I use `localhost:51005` the address parameter from systemd file (snap.multipass.multipassd.service) and restart snapd and multupassd.

How to solve this ?

**Comment by georgeliao** [comment]
@zippy-zebu , thanks for question, based on the tutorial, I think `MULTIPASS_SERVER_ADDRESS=<hostname>:51001` needs a hostname there; in your scenario, I think the hostname should be the linode machine hostname or IP address of your server machine instead of `0.0.0.0`.

**Comment by khurshid-alam** [comment]
@georgeliao 

Using ip doesn't work. I am using server public ip that is, (edited systemd file and restarted multipassd)

```sh
 sudo netstat -plnt | grep multipass
tcp6       0      0 95.217.xx.xx:51005     :::*                    LISTEN      1816416/multipassd  
```

```
MULTIPASS_SERVER_ADDRESS=95.217.xx.xx:51005 multipass find
find failed: cannot connect to the multipass socket
```

Using hostname (hostname -f) **works**. But the issue is docker and other services running on the server and multipass starts lisstning all of them. 

```sh
sudo netstat -plnt | grep multipass
tcp6       0      0 2a01:4f9:xx:xxxx::51005 :::*                    LISTEN      1815270/multipassd  
tcp6       0      0 95.217.xx.xx:51005     :::*                    LISTEN      1815270/multipassd  
tcp6       0      0 172.17.0.1:51005        :::*                    LISTEN      1815270/multipassd  
tcp6       0      0 10.129.72.1:51005       :::*                    LISTEN      1815270/multipassd 
```

```sh
MULTIPASS_SERVER_ADDRESS=jammy-dev:51005 multipass find
Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20211124         Ubuntu Core 18
core20                                        20230119         Ubuntu Core 20
core22                                        20230119         Ubuntu Core 22
20.04                       focal             20230616         Ubuntu 20.04 LTS
22.04                       jammy,lts         20230616         Ubuntu 22.04 LTS
22.10                       kinetic           20230607         Ubuntu 22.10
23.04                       lunar             20230602         Ubuntu 23.04
```

This is overkill, since all I want to listen it just to 0.0.0.0 so that I can access it over the internet without using reverse proxy.

**Comment by zippy-zebu** [comment]
Using ip doesn't work. I am using server public ip that is, (edited systemd file and restarted multipassd)

```sh
sudo netstat -plnt | grep multipass
tcp6       0      0 95.217.xx.xx:51005     :::*                    LISTEN      1816416/multipassd  
```

```
MULTIPASS_SERVER_ADDRESS=95.217.xx.xx:51005 multipass find
find failed: cannot connect to the multipass socket
```

Using hostname (hostname -f) **works**. But the issue is docker and other services running on the server and multipass starts lisstning on all of them. 

```sh
sudo netstat -plnt | grep multipass
tcp6       0      0 2a01:4f9:xx:xxxx::51005 :::*                    LISTEN      1815270/multipassd  
tcp6       0      0 95.217.xx.xx:51005     :::*                    LISTEN      1815270/multipassd  
tcp6       0      0 172.17.0.1:51005        :::*                    LISTEN      1815270/multipassd  
tcp6       0      0 10.129.72.1:51005       :::*                    LISTEN      1815270/multipassd 
```

```sh
MULTIPASS_SERVER_ADDRESS=jammy-dev:51005 multipass find
Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20211124         Ubuntu Core 18
core20                                        20230119         Ubuntu Core 20
core22                                        20230119         Ubuntu Core 22
20.04                       focal             20230616         Ubuntu 20.04 LTS
22.04                       jammy,lts         20230616         Ubuntu 22.04 LTS
22.10                       kinetic           20230607         Ubuntu 22.10
23.04                       lunar             20230602         Ubuntu 23.04
```

This is overkill, since all I want to listen it just to 0.0.0.0 so that I can access it over the internet without using reverse proxy.

**Comment by georgeliao** [comment]
Hi, @zippy-zebu , in your scenario, what needs to be figured out is the server's IP address and port. It looks like your server is on the cloud, so you may need to check the cloud provider's console or dashboard. This is really a matter of the user's personal setup and is beyond the scope of multipass already.

**Comment by zippy-zebu** [comment]
I am using Public ip it provides in the above example. But it is surprising that multipasssd can't bind it to 0.0.0.0. Hopefully it will be available in future. Closing.
