### ISSUE TITLE
Can't connect to multipass_socket after enabling server

### ISSUE THREAD

**Issue by bkarakoc** [canonical/multipass#3139]
**Describe the bug**
Hello everyone! Following this guide: “[How to use multipass remotely | macOS](https://multipass.run/docs/how-to-use-multipass-remotely-a-preview#heading--macos)” somehow deletes my multipass_socket after unloading/loading the multipassd? I tried uninstalling/reinstalling both through the .pkg file and brew cask. Even though after a clean install Multipass works with no problems, but after following the instructions on how to expose the local instance to the network my multipass_socket file in /var/run disappears. 

Could someone help me debug this issue please?
**To Reproduce**
How, and what happened?
1. Clean-install multipass 
2. Verify that it works through version and/or launching an instance
3. Verify that multipass_socket exists under /var/run
4. Run the command: `sudo /usr/libexec/PlistBuddy -c "Add :ProgramArguments: string --address"  -c "Add :ProgramArguments: string localhost:51001"  /Library/LaunchDaemons/com.canonical.multipassd.plist`
5. Unload/load multipassd

**Expected behavior**
To able to run multipass after enabling the server feature.
**Logs**

> [2023-06-26T02:05:29.456] [warning] [Qt] Empty filename passed to function
> [2023-06-26T02:05:29.893] [debug] [update] Latest Multipass release available is version 1.12.0
> [2023-06-26T02:05:33.006] [info] [VMImageHost] Did not find any supported products in “appliance”
> [2023-06-26T02:05:33.009] [debug] [blueprint provider] Loading “anbox-cloud-appliance” v1
> [2023-06-26T02:05:33.009] [debug] [blueprint provider] Loading “charm-dev” v1
> [2023-06-26T02:05:33.010] [debug] [blueprint provider] Loading “docker” v1
> [2023-06-26T02:05:33.010] [debug] [blueprint provider] Loading “jellyfin” v1
> [2023-06-26T02:05:33.011] [debug] [blueprint provider] Loading “minikube” v1
> [2023-06-26T02:05:33.011] [debug] [blueprint provider] Loading “ros-noetic” v1
> [2023-06-26T02:05:33.011] [debug] [blueprint provider] Loading “ros2-humble” v1
> [2023-06-26T02:05:33.023] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket
> [2023-06-26T02:05:33.024] [warning] [Qt] QIODevice::write (QFile, “/var/root/Library/Caches/multipassd/qemu/vault/multipassd-image-records.json”): device not open
> [2023-06-26T02:05:33.024] [info] [daemon] Starting Multipass 1.12.0+Mac
> [2023-06-26T02:05:33.024] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug
> E0626 02:05:33.874993000 6181285888 tcp_server_posix.cc:245] Failed getpeername: Invalid argument
> [2023-06-26T02:11:23.144] [info] [daemon] Received signal 15 (Terminated: 15)
> [2023-06-26T02:11:23.144] [info] [daemon] Goodbye!
> [2023-06-26T02:11:28.677] [warning] [Qt] Empty filename passed to function
> [2023-06-26T02:11:28.864] [info] [VMImageHost] Did not find any supported products in “appliance”
> [2023-06-26T02:11:29.168] [debug] [update] Latest Multipass release available is version 1.12.0
> [2023-06-26T02:11:29.174] [debug] [blueprint provider] Loading “anbox-cloud-appliance” v1
> [2023-06-26T02:11:29.175] [debug] [blueprint provider] Loading “charm-dev” v1
> [2023-06-26T02:11:29.176] [debug] [blueprint provider] Loading “docker” v1
> [2023-06-26T02:11:29.176] [debug] [blueprint provider] Loading “jellyfin” v1
> [2023-06-26T02:11:29.177] [debug] [blueprint provider] Loading “minikube” v1
> [2023-06-26T02:11:29.177] [debug] [blueprint provider] Loading “ros-noetic” v1
> [2023-06-26T02:11:29.177] [debug] [blueprint provider] Loading “ros2-humble” v1
> [2023-06-26T02:11:29.182] [info] [rpc] gRPC listening on localhost:51001
> [2023-06-26T02:11:29.183] [warning] [Qt] QIODevice::write (QFile, “/var/root/Library/Caches/multipassd/qemu/vault/multipassd-image-records.json”): device not open
> [2023-06-26T02:11:29.183] [info] [daemon] Starting Multipass 1.12.0+Mac
> [2023-06-26T02:11:29.183] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug --address localhost:51001

**Additional info**
 - OS: macOS 13.4.1
- Multipass 1.12.0+mac

**Comment by townsend2010** [comment]
Hi @bkarakoc!

Yes, if you change where `multipassd` is listening to `localhost`, this changes the socket type to a TCP socket and no longer the Unix domain socket that you originally see in `/var/run`.  TCP sockets are not filesystem based sockets like what Multipass uses by default.  This is, for example, how web servers communicate with clients over a network.

This is expected behavior and is not a bug.  Please let us know if you any further questions!  Thanks!
