### ISSUE TITLE
Define user name for instance at launch time

### ISSUE THREAD

**Issue by sergiusens** [canonical/multipass#314]
To use multipass as an implementation detail for snapcraft, it would be nice if we could use our own identity and setup. One of those things defining the identity is being able to setup the user name being shelled into.

For this purpose, following previous _hallway_ conversations with @Saviq, we agreed that an elegant way to do this is to allow defining the username to use by multipass during `launch`.

**Comment by Saviq** [comment]
Rolling into #315.
