### ISSUE TITLE
[regression][macos] Restarting daemon while tray GUI is running can hang the daemon

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#3142]
A regression has been [reported](#3140) where restarting `multipassd` while the system tray GUI is running will cause the daemon to not respond to requests after it starts.

It has been narrowed down to this error in the log:
```
E0627 10:12:08.657058000 6136393728 tcp_server_posix.cc:245]           Failed getpeername: Invalid argument
```
`gRPC` seems to get in a bad way *only* on the Mac when this occurs.  It seems this correlates with this change: https://github.com/CanonicalLtd/grpc/commit/447bd664c0fa691f859501b7ee71da48de8b64c7

To work around this issue, please do the following:
```
% launchctl unload /Library/Application\ Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist
% sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
% sudo launchctl load -w /Library/LaunchDaemons/com.canonical.multipassd.plist
```

**Comment by samie** [comment]
Can't fully confirm, but this seems to correlate with the host machine network change. Even reboot does not help until I did `sudo dscacheutil -flushcache`.

**Comment by supersid1695** [comment]
@townsend2010 any workaround for this issue? @samie solution didn't actually work for me. 

System: M1 Pro
OS: ventura 13.4.1

**Comment by townsend2010** [comment]
@supersid1695 Yes, you need to do what I posted in https://github.com/canonical/multipass/issues/3140#issuecomment-1610023585.

I will add those instructions in this issue's description as well.

**Comment by huyz** [comment]
@townsend2010's workaround wasn't sufficient for me. I also had to do @samie's `sudo dscacheutil -flushcache` and multipass started working again for me.
