### ISSUE TITLE
[macos] Setting `MULTIPASS_STORAGE` via the docs does not work on newer macOS

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#3145]
A user reported on IRC that their instances were no longer seen after a macOS update.  They had set `MULTIPASS_STORAGE` as [instructed](https://multipass.run/docs/configure-multipass-storage#heading--macos) in the docs.  After some investigation, it has been determined that `MULTIPASS_STORAGE` is not being set.

This has been reproduced on 13.4.1 and 13.4.  It seems some new changes to the System Integrity Protection (SIP) was introduced in 13.4, but this is merely anecdotal at this time. More investigation on *when* this behavior began is needed and also to figure out a way to mitigate this.

**Comment by townsend2010** [comment]
I missed this, but it has been reported at https://github.com/canonical/multipass/issues/2417#issuecomment-1553437799 and https://github.com/canonical/multipass/issues/2417#issuecomment-1564147227.

Long term, the answer is to add a setting that changes the storage directory and migrates existing data to that directory.  Shorter term, documenting the symlink workaround is best.

**Comment by giuliazanchi** [comment]
The workaround mentioned in https://github.com/canonical/multipass/issues/2417#issuecomment-1553437799 and https://github.com/canonical/multipass/issues/2417#issuecomment-1564147227 is documented in https://multipass.run/docs/configure-multipass-storage. 

@ricab see if we can close this based on Chris' comment above.

**Comment by ricab** [comment]
Yes, I think so. Thanks!
