### ISSUE TITLE
multipass starts very long on windows (~25 secs) when doing `multipass start`

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3148]
**Describe the bug**
multipass starts very long on windows (~25 secs)

**To Reproduce**
How, and what happened?
1. Setup instance like this `multipass launch --name primary -c 4 -m 4G --disk 10G --mount E:\:/mnt/e_host --mount D:\:/mnt/d_host --mount C:\:/mnt/c_host`
2. Try to start it.

**Expected behavior**
It should not take 25 secs to start.

**Logs**
[01_07_2023 log.txt](https://github.com/canonical/multipass/files/11924575/01_07_2023.log.txt)

**Additional info**
 - OS: Windows 11 Pro
 -
```
multipass   1.12.0-rc.499+g1316b0b2.win
multipassd  1.12.0-rc.499+g1316b0b2.win
```
 -
```
Name:           primary
State:          Running
IPv4:           N/A
Release:        Ubuntu 22.04.2 LTS
Image hash:     7d830df583e8 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.02 0.05 0.02
Disk usage:     2.6GiB out of 9.6GiB
Memory usage:   228.3MiB out of 3.8GiB
Mounts:         E:/           => /mnt/e_host
                    UID map: -2:default
                    GID map: -2:default
                C:/Users/user => Home
                    UID map: -2:default
                    GID map: -2:default
                C:/           => /mnt/c_host
                    UID map: -2:default
                    GID map: -2:default
                D:/           => /mnt/d_host
                    UID map: -2:default
                    GID map: -2:default
```
- virtualbox

**Additional context**

**Comment by sharder996** [comment]
Hi @soredake! Does the issue persist if you unmount everything and recreate the mounts? The sshfs server is crashing and ssh is timing out which is causing the long delay.

**Comment by soredake** [comment]
@sharder996 after doing umount with all my three mount the issue is still here, logs: 
[05_07_2023.txt](https://github.com/canonical/multipass/files/11954390/05_07_2023.txt)

**Comment by soredake** [comment]
>Are you saying the instance boots as fast as you'd expect with all the mounts you have defined before you run the script you linked?

No, even when skipping my script it boots ~25 secs, just doing `multipass launch --name primary -c 4 -m 4G --disk 10G --mount E:\:/mnt/e_host --mount D:\:/mnt/d_host --mount C:\:/mnt/c_host` is enough to make it boot slow.

**Comment by townsend2010** [comment]
Ok, thank you, that helps.  One last question, does it take a long to to boot if you pass **no** mounts to `launch`?

**Comment by townsend2010** [comment]
Oh, wait, does this only occur on `launch` when passing the `--mount` options and not on if you `stop` then `start` an instance?  It may take a longer on `launch` when passing `--mount` because the instance has to download and install the `multipass-sshfs` snap and the `core18` snap.  Depending on network conditions/speed and how much load the instance and host is under at the time, you may see a noticeable delay in `launch` due to this.

**Comment by soredake** [comment]
> Oh, wait, does this only occur on `launch` when passing the `--mount` options and not on if you `stop` then `start` an instance?

My problem is with `start` command, with mounts specified i get ~26 secs startup time, without mounts it's ~17 secs.

Logs without mounts:
[without_mounts.txt](https://github.com/canonical/multipass/files/11982255/without_mounts.txt)

**Comment by townsend2010** [comment]
Ok, now I understand what is happening.

So on `start` when Multipass queries `snapd` inside the instance to detect if `multipass-sshfs` is installed for the first time, `snapd` isn't quite ready, so this operation can take some time until it is ready.  In [this log](https://github.com/canonical/multipass/files/11979534/07_07_2023.txt), it took ~10 seconds for this to happen:
```
Сведения	07.07.2023 10:53:33	Multipass	1	Отсутствует	[sshfs-mount-handler] The multipass-sshfs snap is already installed on 'primary'

Сведения	07.07.2023 10:53:23	Multipass	1	Отсутствует	[ssh session] Executing 'sudo snap list multipass-sshfs'
```

The actual setting up of all the mounts took ~2 seconds after that according to that log.

There really isn't anything we can do about `snapd` taking so long here.  I guess we could circumvent `snapd` to ensure `multipass-sshfs` is installed by querying the known directory or something, but that seems pretty hack-y to me.

Are the approximately 9-11 extra seconds when starting an instance with mounts causing you problems in your workflow?

**Comment by soredake** [comment]
> Are the approximately 9-11 extra seconds when starting an instance with mounts causing you problems in your workflow?

No, but i remember that in the past startup times been faster, maybe.

**Comment by townsend2010** [comment]
You can try `$ systemd-analyze blame` inside the instance to perhaps see what may be taking so long.

Also, if it is indeed `snapd` taking so long, then `$ systemd-analyze critical-chain snapd.service` may show which part is taking so long.

**Comment by soredake** [comment]
> You can try `$ systemd-analyze blame` inside the instance to perhaps see what may be taking so long.

Most interesting:


```
8.486s snap.lxd.activate.service
8.335s snapd.service
1.552s systemd-networkd-wait-online.service
```

> Also, if it is indeed snapd taking so long, then $ systemd-analyze critical-chain snapd.service may show which part is taking so long.

```
ubuntu@primary:~$ systemd-analyze critical-chain snapd.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

snapd.service +8.335s
└─basic.target @3.709s
  └─sockets.target @3.708s
    └─snapd.socket @3.703s +4ms
      └─sysinit.target @3.665s
        └─cloud-init.service @3.205s +457ms
          └─systemd-networkd-wait-online.service @1.638s +1.552s
            └─systemd-networkd.service @1.574s +33ms
              └─network-pre.target @1.553s
                └─cloud-init-local.service @951ms +601ms
                  └─systemd-remount-fs.service @507ms +7ms
                    └─systemd-fsck-root.service @470ms +29ms
                      └─systemd-journald.socket @343ms
                        └─system.slice @209ms
                          └─-.slice @209ms
```

```
ubuntu@primary:~$ systemd-analyze critical-chain snap.lxd.activate.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

snap.lxd.activate.service +8.486s
└─basic.target @3.709s
  └─sockets.target @3.708s
    └─snapd.socket @3.703s +4ms
      └─sysinit.target @3.665s
        └─cloud-init.service @3.205s +457ms
          └─systemd-networkd-wait-online.service @1.638s +1.552s
            └─systemd-networkd.service @1.574s +33ms
              └─network-pre.target @1.553s
                └─cloud-init-local.service @951ms +601ms
                  └─systemd-remount-fs.service @507ms +7ms
                    └─systemd-fsck-root.service @470ms +29ms
                      └─systemd-journald.socket @343ms
                        └─system.slice @209ms
                          └─-.slice @209ms
```

**Comment by townsend2010** [comment]
Ouch, that is taking some time for whatever reason.  This is really outside my area of expertise, but if you want to follow up, I'd ask about it on https://forum.snapcraft.io/c/snapd/5.

That said, this is not really a Multipass problem, so I'm going to close this.  If you disagree or find some other issue, please feel free to reopen or submit a new issue report.

Thanks!
