### ISSUE TITLE
Apple M1 Pro cannot launch instance.

### ISSUE THREAD

**Issue by lvorcool** [canonical/multipass#3167]
**Describe the bug**
1. I executed the command `multipass launch `in the terminal, and the terminal output was almost until the creation was complete to launch the instance, and the computer was restarted.
2. Regardless of any command that creates an instance, the computer restarts when the instance is launched

**Expected behavior**
The instance is created and launched normally, and I can use the instance normally

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/12110444/multipassd.log)

**Additional info**
 - OS: macOS 12.3 
-  multipassd  1.12.2+mac
- `multipass info --all`
```
Name:           masterful-junco
State:          Stopped
IPv4:           --
Release:        --
Image hash:     c8d196b1cdd6 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

- `multipass get local.driver`: qemu

**Additional context**
This is true for both brew and pkg installations

**Comment by luis4a0** [comment]
Hi @lvorcool! I see in the logs many things. One, Multipass is automatically migrating from hyperkit, maybe that process is failing. Other thing is that Multipass cannot access the internet (but this shouldn't be related to your actual issue). I would try with `multipass shell masterful-junco`. Does the computer reboot?

**Comment by luis4a0** [comment]
Moreover, it would be nice if you could provide system logs? They are in file `/var/log/system.log`.

**Comment by lvorcool** [comment]
> Hi @lvorcool! I see in the logs many things. One, Multipass is automatically migrating from hyperkit, maybe that process is failing. Other thing is that Multipass cannot access the internet (but this shouldn't be related to your actual issue). I would try with `multipass shell masterful-junco`. Does the computer reboot?

After I execute the command: `multipass shell masterful-junco`, the computer restarts

**Comment by lvorcool** [comment]
> Moreover, it would be nice if you could provide system logs? They are in file `/var/log/system.log`.

I was 2023 on July 21 at 07:54 when the command was executed, and then the computer rebooted, logging from that time

[system.log](https://github.com/canonical/multipass/files/12114822/system.log)

**Comment by luis4a0** [comment]
Hi @lvorcool, I can't see any anomalies in the system log. Did this happen on a fresh installation of Multipass? Did you upgrade from a previous version? Did you move somehow Multipass from another computer (I am asking this because the fact that the driver was initially set to Hyperkit on an M1 is strange). Thanks!

**Comment by lvorcool** [comment]
> Hi @lvorcool, I can't see any anomalies in the system log. Did this happen on a fresh installation of Multipass? Did you upgrade from a previous version? Did you move somehow Multipass from another computer (I am asking this because the fact that the driver was initially set to Hyperkit on an M1 is strange). Thanks!

The first time I installed multipass on my computer, I found out that creating an instance restarted my computer and asked for help with issue

**Comment by luis4a0** [comment]
Hi @lvorcool, I cannot determine what is going on. There is nothing strange in your logs (despite the driver being set to `hyperkit` at the beginning) and I think something related to QEMU is making your computer reboot. Can you please run the command `/Library/Application\ Support/com.canonical.multipass/bin/qemu-system-aarch64 -machine virt,gic-version=3` and tell me what happened? Does this make your computer restart? Thanks!

**Comment by lvorcool** [comment]
After I upgraded macOS to the latest version 13.4, the problem was solved
