### ISSUE TITLE
Apple M1 Pro cannot start multipass

### ISSUE THREAD

**Issue by iamazy** [canonical/multipass#3168]
**Describe the bug**

I try to start multipass via shortcut but it seems failed. and got error message as follow picture:

![image](https://github.com/canonical/multipass/assets/16559960/913077a3-c8b3-4ca4-a6f1-fc3876834392)

**To Reproduce**
I just upgrade multipass from 1.11.1 to 1.12.1/1.12.2 and got this error

**Expected behavior**
Multipass started and can launch instances.

**Logs**

[multipassd.log](https://github.com/canonical/multipass/files/12117846/multipassd.log)

**Additional info**
 - OS: macOS 12.1
- `multipass version: 1.12.2`
- `multipass info --all: cannot execute this command because multipass startup failed`
- `multipass get local.driver：cannot execute this command because multipass startup failed`

**Additional context**
Both brew and pkg installations show this error message

**Comment by luis4a0** [comment]
Hi @iamazy! From your logs, I see that maybe the disk image is corrupted. Maybe that happened when upgrading, maybe there was an issue with the migration from Hyperkit. Can you please run the following command?
```
qemu-img check /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-22.04-server-cloudimg-arm64.img
```

Thanks!

**Comment by luis4a0** [comment]
Can't you run `sudo`? What's the error it is showing? What does `ls -la /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/` give?

**Comment by luis4a0** [comment]
Maybe you should try with
```sudo qemu-img check "/var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-22.04-server-cloudimg-arm64.img"```

**Comment by luis4a0** [comment]
Yeah, the image is indeed corrupted. If you can drop the instance, you can just do `multipass delete --purge primary` and then create a new one using the `multipass launch` command.
