### ISSUE TITLE
mutiple netwrok card combine with VPP/DPDK

### ISSUE THREAD

**Issue by BurlyLuo** [canonical/multipass#3170]
**Describe the bug**
Set the local.driver into lxd to support the mutiple network card. but once install the dpdk/vpp. and bind the nic into dpdk. when we set the interface at vpp level, the vm is stopped. 

**To Reproduce**
vm stop
1. `multipass ...`
```

root@2004:~# mm set local.driver=lxd
root@2004:~# 



root@m1:~/dpdk/usertools# vppctl 
    _______    _        _   _____  ___ 
 __/ __/ _ \  (_)__    | | / / _ \/ _ \
 _/ _// // / / / _ \   | |/ / ___/ ___/
 /_/ /____(_)_/\___/   |___/_/  /_/    

vpp# show interface 
              Name               Idx    State  MTU (L3/IP4/IP6/MPLS)     Counter          Count     
enp6s0                            1     down         9000/0/0/0     
local0                            0     down          0/0/0/0       
vpp# 
vpp# 
vpp# set interface enp6s0 up
set interface: unknown input `enp6s0 up'
vpp# 



"/etc/vpp/startup.conf" 264L, 7361C written                                       
root@m1:~/dpdk/usertools# ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 52:54:00:7b:ae:44 brd ff:ff:ff:ff:ff:ff
    inet 10.199.21.201/24 brd 10.199.21.255 scope global dynamic enp5s0
       valid_lft 2970sec preferred_lft 2970sec
    inet6 fd42:4b1:e518:c3fe:5054:ff:fe7b:ae44/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe7b:ae44/64 scope link 
       valid_lft forever preferred_lft forever
root@m1:~/dpdk/usertools# ./dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:06:00.0 'Virtio network device 1041' drv=vfio-pci unused=

Network devices using kernel driver
===================================
0000:05:00.0 'Virtio network device 1041' if=enp5s0 drv=virtio-pci unused=vfio-pci *Active*

No 'Baseband' devices detected
==============================

```

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
 - Ubuntu 20.04
- `multipass version`
- 1.12
- `multipass info --all`
- NA
- `multipass get local.driver`
lxd
**Additional context**

**Comment by BurlyLuo** [comment]
@andrei-toterman  thanks for the reply.
i suspect it's not related with multipass as well. but with the lxd driver itself. 
but at the OpenStack based vm, which the network card driver is also virtio-pci Red Hat, Inc. Virtio network device. but it can be run this vpp/dpdk successfully. 
so, do you think there is differences btw the 2 environments?
i am not sure, so sorry pool knowledge.

**Comment by andrei-toterman** [comment]
Unfortunately I cannot help you in this case, as I don't have a lot of knowledge about OpenStack or vpp/dpdk. If you think this is an issue within LXD, I suggest that you should open an issue with them. But it might as well be just a difference in configuration, which could be achieved in LXD as well. Nevertheless, I don't think it's pertinent to Multipass itself, so I will close this issue now. Best of luck with your goal!
