### ISSUE TITLE
This is an exact duplicate of https://github.com/canonical/multipass/issues/71 that was never solved or resolved

### ISSUE THREAD

**Issue by dbline** [canonical/multipass#3174]
**Describe the bug**
Some git commands do not work on a fuse.sshfs mounted folder inside a multipass instance:

I'm getting the exact same thing.  On the host it works, on the VM on the internal vhd it works.  Doesn't work on folders in mount.

**To Reproduce**
make some local folders and some folders on the mounted drive and run some advanced git clones.  They generate tons of Operation not permitted  erros

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - Window 11 new enough
- `multipass version latest version .70 I think`
- `multipass info --all`
PS C:\Users\dblin> multipass info --all
Name:           dtest3
State:          Running
IPv4:           172.30.102.155
                172.17.0.1
                172.18.0.1
Release:        Ubuntu 22.04.2 LTS
Image hash:     d699ae158ec0 (Ubuntu 22.04 LTS)
CPU(s):         8
Load:           0.20 0.32 0.18
Disk usage:     35.6GiB out of 48.4GiB
Memory usage:   4.7GiB out of 11.7GiB
Mounts:         C:/Users/dblin/multipass/dtest3 => dtest3
                    UID map: -2:default
                    GID map: -2:default
                C:/Users/dblin/multipass/tsj    => ~/tsj
                    UID map: -2:default
                    GID map: -2:default

Name:           dtest4
State:          Running
IPv4:           172.30.105.162
                172.19.0.1
                172.17.0.1
Release:        Ubuntu 22.04.2 LTS
Image hash:     d699ae158ec0 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.00 0.00 0.00
Disk usage:     8.7GiB out of 38.7GiB
Memory usage:   323.1MiB out of 3.8GiB
Mounts:         C:/Users/dblin/multipass/dtest4 => dtest4
                    UID map: -2:default
                    GID map: -2:default
                C:/Users/dblin/multipass/tsj    => ~/tsj
                    UID map: -2:default
                    GID map: -2:default

- `multipass get local.driver`  = hyperv

**Additional context**
AOther than these git commands, these mounts work AMAZINGLY well!  I am very impressed.   Cross mounting volumes for docker through these volumes works and works fast!  big db's, redis.  Everything seems to be good, except git

Thank you for your time and consideration.  Those "-2"''s in the UID and GID have me on the hunt again for possible solutions.

being able to use git on shared volumes from the host on multipass instances is pretty important to the workflow I want to create.

**Comment by andrei-toterman** [comment]
Hi, @dbline! Thanks for reporting this! Can you please give me a concrete example of what actions result in 'Operation not permitted'? The only one I managed to get is of the form `warning: unable to unlink '/home/ubuntu/.../.git/objects/pack/...': Operation not permitted`, but I'd like to know if you are encountering others

**Comment by dbline** [comment]
Hello!

Thank you so much for looking at this.  You have found the most common error I am seeing too.  That "unlinking the pack temporary file"  error.

Other things I am noticing:

I have noticed that I can't completely remove the repo from the VM side using "rm -rf".  A bunch of files and folders inside the ".git" folder are showing that they are 'read only' and therefore, I can't delete them.  If I go in and blanket chmod those folders to make them r/w again, then I can remove them with no problem.

Another place it is showing is when I build docker containers.  If I build my dev env using a folder on the vm's own vxhd storage, everything works great!  If I build in the fuse.sshfs mounted folder, I end up with containers with permission problems too.  e.g. there is an executable script file copied into the container to set up the db schemas. That script file ends up _not_ having the executable permission, so I can't launch the script inside my running container.  Same thing if I bash into the container and chmod the file to get it executable again, then it starts working.  The containers build and launch fine, they just don't end up exactly the same internally when they are built using the two types of possible starting folders - fuse vs. vxhd(?)

I'm still poking at it today trying to pin it down a little more.   I read something last night about my multipass VM user (ubuntu) possibly not being a "sudoer" maybe?  I'm going to try that next.    I need to read up on that a little more.

I really, really appreciate you taking a look.  I'm always scared to ask because I feel I'm not in the same league as the incredibly talented people around here.  So it means a lot to me to get a reply at all.  I mean that.

DL

**Comment by andrei-toterman** [comment]
Hey, @dbline! No need to be scared, we're all just ordinary humans at the end of the day and we promise to do our best to help our dear users :)

Indeed, there is a big issue with the removal of read-only files. There's nothing wrong with your user, you really should be able to delete those files. After some experimentation, I concluded that it's a bug in our code, that stems from the Qt filesystem functions. However, the functions from `std::filesystem` seem to behave better. We've been discussing for a long time to change our code from using Qt filesystem functions in favor of the standard library ones, so this is just another big reason to do so. 

Thanks for giving me more details, they were definitely helpful!

**Comment by dbline** [comment]
Fantastic!

Now I can stop trying to figure out what I am doing wrong and focus on a workaround until this gets resolved.

I've learned how to get around it for the time being by doing some extra scripting to force the permissions to be what they need to be to get things done.

Awesome product, thank you so much!

DL
