### ISSUE TITLE
Mild security bug? Some writes in multipass to sshfs filesystem can have any userid the VM specifies.

### ISSUE THREAD

**Issue by owainkenwayucl** [canonical/multipass#3179]
Host: MacOS 13.5, ARM
VM: "Primary", Ubuntu 22.04
Multipass version info: 1.12.2+mac

My "Primary" multipass VM mounts `~/Shared` on my Mac rather than `~` because giving a VM access to my entire home directory feels unclean.  Anyway, `~/Shared` is mounted as `~/Shared` in the VM:

```
Mounts:         /Users/uccaoke/Shared => /home/ubuntu/Shared
                    UID map: 501:default
                    GID map: 20:default
```

My userid on the Mac is `uccaoke` (`501`) and my userid on the Ubuntu VM is `ubuntu` (`1000`).  I was tidying up some files in `~/Shared` on my Mac last night and notices that some of them were owned by `1000`.

All the files that were like this were `.gz` files and this made an easy test case.

In Ubuntu:

```
ubuntu@primary:~/Shared$ id
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),119(netdev),120(lxd)
ubuntu@primary:~/Shared$ touch test
ubuntu@primary:~/Shared$ gzip -k test
```

And then on the host Mac:

```
 ~/Shared ☛ ls -lah test*
-rw-rw-r--  1 uccaoke  staff     0B 28 Jul 18:52 test
-rw-rw-r--  1 1000     staff    25B 28 Jul 18:52 test.gz
```

As you can see, reproducibly, writing files with `gzip` in the VM creates a file on the host with numeric owner with the UID of `1000`.

Next of course, I was interested to see if this also happened if I were `root` in a VM as that would be quite bad:

```
ubuntu@primary:~/Shared$ sudo su -
root@primary:~# cd ~ubuntu/Shared/
root@primary:/home/ubuntu/Shared# touch rtest
root@primary:/home/ubuntu/Shared# gzip -k rtest
```

On the host:
```
 ~/Shared ☛ ls -lah rtest*
-rw-r--r--  1 uccaoke  staff     0B 28 Jul 18:57 rtest
-rw-r--r--  1 1000     staff    26B 28 Jul 18:57 rtest.gz
```

That's good at least, it means it's picking up the UID of 1000 from somewhere else.

On the VM there's some definite weirdness going on:

```
root@primary:/home/ubuntu/Shared# id
uid=0(root) gid=0(root) groups=0(root)
root@primary:/home/ubuntu/Shared# ls -lah rtest*
-rw-r--r-- 1 ubuntu ubuntu  0 Jul 28 18:57 rtest
-rw-r--r-- 1 ubuntu ubuntu 26 Jul 28 18:57 rtest.gz
```

Oh dear, what happens if we chown the file to root inside the VM?

On the VM:

```
root@primary:/home/ubuntu/Shared# chown root rtest
```

On the Mac:

```
~/Shared ☛ ls -lah rtest*
-rw-r--r--  1 root  staff     0B 28 Jul 18:57 rtest
-rw-r--r--  1 1000  staff    26B 28 Jul 18:57 rtest.gz
```

This seems potentially quite bad?  I haven't tested things like setuid bits but...

**Comment by townsend2010** [comment]
Hi @owainkenwayucl!

Thanks for pointing this out.  There is indeed a bug in our reverse mapping from the instance to the host.  That said, there are a few things that somewhat mitigate the severity of this in that the user needs to be part of the `wheel` group (ie equivalent to an admin on the Mac) **OR** the user needs to be provided a passphrase that is set via `multipass set local.passphrase` and then the user needs to [authenticate](https://multipass.run/docs/authenticating-clients) with the daemon/service.

That said, I think we can do a little better with some of these concerning issues and so we'll plan on addressing them soon-ish.
