### ISSUE TITLE
Offer option of monochrome toolbar icon on macOS

### ISSUE THREAD

**Issue by eccgecko** [canonical/multipass#3183]
**What are you trying to do?**
I tried to change the icon color of the Multipass icon in the macOS toolbar

**What's your proposed solution?**
I believe Multipass should offer the option of a monochrome icon for the macOS toolbar

**Additional context**
All my other icons, for both first- and third-party applications, are monochrome, with the vast majority of macOS applications offering this as an option. I believe Multipasss should also offer this for visual consistency as I find the sole bright orange icon quite distracting.

**Comment by georgeliao** [comment]
Hi @eccgecko , thanks for your nice proposal. We already have another issue covers this, https://github.com/canonical/multipass/issues/2675
