### ISSUE TITLE
Multipass 1.11.1+mac for macOS "steals" shortcut from Chrome

### ISSUE THREAD

**Issue by commadelimited** [canonical/multipass#3187]
**Describe the bug**
When multipass is running it "steals" the keyboard shortcut **View Page Source** from Chrome (Option + Command  + U) to launch the shell. If I shut down multipass the keyboard shortcut works as expected.

<img width="428" alt="image" src="https://github.com/canonical/microk8s/assets/563460/65de23d3-7846-441a-aac6-40cf86ade74a">

**To Reproduce**
* Open Chrome
* Press Option + Command  + U

**Expected behavior**
I expected View Source to launch

**Logs**
n/a

**Additional info**
 - OS: 12.6.5
 - Chrome: Version 115.0.5790.114
- `multipass version`
```
multipass   1.11.1+mac
multipassd  1.11.1+mac

#########################################################################################
Multipass 1.12.2 release
Fix regession on macOS with hanging clients

Go here for more information: https://github.com/canonical/multipass/releases/tag/v1.12.2
#########################################################################################
```

- `multipass info --all`
```
multipass info --all
Name:           microk8s-vm
State:          Running
IPv4:           192.168.106.3
                10.0.1.1
                10.1.254.64
Release:        Ubuntu 20.04.6 LTS
Image hash:     9f050b53e08c (Ubuntu 20.04 LTS)
CPU(s):         6
Load:           9.29 8.25 7.98
Disk usage:     18.7GiB out of 61.8GiB
Memory usage:   3.9GiB out of 24.5GiB
Mounts:         /Users/andymatthews/TA => /Users/andymatthews/TA
                    UID map: 503:default
                    GID map: 20:default
```
- `multipass get local.driver`: hyperkit

**Additional context**
No other information

**Comment by Saviq** [comment]
@commadelimited you can change it with e.g. `multipass set client.gui.hotkey=Ctrl+Alt+M` if you like. Or set to empty to disable.

https://multipass.run/docs/gui-hotkey

**Comment by commadelimited** [comment]
@Saviq that's great, thank you.
