### ISSUE TITLE
purge failed: cannot connect to the multipass socket

### ISSUE THREAD

**Issue by cctv130** [canonical/multipass#3191]
**Describe the bug**
purge failed: cannot connect to the multipass socket

**To Reproduce**
How, and what happened?
1. install multipass
2. run multipass launch
3. shutdown host and then executive multipass command

**Expected behavior**
Unable to execute all multipass commands

**Logs**
purge failed everywhere: cannot connect to the multipass socket

**Additional info**
 - OS: windows10 22H2
- `multipass latest`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**
null

**Comment by cctv130** [comment]
I found that the multipass service is stopped, when I manually start the service, and then execute multipass list command, the service will automatically shut down again

**Comment by cctv130** [comment]
After investigation, I found the problem, it was my storage location setting is wrong, but there is a new error.

PS C:\Windows\system32> multipass launch
launch failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.

**Comment by luis4a0** [comment]
Hi @cctv130! What happens if you use `multipass authenticate`? Thanks!

**Comment by luis4a0** [comment]
Hi @cctv130, your issue is related to changing the storage location. We are working in a fix to that. In the meantime, you'll need to copy the credentials from `C:\ProgramData\Multipass` to your new storage location. Does this work? Thanks!

**Comment by cctv130** [comment]
> Hi @cctv130, your issue is related to changing the storage location. We are working in a fix to that. In the meantime, you'll need to copy the credentials from `C:\ProgramData\Multipass` to your new storage location. Does this work? Thanks!

Sorry, I don't have much time to test now, I have replaced vmware
