### ISSUE TITLE
Attempting to set driver to 'hyperv' 

### ISSUE THREAD

**Issue by amryounis** [canonical/multipass#3196]
**Describe the bug**
Windows installer takes very long time at "Attempting to set driver to 'hyperv' " step

**To Reproduce**
try to install it on windows

**Expected behavior**
normal install timeframe

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Windows 11
multipass cli is not responsive, considering the install did not finish

**Additional context**
I have WSL 2 active

**Comment by amryounis** [comment]
Output folder: C:\Program Files\Multipass
Output folder: C:\Program Files\Multipass\bin
Extract: Qt5Core.dll... 100%
Extract: Qt5Gui.dll... 100%
Extract: Qt5Network.dll... 100%
Extract: dbghelp.dll... 100%
Extract: libcrypto-1_1-x64.dll... 100%
Extract: libssl-1_1-x64.dll... 100%
Extract: multipass.exe... 100%
Extract: multipass_wt.ico... 100%
Extract: ssh.dll... 100%
Output folder: C:\Program Files\Multipass\fonts
Extract: UBUNTU-LICENCE.txt... 100%
Extract: UbuntuMono-R.ttf... 100%
Output folder: C:\Program Files\Multipass
Output folder: C:\Program Files\Multipass
Output folder: C:\Program Files\Multipass\bin
Extract: Qt5Core.dll... 100%
Extract: Qt5Gui.dll... 100%
Extract: Qt5Network.dll... 100%
Extract: Qt5Widgets.dll... 100%
Extract: dbghelp.dll... 100%
Extract: libcrypto-1_1-x64.dll... 100%
Extract: libssl-1_1-x64.dll... 100%
Extract: multipass.gui.exe... 100%
Extract: ssh.dll... 100%
Output folder: C:\Program Files\Multipass\bin\platforms
Extract: qwindows.dll... 100%
Output folder: C:\Program Files\Multipass
Output folder: C:\Program Files\Multipass
Output folder: C:\Program Files\Multipass\bin
Extract: PocoFoundation.dll... 100%
Extract: PocoZip.dll... 100%
Extract: Qt5Core.dll... 100%
Extract: Qt5Gui.dll... 100%
Extract: Qt5Network.dll... 100%
Extract: concrt140.dll... 100%
Extract: dbghelp.dll... 100%
Extract: libbrotlicommon.dll... 100%
Extract: libbrotlidec.dll... 100%
Extract: libbrotlienc.dll... 100%
Extract: libbz2-1.dll... 100%
Extract: libcrypto-1_1-x64.dll... 100%
Extract: libcrypto-3-x64.dll... 100%
Extract: libcurl-4.dll... 100%
Extract: libffi-8.dll... 100%
Extract: libgcc_s_seh-1.dll... 100%
Extract: libglib-2.0-0.dll... 100%
Extract: libgmp-10.dll... 100%
Extract: libgnutls-30.dll... 100%
Extract: libhogweed-6.dll... 100%
Extract: libiconv-2.dll... 100%
Extract: libidn2-0.dll... 100%
Extract: libintl-8.dll... 100%
Extract: libnettle-8.dll... 100%
Extract: libnfs-14.dll... 100%
Extract: libp11-kit-0.dll... 100%
Extract: libpcre2-8-0.dll... 100%
Extract: libpsl-5.dll... 100%
Extract: libssh.dll... 100%
Extract: libssh2-1.dll... 100%
Extract: libssl-1_1-x64.dll... 100%
Extract: libssp-0.dll... 100%
Extract: libtasn1-6.dll... 100%
Extract: libunistring-5.dll... 100%
Extract: libwinpthread-1.dll... 100%
Extract: libzstd.dll... 100%
Extract: msvcp140.dll... 100%
Extract: msvcp140_1.dll... 100%
Extract: msvcp140_2.dll... 100%
Extract: msvcp140_atomic_wait.dll... 100%
Extract: msvcp140_codecvt_ids.dll... 100%
Extract: multipassd.exe... 100%
Extract: qemu-img.exe... 100%
Extract: ssh.dll... 100%
Extract: sshfs_server.exe... 100%
Extract: vcruntime140.dll... 100%
Extract: vcruntime140_1.dll... 100%
Extract: zlib1.dll... 100%
Output folder: C:\Program Files\Multipass
Output folder: C:\Program Files\Multipass
Created uninstaller: C:\Program Files\Multipass\Uninstall.exe
Set install registry entry: 'DisplayName' to 'Multipass'
Set install registry entry: 'DisplayVersion' to '1.12.2+win'
Set install registry entry: 'Publisher' to 'canonical'
Set install registry entry: 'UninstallString' to 'C:\Program Files\Multipass\Uninstall.exe'
Set install registry entry: 'NoRepair' to '1'
Set install registry entry: 'NoModify' to '1'
Set install registry entry: 'DisplayIcon' to 'C:\Program Files\Multipass\'
Set install registry entry: 'HelpLink' to 'https://github.com/CanonicalLtd/multipass'
Set install registry entry: 'URLInfoAbout' to 'https://github.com/CanonicalLtd/multipass'
Set install registry entry: 'DoNotAddToPath' to '0'
Set install registry entry: 'AddToPathAllUsers' to '0'
Set install registry entry: 'AddToPathCurrentUser' to '1'
Set install registry entry: 'InstallToDesktop' to '0'
[trace] [client cert store] Loading client certs from C:/ProgramData/Multipass/data/authenticated-certs
[trace] [client cert store] Adding cert:
-----BEGIN CERTIFICATE-----
***
-----END CERTIFICATE-----

"Daemon install result: 0"
Copy to C:\WINDOWS\Fonts
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Multipass.lnk
Checking if Hyper-V is enabled
Enabling Hyper-V
Attempting to set driver to 'hyperv'

**Comment by amryounis** [comment]
![image](https://github.com/canonical/multipass/assets/3895133/7805d2a7-ad72-43e4-9058-3597fab2cebf)
time stamp now is 4:14 am

**Comment by amryounis** [comment]
After like a couple of hours I had to kill the installer. During installation, the installer created and started the multipass daemon.
I had to launch the uninstaller to remove the app but again it was stuck for very long time. I came to know that it was because of the daemon as the uninstaller could not stop it which I had to do it myself manually.

I suspect the RCA is having WSL active in my computer.

I had two encounters when I needed to have a VM instead of the WSL layer, which I kept for its agility.

1- When tried to install VBOX. the installer finished in a very smooth way but I could not start any VM. Later and after a lengthy search I discovered that both technologies cannot exist. Oracle did not publish anything about the issue, all are efforts from desperate users

2- I switched to VMware Player. During the install, the installer warned me that I have to disable WSL as both cannot coexist.

and here is the third scenario from multipass, the installer was stuck in the mud

**Comment by luis4a0** [comment]
Hi @amryounis, thanks for the report and for your investigation. Multipass and WSL can coexist, so the problem does not come from there. It seems the daemon got stuck somehow when the client tried to set the driver to Hyper-V. I would suggest to retry the installation and try to capture the logs as described [here](https://multipass.run/docs/accessing-logs#heading--windows). If it fails again, please send us the logs, so we can inspect better what's happening. Thanks!

**Comment by amryounis** [comment]
Hi @luis4a0, Thank you for your reply. Here are the logs. I found that there was a complain about PowerShell and yes it is disabled as a company policy. I also removed some sensitive data from the logs. Thank you.
[mutlipassLogs.zip](https://github.com/canonical/multipass/files/12384997/mutlipassLogs.zip)

**Comment by luis4a0** [comment]
Hi @amryounis, we do use PowerShell to manage Hyper-V. If you can't make PowerShell work, then you'll have to try with VirtualBox, but I'm afraid it will clash with WSL and won't work. I'm closing the ticket, feel free to reopen if you have more questions. Thanks!

**Comment by amryounis** [comment]
thank you indeed. This is confirm that switching to vbox did not work as well for the same reason.
