### ISSUE TITLE
postinstall script does not support brew in apple silicon

### ISSUE THREAD

**Issue by gnzsnz** [canonical/multipass#3199]
**Describe the bug**
postinstall script does not support brew in apple silicon. $(brew --prefix) is /opt/homebrew for homebrew in arm64. bash completion is not installed due to this. see https://github.com/Homebrew/homebrew-cask/issues/153333#issuecomment-1685125173

**To Reproduce**
How, and what happened?
1. install multipass with brew in arm64
2. bash completion not installed

**Expected behavior**
bash completion should be installed

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: macOS / brew arm64 architecture

**Comment by sharder996** [comment]
Hi @gnzsnz, thanks for bringing this up! A fix has been submitted and should make its way into the 1.13 release.
