### ISSUE TITLE
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.

### ISSUE THREAD

**Issue by sincorchetes** [canonical/multipass#3200]
**Describe the bug**
I cannot create a new vm.

**To Reproduce**
How, and what happened?
1. microk8s install --cpu 2 --mem 10

**Expected behavior**
Works (?)

**Logs**
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: The following errors occurred:
microk8s-vm: timed out waiting for response
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
launch failed: instance "microk8s-vm" already exists
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.

**Additional info**
 - OS: 13.4.1 (c)
- multipass   1.12.2+mac
- multipassd  1.12.2+mac
- `multipass info --all`
```
Name:           microk8s-vm
State:          Unknown
IPv4:           --
Release:        --
Image hash:     9c59c6097711 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver`: qemu

**Additional context**
An opened issue in microk8s git repo here: https://github.com/canonical/microk8s/issues/4154

**Comment by sharder996** [comment]
Hi @sincorchetes! It seems you already have a vm named `microk8s-vm`, but is in an unknown state. 

> `launch failed: instance "microk8s-vm" already exists`

From the logs I can't say why it's in that state, but you can try `multipass delete --purge microk8s-vm` to get rid of the existing vm so that you can create a new one with the same name.

**Comment by sincorchetes** [comment]
> Hi @sincorchetes! It seems you already have a vm named `microk8s-vm`, but is in an unknown state.
> 
> > `launch failed: instance "microk8s-vm" already exists`
> 
> From the logs I can't say why it's in that state, but you can try `multipass delete --purge microk8s-vm` to get rid of the existing vm so that you can create a new one with the same name.

Hi! I replayed these commands but I got the same result.

microk8s uninstall
multipass delete --all
multipass purge
microk8s install --cpu 2 --mem 10

Same results.

**Comment by sharder996** [comment]
It seems you are confusing `microk8s` and `multipass` commands. If you want a vm with microk8s installed on it, you will need to first launch a vm through multipass; ie. `multipass launch`, and then install microk8s on that vm.

I suggest giving this tutorial a read: 

https://microk8s.io/docs/install-multipass

**Comment by sincorchetes** [comment]
> It seems you are confusing `microk8s` and `multipass` commands. If you want a vm with microk8s installed on it, you will need to first launch a vm through multipass; ie. `multipass launch`, and then install microk8s on that vm.
> 
> I suggest giving this tutorial a read:
> 
> https://microk8s.io/docs/install-multipass

Hello @sharder996 ,

You're right after perform: 

multipass launch --name microk8s-vm --mem 4G --disk 40G

It's working. I can manage the K8s perfectly.

**Comment by asksmruti** [comment]
> It seems you are confusing `microk8s` and `multipass` commands. If you want a vm with microk8s installed on it, you will need to first launch a vm through multipass; ie. `multipass launch`, and then install microk8s on that vm.
> 
> I suggest giving this tutorial a read:
> 
> https://microk8s.io/docs/install-multipass

I am getting the same error while running `microk8s install` 
Trying to run microk8s on MacOS (macOS 13.5.1 / M1)
Steps followed here -  https://microk8s.io/docs/install-macos

**Comment by sharder996** [comment]
Hi @asksmruti, the tutorial you have linked is a guide for installing microk8s, not Multipass. If you are experiencing a problem specifically with Multipass, I would recommend you open a new github issue and fill out the required information so we are better able to diagnose the problem.
