### ISSUE TITLE
port forwarding redirect thru internet modem to Multipass instance hangs in ubuntu 

### ISSUE THREAD

**Issue by BainMcKay** [canonical/multipass#3210]
**Describe the bug**
Describe what your problem is.
On host, M1 Mac Studio Ultra, MacOS Ventura ,I create a Multipass instance using network with an apache default site. I provide the ports forwarded in ports.conf, the Netplan for the IP is autogenerated, the  ufw allow port, and the site adaptors, listening for for the port forwarded. On macOS, I map the port forward IP to the assigned IP by the router (else multipass does not see it). I use TCP dump to verify that the port is seen forwarding the request on macOS, and on Multi[pass Ubuntu instance. I use curl to see that the subdomain redirect is doing the port forward as seen in ubuntu.  The site hangs on the http request

Full Sructured Report Attached

**Comment by BainMcKay** [comment]
It's hanging, even after I added the patch for client hanging

The attached ZIP has the formatted report

**Comment by ricab** [comment]
Hi @BainMcKay. I can't find any attachments, did you forget them?

I am unable to picture your setup consistently, but ports.conf, netplan, ufw, site adaptors, port forwarding... those are all outside the scope of Multipass.

In any case, assuming you got your setup right and your instances are getting public IPs, we do have [another bug report](https://github.com/canonical/multipass/issues/3038) where a TCP issues causes HTTP to hang. Does it match what you are observing?

**Comment by BainMcKay** [comment]
I'll try to add the
[issue_report_Multipass.zip](https://github.com/canonical/multipass/files/12468831/issue_report_Multipass.zip)
 ZIP again

**Comment by ricab** [comment]
Hi @BainMcKay, your scenario seems similar to #3038. Does it hang when you request both small and large files?
