### ISSUE TITLE
Multipass breaks VirtualBox VMs, they fail with `Guru Meditation -37 (VERR_NOT_SUPPORTED)`

### ISSUE THREAD

**Issue by AndersonQ** [canonical/multipass#3212]
**Describe the bug**
After installing multipass and starting a multipass VM aall my VirtualBox VMs could not start anymore. All failing, going to `Guru Meditation` state.

**To Reproduce**
 - Having VirtualBox (`Oracle VM VirtualBox VM Selector v7.0.10` or `Oracle VM VirtualBox VM Selector v7.0.8_Ubuntu`) installed
 - install `snapd` and `multipass`
 - have no VirtualBox VM running
 - start a multipass VM
 - Try to start any VM on VirtualBox, either new or an existing one, directly through VirtualBox or Vagrant
 - VirtualBox VMs fail, going to `Guru Meditation` state.
 - Stop multipass VM
 - VirtualBox VMs still fail going to `Guru Meditation` state.

I solved the issue by purging (`snap remove --purge multipass`) multipass. After that, my virtualbox VMs start normally.

**Expected behavior**
VirtualBox VMs should still work after installing and using multipass

**Logs**
VietualBox logs:
```
00:00:00.308870 VMEmt: Halt method global1 (5)
00:00:00.309002 VMEmt: HaltedGlobal1 config: cNsSpinBlockThresholdCfg=2000
00:00:00.309349 Changing the VM state from 'CREATING' to 'CREATED'
00:00:00.312747 SharedFolders host service: Adding host mapping
00:00:00.312787     Host path '/home/user/devel/github.com/elastic/elastic-agent', map name 'vagrant', writable, automount=false, automntpnt=, create_symlinks=true, missing=false
00:00:00.313093 Changing the VM state from 'CREATED' to 'POWERING_ON'
00:00:00.313184 AIOMgr: Endpoints without assigned bandwidth groups:
00:00:00.313188 AIOMgr:     /home/user/VirtualBox VMs/elastic-agent_elastic-agent_1693228588014_89803/ubuntu-jammy-22.04-cloudimg-configdrive.vmdk
00:00:00.313190 AIOMgr:     /home/user/VirtualBox VMs/elastic-agent_elastic-agent_1693228588014_89803/ubuntu-jammy-22.04-cloudimg.vmdk
00:00:00.313298 Changing the VM state from 'POWERING_ON' to 'RUNNING'
00:00:00.313303 Console: Machine state changed to 'Running'
00:00:00.313473 Changing the VM state from 'RUNNING' to 'GURU_MEDITATION'
00:00:00.313485 Console: Machine state changed to 'Stuck'
00:00:00.313600 VBoxHeadless: starting event loop
00:00:00.315305 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
00:00:00.315305 !!
00:00:00.315305 !!         VCPU0: Guru Meditation -37 (VERR_NOT_SUPPORTED)
00:00:00.315307 !!
00:00:00.315311 !!
00:00:00.315311 !! {mappings, <NULL>}
00:00:00.315311 !!
00:00:00.315315 !!
00:00:00.315315 !! {hma, <NULL>}
00:00:00.315315 !!
00:00:00.315316 !!
00:00:00.315316 !! {cpumguest, verbose}
00:00:00.315316 !!
```
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: 
```
pop_OS!

Linux mycomputer 6.4.6-76060406-generic #202307241739~1690928105~22.04~d567a38 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux
```

- `multipass version`:
```
multipass   1.12.2
multipassd  1.12.2
```

- `multipass info --all`: no output:
```
❯ multipass info --all

❯
```

- `multipass get local.driver`: 
```
qemu
```

**Additional context**

I saw that if I have a runnign VirtualBox VM multipass does not start. But it seems even stopping the multipass VMs and closing the applet isn't enought to "stop" multipass or undo what ever multipass does when starting a VM that prevents VirtualBox from working.

**Comment by ricab** [comment]
Hi @AndersonQ, I am afraid KVM and VirtualBox conflict, and there isn't much we can do about that. Your surest bet is to choose one or the other at any one time. However, some claim that you can [use them simultaneously](https://askubuntu.com/questions/413511/can-virtualbox-and-kvm-run-alongside-each-other) with special tinkering or by performing operations in specific orders. Let us know if any of that works for you!

I am going to close now, but please reopen if you think there is anything left for Multipass to do.
