### ISSUE TITLE
The ros-noetic blueprint is misconfigured

### ISSUE THREAD

**Issue by binitshah** [canonical/multipass#3218]
**Describe the bug**
I found [this tutorial](https://ubuntu.com/blog/ros-development-on-linux-windows-and-macos) about running ROS through multipass, and I tried running the `ros-noetic` blueprint. It launches correctly, but seems to be misconfigured. None of the ROS CLI or catkin tools are available from the command line. Looking in the `.bashrc`, it can't seem to source `/opt/ros/noetic/setup.bash` since the `/opt/ros` directory is missing.

**To Reproduce**
How, and what happened?
1. `multipass launch -n noetic-vm ros-noetic`
1. `multipass shell noetic-vm`
1. `$ echo $ROS_DISTRO` will be empty. None of the ROS CLI is present.

**Expected behavior**
I expected to see ROS Noetic configured and ready to use.

**Additional info**
 - OS: Ubuntu 22.04
- `multipass version`
```
multipass   1.12.2
multipassd  1.12.2
```
- `multipass info --all`
```
Name:           noetic-vm
State:          Running
IPv4:           10.44.212.208
Release:        Ubuntu 20.04.6 LTS
Image hash:     5e8c2914c5f0 (Ubuntu 20.04 LTS)
CPU(s):         2
Load:           0.00 0.00 0.00
Disk usage:     2.0GiB out of 38.7GiB
Memory usage:   191.3MiB out of 3.8GiB
Mounts:         --
```
- `multipass get local.driver`
```
qemu
```

**Comment by townsend2010** [comment]
Hey @artivis and @GAN-Canonical,

Could you please help with this?  Thanks!

**Comment by artivis** [comment]
I just gave this a shot and the blueprint works as expected. Something must have failed during the initialisation,
@binitshah could you please past the output of the following commands,

- `cat /var/log/cloud-init-output.log` 
- `cat /var/log/cloud-init.log`

**Comment by townsend2010** [comment]
I'm going to close this as there has been no follow up.  Please reopen if there is more info to provide.  Thanks!
