### ISSUE TITLE
Directly delete and purge will cause snap.multipass.multipassd.service abnormal

### ISSUE THREAD

**Issue by BurlyLuo** [canonical/multipass#3231]
**Describe the bug**
Describe what your problem is.
```
root@2204:~/wcni-kind/split# mm delete cc --purge
root@2204:~/wcni-kind/split# mls
list failed: cannot connect to the multipass socket
root@2204:~/wcni-kind/split# mls
list failed: cannot connect to the multipass socket
root@2204:~/wcni-kind/split# 
root@2204:~/wcni-kind/split# 
root@2204:~/wcni-kind/split# systemctl list-units | grep mul
  run-snapd-ns-multipass.mnt.mount                                                                         loaded active       mounted      /run/snapd/ns/multipass.mnt
  snap-multipass-10167.mount                                                                               loaded active       mounted      Mount unit for multipass, revision 10167
  snap-multipass-10244.mount                                                                               loaded active       mounted      Mount unit for multipass, revision 10244
  snap.multipass.multipassd.service                                                                        loaded deactivating stop-sigterm Service for snap applicationmultipass.multipassd
  multi-user.target                                                                                        loaded active       active       Multi-User System
root@2204:~/wcni-kind/split# systemctl restart snap.multipass.multipassd.service 
```

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**

**Comment by townsend2010** [comment]
Hi @BurlyLuo!

Sorry for you troubles.  We've not observed this nor have we seen any other reports of this nature.  Could you please provide [logs](https://multipass.run/docs/accessing-logs) so we can help diagnose your issue?  Thanks!

**Comment by BurlyLuo** [comment]
> Hi @BurlyLuo!
> 
> Sorry for your troubles. We've not observed this nor have we seen any other reports of this nature. Could you please provide [logs](https://multipass.run/docs/accessing-logs) so we can help diagnose your issue? Thanks!

Sure.
[multipass.log](https://github.com/canonical/multipass/files/12659992/multipass.log)

**Comment by BurlyLuo** [comment]
Any update
