### ISSUE TITLE
Problems with multipass commands

### ISSUE THREAD

**Issue by Luca007** [canonical/multipass#3236]
So I started using multipass and it was working fine, but a few days ago, when I tried using multipass to open my intances I had an issue. No multipass commands are working. I have tryed to start multipass manualy and fron there tried to open my instance shell, but it didi`t worked to. I have tried unintalling multipass files and ecven tried to verify if tehre were any corrupted files, but found nothing.

**To Reproduce**
I tried to use this command to find the multipass intance path to make a backup copy of my instance, and that how it started:

multipass list --format csv | findstr "Running" | for /f "tokens=2 delims=," %i in ('findstr /i "Running"') do @echo %i

**Expected behavior**
I expected that it wold give me the path for the running instances.

**Logs**
I have reintalled all multipass files to try to solve the probleme, so I can`t find any logs

**Additional info**
 - `OS: Windows 10 pro`
- `multipass version: 1.12.2+win`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**
![image](https://github.com/canonical/multipass/assets/16074255/13e311e0-1edc-4c88-a2f8-352f3b10bbad)

My starting idea was to make a backup file of my instance, but I could not find the instance paths (I have checked all multipass files and I have surched the internet to try to find the standart path, but my instnace files weren`t there to), so I tried using a command to find where it was and now I cant use any multipass command

**Comment by townsend2010** [comment]
Hi @Luca007!

I'm sorry you are having issues using Multipass.  I'm a little unclear on what your problem is.  Are you saying that no `multipass` command at all works like `multipass list`, `multipass version`, etc?

If so, could you please paste the output of `(get-command multipass.exe).Path`?

Thanks!

**Comment by Luca007** [comment]
Yes, no multipass commands are working. Not multipass list, not multipass version, nothing that involves multipass commands work. 

Here is the output: 

PS C:\Users\Louco050> (get-command multipass).Path
C:\WINDOWS\system32\multipass
PS C:\Users\Louco050>

**Comment by townsend2010** [comment]
Hmm, that is not the right path.  Please delete that file and see if it will start to work.

**Comment by Luca007** [comment]
That worked. Now I can use multipass commands again. Thank you!!

**Comment by townsend2010** [comment]
Hi @Luca007!

Excellent!  Thanks for letting us know!
