### ISSUE TITLE
Daemon does not react to `dnsmasq` dying

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#325]
When `named` is installed, it seems to jump onto all interfaces on port 53 to serve DNS queries. Our `dnsmasq` dies in this situation, failing to bind on port 53 on `mpqpbr0`:

```
Aug 02 12:22:10 foo-host dnsmasq[15529]: failed to create listening socket for 10.227.59.1: Address already in use
Aug 02 12:22:10 foo-host dnsmasq[15529]: FAILED to start up
```

Instances then lack DHCP and fail to start. We need to do something smarter in this case.

**Comment by townsend2010** [comment]
@Saviq, do you know if this happens when using the libvirt driver backend?

**Comment by Saviq** [comment]
I didn't check, but unless libvirt allows dnsmasq to die and starts it on DHCP alone or something, I can't see how it wouldn't. Basically `named` jumps on the new interface port 53 before dnsmasq can.

Maybe take-over option on the bind or some such, if possible?

**Comment by Saviq** [comment]
We could put the daemon in an error state and communicate that to the user on any interaction.

**Comment by Saviq** [comment]
Related: #775
