### ISSUE TITLE
How to uninstall Multipass on M1 Mac?

### ISSUE THREAD

**Issue by ekishelev** [canonical/multipass#3257]
I downloaded Multipass on my M1 Mac a few weeks ago and it's a bit confusing to me. I followed instructions on various forums online which instructed me to download/install various things through the terminal. I would now like to completely delete/uninstall multipass as well as all the data that goes along with it. How can I delete all the stuff I installed within the terminal to my Mac as well as the application as a whole?

**Comment by andrei-toterman** [comment]
Hi, @ekishelev! Please check out https://multipass.run/docs/installing-on-macos#heading--install-upgrade-uninstall. If you installed Multipass in a different way than those described there, please give more details and we'll figure it out!

**Comment by andrei-toterman** [comment]
Also, if you installed Multipass using `brew`, there are some files which you might have to delete manually, like this:
```
sudo rm -rf /var/root/Library/{Application\ Support/multipassd,Application\ Support/multipass-client-certificate,Preferences/multipassd,Caches/multipassd} /Library/logs/Multipass ~/Library/{Application\ Support/multipass*,Preferences/multipass}
```

**Comment by ekishelev** [comment]
Hi @andrei-toterman! Thanks for your response. So yeah I did use the multipass installer to install Multipass, not brew. I am just confused about how to use the installer to uninstall Multipass since that line of code below the image does not work to uninstall Multipass.

**Comment by ekishelev** [comment]
Yeah I do still have it installed and it works

**Comment by andrei-toterman** [comment]
Oh, wait. I just saw in the image you posted that you tried to run the script inside a Multipass instance. You should run it directly on your machine, not inside a Multipass instance.

**Comment by ekishelev** [comment]
[image: Screenshot 2023-10-17 at 11.19.50 AM.png]

**Comment by ekishelev** [comment]
Sorry about that https://github.com/canonical/multipass/assets/148169728/7c74d20d-6b61-4d5d-84a0-5e756f9b1549

**Comment by ekishelev** [comment]
Got it. It started deleting a lot of things I think but my system storage didn't free up so not sure it worked... https://github.com/canonical/multipass/assets/148169728/a3170327-f65c-430e-8a22-ea1f31016b22

**Comment by andrei-toterman** [comment]
You can see if there are any leftover files by running
```
sudo find ~/Library /var/root/Library /Library -iname 'multipass*' 2>/dev/null
```
If there are any, you can delete them manually.

**Comment by andrei-toterman** [comment]
Great! You can safely delete those files and then Multipass should be completely removed.

**Comment by ekishelev** [comment]
So how do I remove the rest of these files?

**Comment by andrei-toterman** [comment]
Oh, sorry for not being more explicit. Run this
```
sudo rm -rf ~/Library/{Application\ Support/multipass*,Preferences/multipass} /Library/Logs/Multipass
```

**Comment by ekishelev** [comment]
Alright, I did all of that but the storage on my laptop hasn't cleared up at all. I am confused because when I started working with multipass I installed some things as instructed online and my storage started going away. If I deleted everything, why wouldn't it have cleared some storage?

**Comment by andrei-toterman** [comment]
Can you please walk me through the process you underwent in order to install Multipass? You mentioned that you followed some instructions from some online forums. Can you point me to the instructions that you have followed?

The only thing needed to install Multipass is to download the package from https://multipass.run/install and run the installer. And everything we went through so far in order to uninstall it should've removed what the installer installed.

**Comment by ekishelev** [comment]
Right that’s correct I used the installer and it looks like based on what
we did the multipass application is gone so that worked. What I’m confused
about is that in my time using multipass, I installed things to my computer
with code within the terminal. Is there any way to delete all of that and
free up the storage that took up on my device?

**Comment by townsend2010** [comment]
Hi @ekishelev!

You have removed Multipass and all of it's data, so I'm very skeptical this is anything Multipass related.  As @andrei-toterman mentioned, you need to provide us with steps of what you have done, otherwise, we are out of ideas on how to help you.

Thank you!

**Comment by andrei-toterman** [comment]
There is definitely a way to uninstall anything that you installed, but you'll have to be a little more descriptive. What did you install and what commands did you run? What instructions did you follow?

**Comment by ekishelev** [comment]
Thanks Chris. I did follow every step Andrei sent and it looks like
multipass has uninstalled but I’m just confused because I thought all the
things I downloaded in multipass have taken up a significant amount of
storage space on my laptop but following the steps Andrei provided did not
free any storage. Do you guys know why that might be? Shouldn’t space free
up by following those steps and uninstalling multipass as well as all the
files within it?

**Comment by ekishelev** [comment]
To be completely honest I don’t remember what I installed and what commands
this was a while ago

**Comment by andrei-toterman** [comment]
Oof. Then unfortunately we can't really do much. At least Multipass itself was completely removed. But anything that was installed separately must be uninstalled separately, and since we don't know what it is, we don't know how to remove it. I will close this issue now, as there isn't anything left to do. Feel free to report any new issues you might encounter with Multipass in the future. Best of luck with your future endeavors!

**Comment by townsend2010** [comment]
Yes, all files related to Multipass are removed.  How are you determining if space is freed up?  I suggest you go to System Settings->General->Storage and then under there, it should be apparent what is taking up so much space such as `Applications`, `Documents`, `Trash`, etc. and you can clean it up.

**Comment by ekishelev** [comment]
Yeah I went there on my Mac and I have a feeling the multipass data is taking up space under system data where I can't see details or somewhere else deep in my device. The issue is that it could be many GB and that kind of space matters since I am on a laptop you know

**Comment by jaeyson** [comment]
> You can see if there are any leftover files by running
> 
> ```
> sudo find ~/Library /var/root/Library /Library -iname 'multipass*' 2>/dev/null
> ```
> 
> If there are any, you can delete them manually.

This really helped. Thanks! 🙏🏾
