### ISSUE TITLE
Removing multipass leaves mpvirtbr0 bridge behind

### ISSUE THREAD

**Issue by morphis** [canonical/multipass#327]
I installed the multipass snap (revision 334 from beta channel) and configured it to use the libvirt driver. I created a few containers and then removed the multipass snap from the system. After the snap was removed there was still a `mpvirtbr0` network device present. A new installation of the multipass snap caused now a `mpvirtbr1` device to be created which will cause multipass to not find the right network bridge when the system is rebooted. libvirt will fail to start then with:

`Aug 08 10:06:44 saturn libvirtd[3188]: Cannot get interface MTU on 'mpvirtbr1': No such device`

and multipassd with

`Aug 06 09:07:54 saturn multipass.multipassd[5868]: libvirt: XML-RPC error : Failed to connect socket to '/var/snap/multipass/common/run/libvirt/libvirt-sock': Connection refused`

Only way to get out of this is to manually modify the configuration of all present containers to use `mpvirtbr0` instead of `mpvirtbr1`.

**Comment by Saviq** [comment]
So we're trying to clean up the bridge on exit (bug part no. 1) and create a new bridge when one exists already on startup (bug part no.2). I wonder if we should just take over the existing one instead? After all there's no good reason for a user to have a `mpvirtbr0` on their system...
