### ISSUE TITLE
`multipass find` should not show the `snapcraft` remote

### ISSUE THREAD

**Issue by holta** [canonical/multipass#3274]
**Describe the bug**

This image is listed as available for about 24 hours now:

```
# multipass find --show-unsupported
Image                       Aliases           Version          Description
...
snapcraft:24.04             noble,devel,core2420231026         Ubuntu 24.04 LTS
```

And yet there seems to be no obvious way to install/launch the image:

```
# multipass launch 24.04
launch failed: Unable to find an image matching "24.04" in remote "".
# multipass launch noble
launch failed: Unable to find an image matching "noble" in remote "".
# multipass launch core24
launch failed: Unable to find an image matching "core24" in remote "".
# multipass launch 'snapcraft:24.04'
launch failed: '24.04' is not a supported alias. Please use `multipass find` for supported image aliases.
# multipass launch devel
Launched: undamaged-leafcutter
```

Above launches the wrong image, as can be seen by:

```
# multipass info undamaged-leafcutter
Name:           undamaged-leafcutter
State:          Running
IPv4:           10.181.233.24
Release:        Ubuntu 23.10
Image hash:     f27df1a7bcbb (Ubuntu 23.10)
CPU(s):         1
Load:           0.41 0.14 0.05
Disk usage:     1.7GiB out of 9.6GiB
Memory usage:   340.8MiB out of 946.1MiB
Mounts:         --
```

_Can further tips please be provided?  Thanks if possible !!_

**Additional info**

```
Operating System: Ubuntu 22.04.3 LTS
          Kernel: Linux 6.2.0-35-generic
    Architecture: x86-64
```
```
# multipass version
multipass   1.13.0-dev.352+gef40bb59
multipassd  1.13.0-dev.352+gef40bb59
```
```
# multipass get local.driver
lxd
```

**Comment by holta** [comment]
ADDENDUM... today the image also appears without the `--show-unsupported` flag:

```
# multipass find
Image                       Aliases           Version          Description
...
snapcraft:24.04             noble,devel,core2420231026         Ubuntu 24.04 LTS
```

_In any case, the inability to launch/install image yesterday and again today, remains mysterious_ 😉

**Comment by townsend2010** [comment]
Hi @holta,

What *should* work is `multipass launch snapcraft:devel`.  There seems to be a bug in our filtering out the aliases that we don't use.  We will fix that in the next release.

**Comment by townsend2010** [comment]
Also, these "snapcraft" images are really only intended for building snaps and aren't supposed to be shown.  Is that what you are doing?  Otherwise, it's not the same image you would expect if you did `multipass launch 24.04`of which those images are not available yet.

**Comment by holta** [comment]
Thanks @townsend2010 for explaining, that helps a lot!

(Trying out your recommendation fails for a different reason, apparently related to LXD, just FYI...)

```
# multipass launch snapcraft:devel
launch failed: Cannot retrieve info for image with id '23a92aa167bc7f2c456e5ffb0617312e3fb44cf73cecf666f68d1f4db403bcf1': LXD object not found
```

**Comment by townsend2010** [comment]
Hi @holta,

It appears the cloud images are now up to date which makes `multipass find` and `multipass launch` behave correctly.  The real problem here is that we should have never shown the `snapcraft:24.04` image in `find` since those images aren't really intended for regular use.  We'll use this bug to track that.  Thanks!

**Comment by holta** [comment]
> It appears the cloud images are now up to date which makes multipass find and multipass launch behave correctly.

Confirmed: great news that `multipass launch 24.04` now works!

ASIDE:

Is there any web visibility into the data underlying `multipass find` and/or `multipass find --show-unsupported` — no matter how informally?

**Comment by townsend2010** [comment]
@holta,

Sorry, I missed you inquiry about the visibility of the underlying data.  This is found at https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json, https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json, and https://cloud-images.ubuntu.com/buildd/daily/streams/v1/com.ubuntu.cloud:daily:download.json.

**Comment by holta** [comment]
Thanks @townsend2010 !

Does `multipass find --show-unsupported` perhaps refer to 3. below?

1. "Ubuntu Cloud Images (RELEASED)"
https://cloud-images.ubuntu.com/releases/
https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json

2. "Ubuntu Cloud Images"
https://cloud-images.ubuntu.com/daily/
https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json

3. "Ubuntu Buildd Images
These are not general-purpose images and their usage is not supported outside of Multipass or Launchpad..."
https://cloud-images.ubuntu.com/buildd/
https://cloud-images.ubuntu.com/buildd/daily/streams/v1/com.ubuntu.cloud:daily:download.json

PS underlying code appears to be:
https://github.com/canonical/multipass/blob/main/src/daemon/daemon_config.cpp#L142-L148

**Comment by townsend2010** [comment]
Hi @holta!

The `--show-unsupported` flag allows seeing images that are not supported any more.  These images may be in anyone of those streams.  Multipass does not guarantee these images will boot, but if they do, then great.
