### ISSUE TITLE
multipass not getting an ip address from the dhcp of a bridged network, cannot ping the bridged network

### ISSUE THREAD

**Issue by djshaw** [canonical/multipass#3290]
**Describe the bug**
I am trying to expose my multipass vms on my local network. When I start multipass with the `--network br0` option (`br0` is a bridge device that I created), it doesn't get an ip address from my router's dhcp. Assigning a static ip doesn't let the guest image ping anything on the physical network.

**To Reproduce**
It's not clear to me if the issue is with how I created the bridge. I create the bridge with:

```
ip link add name br0 type bridge
ip link set dev br0 up
ip link set eno1 master br0
ip address add 192.168.1.2/24 dev br0
ip route add default via 192.168.1.1 dev br0

ip route delete default via 192.168.1.1 dev eno1
ip route delete 192.168.1.0/24 dev eno1
ip route delete 192.168.1.1 dev eno1
```
I start multipass with:
```
multipass launch 23.04 --network br0
```

The routing table on the host machine is
```
$ ip route
default via 192.168.1.1 dev br0
10.135.160.0/24 dev mpbr0 proto kernel scope link src 10.135.160.1
169.254.95.0/24 dev enx0a94ef568c61 proto kernel scope link src 169.254.95.120 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev br-0fa7d11982c5 proto kernel scope link src 172.18.0.1
192.168.1.0/24 dev br0 proto kernel scope link src 192.168.1.2
```

**Expected behavior**

I expect `multipass list` to show the guest with 2 ip addresses. One in 10.135.0.0/24, the other in 192.168.0.0/24 (the range of my local network). In this particular case, I see the first, but not the second.

When I open a shell for the image, I expect that `ip addr list` to show a network adapter with a dhcp provided ip address.

**Logs**
```
Nov 08 05:08:14 walmart multipassd[1072]: Ignoring stop request since instance is already stopped
Nov 08 05:08:18 walmart multipassd[1072]: LXD object not found
Nov 08 05:08:18 walmart multipassd[1072]: LXD object not found
Nov 08 05:08:23 walmart multipassd[1072]: Loading "anbox-cloud-appliance" v1
Nov 08 05:08:23 walmart multipassd[1072]: Loading "charm-dev" v1
Nov 08 05:08:23 walmart multipassd[1072]: Loading "docker" v1
Nov 08 05:08:23 walmart multipassd[1072]: Loading "jellyfin" v1
Nov 08 05:08:23 walmart multipassd[1072]: Loading "minikube" v1
Nov 08 05:08:23 walmart multipassd[1072]: Loading "ros-noetic" v1
Nov 08 05:08:23 walmart multipassd[1072]: Loading "ros2-humble" v1
Nov 08 05:08:29 walmart multipassd[1072]: Using the 'multipass' storage pool.
Nov 08 05:08:29 walmart multipassd[1072]: Creating instance with image id: 1e6d030ed1c9a46314a006afee1e35ed3395c52f08781c86a4b1e9f5d4d16ea9
Nov 08 05:08:35 walmart multipassd[1072]: Waiting for SSH to be up
Nov 08 05:09:05 walmart multipassd[1072]: ssh failed to authenticate: 'Socket error: disconnected'
...snip...
Nov 08 05:09:41 walmart multipassd[1072]: ssh failed to authenticate: 'Socket error: disconnected'
Nov 08 05:09:42 walmart multipassd[1072]: Executing '[ -e /var/lib/cloud/instance/boot-finished ]'
```

**Additional info**
Host OS:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

Guest images:
```
$ multipass list
Name                    State             IPv4             Image
veritable-dane          Running           10.135.160.202   Ubuntu 22.04 LTS
```

Multipass version:
```
$ multipass version
multipass   1.12.2
multipassd  1.12.2
```

Info
```
$ multipass info --all
Name:           veritable-dane
State:          Running
IPv4:           10.135.160.202
Release:        Ubuntu 22.04.3 LTS
Image hash:     1e6d030ed1c9 (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.03 0.16 0.08
Disk usage:     1.4GiB out of 9.6GiB
Memory usage:   195.6MiB out of 945.2MiB
Mounts:         --
```

Local Driver
```
$ multipass get local.driver
lxd
```

**Additional context**
Nothing I can think of

I am baffled with this issue. Of the two machines I have running multipass guest vms, only one machine is failing to get ip address for specified networks. (Though the other machine doesn't have a bridge device to the local network).

I haven't ruled out pebcak. I don't know enough networking to debug what the guest vm is doing.

**Comment by sharder996** [comment]
Hi @djshaw,

There a few things you can check in order to see if this is an issue with Multipass or with the way you set up your bridged network.

1. I assume you are connected via ethernet. Bridged networks with WiFi on Linux is not supported.
2. You can try using a bridged network created by Multipass. Simply use `Multipass networks` to find the name of your physical network device. It should be listed as an `ethernet` type device. Then, launch an instance (eg. `multipass launch -n foo --network=<device>`) and verify that you receive the two IP addresses in the correct ranges. If this works, then its an issue with how you set up your bridged network.

**Comment by djshaw** [comment]
Thanks @sharder996. I was able to get an ip address from `mpbr0`. The issue was indeed in my bridge setup. Thanks for the feedback, I really appreciate a sounding board.

**Comment by jayakasadev** [comment]
@djshaw what was your final bridge configuration?

**Comment by djshaw** [comment]
@jayakasadev : My netplan configuration is:
```
$ cat /etc/netplan/00-installer-config.yaml
# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: true
      optional: true
    eno2:
      dhcp4: true
      optional: true
    eno3:
      dhcp4: true
      optional: true
    eno4:
      dhcp4: true
      optional: true
    enx0a94ef568c61:
      dhcp4: true
      optional: true
  bridges:
    br0:
      #dhcp4: true
      dhcp4: no
      addresses: [192.168.1.2/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [1.1.1.1,8.8.8.8]
      interfaces:
        - eno1
      routes:
        - to: default
          via: 192.168.1.1
  version: 2
```

I needed to edit `/etc/systemd/resolved.conf` to specify a DNS:
```
DNS=192.168.1.1
```

Additional work is required though.  When I ping a host that doesn't exist, I get a "Name or service not known". Pinging actual hosts works though. Since things work well enough for me, I haven't gotten around to resolving the issue.
```
$ ping foo
ping: foo: Name or service not known
$ ping google.ca
PING google.ca (142.251.32.67) 56(84) bytes of data.
64 bytes from yyz12s07-in-f3.1e100.net (142.251.32.67): icmp_seq=1 ttl=117 time=26.6 ms
```

I hope this helps.  Please let me know if you discover anything that would improve my configuration.
