### ISSUE TITLE
Interfaces added after instance creation are not snapshotted

### ISSUE THREAD

**Issue by luis4a0** [canonical/multipass#3294]
**Describe the bug**
The snapshot feature should take care of saving and restoring network interfaces.

**To Reproduce**

**Expected behavior**

**Logs**

**Additional info**

**Additional context**

**Comment by ricab** [comment]
Hey @luis4a0, this one wasn't covered yet, right? Reopening.

**Comment by luis4a0** [comment]
Right, this is not fixed yet. Thanks!

**Comment by townsend2010** [comment]
Hey @luis4a0!

This is now fixed, correct?

**Comment by luis4a0** [comment]
Hey @townsend2010! Yes, this is indeed fixed.

**Comment by townsend2010** [comment]
Ok, great, then I'll close!  Thanks!
