### ISSUE TITLE
Problem with connecting MRD

### ISSUE THREAD

**Issue by BognaMira** [canonical/multipass#3306]
I can't open my ubuntu instance with graphic interface using Microsoft remote desktop.

I have macOS and I was following a tutorial on how to get Ubuntu with GUI using multipass. 
Everything went well until I had to connect to Microsoft remote desktop. When I click connect it gives me an error. 

Unable to connect
We couldn’t connect to the remote PC. Make sure the PC is turned on and connected to the network and that remote access is enabled.
Error code: 0x204

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/13379368/multipassd.log)

**Additional info**
- OS: Ventura 13.2.1
- multipass   1.12.2+mac
- multipassd  1.12.2+mac

Name:           precious-brill
State:          Running
IPv4:           192.168.64.2
Release:        Ubuntu 22.04.3 LTS
Image hash:     eafa7742ce5f (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.10 0.03 0.01
Disk usage:     4.6GiB out of 4.8GiB
Memory usage:   164.3MiB out of 962.3MiB
Mounts:         --

- multipass local.driver: qemu

Please help me.

**Comment by BognaMira** [comment]
Hi @ricab, I am launching both multipass and MRD on the same Mac. I am not sure how can I check if my Ubuntu instance is visible on LAN. I would be glad if you could instruct me on how can I ensure it is on the same LAN.

**Comment by BognaMira** [comment]
Update: I thought having the instance open in the terminal caused the problem, so I closed it. 
The MRD worked this time, but not entirely correctly. 

This is the pop-up that appeared before connecting:
The identity of the remote PC can't be verified. Do you want to connect anyway?
This problem can occur if the remote PC is running a version of Windows that is not configured to support server authentication.

After connecting the following window appears:
Connection Log
connecting to sesman IP 127.0.0.1 port 3350 
sesman connect ok
sending into to session manager, please wait...
login failed for display 0

After clicking ok, a logging window opens but my password I set doesn't work.

**Comment by ricab** [comment]
Hi @BognaMira, I don't know what tutorial you are trying to follow, nor do I know much about MRD, so I am not in the best position to help you. I am not sure why it would fail to authenticate, it seems like something is not fully setup. When you say "my password", do you mean the password you setup on the instance? Note that there is no default password for the ubuntu user (the default) on the instance.

**Comment by BognaMira** [comment]
Hi @ricab, I am referring to this tutorial https://www.youtube.com/watch?v=oi8f6hVI2P4
I mean the password I set up for my Ubuntu instance, I also used it while setting up MRD. 
I guess that something is wrong because after connecting I get a blank blue screen with only this pop-ups I described in my previous comment.  
In case you can't help me, I hope that someone else can.
