### ISSUE TITLE
multipass not working with virtual box 7.0.12

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3311]
**Describe the bug**
```
❯   multipass launch --name primary -c 4 -m 4G --mount E:\:/mnt/e_host --mount D:\:/mnt/d_host --mount C:\:/mnt/c_host
launch failed: Could not start VM: VBoxManage.exe: error: The virtual machine 'primary' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\WINDOWS\system32\config\systemprofile\VirtualBox VMs\Multipass\primary\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
Waiting for VM "primary" to power on...
```

**To Reproduce**
How, and what happened?
1. winget install -h gerardog.gsudo
1. `sudo winget install -h Oracle.VirtualBox Canonical.Multipass`
2. Reboot.
3. `sudo multipass set local.driver=virtualbox; multipass set local.privileged-mounts=yes; multipass set client.gui.autostart=no;   multipass launch --name primary -c 4 -m 4G --mount E:\:/mnt/e_host --mount D:\:/mnt/d_host --mount C:\:/mnt/c_host`

**Expected behavior**
Multipass should work.

**Logs**
[logs.zip](https://github.com/canonical/multipass/files/13415677/logs.zip)

**Additional info**
 - OS: Windows 11 Pro
- `multipass   1.12.2+win; multipassd  1.12.2+win`
- `multipass info --all: outputs nothing`
- `multipass get local.driver: virtualbox`

**Additional context**
Multipass works fine with 6.1.48 version, but not with 7.0.12

**Comment by luis4a0** [comment]
Hi @soredake, thanks for reporting. I cannot reproduce on my computer, VirtualBox 7.0.12 works for me. Examining the logs, one thing I note is that there are some drivers missing. Can you please check if VirtualBox is working, by creating a VM not using Multipass? Thanks!

**Comment by soredake** [comment]
@luis4a0 turns out that Windhawk software is breaking virtualbox by default https://github.com/ramensoftware/windhawk/issues/135

Closing.

**Comment by luis4a0** [comment]
Amazing, thanks for reporting there!
