### ISSUE TITLE
Remove-vm conflict

### ISSUE THREAD

**Issue by major-sam** [canonical/multipass#3313]
**Describe the bug**
Hyper-v module functions conflict with powercli

**To Reproduce**

1. install globaly powerCli: `Install-Module VMware.PowerCLI -Scope AllUsers`
2. run `multipass delete -p` 

**Expected behavior**
VM removed from hyperv

**Logs**
[powershell.exe] [19380] started: powershell.exe Remove-VM -Name k3s -Force
[<instance>] [19380] PowerShell finished abnormally: Process returned exit code: 1

**Additional info**
 - OS: Windows 10
-  multipass   1.12.2+win; multipassd  1.12.2+win
- hyperv

**Workaround**

- To resolve conflicts do not use same scope with VMware.PowerCLI 
- for full resolution `hyper-v\Remove-VM -Name <instansce> -Force` must be called

**Comment by luis4a0** [comment]
Hi @major-sam, thanks for reporting. We are using the global PowerShell scope. It is supposed that no application should contaminate the global scope. In this case, IIUC, VMWare.PowerCLI is avoiding all other applications (not only Multipass) of executing Hyper-V commands.

**Comment by luis4a0** [comment]
I'm closing this. In any case, we can take it into account for a future improvement. Thanks!
