### ISSUE TITLE
`multipass launch charm-dev`: MicroK8s cloud no longer configured by default

### ISSUE THREAD

**Issue by tmihoc** [canonical/multipass#3317]
**Describe the bug**
The Juju [tutorial](https://juju.is/docs/juju/tutorial) uses Multipass, specifically, the `charm-dev` blueprint.

The last time we tested it (quite recently), it was working great -- you just launched a VM with the blueprint and you already had MicroK8s, LXD, Juju, Charmcraft, etc., and if you ran `juju clouds` it would show both LXD and MicroK8s, and so on for credentials and even controllers. However, testing it again today, I noticed that my MicroK8s is no longer preconfigured, and so, no longer recognized automatically by `juju clouds`:

```
ubuntu@tutorial-vm:~$ microk8s version
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user ubuntu to the 'snap_microk8s' group:

    sudo usermod -a -G snap_microk8s ubuntu
    sudo chown -R ubuntu ~/.kube

After this, reload the user groups either via a reboot or by running 'newgrp snap_microk8s'.

```
and 

```
ubuntu@tutorial-vm:~$ juju clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.
You can bootstrap a new controller using one of these clouds...

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   0            built-in  LXD Container Hypervisor
```

**To Reproduce**
How, and what happened?
1. `multipass launch --cpus 4 --memory 8G --disk 30G --name tutorial-vm charm-dev`
2. `microk8s version`
3. `juju clouds` 

**Expected behavior**
I was expecting MicroK8s to be configured and picked up automatically, just as it was before and on par with LXD.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

```
ubuntu@tutorial-vm:~$ journalctl --unit 'snap.multipass*'
Failed to add filter for units: No data available
```

**Additional info**
 - OS: [e.g. Ubuntu 23.04]
- `multipass version` 1.12.2
- `multipass info --all` (too long, but I have 5 Multipass VMs in all, 4 stopped)
- `multipass get local.driver` qemu

**Additional context**
--

**Comment by luis4a0** [comment]
Hey @tmihoc! I am unfortunately not able to reproduce. I created a new `charm-dev` VM, shell into the instance and microk8s seems to work ok:
```
ubuntu@charm-dev:~$ microk8s version 
MicroK8s v1.27.7 revision 6101
ubuntu@charm-dev:~$ juju clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.

Clouds available on the controller:
Cloud     Regions  Default    Type
microk8s  1        localhost  k8s  

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   1            built-in  LXD Container Hypervisor
microk8s   1        localhost  k8s   1            built-in  A Kubernetes Cluster
```

Should something related to Microk8s have changed?

**Comment by tmihoc** [comment]
Hi Luis,

I've tried it again  just now. `multipass launch` is taking longer than usual (seems to be hanging, as I've mentioned in another issue). However, `multipass list` does show the new VM. So I opened a shell into it and noticed that (1) `microk8s version` returned the expected result (the version) but `juju clouds` issued (2) an error about LXD and then (3) a similar error about MicroK8s. If I wait a bit longer, it all looks fine. (Checking my `multipass launch` terminal window, I see launch appears to be complete there too.) See all below. 

```text
ubuntu@juju-vm:~$ juju clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.
You can bootstrap a new controller using one of these clouds...

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   1            built-in  LXD Container Hypervisor
microk8s   1        localhost  k8s   0            built-in  A Kubernetes Cluster
ERROR could not get clouds from controller "lxd": no controller API addresses; is bootstrap still in progress?
ubuntu@juju-vm:~$ juju clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.
You can bootstrap a new controller using one of these clouds...

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   1            built-in  LXD Container Hypervisor
microk8s   1        localhost  k8s   0            built-in  A Kubernetes Cluster
ERROR could not get clouds from controller "lxd": no controller API addresses; is bootstrap still in progress?

ubuntu@juju-vm:~$ juju clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.
You can bootstrap a new controller using one of these clouds...

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   1            built-in  LXD Container Hypervisor
microk8s   1        localhost  k8s   1            built-in  A Kubernetes Cluster
ERROR could not get clouds from controller "microk8s": no controller API addresses; is bootstrap still in progress?


ubuntu@juju-vm:~$ juju clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.

Clouds available on the controller:
Cloud     Regions  Default    Type
microk8s  1        localhost  k8s  

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   1            built-in  LXD Container Hypervisor
microk8s   1        localhost  k8s   1            built-in  A Kubernetes Cluster

```


So my guess right now is that there is no issue -- it's just that, for some reason, `multipass launch` is now taking much longer than before. Do you happen to know why that would be the case?

**Comment by luis4a0** [comment]
Hey @tmihoc, slow network can be the reason for Blueprints taking long for initializing. The fact that without the `charm-dev` Blueprint it's faster just corroborates this.

**Comment by tmihoc** [comment]
@luis4a0 Hah, interesting. The contrast is very stark. Compare the times below. Mentioning in case anything can be done to improve the blueprint experience.

```
$ time multipass launch --cpus 4 --memory 8G --disk 30G --name test-vm charm-dev
launch failed: instance "test-vm" already exists

real	0m0.116s
user	0m0.030s
sys	0m0.054s

$ time multipass launch --cpus 4 --memory 8G --disk 30G --name charm-dev-vm charm-dev
Launched: charm-dev-vm

real	9m56.053s
user	0m0.281s
sys	0m0.341s
```

**Comment by luis4a0** [comment]
I see. In the first command you sent, however, no instance was created :) Anyways, I can't see a way of accelerating this particular Blueprint. Many things must be downloaded and installed, and that certainly takes time.

**Comment by tmihoc** [comment]
Mhmm. It's just that a few weeks ago it wasn't taking this long (<2 mins, from what I remember).

**Comment by tmihoc** [comment]
@luis4a0 Someone just reached out to me to say that the 'MicroK8s cloud not configured by default' issue just happened to them too: https://discourse.charmhub.io/t/get-started-with-juju/6559/45

**Comment by luis4a0** [comment]
Hey @tmihoc, let's try to investigate with what we have. Do you happen to have kept a VM on which Microk8s is misconfigured?

**Comment by tmihoc** [comment]
@luis4a0 Unfortunately, no -- I've deleted it.

**Comment by luis4a0** [comment]
I think at this point we should ask the author of the Blueprint, to ask for any idea about this. @sed-i, can you help us with this issue? Thank you!

**Comment by tmihoc** [comment]
Hi @luis4a0 and @sed-i  -- any news on this?

**Comment by sed-i** [comment]
Hi,

> `timed out waiting for initialization to complete`

This is something I've seen all along. It takes time to create the environment, around 15 mins sometimes. The odd thing is that even though the blueprint sets the [timeout to 30 min](https://github.com/canonical/multipass-blueprints/blob/2278799ca0c1293009cb8cb97a2b77cd7cba3434/v1/charm-dev.yaml#L27), multipass exits after 10 with the timeout error.

But the fact that it timed out doesn't matter - provisioning with the cloud init script continues. You should check back after 15 min or so. What I typically do after shelling into the VM is look at

```
$ tail -f /var/log/cloud-init-output.log
```

and wait for `finished`.
```
Cloud-init v. 23.3.3-0ubuntu0~22.04.1 finished at Tue, 05 Dec 2023 06:02:49 +0000. Datasource DataSourceGCELocal.  Up 131.45 seconds
```

I imagine you were attempting to use microk8s before cloud-init finished.

**Comment by townsend2010** [comment]
I entered an issue report for the Blueprint timeout not being honored: https://github.com/canonical/multipass/issues/3324

**Comment by townsend2010** [comment]
Just to follow up here, but the bug report I opened at #3324 has been closed due to a false alarm.  The timeout in the Blueprint is working as intended.

All I can say is that the bootstrapping of the Blueprint instance, ie, the downloading, installing, and configuring of packages is really at the mercy of network bandwidth in general, bandwidth of the Snap Store, bandwidth of download LXD images, bandwidth of the Ubuntu archive.  The Blueprint also declares updating of packages in the instance, so if there are a bunch of packages that need updating that *could* take some time.  And there are other factors I haven't mentioned either.  As you can see, there are many, many variables at play here that Multipass simply cannot account for.

**Comment by tmihoc** [comment]
Got it. Thank you for taking the time to look into this and explain, @townsend2010 ! Now I know how to advise our users.

**Comment by tmihoc** [comment]
@townsend2010 I just received another report of someone being affected by this (timeout error). If what @sed-i said is true (that the blueprint is set to time out after 30 mins but multipass times out after 10), that could be an issue for a lot of people.

**Comment by townsend2010** [comment]
Hi @tmihoc!

The issue @sed-i reported is based on an older version of Multipass and was fixed in version 1.12.  So the question is, are these users using older versions of Multipass or is it taking longer than 30 minutes for all of the stuff that the `charm-dev` Blueprint does to run?

As I mentioned previously, the `charm-dev` Blueprint does many, many things under the hood and depending on network speeds, etc. it may take a very long time to complete.  In the long term, the answer will be to have a special charm-dev image that has all of the software already installed in it, but we aren't there yet until Imagecraft is more mature.  In the meantime, other than no longer making the Blueprint available, I'm not sure what else we can do for this.  I feel making the timeout longer and longer is just arbitrary.

**Comment by tmihoc** [comment]
@townsend2010 The users are people going through our Juju tutorial who are most likely installing Multipass for the first time (on their Linux, Windows, or macOS machine). 

Right now I've added a note to the tutorial to clarify that the `multipass launch ... charm-dev` step may take some time, because the command is doing a lot of things, some of which depend on the network bandwidth.

However, if they wait 10-15 mins and the command just times out, they'll wonder what's wrong and what they can do next.

So, what should I do? Tell them to start over? Try a workaround (what would that look like)? Stop using the blueprint in our docs? (I really don't want to do that as I think it's an incredibly useful thing and a lot of our charmers use it.)

**Comment by townsend2010** [comment]
> However, if they wait 10-15 mins and the command just times out, they'll wonder what's wrong and what they can do next.

It shouldn't be timing out in this time.  I have confirmed that the `Waiting for initialization to complete" part should be timing out in 30 minutes as intended.  What @sed-i said previously was based on old information.  Are we 100% sure the users reporting the problem are seeing the timeout in 10-15 minutes?  Or is some sort of perception like "It sits there for a while and then I see the timeout", but there isn't a good sense of the actual time it took?

As for what to do in case there is the timeout, it's not like it's a total failure and is probably still working on things behind the scenes, so it's hard to say what the correct answer is- it really depends on what the state of things are when the 30 minute timeout occurs and there really is no way for Multipass to know that.

I really think someone with the experience of how all the Juju and Charming stuff works (perhaps @sed-i?) really needs to debug this and figure out if there is anything better that can be done.  Since we (Multipass) cares about the user experience here, I'm thinking we should remove the `charm-dev` Blueprint until we have a better idea of what is going on.

**Comment by tmihoc** [comment]
FWIW I really don't want the `charm-dev` blueprint to be removed. I think it provides a lot of value.

**Comment by sed-i** [comment]
> @townsend2010 I just received another report of someone being affected by this (timeout error). If what @sed-i said is true (that the blueprint is set to time out after 30 mins but multipass times out after 10), that could be an issue for a lot of people.

@tmihoc it would be curious to see what multipass version they have and the output of their `time multipass launch charm-dev` (note the `time`).

**Comment by tmihoc** [comment]
> It shouldn't be timing out in this time. I have confirmed that the Waiting for initialization to complete part should be timing out in 30 minutes as intended. What @sed-i said previously was based on old information. 

Good to know.

> Are we 100% sure the users reporting the problem are seeing the timeout in 10-15 minutes? Or is some sort of perception like "It sits there for a while and then I see the timeout", but there isn't a good sense of the actual time it took?

I'll ask them to measure the time next time, as otherwise all we're getting is vague impressions.

> I really think someone with the experience of how all the Juju and Charming stuff works (perhaps @sed-i?) really needs to debug this and figure out if there is anything better that can be done.

+1

> Since we (Multipass) cares about the user experience here, I'm thinking we should remove the charm-dev Blueprint until we have a better idea of what is going on.

I think removing the Blueprint would be a big loss. I'd rather we added a note making people aware that it might take a while to complete (as I've just done in Juju docs) than get rid of it altogether. Because the truth is that, once it does complete, it's a pretty wonderful thing to have, as it sets everything up for you, and in a nice isolated environment.
