### ISSUE TITLE
[lxd] multipass stops sshfs mount on suspend even when suspend isn't supported

### ISSUE THREAD

**Issue by sharder996** [canonical/multipass#3322]
**Describe the bug**
The LXD backend driver does not support suspending instances. However, if the instance has mounts they will be stopped on calling suspend even though the instance cannot be suspended. You then need to restart the instance to get them back.

**To Reproduce**
1. `multipass set local.driver=lxd`
2. `multipass mount ...`
3. `multipass suspend ...`

**Comment by georgeliao** [comment]
Hi @sharder996 , can you provide more specific commands? I seem always to get the `suspend failed: suspend is currently not supported` message with classic/native mount or without any mount.

**Comment by sharder996** [comment]
Yes, and now all your mounts will be stopped. The problem is coming from [this](https://github.com/canonical/multipass/blob/8bc1e8388b0535b3c37ff4ada3f7337d1415147b/src/daemon/daemon.cpp#L2161:2164) block of code. Mounts are stopped and then suspend fails, but the mounts are not restored.
