### ISSUE TITLE
Blueprints timeouts are not honored when launching

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#3324]
When `timeout` is set in a Blueprint, it is not being honored.  For example, if a 30 minute timeout is being set in a Blueprint, the `Waiting for initialization` phase will still time out in 10 minutes.

**Comment by luis4a0** [comment]
Hi @townsend2010, I checked the `--timeout` parameter is perfectly honored. This appears to be an issue with the value set in theBlueprint specifically.

**Comment by townsend2010** [comment]
Hi @luis4a0!

Yes, this issue is specifically about the timeout set in Blueprints not being honored.  I agree, passing `--timeout` during `launch` works as intended.

**Comment by georgeliao** [comment]
@townsend2010 , I think not honoring timout value was fixed in https://github.com/canonical/multipass/issues/2772.

**Comment by sed-i** [comment]
Related: #1039

**Comment by townsend2010** [comment]
Hey @georgeliao,

Hmm, you may be right.  But @sed-i [reported](https://github.com/canonical/multipass/issues/3317#issuecomment-1841189363) seeing a timeout after 10 minutes even though the Blueprint's timeout is set to 30 minutes.  Some investigation is still needed to figure out what is happening.

**Comment by townsend2010** [comment]
I'm simply not seeing the non-honored Blueprint timeout when I try this.  @sed-i, could you please show a case where you see the `Waiting for initialization to complete` time out before the actual Blueprint, perhaps with using `time multipass launch charm-dev`?  Thanks!

**Comment by townsend2010** [comment]
Ok, after some more investigation, I'm convinced this is not a problem with Multipass version 1.12 and newer.  I'm going to close this.

**Comment by sed-i** [comment]
Yep, with 1.12.2 I don't see it anymore
```
$ time multipass launch --mem 7G --cpus 2 --disk 50G --name timing-test charm-dev                                                                                                   warning: "--mem" long option will be deprecated in favour of "--memory" in a future release. Please update any scripts, etc.
Launched: timing-test
multipass launch --mem 7G --cpus 2 --disk 50G --name timing-test charm-dev  0.14s user 0.16s system 0% cpu 11:15.37 total
```
