### ISSUE TITLE
Starting too many instances simultaneously crashes multipassd

### ISSUE THREAD

**Issue by lengau** [canonical/multipass#3336]
**Describe the bug**
If you programmatically launch multipass instances but do so too quickly, `multipassd` crashes in a way that's quite hard to recover from (it requires manually killing qemu instances).

**To Reproduce**
1. Run in bash: `for i in {1..10}; do multipass launch -n test-$i jammy & done`
2. Wait about 10 seconds
3. Try to run any multipass command (e.g. `multipass list`). 

**Expected behavior**
Multipass continues as usual

**Logs**
[multipass.log](https://github.com/canonical/multipass/files/13686955/multipass.log)

**Additional info**
 - OS: Kubuntu 23.10
- `multipass version`: `multipass   1.12.2`
- `multipass info --all`  (this is after stopping and restarting multipassd)
```
Name:           spread-multipass-63-ubuntu-22-04-64
State:          Running
IPv4:           10.114.143.222
Release:        Ubuntu 22.04.3 LTS
Image hash:     6d6af17f28c8 (Ubuntu 22.04 LTS)
CPU(s):         2
Load:           0.00 0.00 0.00
Disk usage:     2.8GiB out of 19.3GiB
Memory usage:   184.2MiB out of 1.9GiB
Mounts:         --

Name:           test-1
State:          Stopped
IPv4:           --
Release:        --
Image hash:     6d6af17f28c8 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           test-3
State:          Running
IPv4:           10.114.143.237
Release:        Ubuntu 22.04.3 LTS
Image hash:     6d6af17f28c8 (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     1.5GiB out of 4.8GiB
Memory usage:   168.3MiB out of 951.9MiB
Mounts:         --

Name:           test-9
State:          Stopped
IPv4:           --
Release:        --
Image hash:     6d6af17f28c8 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver`: `qemu`

**Additional context**
I'm not sure 10 simultaneous runs are necessary, but it seems to reliably break it.

**Comment by andrei-toterman** [comment]
Hi, @lengau! Thanks for reporting this and I'm sorry that you're experiencing problems with Multipass. I ran your test case with 20 instances multiple times and I couldn't get `multipassd` to crash. Could it be a resource problem? How powerful is your computer? We'll inspect the logs and try to get back to you as soon as possible.

**Comment by syu-w** [comment]
I can reproduce with 10 instances. It seems multipassd not crash but the socket is not usable.
The system is ubuntu 23.10 with 5950X + 128GB ECC memory.

**Comment by cmatsuoka** [comment]
It happens to me with current stable when launching as few as 4 or 5 instances configured in spread as adhoc back-ends. Machine is a Ryzen7 2700 with 64GB of RAM running jammy server. Adding random delays before launching instances makes the problem less frequent. Once it happens the only way to fix it is restarting the service.

**Comment by townsend2010** [comment]
Yeah, I'm unable to reproduce as well.  I tried a number of times with success on my Ryzen laptop w/ 32GB of RAM.  It does seem like it may be a race condition of sorts and we are going to improve the asynchronicity of the daemon during the 24.04 cycle, so that may alleviate this issue.

**Comment by lengau** [comment]
Hmmm yeah, I'm unable to reproduce with a completely fresh multipass. However, I think that's to do with my reproducer as last night I got some weirdness out of my more complex workflows. I'll try to get you a better reproducer.

**Comment by lengau** [comment]
I think this is the same issue as #3401, but #3401 has a clearer reproducer so I'll close this in favour of it.

**Comment by townsend2010** [comment]
Hi @lengau!

#3401 is not crashing the daemon and is also caused by a broken image.  It appears to me the symptoms in this issue and #3401 are different, but if you prefer to close this in favor of #3401, I am fine with that since we never seemed to be able to reproduce this issue.
