### ISSUE TITLE
Where is multipass downloading to image so i could remove it when finished using. Had some crash and removing still somewhere has some files still using space a bit the it was before install

### ISSUE THREAD

**Issue by kangarooo** [canonical/multipass#3337]
Where is multipass downloading to image so i could remove it when finished using. Had some crash and removing still somewhere has some files still using space a bit the it was before install

**Comment by andrei-toterman** [comment]
Hey, @kangarooo! Depending on your operating system, images are downloaded to the following locations:
- Linux: `/var/snap/multipass/common/cache/multipassd`
- Windows: `C:\ProgramData\Multipass\cache`
- macOS: `/var/root/Library/Caches/multipassd`

If you want, you can also change the location where Multipass stores its data by following [this guide](https://multipass.run/docs/configure-multipass-storage)

**Comment by kangarooo** [comment]
How can i access thouse folders? In windows 10 i cant
![image](https://github.com/canonical/multipass/assets/73187/e84ed035-abd6-42c5-b465-4920df542eb3)

**Comment by andrei-toterman** [comment]
Well, what are the contents of `C:\ProgramData\Multipass`? I see from your other issue that you tried to uninstall Multipass. Maybe the `cache` directory was already deleted. From your wording, I understood that you are trying to delete the downloaded Ubuntu images, but perhaps you are trying to delete an instance's image file (which is the actual VM file)?
