### ISSUE TITLE
In powershell windows 11 "multipass delete nameofinstance" didnt delete from hyper-v

### ISSUE THREAD

**Issue by kangarooo** [canonical/multipass#3344]
Its still in hyper-v

**Comment by georgeliao** [comment]
Hi @kangarooo , thanks for reporting, can you elaborate the "Its still in hyper-v"? did you run the hyper-v command directly?

**Comment by kangarooo** [comment]
Yes with delete its only in recycle bin from where can recover i just found in wiki, theres 2nd section about removing permanently
https://multipass.run/docs/remove-an-instance
$ multipass delete keen-yak
$ multipass purge
$ multipass list
No instances found.
