### ISSUE TITLE
CPU does not have the features necessary for Multipass

### ISSUE THREAD

**Issue by sudo-bruno** [canonical/multipass#3356]
**What are you trying to do?**
Recently I needed to install MAC on my PC to use some applications that don't work well or don't exist for Windows. With that I installed MAC on my Ryzen 7 5800X and everything works impeccably, vanilla installation.

So far everything is good, except virtualization. Versions prior to Ventura 13.6 could run VM normally, however, in this version I have no success. I would like to know if there would be a way to add a different way of fetching information from the CPU, a kind of second check?

**What's your proposed solution?**
My proposal is that Multipass can consult via libcpuid the features present in the processor, thus confirming that there is SVM and that it supports virtualization. Bear in mind that the limitation is only in the pre-assumption that all MACOS is running on INTEL.

**Additional context**
The context I want to add is that, as the objective of free software is to have access to any software in the best way, even if there are some opinions that MACOS should only be run on MAC, I believe that we can overcome this barrier and make Multipass available in an open way, not limited to MACOS users on PCs that today use them stably with non-INTEL CPUs.

If there is a path I can follow, if this is not in the interest of the maintainers, I would be very grateful to hear opinions on how to make Multipass be compiled to accept SVM on MACOS

```
CPUID is present
CPU Info for type #0:
------------------
  arch       : x86
  purpose    : general
  vendor_str : AuthenticAMD
  vendor id  : 1
  brand_str  : AMD Ryzen 7 5800X 8-Core Processor
  family     : 15 (0Fh)
  model      : 1 (01h)
  stepping   : 2 (02h)
  ext_family : 25 (19h)
  ext_model  : 33 (21h)
  num_cores  : 1
  num_logical: 16
  tot_logical: 16
  affi_mask  : 0x0000FFFF
  L1 D cache : 32 KB
  L1 I cache : 32 KB
  L2 cache   : 512 KB
  L3 cache   : 32768 KB
  L4 cache   : -1 KB
  L1D assoc. : 8-way
  L1I assoc. : 8-way
  L2 assoc.  : 8-way
  L3 assoc.  : 16-way
  L4 assoc.  : -1-way
  L1D line sz: 64 bytes
  L1I line sz: 64 bytes
  L2 line sz : 64 bytes
  L3 line sz : 64 bytes
  L4 line sz : -1 bytes
  L1D inst.  : 1
  L1I inst.  : 1
  L2 inst.   : 1
  L3 inst.   : 1
  L4 inst.   : 0
  SSE units  : 256 bits (authoritative)
  code name  : Ryzen 7 (Vermeer)
  features   : fpu vme de pse tsc msr pae mce cx8 apic mtrr sep pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht pni pclmul monitor ssse3 cx16 sse4_1 sse4_2 syscall movbe popcnt aes xsave osxsave avx mmxext nx fxsr_opt rdtscp lm lahf_lm cmp_legacy svm abm misalignsse sse4a 3dnowprefetch osvw ibs skinit wdt ts ttp tm_amd hwpstate constant_tsc fma3 f16c rdrand cpb aperfmperf avx2 bmi1 bmi2 sha_ni rdseed adx
```

**Comment by sharder996** [comment]
Hi @fbrunosf,

Can you clarify what your setup is? From how I understand you have installed macOS as your host operating system and are then attempting to run Multipass. Then, Multipass will not work on macOS versions of Ventura 13.6+. Correct me if I'm wrong here.

If Multipass is not working correctly for you, can you provide an error output and/or [logs](https://multipass.run/docs/accessing-logs)?

**Comment by fbrunosf** [comment]
Hi @sharder996, firstly thanks for responding.

How can I get installation logs to send to you? I was unable to install it to create logs in "/Library/Logs/Multipass/multipassd.log"

When trying to install, the following error occurs:

Title: Unsupported CPU
Message: Your CPU does not have the features necessary for Multipass. Installation cannot proceed.

However, the SVM is enabled in the BIOS and when running cpuid_tool it returns that the SVM and other features are present, as shown in my first message.

And when executing "sysctl machdep.cpu.features", it does not return the SVM feature.

> machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH MMX FXSR SSE SSE2 HTT SSE3 PCLMULQDQ MON SSSE3 FMA CX16 SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES XSAVE OSXSAVE AVX1.0 RDRAND F16C

I managed to get around this using pkgutil and removing the condition created to validate the "sysctl machdep.cpu.features" from the script, but at the end of the installation error and I was unsuccessful.

I'm thinking about installing the Windows version via Parallels, but it would be horrible.

PS.: Until the OSX 12.X version I ran Multipass normally.

**Comment by townsend2010** [comment]
Hi @fbrunosf,

What the installer is doing here is essentially checking if `sysctl kern.hv_support` is true. If macOS doesn't think the host is capable of supporting virtualization, then there really isn't anything we can do about that.  We rely on what macOS says.

Considering you are installing macOS on a system that Apple doesn't think you should install macOS on, I'm afraid you are at the mercy of Apple in this case.  It seems Apple has put in some extra checks in 12.x+ to cripple macOS on hosts it doesn't support.

I'm going to close this since there isn't anything we can do and even if there was, it would cross into a legal grey area I do not want to go into.

**Comment by fbrunosf** [comment]
Hi @townsend2010, thanks for answering.

In this case, would having free software that allows you to use CPU X or Y in a closed OS be legally prohibited?

Thank you very much in advance.

**Comment by townsend2010** [comment]
I would say that if free software did things to bypass crippled features (such a virtualization in this case) in a closed OS running on a system the OS vendor distinctly prohibits in their licensing agreement, we would be putting ourselves at risk of hearing from the OS vendor. :wink:

This is why I called it a legal grey area though because I'm not a lawyer, but I'm quite sure Canonical would not want to risk running amok of Apple.

**Comment by fbrunosf** [comment]
Oow, yes. I also don't understand anything legal, but certainly in this hypothesis, Apple wouldn't let it go cheap.

Thank you again
