### ISSUE TITLE
apt timeouts in subiquity steps

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3359]
i also have a issues in upgrade packages and install kernel subiquty steps due to small apt timeout and retries count - may be we need to add some settings here with apt timeouts?

Last week my user-data was executed without any problem, but now I can't install kernel
and also should switch to install all packages via late-step block, so this means that packages update, upgrade and install block have a no sense.
also - we have a already provided kernels and images on our HTTP or (t)ftp resource, so may be we need to use it, and just updates if something goes wrong with network?
@matthewpaulthomas, @townsend2010 - what are you thing about it

_Originally posted by @mturnaviotov in https://github.com/canonical/multipass/issues/1039#issuecomment-1880052594_

**Comment by ricab** [comment]
Hi @mturnaviotov, I am not sure I understand your problem, but your issue appears to be different from the cloud-init timeout stuff, so let's discuss here. You say that package install steps time out in apt, when launching a new instance, correct? Could that be due to some transient internet connectivity issue? Or maybe some mirror was unresponsive at the time? Do you still get the same if you try again now?

There may be ways to configure the apt timeouts, but they would be entirely outside of Multipass's scope. You could try some specific [clould-init for Apt](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#apt-configure) and try to configure apt timeouts that way (e.g. search for "timeout" [here](https://wiki.debian.org/AptConfiguration)). Or you could try to ask cloud-init to execute custom commands. Anyway, I suppose increasing apt timeouts would only make sense if you knew that you were on a very slow but otherwise working connection.

**Comment by mturnaviotov** [comment]
1. Yes, you are correct, When I tried to install a new instance -got a unexpected timeout,  when apt installs kernel via CloudInit internals, and i see in shell logs that CI interrupted in trying to download packages from official mirrors. Also this issue sometimes caused in update/upgrade packages in CloudInit steps. in happens unexpected to me one time per 1-5 retries, when I try to test my approach ( [here](http://github.com/mturnaviotov/provisioning)) in the same environment 
2. it's related to Cloudinit internal apt, i think, because - no kernel/firmware - no option to install packages.
3. third my question - we have a mounted iso va http/nfs resource - why cloudinit don't use than as base and after that it can be safely updated from internel.
(screen is attached)
<img width="635" alt="Знімок екрана 2024-01-07 о 14 00 00" src="https://github.com/canonical/multipass/assets/3820029/5447d1a2-662d-45d9-80bb-67ff5cc8eb05">

**Comment by ricab** [comment]
What image are you using to launch multipass instances? 

I have no idea why cloud-init doesn't use your ISO. Perhaps you need to specify a different uri for the mirror? Something like in [these examples](https://cloudinit.readthedocs.io/en/latest/reference/examples.html#add-primary-apt-repositories), maybe?

This is all beyond Multipass AFAICT. Is there any improvement you are asking of Multipass specifically?

**Comment by mturnaviotov** [comment]
i use "ubuntu-22.04.3-live-server-amd64.iso. i provided link to my provisioning cloudinit repo [direct link to cloudinit yaml here](https://github.com/mturnaviotov/provisioning/blob/main/templates/cloud-init.yaml)

**Comment by ricab** [comment]
OK. Well, I am still unable to identify anything specific to Multipass, so I am going to close this now. Please reopen if you have a specific request for us.

**Comment by mturnaviotov** [comment]
but why this issue is closed, because we have an apt related time out in steps which install system and kernel before subiqity install all other described packages? 
bultin/cmd-curthooks: installing kernel : FAIL

**Comment by ricab** [comment]
Hi @mturnaviotov, I closed the issue because I could not identify anything concerning Multipass. IIUC you are using a custom image that installs stuff with Subiquity and applies a complex cloud-init. When attempting this, you report apt timeouts or failure to install the kernel. This all appears to be entirely outside the intervention of Multipass.

Again, is there anything Multipass can do for you? Anything it is doing wrongly? Any capability that you would like it to have?

**Comment by mturnaviotov** [comment]
i'm a only user of Cloudinit and don't know about parts of it (
if you can help me to route me to a related part of cloud-init which help me with my issue solve - I will be glad to hear. thank you
