### ISSUE TITLE
Add multipass to `App Paths` instead of `PATH`

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3369]
**What are you trying to do?**
`PATH` can become too long and installer will give you this warning:
![PATH too long error](https://github.com/canonical/multipass/assets/5204968/13cb5c3f-bec1-4664-b31f-0df6bfa9391d)

Using `App Paths` instead of `PATH` will avoid this problem.

**What's your proposed solution?**
Adding something like in installer (really easy): https://github.com/thonny/thonny/blob/e9b8b82f671f4cfee8c9042569706d200d26da96/packaging/windows/inno_setup.iss#L103-L108

**Additional context**
https://learn.microsoft.com/en-us/windows/win32/shell/app-registration

**Comment by ricab** [comment]
Thanks for the suggestion @soredake.

**Comment by soredake** [comment]
Oops, my bad, powershell/pwsh do not use App Paths at all, they only use PATH.
