### ISSUE TITLE
Add `--login` option to `multipass exec` command

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3375]
**What are you trying to do?**
Would be nice to have `--login` option in `multipass exec` command so shell with login parameter (`-l` for bash) so it will source ~/.profile.

WSL have option for this - `wsl --shell-type login`

**What's your proposed solution?**
Adding `--login` option to `multipass exec` command.

**Additional context**
https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell

**Comment by luis4a0** [comment]
Hi @soredake. It is indeed a good idea for some use cases. But this can be implemented without an extra option, by calling `multipass exec instance-name -- bash --login -c "commands"`. I think the simplicity of this does not justfify adding a new command to the command-line interface. Thanks for the proposal, anyway!
