### ISSUE TITLE
Multipass starting...

### ISSUE THREAD

**Issue by ggrisandi** [canonical/multipass#3378]
After reboot, multipass will go to starting state...and wait...wait...wait...

PS C:\Windows\system32> multipass list
Name                    State             IPv4             Image
quickstart              Starting          --               Ubuntu 22.04 LTS

PS C:\Windows\system32> multipass version
multipass   1.13.0+win
multipassd  1.13.0+win

PS C:\Windows\system32> multipass info --all
Warning: the `--all` flag for the `info` command is deprecated. Please use `info` with no positional arguments for the same effect.
Name:           quickstart
State:          Starting
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     6d6af17f28c8 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

PS C:\Windows\system32> multipass get local.driver
hyperv

**Comment by luis4a0** [comment]
Yeah, whatever format. Evtx is OK. Thanks!

**Comment by ggrisandi** [comment]
[multipass.zip](https://github.com/canonical/multipass/files/13997734/multipass.zip)

**Comment by luis4a0** [comment]
Hi @ggrisandi, thanks for the logs. I see two failures in the logs. One is that Multipass couldn't access the network, so I'd check if networking is working OK (we use the local network to connect to the instances). The other issue has to do with failures in PowerShell commands, so I'll check if PowerShell is working properly. Can you please check these two issues? Thanks!

**Comment by townsend2010** [comment]
Hi @ggrisandi!

Just following up to see if you can provide the answers for the questions that @luis4a0 asked?

**Comment by ggrisandi** [comment]
Tnks Luis,
sorry for my late replay, but I was in holiday...

previously my request, for attempt to resolve these problems, I had also
tried to uninstall multipass and recreate the image I used (entando
platform) without success...
and of course, my PC was correctly connected to network as well PowerShell
was running...
from some days, magically, everything started to working again....I don't
know how....maybe some configuration was recovered...


Il giorno gio 25 gen 2024 alle ore 13:57 Luis Peñaranda <
***@***.***> ha scritto:

**Comment by luis4a0** [comment]
Hi @ggrisandi, thanks! I'll close this ticket now, but don't hesitate in reopening if the problem occurs again.
