### ISSUE TITLE
[regression] multipass aliases command throws segmentation fault

### ISSUE THREAD

**Issue by minhio** [canonical/multipass#3383]
**Describe the bug**
`multipass aliases` command throws `segmentation fault` after launching the `docker` blueprint, if and only if there are no other aliases defined.

**To Reproduce**
Given there are no aliases defined and `multipass aliases` should yield `No aliases defined.`
1. launch an instance of the `docker` blueprint with `multipass launch docker`
2. execute `multipass aliases`, `segmentation fault` happens here
3. create an alias with `multipass alias docker:hello`
4. execute `multipass aliases`, back to normal, no errors here

**Expected behavior**
`multipass aliases` should return list of aliases without error

**Additional info**
- OS: macOS 14.2.1
- `multipass version`
  - `multipass   1.13.0+mac`
  - `multipassd  1.13.0+mac`
- `multipass info --all`
  - Name:           docker
State:          Running
Snapshots:      0
IPv4:           192.168.101.24
                172.17.0.1
Release:        Ubuntu 22.04.3 LTS
Image hash:     f885a8e8f62a (Ubuntu 22.04 LTS)
CPU(s):         2
Load:           0.97 0.46 0.17
Disk usage:     2.5GiB out of 38.7GiB
Memory usage:   254.7MiB out of 3.8GiB
Mounts:         /Users/minh/multipass/docker => docker
                    UID map: 501:default
                    GID map: 20:default
- `multipass get local.driver`
  - `qemu`

**Comment by andrei-toterman** [comment]
Hey, @minhio! Indeed, I can reproduce this. And it doesn't seem to happen in 1.12.2. We'll come up with a fix as soon as possible. Thanks for reporting this!
