### ISSUE TITLE
multipass not found, after proper installation and after updating PATH

### ISSUE THREAD

**Issue by nerminba** [canonical/multipass#3406]
**Describe the bug**
Well first the install application failed/could not add multipass to PATH, so I added it manually as suggested in another issue. Now testing multipass in its own CLI, it can't find its path. See the screenshot I attached it showcases the problem exactly. I've restarted the windows after installing multipass, that did not help. What can I do here so that I can run multipass commands in this CLI that pops up when I right click and "Open Shell"

**Additional info**
 - OS: Win 11 Pro
 - `multipass version`
![image](https://github.com/canonical/multipass/assets/443080/8a7545d9-8029-4b20-bafa-45b4b82d4a74)

**Additional context**
![multipass](https://github.com/canonical/multipass/assets/443080/f850a605-bde4-4dec-9bce-3eb8be695de1)

**Comment by sharder996** [comment]
You are trying to invoke Multipass from within a Multipass instance.
Instead, open a command prompt or powershell window and invoke Multipass from there.
