### ISSUE TITLE
It should be possible to uninstall from Apps/Installed Apps

### ISSUE THREAD

**Issue by nerminba** [canonical/multipass#3407]
**Describe the bug**
The problem
![image](https://github.com/canonical/multipass/assets/443080/4cbe0124-b800-496f-8016-f5eff7d4f2bb)

If Uninstall.exe is already shipped with multipass, it should be possible to uninstall from Windows add/remove programs as well.

**Additional info**
 - OS: Win 11 pro
- multipass latest version

**Comment by sharder996** [comment]
Hi @nikocraft,
You mentioned in your other bug report that you had some trouble installing Multipass. During installation, a registry key should have been created for the purpose of telling Windows where to find the uninstaller. Best thing I can suggest is to try reinstalling Multipass and seeing if it works then.

**Comment by sharder996** [comment]
Hey @nikocraft, judging from your reaction to my above comment this issue has been resolved for you? If so, I will close this issue.
