### ISSUE TITLE
[bug] ssh/scp timeout

### ISSUE THREAD

**Issue by edwardsun** [canonical/multipass#3427]
**Describe the bug**
I installed tailscale to connect guest vm with all my other machines
1. when I use "scp" on guest vm to copy other machines' files to guest vm (docker blueprint), I noticed the scp always hangs after a couple of seconds, even though initially it does transfer data. 
2. The same situation applies when I use "scp" on other machines to connect to guest vm.
3. When I ssh to guest machine from other machines, the only success moments are when I actively "multipass shell guestmachine" on the host.

I'm wondering if the guest vm can be on automatic hibernation, or there is some settings issue on ssh. (should not be an sshd issue because case 1 does not require guest vm sshd)

**Additional info**
 - OS: Windows 11 Home Edition
- `multipass version` : multipass   1.13.1+win
- `multipass info --all` :
Name:           docker
State:          Running
IPv4:           172.17.0.1
                100.100.249.26
Release:        Ubuntu 22.04.4 LTS
Image hash:     fa2146bb04e5 (Ubuntu 22.04 LTS)
CPU(s):         2
Load:           0.00 0.02 2.49
Disk usage:     5.0GiB out of 38.7GiB
Memory usage:   285.7MiB out of 3.8GiB
Mounts:         --
- `multipass get local.driver`: virtualbox

**Comment by andrei-toterman** [comment]
Hi, @edwardsun! Can you give more details about how the operations are failing? Do they have any error messages? You mentioned that you can only shell into a vm by running `multipass shell`. If you want to use ssh directly, you will need to add your own ssh key to the vm, as multipass uses its own private key for `shell`. Did you do that? I can provide you with instructions if needed.

**Comment by townsend2010** [comment]
Hi @edwardsun!

Could you please provide the answers asked [here](https://github.com/canonical/multipass/issues/3427#issuecomment-1979532812)?  We well close this issue in approximately one week if we don't hear back from you.  Thanks!

**Comment by townsend2010** [comment]
Since we've no response to our question, I'm going close.  Please feel free to reopen with the requested info or open a new issue.  Thanks!
