### ISSUE TITLE
[hyper-v] Multipass reports stale IPs after direct shutdown

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3438]
**Describe the bug**
Multipass shows a stale IP for Hyper-V instances, along with the actual IP, after shutting down an instance *directly*, i.e. without going through Multipass's stop RPC. The old IP is kept around even after Multipass realizes that the instance is stopped (e.g. with `multipass list`). It is then included in `list`/`info` results after the instance starts anew.

**To Reproduce**
This can be reproduced  with something like `sudo shutdown -h now` or by shutting down the instance directly with Hyper-V. For instance:
```
PS C:> multipass ls
Name                    State             IPv4             Image
godlike-kestrel         Running           172.21.4.179     Ubuntu 22.04 LTS
PS C:> multipass exec -n godlike-kestrel -- sudo shutdown -h now
PS C:> multipass ls
Name                    State             IPv4             Image
godlike-kestrel         Running           172.21.4.179     Ubuntu 22.04 LTS
PS C:> multipass ls
Name                    State             IPv4             Image
godlike-kestrel         Stopped           --               Ubuntu 22.04 LTS
PS C:> multipass start godlike-kestrel
PS C:> multipass ls
Name                    State             IPv4             Image
godlike-kestrel         Running           172.21.4.179     Ubuntu 22.04 LTS
                                          172.21.4.237
```

**Additional info**
 - OS: Windows
- `multipass version`: 1.13.0+win
- `multipass get local.driver`: hyperv

**Comment by townsend2010** [comment]
Probably either the same issue reported in #3354 or very related. @ricab, I'll let you determine if you want to dup this to that issue or leave these separate. :slightly_smiling_face:

**Comment by ricab** [comment]
Oops, you're right.

**Comment by ricab** [comment]
Duplicate of #3354
