### ISSUE TITLE
Is there any way to launch older release of ubuntu?  to be more specific, it's 16.04.7 LTS ubuntu that I want to install but I could only find the newer ones in the documentation

### ISSUE THREAD

**Issue by sushilkhadkaanon** [canonical/multipass#3443]
To be more specific, it's 16.04.7 LTS ubuntu that I want to install but I could only find the newer ones in the documentation

**Comment by townsend2010** [comment]
Hi @sushilkhadkaanon!

Older releases that are EOL'd, ie, "unsupported" will not show up by default in Multipass.  That said, it is possible to *try* launching these by issuing `multipass launch 16.04`.  The Multipass team does not make any guarantees that "unsupported" images will launch successfully.  

You can see the full list of images using `multipass find --show-unsupported`.
