### ISSUE TITLE
No Ubuntu 24.04 devel image for Multipass on Windows & macOS

### ISSUE THREAD

**Issue by cppservergit** [canonical/multipass#3450]
**What are you trying to do?**
I want to create a VM using devel image, Ubuntu 24.04 on Windows 10 Pro w/Hyper-V
I am using latest multipass for Windows 10/11 Pro: 
```
multipass   1.13.1+win
multipassd  1.13.1+win
```

I can see this image when using `multipass find` on Ubuntu 22.04, but it is not listed when using Multipass on Windows.

**What's your proposed solution?**
To provide the same images available for Multipass on Linux

**Additional context**
The is the list of images available for multipass 1.13.1 on Windows:
```
Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20211124         Ubuntu Core 18
core20                                        20230119         Ubuntu Core 20
core22                                        20230717         Ubuntu Core 22
20.04                       focal             20240306         Ubuntu 20.04 LTS
22.04                       jammy,lts         20240319         Ubuntu 22.04 LTS
23.10                       mantic            20240319         Ubuntu 23.10
appliance:adguard-home                        20200812         Ubuntu AdGuard Home Appliance
appliance:mosquitto                           20200812         Ubuntu Mosquitto Appliance
appliance:nextcloud                           20200812         Ubuntu Nextcloud Appliance
appliance:openhab                             20200812         Ubuntu openHAB Home Appliance
appliance:plexmediaserver                     20200812         Ubuntu Plex Media Server Appliance

Blueprint                   Aliases           Version          Description
anbox-cloud-appliance                         latest           Anbox Cloud Appliance
charm-dev                                     latest           A development and testing environment for charmers
docker                                        0.4              A Docker environment with Portainer and related tools
jellyfin                                      latest           Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media.
minikube                                      latest           minikube is local Kubernetes
ros-noetic                                    0.1              A development and testing environment for ROS Noetic.
ros2-humble                                   0.1              A development and testing environment for ROS 2 Humble.
```

Thank you very much.

**Comment by townsend2010** [comment]
Hi @cppservergit!

Thank you for the enhancement request.  The decision to not allow the devel image on both Windows and macOS is a corporate decision.  I tried to bring this up with upper management a few months ago and was struck down.  I won't won't get into all of the details as to why, but just understand that I did try.  That said, I will leave this open in hopes that maybe it can get some more attention and change some minds :slightly_smiling_face:

**Comment by cppservergit** [comment]
Thank you for such an honest reply, it made me scratch my head wondering why? I suspect the devel image may not be stable enough to run on hyper-v, because being Canonical so cooperative with Microsoft, that's the only reason I can imagine. In any case, it's only a matter of a few weeks before the next LTS release.

**Comment by colinmarc** [comment]
Hi, 24.04 has been released now :) Is there any chance the image could be made available to `multipass launch` on macOS?

**Comment by holta** [comment]
> Yes, it will be enabled in the upcoming 1.14 release. Thanks!

Will this include pre-release versions of Ubuntu like 24.10, ideally with Multipass on Windows too ?!

**Comment by townsend2010** [comment]
> Will this include pre-release versions of Ubuntu like 24.10, ideally with Multipass on Windows too ?!

Unfortunately, only on Linux.  Windows and macOS are a no go for reasons I pointed out at https://github.com/canonical/multipass/issues/3450#issuecomment-2023277984.  Not my decision...
