### ISSUE TITLE
Cannot start correctly instance after fresh install on Windows 11 (stuck for minutes at "starting", then timeout)

### ISSUE THREAD

**Issue by david-77** [canonical/multipass#3451]
**Describe the bug**
Instance stuck at "starting" for minutes, and then the following message appears :
launch failed: The following errors occurred:
microk8s: timed out waiting for response

I found other people discussing the same issue, and I tried : 
- deleting the hosts.ics file
- uninstall Mulitpass
- rebooted (several times) the computer
- stopping WSL 2 (wsl --shutdown)
- reinstalling (several times) multipass
- retried the process to create the instance
- tried with other image (mantic) 

Every time, i have the same issue.
I need to keep WSL 2 (for docker desktop), so I can't uninstall it.
Is there any way to make it work without uninstalling WSL 2 ?

**To Reproduce**
How, and what happened?
1. `Download Mulitpass installer for Windows multipass-1.13.1+win-win64.exe`
2. Install it as Administrator
3. Follow 'MicroK8s' installation via Multipass: https://microk8s.io/docs/install-multipass
4. In my PowerShell, type the following command :  multipass launch --name microk8s-vm --mem 4G --disk 40G
5. Displays image download, configuration, and instance starting
6. It stays there at "starting microk8s-vm ...."

**Expected behavior**
What did you expect to happen?
The instance to starts correctly

**Logs**
Found this entry in windows event log, seems interesting : 
[daemon] Cannot open ssh session on "microk8s-vm" shutdown: ssh connection failed: 'Failed to resolve hostname microk8s-vm.mshome.net (Hôte inconnu. )'

**Additional info**
 - OS: Windows 11 x64
- `multipass version 1.13.1+win-win64.exe`
- `multipass info --all` :  
 Warning: the `--all` flag for the `info` command is deprecated. Please use `info` with no positional arguments for the same effect.
[2024-03-27T18:30:45.198] [error] [client] Caught an unhandled exception: invalid utf8
- `multipass get local.driver`
    hyperv

**Additional context**
Windows 11 x64
WSL 2 activated
Docker Desktop

![2024-03-27 18_24_58-Clipboard](https://github.com/canonical/multipass/assets/46008203/560902b0-3f50-4a45-8923-8da1742f4e44)
![2024-03-27 18_16_26-Clipboard](https://github.com/canonical/multipass/assets/46008203/a868a7b1-e589-46a9-b426-dd2632d521aa)

**Comment by sharder996** [comment]
Hi @david-77, I know you mentioned that you tried deleting the `hosts.ics` file, but it still looks like there might be a problem with the file. See the Multipass docs on [stale internet connection sharing lease](https://multipass.run/docs/troubleshoot-networking#heading--stale-internet-connection-sharing-lease).

Can you either verify that there are no problems with the file or paste the contents here?

**Comment by david-77** [comment]
Hi @sharder996 ,
Thanks for your reply.
I've deleted,edited multiple times the hosts.ics file (as admin)
Here its content for now : 

    # Copyright (c) 1993-2001 Microsoft Corp.
    #
    # This file has been automatically generated for use by Microsoft Internet
    # Connection Sharing. It contains the mappings of IP addresses to host names
    # for the home network. Please do not make changes to the HOSTS.ICS file.
    # Any changes may result in a loss of connectivity between machines on the
    # local network.
    #
    172.18.128.1 mycomputername.mshome.net # 2029 3 1 26 16 45 0 535

Once or twice i saw this file with a added line for the instance, such as 
     `172.xxx.yyy.zzz  microk8s-vm.mshome.net`

The file was corrupted just once (the first time I think). But after deleting it and rebooted my machine, it always seemed to be ok.

**Comment by sharder996** [comment]
Do you happen to have internet connection sharing turned on?

**Comment by david-77** [comment]
Great !!!!!
Thanks a lot !
Internet Sharing was disabled on the hyperv adapter, and once I enabled it and reboot the computer : tada ! (french way to express a little victory ;)
Thanks again !!!!
