### ISSUE TITLE
Multipass Installation Issue with Windows Profile Containing Multilingual Characters

### ISSUE THREAD

**Issue by sionjlewis** [canonical/multipass#3452]
**Describe the Bug**

I am unable to install Multipass using a Windows profile that contains **multilingual characters**. I **believe** this had been fixed in 2022, but that bug seems to have crept back in.

As a workaround for the installer errors, I used another profile to install Multipass, and that works as expected. However, that is not ideal due to having everything else set up in my main profile. I then **copied** the `multipass_cert.pem` and `multipass_cert_key.pem` into my main profile, and this is what the error looks like:

```
C:\Users\SiônJLewis>multipass version
[error] [client] Caught an unhandled exception: failed to open file 'C:/Users/SiônJLewis/AppData/Local/multipass-client-certificate/multipass_cert.pem': No such file or directory(2)
```

It would appear that neither the installer nor the application can correctly resolve my **ô** character.

**To Reproduce**
1. Create a **Windows 10 or 11 profile** containing a character from the **'Latin Extended-A'** character set.
2. Note the error when trying to create/deploy the two `.pem` files.

**Expected Behavior**
I would like to be able to run the installer and application from my **SiônJLewis** profile.

**Additional Info**
- **OS**: Windows 10
- **Multipass Version**: 1.13.1+win-win64

**Comment by sharder996** [comment]
Hi @sionjlewis,
Yes, this is an issue we are aware of on Windows. It has already been reported in #1314, so I am going to close this issue as a duplicate. Feel free to reopen if your issue is fundamentally different though.
