### ISSUE TITLE
Open shell failed - Failed to fdwalk: Operation not permited

### ISSUE THREAD

**Issue by maxirobaina** [canonical/multipass#3459]
**Describe the bug**
Open shell console failed with the message "Failed to execute child process "bash": Failed to fdwalk: Operation not permited

**To Reproduce**
How, and what happened?
1. From `multipass ...` desktop indicator, Open Shell from menu
2. When bash console is open show this error message

![2024-04-03_18-24](https://github.com/canonical/multipass/assets/578586/99e8f843-57c5-460b-a384-67166a3e1b5b)

**Logs**

[multipass.log](https://github.com/canonical/multipass/files/14858670/multipass.log)

**Additional info**
 - OS: Ubuntu 20.04
- `multipass version` 1.13.1
- `multipass get local.driver` qemu
- `multipass info --all`

```
Name:           primary
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/maxi => Home
                    UID map: 1000:default
                    GID map: 1000:default

Name:           caktus
State:          Running
Snapshots:      0
IPv4:           10.27.50.105
Release:        Ubuntu 20.04.6 LTS
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
CPU(s):         2
Load:           0.00 0.00 0.00
Disk usage:     2.9GiB out of 9.6GiB
Memory usage:   161.9MiB out of 1.9GiB
Mounts:         /home/maxi/databases => /home/ubuntu/databases
                    UID map: 1000:default
                    GID map: 1000:default

```

**Comment by ricab** [comment]
Hi @maxirobaina, does `multipass shell caktus` work on a regular terminal?

We are going to release an entire new GUI soon which will have an integrated terminal. This will obsolete the current desktop indicator GUI along with any bugs that are specific to it.

**Comment by maxirobaina** [comment]
Hi @ricab 

> Hi @maxirobaina, does `multipass shell caktus` work on a regular terminal?
Yes, it works.

**Comment by ricab** [comment]
OK, then I am going to close this as it will be fixed in the next release.
