### ISSUE TITLE
aliases not working

### ISSUE THREAD

**Issue by minhio** [canonical/multipass#3472]
**Describe the bug**
I got a new MacBook Air M3 (old laptop was MacBook Pro M1), installed the latest version of multipass (1.13.1+mac), and aliases doesn't seems to be working anymore. I don't remember needing to add anything to PATH on my previous installations to get aliases to work. And I can't seems to find any documentations on where aliases are stored (at least not for Mac) so that I can add that to PATH manually

**To Reproduce**
How, and what happened?
1. `brew install --cask multipass`
1. `multipass launch docker`
1. `docker` -> `zsh: command not found: docker`

**Expected behavior**
What did you expect to happen?
the docker alias to work without needing to manually add aliases directory to PATH

**Logs**
N/A

**Additional info**
 - OS: macOS 14.4.1
- `multipass version`
  - `multipass   1.13.1+mac`
  - `multipassd  1.13.1+mac`
- `multipass get local.driver`
  - `qemu`

**Comment by luis4a0** [comment]
Hi @minhio, thanks for reporting. I think your issue is related to [this](https://github.com/canonical/multipass/pull/3388). No alias message was shown, It was fixed and will be released in the next version of Multipass. What happened is that the message was never displayed and you didn't set the `$PATH`. Basically, the message would be this:
```
You'll need to add this to your shell configuration (.bashrc, .zshrc or so) for
aliases to work without prefixing with multipass:

PATH="$PATH:/Users/<yourusername>/Library/Application Support/multipass/bin"
```

So, basically, you set the path and aliases will work. Please confirm this solves your issue so I can close the ticket. Thanks!

**Comment by minhio** [comment]
> Hi @minhio, thanks for reporting. I think your issue is related to [this](https://github.com/canonical/multipass/pull/3388). No alias message was shown, It was fixed and will be released in the next version of Multipass. What happened is that the message was never displayed and you didn't set the `$PATH`. Basically, the message would be this:
> 
> ```
> You'll need to add this to your shell configuration (.bashrc, .zshrc or so) for
> aliases to work without prefixing with multipass:
> 
> PATH="$PATH:/Users/<yourusername>/Library/Application Support/multipass/bin"
> ```
> 
> So, you must set the path and aliases will work. Please confirm this solves your issue so I can close the ticket. Thanks!

ahh gotcha, that was it, thank you

**Comment by svandenhoek** [comment]
Ran into the same issue (though indeed also got it fixed). Any chance the docs (on https://multipass.run/docs/using-aliases#heading--macos) will be updated to include the specific path?
