### ISSUE TITLE
Give the option to create your own username instead of being stuck with the default "ubuntu".

### ISSUE THREAD

**Issue by andrewhong04** [canonical/multipass#3491]
**What are you trying to do?**
Give the option to create your own root user with a custom username instead of being stuck with the default "ubuntu".

**What's your proposed solution?**
`multipass launch lts --username andrew`

**Comment by andrei-toterman** [comment]
Hi, @novialriptide! Thanks for the suggestion! For the time being, you can use the `--cloud-init` option to pass some configuration to create the users you want. You can read more about the schema of the config and see some examples here: https://cloudinit.readthedocs.io/en/latest/reference/modules.html#users-and-groups

**Comment by novialriptide** [comment]
Thank you @andrei-toterman for the quick response. Are you open to the idea being worked on? I would like to give my best efforts to work on this issue.

**Comment by andrei-toterman** [comment]
@novialriptide, is there some particular reason you'd really need the username to be different or is it simply a cosmetic issue?
In case you find using a cloud-init file cumbersome, you can use a bash 'here string' like so:
```bash
multipass launch --cloud-init - <<< 'users: [name: andrei]'
```

**Comment by novialriptide** [comment]
@andrei-toterman, just a cosmetic issue.

**Comment by andrei-toterman** [comment]
Then, at least for the moment, I don't think we'd like to integrate this feature. The reason for this is to avoid feature creep. If we allow setting the username through a flag, this could raise the question of what other users configurations should be set through flags, like groups, passwords, keys etc.
If someone wants to set the username, they would use the `--username` flag. But if they also want to set a password, then suddenly they have to go back to cloud-init.
And this would split the CLI experience into two: configuring users through the flags that we support or, in the case of flags we don't support, fall back on cloud-init.

Still, maybe in the future we might consider this again. If, for example, we will allow users to run other distributions besides Ubuntu, then I think it would be strange to have an `ubuntu` username on a Fedora VM.

So thanks again for the suggestion, but I will close this for now. Have a nice day!
