### ISSUE TITLE
Inability to SSH in as root

### ISSUE THREAD

**Issue by computershateme** [canonical/multipass#3494]
**Describe the bug**
Inability to SSH in as root

**To Reproduce**
1. Set /etc/ssh/sshd_config to allow root login and restart ssh on instance
2. Run the command sudo multipass exec instance-name -- bash -c "echo `cat path/to/id_rsa.pub` >> /root/.ssh/authorized_keys” on host, get back an empty line
3. Try to login as root: sudo ssh -X root@xx.xx.xx.xx get back "SSH Permission denied (publickey)"

**Expected behavior**
SSH into instance as root user

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - _OS_: 14.4.1 (23E224)
- _multipass version_: multipass   1.13.1 & multipassd  1.13.1
- _multipass get local.driver_: lxd

**Additional context**

**Comment by andrei-toterman** [comment]
Hey, @computershateme! What you want to do should be entirely possible. Are you sure the key did actually end up in `/root/.ssh/authorized_keys`? Just to clarify, do you want to log in as root using your own user's key or does the root user on your system have a key that you're trying to use?
If it's the former, try this:
```bash
multipass exec instance-name -- sudo bash -c "echo `cat ~/.ssh/id_rsa.pub` >> /root/.ssh/authorized_keys"
```
if it's the latter, try this:
```bash
multipass exec instance-name -- sudo bash -c "echo `sudo cat /root/.ssh/id_rsa.pub` >> /root/.ssh/authorized_keys"
```

**Comment by computershateme** [comment]
Awesome, thank you so much. Apparently my keys were not getting through to the root user because I wasn't putting the sudo in front of bash or cat. Thank you and you can close this ticket.

**Comment by andrei-toterman** [comment]
I'm glad it worked!
