### ISSUE TITLE
Better updating UX - help prevent machine deletion

### ISSUE THREAD

**Issue by lllama** [canonical/multipass#3515]
Currently, when an update is performed (on Windows; unknown on other platforms) the installer first asks to remove the existing installation. As part of removing the old installation, the user is prompted as to whether they would like to remove their existing VMs.

Unfortunately, this means that a single mis-click could result in all of the VMs being removed as part of an upgrade.

Ideally the user should either have to confirm again that they wish to remove all the data, or the installer should have an `/update` flag or similar that will prevent the question from being asked as part of an upgrade. (Having battled with Wix to create installers, I know that this isn't "just" a thing that can be added but it would be very useful to prevent data loss as part of an upgrade.)

**Comment by sharder996** [comment]
Hi @lllama, we are currently in the process of overhauling the installer on Windows and the behavior you have described is no longer a part of the upgrade experience. You should be seeing the new installer in the near future.
