### ISSUE TITLE
brew install multipass  Installation failed

### ISSUE THREAD

**Issue by White957** [canonical/multipass#3518]
brew install multipass
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/afbc122fa14873307ac0b448134d70e9c0bff771/Casks/m/multipass.rb
Already downloaded: /Users/bob/Library/Caches/Homebrew/downloads/3b9a7919d1ae7f28a5c0a6d1a7fddd9dd202c86043d477f3e76e0de72a98f0b9--multipass.rb
Warning: Cannot verify integrity of '3b9a7919d1ae7f28a5c0a6d1a7fddd9dd202c86043d477f3e76e0de72a98f0b9--multipass.rb'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "be45d9153cddf7cb5156ed3ab2dd40108787a972db92638a18e067d53b990d82"
==> Downloading https://github.com/canonical/multipass/releases/download/v1.13.1/multipass-1.13.1+mac-Darwin.pkg
Already downloaded: /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
==> Installing Cask multipass
==> Running installer for multipass with sudo; the password may be necessary.
Password:
installer: Package name is multipass
installer: Installing at base path /
installer: The install failed. (安装器遇到了一个错误，导致安装失败。请联系软件生产企业以获得帮助。 运行软件包“multipass-1.13.1+mac-Darwin.pkg”的脚本时出错。)
==> Purging files for version 1.13.1 of Cask multipass
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=bob USER=bob USERNAME=bob -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/multipass/1.13.1/multipass-1.13.1+mac-Darwin.pkg -target /` exited with 1. Here's the output:
installer: Package name is multipass
installer: Installing at base path /
installer: The install failed. (安装器遇到了一个错误，导致安装失败。请联系软件生产企业以获得帮助。 运行软件包“multipass-1.13.1+mac-Darwin.pkg”的脚本时出错。)

**Comment by White957** [comment]
Security settings have been attempted to allow and restart the system

**Comment by White957** [comment]
Yes, I have tried but also failed

**Comment by White957** [comment]
@townsend2010  This is the installation information displayed under debug. Can you identify any issues?

brew install --debug multipass
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading multipass
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading multipass
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading multipass
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/0366e46578dee6b5f92d6a6a0d2ccab15b15fe84/Casks/m/multipass.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/0366e46578dee6b5f92d6a6a0d2ccab15b15fe84/Casks/m/multipass.rb
Already downloaded: /Users/bob/Library/Caches/Homebrew/downloads/06bea999e951d3f66da8820fabcc7d710fe0af4286343f86bc0b64797e203b7a--multipass.rb
==> Downloading https://github.com/canonical/multipass/releases/download/v1.13.1/multipass-1.13.1+mac-Darwin.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/canonical/multipass/releases/download/v1.13.1/multipass-1.13.1+mac-Darwin.pkg
Already downloaded: /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
==> /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg is quarantined
/usr/bin/env hdiutil imageinfo -format /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
==> Installing Cask multipass
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
==> Verifying Gatekeeper status of /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
==> /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg is quarantined
==> Propagating quarantine from /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg to /opt/homebrew/Caskroom/multipass/1.13.1
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;6634809d\;Homebrew\\x20Cask\;D2E4AF01-53C7-45F6-8C6B-D251F4ED5333
==> Creating metadata directory: /opt/homebrew/Caskroom/multipass/.metadata/1.13.1/20240505023934.735
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/multipass/.metadata/1.13.1/20240505023934.735/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for multipass with sudo; the password may be necessary.
/usr/bin/sudo -u root -E LOGNAME=bob USER=bob USERNAME=bob -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/multipass/1.13.1/multipass-1.13.1+mac-Darwin.pkg -target /
installer: Package name is multipass
installer: Installing at base path /
installer: The install failed. (安装器遇到了一个错误，导致安装失败。请联系软件生产企业以获得帮助。 运行软件包“multipass-1.13.1+mac-Darwin.pkg”的脚本时出错。)
==> Purging files for version 1.13.1 of Cask multipass
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=bob USER=bob USERNAME=bob -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/multipass/1.13.1/multipass-1.13.1+mac-Darwin.pkg -target /` exited with 1. Here's the output:
installer: Package name is multipass
installer: Installing at base path /
installer: The install failed. (安装器遇到了一个错误，导致安装失败。请联系软件生产企业以获得帮助。 运行软件包“multipass-1.13.1+mac-Darwin.pkg”的脚本时出错。)
/opt/homebrew/Library/Homebrew/system_command.rb:352:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in `block in run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:76:in `with_choices_file'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:56:in `run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:249:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:12:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:12:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:242:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'

**Comment by ricab** [comment]
It is unclear why the install failed and whether the problem extends to installing directly with our package. Please note that the brew recipe is outside of our control, so if the issue only happens there, that would be a problem to report to them.

**Comment by 123THU** [comment]
> brew install multipass ==> 正在下载https://raw.githubusercontent.com/Homebrew/homebrew-cask/afbc122fa14873307ac0b448134d70e9c0bff771/Casks/m/multipass.rb 已下载：/Users/bob/Library/Caches/Homebrew/downloads/3b9a7919d1ae7f28a5c0a6d1a7fddd9dd202c86043d477f3e76e0de72a98f0b9--multipass.rb 警告：无法验证'3b9a7919d1ae7f28a5c0a6d1a7fddd9dd202c86043d477f3e76e0de72a98f0b9--multipass.rb'。 未提供校验和。 供您参考，校验和为： sha256“be45d9153cddf7cb5156ed3ab2dd40108787a972db92638a18e067d53b990d82” ==> 下载https://github.com/canonical/multipass/releases/download/v1.13.1/multipass-1.13.1+mac-Darwin.pkg 已下载：/Users/bob/Library/Caches/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg ==> 安装 Cask multipass ==> 运行 multipass 安装程序与须藤；可能需要密码。 密码： 安装程序： 软件包名称为多遍 安装程序： 正在基本路径/ 安装程序安装： 安装失败。 (安装器遇到一个错误，安装导致失败。请联系软件生产企业寻求帮助。运行“multipass-1.13.1+mac-Darwin.pkg”的脚本时出现错误。) ==> Purging files for version 1.13.1 of Cask multipass Error: Failure while running;`/usr/bin/sudo -u root -E LOGNAME=bob USER=bob USERNAME=bob -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/multipass/1.13.1/multipass-1.13.1+mac-Darwin.pkg -target /`以 1 退出。输出如下： installer: Package name is multipass installer: Installing at base path / installer: The install failed. （安装器遇到一个错误，安装导致失败。请联系软件生产企业寻求帮助。运行“multipass-1.13.1+mac-Darwin.pkg”的脚本时出现错误。）

Hi, excues me, have you tackled this issue? I encountered this problem as well. And I have tried both brew and dirctly download from the official website. I'm using M2 and haven't figured it out.

**Comment by 123THU** [comment]
> > 酿造安装多通道==>正在下载https://raw.githubusercontent.com/Homebrew/homebrew-cask/afbc122fa14873307ac0b448134d70e9c0bff771/Casks/m/multipass.rb已下下载：/Users/bob/Library/Caches/Homebrew/downloads/3b9a7919d1ae7f28a5c0a6d1a7fddd9dd202c86043d477f3e76e0de72a98f0b9--multipass.rb警告：无法验证'3b9a7919d1ae7f28a5c0a6d1a7fddd9dd202c86043d477f3e76e0de72a98f0b9--multipass.rb'。 未提供校验和。 供您参考，校验和为： sha256“be45d9153cddf7cb5156ed3ab2dd40108787a972db92638a18e067d53b990d82” ==>下载https://github.com/canonical/multipass/releases/download/v1.13.1/multipass-1.13.1+mac-Darwin.pkg已下载：/Users/bob/Library/C疼痛/Homebrew/downloads/2d5e02353cda04cfc9432e2bd851b8701e3880602961bd905d5742ef577d9af5--multipass-1.13.1+mac-Darwin.pkg ==> 安装 Cask multipass ==> 运行 multipass 安装程序与须藤；可能需要密码。密码：安装程序：FAQ名称为多遍安装程序：正在基本路径/安装程序安装：安装失败。(安装器遇到一个错误，安装导致失败。请联系软件生产企业寻求帮助。运行“multipass-1.13.1+mac-Darwin.pkg”的脚本时出现错误。) ==> Purging files for version 1.13.1 of Cask multipass Error: Failure while running;`/usr/bin/sudo -u root -E LOGNAME=bob USER=bob USERNAME=bob -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/multipass/1.13.1/multipass-1.13.1+mac-Darwin.pkg -target /`以 1退出。输出如下： installer: Package name is multipass installer: Installing at base path / installer: The install failed. （安装器遇到错误，安装导致失败。请联系软件生产企业寻求帮助。运行“multipass-1.13.1+mac-Darwin.pkg”的脚本时出现错误。）
> 
> 你好，请问这个问题解决了吗？我也遇到了这个问题。我试过 brew 和直接从官方网站下载。我用的是 M2，但还没搞清楚。

I find this is due to the requirement for Mac 13.0 or newer, my Mac is 12.5 and it's ok to run multipass1.14 instead of 1.15
