### ISSUE TITLE
In the built-in shell, allow paste from clipboard to work

### ISSUE THREAD

**Issue by richard-teo-at-kelvin** [canonical/multipass#3525]
**What are you trying to do?**
Using the new built-in shell component in the Multipass UI. Can not paste from the clipboard.

If I run `multipass shell vm_name` in a terminal, then paste works ok as it is in a terminal.

**What's your proposed solution?**
Make the experience of the terminal the same whether from the Multipass GUI or from a terminal.

**Additional context**
None

**Comment by andrei-toterman** [comment]
Hey, @kelvin-documentation-tutorials-code! That is indeed a missing functionality, and it will be added soon. But just for curiosity, how would you like to be able to paste text? Different terminals on different platforms have various ways e.g. Control+V, Control+Shift+V, Shift+Insert, Right Click etc. What about copying?

**Comment by kelvin-documentation-tutorials-code** [comment]
That will be great !

In Ubuntu terminal it is commonly ctrl-shift-v in the terminal. To keep this the same method would keep the experience seamless and intuitive. 

It would be also good if we can copy from the terminal too with ctrl-shift-c as well.
