### ISSUE TITLE
Allow mounting volumes in GUI while VM is running

### ISSUE THREAD

**Issue by richard-teo-at-kelvin** [canonical/multipass#3527]
**What are you trying to do?**
I would like to mount and umount a volume to the VM in the GUI while the VM is running.

This is possible in CLI and would be good if we could do the same in the Details page of the VM in GUI.

Currently once you start the VM, the mounts configure button is disabled.

**What's your proposed solution?**
Allow the same functionality for mounting a volume like in the CLI.

**Additional context**
None

**Comment by andrei-toterman** [comment]
Hey, @kelvin-documentation-tutorials-code! Yup, this implemented and will come soon in a new RC. Thanks for the suggestion!

**Comment by kelvin-documentation-tutorials-code** [comment]
Thank you @andrei-toterman. Your fast responses have been great. The new GUI is looking really good and these updates will level the usability compared to the CLI.
