### ISSUE TITLE
multipass 1.13.1 doesnt run VMs and state shows "unknown"

### ISSUE THREAD

**Issue by amitchahalgits** [canonical/multipass#3533]
**Describe the bug**
multipass 1.13.1 doesnt run VMs and state shows "unknown"
Multipass version 1.13.1
MacOS version : Sonoma 14.5(ARM64)

**To Reproduce**
How, and what happened?
1. ` mp launch jammy -n consul --cloud-init consul-server-cloud-init.yaml `
2. `multipass get local.driver`
qemu

**Expected behavior**
With all things in place, ot should be able to spin VMs as expected.

**Logs**
```
[2024-05-22T06:28:10.105] [debug] [consul] Waiting for SSH to be up
[2024-05-22T06:28:10.488] [debug] [consul] QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 2, "major": 8}, "package": ""}, "capabilities": ["oob"]}}

[2024-05-22T06:28:10.538] [debug] [consul] QMP: {"return": {}}

[2024-05-22T06:28:23.019] [debug] [consul] QMP: {"timestamp": {"seconds": 1716323303, "microseconds": 19368}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}

[2024-05-22T06:29:03.908] [debug] [consul] QMP: {"timestamp": {"seconds": 1716323343, "microseconds": 908602}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

[2024-05-22T06:38:11.689] [debug] [async task] fetch manifest periodically
[2024-05-22T06:38:11.717] [info] [VMImageHost] Did not find any supported products in "appliance"
[2024-05-22T06:40:01.980] [debug] [consul] QMP: {"timestamp": {"seconds": 1716324001, "microseconds": 979525}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

[2024-05-22T06:51:09.982] [debug] [consul] QMP: {"timestamp": {"seconds": 1716324669, "microseconds": 982085}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

[2024-05-22T06:53:11.694] [debug] [async task] fetch manifest periodically
[2024-05-22T06:53:11.698] [info] [VMImageHost] Did not find any supported products in "appliance"
```

**Additional info**
- Multipass version 1.13.1
- MacOS version : Sonoma 14.5(ARM64)
- `mp info consul`
```
mp info consul
Name:           consul
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f6bf7305207a (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

**Additional context**
NA

**Comment by SaRoKu** [comment]
Happens to me aswell, I recently udpated to 14.5 too. I had previously installed a regular ubuntu 22.04 server instance. Now it doesn't start, I've tried purging the image and launching another one, but after waiting a lot of time:

```
$ multipass launch docker
launch failed: The following errors occurred:
docker: timed out waiting for response
$ multipass list
Name                    State             IPv4             Image
docker                  Unknown           --               Ubuntu 22.04 LTS
```

**Comment by mdfranz** [comment]
Same results 

`<div class="adn ads" data-message-id="#msg-f:1799874262811057752" data-legacy-message-id="18fa701b1b389e58" style="border-left: none; padding: 0px; display: flex; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gs" style="margin: 0px; min-width: 0px; padding: 0px 0px 20px; width: initial;"><div class=""><div id=":29m" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTc5OTg3NDI2MjgxMTA1Nzc1Mnxtc2ctZjoxNzk5ODc0MjYyODExMDU3NzUyIl0.; 4:WyIjbXNnLWY6MTc5OTg3NDI2MjgxMTA1Nzc1MiJd" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem; overflow-x: hidden;"><div id=":29l" class="a3s aiL " style="direction: initial; font: small / 1.5 Arial, Helvetica, sans-serif; overflow: auto hidden; position: relative;"><div dir="ltr"><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">matt@matts-MBP ~ % multipass --version</span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">multipass<span> </span><span> <span> </span></span>1.13.1+mac</span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">multipassd<span> <span> </span></span>1.13.1+mac</span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;"><br></span></p><p style="margin: 0px; font: 14px Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">matt@matts-MBP ~ % multipass start<span> </span></span></p><p style="margin: 0px; font: 14px Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">launch failed: The following errors occurred:</span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;"></span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">primary: timed out waiting for response</span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;"><br></span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;"><br></span></p><p style="margin: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-kerning: auto; font-feature-settings: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Menlo; color: rgb(0, 0, 0);"><span style="font-variant-ligatures: no-common-ligatures;">[2024-05-23T15:43:38.268] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.<wbr>multipass/bin/multipassd --verbosity debug<br>[2024-05-23T15:43:38.314] [debug] [update] Latest Multipass release available is version 1.13.1<br>[2024-05-23T15:44:01.558] [debug] [daemon] Deleting instance: primary<br>[2024-05-23T15:44:01.558] [debug] [daemon] Instance deleted: primary<br>[2024-05-23T15:44:12.016] [debug] [daemon] Instance purged: primary<br>[2024-05-23T15:44:16.024] [debug] [qemu-system-aarch64] [9815] started: qemu-system-aarch64 --version<br>[2024-05-23T15:44:16.721] [debug] [qemu-img] [9816] started: qemu-img info /var/root/Library/Caches/<wbr>multipassd/qemu/vault/images/<wbr>noble-20240423/ubuntu-24.04-<wbr>server-cloudimg-arm64.img<br>[2024-05-23T15:44:16.739] [debug] [qemu-img] [9817] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/<wbr>instances/primary/ubuntu-24.<wbr>04-server-cloudimg-arm64.img 5368709120<br>[2024-05-23T15:44:16.758] [debug] [qemu-img] [9818] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/<wbr>instances/primary/ubuntu-24.<wbr>04-server-cloudimg-arm64.img<br>[2024-05-23T15:44:16.771] [debug] [qemu-img] [9819] started: qemu-img amend -o compat=1.1 /var/root/Library/Application Support/multipassd/qemu/vault/<wbr>instances/primary/ubuntu-24.<wbr>04-server-cloudimg-arm64.img<br>[2024-05-23T15:44:16.784] [debug] [primary] process working dir ''<br>[2024-05-23T15:44:16.784] [info] [primary] process program 'qemu-system-aarch64'<br>[2024-05-23T15:44:16.784] [info] [primary] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.<wbr>multipass/bin/../Resources/<wbr>qemu/edk2-aarch64-code.fd,if=<wbr>pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-<wbr>pci,mac=52:54:00:04:fd:36, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/<wbr>Application Support/multipassd/qemu/vault/<wbr>instances/primary/ubuntu-24.<wbr>04-server-cloudimg-arm64.img,<wbr>if=none,format=qcow2,discard=<wbr>unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/<wbr>instances/primary/cloud-init-<wbr>config.iso'<br>[2024-05-23T15:44:16.787] [debug] [qemu-system-aarch64] [9820] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/<wbr>zyxvpxvq6csfxvn_<wbr>n0000000000000/T/multipassd.<wbr>ZclatN<br>[2024-05-23T15:44:16.832] [info] [primary] process state changed to Starting<br>[2024-05-23T15:44:16.834] [info] [primary] process state changed to Running<br>[2024-05-23T15:44:16.834] [debug] [qemu-system-aarch64] [9821] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.<wbr>multipass/bin/../Resources/<wbr>qemu/edk2-aarch64-code.fd,if=<wbr>pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-<wbr>pci,mac=52:54:00:04:fd:36 -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/<wbr>Application Support/multipassd/qemu/vault/<wbr>instances/primary/ubuntu-24.<wbr>04-server-cloudimg-arm64.img,<wbr>if=none,format=qcow2,discard=<wbr>unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/<wbr>instances/primary/cloud-init-<wbr>config.iso<br>[2024-05-23T15:44:16.834] [info] [primary] process started<br>[2024-05-23T15:44:16.835] [debug] [primary] Waiting for SSH to be up<br>[2024-05-23T15:44:16.861] [debug] [primary] QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 2, "major": 8}, "package": ""}, "capabilities": ["oob"]}}<br><br>[2024-05-23T15:44:16.882] [debug] [primary] QMP: {"return": {}}<br><br>[2024-05-23T15:44:27.165] [debug] [primary] QMP: {"timestamp": {"seconds": 1716493467, "microseconds": 165754}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]<wbr>/virtio-backend"}}<br><br>[2024-05-23T15:45:07.983] [debug] [primary] QMP: {"timestamp": {"seconds": 1716493507, "microseconds": 983138}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]<wbr>"}}<br></span></p></div><div class="yj6qo"></div><div class="adL"></div></div></div><div class="WhmR8e" data-hash="0" style="clear: both;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: rgb(255, 255, 255); color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gB xu" jslog="184332; u014N:xr6bB;" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":29n">
  | ReplyForwardAdd reaction
-- | --


</div></div></div></div>`

**Comment by SaRoKu** [comment]
> Happens to me aswell, I recently udpated to 14.5 too. I had previously installed a regular ubuntu 22.04 server instance. Now it doesn't start, I've tried purging the image and launching another one, but after waiting a lot of time:
> 
> ```
> $ multipass launch docker
> launch failed: The following errors occurred:
> docker: timed out waiting for response
> $ multipass list
> Name                    State             IPv4             Image
> docker                  Unknown           --               Ubuntu 22.04 LTS
> ```

I've tried reinstalling multipass and it didn't initially work, but after rebooting (I don't really know if that solved it) it works again.

**Comment by sharder996** [comment]
Sorry, I thought those were from another user. The `NIC_RX_FILTER_CHANGED` in the logs suggests that the instance has successfully started up and initialized the network interface, just that Multipass cannot connect to it. Can you confirm that you don't have anything else running that could affect the network (VPN, macOS firewall, etc). You may have to reboot the machine to any changes take effect.

**Comment by mdfranz** [comment]
Turns out my M3 had bad memory. 😬

**Comment by sharder996** [comment]
@amitchahalgits Can you confirm whether the issue has been solved for you or not? If not, would you be able to provide me the information from the commands I gave in my previous comments to you? Otherwise, if there is no longer an issue, I will close this issue.

Thanks!

**Comment by ricab** [comment]
Closing then. Please reopen if needed.
