### ISSUE TITLE
Connection broken on 1.13.1

### ISSUE THREAD

**Issue by juditnovak** [canonical/multipass#3542]
**Describe the bug**
Connection to multipass instance got interrupted.

Syndrome was observed after removing and re-installing the `multipass` snap.
After rebooting the machine (host system, i.e. "laptop"), situation improved. 

**To Reproduce**
How, and what happened?
I've been using a multipass instace with a fully functional Juju installation bootstrapped against LXD.
(In case more info needed on the above, feel free to contact.)
NOTE: the `multipass` instance was hosting a `jammy` OS.

1. `multipass shell <instance>`
1. `cd <git_repo_local_checkout>`
1. Running tests that include long delays on charm build.
1. The connection got closed.

The above happened multiple times.
When running `multipass shell` after, on occasions the instance had to be started. Meaning that it has shut down (not only break connection).

**Expected behavior**
Keeping up `multipass` shell fully functional even after long delays.

**Logs**
Logs are difficult to follow as I've been destroying, re-creating, re-installing `multipass`.
But I think this snippet may correspond?

```
12:48 pegasus systemd[1]: snap.multipass.multipassd.service: A process of this unit has been killed by the OOM killer.
12:49 pegasus multipassd[87076]: Received signal 15 (Terminated)
12:49 pegasus multipassd[87076]: Goodbye!
12:53 pegasus multipassd[87076]: Failed checking SSHFS mount "repos" in instance 'vm-lxd-22': ssh connection failed: 'No route to host'
12:56 pegasus multipassd[87076]: process state changed to NotRunning
12:56 pegasus multipassd[87076]: error: program: qemu-system-x86_64; error: Process crashed
12:57 pegasus dnsmasq[87151]: error binding DHCP socket to device mpqemubr0
```

**Additional info**
 - OS: `jammy`, amd64
- `multipass version`: 1.13.1 (both `multipass` and `multipassd`)
- `multipass info`

```
Name:           vm-lxd-22
State:          Running
Snapshots:      0
IPv4:           10.38.193.57
                10.254.188.1
Release:        Ubuntu 22.04.4 LTS
Image hash:     1718f177dde4 (Ubuntu 22.04 LTS)
CPU(s):         12
Load:           0.08 0.25 0.27
Disk usage:     34.9GiB out of 145.3GiB
Memory usage:   3.9GiB out of 31.3GiB
Mounts:         /home/kaboca/repos => repos
                    UID map: 1001:default
                    GID map: 1001:default
```

- `multipass get local.driver`: qemu

**Comment by ricab** [comment]
As discussed elsewhere, you just went out of memory.

**Comment by georgeliao** [comment]
@ricab , is there a chance that it is related to the [memory leak issue](https://github.com/canonical/multipass/issues/3454) besides the actual consumption of the VM memory?

**Comment by ricab** [comment]
Hey @georgeliao: it is difficult to say for sure, but I think it is unlikely. There is no evidence of a leak in here and the issue you link was only reported on macOS so far. Plus, it happens over a period of time. In this case, it seems that the snap was updated and reinstalled over the course of a day. In any case, we already have that one open to investigate when we get a chance.
