### ISSUE TITLE
Transaction endpoint not connected

### ISSUE THREAD

**Issue by juditnovak** [canonical/multipass#3543]
**Describe the bug**
Editing a file from a mounted (hosting system local) volume, it was not accessible anymore.
If I recall correctly logging in and out solved the issue.

**To Reproduce**
I'm not sure how to reproduce, the issue seemed intermittent.

**Expected behavior**
Volume content being accessible.

**Logs**
I couldn't find relevant log entries.

**Additional info**
 - OS: `jammy`, amd64
- `multipass version`: 1.13.1
- `multipass info`
```
Name:           vm-lxd-22
State:          Running
Snapshots:      0
IPv4:           10.38.193.57
                10.254.188.1
Release:        Ubuntu 22.04.4 LTS
Image hash:     1718f177dde4 (Ubuntu 22.04 LTS)
CPU(s):         12
Load:           0.08 0.25 0.27
Disk usage:     34.9GiB out of 145.3GiB
Memory usage:   3.9GiB out of 31.3GiB
Mounts:         /home/kaboca/repos => repos
                    UID map: 1001:default
                    GID map: 1001:default
```
- `multipass get local.driver`: qemu

**Additional context**
No particulalry high load on the server.
![Screenshot from 2024-06-05 17-54-24](https://github.com/canonical/multipass/assets/3271248/b1e95e06-25d5-4583-9de4-6ca7904ef040)

**Comment by georgeliao** [comment]
Hi @juditnovak 
Thanks for reporting this. 
It looks like somehow the network resource is lost, so the mounted folder is no longer accessible. 
How often does this occur? 
One thing you can try when this happens is remount, that would be 
`multipass umount vm-lxd-22:repos`
`multipass mount /home/kaboca/repos vm-lxd-22:repos`

Besides this, may I ask which type of mount did you use? classic (sshfs) or native (viriofs)
To find out, you can type `mount | grep repos` in vm-lxd-22 instance. 
If it is classic, then you may want to try the native mount, which is more performant and stable. That leads to a slight different mount command line `multipass mount -t native /home/kaboca/repos vm-lxd-22:repos`.

**Comment by ricab** [comment]
Closing for lack of reply. Please reopen if appropriate.
