### ISSUE TITLE
`multipass launch 24.04` and `multipass launch noble` no longer work on Windows (multipass 1.13.1 and 1.14.0 RC1)

### ISSUE THREAD

**Issue by holta** [canonical/multipass#3553]
**To Reproduce**

Two different users, on two different continents, have independently confirmed this:

```
C:\Users\abcd>multipass launch noble
launch failed: 'noble' is not a supported alias. Please use `multipass find` for supported image aliases.

C:\Users\abcd>multipass launch 24.04
launch failed: '24.04' is not a supported alias. Please use `multipass find` for supported image aliases.

C:\Users\abcd>multipass version
multipass   1.13.1+win
multipassd  1.13.1+win
```

Conversely, `multipass launch lts` and `multipass launch` both still work to launch an Ubuntu 24.04 VM (instance), if folks need an interim workaround.

**Comment by holta** [comment]
Above report revised!  FYI Multipass instructions (pasted in above) say to use `multipass find` which provided erroneoues info:

```
C:\Users\abcd>multipass find
Image                       Aliases           Version          Description
core                        core16            20200818         Ubuntu Core 16
core18                                        20211124         Ubuntu Core 18
core20                                        20230119         Ubuntu Core 20
core22                                        20230717         Ubuntu Core 22
20.04                       focal             20240626         Ubuntu 20.04 LTS
22.04                       jammy             20240627         Ubuntu 22.04 LTS
23.10                       mantic            20240619         Ubuntu 23.10
24.04                       noble,lts         20240628         Ubuntu 24.04 LTS
...
```

**Comment by holta** [comment]
FYI the exact same problem occurs with Multipass 1.14.0 RC1 on Windows:

```
C:\Users\abcd>multipass version
multipass   1.14.0-rc1.2439+g95e4d16a3.win
multipassd  1.14.0-rc1.2439+g95e4d16a3.win
```

**Comment by georgeliao** [comment]
@holta 
Thanks for reporting this. https://github.com/canonical/multipass/issues/3519 reproted the exact same issue and it has been fixed already. It just did not go into multipass 1.14.0-rc yet. We are going to release 1.14.0 shortly and the fix will be included.

**Comment by holta** [comment]
Thanks @georgeliao!

- Interesting that Mac too is affected, not just Windows, and yet `multipass launch 24.04` works fine on Linux/Ubuntu itself 😉

- Is a July release of 1.14.0 very likely, do you think?

**Comment by georgeliao** [comment]
@holta 
Yes, likely in July.

**Comment by holta** [comment]
Thanks @georgeliao

Just FYI the snap instructions at https://github.com/canonical/multipass/releases/tag/v1.14.0-rc5 don't quite work...

![image](https://github.com/canonical/multipass/assets/2458907/72decb3e-f610-4671-85c9-402cd97d0904)

The reason is that snap's beta channel offers RC2 not RC5...

```
# snap info multipass
...
channels:
  latest/stable:    1.13.1                    2024-06-28 (12829) 122MB -
  latest/candidate: 1.13.1                    2024-07-08 (12911) 122MB -
  latest/beta:      1.14.0-rc2.2109+g92bf2a0f 2024-07-06 (12905)  64MB -
  latest/edge:      1.15.0-dev.2326+g9a9bcf83 2024-07-04 (12890)  64MB -
```

**Comment by georgeliao** [comment]
@holta 
Thanks, now the snap build should work.

**Comment by sryze** [comment]
I have the same problem with 1.14 (trying to run microk8s) on a macOS machine. 
version:

```
multipass   1.8.1+mac
multipassd  1.8.1+mac

#########################################################################################
Multipass 1.14.0 release
New GUI, bridge addition, force-stop, snapshots extended to VirtualBox

Go here for more information: https://github.com/canonical/multipass/releases/tag/v1.14.0
#########################################################################################
```
