### ISSUE TITLE
[docs] Update explanation for privileged-mounts default on windows

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3555]
**Description of documentation issue or suggestion**

> On Windows, mounts are disabled by default, as anyone with TCP access to localhost (127.0.0.1) can use Multipass, and by extension, gets access to the entire filesystem.

This is now outdated.

**Proposal to fix issue or enact suggestion**

Explain that any user beyond the installing user needs to authenticate with the daemon before it will service their requests. Add that privileged mounts are still disabled by default on Windows for historical reasons (something we may want to revisit). 

**Additional context**
https://multipass.run/docs/authenticating-clients

**Comment by ricab** [comment]
This will eventually be updated by #3593

**Comment by giuliazanchi** [comment]
Clarifications added to https://multipass.run/docs/mount in the new "Security consideration" section. 
Closing as Done.
