### ISSUE TITLE
Standardize and generalize "see also"

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3564]
**Description of documentation issue or suggestion**

Many, but not all, of our pages have a "see also" entry at the top. For example: 

- https://multipass.run/docs/configure-static-ips has the usual format
- https://multipass.run/docs/find-command doesn't have a see also
- https://multipass.run/docs/networks-command doesn't have a see also, but says "See [launch](https://multipass.run/docs/launch-command) and [additional network interfaces](https://discourse.ubuntu.com/t/additional-network-interfaces/19544) for instructions on how to use these." in the text.

Now that there is also a feedback header, having these two things as separate quotations doesn't feel quite right IMO (it looks like two headers). Some documents have a "see also" under different sections too, which I think is fine, but should be taken into account when choosing a format to avoid making it too prominent. For example: https://multipass.run/docs/create-an-instance

An alternative would be to change the format for the feedback entry.

**Proposal to fix issue or enact suggestion**

It would be good come up with a format to standardize the "see also" entry that integrates well with the feedback one. (This might be as simple as just joining the quotation entries?). Then we should apply it to pages where it is missing.

**Comment by giuliazanchi** [comment]
Hi Ricardo, thanks for raising this. I would not join the Feedback + See also sections, as they are conceptually different and have an entirely different purpose. I'll look into it and propose some alternative solutions.

**Comment by ricab** [comment]
OK. I guess what I am stumbling over is that it looks as though the documents have two headers. One possibility to distinguish would be to have a separation within the same quotation, like a horizontal line). Other ideas are welcome too, of course :slightly_smiling_face:

**Comment by giuliazanchi** [comment]
As a temporary fix, we have decided to move feedback links to the bottom of the page (see: https://multipass.run/docs/mount). The "See also" section at the top will remain as is for the time being.
