### ISSUE TITLE
Accept local.driver values regardless of the case

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3565]
For instance, `multipass set local.driver=VirtualBox` should work as well as `multipass set local.driver=virtualbox`. Also, we should probably accept "Hyper-V"/"hyper-v" along with "hyperv".

**Comment by levkropp** [comment]
>Also, we should probably accept "Hyper-V"/"hyper-v" along with "hyperv".
I think we should remove dashes, slashes, and generally any non-alphanumeric characters from being read as well.
>`multipass set local.driver=VirtualBox` should work as well as `multipass set local.driver=virtualbox`
What do you think about allowing "vbox"?

**Comment by levkropp** [comment]
On second thought, supporting "vbox" adds more complexity than it is worth and there is no official source that uses "vbox" or similar as an alias for VirtualBox anyways
