### ISSUE TITLE
Https on multipass guest under MacOS Sonoma through Port Forwarding from internet fails where curl succeeds

### ISSUE THREAD

**Issue by BainMcKay** [canonical/multipass#3576]
**Describe the bug**
Describe what your problem is.
I can CURL an apache site through portforwarding on multipass guest instance under MacOS Sonoma Host. But I can't gain. browser access. Same url and port. As well TCPDUMP on PORT packets flow for CURL, but not for Browser URL

**To Reproduce**
How, and what happened?
1. multipass ubuntu 22.04.4 instance with apache site, and letsencrypt SSL mapped to namecheap fqdn
2. From Web Cloud VM: CURL to https url works. Lists the site html. Packets flow on tcpdump port....
3. From Web Cloud VM: Browser to same https fails. browser inspect/network tab.   Packets do not flow on tcpdump port.... 
4. /var/log/apache2/access.log shows curl not https access
5. /var/log/apache2/error.log shows no errors
6. Browser>inspect>network> shows: NE_ERROR_NET_TIMEOUT

**Expected behaviour**
1. Browser same https displays the web page

**Logs**
See above

**Additional info**
 - OS: macOS 14.5 Sonoma
 
- `multipass version`: 1.13.1+mac

- `multipass info`
- Name:           primary
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f7555cd22ead (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /Users/bainmckay => Home
                    UID map: 501:default
                    GID map: 20:default

Name:           LLMAppjammy
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     39103ef4cfb1 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           RAG
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f885a8e8f62a (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           RAG-WEB
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     532d5bfdb80b (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           RAG-WEB-PRODUCTION
State:          Running
Snapshots:      1
IPv4:           192.168.64.38
                10.0.1.98
Release:        Ubuntu 22.04.4 LTS
Image hash:     f6bf7305207a (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.06 0.10 0.09
Disk usage:     15.9GiB out of 77.4GiB
Memory usage:   361.2MiB out of 7.7GiB
Mounts:         --

Name:           RAG-WEB2
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f1c6fc0bb527 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           RAG-WEB3
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f1c6fc0bb527 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           RAG-WEB4
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f1c6fc0bb527 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           RAG-WEB4v2
State:          Running
Snapshots:      11
IPv4:           192.168.64.26
                10.0.1.172
Release:        Ubuntu 22.04.4 LTS
Image hash:     40ea1181447b (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.06 0.10 0.06
Disk usage:     37.1GiB out of 77.4GiB
Memory usage:   776.1MiB out of 7.7GiB
Mounts:         --

Name:           RAG-WEBv2
State:          Running
Snapshots:      2
IPv4:           192.168.64.25
                10.0.1.213
Release:        Ubuntu 22.04.4 LTS
Image hash:     40ea1181447b (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.08 0.02 0.01
Disk usage:     4.1GiB out of 77.4GiB
Memory usage:   171.7MiB out of 7.7GiB
Mounts:         --

Name:           RAGv2
State:          Running
Snapshots:      4
IPv4:           192.168.64.24
                10.0.1.122
Release:        Ubuntu 22.04.4 LTS
Image hash:     40ea1181447b (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.08 0.05 0.04
Disk usage:     8.6GiB out of 77.4GiB
Memory usage:   468.3MiB out of 7.7GiB
Mounts:         --

Name:           ScottTest
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     c8d196b1cdd6 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           ace-elasmobranch
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f7555cd22ead (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           animated-elf
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     40ea1181447b (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           awed-curlew
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     5ecab49ff44f (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           breezy-cougar
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f7555cd22ead (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           ckan
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     08a57f69a813 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           ckan2
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     08a57f69a813 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           education-sandbox
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f1c6fc0bb527 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           glowing-killdeer
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     5ecab49ff44f (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           jobflow-dev
State:          Running
Snapshots:      0
IPv4:           192.168.64.43
                10.0.1.26
Release:        Ubuntu 22.04.4 LTS
Image hash:     ee96bbc60af2 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.00 0.00 0.00
Disk usage:     8.3GiB out of 77.4GiB
Memory usage:   191.5MiB out of 7.7GiB
Mounts:         --

Name:           kayvium-agent-server
State:          Running
Snapshots:      0
IPv4:           192.168.64.30
                10.0.1.185
Release:        Ubuntu 22.04.4 LTS
Image hash:     3d803c091384 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.26 0.14 0.10
Disk usage:     6.6GiB out of 77.4GiB
Memory usage:   534.4MiB out of 7.7GiB
Mounts:         --

Name:           khub1
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     289a20ec60e4 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khub2
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     289a20ec60e4 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khub5
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f885a8e8f62a (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khub6
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     289a20ec60e4 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khub7
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     289a20ec60e4 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khub7v2
State:          Running
Snapshots:      2
IPv4:           192.168.64.27
                10.0.1.117
Release:        Ubuntu 22.04.4 LTS
Image hash:     40ea1181447b (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.00 0.01 0.00
Disk usage:     2.5GiB out of 77.4GiB
Memory usage:   182.2MiB out of 7.7GiB
Mounts:         --

Name:           khubserv1
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     08a57f69a813 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khubserv2
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     289a20ec60e4 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khubserv3
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     289a20ec60e4 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khubtest-msu-1
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     25538a7a0254 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           khubtest4
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     25538a7a0254 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           llama3-test
State:          Running
Snapshots:      0
IPv4:           192.168.64.29
                10.0.1.91
Release:        Ubuntu 22.04.4 LTS
Image hash:     3d803c091384 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.01 0.02 0.00
Disk usage:     2.3GiB out of 77.4GiB
Memory usage:   161.7MiB out of 7.7GiB
Mounts:         --

Name:           localckan-mu
State:          Suspended
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     25538a7a0254 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           ragweb4-recovery
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     6c0830e098c7 (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           test
State:          Running
Snapshots:      0
IPv4:           192.168.64.5
Release:        Ubuntu 22.04.4 LTS
Image hash:     40ea1181447b (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     2.4GiB out of 4.8GiB
Memory usage:   143.4MiB out of 962.2MiB
Mounts:         --

Name:           universal-bobolink
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f7555cd22ead (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

- `multipass get local.driver`: **qemu**

**Additional context**

**Comment by ricab** [comment]
Hi @BainMcKay, I am afraid I don't really follow. Could you please explain what it is that you think Multipass is doing wrong?

**Comment by BainMcKay** [comment]
I found and resolved the issue. It turns out, when you go thru cable modem portforwarding from a DNS, the initial entry is to make sure the port is not blocked, and then it requires a second pass to authenticate the SSL to authorize access. The cable internet ISP is not expecting a public domain access back into the cable modem. So it dumps the NATs on the second pass, leaving the browser to time out waiting for NATs that never come.The solution? You need to access publically accessible domain sites behind your cable modem, from another cable modem. So I simply logged into my neighbours WIFI and now I can use my public domain site behind my cable modem.Thank you for the follow up.BainBain McKay CEO & Chief ScientistKayvium ***@***.***(613)668-9979                   ___________________                          KAYVIUMBeyond Search - Intelligent Applications that work the way you think                   ___________________THE CONTENTS OF THIS EMAIL ARE COPYRIGHT KAYVIUM CORPORATION 2005-2024 - ALL RIGHTS RESERVED. THIS EMAIL IS NOT TO BE FORWARDED OR SHARED WITHOUT THE PERMISSION OF KAYVIUM CORPORATIONSent from my iPhoneOn Jul 16, 2024, at 12:49 PM, Ricardo Abreu ***@***.***> wrote:﻿
Hi @BainMcKay, I am afraid I don't really follow. Could you please explain what it is that you think Multipass is doing wrong?

**Comment by ricab** [comment]
OK, well, good to know you've sorted it out.

**Comment by aaronwng** [comment]
@BainMcKay I am having the same issue, is your neighbor using the same ISP as you?
