### ISSUE TITLE
In Windows 10: multipass launch failed: Remote "" is unknown or unreachable

### ISSUE THREAD

**Issue by jjaone** [canonical/multipass#3579]
**Describe the bug**
In Windows 10 multipass launch of (Ubuntu) instance(s) fails with error:
```
launch failed: Remote "" is unknown or unreachable.
```

**To Reproduce**
1. Install multipass (1.13.1+win)
2. Run command like `multipass -vv launch "20.04" --name "u20medium" --cpus 2 --disk 100G --memory 2G` 

**Expected behavior**
Instance gets created so that with command `multipass start u20medium` it can be started.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Windows 10
- `multipass version: 1.13.1+win`
- `multipass info (another multipass Ubuntu instance only running`
```
Name:           u22small
State:          Running
IPv4:           192.168.0.24
Release:        Ubuntu 22.04.4 LTS
Image hash:     769f0355acc3 (Ubuntu 22.04 LTS)
CPU(s):         2
Load:           0.10 0.03 0.01
Disk usage:     2.7GiB out of 48.4GiB
Memory usage:   204.9MiB out of 1.9GiB
Mounts:         --
```
- `multipass get local.driver: virtualbox`

**Additional context**
I have enterprise VPN running (can not change that), but is not a problem cause that other instance was succesfully created, started with shell.

**Comment by ricab** [comment]
Hi @jjaone, we have recently fixed #3464 which caused this. It hasn't been released yet, but you can try it out in our [latest RC](https://github.com/canonical/multipass/releases/tag/v1.14.0-rc6). Otherwise, a workaround on 1.13.1 is to run `multipass find --force-update`. Does that help in your case?

**Comment by ricab** [comment]
After seeing your comments in #3074, I suspect that your issue is that Multipass just couldn't connect to the image servers for some reason (possibly the VPN setup). Since you say that you were able to create an instance, it must have succeeded at some point. Any idea what changed?

**Comment by jjaone** [comment]
For  me, this does not work:
`multipass find --force-update`

response it:
`find failed: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Operation canceled`

**Comment by ricab** [comment]
Hi @jjaone that is more evidence in favor of the same hypothesis: the daemon just can't connect to the internet, but it did at some point in the past and cached those images. 

Given the versions you show, it was able to connect no longer ago that July 10. You may be able to solve it by figuring out what changed since then that started preventing access.

**Comment by jjaone** [comment]
Yes, the problem may well be due the connectivity from Windows host to public internet (because of the corporate VPN).

To diagnose this it would be helpful to know what the addresses are multipass is trying to access when find command is run?

On the other hand, I don't understand how the find command works without that force flag and is able to download and show all the images available to my multipass client.

**Comment by ricab** [comment]
> To diagnose this it would be helpful to know what the addresses are multipass is trying to access when find command is run?

Hi @jjaone, you can find the links that it is trying to hit and failing in the logs. See [accessing logs](https://multipass.run/docs/accessing-logs). For example, https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz from your message above is one.

> On the other hand, I don't understand how the find command works without that force flag and is able to download and show all the images available to my multipass client.

Multipass fetches data on the images periodically and caches it. By default, the `find` command just returns the last cached data, which succeeds, showing that you have cached data. The `--force-update` flag forces retrieving remote information right away, which is failing. Given how out of date your cached data is, the periodic attempts to retrieve that data have been failing for a while too. However, an attempt must have succeeded in the past. That is the info that `multipass find` is showing you.

**Comment by jjaone** [comment]
Hi @ricab,

thanks for your help in diagnosing this. 

Your analysis is correct; my Windows-host in the enterprise VPN environment is able to find and download (launch) instance images only when the corporate VPN is off. 

To start and use the instance I can either I have VPN on or off and it works, but when the VPN is up (and actually in any case) I need to setup the host network adapers and networking inside the Multipass Linux with very specific configuration (netplan) of two bridged adapers then to be able to access from Multipass/Ubuntu instance both corporate networks behind the VPN (NAT) and the public internet (Bridge adapers for bot Wired and Wifi).

Any now it works (with above VPN off and on workaround) 💪

**Comment by jjaone** [comment]
Hi @ricab,

thanks for your help in diagnosing this. 

Your analysis is correct; my Windows-host in the enterprise VPN environment is able to find and download (launch) instance images only when the corporate VPN is off. 

To start and use the instance I can either I have VPN on or off and it works, but when the VPN is up (and actually in any case) I need to setup the host network adapers and networking inside the Multipass Linux with very specific configuration (netplan) of two bridged adapers then to be able to access from Multipass/Ubuntu instance both corporate networks behind the VPN (NAT) and the public internet (Bridge adapers for bot Wired and Wifi).

Any now it works (with above VPN off and on workaround) 💪

**Comment by ricab** [comment]
Thank you @jjaone, closing this now then.
