### ISSUE TITLE
Multipass in windows Server

### ISSUE THREAD

**Issue by josemtella** [canonical/multipass#3595]
**What are you trying to do?**
Execute in windows server.

**Comment by josemtella** [comment]
really multipass installs without problems on WIndows Server.
But when you run it to install an instance, it sends a message saying that you have to activate the Hyper-V feature. But Hyper-V is installed and running on the server without problems.

**Comment by georgeliao** [comment]
Hi @josemtella 

Thanks for reporting this. 

Can you follow the format of the [bug report](https://github.com/canonical/multipass/issues/new?assignees=&labels=bug%2C+needs+triage&projects=&template=bug_report.md&title=) and provide more details like the exact error message and exact multipass command you run?

**Comment by georgeliao** [comment]
Duplication of https://github.com/canonical/multipass/issues/1323
