### ISSUE TITLE
cannot install v1.14.0 with winget

### ISSUE THREAD

**Issue by uishon** [canonical/multipass#3605]
**Describe the bug**
Cannot install multipass on Windows using `winget`.
Getting this error:
```
Installer hash does not match.
```

**To Reproduce**
How, and what happened?
1. `winget install multipass`

**Expected behavior**
It should work :-).

**Logs**
```
PS C:\Users\me> winget install multipass
Found Multipass [Canonical.Multipass] Version 1.14.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/canonical/multipass/releases/download/v1.14.0/multipass-1.14.0+win-win64.exe
  ██████████████████████████████  37.6 MB / 37.6 MB
Installer hash does not match.
```

**Additional info**
 - OS: Microsoft Windows 11 Pro (10.0.22631 N/A Build 22631)
- `multipass version` 1.14.0
- `multipass info` N/A
- `multipass get local.driver` N/A

**Additional context**
N/A

**Comment by ricab** [comment]
Hi @uishon, we didn't create and don't control the WinGet package. You would need to file an issue with them. I believe this is the repository: https://github.com/microsoft/winget-pkgs

We had to update the package shortly after releasing, which is probably why the hash differs.
