### ISSUE TITLE
Installed multipass 1.14.0 on OSX but don't have --force option

### ISSUE THREAD

**Issue by avni** [canonical/multipass#3606]
**Describe the bug**
I installed multipass 1.14.0 on OSX (Sonoma 14.0) and have a suspended multipass instance. I tried to use the --force command and receive "Unknown option 'force'."

**To Reproduce**
How, and what happened?

```
X@X-MBP iiab-calibre % multipass list              
Name                    State             IPv4             Image
box-20240225            Suspended         --               Ubuntu 22.04 LTS
....
X@X-MBP iiab-calibre % multipass delete box-20240225
delete failed: Cannot stop suspended instance. Use --force to override.
X@X-MBP iiab-calibre % multipass --force delete box-20240225
Unknown option 'force'.
```

**Expected behavior**
I expected the --force option to work and the instance to be deleted.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

https://dpaste.com/5MA59LH62

**Additional info**
 - OS: OSX Sonoma 14.0
- `multipass version` 
  - multipass   1.14.0+mac
  - multipassd  1.14.0+mac
- `multipass info` 
This is also odd. I didn't see this behavior with 1.14.0-rc6: 

avni@Avnis-MBP ~ % multipass info
info failed: ssh connection failed: 'Socket error: Connection reset by peer'

- `multipass get local.driver` qemu

**Additional context**
I can delete other non-suspended instances and purge them.

**Comment by akauppi** [comment]
`--force` doesn't seem to be a flag for the `delete` command - has it worked before?

```
$ mp delete --help
Usage: multipass delete [options] <instance>[.snapshot] [<instance>[.snapshot] ...]
Delete instances and snapshots. Instances can be purged immediately or later on,
with the "purge" command. Until they are purged, instances can be recovered
with the "recover" command. Snapshots cannot be recovered after deletion and must be purged at once.

Options:
  -h, --help     Displays help on commandline options
  -v, --verbose  Increase logging verbosity. Repeat the 'v' in the short option
                 for more detail. Maximum verbosity is obtained with 4 (or more)
                 v's, i.e. -vvvv.
  --all          Delete all instances and snapshots
  -p, --purge    Permanently delete specified instances and snapshots
                 immediately

Arguments:
  name           Names of instances and snapshots to delete
```

@avni Care to try `multipass delete --purge box-20240225`?

**Comment by andrei-toterman** [comment]
Hey, @avni! The new `--force` option is for the `stop` command, not the `delete` one. But if you run `multipass delete --purge <instance>`, that will also run `stop --force` for that instance. I hope this covers your use case.

But indeed, it is a bug that you cannot just mark a suspended instance as deleted.

**Comment by holta** [comment]
@andrei-toterman wrote:
> The new `--force` option is for the `stop` command, not the `delete` one.

Recap:

Multipass's error message (this original ticket, and excerpted below) currently contradicts @andrei-toterman — no doubt error message was well-intended even if providing false/premature advice 😉

> % multipass delete box-20240225
> delete failed: Cannot stop suspended instance. Use --force to override.

**Comment by holta** [comment]
> no doubt error message was well-intended — even if providing false/premature advice 😉

(Feel free to reclassify this issue as a "Documentation" problem!?)

**Comment by avni** [comment]
Thank you for the quick replies! I tried both delete (with the --purge option) and stop (with the --force option) and neither did the trick. **Update log here: https://dpaste.com/9HRA49NRP**

> @avni Care to try multipass delete --purge box-20240225?
> 

```
X@X-MBP ~ % multipass delete --purge box-20240225
delete failed: Failed to delete suspend image: qemu-img failed (Process returned exit code: 1) with output:
qemu-img: Could not delete snapshot 'suspend': Failed to free the cluster and L1 table: Invalid argument
```

>The new --force option is for the stop command, not the delete one. But if you run multipass delete --purge <instance>, that will also run stop --force for that instance. I hope this covers your use case.

avni@Avnis-MBP ~ % multipass stop --force box-20240225
stop failed: Failed to delete suspend image: qemu-img failed (Process returned exit code: 1) with output:
qemu-img: Could not delete snapshot 'suspend': snapshot not found

```
X@X-MBP ~ % multipass list                       
Name                    State             IPv4             Image
box-20240225            Suspended         --               Ubuntu 22.04 LTS
....
```

> But indeed, it is a bug that you cannot just mark a suspended instance as deleted.
+1

> Multipass's error message (this original ticket, and excerpted below) currently contradicts @andrei-toterman 
+1, the original error message here (in bold) implies that the --force option will work with 'multipass delete'

```
X@X-MBP iiab-calibre % multipass delete box-20240225
**delete failed: Cannot stop suspended instance. Use --force to override.**
```

**Comment by lure23** [comment]
Please ignore this if not useful, but @avni I seem to have solved a similar crisis today by:

- uninstalling and reinstalling Multipass
- Allowing “all data to be removed” (images)during the uninstall
- Recreating the VM instance with *a different name* than I used for it, before

**Comment by avni** [comment]
Thanks, @lure23, creating a new VM instance with a different name does work successfully [NB: I didn't have to uninstall/reinstall Multipass first], so I am not blocked. The issue seems to be with existing instances, whether it's trying to delete a suspended instance or shell into an existing one a la #3607.

**Comment by matt-seedata-io** [comment]
i have the same problem, but the suspended instance is my primary instance. so i cant just use a different name. Any ideas?

**Comment by lure23** [comment]
@matt-seedata-io I went back to 1.14.0-RC1 and it seems to nyt haave these problems. You will lose your image, though.

**Comment by matt-seedata-io** [comment]
Thanks @lure23 ... i started to install rc1, but then i found a way of fixing the issue AND keeping access to old instances. I think its something to do with initially installing  and uninstalling via homebrew, then installing 1.14.0 pkg (not via homebrew)... all works now. Weird. Now if only they could fix the icon to stay in my menu bar 🫤

**Comment by georgeliao** [comment]
@avni 
Thanks for reporting this. 

> X@X-MBP iiab-calibre % multipass delete box-20240225
> delete failed: Cannot stop suspended instance. Use --force to override.

Indeed, this is a bug, a corner case we overlooked during the testing. It will be fixed in the patch release.

> X@X-MBP ~ % multipass delete --purge box-20240225
> delete failed: Failed to delete suspend image: qemu-img failed (Process returned exit code: 1) with output:
> qemu-img: Could not delete snapshot 'suspend': Failed to free the cluster and L1 table: Invalid argument

The suspended instance without the suspend snapshot is a weird state to get into. However, on the other hand, the command should be robust enough to cover this as well. It also will be fixed in the patch release.

**Comment by avni** [comment]
Thank you!
