### ISSUE TITLE
mounting error

### ISSUE THREAD

**Issue by Ethan47345** [canonical/multipass#3609]
![image](https://github.com/user-attachments/assets/bc3f93dd-e1c9-4c04-b09c-64741c4d1883)
Greetings!
I'm not quite sure why I'm getting an error when I mount it, is it because of insufficient permissions? I ran the “multipass launch docker” command directly from a PowerShell window, should I run the command from a PowerShell window Run as Administrator? or should I give mulitipass more advanced permissions (I remember I saw the note about Administrator Permission or something similar at https://multipass.run/docs/tutorial. I don't remember exactly ).
    Another question, can I change the installation path after running the command, the c-drive is too small and I don't want to install it on the c-drive.

**Comment by andrei-toterman** [comment]
Hey, @Ethan47345! For your first question, make sure that you do `multipass set local.privileged-mounts=true` before attempting mounts on Windows!
For your second question, it is possible to change where Multipass is installed, but most likely that is not what you want. What takes up the most storage space is the data that Multipass stores (images, instances etc.). And you can configure that by following this guide https://multipass.run/docs/configure-multipass-storage.

**Comment by Ethan47345** [comment]
thx very much!
