### ISSUE TITLE
ICYMI: v1.14.0 not available via brew yet

### ISSUE THREAD

**Issue by ralgozino** [canonical/multipass#3610]
**Describe the bug**
The latest version v1.14.0 is not available via brew yet.

**To Reproduce**
Installing or upgrading multipass via brew should get you the latest version, the current [definition of the cask](https://github.com/Homebrew/homebrew-cask/blob/97e0e9d36332a467e5480d788cd01a51fb255a50/Casks/m/multipass.rb) installs v1.13.3 instead:

https://github.com/Homebrew/homebrew-cask/blob/97e0e9d36332a467e5480d788cd01a51fb255a50/Casks/m/multipass.rb#L2

**Expected behavior**
Performing `brew upgrade` or `brew upgrade multipass` should update multipass to v1.14.0.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**

```
❯ brew upgrade multipass
Warning: Not upgrading multipass, the latest version is already installed
❯ brew info multipass
==> multipass: 1.13.1
https://github.com/canonical/multipass/
Installed
/opt/homebrew/Caskroom/multipass/1.13.1 (109.1MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/m/multipass.rb
==> Name
Multipass
==> Description
Orchestrates virtual Ubuntu instances
==> Artifacts
multipass-1.13.1+mac-Darwin.pkg (Pkg)
==> Analytics
install: 2,630 (30 days), 8,019 (90 days), 37,130 (365 days)
```

**Additional context**

You are probably aware, but it has been some days since the release (I even got a notification in the app saying to upgrade) and the release is not available in brew so I figured I'd let you know with this issue.

**Comment by ralgozino** [comment]
sure thing, here it is:
https://github.com/Homebrew/homebrew-cask/issues/181054

**Comment by carvido1** [comment]
multipass 1.14 seems to be available in brew for macos

**Comment by ricab** [comment]
Thanks for the update @carvido1!
