### ISSUE TITLE
/etc/hosts file contents reset once VM's are stopped

### ISSUE THREAD

**Issue by agahemre** [canonical/multipass#3614]
**Describe the bug**
Whenever I stop my running VM instances, /etc/hosts files of those VMs are reset. I am not sure this behavior is intended or bug but I expect /etc/hosts file content should persist across VMs restarts since I also edit /etc/environment files and they persist stop & start cycle. In fact `multipass suspend <vm-node>` command preserves /etc/hosts file contents but I cannot edit resource settings of suspended VMs.        

**To Reproduce**
How, and what happened?
1. `multipass shell <sample-node>`
2.  Edit /etc/hosts file 
3. `multipass stop <sample-node>`
4. `multipass shell <sample-node>`
5. cat /etc/hosts, file contents are reset

**Expected behavior**
/etc/hosts file content should persist across VMs restarts

**Additional info**
 - OS: [ macOS 14.5]
- `multipass version` 1.14.0+mac
- `multipass info` 
- Name:           node01
State:          Running
Snapshots:      0
IPv4:           10.211.55.5
                10.244.0.0
Release:        Ubuntu 22.04.4 LTS
Image hash:     facac3b73152 (Ubuntu 22.04 LTS)
CPU(s):         2
Load:           0.06 0.12 0.10
Disk usage:     4.3GiB out of 24.1GiB
Memory usage:   228.6MiB out of 1.9GiB
Mounts:         --
- `multipass get local.driver` qemu

**Comment by andrei-toterman** [comment]
Hey, @agahemre! By any chance, is this inside your `/etc/hosts` file?
```
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
```
If so, please edit the template file as prescribed :)

**Comment by agahemre** [comment]
Yes, I am blinded, I am closing this issue right now.
