### ISSUE TITLE
(Re-)Enable Copy/Paste

### ISSUE THREAD

**Issue by triplekids** [canonical/multipass#3617]
**What are you trying to do?**
I want to copy/paste from/to the shell

**What's your proposed solution?**
Make CTRL-C / CTRL-V work inside multipass shell

**Additional context**
Before 1.14, this was possible because multipass used powershell, with 1.14 it is inside the multipass application whcih does not seem to allow this

**Comment by andrei-toterman** [comment]
Hey, @triplekids! Try Ctrl+Shift+C/V!

**Comment by triplekids** [comment]
Yippie, this works
Thanks
