### ISSUE TITLE
Multipass mounted directory permission issues (tox and virtualenv)

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/multipass#3620]
**Describe the bug**

When working in the multipass charm-dev VM and noticed some strange permission behaviour with mounted directories and `tox/venv`.

When running `tox` or `venv` in this mounted directory within the VM I get permission errors. This error does not occur when I run them from a non-mounted directory.

See related thread on [MatterMost](https://chat.canonical.com/canonical/pl/o4ttr9u8mirc9jnajzwz41oexw).

**To Reproduce**
* [onboarding-troublemakers-task](https://github.com/canonical/onboarding-troublemakers-task)

On my host
1. `multipass launch --name test-mounting 22.04`
2. `multipass mount -g 1000:1000 -u 1000:1000 /home/mt/work/canonical/repos test-mounting:/home/ubuntu/repos`
3. `multipass shell test-mounting`

In the VM
1. `cd repos/my-onboarding-task/`
2. `sudo apt install tox`
3. `tox -e webserver`
4. `sudo apt install python3.10-venv`
5. `python3 -m venv .venv`

**Expected behavior**
There are 2 main topics here:
1. I expect that after mapping the host user and/or group id to the VM id that I have the permissions to execute `tox` and `venv` commands without permission errors.
2. It would be nice to have the `-u` and `-g` options in the `multipass launch` command alongside or within the `--mount` option which is useful for CI. This is more of an improvement than an issue though.

**Logs**
Here are the directory permissions after mounting:

On my host
```
~/work/canonical/repos/my-onboarding-task$ ls -lan
total 56
drwxrwxr-x 9 1000 1000 4096 Aug  1 15:13 .
drwxrwxr-x 7 1000 1000 4096 Aug  1 14:48 ..
drwxrwxr-x 8 1000 1000 4096 Aug  1 14:51 .git
drwxrwxr-x 3 1000 1000 4096 Aug  1 14:48 .github
-rw-r--r-- 1 1000 1000   65 Aug  1 14:48 .gitignore
drwxrwxr-x 6 1000 1000 4096 Aug  1 14:48 keydb
-rw-r--r-- 1 1000 1000 4989 Aug  1 14:48 README.md
-rw-r--r-- 1 1000 1000   97 Aug  1 14:48 requirements-dev.txt
drwxrwxr-x 2 1000 1000 4096 Aug  1 14:48 tests
drwxrwxr-x 5 1000 1000 4096 Aug  1 16:20 .tox
-rw-r--r-- 1 1000 1000 2231 Aug  1 14:48 tox.ini
drwxrwxr-x 5 1000 1000 4096 Aug  1 15:13 .venv
drwxrwxr-x 6 1000 1000 4096 Aug  1 14:48 webserver
```
In the VM
```
~/repos/my-onboarding-task$ ls -lan
total 56
drwxrwxr-x 1 1000 1000 4096 Aug  1 15:13 .
drwxrwxr-x 1 1000 1000 4096 Aug  1 14:48 ..
drwxrwxr-x 1 1000 1000 4096 Aug  1 14:51 .git
drwxrwxr-x 1 1000 1000 4096 Aug  1 14:48 .github
-rw-r--r-- 1 1000 1000   65 Aug  1 14:48 .gitignore
drwxrwxr-x 1 1000 1000 4096 Aug  1 16:20 .tox
drwxrwxr-x 1 1000 1000 4096 Aug  1 15:13 .venv
-rw-r--r-- 1 1000 1000 4989 Aug  1 14:48 README.md
drwxrwxr-x 1 1000 1000 4096 Aug  1 14:48 keydb
-rw-r--r-- 1 1000 1000   97 Aug  1 14:48 requirements-dev.txt
drwxrwxr-x 1 1000 1000 4096 Aug  1 14:48 tests
-rw-r--r-- 1 1000 1000 2231 Aug  1 14:48 tox.ini
drwxrwxr-x 1 1000 1000 4096 Aug  1 14:48 webserver
```

Here are the resulting errors for `tox` and `venv`:

```
python3 -m venv .venv
Unable to symlink '/usr/bin/python3' to '/home/ubuntu/repos/my-onboarding-task/.venv/bin/python3'
```

```
tox -e webserver
webserver: internal error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tox/session/cmd/run/single.py", line 47, in _evaluate
    tox_env.setup()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tox/tox_env/api.py", line 249, in setup
    self._setup_env()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tox/tox_env/python/runner.py", line 108, in _setup_env
    super()._setup_env()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tox/tox_env/python/api.py", line 201, in _setup_env
    self.ensure_python_env()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tox/tox_env/python/api.py", line 208, in ensure_python_env
    self.create_python_env()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tox/tox_env/python/virtual_env/api.py", line 130, in create_python_env
    self.session.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/session.py", line 44, in run
    self._create()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/session.py", line 51, in _create
    self.creator.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/create/creator.py", line 158, in run
    self.create()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 95, in create
    src.run(self, self.symlinks)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/create/via_global_ref/builtin/ref.py", line 153, in run
    method(self.src, dest)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/util/path/_sync.py", line 33, in symlink
    dest.symlink_to(src, target_is_directory=src.is_dir())
  File "/usr/lib/python3.10/pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
PermissionError: [Errno 13] Permission denied: '/usr/bin/python3' -> '/home/ubuntu/repos/my-onboarding-task/.tox/webserver/bin/python'
```

**Additional info**
 - OS: `Ubuntu 22.04.4 LTS`
- `multipass version`
```
multipass   1.14.0
multipassd  1.14.0
```
- `multipass info`
```
multipass info
Name:           charm-dev
State:          Running
Snapshots:      0
IPv4:           10.220.11.219
                10.54.184.1
                10.1.157.64
Release:        Ubuntu 22.04.4 LTS
Image hash:     123e55661336 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.10 0.15 0.15
Disk usage:     9.9GiB out of 48.4GiB
Memory usage:   1.7GiB out of 7.7GiB
Mounts:         /home/mt/work/canonical/repos => /home/ubuntu/repos
                    UID map: 1000:1000
                    GID map: 1000:1000

Name:           test-mounting
State:          Running
Snapshots:      0
IPv4:           10.220.11.247
Release:        Ubuntu 22.04.4 LTS
Image hash:     123e55661336 (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     1.9GiB out of 4.8GiB
Memory usage:   198.9MiB out of 951.8MiB
Mounts:         /home/mt/work/canonical/repos => /home/ubuntu/repos
                    UID map: 1000:1000
                    GID map: 1000:1000
```
- `multipass get local.driver`

`qemu`

**Comment by mmkay** [comment]
I'm also getting the same issue. Seems it started happening after multipass snap upgraded to 1.14.0. Also when I try to copy an existing mounted folder with symlinks, I get permission issues:

```
ubuntu@charm-dev:~$ cp -r grafana-agent-operator/ copied-grafana
cp: cannot read symbolic link 'grafana-agent-operator/.tox/static-charm/bin/python3': Permission denied
cp: cannot read symbolic link 'grafana-agent-operator/.tox/static-charm/bin/python3.10': Permission denied
cp: cannot read symbolic link 'grafana-agent-operator/.tox/static-charm/bin/python': Permission denied
cp: cannot read symbolic link 'grafana-agent-operator/.tox/.package/bin/python3': Permission denied
cp: cannot read symbolic link 'grafana-agent-operator/.tox/.package/bin/python3.10': Permission denied
cp: cannot read symbolic link 'grafana-agent-operator/.tox/.package/bin/python': Permission denied
```

on my host:

```
$ ls -lan
total 8
drwxrwxr-x 2 1000 1000 4096 Aug  5 20:47 .
drwxrwxr-x 5 1000 1000 4096 Aug  6 10:03 ..
lrwxrwxrwx 1    0    0   16 Jul 31 14:59 python -> /usr/bin/python3
lrwxrwxrwx 1    0    0    6 Jul 31 14:59 python3 -> python
lrwxrwxrwx 1    0    0    6 Jul 31 14:59 python3.10 -> python
```

on the multipass VM:
```
$ ls -lan grafana-agent-operator/.tox/static-charm/bin/
ls: cannot read symbolic link 'grafana-agent-operator/.tox/static-charm/bin/python3': Permission denied
ls: cannot read symbolic link 'grafana-agent-operator/.tox/static-charm/bin/python3.10': Permission denied
ls: cannot read symbolic link 'grafana-agent-operator/.tox/static-charm/bin/python': Permission denied
total 20
drwxrwxr-x 1  1000  1000 4096 Aug  5 20:47 .
drwxrwxr-x 1  1000  1000 4096 Aug  6 10:03 ..
lrwxrwxrwx 1 65534 65534   16 Jul 31 14:59 python
lrwxrwxrwx 1 65534 65534    6 Jul 31 14:59 python3
lrwxrwxrwx 1 65534 65534    6 Jul 31 14:59 python3.10
```

multipass info:

```
$ multipass info
Name:           charm-dev
State:          Running
Snapshots:      0
IPv4:           10.211.88.161
                10.130.135.1
                10.1.157.64
Release:        Ubuntu 22.04.4 LTS
Image hash:     123e55661336 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.24 0.38 0.47
Disk usage:     9.8GiB out of 48.4GiB
Memory usage:   1.7GiB out of 7.7GiB
Mounts:         /home/mat/Code/grafana-agent-operator => ~/grafana-agent-operator
                    UID map: 1000:default
                    GID map: 1000:default
```

**Comment by Abuelodelanada** [comment]
I can confirm this issue as well.

P.S.: @MichaelThamm the `--mount` option is available to `launch` subcommand, for example I create my VMs this way:

```shell
multipass launch --cloud-init charm-dev-juju-3.5.yaml \  
--timeout 1200 \
--name charm-dev-35 \
--memory 8G \
--cpus 4 \
--disk 60G \
--mount /home/jose/trabajos/canonical/repos:/home/ubuntu/repos --network enp1s0
```

**Comment by MichaelThamm** [comment]
@Abuelodelanada I understand, but what I mean is that as far as I know there are no options to map the GID and UID in this way and it is only possible when running the `multipass mount` command after having created the VM.

```
multipass launch
  --mount <local-path>:<instance-path>  Mount a local directory inside the
                                        instance. If <instance-path> is omitted,
                                        the mount point will be the same as the
                                        absolute path of <local-path>
```
```
multipass mount
  -g, --gid-map <host>:<instance>  A mapping of group IDs for use in the mount.
                                   File and folder ownership will be mapped from
                                   <host> to <instance> inside the instance. Can
                                   be used multiple times. Mappings can only be
                                   specified as a one-to-one relationship.
  -u, --uid-map <host>:<instance>  A mapping of user IDs for use in the mount.
                                   File and folder ownership will be mapped from
                                   <host> to <instance> inside the instance. Can
                                   be used multiple times. Mappings can only be
                                   specified as a one-to-one relationship.
```
It is not really a requirement, more of a nice-to-have. This would cut the number of commands in half if the `sshfs` is causing issues.

**Comment by shyjuk** [comment]
Same issue here on M1 Mac.

**Comment by rkr-kununu** [comment]
On my M1 Mac, I get a permission denied (inside multipass) if I try to mount the Mac's `/etc` or `/private/etc` folder into the VM.  I wanted to my multipass VM to modify the Mac's `/etc/hosts` file, which works perfectly on v1.3.X.  I've given full disk access both the multipassd and also sshfs_server.  It doesn't seem to help :(

**Comment by sed-i** [comment]
For reference, copying here from the internal mattermost thread:

> you need UID or GID mapping from the files on the host to the user in the VM to be able to access them
> https://multipass.run/docs/id-mapping
> -- @ricab 


> You could try using native mounts. Just do `multipass mount --type native ....` That does not have the strict sshfs restrictions, so you can use that while we sort out the issues with the classic mounts
> -- @andrei-toterman

**Comment by sharder996** [comment]
Hi @MichaelThamm, try creating the mount with the following command:

```
multipass mount -g 1000:1000 -u 1000:1000 -g 0:0 -u 0:0 /home/mt/work/canonical/repos test-mounting:/home/ubuntu/repos
```

taking care to note the additional mapping of root to root from the instance to the host. As for the symbolic link, I see no difference in behaviour since 1.13. However, some improvement might be possible in the way we handle symbolic links in the context of mounts.

@rkr-kununu, in the case of macOS, you will have to do something like:

```
multipass mount -g 20:1000 -u 501:1000 -g 0:0 -u 0:0 /private/etc foo:/home/ubuntu/etc
```

Now, this only works because we only allow access for uid/gid's that are explicitly defined as a mapping for the mount. If another user need to access the files in the instance, subsequent id mappings will have to be added for that as well. I realize this is going to make mounting file directory via sshfs more tedious as one will likely have to define multiple mappings.

For context, this change was decided to be necessary as a way to mitigate the chances of root escaping the instance into the host. More can be read about the issue here; https://github.com/canonical/multipass/issues/3179. Essentially, we want users to be conscious of the fact that they are mapping root to root in their sshfs mounts.

One way of working around this workflow is to use native mounts instead with `--type native`. Note that the instance must be stopped first in order to create a native mount.

**Comment by sed-i** [comment]
Is there a way to automate the logic behind `-g 1000:1000 -u 1000:1000 -g 0:0 -u 0:0` with a dedicated cli arg, @sharder996?
For example 
```
multipass mount --dangerous /home/mt/work/canonical/repos test-mounting:/home/ubuntu/repos
```

**Comment by andrei-toterman** [comment]
@sed-i thanks for the suggestion! As of now, I think an easier and more customizable way of achieving this is just a bash alias/function. We don't have any plans at the moment for something like `--dangerous`, but we are actively trying to improve the mount experience, and we need to find a solution that works well across all mounting technologies that we use and to have more sensible defaults. Again, thanks for the idea and sorry for the inconveniences!
