### ISSUE TITLE
Re-implement TCI protocol

### ISSUE THREAD

**Issue by LA3QMA** [canonical/multipass#3638]
re-implement TCI control for Expert Electronics radioes.

TCI might have some changes since FD first implemented this.

https://github.com/ExpertSDR3/TCI

**Comment by ricab** [comment]
This sounds off topic for Multipass. Let me know if I am missing something.

**Comment by LA3QMA** [comment]
> This sounds off topic for Multipass. Let me know if I am missing something.

Just delete this request but sure how it was posted  in this repo. Sorry
