### ISSUE TITLE
Incompatibility between Cloudflare WARP client and Multipass (+ solution)

### ISSUE THREAD

**Issue by akauppi** [canonical/multipass#3639]
**Describe the bug**

Cloudflare WARP is a VPN-like tool for optimizing one's Internet speed. Recently, I found it was not possible to activate connections on it (port 53 taken), but found a solution.

Note: This might be beyond Multipass's means to do anything about it. It's likely between Apple and Cloudflare. Writing here in the hopes that others can find the work-around if affected.

**To Reproduce**

How, and what happened?

1. Have Multipass (mine is `1.14.0-RC1`) installed
2. Start a VM (`multipass start default`)
3. Try to activate 1.1.1.1 (Cloudflare WARP) client

**Expected behavior**

I can activate Cloudflare WARP

**Actual behaviour**

Cloudflare WARP reports that `mdnsresponder` process is sitting on the port 53 and preventing the activation.

**Additional info**
 - OS: macOS 14.6.1 (Intel)
- `multipass version`: 

   ```
   multipass   1.14.0-rc1.2439+g95e4d16a3.mac
   multipassd  1.14.0-rc1.2439+g95e4d16a3.mac
   ```

- `multipass info`

```
$ mp info
Name:           rust-emb
State:          Running
Snapshots:      0
IPv4:           192.168.64.120
Release:        Ubuntu 24.04 LTS
Image hash:     d2377667ea95 (Ubuntu 24.04 LTS)
CPU(s):         3
Load:           0.00 0.00 0.00
Disk usage:     4.9GiB out of 17.4GiB
Memory usage:   413.3MiB out of 5.8GiB
Mounts:         /Users/xxx/Git/VL53L5CX_rs             => /home/ubuntu/VL53L5CX_rs
                    UID map: 501:default
                    GID map: 20:default
```

- `multipass get local.driver`

```
qemu
```

>AH!  That's why it works!!!    If port 53 is taken, Multipass likely falls back on the `qemu` instead of the native client?

**Work-around**

1. Stop running Multipass VM's
2. Activate Cloudflare WARP now
3. Restart the VM instances

**Comment by ricab** [comment]
Hi @akauppi, thanks for sharing. Just so you know, [our discourse](https://discourse.ubuntu.com/c/multipass/) is better suited for knowledge-sharing posts such as this one.

I am leaving the issue open for now to discuss how to handle this in our documentation.

**Comment by giuliazanchi** [comment]
Hi @akauppi , if you want to share this information on the Multipass Discourse forum, you could create a new topic under our new ["Community knowledge" category](https://discourse.ubuntu.com/c/multipass/community-knowledge/267) so other users can find it easily. Thanks for sharing!

**Comment by ricab** [comment]
Thank you @giuliazanchi, that is indeed the best place for this. Closing the issue now.

**Comment by giuliazanchi** [comment]
@akauppi FYI - I've copied this issue over to Discourse as a new topic in the Community Knowledge category: https://discourse.ubuntu.com/t/incompatibility-between-cloudflare-warp-client-and-multipass-solution/47377

**Comment by air3ijai** [comment]
To add one more note
1. Cloudflare WARP is running in a "Traffic and DNS" mode
2. Create a VM - `multipass launch 24.04 --name test`
3. Launch fail with an error
   >launch failed: The following errors occurred:
   > timed out waiting for initialization to complete
4. Switching WARP to a "Traffic only" mode, solve the issues
5. Switching WARP back to a "Traffic and DNS" mode fail
6. At that point, we have to use a mentioned workaround

- WARP: `2026.6.880.0`
- Multipass: `1.16.3+mac`
