### ISSUE TITLE
[Doc] Using `multipass list` should happen early in a HowTo

### ISSUE THREAD

**Issue by DanRoscigno** [canonical/multipass#3641]
The HowTo for setting up a GUI with RDP starts off with `multipass shell` to a randomly generated VM instance. Later in the guide `multipass list` is used to get the IP addr for the RDP client. If we move the `list` command to the top, then the reader can be told "Use the name and the IP addr returned by `list` when you follow these commands.

**Proposal to fix issue or enact suggestion**
I will open a PR to move the `list` command up top.

**Additional context**
[Page in question](https://multipass.run/docs/set-up-a-graphical-interface)

**Comment by giuliazanchi** [comment]
Thanks for your suggestion, @DanRoscigno . If you want to give this a go, but don’t have edit access where this page is hosted, let me know and I can set up an issue on the Canonical Open Documentation Academy repo :)

**Comment by DanRoscigno** [comment]
Thanks @giuliazanchi , that would be perfect!

**Comment by giuliazanchi** [comment]
This issue has been moved to the Canonical Open Documentation Academy backlog: https://github.com/canonical/open-documentation-academy/issues/128 

@DanRoscigno feel free to pick it up and continue the chat over there! Thanks again.

**Comment by giuliazanchi** [comment]
Done.
