### ISSUE TITLE
Add an option to reuse an ip

### ISSUE THREAD

**Issue by ssg3d** [canonical/multipass#3664]
Based on what I know at the moment, Multipass launch allocates a new ip for the instance. This clutters up the ip space and also makes it hard to remember which instance is which. For example, I like to have a few instances like dev and test, and would like them to always have the same ip so I don't have to lookup their ip when, say, I run a server on a Multipass instance and access it from a browser.

I often find myself using the workaround to open `/var/db/dhcpd_leases` and manually deleting the ips I want to reuse.

I think a possible way to reuse could be to add an option like `multipass launch --reuse-ip xx.yy.zz.ww`. 

If one does not know the broad range of ips that are used at first, they could let Multipass choose the first ip by itself and then for subsequent launches, supply the ip as xx.yy.zz.aa where aa is their choice.

**Comment by sharder996** [comment]
Hi @ssg3d, It would be highly unlikely that we would implement something like as it would clutter up the already very busy launch command and isn't very integral to the normal operation of a virtual machine.

However, there might some things that you can do to make your life easier. Take a look at the doc for assigning static IPs to Multipass instances. It might help you out.
https://multipass.run/docs/configure-static-ips
