### ISSUE TITLE
Tiny potential typo on https://multipass.run/docs/using-aliases page

### ISSUE THREAD

**Issue by jeremiah** [canonical/multipass#3666]
**Description of documentation issue or suggestion**
Tiny potential typo on https://multipass.run/docs/using-aliases page

**Proposal to fix issue or enact suggestion**
I think on this line; multipass lscc` there is a typo; namely a spurious "`" possibly left over from Markdown.

**Additional context**
None. :-)

**Comment by sharder996** [comment]
Fixed!

Thanks for pointing that out, @jeremiah!

In the future, feel free to make updates and suggestions yourself through the [Help improve this document in the forum](https://discourse.ubuntu.com/t/how-to-use-instance-command-aliases/24128) link at the bottom of every page.

**Comment by giuliazanchi** [comment]
Thanks @jeremiah for spotting it, and thanks @sharder996 for fixing it so quickly!
