### ISSUE TITLE
Multipass 1.14 is not compatible with MacOS Sequoia

### ISSUE THREAD

**Issue by lallini94** [canonical/multipass#3685]
**Describe the bug**
The problem is that multipass doesn't work after the update to Sequoia.
My primary instance keeps staying on "starting"

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version 1.14`

**Comment by georgeliao** [comment]
@lallini94 
Sorry that you encountered this. It is known problem and we are working on a solution. Meanwhile, the issue #3661 tracks this.

**Comment by georgeliao** [comment]
Duplicate of https://github.com/canonical/multipass/issues/3661
