### ISSUE TITLE
Delayed stop

### ISSUE THREAD

**Issue by sergiusens** [canonical/multipass#369]
In order to make unexpected user reuse of a VM more pleasant, at least when driven programmatically, it would be nice to be able to specify a stop delay such that

```
multipass stop <instance-name> --delay 10m
```

Would only stop the instance after 10 minutes, stopping can be canceled by calling

```
multipass start <instance-name>
```

or use of any other interaction.

**Comment by Saviq** [comment]
Sure, I think we can have something We should probably try and reproduce `shutdown`'s time parsing or so.

**Comment by townsend2010** [comment]
I told @sergiusens that I would try to get this done in time for his Brussels demo:)

**Comment by townsend2010** [comment]
Here is my proposed cli usage:

`$ multipass stop my-vm --time +m`
where `m` is the number of minutes to delay before shutting down.  Also, `-t` will be supported for the short option.

To cancel a delayed shutdown, either:
`$ multipass stop my-vm --cancel` (`-c` is also supported)
or
`$ multipass start my-vm`
will cancel any delayed shutdowns.
