### ISSUE TITLE
[win] VMs fail during startup in VirtualBox 7.0.X when X > 14

### ISSUE THREAD

**Issue by Sploder12** [canonical/multipass#3691]
**Describe the bug**
When launching a VM using the VirtualBox backend, the following error is produced:
`Could not start VM: VBoxManage.exe: error: The virtual machine ‘<name>’ has terminated unexpectedly during startup with exit code 1 (0x1). More details may be available in ‘C:\Windows\system32\config\systemprofile\VirtualBox VMs\Multipass\<name>\Logs\VBoxHardening.log’ VboxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine`

The file mentioned in the error message does not exist.

**To Reproduce**
1. Run multipass with the VirtualBox backend with the mentioned version of VirtualBox installed
2. Launch an instance
3. See error

**Expected behavior**
Instance launches with no error

**Additional info**
 - OS: Windows 10 Home

**Comment by ricab** [comment]
Hey @Sploder12, Eric reports that 7.0.18 works for him. Did you happen to try that version?

**Comment by Sploder12** [comment]
That is the only version after 7.0.14 I did not try... I will try it and see what happens.

**Comment by ricab** [comment]
Thank you :)

**Comment by ricab** [comment]
Ah, interesting! That explains why I could launch with 7.0.20 just fine... I guess we can close this one then?

**Comment by Sploder12** [comment]
I think so, appears to be a bug with the VirtualBox installer, not Multipass.
