### ISSUE TITLE
Unable to start multipass instance

### ISSUE THREAD

**Issue by ZhenmeiOng** [canonical/multipass#3699]
**Describe the bug**
I received timeout trying to start an instance. At first, it was due to macOS Sequoia 15.0 update, that required mac users to reinstall multipass using a test package (#3661), which I did, and it managed to solve the issue. However, when I exited the instance, and reentered it again, I get a timeout, but unlike the previous time, this time I am able to launch a new instance without getting a timeout. 

**To Reproduce**
1. `multipass start faasd-vm`
2. `start failed: The following errors occurred:
faasd-vm: timed out waiting for response`

**Expected behavior**
I expected to get the instance, `faasd-vm` running

**Logs**
[logs.txt](https://github.com/user-attachments/files/17123234/logs.txt)

**Additional info**
 - OS: macOS Sequoia 15.0
- `multipass version`:  
multipass   1.15.0-dev.2929.pr661+gc67ef6641.mac
multipassd  1.15.0-dev.2929.pr661+gc67ef6641.mac

- `multipass info`
- Name:           faasd-vm
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

- `multipass get local.driver` : qemu

**Additional context**

**Comment by ZhenmeiOng** [comment]
Nvm, I deleted that instance and created a new one. But I would like to know what were the reasons that caused this issue still.

**Comment by georgeliao** [comment]
> However, when I exited the instance, and reentered it again, I get a timeout. 

Interesting, if you just exited the instance, meaning that `ctrl+d` in the instance or typed `exit`, then the instance would still be running, right? Did you stop the instance after that?

**Comment by ndkthienhy** [comment]
i same. When I start a instance, it always show message on log: Could not determine IP address within 1000ms.

**Comment by ndkthienhy** [comment]
[log.docx](https://github.com/user-attachments/files/17129614/log.docx)
this is my log

**Comment by giuliazanchi** [comment]
Hi everyone, I'm afraid this may be a known issue that periodically comes up here. We're currently working to expand the Troubleshooting section in our documentation to address launch/start timeouts, including this issue. I'll post a link here as soon as the new content is available.

**Comment by ndkthienhy** [comment]
Thank you. I spent 2 days trying to fix this error and it still didn't work. I can't delete it, because some important data I haven't backed up yet. I hope it is work soonest possible

**Comment by georgeliao** [comment]
@ndkthienhy 
Based on your log, the `arp` did not get that ip and mac address pair in the cache table. Can you check the top of the lease file `/var/db/dhcpd_leases` and see if the ip corresponds to your vm is there?

**Comment by ZhenmeiOng** [comment]
@georgeliao 
I typed `exit`, and then `multipass stop`, but was unable to start the instance again.
I already had that instance before installing multipass 15.0. It worked when I used multipass 15.0 for the first time to start the instance, but not after I stopped and tried to start again.

**Comment by georgeliao** [comment]
> I already had that instance before installing multipass 15.0. It worked when I used multipass 15.0 for the first time to start the instance, but not after I stopped and tried to start again.

Based on the log of yours, it should work, `ARP` is able to get the ip address and mac address pair and multipass should get the ip subsequently. Not sure what exactly is happening. 

Can you launch a new vm, shell, exit, stop the vm, and start it again? see if it works. 
Can you also run `multipass stop faasd-vm --force` on the migrated vm and start it again? Check if the problem persist.

**Comment by ZhenmeiOng** [comment]
> Can you launch a new vm, shell, exit, stop the vm, and start it again? see if it works.
Can you also run multipass stop faasd-vm --force on the migrated vm and start it again? Check if the problem persist.

I was able to launch new vm and do work in it and so on without a problem.
That's why I deleted the the problematic instance... oops

**Comment by georgeliao** [comment]
> That's why I deleted the the problematic instance... oops

Did you purged it already? otherwise it can recovered. Anyway, your log shows that the ip polling process worked and the vm is started. It is just that error message is unexpected.

**Comment by ZhenmeiOng** [comment]
@georgeliao 

unfortunately I did purge it (I regret very much doing that). Thank you so much for taking the time to look at my log and trying to find what's wrong. I really appreciate that! Maybe the problem was from the newly created installation package for multipass 15.0, because I know it was created to fix issues with macOS Sequoia

**Comment by ndkthienhy** [comment]
> @ndkthienhy Based on your log, the `arp` did not get that ip and mac address pair in the cache table. Can you check the top of the lease file `/var/db/dhcpd_leases` and see if the ip corresponds to your vm is there? You also can check if the firewall is on and turning it off makes a difference or not.

I had already deleted this file, and firewall also off. But it isn't work. Thanks

**Comment by yohoojoo** [comment]
I same. when I restart MacOS

**Comment by georgeliao** [comment]
> I had already deleted this file, and firewall also off. But it isn't work. Thanks

The `/var/db/dhcpd_leases` file should get recreated if the DHCP lease is issued. It should get issued if dhcp server is working properly. Can you double check whether you get that file recreated if you try to launch or start a VM? 
If it is certain that the lease can not be obtained, then maybe you can try to run `sudo tcpdump -i bridge100 udp port 67 and port 68` to monitor the DHCP requests and replies. Note that `bridge100` is a virtual network interface used by qemu on macos and it only appears when you have vms running. So you should start or launch a VM in order to monitor `bridge100`. 

More detailed troubleshooting steps can be found [here](https://github.com/canonical/multipass/discussions/3660#discussioncomment-10548808).

**Comment by ricab** [comment]
Hi everyone. Thank you for sharing your experiences. The symptoms reported here have various causes (e.g., firewall, image corruption, DHCP issues, etc.), so we've created a troubleshooting guide to help address them. 

As this thread mixes different situations, we’re unable to provide further guidance here. If the guide doesn’t resolve your issue and you believe it is caused by a bug in Multipass, please open a new report with specific details. Thank you for understanding!
