### ISSUE TITLE
random start error with mounted dir

### ISSUE THREAD

**Issue by sergiusens** [canonical/multipass#371]
I usually get this when launching multipass, a retry usually gets through:

    start failed: The following errors occured:                                     
    Removing "/home/multipass/project": failed to obtain exit status for remote process: 'id -g'
    failed to launch: instance "snapcraft-make-hello" already exists

**Comment by townsend2010** [comment]
This should be resolved with #422 and when #429 is merged.

**Comment by townsend2010** [comment]
Going to go ahead and close this and we can track #425 and #429 for status of the PR being merged.
