### ISSUE TITLE
Can't start or open an instance

### ISSUE THREAD

**Issue by SchoolPatryck** [canonical/multipass#3711]
Hello, I am new to Multipass and have not been able to get it working on any of my devices, MacOs 15.0, Windows 11 Pro 23H2, and Windows 10 Pro 22H2. When I run `multipass lauch --name primary` or any instance for that matter, I am greeted with a timeout bug. I have turned off Firewall and made sure my connection is private, but to no avail.

**Comment by SchoolPatryck** [comment]
On Mac I was able to find a way around and is now working. On my Windows machine at home, the Windows 11 one, i am told I don't have an OpenSSL and cannot open multipass, at all. I am not home right now so cannot provide a screenshot. The other Windows machine is my work laptop. This is because of the VPN firewall I must use I believe.

**Comment by 0m-a-D** [comment]
> On Mac I was able to find a way around and is now working. On my Windows machine at home, the Windows 11 one, i am told I don't have an OpenSSL and cannot open multipass, at all. I am not home right now so cannot provide a screenshot. The other Windows machine is my work laptop. This is because of the VPN firewall I must use I believe.

Could you share your workaround for mac? How did your resolve the issue?

**Comment by SchoolPatryck** [comment]
Someone in my class posted this on one of the forums:
"Someone in my section today showed me an additional package for Multipass which has seemingly fixed the timeout error that some students have been dealing with on macOS. You can download the package directly from the following link: https://multipass-ci.s3.amazonaws.com/pr661/multipass-1.15.0-dev.2929.pr661%2Bgc67ef6641.mac-Darwin.pkg."
I got a warning on my machine that it could not confirm if the download had malware, so be warned. I downloaded it and everything has been okay thus-far.

**Comment by SchoolPatryck** [comment]
> > On Mac I was able to find a way around and is now working. On my Windows machine at home, the Windows 11 one, i am told I don't have an OpenSSL and cannot open multipass, at all. I am not home right now so cannot provide a screenshot. The other Windows machine is my work laptop. This is because of the VPN firewall I must use I believe.
> 
> Could you share your workaround for mac? How did your resolve the issue?
Someone in my class posted this on one of the forums:
"Someone in my section today showed me an additional package for Multipass which has seemingly fixed the timeout error that some students have been dealing with on macOS. You can download the package directly from the following link: https://multipass-ci.s3.amazonaws.com/pr661/multipass-1.15.0-dev.2929.pr661%2Bgc67ef6641.mac-Darwin.pkg."
I got a warning on my machine that it could not confirm if the download had malware, so be warned. I downloaded it and everything has been okay thus-far.

**Comment by 0m-a-D** [comment]
That uses the same version as homebrew. So that didn't fix the issue for me

**Comment by ricab** [comment]
Hi everyone. Thank you for sharing your experiences. The symptoms reported here have various causes (e.g., firewall, image corruption, DHCP issues, etc.), so we've created a [troubleshooting guide](https://discourse.ubuntu.com/t/troubleshoot-launch-start-issues/48104) to help address them. 

As this thread mixes different situations, we’re unable to provide further guidance here. If the guide doesn’t resolve your issue and you believe it is caused by a bug in Multipass, please open a new report with specific details. Thank you for understanding!
