### ISSUE TITLE
Multipass seems to delete my instances, "cannot connect to the multipass socket", and gives me the screen "waiting for daemon"

### ISSUE THREAD

**Issue by weluvgoatz** [canonical/multipass#3721]
**Describe the bug**
After I have used the multipass GUI a couple times, it seems to freeze up, and then I am greeted with the message "waiting for daemon", which lasts indefinitely, even if I close and re-open the program.

**To Reproduce**
How, and what happened?
1. Open the Multipass GUI
2. Do some stuff in Multipass for a while.....
3. After using it a couple times, upon startup, my instances are all seemingly deleted and I get the "waiting for daemon" message.

**Expected behavior**
I expected Multipass to start up and not give me this message and let me access my previously used instances.

**Logs**
It won't let me put the log file, for some reason.  Should I attach a screenshot, or upload the file elsewhere, or something? 

**Additional info**
 - OS: Windows 10 Home
- `multipass version` 1.14.0
- `multipass info` I am unable to access it.  I will explain below.
- `multipass get local.driver` Same as above.

**Additional context**
Here is a screenshot of what I am experiencing.  Apologies if my information is not helpful, I am extremely new to this (and Ubuntu in general) and am only using it for a class that requires it.
![image](https://github.com/user-attachments/assets/e166713f-5742-4954-8458-62aeba3841a5)

Also, every time I try to run a multipass command in CMD, it fails, because I get this error:
![image](https://github.com/user-attachments/assets/6d15d1ff-92cf-4b50-a39b-b7e6442987c7)

After a little bit of searching, I am assuming this is related to #3142 .

**Comment by sharder996** [comment]
Hi @weluvgoatz, it looks like the Multipass service has crashed due to some unknown error. A quick fix might just be to restart it (Services->Multipass->restart service). However, to determine what went wrong we will need the logs as a first step. This [document](https://multipass.run/docs/accessing-logs) explains where to find the logs on Windows. You can select and export the logs as a txt file and simply paste the contents in a comment here or create a paste on pastebin.

**Comment by weluvgoatz** [comment]
I tried restarting the service, but it looks like it's been stuck at this screen for a bit:
![image](https://github.com/user-attachments/assets/a1f50966-6c54-45a6-b640-5c136fe94a50)


I read that document, but was unaware I could export it as a txt file, so I did that. Thanks! 
[Logs.txt](https://github.com/user-attachments/files/17317177/Logs.txt)

**Comment by sharder996** [comment]
If it's stuck in the `Stopping` state, you will need to force stop the service which you can do by ending the `multipassd.exe` process in task manager. Or, you can simply restart your machine.

As for the logs, I'm not immediately seeing anything pointing to the original error. If the problem persists after restarting the service (as described above), the logs around the time the service is starting up/crashing/some problem occurring would be helpful.

**Comment by weluvgoatz** [comment]
Okay, a somewhat-odd workaround I managed to find is using Services to restart it, but this is only reliable about half the time.  However, in the situations that it does work, my instances and associated files do return.  

As for what you said about the logs, the ones I sent was everything associated with my usage of Multipass today.

Anyway, I appeared to find a workaround, but if the problem arises again and the workaround does not work anymore I will come back.

**Comment by mdorier** [comment]
I'm hitting the same problem on a Mac M2 Max after updating to 1.14.1. Any solution? The UI keeps showing Waiting for daemon, over and over again. I can't do anything. What's the Mac equivalent of the workaround above?

**Comment by sharder996** [comment]
@mdorier Restart the Multipass daemon?

```
launchctl kickstart -k /Library/LaunchDaemons/com.canonical.multipassd.plist
```

**Comment by mdorier** [comment]
Can't try it anymore. I uninstalled and reinstalled a bunch of times, it ended up working eventually but I lost my VM in the process.

**Comment by BhautikChudasama** [comment]
Reinstall the multipass, solves the problem.

**Comment by ricab** [comment]
Hey @codecowboy, would you mind opening a [new issue](https://github.com/canonical/multipass/issues/new/choose), filling in the form, including logs? Thank you.

**Comment by zrml** [comment]
Same issue here. OSX Sequoia 15.3.1. After a reboot nothing is working. I re-iinstalled and Multipass GUI works but when I try a ```multipass start instance``` it seats there forever :-( I just wasted a week worth of work... :-( Wondering how I can recover...

**Comment by owenzorrin** [comment]
> [@mdorier](https://github.com/mdorier) Restart the Multipass daemon?
> 
> ```
> launchctl kickstart -k /Library/LaunchDaemons/com.canonical.multipassd.plist
> ```

It worked for me to run, 
```
launchctl kickstart -k system/com.canonical.multipassd
```
