### ISSUE TITLE
Mounts hangging on edge

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3727]
```
$ mp mount tmp/ amazed-topi:tmp
$ mp exec -n amazed-topi -- ls
snap  tmp
         $
$
$ mp exec -n amazed-topi -- ls tmp
[hangs]
```

Also don't know what causes the misalignment in the middle.

This in the logs:
```
[...]
out 11 18:45:23 ricab-laptop sshfs_server[311136]: Executing 'sudo env LD_LIBRARY_PATH=/snap/multipass-sshfs/145/lib /snap/multipass-sshfs/145/bin/sshfs -o slave -o transform_symlinks -o allow_other -o Compression=no -o dir_cache=no :"/home/ricab/tmp" "/home/ubuntu/tmp"'
out 11 18:45:44 ricab-laptop sshfs_server[311136]: sshfs in the instance appears to have exited unexpectedly.  Trying to recover.
out 11 18:45:44 ricab-laptop sshfs_server[311136]: Executing 'findmnt --source :/home/ricab/tmp  -o TARGET -n'
out 11 18:45:44 ricab-laptop sshfs_server[311136]: Executing 'sudo umount /home/ubuntu/tmp
                                                     '
out 11 18:45:44 ricab-laptop sshfs_server[311136]: Executing 'sudo env LD_LIBRARY_PATH=/snap/multipass-sshfs/145/lib /snap/multipass-sshfs/145/bin/sshfs -o slave -o transform_symlinks -o allow_other -o Compression=no -o dir_cache=no :"/home/ricab/tmp" "/home/ubuntu/tmp"'
out 11 18:46:04 ricab-laptop sshfs_server[311136]: Caught an unhandled exception: [sftp] server init failed: 'sftp_get_client_message: Out of memory'
```

This appears to have been caused by changes to `libssh`.

**Comment by Sploder12** [comment]
Looks like `libssh` moved the sftp server implementation to a callback approach and deprecated the old API. Some functions called by the old API were also changed so I'm guessing that's where the issue is coming from. Also the "sftp_get_client_message: Out of memory" error appears to be a red-herring since `sftp_get_client_message` assumes all packet failures are OOM even if they aren't.
However, I'm struggling to find documentation on their callback approach.

**Comment by ricab** [comment]
Hey @Sploder12, let's first revert to point to the previous version of libssh. We can then work on a separate PR to adapt to the new version properly.

**Comment by Sploder12** [comment]
Sounds good.

For later reference, I isolated the breaking change to [this](https://github.com/canonical/libssh/commit/2d3b7e07af3675b9a0326bc5c6253a0bbbda567b) commit.
