### ISSUE TITLE
hhhn

### ISSUE THREAD

**Issue by freshystar** [canonical/multipass#3738]
**Description of documentation issue or suggestion**
A description of the issue or suggestion you are making.

**Proposal to fix issue or enact suggestion**
If applicable, a description of how you think the issue should be fixed or how to enact your suggestion.

**Additional context**
Any additional context such as a link to the documentation page, a screenshot, etc.

**Comment by andrei-toterman** [comment]
Hey, @freshystar! Perhaps you created this issue with the default content accidentally. You can edit its contents if you want. Still, I'll close this for now, but you can reopen it at any time when you provide some proper content :)
