### ISSUE TITLE
External storage with multipass don't work

### ISSUE THREAD

**Issue by vilm725** [canonical/multipass#3753]
Hi everyone 👋🏻

<br>

**Describe the bug**
I would stock all my data (vm, containers, etc) in my external ssd, but ... when I follow the tutorial in the documentation (https://multipass.run/docs/configure-multipass-storage) , it simply **doesn't work**. The following error is displayed: **Waiting for daemon**.

This is what appears :
![image](https://github.com/user-attachments/assets/cb0b484a-57b7-4567-9e4f-c5e831822680)

<br>

**To Reproduce**

Here's exactly what I ordered:

```
sudo snap stop multipass

sudo snap connect multipass:removable-media

sudo mkdir /etc/systemd/system/snap.multipass.multipassd.service.d/

sudo tee /etc/systemd/system/snap.multipass.multipassd.service.d/override.conf <<EOF
[Service]
Environment=MULTIPASS_STORAGE=/media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/
EOF

# /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/ = This is the absolute link to my folder in a partition

sudo systemctl daemon-reload

sudo snap start multipass
```

Have I forgotten something? Do you have any idea what the problem is ? 🤔

I'd like to finish by saying that I don't want to retrieve any data. I don't have anything to import because I use my own cloud init files for deployment. I just wish this external ssd storage feature could work normally.

<br>

**Expected behavior**
What did you expect to happen?

<br>

**Logs**
In this file : 
[log.txt](https://github.com/user-attachments/files/17481541/log.txt)

<br>

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info`
- `multipass get local.driver`

**Additional context**
My version of multipass : 
```
:~$ multipass version
multipass   1.14.1
multipassd  1.14.1
```

My settings :
![settings](https://github.com/user-attachments/assets/fb7d3b08-1f78-450b-a662-eeced778e712)

💡 **Info** : I use several ssd with one partition (using a lvm group) and an ext4 file system. I've never had any problems with virtualbox, virt manager or any other software storing my data on this partition.

![folder](https://github.com/user-attachments/assets/8834b662-0492-4338-8436-61022b3e6b77)

💡 **System info** :
```
Operating System: KDE neon 6.2
KDE Plasma Version: 6.2.0
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.8.0-45-generic (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz
Memory: 62.7 Gio of RAM
Graphics Processor: AMD Radeon RX 590 Series
```

**Comment by vilm725** [comment]
In the log file, some lines show the problem but are still very vague :
```
oct. 22 22:03:33 soso multipassd[101783]: Caught an unhandled exception: unable to create directory '/media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/cache'
oct. 22 22:03:33 soso systemd[1]: snap.multipass.multipassd.service: Main process exited, code=exited, status=1/FAILURE
oct. 22 22:03:33 soso systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
oct. 22 22:03:34 soso systemd[1]: snap.multipass.multipassd.service: Scheduled restart job, restart counter is at 5.
oct. 22 22:03:34 soso systemd[1]: Stopped Service for snap application multipass.multipassd.
oct. 22 22:03:34 soso systemd[1]: snap.multipass.multipassd.service: Start request repeated too quickly.
oct. 22 22:03:34 soso systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
oct. 22 22:03:34 soso systemd[1]: Failed to start Service for snap application multipass.multipassd.
```

The ligne ```Caught an unhandled exception: unable to create directory path``` shows that multipass is unable to create the folder. However, the rights are correct ...

Someone has found a solution ? 🤔

**Comment by georgeliao** [comment]
@vilm725 

Sorry that you have encountered this. Thanks for the log, that does give us some clues. 

It smells like a permission thing. Can you first try to run `mount | grep /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2` and check whether it is `(rw)` as opposed to `(ro)`?

**Comment by vilm725** [comment]
Hi @georgeliao 

I get no response when I use your command :

```
soso@soso:~$ mount | grep /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2
soso@soso:~$ mount | grep /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/
```

Maybe there's more information with this command:

```
soso@soso:~$ ls -la /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2
total 12
drwxr-xr-x  3 root root 4096 oct.  23 23:01 .
drwxr-x---+ 6 root root 4096 oct.  24 08:49 ..
drwx------  4 root root 4096 oct.  23 23:10 multipass
soso@soso:~$ ls -la /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/
ls: cannot open directory '/media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/': Permission denied
soso@soso:~$ sudo ls -la /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/
total 16
drwx------ 4 root root 4096 oct.  23 23:10 .
drwxr-xr-x 3 root root 4096 oct.  23 23:01 ..
drwxr-xr-x 4 root root 4096 oct.  23 23:10 cache
drwxr-xr-x 7 root root 4096 oct.  24 10:07 data

```

Do you think I should create a mount point for my partition in a folder in my home? Honestly, I don't see why I should because all my softs save my datas in my external ssds (1 ext4 partition via a lvm group of 5 ssd of different sizes) but maybe that would solve the problem only for multipass?

**Comment by georgeliao** [comment]
I think it is already mounted based on the file browser's triangle symbol on the disk. Maybe just try `mount | grep media` or `mount` and manually check to confirm this.  

About the permissions, `drwx------  4 root root 4096 oct.  23 23:10 multipass`, the last three digits `---` does prohibit other users like `soso` to read, write and execute it. But `multipassd` is run by root user who should have the elevated privilege, so he should be able to operate on this directory. Can you login into root user and do the same thing (`ls -la /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/`) to confirm that?

**Comment by georgeliao** [comment]
Another thing to consider is whether the `sudo snap connect multipass:removable-media` step is done correctly. Can you simply run `snap connections multipass` and check whether the `removable-media` is there?

**Comment by georgeliao** [comment]
> About the permissions, drwx------  4 root root 4096 oct.  23 23:10 multipass, the last three digits --- does prohibit other users like soso to read, write and execute it. But multipassd is run by root user who should have the elevated privilege, so he should be able to operate on this directory. Can you login into root user and do the same thing (ls -la /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/) to confirm that?

I think I missed that the owner is the root already, so the multipassd run by root should have the right permission already.

**Comment by vilm725** [comment]
In fact, I've just seen that it works... What have I really done? I don't know.
The multipass files are in my external ssds :

```
soso@soso:~$ sudo ls -la /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/
total 16
drwx------ 4 root root 4096 oct.  23 23:10 .
drwxr-xr-x 3 root root 4096 oct.  23 23:01 ..
drwxr-xr-x 4 root root 4096 oct.  23 23:10 cache
drwxr-xr-x 7 root root 4096 oct.  24 10:07 data
```

Here is the result of the command ```snap connections multipass``` : 
```
soso@soso:~$ snap connections multipass
Interface               Plug                         Slot                            Notes
content[gnome-42-2204]  multipass:gnome-42-2204      gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   multipass:gtk-3-themes       gtk-common-themes:gtk-3-themes  -
content[icon-themes]    multipass:icon-themes        gtk-common-themes:icon-themes   -
content[sound-themes]   multipass:sound-themes       gtk-common-themes:sound-themes  -
desktop                 multipass:desktop            :desktop                        -
desktop-legacy          multipass:desktop-legacy     :desktop-legacy                 -
firewall-control        multipass:firewall-control   :firewall-control               -
gsettings               multipass:gsettings          :gsettings                      -
home                    multipass:all-home           :home                           -
kvm                     multipass:kvm                :kvm                            -
libvirt                 multipass:libvirt            -                               -
lxd                     multipass:lxd                -                               -
multipass-support       multipass:multipass-support  :multipass-support              -
network                 multipass:network            :network                        -
network-bind            multipass:network-bind       :network-bind                   -
network-control         multipass:network-control    :network-control                -
network-manager         multipass:network-manager    :network-manager                -
network-observe         multipass:network-observe    :network-observe                -
opengl                  multipass:opengl             :opengl                         -
removable-media         multipass:removable-media    :removable-media                manual
system-observe          multipass:system-observe     :system-observe                 -
unity7                  multipass:unity7             :unity7                         -
wayland                 multipass:wayland            :wayland                        -
x11                     multipass:x11                :x11                            -
```

It is clear that ```removable-media         multipass:removable-media    :removable-media                manual``` is activated.

Here is the result of the command ```mount | grep media``` :
```
mount | grep media
/dev/sdc1 on /media/soso/DD-1TO-INTERNE type ntfs3 (rw,nosuid,nodev,relatime,uid=1000,gid=1000,windows_names,iocharset=utf8,uhelper=udisks2)
/dev/mapper/luks-9fcde5f6-1207-4924-95dd-83d5803649d9 on /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea type ext4 (rw,nosuid,nodev,relatime,errors=remount-ro,stripe=32,uhelper=udisks2)
```

Now, what I don't understand is why multipass refuses to put it in a specific folder on my external ssd? 🤔

**To summarize**, when I wanted to put it in ```/media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/```, it's work, but not in ```/media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea/multipass/```. Any ideas?

**Comment by georgeliao** [comment]
> Now, what I don't understand is why multipass refuses to put it in a specific folder on my external ssd? 🤔
> 
> To summarize, when I wanted to put it in /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/, it's work, but not in /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea/multipass/. Any ideas?

Not sure I fully understand this part, based on what you have shown. Your file hierarchy is always that the `cache` and `data` folder sit in `/media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/multipass/`. Are you saying the `Environment=MULTIPASS_STORAGE=<path>` path value in `/etc/systemd/system/snap.multipass.multipassd.service.d/ `is either `b24d9c94-c66c-4dec-9635-1bf2bd8bdeea2/` or `b24d9c94-c66c-4dec-9635-1bf2bd8bdeea/multipass/` made a difference?

**Comment by vilm725** [comment]
I finally did it! I've done it again, but this time it works. Is it because I've updated virtualbox? I'm not sure.
I'm really sorry to have wasted your time, and thanks again @georgeliao 👋🏻

A brief summary of my orders:

```
# 🔥 **Important** : update your hypervisor (lxd, virtualbox, hyper v, qemu, libvirt, etc)

sudo snap stop multipass
sudo snap connect multipass:removable-media

# Change by your path
sudo chown root /media/soso/b24d9c94-c66c-4dec-9635-1bf2bd8bdeea/multipass/
# Check rights using the ls -la command, for example

# If there's an error with this command, don't worry
sudo mkdir /etc/systemd/system/snap.multipass.multipassd.service.d/
sudo nano /etc/systemd/system/snap.multipass.multipassd.service.d/override.conf
# Set the path you want

sudo systemctl daemon-reload

# 💡 **info** : If you need to migrate instances, use the doc with the two cp commands

# And finally
sudo snap start multipass

# Delete everything in the old multipass path, to save as much space as possible on your ssd
```

Now, deploy and test your virtual machine. The faster method, deploy a blueprint with docker pre-installed and run nginx : 
```
# Change specs if you want
multipass launch docker --name mydockerserver --memory 2G --cpus 2

# Run container
docker run -d --name hello-multipass -p 8080:80 nginx:alpine-slim

# Open a window with firefox and enter the ip address of your machine with port 8080, for exemple : 192.168.1.100:8080
```

If the machine worked fine, with no errors, and you've succeeded in deploying your container, but it can't be accessed via your browser, then you need to look at the network side instead.

If you have any questions, I'll be happy to answer them. Thanks again to this wonderful community 👋🏻

**Comment by georgeliao** [comment]
@vilm725 
Thanks for the sharing the discovery. Then it looks like the doc recipe is fine. I will close the issue. Feel free to open if something is not working as expected. 

@qianlvzhe 
You issue looks like something else. I suggest you to look into https://github.com/canonical/multipass/issues/3737 and try the solution there. If it does not fix, then maybe open an new issue with detailed description of the behavior.
