### ISSUE TITLE
[GUIDE] How to migrate instances between different machines

### ISSUE THREAD

**Issue by lars18th** [canonical/multipass#3755]
Hi,

I want to share this mini-guide. The idea is to provide this technical information to other users. And at the same time propose a new functionality of a ‘migrate’ command. This functionality is already requested in other issues.

Guide to migrating an instance from one Linux host to another Windows host:

- The Linux machine is Ubuntu with a recent multipass package installed with snap. And the Windows machine is Windows 11 Pro with Hyper-V enabled and the same multipass version.
- Copy the vdisk of the donor instance from the Linux machine to one directory of the Windows machine. Location of source: `/var/snap/multipass/common/data/multipassd/vault/instances/<instance_name>/*.qcow2` (or "*.img" depending on the hypervisor used).
- Convert the vdisk to VHDX format. You need to use `qemu-img.exe` (native win32 tool) or `qemu-img` (from WSL); or you can do the conversion in the original Linux machine: `qemu-img convert <donor>.qcow2 -O vhdx -o subformat=<donor>.vhdx`.
- Create a new instance in the Windows machine with similar (but not necessary identical) configuration, but with the same name: `multipass launch –n <instance_name> … `.
- Stop the new created instance and search for the disk. Common location: `C:\ProgramData\Multipass\data\vault\instances\<instance_name>\*.vhdx` _(Warning: to complete this action and from this point you need administrator privileges)_.
- Using WSL (or moving the *.vhdx disk to the Linux machine) mount the two root filesystems. For example with: `sudo qemu-nbd --connect=/dev/nbd0 <donor>.vhdx; sudo qemu-nbd --connect=/dev/nbd1 <target>.vhdx; sudo mount /dev/nbd0p1 /media/donor; sudo mount /dev/nbd1p1 /media/target;`
- Now copy **from “target”** to “donor” the ssh config data of the instance used by the multipass daemon. The files are: `/etc/ssh/ssh_host*` (remove first all of them in donor, perhaps more formats exists in the donor filesystem) and the `/home/ubuntu/.ssh/authorized_keys`.
- Umount all filesystems and move the `<donor>.vhdx` file to the directory where `<target>.vhdx` file exists.
- Copy the permissions with PowerShell `Get-Acl <target>.vhdx | Set-Acl <donor>.vhdx` and delete the <target>.vhdx file.
- Rename the `<donor>.vhdx` file with the original filename of the target vdisk.
- Start the instance and check it: `multipass shell <instance_name>`.

This works because the trick is to replace all the ssh data of the original instance with the data of the temporary instance. You don't need to change anything else to migrate an instance to another machine. Just copy/convert the instance disk image. I have completed multiple migrations without any trouble using this technique.

I hope the developers will want to add support for this. Although at the moment we already have a manual process to achieve this.

Regards.

**Comment by georgeliao** [comment]
Hi @lars18th 
About the migrate instance feature, since we already have a feature request on this. I am gotta close this one.

**Comment by giuliazanchi** [comment]
Hi @lars18th , if you want you can create a new Discourse topic in our [Community Knowledge category](https://discourse.ubuntu.com/c/multipass/community-knowledge/267). Or, I can create if for you if you like. Thanks for your input!

**Comment by lars18th** [comment]
> > Or, I can create if for you if you like. Thanks for your input!
> 
> Dear @giuliazanchi , I recommend that you do so. 👍

Hi @giuliazanchi ,
Do you do it?

**Comment by melutovich** [comment]
@lars18th @giuliazanchi I'm just wondering since the <donor>.vhdx is edited, perhaps a comment that one should ensure that this is a copy of the original disk that is being edited until one has verified the next instance is functional and one does not need the original instance as well.

 In "Copy the permissions with PowerShell Get-Acl <target>.vhdx | Set-Acl <donor>.vhdx and delete the .vhdx file." the 'delete the .vhdx file' is specially for deleting the <target>.vhdx

**Comment by lars18th** [comment]
Hi @melutovich ,

Thank you for pointing this. At start my post was only to describe that the _migration process_ could be done. And describe more or less the process. With the idea of pointing the key aspects: 1) the configuration, 2) the ssh key to access to the instance.

My suggestion now is to write a PowerShell script that could complete the process. The problem is that multiple use cases could exist. For example: Linux QEmu --> Windows Hyper-V. And this is only one case of the multiple sources and targets.

But if someone will develop such script, then perhaps the main developers will want to incorporate the process internally.
