### ISSUE TITLE
New vm launch getting timedout

### ISSUE THREAD

**Issue by aamirqs** [canonical/multipass#3757]
**Describe the bug**
Describe what your problem is.
Just Installed Multipass, The new VM launch is getting timed out, and the VM stays in an Unknown state.
the issue is system-specific. I was able to launch VM's before not sure what happened, recently I installed Whiskey not sure if it is related. 
System: Mac M3

**To Reproduce**
How, and what happened?
1. `multipass launch foo`

**Expected behavior**
What did you expect to happen?
VM to launch successfully
[multipassd.log](https://github.com/user-attachments/files/17535932/multipassd.log)

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: mac OS 15.0.1 
- `multipass version
multipass   1.14.0+mac
multipassd  1.14.0+mac`
- `multipass info   
    Name:           foo
    State:          Unknown
    Snapshots:      0
    IPv4:           --
    Release:        --
    Image hash:     e380b683b0c4 (Ubuntu 24.04 LTS)
    CPU(s):         --
    Load:           --
    Disk usage:     --
    Memory usage:   --
    Mounts:         --
    
    Name:           quiet-bull
    State:          Unknown
    Snapshots:      0
    IPv4:           --
    Release:        --
    Image hash:     e380b683b0c4 (Ubuntu 24.04 LTS)
    CPU(s):         --
    Load:           --
    Disk usage:     --
    Memory usage:   --
    Mounts:         --`
- `multipass get local.driver
qemu`

**Additional context**

**Comment by ricab** [comment]
Hi @aamirqs, can you please try the latest release? https://github.com/canonical/multipass/releases/tag/v1.14.1

**Comment by aamirqs** [comment]
Works with the latest release, Thanks!
