### ISSUE TITLE
Multipass is not working on Windows

### ISSUE THREAD

**Issue by Hansonpython** [canonical/multipass#3769]
I installed `multipass-1.14.1+win-win64`. 
During the installation process, it displays `Failed to set driver to virtualbox`. (I only have virtualbox, and I installed virtualbox before install multipass).
But I installed multipass successfully.
Then, I open `multipass.gui.exe`, It keeps showing `Waiting for daemon`.
I closed GUI program.
I ran `multipass.exe`, It displays `[error] [client] Caught an unhandled exception: failed to open file 'C:/Users/my-username/AppData/Local/multipass-client-certificate/multipass_cert_key.pem': Illegal byte sequence(42).`(My username contains Chinese characters.)
I read Issues [#1314](https://github.com/canonical/multipass/issues/1314).
But Release `1.0.0+win-win64` can't solve my problem.
I opened `eventvwr` to show last log.
It displays this:
```
错误应用程序名称: multipass.exe，版本: 0.0.0.0，时间戳: 0x5df428fa
错误模块名称: ucrtbase.dll，版本: 10.0.22621.3593，时间戳: 0x10c46e71
异常代码: 0xc0000409
错误偏移量: 0x000000000007f6fe
错误进程 ID: 0x0x15B8
错误应用程序启动时间: 0x0x1DB31CC3F91DFAA
错误应用程序路径: E:\multipass\bin\multipass.exe
错误模块路径: C:\WINDOWS\System32\ucrtbase.dll
报告 ID: 68f1692e-253c-4607-8dc5-36c8bc1d60fc
```
 (Chinese version)

```
Incorrect application name: multipass.exe, version: 0.0.0.0, timestamp: 0x5df428fa
Error module name: ucrtbase.dll, version: 10.022621.3593, timestamp: 0x10c46e71
Exception code: 0xc0000409
Error offset: 0x00000007f6fe
Error process ID: 0x0x15B8
Error application startup time: 0x0x1DB31C3F91DFAA
Wrong application path: E:\multipass\multipass\bin\multipass.exe
Error module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 68f1692e-253c-4607-8dc5-36c8bc1d60fc
```
(English Version)

Why is that?
Is it because my username contains Chinese characters?
Is there a specific version that can solve this problem?

OS version: 
```
Microsoft Windows 23H2 22631.4391
Windows 11 Home Chinese Edition
```

**Comment by levkropp** [comment]
Hi @Hansonpython,

Thank you for reporting this issue and providing detailed information,
We are aware that Multipass on Windows has trouble handling usernames with non-English characters, such as Chinese characters. This is a known issue we're tracking in [#1314](https://github.com/canonical/multipass/issues/1314). Unfortunately, there is no fix available at the moment, but it's something we'd like to address in the future.

As a workaround, you might consider creating a new Windows user account that contains only English characters. This should allow Multipass to function properly until we resolve the issue.

**Comment by Hansonpython** [comment]
Thank you very much.
I will try to create a new account.
If it can solve the problem, I will close this issue.
