### ISSUE TITLE
[documentation] client authentication workaround is Linux specific

### ISSUE THREAD

**Issue by dinesh-pandikona** [canonical/multipass#3773]
**Describe the bug**
I was following [this](https://multipass.run/docs/authenticating-clients) to authenticate client. I followed the workaround mentioned in the last portion of "Troubleshooting"

**To Reproduce**
How, and what happened?
1. `cat ~/snap/multipass/current/data/multipass-client-certificate/multipass_cert.pem | sudo tee -a /var/snap/multipass/common/data/multipassd/authenticated-certs/multipass_client_certs.pem > /dev/null`

2. `snap restart multipass`

**Expected behavior**
What did you expect to happen?
`❯ sudo snap restart multipass`

`Interacting with snapd is not yet supported on darwin.
This command has been left available for documentation purposes only.`

**Additional info**
 - OS: MacBook Air
  Model Identifier:	Mac14,15
- `multipass version` : multipass   1.14.1+mac
- `multipass info` : No instances found.
- `multipass get local.driver` : qemu

**Comment by sharder996** [comment]
Hi @dinesh-pandikona,

`snap` and `snapd` is service that is used in various Linux distributions, so it won't work on macOS. If you have somehow lost contact with the Multipass daemon, you can execute the following commands to restart the Multipass daemon and the first client to connect with it will automatically be authenticated:

```
sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
```

**Comment by sharder996** [comment]
@giuliazanchi We should probably update this piece of the documentation to mention that it is Linux specific.

https://multipass.run/docs/authenticating-clients#the-client-cannot-be-authorized-and-the-passphrase-cannot-be-set

and under 

> The following workaround should help get out of this situation:

**Comment by dinesh-pandikona** [comment]
it worked @sharder996 . Thank you so much 👍
