### ISSUE TITLE
Derive the GUI size as a percentage of the screen, when within the [min,max] range

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#3812]
**What are you trying to do?**
Resize the GUI to a sensible percentage of the screen when within a common range.

**What's your proposed solution?**
For screen resolutions in the range ]1024x576, 1600x900[ (exclusive on both ends), resize the GUI to the largest rectangle that is the same ratio of the screen (e.g. 16x9) and enclosed in 80% of the screen. For resolutions outside of those bounds, resize the GUI to same size as today (750x450 when below, 1400x822 when above).

When the screen size cannot be determined, resize the GUI to 750x450.

In the above, the resolution is *in the range* iff the corresponding rectangle encloses the lower bound and is enclosed by the higher bound (with no overlaps).

**Additional context**
In the future, we could consider varying the aspect ratio according to the screen, but we'd need special handling for ultra wide. Actual percentages and sizes open for adjustment (e.g. to minimize how much smaller we go when crossing the high bound).

**Comment by andrei-toterman** [comment]
> When the screen size cannot be determined, resize the GUI to 1024x576.

Shouldn't it be 750x450 aka the minimum if we can't determine the screen size?

**Comment by ricab** [comment]
We [discussed that](https://github.com/canonical/multipass/pull/3811#discussion_r1869973649). I thought not, but perhaps it's best if you both think that way. Feel free to edit the description then.

**Comment by andrei-toterman** [comment]
Well, since the GUI will remember its last size, I think it's more acceptable for it to start in a small size that the user can expand than for it to start on a size that might be too big.

**Comment by ricab** [comment]
I see your point. I would agree if I didn't expect most screens to have a larger size in practice, where the small GUI doesn't look very good. In the worse case, people can still resize, although it is not obvious. It is a worse situation, but one that I'd expect to be infrequent, whereas I worry that the other one may come about often. 

But I don't know how often we expect this whole scenario to come about (might be worth a log). Anyway, not my preference, but I'll yield.

**Comment by andrei-toterman** [comment]
I'm also not really sure how often this scenario can come up. My assumption is that in the vast majority of cases, determining the screen size would work without issue. I'm not even sure what could prevent the screen size from being retrieved. The implementation of that plugin just calls some standard platform methods from winapi, gtk and cocoa, which should in principle `just work™`
