### ISSUE TITLE
multipass start timeout in windows11

### ISSUE THREAD

**Issue by jack-yu** [canonical/multipass#3843]
**Describe the bug**
Describe what your problem is.
I installed multipass v1.14.0 a week ago, it worked well at first. But last weekend I found my vm was down and I can't start it again.

I try to update multipass to v1.15.0, but it didn't work. The cmd like below:

```
PS C:\Users\mailo>multipass start ubuntu24
start failed: The following errors occurred:
ubuntu24: timed out waiting for response
```
`ubuntu24` is my vm's name. 

By the way, I'm using hyper-V, not virtualBox. And I can see my vm in hyper-V manager and I can start or stop my vm in hyper-V manager.

**To Reproduce**
How, and what happened?
1. `multipass start ubuntu24` wait and timeout
1.

**Expected behavior**
What did you expect to happen?

start my vm properly.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

```
级别	日期和时间	来源	事件 ID	任务类别
信息	2024/12/16 8:44:02	Multipass	1	无	[async task] fetch manifest periodically

信息	2024/12/16 8:44:02	Multipass	1	无	[image vault] Checking for images to update鈥?
信息	2024/12/16 8:46:14	Multipass	1	无	[powershell.exe] [15664] started: powershell.exe -NoProfile -NoExit -Command -

信息	2024/12/16 8:46:14	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber'

信息	2024/12/16 8:46:14	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:14	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty ReleaseId'

信息	2024/12/16 8:46:14	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:14	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet: 'Get-CimInstance Win32_ComputerSystem | Select-Object -ExpandProperty HypervisorPresent'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet: 'Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V | Select-Object -ExpandProperty State'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet: 'Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor | Select-Object -ExpandProperty State'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet: 'Get-Service -Name vmms | Select-Object -ExpandProperty Status'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:15	Multipass	1	无	[Hyper-V Health Check] [15664] PowerShell finished successfully

信息	2024/12/16 8:46:15	Multipass	1	无	[ubuntu24] [18188] Cmdlet: 'Start-VM -Name ubuntu24'

信息	2024/12/16 8:46:17	Multipass	1	无	[ubuntu24] [18188] Cmdlet exit status is 'true'

信息	2024/12/16 8:46:17	Multipass	1	无	[ubuntu24] Waiting for SSH to be up

信息	2024/12/16 8:49:33	Multipass	1	无	[update] Latest Multipass release available is version 1.15.0

信息	2024/12/16 8:59:11	Multipass	1	无	[async task] fetch manifest periodically

信息	2024/12/16 9:04:36	Multipass	1	无	[ubuntu24] SSH session disconnected

信息	2024/12/16 9:04:36	Multipass	1	无	[ubuntu24] Caching new SSH session

信息	2024/12/16 9:06:11	Multipass	1	无	[daemon] Returning setting local.driver=hyperv

信息	2024/12/16 9:14:14	Multipass	1	无	[async task] fetch manifest periodically

```

**Additional info**
 - OS: windows 11
- `multipass version` 1.15.0

>PS C:\Users\mailo> multipass version
>multipass   1.15.0+win
>multipassd  1.15.0+win

- `multipass info`

>PS C:\Users\mailo> multipass info
>info failed: ssh connection failed: 'Timeout connecting to ubuntu24.mshome.net'

- `multipass get local.driver`

>PS C:\Users\mailo> multipass get local.driver
>hyperv

**Additional context**

**Comment by ricab** [comment]
Hi @jack-yu, could you please have a look at [this troubleshooting guide](https://discourse.ubuntu.com/t/troubleshoot-launch-start-issues/48104) and see if anything in there helps? Let us know what you find!

**Comment by jack-yu** [comment]
> Hi @jack-yu, could you please have a look at [this troubleshooting guide](https://discourse.ubuntu.com/t/troubleshoot-launch-start-issues/48104) and see if anything in there helps? Let us know what you find!

It's amazing~ it works

I found the solution in  [stale-internet-connection-sharing-lease](https://discourse.ubuntu.com/t/troubleshoot-launch-start-issues/48104#stale-internet-connection-sharing-lease). I removed any of them except for the first one listed on the file `C:\WINDOWS\System32\drivers\etc\hosts.ics`. All things goes well now, thanks a lot :)

**Comment by ricab** [comment]
Ahh, good news, thanks!
