### ISSUE TITLE
Launch VM failed: Property 'host-arm-cpu.sme' not found

### ISSUE THREAD

**Issue by ivoterhorst** [canonical/multipass#3859]
**Describe the bug**
Trying to launch any of the default of available VMs, e.g. `multipass launch docker --name node1`. This fails:
> launch failed: The following errors occurred:
> Unexpected error in object_property_find_err() at ../../../qom/object.c:1330:
> qemu-system-aarch64: Property 'host-arm-cpu.sme' not found 

It then shows up with state `Unknown` when performing `multipass list`.

**To Reproduce**
1. Clean install of Multipass 1.15.0 on Mac OS Sequoia 15.2
2. `multipass launch docker --name node1`
3. `multipass launch lts --name test1`

Both show the same error

**Expected behavior**
A working VM

**Logs**
[multipass.log](https://github.com/user-attachments/files/18241513/multipass.log)

**Additional info**
 - OS: macOS 15.2 (On Apple M4Pro)
- `multipass version`: 1.15.0+Mac
- `multipass info`: Name:           node1
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     6e1f90d3e81b (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           test1
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     6e1f90d3e81b (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
- `multipass get local.driver`: qemu

**Additional context**

**Comment by levkropp** [comment]
Hi @ivoterhorst, thanks for bringing this up! This seems to be the same issue as #3482. Please check out the workaround mentioned there. I'll close this issue to keep the discussion centralized.

**Comment by ivoterhorst** [comment]
Thank you for letting me know that this is already a know issue. There seems to be a typo in the reference to the known issue; I believe that you meant this one: [#3842](https://github.com/canonical/multipass/issues/3842#issuecomment-2552189605).
