### ISSUE TITLE
Network timeout too aggressive

### ISSUE THREAD

**Issue by sergiusens** [canonical/multipass#386]
If my network is not at its best state with regards to latency, it is rather easy to get:
```
$ multipass launch
failed to launch: Network timeout                                               
$ multipass launch                        
failed to launch: Network timeout
```

As a side data point, using snapcraft or having lxd auto trigger the new image download does not timeout like this. I have not timed it, but feels like it waits only 2 seconds to decide on a timeout.

**Comment by Saviq** [comment]
It looks like the simplestreams index downloader is what this bails on.

**Comment by townsend2010** [comment]
It is set to be a 10 second timeout for any network activity such as fetching the SimpleStreams data or an image.  If it is indeed shorter than ~10 seconds, then something strange is going on.  But if it is 10 seconds, then maybe we need to bump up the timeout...but to what??

**Comment by townsend2010** [comment]
LXD just uses whatever the Go network stuff gives it, so I'll have to dig into that stuff to figure it out.  

One thing I thought of though is that we give it 10 seconds total to fully download the SimpleStreams manifest, so for high latency/low bandwidth setups, this is not optimal.  I think instead, we should just detect if any progress is being made and if so, let it keep chugging along and only timeout if no progress is being made in 10 seconds (or some other arbitrary timeout).

**Comment by Saviq** [comment]
> It is set to be a 10 second timeout for any network activity such as fetching the SimpleStreams data or an image.

[`url_downloader.cpp#L60`](https://github.com/CanonicalLtd/multipass/blob/v0.5/src/network/url_downloader.cpp#L60) actually shows the shorthand `URLDownloader(const QUrl& url)` used for index downloads does not have this treatment. It will plain time out after 10s.

**Comment by Lin-Buo-Ren** [comment]
I wonder if this issue is the same as the `[error] [daemon] Error fetching image information: Network timeout` error message when running `multipass list`?

**Comment by Saviq** [comment]
@Lin-Buo-Ren that is [quite likely](https://github.com/CanonicalLtd/multipass/blob/v0.5/src/daemon/daemon.cpp#L1037), yes, is that what you've been having trouble with `snapcraft` with?

**Comment by Lin-Buo-Ren** [comment]
> @Lin-Buo-Ren that is [quite likely](https://github.com/CanonicalLtd/multipass/blob/v0.5/src/daemon/daemon.cpp#L1037), yes, is that what you've been having trouble with `snapcraft` with?

Not really with the previous one, it just kept coming out for my attention.
It would be great if multipass can support custom image remotes as `lxc remote` does, but that's other issue.
