### ISSUE TITLE
provide snapcraft aliases for VMs

### ISSUE THREAD

**Issue by sergiusens** [canonical/multipass#387]
As a proposal:

- snapcraft-core18 -> 18.04
- snapcraft-core16 -> 16.04
- snapcraft-core -> 16.04 (this is a special snowflake as it is not a base, but it is a _core_ base?)

**Comment by Saviq** [comment]
@sergiusens would you object to it being `snapcraft:…` instead of the hyphen? It would make for a better isolation of the snapcraft build VMs IMO.

**Comment by sergiusens** [comment]
El 18/09/18 a las 10:15, Michał Sawicz escribió:
>
> @sergiusens <https://github.com/sergiusens> would you object to it 
> being |snapcraft:…| instead of the hyphen? It would make for a better 
> isolation of the snapcraft build VMs IMO.
>

No objections!
