### ISSUE TITLE
info failed: ssh: Timeout connecting to (IP)

### ISSUE THREAD

**Issue by popey** [canonical/multipass#394]
I'm doing a build via `snapcraft` and `SNAPCRAFT_BUILD_ENVIRONMENT=multipass`. I want to poke about in the VM while it's building, as it takes ages and I want to see what it's doing.

I am unable to get in.

```
alan@KinkPad-K450:~/src/che$ multipass list | grep che
snapcraft-che           RUNNING     10.185.163.90    Ubuntu 18.04 LTS
alan@KinkPad-K450:~/src/che$ multipass shell snapcraft-che
shell failed: ssh: Timeout connecting to 10.185.163.90
alan@KinkPad-K450:~/src/che$ multipass info snapcraft-che
info failed: ssh: Timeout connecting to 10.185.163.90
```

**Comment by Saviq** [comment]
This looks like the VM went into a busy loop...

One thing to try:
`snap set multipass driver=LIBVIRT`

Then, when building with snapcraft you can use `multipass.virsh` to introspect the machine (and connect to its console) or hook it up to `virt-manager` with:
`virt-manager -c qemu+unix:///system?socket=/var/snap/multipass/common/run/libvirt/libvirt-sock`

@sergiusens is there a snapcraft mode where it will be more verbose about the build?
