### ISSUE TITLE
Need to wait for `cloud-init` to complete

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#41]
If you try to interact with an instance before `cloud-init` completes, it might fail (say, `apt` still updating), or even worse we can interrupt some `cloud-init` steps and leave the instance in a bad state.

**Comment by townsend2010** [comment]
Yep, I was planning on fixing this very soon:)  The best way I've found is to poll the instance on first boot for /var/lib/cloud/instance/boot-finished, and when that file shows up, the cloud-init is done.

Also, we should check /var/lib/cloud/data/result.json to check for errors in cloud-init.
