### ISSUE TITLE
Can't launch core images

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#412]
On both `edge` and `beta`, launching core instances fails (trying to launch it manually it tries to PXE boot after saying that hard disk is not bootable).

This part is suspicious:
```
$ multipass launch core -vv
[2018-09-27T11:00:31.200] [warning] [Qt] QProcess: Destroyed while process ("qemu-img") is still running.
```

**Comment by Saviq** [comment]
The same image we download, downloaded manually seems to work fine, so whatever we do to it with `qemu-img` seems to be causing this. And this happens for both libvirt and qemu backends.

However it doesn't seem to happen when built from source... wonder if it's something bad with my system.

**Comment by townsend2010** [comment]
Hmm, it's working for me...I wonder if somehow I'm using qemu-img on the local machine and you are using qemu-img in the snap and that is somehow not working??

**Comment by Saviq** [comment]
Realized the default timeout for [`QProcess::waitForFinished`](http://doc.qt.io/qt-5/qprocess.html#waitForFinished) is 30s...
