### ISSUE TITLE
Network bridges leaking

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#413]
When switching between `QEMU` and `LIBVIRT` backends, the bridges are left behind:
```
$ brctl show               
bridge name     bridge id               STP enabled     interfaces
mpqemubr0       8000.52540055481d       no              mpqemubr0-dummy
mpvirtbr0       8000.52540039b09a       yes             mpvirtbr0-nic
```

**Comment by townsend2010** [comment]
It looks to me that the mpvirtbr0 bridge is the one that sticks around, as reported in #327.  I tried switching between the two backends and for me, the mpqemu* based devices are removed as they should.

Is this your experience or are you seeing the mpqemu* being left behind as well?

**Comment by Saviq** [comment]
Indeed no, this might've been me switching from `LIBVIRT` back to `QEMU` and that's how there were two.

**Comment by townsend2010** [comment]
Ok, good...I'll fix the libvirt side and hopefully be done with this:)
