### ISSUE TITLE
Homebrew recipe for macOS install

### ISSUE THREAD

**Issue by tristanpemble** [canonical/multipass#437]
Would love to be able to have my team just `brew install multipass`!

**Comment by Saviq** [comment]
It should be pretty easy to add a cask indeed:
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by Saviq** [comment]
There we go: https://github.com/Homebrew/homebrew-cask/pull/53503

**Comment by townsend2010** [comment]
This is landed now:)
