### ISSUE TITLE
`exec` does not exit on EOF

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#45]
It's possible to pipe stdin into `multipass exec`, but EOF there isn't passed through?

This works:
```
⟫ multipass exec instance tee foo
bar
^D
```

But this hangs:
```
⟫ echo bar | multipass exec instance tee foo
```

**Comment by townsend2010** [comment]
After much debugging, I found this to be a bug in libssh.

In it's polling of stdin, it does not check if POLLHUP (which indicates EOF) is set on the fd.  It's a very simple fix and I'll plan on proposing it in upstream libssh.  In the meantime, we'll probably need to patch the version we are using.

**Comment by townsend2010** [comment]
BTW, here is the simple diff:
 
```
diff --git a/src/connector.c b/src/connector.c
index 54e85241..714ef815 100644
--- a/src/connector.c
+++ b/src/connector.c
@@ -368,7 +368,7 @@ static int ssh_connector_fd_cb(ssh_poll_handle p,
 
     if (revents & POLLERR) {
         ssh_connector_except(connector, fd);
-    } else if((revents & POLLIN) && fd == connector->in_fd) {
+    } else if(((revents & POLLIN) || (revents & POLLHUP)) && fd == connector->in_fd) {
         ssh_connector_fd_in_cb(connector);
     } else if((revents & POLLOUT) && fd == connector->out_fd) {
         ssh_connector_fd_out_cb(connector);
```

**Comment by townsend2010** [comment]
Here is the upstream bug report:

https://bugs.libssh.org/T81

**Comment by townsend2010** [comment]
Still no response from upstream.  If we don't get a response soon, we should probably clone our own libssh branch, fix it, and point our submodule to it.

**Comment by simos** [comment]
I think the bug report on libssh would need a bit of description to demonstrate the issue.

With plain SSH, the following works
```
$ echo bar | ssh localhost tee foo
bar
$ 
```

Perhaps a link to this report or a suitable example with plain SSH that demonstrates the issue?

**Comment by townsend2010** [comment]
@simos, I took your advice and updated the upstream bug report with some more info including linking to this bug.  I do think the libssh maintainers simply have not been active this week:)
