### ISSUE TITLE
Bad messaging when `multipass` can't connect to the socket

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#460]
```
$ multipass find
find failed: Connect Failed
```

There may be multiple reasons why you wouldn't be able to connect to the socket - the daemon being dead, the socket being in a different place, or the permissions being wrong. All of that results in the above, not giving much of a clue on what's going on.

**Comment by carmine** [comment]
I ran into this issue while installing multipass in a VM on GCP. Multipass installs into group sudo, which I wasn't part of. After adding myself to `sudo`, I was able to run the command.

Would be great if multipass find told me that :-)

**Comment by townsend2010** [comment]
This is an awful limitation of gRPC.  They do not bubble up any sort of OS/system errors in these cases.

So what we are going to have to do is put logic in the client to test if it can connect successfully to the socket.

**Comment by hoto** [comment]
I'm on fedora and while trying to use `snapcraft` I couldn't run `multipass` even after adding myself to `sudo`
I ended up changing the user and group for the socket.

```
$ snapcraft
Launching a VM.
launch failed: cannot connect to the multipass socket                           
Please ensure multipassd is running and '/run/multipass_socket' is accessible
An error occurred when trying to launch the instance with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.

$ multipass list
list failed: multipass socket access denied
Please check that you have read/write permissions to '/run/multipass_socket'

$ ls -la /run/multipass_socket
srw-rw----. 1 root adm 0 Feb 23 16:29 /run/multipass_socket

$ sudo chown $USER:$USER /run/multipass_socket

$ multipass list
No instances found.
```

It does seem to work fine now.

**Comment by 6umpukc-uHKBu3umop** [comment]
>  multipass list                                                                             :(
> list failed: multipass socket access denied
> Please check that you have read/write permissions to '/var/snap/multipass/common/multipass_socket'
> 

`sudo chown user:users /var/snap/multipass/common/multipass_socket`

fix for ArchLinux

**Comment by denisfalqueto** [comment]
> > multipass list                                                                             :(
> > list failed: multipass socket access denied
> > Please check that you have read/write permissions to '/var/snap/multipass/common/multipass_socket'
> 
> `sudo chown user:users /var/snap/multipass/common/multipass_socket`
> 
> fix for ArchLinux

A better fix is add your user to "adm" group. That group has read/write permissions on that socket.

**Comment by 6umpukc-uHKBu3umop** [comment]
i just uninstall ArchLinux and install Ubuntu - this works for me

**Comment by ssbarnea** [comment]
This seems to be a bug in multipass rpm ditribution as the correct group should be wheel not adm.

**Comment by Saviq** [comment]
Hi @ssbarnea thanks for that, I've just proposed #1425 - you should be able to `snap refresh multipass --channel edge/pr1425` in 15 minutes or so (look for a comment from @multipass-ci-bot).
