### ISSUE TITLE
Suppress metrics error message

### ISSUE THREAD

**Issue by carmine** [canonical/multipass#486]
When launching a VM I got the following error message; feels like this should be suppressed.

Starting .. -[2018-11-11T17:16:14.537] [error] [metrics] Metrics error: Error transferring https://api.staging.jujucharms.com/omnibus/v4/multipass/metrics - server replied: Proxy Error - Attempting to resend

**Comment by gerboland** [comment]
Are you behind a proxy?

**Comment by Saviq** [comment]
Any case, we should probably reduce the severity of those messages to warnings.

**Comment by carmine** [comment]
Wasn't behind a proxy, but I may have experienced intermittent networking issues. The error message seemed orthogonal to what I was doing (ie launching a VM) - or at least not critical to the requested operation. 

If these metrics are just nice-to-have, then a warning in a log file should suffice. If the desire to collect is stronger than that, then caching the data and sending at some other time may be appropriate.

**Comment by Lin-Buo-Ren** [comment]
I still see metric errors in the system journal of edge multipass:

```
Metrics error: Error transferring https://api.staging.jujucharms.com/omnibus/v4/multipass/metrics - server replied: Internal Server Error - Attempting to resend
```

It appears that multipassd is run with the `--verbosity debug` flag on.

**Comment by Saviq** [comment]
Yes, it is on purpose to log to journal with debug verbosity, this way we get enhanced history in case of issues.

When looking at the log, you can use the `--priority` switch and note the text formatting/colouring to see what messages are more important.

**Comment by Lin-Buo-Ren** [comment]
> When looking at the log, you can use the `--priority` switch and note the text formatting/colouring to see what messages are more important.

Is there any way to customize it and make the change survive after snap refresh?

**Comment by Saviq** [comment]
What change? The `--priority` switch to `journalctl`? It only affects the display, not what is actually logged. Why would you want to change that?

I noticed we don't pass `$@` to `multipassd` in [our launcher](https://github.com/CanonicalLtd/multipass/blob/v0.5/snap-wrappers/bin/launch-multipassd#L10). Please file an issue about that, it would then allow you to tweak the options with `systemctl edit snap.multipass.multipassd.service`.
