### ISSUE TITLE
multipass bridge subnet may clash

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#49]
We're using a static private subnet of `10.122.122.0/24` for multipass instances, there's a chance that one's already used (like if you installed multipass inside multipass, even if that's not gonna really work).

We should probably try and randomize, and verify there's not a route for it on the host.

**Comment by townsend2010** [comment]
Yep, definitely planned on doing this, just need time:)  Also, we should make this user configurable when we do the multipass init stuff.

**Comment by BurlyLuo** [comment]
can we make a self-definition subnet for the network when init the multipass?

**Comment by BurlyLuo** [comment]
> Hello @townsend2010 thanks for your efforts. An question there. would you pls comment it? can we make a self-definition subnet for the network when init the multipass?
> 
> Or by multipass set xx to achieve?
> 
> ```
> [root@wluo netplan]$ mm set -h 
> Usage: multipass set [options] <key>[=<value>]
> Set, to the given value, the configuration setting corresponding to the given key.
> 
> Some common settings keys are:
>   - client.primary-name
>   - local.driver
>   - local.privileged-mounts
> 
> Use `multipass get --keys` to obtain the full list of available settings at any given time.
> 
> Options:
>   -h, --help     Displays help on commandline options
>   -v, --verbose  Increase logging verbosity. Repeat the 'v' in the short option
>                  for more detail. Maximum verbosity is obtained with 4 (or more)
>                  v's, i.e. -vvvv.
> 
> Arguments:
>   keyval         A key, or a key-value pair. The key specifies a path to the
>                  setting to configure. The value is its intended value. If only
>                  the key is given, the value will be prompted for.
> [root@wluo netplan]$ mm set 
> ```

The issue can be solved with:
```
[root@wluo network]$ pwd
/var/snap/multipass/common/data/multipassd/network
[root@wluo network]$ cat multipass_subnet 
11.1.1
[root@wluo network]$ alias mmrs
alias mmrs='systemctl stop snap.multipass.multipassd.service && systemctl start snap.multipass.multipassd.service && systemctl status snap.multipass.multipassd.service'
[root@wluo network]$ 
```
