### ISSUE TITLE
Extend README.md

### ISSUE THREAD

**Issue by mitra42** [canonical/multipass#497]
Has anyone managed to get this running on OSX, it was suggested as a way to get snap running for development, but the build instructions in the README.md don't work on OSX.  (One version of the instructions requires snap, and the other requires "apt" which isnt' on OSX by default.

Anyone had any luck with it?

**Comment by popey** [comment]
There's a [thread](https://community.ubuntu.com/t/installing-multipass-on-macos/8329) on the Ubuntu Community Hub which details this. There's a build on the [releases](https://github.com/CanonicalLtd/multipass/releases/) page here on github. Have you tried that?

**Comment by mitra42** [comment]
Thanks for the pointer, I made the mistake of trying to follow the README.md :-(

**Comment by Saviq** [comment]
We've reworked README.md since, closing.
