### ISSUE TITLE
Improve behavior of delete command

### ISSUE THREAD

**Issue by jameinel** [canonical/multipass#499]
I was trying to delete and relaunch a container using multipass 2018.10.1 and ran into:

```
$ multipass delete pliable-greyhound
$ multipass launch -n pliable-greyhound bionic
failed to launch: instance "pliable-greyhound" already exists
$ multipass delete pliable-greyhound
delete failed: The following errors occurred:
instance "pliable-greyhound" does not exist
$ multipass delete --purge pliable-greyhound
delete failed: The following errors occurred:
instance "pliable-greyhound" does not exist
$ multipass list
Name                    State             IPv4             Release
...
pliable-greyhound       DELETED           --               Not Available
```

Note that `multipass purge` does seem to properly clean out the record and let me launch, but "multipass delete --purge foo" seems like it should be handling that case as well.

**Comment by ricab** [comment]
I thought a bit about this and I find delete could profit from a bit of a rewrite. Here is how I think it should [behave](https://docs.google.com/document/d/1tP1dmavKhfqUkBqAjkA2CfvlIzpiyztp0SO5ThMgCNQ/edit?usp=sharing). And here is a little [flowchart](https://is.gd/KSPJSN) for a new implementation.

**Comment by Saviq** [comment]
Flowchart looks fine by me.

**Comment by ricab** [comment]
Related to #189
