### ISSUE TITLE
[snap] libvirt fails creating the virtual bridge due to a missing group

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#507]
Log snippet from the failure:
```
Nov 30 17:12:53 hal libvirtd[10213]: internal error: Child process (VIR_BRIDGE_NAME=mpvirtbr0 /snap/multipass/current/usr/sbin/dnsmasq --conf-file=/var/snap/multipass/common/lib/libvirt/dnsm
                                     dnsmasq: unknown user or group: libvirt-dnsmasq
```

This happens on hosts that do not have libvirt installed.  We need to somehow get libvirt to use a group that exists on the host for dnsmasq.

**Comment by ricab** [comment]
For the record, `libvirt-daemon` was not enough for me. The required package was actually `libvirt-daemon-system` (thanks @Saviq)

**Comment by townsend2010** [comment]
This goes away now that we are no longer including `libvirt` in the snap.
