### ISSUE TITLE
multipass connect/exec should allow using custom ssh keys

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#52]
As referenced in #51, the multipass 'connect' and 'exec' commands should support ssh keys passed in via a custom cloud-init config.

**Comment by Saviq** [comment]
Agreed, if we have access (e.g. `ssh` interface when we're confined) to the default ssh keys location (`~/.ssh/id_rsa.pub`) we can add that for the default user.

**Comment by townsend2010** [comment]
This is working now, so closing.
