### ISSUE TITLE
multipass errors are incorrectly reported as inability to connect to socket

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#527]
For example, trying to stop a deleted issue should report: 
`fmt::format_to(errors, "instance \"{}\" is deleted\n", name);` - see [here](https://github.com/CanonicalLtd/multipass/blob/master/src/daemon/daemon.cpp#L1505)

But instead:

```sh
$ multipass list
Name                    State             IPv4             Release
pliable-greyhound       DELETED           --               Not Available
$ multipass stop pliable-greyhound 
stop failed: cannot connect to the multipass socket                             
Please ensure multipassd is running and '/run/multipass_socket' is accessible
```

I suppose this was introduced with changes for #460.

**Comment by townsend2010** [comment]
Apparently, I messed up something with #513 :)
