### ISSUE TITLE
proxy setting for downloading images is missing

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#53]
It would be nice to have a parameter which allows to specify proxy for download. Or if multipass honored http(s)_proxy environment variables

**Comment by Saviq** [comment]
Note the daemon (`multipassd`) is a system service, so it should respect whatever is configured for that, and not what's set in your client's (`multipass`) environment?

**Comment by albaguirre** [comment]
@Saviq, yeah correct.

I think the cleanest way is to introduce a "snap set multipass proxy.{http,https}=...", mirroring how you configure the proxy for snapd.

**Comment by albaguirre** [comment]
@marosg42, 

with multipass revision 118 available in the edge channel, you can now do the following to configure the proxy:
    
   snap set multipass proxy.http=http://myproxy:7777
   snap restart multipass

**Comment by manuzhang** [comment]
Is there a way to set proxy on Mac ?

**Comment by Saviq** [comment]
@manuzhang if we're not respecting the system-wide proxy selection on macOS, please file a new issue.

We'll be adding a an option (#756) to set the proxies for Multipass itself.

**Comment by Airren** [comment]
worked with a proxy in Ubuntu 18.04
```sh
airren@NUC11:/etc/systemd/system/multi-user.target.wants$ ls -al |grep multipassd
lrwxrwxrwx  1 root root   53 9月   4 00:48 snap.multipass.multipassd.service -> /etc/systemd/system/snap.multipass.multipassd.service

## Set Proxy In [Service] Section
# Environment="HTTP_PROXY=$your_proxy "
# Environment="HTTPS_PROXY=$your_proxy "
# Environment="NO_PROXY=localhost,127.0.0.0/8,10.112.232.0/24"
airren@NUC11:/etc/systemd/system/multi-user.target.wants$ sudo vim /etc/systemd/system/snap.multipass.multipassd.service

# Restart the process
airren@NUC11:/etc/systemd/system/multi-user.target.wants$ sudo systemctl daemon-reload
airren@NUC11:/etc/systemd/system/multi-user.target.wants$ sudo systemctl restart snap.multipass.multipassd

# Check proxy is available
airren@NUC11:/etc/systemd/system/multi-user.target.wants$ sudo systemctl show --property Environment snap.multipass.multipassd
Environment=HTTP_PROXY=$your_proxy HTTPS_PROXY=$your_proxy NO_PROXY=localhost,127.0.0.0/8,10.112.232.0/24

# Work Normal 
airren@NUC11:/etc/systemd/system/multi-user.target.wants$ m launch -c 4 -m 6G
```

**Comment by Saviq** [comment]
> $ sudo vim /etc/systemd/system/snap.multipass.multipassd.service

This will get overwritten on snap refresh, you should use `sudo systemctl edit ...` instead.

**Comment by Airren** [comment]
> This will get overwritten on snap refresh, you should use `sudo systemctl edit ...` instead.

Thanks for you info.
