### ISSUE TITLE
[macos] orphan hyperkit processes remain

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#538]
My Mac install got in a weird state:
```
$ multipass start snapcraft-multipass
…
virtio_net: Could not create vmnet interface, permission denied or no entitlement?
```

**Comment by Saviq** [comment]
Hmm this might have been a problem with an earlier version I was trying out.

**Comment by Saviq** [comment]
Oh I just realized the original `hyperkit` process was still running, killing that got me back in working order.

Seems the underlying issue is that `multipassd` crashed without having killed the hyperkit process. I wonder if we can somehow have `launchd` ensure that child processes of `multipassd` go away?

**Comment by ricab** [comment]
Related to #708 (probably same cause).

**Comment by townsend2010** [comment]
We are deprecating Hyperkit, so closing this.
