### ISSUE TITLE
[macos] multipassd fails to realize `hyperkit` died

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#540]
Related to #538.

```
[2018-12-17T14:26:41.076] [info] [snapcraft-multipass] virtio_net: Could not create vmnet interface, permission denied or no entitlement?
[2018-12-17T14:26:41.078] [info] [snapcraft-multipass] process state changed to NotRunning
[2018-12-17T14:26:41.078] [info] [snapcraft-multipass] process finished with exit code 1
```

So hyperkit died, but:

```
$ multipass start snapcraft-multipass
…
launch failed: timed out waiting for instance to respond
$ multipass list                                               
Name                    State             IPv4             Release
snapcraft-multipass     UNKNOWN           --               Ubuntu Snapcraft builder for Core 16
```

We should notice that hyperkit died and put the instance in `BROKEN` state instead.

**Comment by gerboland** [comment]
To summarise:
- Broken if VM fails to even launch
- Unknown if VM appears to launch, but isn't connectable
Just want to get terminology clear.

**Comment by Saviq** [comment]
@gerboland now I think of it we never got BROKEN as a state, did we... This relates to bug #539 which meant when this happens I was unable to stop the instance as far as `multipass` is concerned to try and restart it.

**Comment by gerboland** [comment]
@Saviq right. I don't think it is a bad idea. I do suspect there'll be multiple ways a VM will fail, so putting them all under unknown isn't helping anyone.

**Comment by Saviq** [comment]
This is happening for qemu, too (e.g. #1358).

**Comment by townsend2010** [comment]
We are deprecating Hyperkit, so closing this.
