### ISSUE TITLE
failure to contact image providers causes multipassd to abort startup

### ISSUE THREAD

**Issue by cmars** [canonical/multipass#555]
Multipass has stopped working on my machine, a bionic host.

```
c@slate:~$ multipass version
multipass  2018.12.1-20-gf15e279
c@slate:~$ multipass list
list failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/run/multipass_socket' is accessible
c@slate:~$ sudo systemctl start snap.multipass.libvirt-bin.service 
c@slate:~$ ps -ef | grep multipass
c         6449  5557  0 22:14 pts/0    00:00:00 grep --color=auto multipass
c@slate:~$ multipass list
list failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/run/multipass_socket' is accessible
```

syslog doesn't show much:
```
Jan 03 22:15:47 slate sudo[6533]:        c : TTY=pts/0 ; PWD=/home/c ; USER=root ; COMMAND=/bin/systemctl start snap.multipass.libvirt-bin.service
Jan 03 22:15:47 slate sudo[6533]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan 03 22:15:47 slate systemd[1]: Started Service for snap application multipass.libvirt-bin.
-- Subject: Unit snap.multipass.libvirt-bin.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit snap.multipass.libvirt-bin.service has finished starting up.
-- 
-- The start-up result is RESULT.
Jan 03 22:15:47 slate sudo[6533]: pam_unix(sudo:session): session closed for user root
lines 1617-1671/1671 (END)
```

I've tried `sudo snap refresh` as well as apt updating.

**Comment by Saviq** [comment]
Hi @cmars sorry about this.

Can you show the output of `snap info multipass` please? The interesting lines are like so:

```
$ snap info multipass
…
services:
  multipass.libvirt-bin: simple, enabled, inactive
  multipass.multipassd:  simple, enabled, active
…
```

Also `sudo systemctl status snap.multipass.*` could shed some light, as would `journalctl -b0 -u snap.multipass.*`. You could use `snap logs multipass` for this as well, with some `-n` or `-f` flags as appropriate. `snap restart multipass` should take care of restarting the services as needed. What's in `snap get multipass` btw?

**Comment by ricab** [comment]
According to discussion elsewhere, the log said:

```
Jan 03 22:10:44 slate dnsmasq[2826]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
Jan 03 22:10:44 slate multipassd[2052]: "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/1"
Jan 03 22:10:44 slate multipassd[2052]: Host cdimage.ubuntu.com not found
```
Where the last message seems to be the relevant bit. The issue seemed to be resolved after a manual ping to `cdimage.ubuntu.com`.

Provabably related to #404.

**Comment by cmars** [comment]
```
c@slate:~/Projects$ snap info multipass
name:      multipass
summary:   Ubuntu at your fingertips
publisher: Canonical✓
license:   unset
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch` and it'll do all the setup
  for you. Check out `multipass find` for a list of available images. More details you can find
  under `multipass help`.
commands:
  - multipass
  - multipass.virsh
services:
  multipass.libvirt-bin: simple, enabled, inactive
  multipass.multipassd:  simple, enabled, inactive
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     edge
refresh-date: 18 days ago, at 18:19 CST
channels:                                      
  stable:    –                                 
  candidate: –                                 
  beta:      2018.12.1             (572) 111MB classic
  edge:      2018.12.1-20-gf15e279 (573) 111MB classic
installed:   2018.12.1-20-gf15e279 (573) 111MB classic
```

The journalctl command helped me get to the bottom of it (though I'm still puzzled):

```
c@slate:~/Projects$ journalctl -b0 -u snap.multipass.*
-- Logs begin at Sun 2018-03-18 19:00:42 CDT, end at Mon 2019-01-07 12:30:02 CST. --
Jan 03 22:10:41 slate systemd[1]: Started Service for snap application multipass.libvirt-bin.
Jan 03 22:10:41 slate systemd[1]: Started Service for snap application multipass.multipassd.
Jan 03 22:10:44 slate multipassd[2052]: Unable to determine subnet for the mpqemubr0 subnet
Jan 03 22:10:44 slate dnsmasq[2826]: started, version 2.75 cachesize 150
Jan 03 22:10:44 slate dnsmasq[2826]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Jan 03 22:10:44 slate dnsmasq-dhcp[2826]: DHCP, IP range 10.157.15.2 -- 10.157.15.254, lease time infinite
Jan 03 22:10:44 slate dnsmasq-dhcp[2826]: DHCP, sockets bound exclusively to interface mpqemubr0
Jan 03 22:10:44 slate dnsmasq[2826]: reading /etc/resolv.conf
Jan 03 22:10:44 slate dnsmasq[2826]: using nameserver 127.0.0.53#53
Jan 03 22:10:44 slate dnsmasq[2826]: read /etc/hosts - 58 addresses
Jan 03 22:10:44 slate dnsmasq[2826]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
Jan 03 22:10:44 slate multipassd[2052]: "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/1"
Jan 03 22:10:44 slate multipassd[2052]: Host cdimage.ubuntu.com not found
Jan 03 22:10:44 slate systemd[1]: snap.multipass.multipassd.service: Main process exited, code=exited, status=1/FAILURE
Jan 03 22:10:44 slate systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
Jan 03 22:10:45 slate systemd[1]: snap.multipass.multipassd.service: Service hold-off time over, scheduling restart.
Jan 03 22:10:45 slate systemd[1]: snap.multipass.multipassd.service: Scheduled restart job, restart counter is at 1.
Jan 03 22:10:45 slate systemd[1]: Stopped Service for snap application multipass.multipassd.
Jan 03 22:10:45 slate systemd[1]: Started Service for snap application multipass.multipassd.
```

I then tried pinging `cdimage.ubuntu.com` and it responded. Then I tried `multipass list` and it suddenly started working.

This seems similar to CanonicalLtd/multipass#404 / CanonicalLtd/multipass#316, however in this latest case, I had network connectivity, and dnsmasq was just failing to resolve cdimage.

Only thing noteworthy about my network setup, I have a rather large /etc/hosts file that resolves many advertising & tracker-related domains to localhost (cdimage.ubuntu.com isn't one of them though!). Cloudflare DNS (1.1.1.1) is my primary upstream DNS server, and I also regularly connect through various VPNs.
- I have lxd installed which runs its own dnsmasq, though it should

**Comment by ricab** [comment]
I managed to reproduce something similar to this, but with "connection refused" instead of "host not found", by adding the following to `/etc/hosts`:

```
127.0.0.1 cdimage.ubuntu.com
::1 cdimage.ubuntu.com
```

The issue comes up during configuration [here](https://github.com/CanonicalLtd/multipass/blob/f3ed010a15d55df26a07c684a13de0a1a6026537/src/daemon/custom_image_host.cpp#L87). I expect the same `runtime_error` is [thrown](https://github.com/CanonicalLtd/multipass/blob/f3ed010a15d55df26a07c684a13de0a1a6026537/src/network/url_downloader.cpp#L72) in the "not found" case, (with a different error message).

I succeeded in making the daemon ignore and move on with a try-catch surrounding 132-145 here: https://github.com/CanonicalLtd/multipass/blob/f3ed010a15d55df26a07c684a13de0a1a6026537/src/daemon/custom_image_host.cpp#L132 

I suppose the proper fix would involve throwing and catching a specialized exception instead. But *just ignoring* may not be the right thing to do. Perhaps the daemon should keep trying periodically in the background. Other network issues may also have to be bundled and treated the same way. To be continued...

**Comment by cmars** [comment]
https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing might be a useful model to start with, for how things can fail.

**Comment by cmars** [comment]
Another failure mode.. for some reason, cloud-images responds with a 500 error due to a proxy issue at the Cape Town sprint -- you'll see this if you're on Canonical wifi: https://pastebin.canonical.com/p/DwvP6gZCVh/

This also causes multipassd to fail to start:

```
Jan 14 09:42:52 slate multipassd[4073]: Error transferring http://cloud-images.ubuntu.com/minimal/releases/xenial/release/SHA256SUMS - server replied: Internal Server Error
Jan 14 09:42:52 slate systemd[1]: snap.multipass.multipassd.service: Main process exited, code=exited, status=1/FAILURE
Jan 14 09:42:52 slate systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
Jan 14 09:42:52 slate systemd[1]: snap.multipass.multipassd.service: Service hold-off time over, scheduling restart.
Jan 14 09:42:52 slate systemd[1]: snap.multipass.multipassd.service: Scheduled restart job, restart counter is at 5.
```
```

**Comment by ricab** [comment]
Thank you for reporting. That is indeed a different manifestation of the same general problem, which is that multipass does not properly handle communication failure with image providers. It would be covered by the approach [above](https://github.com/CanonicalLtd/multipass/issues/555#issuecomment-452372984).
