### ISSUE TITLE
Daemon hangs for 30s when suspending a suspended instance

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#559]
Perhaps a minor issue, but:

```
$ multipass suspend graceful-cobia
$ time multipass suspend graceful-cobia 
                                                                                
real    0m30.041s
user    0m0.024s
sys     0m0.016s
```

An attached gdb shows the following stack:

```
#0  0x00007f481c10874d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f481689538c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f481689549c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f481cf393ff in QEventDispatcherGlib::processEvents (this=0x272b010, flags=...)
    at kernel/qeventdispatcher_glib.cpp:422
#4  0x00007f481cee3c3a in QEventLoop::exec (this=0x7ffe4c63a9f0, flags=...)
    at kernel/qeventloop.cpp:214
#5  0x00000000009e638c in multipass::Daemon::suspend(grpc::ServerContext*, multipass::SuspendRequest const*, grpc::ServerWriter<multipass::SuspendReply>*) ()
[...]
```

The thread serving the request waits [here](https://github.com/CanonicalLtd/multipass/blob/f3ed010a15d55df26a07c684a13de0a1a6026537/src/daemon/daemon.cpp#L1574) until timeout. Ideally it would reply back ASAP after realizing the instance was already suspended.

**Comment by smokfyz** [comment]
Hey. Can I use this issue for the first contribution to the project?

**Comment by townsend2010** [comment]
Hey @smokfyz,

Unless @ricab has already started to fix it, then yes, by all means, go for it!

Good luck and let us know if you have any questions.

**Comment by ricab** [comment]
@smokfyz sure, go ahead! I haven't done anything on it yet, only reported.
