### ISSUE TITLE
`transfer` should accept `-` as arguments for stdin/out

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#578]
`multipass transfer - instance:file/path` would read the file contents from standard input.
`multipass transfer instance:file/path -` would write the file contents into standard output.

Destination has to be a file, so it isn't supported for more than one `<source>` when `-` is used anywhere.

**Comment by MaximDanilov** [comment]
Hello. I'm willing to help you with this issue.

**Comment by townsend2010** [comment]
Hi @MaximDanilov!

Yes, absolutely, if you'd like to contribute, we'd be happy to review it:)  Thanks!

**Comment by MaximDanilov** [comment]
Okey :-) I'll start working with the code soon.

**Comment by MaximDanilov** [comment]
Hi @townsend2010! What version of Qt are you using? I'm continue to receive errors like `‘ISODateWithMs’ is not a member of ‘Qt’

**Comment by townsend2010** [comment]
Hi @MaximDanilov,

I generally use 5.9.5, but that enum value was introduced in Qt 5.8.

**Comment by MaximDanilov** [comment]
@townsend2010. Yep, I just found this enum variable in qt archive. Thank you. I'll try to compile project tomorrow. One more question. I tried to install dependencies via `mk-build-deps -s sudo -i` (before have done all steps in instruction), but receive this error (
![default](https://user-images.githubusercontent.com/47329914/52441405-8833d180-2b31-11e9-87d4-6f6ddb346e93.png)). Is this okay?

**Comment by Saviq** [comment]
@MaximDanilov `cmake-extras` is a package in Ubuntu: https://packages.ubuntu.com/search?keywords=cmake-extras. But actually it's not needed after all. You can remove it from `debian/control` and we'll do the same.

**Comment by MaximDanilov** [comment]
Hello @townsend2010 @Saviq. I want to launch multipass instance but get this error:  
`launch failed: Cannot resize instance image`  
 What does this mean? Have done everything from instruction. Using Ubuntu on VM.

**Comment by townsend2010** [comment]
Hi @MaximDanilov,

So that error means that `qemu-img` is failing to resize the instance image to the default size of 5GB.  How much disk space do you have allocated to your Ubuntu VM and how much free space do you have?

**Comment by MaximDanilov** [comment]
@townsend2010 ,  
I used 13gb of 32gb on my VM. So now available disk space is about 18 gb.  
But i chose dynamic virtual disk before installing Ubuntu. Maybe that's a problem.

**Comment by MaximDanilov** [comment]
@townsend2010 ,  
I made new VM with ubuntu, but now choose fixed disk space size. Keep getting following error.
![image](https://user-images.githubusercontent.com/47329914/52749831-75bb0b80-2ffb-11e9-9b5a-666795881d8a.png)  
Tomorrow, I'll start to analyze code, but, if you have some thoughts about what goes wrong, would be glad to hear it.

**Comment by Saviq** [comment]
@MaximDanilov your Ubuntu installation is in a VM? That may not work at all with Multipass, depending on whether nested virtualization is possible.

The error you're getting, however, is misleading if that's the reason. If you run the command with `-vvv`, are there other errors? Can you look at the daemon logs (run `multipassd` with `--logger stderr --verbosity debug`?

**Comment by MaximDanilov** [comment]
@Saviq, ok then. I will try to do it after work and send logs to you. Thanks for reply :-)

**Comment by MaximDanilov** [comment]
hellman@hellman-VirtualBox:~/multipass/build/bin$ sudo ./multipassd --logger stderr --verbosity debug
[2019-02-15T07:50:53.747] [info] [daemon] Unable to determine subnet for the mpqemubr0 subnet
[2019-02-15T07:50:54.981] [info] [rpc] gRPC listening on unix:/run/multipass_socket, SSL:on  

So i try to run multipass with this `./multipass launch -vvv` and keeping get the same error. It seems to me, that it's already create smth, but just cant resize the image, because it doen't try to retrieve new one, like was in first launch.

**Comment by Saviq** [comment]
@MaximDanilov it caches the image, so until it's updated it won't download it again. It's possible that the image got corrupted and that's why it can't resize it. You can try launching a different image (`multipass launch xenial`) or clearing multipassd's state altogether:

```
sudo rm -rf ~/.cache/multipass* ~/.local/share/multipass*
```

**Comment by MaximDanilov** [comment]
Good evening. I tried multiple times to launch instance, but it was always the same. So i decide to install ubuntu on my external HDD. I hope this would work and I continue making the solution :-)

**Comment by ricab** [comment]
I had the same `Cannot resize instance image` problem on a new machine. It turned out I was missing qemu. Overcome with 

```
sudo apt install qemu qemu-kvm qemu-system-common qemu-system-x86 qemu-utils`
```

You would have to replace `x86` with whatever architecture you are on. I am not sure any beyond the "system" packages in that command are really necessary...

As pointed out above, the error should be more meaningful. The documentation should also mention runtime dependencies. Opening issues to track that.
