### ISSUE TITLE
[macos] Unable to determine IP address

### ISSUE THREAD

**Issue by Sylva1n** [canonical/multipass#587]
I have installed snapcraft on macOs. 
`brew install snapcraft`

Multipass is required. I have installed from the official .pkg.

When I launch snapcraft command, sometimes it works, sometimes it fails:

```
Unable to determine IP address

launch failed: timed out waiting for instance to respond                        
stop failed: libssh failed to set host option to '': 'Invalid argument in ssh_options_set'
stop failed: libssh failed to set host option to '': 'Invalid argument in ssh_options_set'
An error occurred when trying to stop the instance with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

At this  time, I didn't find where the logs are written for snapcraft.

```
multipass ls

Name                    State             IPv4             Release
snapcraft-test     UNKNOWN           --               Ubuntu Snapcraft builder for Core 18
```

```
multipass stop snapcraft-test
stop failed: libssh failed to set host option to '': 'Invalid argument in ssh_options_set'
```

```
multipass  delete snapcraft-test
multipass purge 
purge failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible
```

After that, I run again 

`snapcraft`

And it worked... to the next time...

**Comment by twpayne** [comment]
FWIW I had this exact same problem (macOS 10.14.4, MacBook Pro late 2013 model) and @Sylva1n's steps to work around it worked for me as well.

Thank you @Sylva1n for posting not just the problem, but also a solution :)

**Comment by sdeibel** [comment]
I've also seen this intermittently on macOS 10.13.6 with snapcraft 3.3 and 'snapcraft clean' seemed to clear it in the past.  But I now think it's not that simple, or there may be multiple causes of this problem.

I have found that 'snapcraft clean' doesn't always work and in that case using multipass as described above also does not help.  In such cases, 'multipass ls' hangs for a long time as well although eventually completes and I can delete and purge but it does not help and 'snapcraft' fails again in the same way.  

My general impression is multipass is just flaky.  I've also had cases where 'snapcraft' failed with this error and then I did nothing else other than re-run 'snapcraft' and it worked.

I have multipass version 0.6.1+mac although perhaps interestingly even 'multipass --version' hangs up after it prints the multipass version and before it prints the multipassd version.  So it seems like a multipassd issue but killing multipassd and letting it restart also doesn't seem to help.

At this point I seem to be completely out of luck; going to try rebooting entirely.

**Comment by wieczorek1990** [comment]
It worked for me after `snapcraft clean`.

**Comment by Saviq** [comment]
Seems you guys got this solved. Please report back if you still have problems.

**Comment by mirr254** [comment]
I have the same problem but with microk8s
