### ISSUE TITLE
Improve message when KVM is unavailable (conflict with VirtualBox)

### ISSUE THREAD

**Issue by popey** [canonical/multipass#6]
```
alan@hal:~$ multipass launch 
failed to launch: ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy       
failed to initialize KVM: Device or resource busy
```

This is because I have VirtualBox installed (and running) on this machine. I had to kill the VBox processes to allow multipass to run. Perhaps a nicer error message might be useful here?

**Comment by Saviq** [comment]
Catching this error message and clearly saying that the problem might be another hypervisor running would help a lot here.
