### ISSUE TITLE
[windows] Add option to turn off dynamic memory

### ISSUE THREAD

**Issue by chrisurwin** [canonical/multipass#604]
When using the windows release it automatically creates VM's in Hyper-V with dynamic memory, this can quickly lead to exhausting the host memory.

Would it be possible to have it so that it fixed the memory at the size that is specified in the launch command or have it as an option to set dynamic or static?

**Comment by Saviq** [comment]
Yes, we should certainly look into this.

**Comment by c-goes** [comment]
I think it's the best to make it the default to turn it off. The other supported VMM don't do this.

**Comment by tomaswarynyca** [comment]
News on the solution to this problem?

**Comment by mdrakiburrahman** [comment]
My Microk8s cluster - which runs multipass - would go into really weird states (Pods going into `unknown`) and get Blue screens continuously - I realized this was dye to Hyper-V Dynamic memory. Until Multipass bakes this in, the fix is:

```powershell
microk8s install "--cpu=8" "--mem=32" "--disk=25" "--channel=1.22/stable" -y

# Seems to work better for smaller VMs

# Launched: microk8s-vm
# 2022-03-05T23:05:51Z INFO Waiting for automatic snapd restart...
# ...

# Stop the VM
microk8s stop

# Turn off Dynamic Memory
Set-VMMemory -VMName 'microk8s-vm' -DynamicMemoryEnabled $false -Priority 100

# Start the VM
microk8s start
```

**Comment by jfmatth** [comment]
Would there be anyway of making this an option on launch?  I love Dynamic memory on my Hyper-v world, and now i have to turn off the VM, setup dynamic memory and then turn it back on :(

**Comment by georgeliao** [comment]
> Would there be anyway of making this an option on launch? I love Dynamic memory on my Hyper-v world, and now i have to turn off the VM, setup dynamic memory and then turn it back on :(

This definitely a good feature to have for Hyper-v backend. However, this is also a backend specific option in launch command, it does break the consistency the command has across multiple backends. So we do not think the benefits outweigh the additional complexity it brings in.

**Comment by jfmatth** [comment]
> This definitely a good feature to have for Hyper-v backend. However, this is also a backend specific option in launch command, it does break the consistency the command has across multiple backends. So we do not think the benefits outweigh the additional complexity it brings in.

Maybe make it a setting that you set, and then upon launch, it can read applicable settings for that hypervisor?

```
multipass set local.hyperv-dynamic=true
```
something like that?

Just seems a waste to not use a hypervisors features if we can, not to mention I think others will start doing similar options.

**Comment by georgeliao** [comment]
> multipass set local.hyperv-dynamic=true

This sounds good, it is definitely something we can try to develop in the future. Since this is a feature request, can you open a new feature request issue? We can talk more in details there. Thanks.
