### ISSUE TITLE
Error message misleading when qemu runtime dependency is not satisfied 

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#613]
As discussed in (unrelated) issue #578, trying to launch an instance with multipass when the qemu-system command is not available results in a misleading error message:

```
$ multipass launch -vvv b
launch failed: Cannot resize instance image
```

Highest verbosity logs were not useful either.

**Comment by townsend2010** [comment]
`qemu` will always be included in the snap package, so this really only potentially affects developers of Multipass who run it from a build

**Comment by ricab** [comment]
The error is less misleading now, but still misses the point:

```console
$ multipass launch
launch failed: failed to start qemu instance: execve: No such file or directory
```

The last part (starting with `execve`) is something qt adds in Unix processes. We should say what program the error occurred on.

**Comment by ricab** [comment]
With the PR above, we get:

```console
$ multipass launch
launch failed: failed to start qemu instance: program: qemu-system-x86_64; error: execve: No such file or directory
```
The colon excess is due to composing error messages. I'd prefer the message to omit `execve` entirely, and say `qemu-system-x86_64: No such file or directory`. But that would mean relying on a particular Qt implementation…
