### ISSUE TITLE
Feature request: A command to resize a vm

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#62]
I have an existing VM that's run out of space, it would be really nice if I could resize it. Or even better would be a VM with a dynamic size on disk.

**Comment by Saviq** [comment]
The problem with resizing is the filesystem needs to grow, which needs to happen within the instance.

We're increasing the default size from the cloud-image 2.1GB default to 5GB - fortunately that doesn't mean it takes 5GB of your space, as that is allocated dynamically.

We'll allow changing the default size, but I'm not sure yet we'll support resizing. Maybe we should be even more aggressive with the default, since it doesn't bear a cost to start with.

**Comment by townsend2010** [comment]
I'll just add that we already have the '--disk' option in launch for specifying the size of the virtual disk when launching a new instance.

But yeah, increasing the virtual disk size after launch will still either require a user to resize the partition inside the VM or multipass would need some magic to do it automatically, but we would need to take great care in such a case.

**Comment by Saviq** [comment]
We'll close this on the basis that repartitioning and growing the filesystem is beyond the scope of Multipass. We'll increase the size of the default disk, though.

**Comment by okneloper** [comment]
Guys, this is a HUGE issue! If resizing the disk is not an option the user should be made aware before the VM is even created, not after he has run out of space.... this is so frustrating! After spending all this time to configure the VM I run out of disk space and find out the only option is ditch the while thing...

The disk space should be made a required setting and there should be a warning that on will have to start over if he runs out of disk space.

**Comment by townsend2010** [comment]
@okneloper,

I'm not sure which host OS you are using, but I have found that it is possible to resize an instance's virtual disk via `qemu-img` and on next boot, `cloud-init` will automatically grow the partition.  If you are not sure where the instance's virtual disk resides, please let us know which host OS you are using and we can help you out.

**Comment by okneloper** [comment]
@townsend2010 thanks, I am on windows and was about to try the `Resize-VHD` solution from #29, but if you recommend `qemu-img` I'll go with that. 

An advice on the disk location would be very helpful as it seems to be classified information.

**Comment by townsend2010** [comment]
Hi @okneloper,

Sure, `Resize-VHD` is the way to do it on Windows.  You can also use Hyper-V Manager, right click on the instance you are interested in, select `Settings...`, then select the `Hard Drive` under `IDE Controller 0`.  From there, you can see the path to the virtual disk.  You can also click `Edit` under the `Virtual hard disk` and that will bring up the `Edit Virtual Hard Disk Wizard`.  Click `Next` from here and you will be presented with several different options.  Choose `Expand` -> `Next` and then fill out whatever size you want to make the disk.  Click `Next`, review the change, and then click `Finish`.

Then start the instance via Multipass and when you log in, the partition will be fully expanded.  Hope this helps!

**Comment by okneloper** [comment]
Thanks. I've tried `qemu-img` before you posted the above, and it said the disk format doesn't support resizing. 

Using Hyper-V seems to have done the trick! I'll continue using the VM and report if there are any issues.

**Comment by Saviq** [comment]
I'll actually reopen this, as resizing the block device seems to be enough for at least a good subset of the images we allow running.

**Comment by erny** [comment]
On OS X (High Sierra) I tried to resize image with qemu-img (5.1.0) without luck. qemu-img info seems to give the right info, but qemu-img check returns a lot of errors, and trying to fix them and then resize, gives an unusable image.

I found [this gist](https://gist.github.com/stefanfoulis/5bd226b25fa0d4baedc4803fc002829e), so I tried with `/Applications/Docker.app/Contents/MacOS/qcow-tool` because I have Docker Desktop installed too:

        /Applications/Docker.app/Contents/MacOS/qcow-tool resize --size=$(( 15 * 1024**3 )) ubuntu-20.04-server-cloudimg-amd64.img

and that seemed to work, `df -h` returns the new disk size (without any file system resizing).

**Comment by winkeesail** [comment]
I need this feature very badly because I run into a situation that my VM is using up the initial space after I have spent so much time setting up a dev environment in the VM and to ditch the whole thing is a big pain.

**Comment by Saviq** [comment]
@winkeesail you commented on two issues, both of which had explanations on how to achieve this in the comments…

**Comment by winkeesail** [comment]
> @winkeesail you commented on two issues, both of which had explanations on how to achieve this in the comments…

Are you saying that I should use `qcow-tool resize` to do the trick? I will try it.

**Comment by winkeesail** [comment]
these tricks make no sense to me, qcow-tool resize does not affect the image size.

**Comment by Saviq** [comment]
> these tricks make little sense to me, because qcow-tool resize does not affect the image size.

You mean the image file size? It won't. The image files will only grow with use.

**Comment by winkeesail** [comment]
> > these tricks make little sense to me, because qcow-tool resize does not affect the image size.
> 
> You mean the image file size? It won't. The image files will only grow with use.

Unfortunately, this is not the case on my machine. I use `qcow-tool resize --size=$((1024*1024*1280) ubuntu-20.04-server-cloudimg-amd64.img` to increase my image from 10G to 12G. After I execute the command, the image size does not change at all, and I login into the VM instance, trying to do things, and it still keeping warning me that **No space left on device**. Clearly, the VM size has not changed.

**Comment by Saviq** [comment]
> Unfortunately, this is not the case on my machine. I use `qcow-tool resize --size=$((1024*1024*1280) ubuntu-20.04-server-cloudimg-amd64.img` to increase my image from 10G to 12G. After I execute the command, the image size does not change at all, and I login into the VM instance, trying to do things, and it still keeping warning me that **No space left on device**. Clearly, the VM size has not changed.

I'm assuming the missing `)` is a typo here on GitHub. However, the size you gave above was 1280MB, not 12GB (which would be `$(( 12 * 1024 * 1024 * 1024 ))`:

```bash
$ multipass launch                        
Launched: suited-emu                                                            
$ multipass info suited-emu | grep Disk
Disk usage:     1.2G out of 4.7G
$ multipass stop suited-emu
Stopping suited-emu -
$ sudo /Applications/Docker.app/Contents/MacOS/qcow-tool resize --size=$(( 12 * 1024 * 1024 * 1024 )) "/var/root/Library/Application Support/multipassd/vault/instances/suited-emu/ubuntu-20.04-server-cloudimg-amd64.img"
qcow-tool: [INFO] Resized file to 22880 clusters (2928640 sectors)
qcow-tool: [INFO] image has 0 free sectors and 22876 used sectors
$ multipass start suited-emu
$ multipass info suited-emu | grep Disk
Disk usage:     1.2G out of 11.5G
```

**Comment by winkeesail** [comment]
Thanks, this is helpful, I typed the wrong size. Fortunately, a smaller size has no harm to my image.

**Comment by xinster** [comment]
I ran into the virtual disk size issue today. the default size is up to 5GB but my project requires more. it stopped during the compile :  No space left on device (os error 28). How can I resize the VM disk or how can I set up a larger disk size during the installation?

**Comment by countingpine** [comment]
Right now, the question of resizing the base disk seems to have an answer of "it depends...", and involves finding the location of the disk image, knowing which tool to use, and how to use it.  And I (myself) am not clear if the correct tool can even be assumed to be present at the moment, or if I have to go away and install something else.

But at least once the base disk is resized, growing the partition inside it is at least a procedure that should work the same independently of the host platform.

I think it would be great if multipass were able to do the most complicated/platform dependent step for me, and let me worry about growing partitions/filesystems in the guest.

**Comment by Saviq** [comment]
@countingpine that's exactly what this feature request is about, and we will make it happen, for sure.

**Comment by Darival** [comment]
Hi everyone,
I just wanted to add something, *IF** you are using VirtualBox driver you can simply use the _virtual media manager_ to resize it.   
[here](https://www.howtogeek.com/124622/how-to-enlarge-a-virtual-machines-disk-in-virtualbox-or-vmware/#:~:text=VirtualBox%206%20added%20a%20graphical,in%20the%20main%20VirtualBox%20window.&text=Select%20a%20virtual%20hard%20disk,%E2%80%9D%20when%20you're%20done.) are the steps.

**Comment by fsevenm** [comment]
I found it hard to install qcow-tool, so I used qemu-img (Idk it's already installed on my Ubuntu).
`sudo qemu-img resize --preallocation='full' ubuntu-20.04-server-cloudimg-amd64.img +5G`  will add 5 GB to the specified image file.

**Comment by karuppiah7890** [comment]
https://github.com/canonical/multipass/issues/62#issuecomment-729650082 just worked for me! Thanks @Saviq

**Comment by nicoster** [comment]
since Docker Desktop isn't free anymore, I have to install `qemu` to make the tool `qemu-img` available. On macOS, installing qemu spends quite some time on the dependencies. As I don't really use qemu, I ignore the dependencies:

`brew install --ignore-dependencies qemu`

and the following command does the trick to resize:

`sudo qemu-img resize /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/docker/ubuntu-20.04-server-cloudimg-arm64.img 40G`

If there's no legal issue, maybe we should ship the `qemu-img` with Multipass?

**Comment by Saviq** [comment]
> If there's no legal issue, maybe we should ship the `qemu-img` with Multipass?

It's there, in `/Library/Application\ Support/com.canonical.multipass/bin`. Note, there's also a `-hyperkit` version that should be used if using the `hyperkit` driver (the default on x86).

**Comment by infinitepr0** [comment]
Can you please guide me on the steps to resize the `primary` machine on MacOS (M1, Monterey 12.0.1)?

```
# Steps followed to create the instance
brew install multipass
multipass init
multipass launch
```

**Comment by Saviq** [comment]
@infinitepr0 see the comments further up, it's described there. Doesn't matter if it's M1 or not.

**Comment by infinitepr0** [comment]
> since Docker Desktop isn't free anymore, I have to install `qemu` to make the tool `qemu-img` available. On macOS, installing qemu spends quite some time on the dependencies. As I don't really use qemu, I ignore the dependencies:
> 
> `brew install --ignore-dependencies qemu`
> 
> and the following command does the trick to resize:
> 
> `sudo qemu-img resize /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/docker/ubuntu-20.04-server-cloudimg-arm64.img 40G`
> 
> If there's no legal issue, maybe we should ship the `qemu-img` with Multipass?

That folder doesn't exist on my device.

**Comment by Saviq** [comment]
@infinitepr0 drop `/qemu` from that path, and amend for instance name and Ubuntu version etc.

Here's an example file hierarchy for hyperkit:

```plain
$ sudo tree '/var/root/Library/Application Support/multipassd'
/var/root/Library/Application\ Support/multipassd
|-- certificates
|   |-- localhost.pem
|   `-- localhost_key.pem
|-- multipass-unique-id
|-- multipassd-send-metrics.yaml
|-- multipassd-vm-instances.json
|-- saved_metrics.json
|-- ssh-keys
|   `-- id_rsa
`-- vault
    |-- instances
    |   `-- primary
    |       |-- cloud-init-config.iso
    |       |-- pty
    |       |-- ubuntu-20.04-server-cloudimg-amd64-initrd-generic
    |       |-- ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
    |       `-- ubuntu-20.04-server-cloudimg-amd64.img
    `-- multipassd-instance-image-records.json

5 directories, 13 files
```

**Comment by Bresenham** [comment]
> since Docker Desktop isn't free anymore, I have to install `qemu` to make the tool `qemu-img` available. On macOS, installing qemu spends quite some time on the dependencies. As I don't really use qemu, I ignore the dependencies:
> 
> `brew install --ignore-dependencies qemu`
> 
> and the following command does the trick to resize:
> 
> `sudo qemu-img resize /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/docker/ubuntu-20.04-server-cloudimg-arm64.img 40G`
> 
> If there's no legal issue, maybe we should ship the `qemu-img` with Multipass?

I actually had to install the complete `qemu`package because otherwise I would get `Library not loaded: /opt/homebrew/opt/glib/lib/libglib-2.0.0.dylib`

**Comment by freewizard** [comment]
> > If there's no legal issue, maybe we should ship the `qemu-img` with Multipass?
> 
> It's there, in `/Library/Application\ Support/com.canonical.multipass/bin`. Note, there's also a `-hyperkit` version that should be used if using the `hyperkit` driver (the default on x86).

Thanks, this is helpful!

Also in case it happens to anyone, my disk image corrupts when it's full, so I had to repair before resize it:

`sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img  check -r all /var/root/Library/Application\ Support/multipassd/vault/instances/name/ubuntu-20.04-server-cloudimg-amd64.img`

**Comment by jstanley0** [comment]
`qemu-img resize` complained the image was corrupt.

`qemu-img check -r all` found some errors and claimed to have repaired them.

nevertheless, the VM will not start.

`Instance stopped while starting`

the logs show

[2022-02-15T07:24:03.116] [info] [primary] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None

```
[2022-02-15T07:24:03.117] [error] [primary] hyperkit: [ERROR] Mirage block device raised exception: (Failure "Read a header_length of 112 but we computed 104")
[2022-02-15T07:24:03.117] [error] [primary] Mirage-block error: Block device is disconnected
[2022-02-15T07:24:03.117] [error] [primary] Could not open mirage-block device: Invalid argument
[2022-02-15T07:24:03.117] [error] [primary] Could not open backing file: Invalid argument
[2022-02-15T07:24:03.118] [info] [primary] process state changed to NotRunning
[2022-02-15T07:24:03.118] [info] [primary] process finished with exit code 1
```

**Comment by townsend2010** [comment]
Hey @jstanley0,

Are you using `qemu-img` that is included in Multipass or a different version like installed via brew?  The version with Multipass should work with resizing qcow2 images intended to be used with Hyperkit, but `qemu-img` from brew will exhibit this behavior.

**Comment by townsend2010** [comment]
Hey @jstanley0,

I was just reminded that `qemu-img` has been renamed in the Multipass to `qemu-img-hyperkit`.  The full path to it is `/Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit`.

Also of note, we are currently working on a solution to modify instances including virtual disk size and that should be available soon-ish.

**Comment by lucasnetau** [comment]
> `qemu-img resize` complained the image was corrupt.
> 
> `qemu-img check -r all` found some errors and claimed to have repaired them.
> 
> nevertheless, the VM will not start.
> 
> `Instance stopped while starting`
> 
> the logs show
> 
> ```
> [2022-02-15T07:24:03.116] [info] [primary] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None
> [2022-02-15T07:24:03.117] [error] [primary] hyperkit: [ERROR] Mirage block device raised exception: (Failure "Read a header_length of 112 but we computed 104")
> [2022-02-15T07:24:03.117] [error] [primary] Mirage-block error: Block device is disconnected
> [2022-02-15T07:24:03.117] [error] [primary] Could not open mirage-block device: Invalid argument
> [2022-02-15T07:24:03.117] [error] [primary] Could not open backing file: Invalid argument
> [2022-02-15T07:24:03.118] [info] [primary] process state changed to NotRunning
> [2022-02-15T07:24:03.118] [info] [primary] process finished with exit code 1
> ```

I found that the Failure "Read a header_length of 112 but we computed 104" error occurs when the qcow2 image has been created with lazy refcounts: false. It appears that Multipass creates the images with lazy refcounts: true, which while faster does mean more chances of corruption with power loss.

Using qemu-img-hyperkit and copying the image via create with option `-o lazy_refcounts=on` fixed the header size for me and my instance was bootable again.

**Comment by tkongithub** [comment]
> Hi everyone,
> I just wanted to add something, **IF** you are using VirtualBox driver you can simply use the _virtual media manager_ to resize it.
> [here](https://www.howtogeek.com/124622/how-to-enlarge-a-virtual-machines-disk-in-virtualbox-or-vmware/#:~:text=VirtualBox%206%20added%20a%20graphical,in%20the%20main%20VirtualBox%20window.&text=Select%20a%20virtual%20hard%20disk,%E2%80%9D%20when%20you're%20done.) are the steps.

The following update from 5G to 40G worked for me on Mac OS X using virtualbox
```
sudo multipass set local.driver=virtualbox
multipass launch --name focal
multipass exec focal bash
df -H |grep 'sda1 '
  /dev/sda1       5.1G  1.5G  3.6G  29% /
exit
multipass stop focal
sudo VBoxManage modifyhd "/var/root/Library/Application Support/multipassd/virtualbox/vault/instances/focal/ubuntu-20.04-server-cloudimg-amd64.vdi"  --resize 41960
multipass start focal
multipass exec focal bash
df -H |grep 'sda1 '
  /dev/sda1       43G  2.3G   41G   6% /
exit
```

**Comment by MaKiPL** [comment]
OSX M1 ARM tested and working with full QCOW2 image:

```sh
sudo su -
mkdir a
cp /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/primary/* ./a/
exit
sudo qemu-img resize ubuntu-20.04-server-cloudimg-arm64.img +20G
sudo su -
cp ./a/* /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/primary/
exit
multipass start primary
multipass shell
```

voila!

then if needed when full disk was during install:

```sh
sudo apt update
sudo dpkg --configure -a
sudo apt --fix-broken install
```

**Comment by nana-marinbio** [comment]
Hey @jstanley0 
> 
> Are you using `qemu-img` that is included in Multipass or a different version like installed via brew? The version with Multipass should work with resizing qcow2 images intended to be used with Hyperkit, but `qemu-img` from brew will exhibit this behavior.

Hi @townsend2010 

I tried `qemu-img resize` with `qemu-img`  included in Multipass (macos host).
I got the following error message:
           
`qcow2: Marking image as corrupt: Preventing invalid write on metadata (overlaps with qcow2_header); further corruption events will be suppressed `
`qemu-img: Error resizing image: Input/output error`


I checked the instance and it is okay, but could not resize.

Can I copy its configuration and content in a new instance that I launch with expanded size???
I've almost a whole week job done... we should get advice on this issue on installation and launching.

tks

**Comment by townsend2010** [comment]
Hi @nana-marinbio,

Was your instance stopped before trying the resize?  Also, could you please give me the exact command you tried when resizing the image?

> Can I copy its configuration and content in a new instance that I launch with expanded size???

No, that's not really possible.

**Comment by townsend2010** [comment]
Also @nana-marinbio,

Are you on M1 Mac or using Intel Mac?  Could you also please post the output of `sudo multipass get local.driver`?

**Comment by nana-marinbio** [comment]
> Hi @nana-marinbio,
> 
> Was your instance stopped before trying the resize? Also, could you please give me the exact command you tried when resizing the image?
> 
> > Can I copy its configuration and content in a new instance that I launch with expanded size???
> 
> No, that's not really possible.

HI @townsend2010 
Yes, I stopped the instance before the trial.

The full command follows:

`sudo qemu-img resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`

**Comment by townsend2010** [comment]
@nana-marinbio,

Ok, you've used the [wrong](https://github.com/canonical/multipass/issues/62#issuecomment-1040448379) `qemu-img` for use with HyperKit VM's.  Please try the following:

` sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`

Thanks!

**Comment by nana-marinbio** [comment]
> `sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`

@townsend2010 

Just tried and the result was:
`sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`

`sudo: /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit: command not found`

**Comment by townsend2010** [comment]
@nana-marinbio,

What version of Multipass do you have installed?  If it's a version older than 1.8, then use this command instead:

`sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`

Thanks!

**Comment by nana-marinbio** [comment]
@townsend2010 
> sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G

`qemu-img: Could not open '/var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img': qcow2: Image is corrupt; cannot be opened read/write`

**Comment by townsend2010** [comment]
@nana-marinbio,

Hmm, ok, so what I would do is make a copy of that image and then do:
`sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img check -r /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img`

If that seems to run successfully, try to resize the image again and see if it works.  If this is not successful, then I think we've hit a roadblock and there isn't much else that can be done unfortunately.

**Comment by nana-marinbio** [comment]
> @nana-marinbio,
> 
> Hmm, ok, so what I would do is **make a copy** of that image and then do: `sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img check -r /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img`
> 
> If that seems to run successfully, try to resize the image again and see if it works. If this is not successful, then I think we've hit a roadblock and there isn't much else that can be done unfortunately.

you mean `ctrl-c` of ubuntu-18.04-server-cloudimg-amd64.img?

**Comment by townsend2010** [comment]
I mean stop the instance if it's running, then make a copy of the image, something like:
`sudo cp /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img.orig`

This way, if the check to try to fix the issue in the image makes it worse, you can at least copy back the original image and run the instance.

Then run the `check -r` I posted [above](https://github.com/canonical/multipass/issues/62#issuecomment-1093195029).  If that commands succeeds, then try the `resize` command I posted [here](https://github.com/canonical/multipass/issues/62#issuecomment-1093170620).

**Comment by nana-marinbio** [comment]
> sudo cp /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img.orig

@townsend2010 
sorry, obviously i could not ctrl-c, it should be sudo cp.
I checked the copy with `tree` and it is there.

I tried the `check -r`:
`qemu-img: Unknown option value for -r (expecting 'leaks' or 'all'): /var/root/Library/Application Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img
Try 'qemu-img --help' for more information`

I asked help and for check  I got:
`check [-q] [--object objectdef] [--image-opts] [-f fmt] [--output=ofmt] [-r [leaks | all]] [-T src_cache] filename`

**Comment by townsend2010** [comment]
Sorry, I forgot the `all` for the `-r` option.  So it should be:
`sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img check -r all /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img`

**Comment by nana-marinbio** [comment]
> Sorry, I forgot the `all` for the `-r` option. So it should be: `sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img check -r all /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img`

@townsend2010 

`check -r`
`The following inconsistencies were found and repaired:
0 leaked clusters
 79011 corruptions
Double checking the fixed image now...
No errors were found on the image.
78998/81920 = 96.43% allocated, 2.15% fragmented, 0.00% compressed clusters
Image end offset: 5178392576`

`resize`
`Image resized.`

I started image and used shell:

` System information disabled due to load higher than 1.0`

How can I check size?

**Comment by townsend2010** [comment]
You can do `df -BG /` while shelled into the instance or do:
`$ multipass exec ubuntu18 -- df -BG /`

You should hopefully see under the `1G-blocks` header the new size of the virtual disk.

**Comment by townsend2010** [comment]
@nana-marinbio,

Also, if this did indeed work, you can delete that copy of the image you made in order to save disk space on your Mac.

**Comment by nana-marinbio** [comment]
> You can do `df -BG /` while shelled into the instance or do: `$ multipass exec ubuntu18 -- df -BG /`
> 
> You should hopefully see under the `1G-blocks` header the new size of the virtual disk.

@townsend2010 

 `iMac-de-Ana:bin AnaPaula$ multipass info ubuntu18`

`**Disk usage:     4.4G out of 38.6G**`

IT WORKED, tks for your patience,
sending a bear hug!

**Comment by townsend2010** [comment]
@nana-marinbio,

Hooray!!!! :tada:

**Comment by Saviq** [comment]
Anyone stumbling here, you can now try the implementation in action in #2353, with snaps under `edge/pr2353` channel and [Windows](https://github.com/canonical/multipass/pull/2353/checks?check_run_id=5887563474) and [macOS](https://github.com/canonical/multipass/pull/2353/checks?check_run_id=5887568801) packages.

**Comment by linhmtran168** [comment]
> `qemu-img resize` complained the image was corrupt.
> 
> `qemu-img check -r all` found some errors and claimed to have repaired them.
> 
> nevertheless, the VM will not start.
> 
> `Instance stopped while starting`
> 
> the logs show
> 
> ```
> [2022-02-15T07:24:03.116] [info] [primary] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None
> [2022-02-15T07:24:03.117] [error] [primary] hyperkit: [ERROR] Mirage block device raised exception: (Failure "Read a header_length of 112 but we computed 104")
> [2022-02-15T07:24:03.117] [error] [primary] Mirage-block error: Block device is disconnected
> [2022-02-15T07:24:03.117] [error] [primary] Could not open mirage-block device: Invalid argument
> [2022-02-15T07:24:03.117] [error] [primary] Could not open backing file: Invalid argument
> [2022-02-15T07:24:03.118] [info] [primary] process state changed to NotRunning
> [2022-02-15T07:24:03.118] [info] [primary] process finished with exit code 1
> ```

I had the same problem as @jstanley0 and thanks to @lucasnetau's [comment](https://github.com/canonical/multipass/issues/62#issuecomment-1070788958), I was able to create a new image from the old image and booted the instance successfully again:
```
$ sudo su
$ cd /var/root/Library/Application\ Support/multipassd/vault/instances/docker-vm/
$ /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit convert -p -O qcow2 -o lazy_refcounts=on ubuntu-20.04-server-cloudimg-amd64.img new_image.img
$ mv ubuntu-20.04-server-cloudimg-amd64.img backup.img
$ mv new_image.img ubuntu-20.04-server-cloudimg-amd64.img
```

**Comment by furkan-guvenc** [comment]
> ```shell
> sudo apt --fix-broken install
> ```

Not worked, also path is wrong in the script:
`sudo qemu-img resize ubuntu-20.04-server-cloudimg-arm64.img +20G`
need to be:
`sudo qemu-img resize /var/root/a/ubuntu-20.04-server-cloudimg-arm64.img +20G`

**Comment by Kalaikkovan** [comment]
> @nana-marinbio,
> 
> Ok, you've used the [wrong](https://github.com/canonical/multipass/issues/62#issuecomment-1040448379) `qemu-img` for use with HyperKit VM's. Please try the following:
> 
> ` sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`
> 
> Thanks!

This is perfect , worked for me. Thanks @nana-marinbio @townsend2010

**Comment by rewgs** [comment]
> > @nana-marinbio,
> > Ok, you've used the [wrong](https://github.com/canonical/multipass/issues/62#issuecomment-1040448379) `qemu-img` for use with HyperKit VM's. Please try the following:
> > ` sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img-hyperkit resize /var/root/Library/Application\ Support/multipassd/vault/instances/ubuntu18/ubuntu-18.04-server-cloudimg-amd64.img 40G`
> > Thanks!
> 
> This is perfect , worked for me. Thanks @nana-marinbio @townsend2010

I had to amend this slightly, to
`sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-img resize /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/ubuntu/ubuntu-20.04-server-cloudimg-arm64.img 32G`

(Though of course change 32G to whatever size you want).

**Comment by daviewales** [comment]
> Hi @okneloper,
> 
> Sure, `Resize-VHD` is the way to do it on Windows. You can also use Hyper-V Manager, right click on the instance you are interested in, select `Settings...`, then select the `Hard Drive` under `IDE Controller 0`. From there, you can see the path to the virtual disk. You can also click `Edit` under the `Virtual hard disk` and that will bring up the `Edit Virtual Hard Disk Wizard`. Click `Next` from here and you will be presented with several different options. Choose `Expand` -> `Next` and then fill out whatever size you want to make the disk. Click `Next`, review the change, and then click `Finish`.
> 
> Then start the instance via Multipass and when you log in, the partition will be fully expanded. Hope this helps!

I tried both this method and the Resize-VHD method, but I'm not getting any additional space. I tried this command:

```
Resize-VHD -Path C:\ProgramData\Multipass\data\vault\instances\primary\ubuntu-20.04-server-cloudimg-amd64.vhdx -SizeBytes 10GB
```

But still getting: `Disk usage: 4.7G out of 4.7G` from `multipass info`. And similar from `df -h`.

**Comment by androidseb** [comment]
This is not a solution to resizing the disk, but a workaround that I found worked for me to solve the problem of running out of disk space: just extract the folders containing too much data into your physical computer and mount them into the VM.

For example let's say you have a folder taking too much space in your VM's home under `/home/ubuntu/.gradle`.

Do this from inside the VM:
```bash
cd /home/ubuntu
mv .gradle .gradle.old
```

Then do this from your physical computer:
```bash
# Replace "multipass_vm_storage" with whatever folder you decided to store your VM files in
cd ~/multipass_vm_storage
mkdir .gradle
# Replace "primary" with whatever name your VM has
# You can list VMs with the `multipass list` command
multipass mount .gradle primary:/home/ubuntu/.gradle
```

Then do this from your VM:
```bash
cd /home/ubuntu
# Moving all files from the VM-hosted folder to the mounted physical-computer-hosted folder
mv .gradle.old/* .gradle/
# Optionally delete the old empty gradle folder
rm -rf .gradle
```

I hope this helps!

**Comment by sbs2001** [comment]
I think this was added in recent release of multipass. I'm able to do:
```
multipass stop primary
multipass set local.primary.disk=30G
multipass start primary
```

Much cleaner.

**Comment by theonewolf** [comment]
@townsend2010 I fond the `qemu-img-hyperkit` tool thanks to your comment and successfully resized my VM!

Then I saw you guys have added this as a feature and there is nice documentation which @weisdd linked.

Honestly, this is one of the nicest cross-platform VM management tools I've seen!  Really smooth on Mac, and I love that I can go to other OS and have a uniform(ish) experience.

**Comment by hamdisha** [comment]
> I think this was added in recent release of multipass. I'm able to do:
> 
> ```
> multipass stop primary
> multipass set local.primary.disk=30G
> multipass start primary
> ```
> 
> Much cleaner.

thanks, worked for me on Windows 💯

**Comment by itsazzad** [comment]
` multipass info` is  showing the old `Disk usage`

**Comment by junosuarez** [comment]
>  multipass info is showing the old size in Disk usage

After expanding the disk, you need to expand the partition and extend the filesystem from within the vm, eg with https://manpages.ubuntu.com/manpages/xenial/en/man1/growpart.1.html

**Comment by boukandouramhamed** [comment]
If your vm disk is at 100% the changes won't take effect. Try to free some space first and rerun the commands. 
> I think this was added in recent release of multipass. I'm able to do:
> 
> ```
> multipass stop primary
> multipass set local.primary.disk=30G
> multipass start primary
> ```
> 
> Much cleaner.

**Comment by kangarooo** [comment]
> I think this was added in recent release of multipass. I'm able to do:
> 
> ```
> multipass stop primary
> multipass set local.primary.disk=30G
> multipass start primary
> ```
> 
> Much cleaner.

In where do i write that on windows 10/11?

**Comment by ricab** [comment]
@kangarooo On either Powershell or Command Prompt (CMD).
