### ISSUE TITLE
uninstall on mac - not executable and ends with some errors

### ISSUE THREAD

**Issue by carmine** [canonical/multipass#620]
A few suggestions:

1) might be helpful for people to know how to uninstall (couldn't find in docs)
2) the uninstall script on mac isn't executable (have to chmod it).
3) when executed, it generates some errors.

Regarding user experience, I'd expect questions:
i) if VMs are running, whether to stop them

Finally, multipass assets are in a few places, like bash completion. That may or may not be important to delete.

**Comment by drujensen** [comment]
Where is the uninstall script at?

**Comment by Saviq** [comment]
We kept it not-executable a bit on purpose, so we'd recommend:

```
sudo sh /Library/Application Support/com.canonical.multipass/uninstall.sh
```

But I suppose it's interactive enough that we could just make it executable.

**Comment by matti** [comment]
needs quotes:

```
sudo chmod 755 "/Library/Application Support/com.canonical.multipass/uninstall.sh"
sudo "/Library/Application Support/com.canonical.multipass/uninstall.sh"
```

**Comment by LeDominik** [comment]
I think all that's needed is highlight @Saviq s command somewhere in the docs, I just checked there's no entry for uninstall. CLI is totally fine given the target audience

**Comment by Saviq** [comment]
Actually it's here: https://multipass.run/docs/installing-on-macos - but it could probably use an emphasis indeed…

**Comment by LeDominik** [comment]
@Saviq wow, I'm impressed - it's really there. I scrolled over that page like 3x before making my note here...

**Comment by Saviq** [comment]
Hidden it well, eh? ;P

**Comment by townsend2010** [comment]
Since this is documented and no complaints in over 3 years, I think it's safe to close this.

**Comment by shqear93** [comment]
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/073e31ba-36e9-4180-a322-da8edb840adc">

Me too :p, this does not indicate a dropdown, kinda hidden for me either 🥲
