### ISSUE TITLE
Add static sshfs binary

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#627]
To avoid issues with installing sshfs on instances that lack it, we can ship our own static version of it into the instance.

**Comment by townsend2010** [comment]
After some initial investigation, it looks like all we need is to do is clone https://github.com/libfuse/libfuse.git and https://github.com/libfuse/sshfs.git and use `meson`/`ninja` on Linux to build it.

A high level overview on how to build it is this.
* Build `libfuse` first
  * $ `mkdir build`
  * $ `cd build`
  * $ `meson ..`
  * $ `ninja`
* Then build `sshfs`
  * `PKG_CONFIG_PATH=/path/to/libfuse/build/meson-private meson ..`
  * meson configure -Dc_args=-I/path/to/libfuse/include -Dc_link_args=-L/path/to/libfuse/build/lib`
  * `meson ..`
  * `ninja`

My next steps are to make sure that actually works on different versions of Ubuntu including Core along with Fedora, Debian, etc.  Once I confirm that, then come up with a programmatic way to do this and include it in the various packages and modify `multipassd` to call our static verison.

**Comment by townsend2010** [comment]
I've now tested the static `libfuse3`/`sshfs` solution on a few different distros such as Core, Trusty, and Fedora and using a "hacked" `multipassd` to call these static versions when doing a mount and it works in all cases.

Now, we need to make some decisions on how we want to deploy this.
* How and where do we want to build these using the instructions above?  We should build them using some infrastructure we have access to.
* How do the various package types "pull in" the built binaries and include them in the package?
* Where in the instance do these binaries get "injected" at launch?  We need to be mindful of "read-only" distros like Core and we should use the same place no matter the distro.

**Comment by Saviq** [comment]
1) we could either use a PPA or (preferably) build a snap
2) indeed
3) I think the best place would be our cloud-init ISO
