### ISSUE TITLE
-vvv is not the same as -v -v -v

### ISSUE THREAD

**Issue by kalikiana** [canonical/multipass#63]
Since `--help` suggests this

      -v, --verbose  Increase logging verbosity, repeat up to three times for more
                     detail

I did this:

    $ multipass start -vvv test
    Verbose level: 0

That seemed wrong, so I instead tried this:

    $ multipass start -v -v -v foo
    Verbose level: 3

I'd expect both of these to have the same effect.

**Comment by Saviq** [comment]
Yeah IIRC Qt's argument parsing doesn't make that easy.

That said, I'm afraid `--verbose` isn't actually hooked up to anything right now...

**Comment by albaguirre** [comment]
This was fixed by #395
