### ISSUE TITLE
Unexpected qemu process exit is not relayed back to the client during launch & start

### ISSUE THREAD

**Issue by kalikiana** [canonical/multipass#64]
I wanted to run a new instance on a VPS.

    # multipass launch --name=foo
    failed to launch: failed to determine IP address

Running qemu by hand gives me this (command copied from `ps -flA | grep qemu` on another machine where an instance of the same name was running fine):

    (qemu) qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory

Increasing the memory of the system fixed it.

**Comment by Saviq** [comment]
In general we're lacking some error condition handling, like the instance being shut down. The daemon seems it doesn't notice and that results in weird errors.
