### ISSUE TITLE
[libvirt] multipass instances time out after snap refresh

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#647]
When using the libvirt backend, a multipass refresh sometimes fails to fully recover previously running instances. In particular, they get no IP (virsh shows them running, but no DHCP leases). This does not happen all the time though.

Steps to reproduce:
```sh
snap install --beta --classic multipass
snap set multipass driver=LIBVIRT
multipass launch
snap refresh --edge multipass
multipass list
```

Recovering of suspended instances after a reboot of the host was also reported to suffer from the same issue.

**Comment by Saviq** [comment]
I believe this is because we rely on `dnsmasq`'s leases file that gets reset and so we don't know the IP of the instance that resumed. We need to cache the last known IP per instance or not destroy the leases file.

**Comment by townsend2010** [comment]
Since we have recently moved to using host based `libvirt`, I wonder how we should handle the restart of `multipassd` wrt to suspending instances when using the libvirt backend?

**Comment by Saviq** [comment]
If we can tell multipassd that it's shutting down for a restart (as opposed to system shutdown), we can probably keep them going.

**Comment by townsend2010** [comment]
Yeah, good point.  We need to know _why_ `multipassd` is shutting down.

At any rate, I think this particular bug goes away since `libvirtd` and its `dnsmasq` will no longer be restarting on a multipass snap refresh.  I'll do some tests to see and close if I can't reproduce.

**Comment by townsend2010** [comment]
I have been unable to reproduce this since moving `libvirt` out of the snap.  I do think we should try to be more "nice" and not suspend `libvirt` based instances when the multipass snap refreshes.  I'll open a separate bug for that though.
