### ISSUE TITLE
Concurrent `launch` requests duplicate downloads

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#664]
Steps:
- run `multipass launch <not-cached-image>` twice

Expected:
- only one download follows

Current:
- both requests download the image separately

**Comment by ricab** [comment]
I believe this happens because the `URLDownloader` calls the event loop to avoid blocking other requests. If in that event loop we process another launch request, a new download is triggered. If it's the same image, it is actually being downloaded twice.
