### ISSUE TITLE
getting output from multipass hangs when redirecting output to a file

### ISSUE THREAD

**Issue by ColinIanKing** [canonical/multipass#667]
When redirecting output of stdout to a file the following command will hang:

multipass exec my-instance -- systemd-analyze blame > output.log

I've found a workaround:

multipass exec my-instance -- systemd-analyze blame > output.log  < /dev/null

..however I'd rather not rely on a workaround.

**Comment by ColinIanKing** [comment]
One more thing to note, the tty semantics of exec are not the same as ssh'ing, for example:

multipass exec bionic -- systemd-analyze dump

..will invoke the systemd-analyzer pager, where as I was expecting the output to go via directly to stdout.  So I suspect the systemd-analyzer is treating the output as a tty differently to that when one is executing a command via ssh.

**Comment by Saviq** [comment]
Regarding `multipass exec`, it should behave exactly like `ssh` would - if you're in a terminal, the tty gets passed to the instance, this way you can:
```
multipass exec <instance> bash
```
and get a working bash session. If you pipe output or input, indeed it should work without the tty.

**Comment by paride** [comment]
I think the following is related. The standard way to prevent programs expecting data from stdin from blocking is to add a redirect from `/dev/null`, like this:

```
$  multipass exec testvm cat
<blocks>

$  multipass exec testvm cat </dev/null
$ # doesn't block
```

however `</dev/null` redirects behave in unexpected ways in multipass, for example:

```shell
$ multipass exec testvm noexistent # works as expected
bash: noexistent: command not found

$ multipass exec testvm noexistent </dev/null
<blocks with 100% CPU usage>

$ multipass exec testvm wget
wget: missing URL
[expected output]

$ multipass exec testvm wget </dev/null
<blocks with 100% CPU usage, the same happens with curl>

$ multipass exec testvm true </dev/null # works as expected
$ multipass exec testvm false </dev/null # works as expected
```

**Comment by mmontossi** [comment]
any progress on this? I'm facing the same issue...

**Comment by Saviq** [comment]
A couple points:
1) redirecting to a file indeed doesn't switch `multipass exec` to a no-tty mode, the file contains the "pager" footer
1) regarding `exec`, we're following `lxc exec`'s behaviour, where the terminal is passed by default (as opposed to ssh):
   ```
   $ lxc exec <container> bash
   # gets you a shell
   # vs.
   $ ssh <host> bash
   # waits for input
   ```

**Comment by townsend2010** [comment]
I'll be posting a fix for the original issue posted here.  However, the additional /dev/null issues pointed out in https://github.com/CanonicalLtd/multipass/issues/667#issuecomment-509710164 are different issues and I'll split that out as a different issue.

**Comment by townsend2010** [comment]
Unfortunately, the fix I identified for this issue caused a regression (#1214) and so we had to revert.  I will work on a solution that address both issues.
