### ISSUE TITLE
Doesn't respect disk size with "GB" suffix

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#67]
`multipass launch -n foo -d 10GB -m 2G`

Did not complain about the invalid disk size value but reverted silently to the default. It would be nice if it would refuse to go ahead to avoid issues after using the VM.

`multipass launch -n foo -d 10G -m 2G` works as expected.

$ multipass version
multipass  2017.2.2-full-1-g01a386f
multipassd 2017.2.2-full-1-g01a386f

**Comment by Saviq** [comment]
The flag is actually valid, the bug is that we didn't respect it!

**Comment by hatched** [comment]
@Saviq updated with version
