### ISSUE TITLE
qemu backend tries to allocate millions of megabytes of memory

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#677]
Between #654 and #650 the qemu backend started allocating petabytes of memory... Failing, obviously.

**Comment by ricab** [comment]
From `man qemu-system-x86_64`

       -m [size=]megs[,slots=n,maxmem=size]
           Sets guest startup RAM size to megs megabytes. Default is 128 MiB.  Optionally, a
           suffix of "M" or "G" can be used to signify a value in megabytes or gigabytes
           respectively.

So qemu's memory resolution is megabytes. We will floor when an exact match is not possible.

**Comment by ricab** [comment]
Also interesting: https://libvirt.org/formatdomain.html#elementsMemoryAllocation

In particular 

> [...] the value will be rounded up to the nearest kibibyte by libvirt, and may be further rounded to the granularity supported by the hypervisor. Some hypervisors also enforce a minimum, such as 4000KiB. [...]"
