### ISSUE TITLE
Multipass needs more regular releases

### ISSUE THREAD

**Issue by popey** [canonical/multipass#693]
Twice now, in the last few weeks I've encountered bugs in the build in the beta channel which is already fixed in master, and thus in edge. So the 'workaround' / 'fix' for me as a consumer of multipass is `snap refresh multipass --edge`. 

Last night I kicked off a script to build a few snaps on my laptop. The multipass edge snap refreshed and killed my build. I'm a sad bunny that I'm having to use the edge builds of multipass as a consumer, as it leads to higher chance of a refresh breaking builds. 

Yes, I could defer refreshes to mitigate this, and indeed I do, I do my refreshes overnight. However, I'd rather like to not have this problem in the first place.

Please do releases of multipass more regularly. <3

**Comment by Saviq** [comment]
Totally, yes. We're planning a monthly release cadence at least.
