### ISSUE TITLE
multipass edge is sometimes late executing cloud-init directives

### ISSUE THREAD

**Issue by kstenerud** [canonical/multipass#696]
This is a script I was working on before running into https://github.com/CanonicalLtd/multipass/issues/690

It works perfectly in the beta channel, but fails in the edge channel. The installation of nginx happens much later after multipass launch finishes. If I test on a single VM, it works, but when doing two VMs back-to-back, it fails:

```
karl@tp-work:~/Projects/linux-ha-notes/keepalived-quickstart$ snap info multipass
name:      multipass
summary:   Ubuntu at your fingertips
publisher: Canonical✓
license:   unset
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch` and it'll do all the setup
  for you. Check out `multipass find` for a list of available images. More details you can find
  under `multipass help`.
commands:
  - multipass
  - multipass.virsh
services:
  multipass.libvirt-bin: simple, enabled, inactive
  multipass.multipassd:  simple, enabled, active
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     edge
refresh-date: yesterday at 17:54 CET
channels:
  stable:           –                                             
  candidate:        –                                             
  beta:             v0.5                   2019-01-22 (587) 111MB classic
  edge:             0.6.0-dev.218+g3febdd7 2019-03-27 (700) 112MB classic
  core16/stable:    –                                             
  core16/candidate: –                                             
  core16/beta:      v0.5                   2019-03-07 (587) 111MB classic
  core16/edge:      v0.5-128-g47ceef4      2019-03-07 (659) 112MB classic
installed:          0.6.0-dev.214+gec3848d            (697) 112MB classic
```
keepalived-cloud-config.yaml:
```yaml
#cloud-config

bootcmd:
  # https://github.com/CanonicalLtd/multipass/issues/666
  - sudo ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf

packages:
  - nginx
  - keepalived
```
keepalived-quickstart.sh:
```bash
#!/bin/bash

set -eu

echo
echo "### Rebuilding ka-node1 and ka-node2"

multipass delete -p ka-node1 || true
multipass delete -p ka-node2 || true

multipass launch daily:cosmic --cloud-init ./keepalived-cloud-config.yaml --name ka-node1
multipass launch daily:cosmic --cloud-init ./keepalived-cloud-config.yaml --name ka-node2

# -------------------------------------------------------------------

echo
echo "### Gathering network information"

ip_node1=$(multipass exec ka-node1 -- ip addr | grep 'inet ' | grep global | head -1 | sed 's/.*inet \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/g')
ip_node2=$(multipass exec ka-node2 -- ip addr | grep 'inet ' | grep global | head -1 | sed 's/.*inet \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/g')
ip_dot3=$(multipass exec ka-node1 -- ip addr | grep 'inet ' | grep global | head -1 | sed 's/.*inet \([0-9]*\.[0-9]*\.[0-9]*\)\..*/\1.3/g')

echo "ka-node1 is at $ip_node1, ka-node2 is at $ip_node2, and our virtual IP will be at the .3 address of this subnet: $ip_dot3"

# -------------------------------------------------------------------

echo
echo "### We're using nginx as our highly available service. Create home pages so we can see when it's running."
echo
echo "Note: You'd normally use the same content on both sites, but we want to see via the browser which node is running!"

multipass exec ka-node1 -- sudo bash -c "echo '<html><h1>Primary</h1></html>' >/var/www/html/index.html"
multipass exec ka-node2 -- sudo bash -c "echo '<html><h1>Secondary</h1></html>' >/var/www/html/index.html"
```
Result:
```
karl@tp-work:~/Projects/linux-ha-notes/keepalived-quickstart$ ./keepalived-quickstart.sh 
/snap/bin/multipass
### Rebuilding ka-node1 and ka-node2
Launched: ka-node1                                                              
Launched: ka-node2                                                              
                                                                                
### Gathering network information
ka-node1 is at 10.214.41.37, ka-node2 is at 10.214.41.99, and our virtual IP will be at the .3 address of this subnet: 10.214.41.3

### We're using nginx as our highly available service. Create home pages so we can see when it's running.

Note: You'd normally use the same content on both sites, but we want to see via the browser which node is running!
bash: /var/www/html/index.html: No such file or directory
```
This looks like a timing issue:

```
karl@tp-work:~/Projects/linux-ha-notes/keepalived-quickstart$ multipass exec ka-node1 -- bash -c "apt search nginx |grep '^nginx/'"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

nginx/cosmic-updates,cosmic-security,now 1.15.5-0ubuntu2.1 all [installed]
karl@tp-work:~/Projects/linux-ha-notes/keepalived-quickstart$ multipass exec ka-node2 -- bash -c "apt search nginx |grep '^nginx/'"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

nginx/cosmic-updates,cosmic-security 1.15.5-0ubuntu2.1 all
```
30 seconds later:

```
karl@tp-work:~/Projects/linux-ha-notes/keepalived-quickstart$ multipass exec ka-node2 -- bash -c "apt search nginx |grep '^nginx/'"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

nginx/cosmic-updates,cosmic-security,now 1.15.5-0ubuntu2.1 all [installed]
```

**Comment by Saviq** [comment]
Hi @kstenerud yes, this was actually done on purpose to improve the perceived speed of `multipass launch`, as in the launch itself we need not wait for `cloud-init` any more.

What you can do is add a `multipass exec <instance> cloud-init status --wait` in your script after `launch`.

We'll have to consider whether putting `--cloud-init` on the `launch` command line warrants Multipass waiting for that itself again, or maybe we'll add a `--wait` option of some kind that would enable that. What do you think?

**Comment by kstenerud** [comment]
Hmm this is tricky.

If you wait, you have longer launch times, but if you don't, you may have an incomplete system when users start interacting with it. On the other hand, for service nodes, there's probably no need to wait because the services themselves need time to initialize.

This is definitely going to be a per-circumstance preference.

Either way you do this, there will be confusion without something explicit in the docs:

* By default, wait for cloud init and have `--no-wait-cloud-init` to turn it off.
* By default, don't wait for cloud init and have `--wait-cloud-init` to turn it on.

My inclination would be towards waiting by default, because this follows the principle of least astonishment (people would normally expect the system to be finished installing by the time they use it). Otherwise you risk a bunch of invalid bug reports. This would then leave the "no wait" option as an optional optimization that can be discovered in the docs, with caveats explained.

**Comment by Saviq** [comment]
That depends what you mean by "incomplete system". It's complete as far as Multipass is concerned (we can access it and log in as our user). If the user asked for additional steps through `--cloud-init`, it should be their decision on whether to wait for that to complete or not.

My proposal:
- add `--wait` and `--no-wait` to `multipass launch`
- default to `--no-wait` if no `--cloud-init` provided
- default to `--wait` if `--cloud-init` provided

@ricab @gerboland @townsend2010 what do you guys think?

**Comment by kstenerud** [comment]
Yes, that makes sense :)

Just out of curiosity, what else would it wait for if there was no `--cloud-init` phase to perform? It has to wait for network and sshd to come up I think, right?

**Comment by townsend2010** [comment]
@Saviq,

I'm good with your proposal.

**Comment by Saviq** [comment]
@kstenerud `cloud-init` always runs, and depending on how it's configured in the image itself, for example, it may actually take a while. What you give in `--cloud-init` is just one source of data that `cloud-init` takes into account.

**Comment by ricab** [comment]
@Saviq I think I would be more in favor of a single default. IIUC, not waiting for `cloud-init` may impact the user, whether or not `--cloud-init` was provided. If it doesn't just because it is usually fast enough when no `--cloud-init` is provided, then we might as well just wait. If we don't want to wait, it is because things may not be immediately required. But then that is also true with `--cloud-init`.

**Comment by Saviq** [comment]
Yeah indeed, maybe the distinction between passing `--cloud-init` and not is moot. Maybe we only need a `--no-wait` option, since for the most common case `cloud-init` will be done by the time we can ssh in.

@townsend2010 ↑?

**Comment by townsend2010** [comment]
I guess it's fine to default back to waiting for `cloud-init` to complete...the only reason we removed that was due to the long `apt update`/`apt install sshfs` operation it was doing and we've now moved that to be on demand.

So yeah, I'm fine with just adding a flag to not wait on `cloud-init`, but I think we should name it something else besides `--no-wait` since that implies the client doesn't wait _at _all__ at `launch`.  Maybe something like `--no-cloud-init-wait` or something?

**Comment by Saviq** [comment]
Yeah I was thinking that `--no-wait` would not be enough, but `--no-cloud…` is a mouth^Whandful… `--no-init-wait`? `--no-wait-init`?

**Comment by townsend2010** [comment]
We are getting some more requests to have this in place, so will work on getting it done this cycle.

**Comment by townsend2010** [comment]
I've re-introduced the `wait_for_cloud_init()` functionality, and for our default `cloud-init`, it's nearly instantaneous.  Thinking about it some, do we really need a `--no-wait-init` option (or whatever we name the option) for `'launch` if someone uses a long running custom `cloud-init`?  I would think they would want to wait for it to complete before moving and the other "no wait" use case would seem quite unlikely.

I'm asking because we'll need to modify the rpc/client/daemon in order to support that option and I'm just not sure if it's worth it.

@Saviq, @gerboland, @ricab, any opinions?

**Comment by Saviq** [comment]
Let's just bring back `wait_…` for now and see if poeple actually want `--no-wait`?

**Comment by ricab** [comment]
@townsend2010 makes sense to me (sorry for the late reply)
