### ISSUE TITLE
start failed: timed out waiting for instance to respond (on Windows 10 host)

### ISSUE THREAD

**Issue by ColinIanKing** [canonical/multipass#706]
Running latest multipass (as of 1st April 2019) on Windows 10 Pro Xeon host with 8 CPUs + 16GB of memory.  My network is 200mbit/sec so it's fast enough network + host IMHO.

multipass launch -c 8 -m 8G 16.04

.. after a long while I see the timeout message. No idea how to work around this.

"start failed: timed out waiting for instance to respond"

**Comment by townsend2010** [comment]
@ColinIanKing,

Sounds like it could be related to the virtual networking.  Could you look in the Event Viewer and see if you see anything there?  Also, in the Hyper-V Manager->Virtual Switch Manager, do you see an called "Default Switch"?  Lastly, which build of Windows are you using?

**Comment by ColinIanKing** [comment]
Update: creating a vm with 2GB and 8 CPUs seems to work, so it maybe a memory constraint.

**Comment by ColinIanKing** [comment]
OK, seems like anything > ~6GB is not able to start and times out. :-(

**Comment by ColinIanKing** [comment]
So the timeout error message could be improved if it's possible to detect such failures.  Took me a while to figure out what the failure was.

**Comment by Saviq** [comment]
Agreed, we need to realize the instance failed to start at all (as I'm expecting Hyper-V returned an error here).

**Comment by ntherrien** [comment]
We are having the same issue, on Windows 10 Host.

No errors in Hyper-V event viewer.

We can perform "multipass list" and see the vms in running state. But when we try to execute a command on it we are getting "ssh connection failed: 'Failed to resolve hostname microk8s-vm.mshome.net" where "microk8s-vm" was the name of the VM.

**Comment by Saviq** [comment]
Hi @ntherrien I think yours is a slightly different issue, and one more like #1052 - can you try creating a fresh VM from the Hyper-V Gallery and see if it gets networking fine? And whether its IP is reachable via "ping <hostname>.mshome.net"?

**Comment by ntherrien** [comment]
Hi @Saviq, thanks for your response. Solution for us was to restart the Hyper-V default switch.   It seems like the internal network was not allowing internet access.   We realized that when we tried to do a vm manually and then download microk8s on it. I don't know why this happenned on two different machines but thanks for your help.

**Comment by Saviq** [comment]
@ntherrien glad you got it going, could you please document what exact steps you needed to take to unclog it? Thanks!

**Comment by ntherrien** [comment]
Of course @Saviq! Here goes: 

In both cases, we went to the network adapters control panel, right clicked the default switch, selected Disable and then Enabled it again.   That forced the adapter to obtain/refresh a LAN IP address on the same subnet as the ones allocated to the VMs attached to that default switch.

At first, I thought the problem could easily be detected by running ipconfig and verifying if the default switch was assigned a link-local address (169.254.*.*) but this is not always the case. We had one computer which had a valid LAN address in the first place, and still had no route to the vms.   Disabling/Enabling the default switch has fixed the problem in both cases, though.

We can also ping vmname.mshome.net as expected after doing this.

we are going to be paying attention as to whether the problem with the default switch still occurs after a reboot.

**Comment by SirWindfield** [comment]
I'm still experiencing this problem on my Windows 10 machine. It's my desktop computer without any network adapters installed beside the WiFi one that I use (which probably gets added after connecting to it...?)

**Comment by grebennikov** [comment]
Same here. Windows 10 enterprise, fresh multipass install. Following the exact guide - getting timeout on VM start.

**Comment by Oz0n3** [comment]
I had this same issue.  I resolved it by uninstalling vmware.  I am not sure if there is a way to make hyper-v and vmware work together, but since I don't really use it I just uninstalled it.

**Comment by ricab** [comment]
To refocus, this can be reproduced by trying to launch with more memory than the system can commit. Hyper-v errors out starting the VM immediately, but multipass fails to see this and just keeps on waiting for the instance until timeout. 

For reference, the corresponding Hyper-V errors can be found in the event viewer under "Applications and Services Logs → Microsoft → Windows → Hyper-V-Worker → Admin".

**Comment by sromano1992** [comment]
Same issue for me. Resolved turning off my VPN client.

Hope this can help

**Comment by Echo9k** [comment]
I solved it following this [tutorial](https://www.youtube.com/watch?v=TM0bd20Bu6I&t=25s)
You will need to have CMD-admin rights and restart after running 5 comands.

**Comment by Tariqpgr8** [comment]
Hi members - I'm experiencing some issue. I've launch and one instance which is up and running (works perfectly fine). I came out from that instance and tried to launch one more instance (keeping in mind that one instance is up and running) with same capabilities --cpus 2 --mem 2G --disk 5G. After several minutes of wait, it says timeout. But as soon as I stopped all previous instances and tried to launch a new one it works fine. Can anyone guide me about this dependency?

**Comment by Tariqpgr8** [comment]
> Hi members - I'm experiencing some issue. I've launch and one instance which is up and running (works perfectly fine). I came out from that instance and tried to launch one more instance (keeping in mind that one instance is up and running) with same capabilities --cpus 2 --mem 2G --disk 5G. After several minutes of wait, it says timeout. But as soon as I stopped all previous instances and tried to launch a new one it works fine. Can anyone guide me about this dependency?

Windows 10, using MS Hyper-V. Core i7 3rd gen 8gb ram and plenty of ssd remaining.

**Comment by ColinIanKing** [comment]
Why closed? Has this been fixed?

**Comment by ricab** [comment]
Hi @ColinIanKing, yes. We were basically missing a check for a return. I submitted a fix where multipass now detects when hyper-v start fails (e.g. because of low memory), aborting the launch.

**Comment by Saviq** [comment]
To clarify: the "timeout" error was misleading - the instance never started, so Multipass timed out waiting for it. Now you will get the context of _why_ it did not start.

**Comment by ColinIanKing** [comment]
Ah, OK. Basically I need shed loads of memory. Understood. Thanks.
