### ISSUE TITLE
some actions on mounted directory fail with permission denied

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#71]
I created a directory on host and mounted it to VM
`multipass mount remote:/home/marian/VMs/multipass/git Mate-17-10:git`

when I connect to VM, I can create files and directories in mounted dir, but git clone fails

```
Cloning into 'mate-applets'...
error: could not write config file /home/ubuntu/git/mate-applets/.git/config: Operation not permitted
fatal: could not set 'core.filemode' to 'true'

```

When I move outside the mounted directory, git clone works.

When I return back to host and run git clone into that directory, it works.

Going back to VM, I can see cloned dir, I start ./autogen.sh. It starts to work, creates things as expected, but then fails with 
`./autogen.sh: 438: /usr/bin/mate-autogen: ./configure: Permission denied`

Maybe exec flag on mount missing?
It is mounted as 

`:/home/marian/VMs/multipass/git on /home/ubuntu/git type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)`

**Comment by marosg42** [comment]
Probably not exec flag. I copied /bin/dir command to mounted dir and I could execute it from there.

**Comment by townsend2010** [comment]
After looking at an strace of this, this is what is happening:

``rename("/home/ubuntu/git/multipass/.git/config.lock", "/home/ubuntu/git/multipass/.git/config") = -1 EPERM (Operation not permitted)``

So maybe our sftp_server is missing a function or not handling one correctly.

**Comment by townsend2010** [comment]
So the issue is that git tries to rename a file to a name of a file that already exists and the underlying QFile::rename() fails on this condition.

I'll have to think about how best to handle this condition.

**Comment by marosg42** [comment]
I can confirm version 2017.2.3-14-gc2f33a5 (123) solves the issue
