### ISSUE TITLE
Support to configure the mirror url of cloud image  

### ISSUE THREAD

**Issue by adglkh** [canonical/multipass#717]
The user experience of using multipass in China is not quite good.

- The process of cloud image download from the official site https://cloud-images.ubuntu.com is interrupted quite often.
- I also hit the issue from time to time in poor network conditions  https://github.com/CanonicalLtd/multipass/issues/386 
- If i was lucky enough, the whole process to download an image from the above URL would take 1~2h, which is really painful.

So I'm wondering if there's a way to configure mirrors in multipass so that I can use something like the URL[1] as a mirror to boost the image download speed.
That could be really helpful for multipass users in China.

Thanks
Gary 

[1] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/

**Comment by Saviq** [comment]
Hey @adglkh,

Certainly, this would be a welcome addition. #276 needs to be solved before, though, so we can authenticate the images downloaded.

**Comment by wusphinx** [comment]
when you visit https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/ , you can't find the directory **release**, which will cause something wrong as below: 
```
launch failed: Remote "release" is unknown or unreachable. If image mirror is enabled, please confirm it is valid.
```
but, you can try the following commands
```
multipass set local.image.mirror=https://mirrors.cloud.tencent.com/ubuntu-cloud-images/
```
it works fine.
