### ISSUE TITLE
Optimize `qemu` executions

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#719]
There's a handful of `qemu` flags that we could use to optimize the speed of qemu-based instances.

The full list of suggested tweaks:
```
Tune up the disk to use multiple channels and virtio-scsi (for trim
and such later if needed)
Instead: -hda /var/snap/multipass/common/data/multipassd/vault/instances/magical-sablefish/ubuntu-18.04-server-cloudimg-amd64.imgi
Use: -device virtio-scsi-pci,id=virtio-scsi-mp,num_queues=8
     -drive if=none,id=hd,file=/var/snap/multipass/common/data/multipassd/vault/instances/magical-sablefish/ubuntu-18.04-server-cloudimg-amd64.img
     -device scsi-hd,drive=hd

Use threaded device handling, define a set of I/O threads and assign
them to your devices to be independent
USE:
  -object iothread,id=iothread0 \
  -object iothread,id=iothread1 \
  -object iothread,id=iothread2 \
  -device virtio-scsi-pci,iothread=iothread0,id=scsi0,$VSP_OPTS \
  -device virtio-scsi-pci,iothread=iothread1,id=scsi1,$VSP_OPTS \
  -device virtio-scsi-pci,iothread=iothread1,id=scsi2,$VSP_OPTS
Use that for any device that you add

You don't expose graphics nor use the serial console
Use: -nographic
If you need to have a serial console to attach later you can use
-nographics -serial ...
In general the less devices the faster it will be

Help us tracking multipass vs other things, set what you are in smbios
User: -smbios type=1[,manufacturer=str][,product=str][,version=str][,serial=str][,uuid=uuid][,sku=str][,family=str]

Also use vhost-net
Instead: -device
virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:8e:fc:19 -netdev
tap,id=hostnet0,ifname=tap-8f9941eb131,script=no,downscript=no
USE:     -device
virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:8e:fc:19 -netdev
tap,id=hostnet0,ifname=tap-8f9941eb131,script=no,downscript=no,vhost=on

This needs some probing, but can help - set Discard features on disks
if the host has ssd/nvme disks backing things
Use: discard=discard on disk config

Further we should use the q35 based machine as it is more modern in
general and initializes slightly faster
Instead: (not present)
Use: -M pc-q35-<release>
Hint: Potential types can be probed with `qemu-system-x86_64 -M ?`
```

Need to evaluate them first :)

**Comment by townsend2010** [comment]
It should be trivial to add these options.  Do we have any idea what these options are?

**Comment by cpaelzer** [comment]
Hi,
I wanted to ask if there is and progress on this and in particular since I found this "Do we have any idea what these options are" question - is there anything I could help with?

**Comment by Saviq** [comment]
Hi @cpaelzer thanks, just need to get to integrating those in. I only added your report in the description after Chris asked.

**Comment by cpaelzer** [comment]
One of the biggest speedups we discussed is the external loading of kernel/initrd (instead of using bootloaders) which you said you do already.
But I don't see that on --beta (752) or --edge (798) yet.
If not really in the code yet consider using -kernel/-initrd as big speedups as well please.
They are published on the maas streams and/or can be read out of the image with mount-image-callback.

**Comment by cpaelzer** [comment]
Finally lets please also add `-name` for better visibility in ps,top,htop,... and similar tools that show processed/threads.

`-name guest=<name>,debug-threads=on`

(no speedup but very helpful)

**Comment by Saviq** [comment]
> One of the biggest speedups we discussed is the external loading of kernel/initrd (instead of using bootloaders) which you said you do already.
> But I don't see that on --beta (752) or --edge (798) yet.
> If not really in the code yet consider using -kernel/-initrd as big speedups as well please.
> 
> They are published on the maas streams and/or can be read out of the image with mount-image-callback.

Looks like we misunderstood each other, we're only doing this today on macOS that can't do bootloaders. In any case, having discussed this with CPC and Foundations, it's unlikely that we'll be bypassing bootloaders unless necessary. I'm told `initramfs`-less boot is what gives the biggest speedup and that's what we're targeting with those teams.

The biggest problem with booting the kernel directly is that there's no way to upgrade it (or select another) from inside the instance, meaning we'd have to add some kernel management to Multipass itself. People would also have to be taught that whatever kernel they install is not in use.

**Comment by Saviq** [comment]
We're punting this to LXD since that's what will drive qemu/KVM for us soon.
