### ISSUE TITLE
Cannot launch trusty VM as claims it is not supported

### ISSUE THREAD

**Issue by powersj** [canonical/multipass#734]
When launching a VM of trusty today I was told it is no longer supported:

```
$ multipass launch trusty
launch failed: The trusty release is no longer supported. 
```

Version info:

```
$ snap info multipass
name:      multipass
summary:   Ubuntu at your fingertips
publisher: Canonical✓
license:   unset
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch` and
  it'll do all the setup for you. Check out `multipass find` for a list of
  available images. More details you can find under `multipass help`.
commands:
  - multipass
  - multipass.virsh
services:
  multipass.libvirt-bin: simple, enabled, inactive
  multipass.multipassd:  simple, enabled, active
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     beta
refresh-date: 17 days ago, at 12:01 PDT
channels:
  stable:           –                                             
  candidate:        –                                             
  beta:             0.6.0                  2019-04-02 (716) 113MB classic
  edge:             0.7.0-dev.115+g8295962 2019-04-19 (740) 113MB classic
  core16/stable:    –                                             
  core16/candidate: –                                             
  core16/beta:      0.6.0                  2019-04-02 (716) 113MB classic
  core16/edge:      0.7.0-dev.236+gcd11605 2019-03-29 (712) 113MB classic
installed:          0.6.0                             (716) 113MB classic
```

**Comment by dhenrich** [comment]
Yeah, this is broken. 14.04 is still supported, it should work.

**Comment by vorlonofportland** [comment]
This is probably based on /usr/share/distro-info/ubuntu.csv from distro-info-data listing the original EOL date of 2019-04-17.  There's still wrong data showing 2019-04-17 instead of 2019-04-25 for the end of standard support; but there is also now a new eol-esm field which is populated for trusty and should be used instead if present.

**Comment by OddBloke** [comment]
https://github.com/CanonicalLtd/multipass/blob/01514281334ddaf7c4d736cc216fb6c4547e36e8/src/daemon/ubuntu_image_host.cpp#L111 suggests to me that this is actually keyed off the "supported" key in streams:

```
% curl http://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json | grep "supported.*false" -A1 | grep 14.04 -B1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5919k  100 5919k    0     0  1110k      0  0:00:05  0:00:05 --:--:-- 1219k
   "supported": false,
   "version": "14.04",
--
   "supported": false,
   "version": "14.04",
--
   "supported": false,
   "version": "14.04",
--
   "supported": false,
   "version": "14.04",
--
   "supported": false,
   "version": "14.04",
```

**Comment by townsend2010** [comment]
Multipass is getting this information from SImpleStreams.  A quick look at http://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json and clicking through `Products:` -> `com.ubuntu.cloud:server:14.04:amd64` says `Supported: false`.   So this needs to be fixed in SimpleStreams.

**Comment by townsend2010** [comment]
I'm going to close this and interested parties can follow up with the cloud-images folks:)

**Comment by OddBloke** [comment]
@townsend2010 I agree that this isn't a multipass issue; I expect a workaround would be:

```
multipass launch http://cloud-images.ubuntu.com/releases/trusty/release/ubuntu-14.04-server-cloudimg-amd64-disk1.img
```

Does that make sense for people to use in the meantime?

**Comment by townsend2010** [comment]
@OddBloke,

Sure, that is a way to work around this.  Of course, the cached image will never update, but I don't think that will matter in this case:)
