### ISSUE TITLE
Allow configuring the primary name

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#766]
It should be possible to configure the name of the primary instance (currently "primary"). Following current state of affairs in #756, this should be achievable with `multipass set client.primary_name <name>`.

**Comment by ricab** [comment]
Initially, this may involve very basic `set`(/`get`/`config`) command(s) that only accept(s) the one key. To accommodate further configuration, however, these commands would probably need to rely on some intermediary object knowing what keys should be in the output, what to fill them with, and how to reflect config input on program state.

**Comment by ricab** [comment]
@Saviq IIUC this should be in 0.7.0, right? I added it there, please change if needed.

**Comment by ricab** [comment]
Looking better into this issue, I don’t think it makes sense to implement anything without a config intermediary.

Being an adept of _solving the problem, then coding_, I put together [some thoughts](https://docs.google.com/document/d/1pyQsMTPnR-iDqKeffo0bS7rSq-BwbZ0tbxdfx_l89QU) on how to approach this. @Saviq, @townsend2010, @gerboland, your feedback would be appreciated.

**Comment by ricab** [comment]
After further team discussion, the current plans for this issue evolved:
- use `QSettings` directly
- use a specific per-user file for client settings (separate from the daemon's)
    * this file is shared by both CLI and systray clients
- create a `QSettings` object as needed, throwing away after use (both read and write use, no internal state, only the file keeps record of the settings)
- rely on Qt file watchers/locks to protect concurrent access

**Comment by gerboland** [comment]
>     * rely on Qt file watchers/locks to protect concurrent access
Note that QSettings does this for you. We do need Qt file watcher for the daemon to watch for if the client changes the settings file though.

**Comment by Saviq** [comment]
> Note that QSettings does this for you. We do need Qt file watcher for the daemon to watch for if the client changes the settings file though.

And for the systray, too.

**Comment by ricab** [comment]
For the systray *only* actually, right? Since the daemon was supposed to be killed by the client: #776

**Comment by Saviq** [comment]
Correct.

**Comment by ricab** [comment]
Fixed by #805
