### ISSUE TITLE
Send usage data question blocks run when running in a batch script

### ISSUE THREAD

**Issue by ColinIanKing** [canonical/multipass#767]
I was wondering why a batch script was taking a while to complete and noticed that multipass was blocked on asking me the following question:

"Send usage data (yes/no/Later)? no"

Tad annoying to have a tool that blocks like this when running the tool inside a python script and it blocks waiting for input when I'm trying to get automated multipass scripts to work. Is there a way around this?

Also the question has a lower case "yes" and "no" but an upper case "Later" which is rather awkward.

**Comment by Saviq** [comment]
Hi @ColinIanKing, we only ask this if we're in an interactive terminal, so in a batch environment it should be skipped. To ensure a non-interactive behaviour you could `| tee /dev/null`.

I suppose we can add a `--non-interactive` option that would ensure nothing like that happens regardless of interactivity or not.

**Comment by ColinIanKing** [comment]
Unfortunately the script is Python on Windows and not Linux

**Comment by Saviq** [comment]
You should be able to tweak how python invokes the process to ensure no interactivity then… `subprocess.PIPE` comes to mind.

**Comment by ColinIanKing** [comment]
OK, will do. Thanks for the advice, I'm new to the Windows/Python domain

**Comment by joshti** [comment]
hi @Saviq - I'm seeing the same behaviour in a sh script running in git bash.
Is there an additional option that has since shipped in the last year that could help me out here 😄? Perhaps a `multipass set cli.usage_data=false` or similar?

**Comment by Saviq** [comment]
> hi @Saviq - I'm seeing the same behaviour in a sh script running in git bash.

Hey @joshti, just make sure the console isn't interactive:

```bash
$ multipass launch … < /dev/null
# or
$ your-script.sh < /dev/null
```

We're likely to add the above config setting, and potentially a `--non-interactive` option or so, but that would have the exact same effect as the above.
