### ISSUE TITLE
strange issue with mount

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#77]
I cloned a repo from github, without any other actions when I try to checkout my branch it says I have modified files. Plus see how long it took to report the problem. It is also interesting there is that automatic step of checkout 1090 files which does not happen when not in mounted dir.

```
$ rm -rf mate-applets/
$ ll
total 8
drwxrwxr-x  1 ubuntu ubuntu 4096 Jan 27 13:51 ./
drwxr-xr-x 27 ubuntu ubuntu 4096 Jan 27 13:41 ../
$ git clone https://github.com/marosg42/mate-applets.git 
Cloning into 'mate-applets'...
remote: Counting objects: 7363, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7363 (delta 0), reused 1 (delta 0), pack-reused 7358
Receiving objects: 100% (7363/7363), 20.95 MiB | 137.00 KiB/s, done.
Resolving deltas: 100% (4475/4475), done.
Checking out files: 100% (1090/1090), done.
$ cd mate-applets/
$ git branch 
* master
$ time git checkout multiload-network-scale 
error: Your local changes to the following files would be overwritten by checkout:
	multiload/linux-proc.c
	multiload/load-graph.c
	multiload/main.c
	multiload/org.mate.panel.applet.multiload.gschema.xml.in
	multiload/properties.c
Please commit your changes or stash them before you switch branches.
Aborting

real	0m27.345s
user	0m0.065s
sys	0m0.130s

```
Funny thing is, I have those files modified in the same repo, in multiload-network-scale branch but in totally different directory in that instance, they are not in remote repo. It looks like it is looking into other dirs or something like that, I cannot explain.

These are exactly the same steps done outside of mounted directory, that checkout step during clone is not happening and all works as expected.

```

$ rm -rf mate-applets/
$ git clone https://github.com/marosg42/mate-applets.git 
Cloning into 'mate-applets'...
remote: Counting objects: 7363, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7363 (delta 0), reused 1 (delta 0), pack-reused 7358
Receiving objects: 100% (7363/7363), 20.95 MiB | 130.00 KiB/s, done.
Resolving deltas: 100% (4475/4475), done.
$ cd mate-applets/
$ git branch
* master
$ time git checkout multiload-network-scale 
Branch multiload-network-scale set up to track remote branch multiload-network-scale from origin.
Switched to a new branch 'multiload-network-scale'

real	0m0.081s
user	0m0.070s
sys	0m0.012s
```

**Comment by townsend2010** [comment]
The 'git checkout' issue where git says the local changes will overwrite files is now fixed.  You'll still see the checkout of the files step.  This step does happen in a non-mounted directory, but it is fast enough to where git doesn't report it.  However, the performance on the mounted directories is really bad, so git reports the checkout progress.
