### ISSUE TITLE
startup crash on corrupt instance database

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#773]
A problem reported today showed we're fragile when it comes to logically-corrupt instance databases and crashing when we encounter anything out of the ordinary.

We should improve our resiliency there - recover the instance (if it's deleted, it definitely should not be running) and log a warning. If we can't recover without losing data, we should skip the instance and log an error. Crashing is the worst :)

A deleted instance (`deleted: true`) with a running state (`state: 4`) will crash in [`daemon.cpp:593`](https://github.com/CanonicalLtd/multipass/blob/v0.6.1/src/daemon/daemon.cpp#L593).

The instance should have been shut down / suspended when deleting, but that did not happen for some reason and `multipassd` started [crashing](https://github.com/CanonicalLtd/multipass/files/3161538/gdb.txt) since.

```
{
    "lpt": {
        "deleted": true,
        "disk_space": "5368709120",
        "mac_addr": "52:54:00:ac:7a:50",
        "mem_size": "1073741824",
        "metadata": {
            "machine_type": "pc-i440fx-xenial"
        },
        "mounts": [
        ],
        "num_cores": 1,
        "ssh_username": "multipass",
        "state": 4
    },
}
```

**Comment by gerboland** [comment]
I've failed to reproduce this with current Multipass. Perhaps it was possible in an older release?

The only workaround I can propose is this:
https://github.com/CanonicalLtd/multipass/compare/avoid-crash-on-invalid-state

My other idea would be to remove the "deleted" property from the JSON file, and instead use `state: -1` - that I'd prefer as then it wouldn't be possible to have contradictory state in the JSON.

**Comment by ricab** [comment]
I find the approach there to be reasonable, although I would think the log level should be higher than `debug`, to me it is a plain `error`. Error != bug, but if we're concerned with scaring the user, perhaps warning...

As to changing file content, notice we would still have to cope with old DBs...

**Comment by gerboland** [comment]
Yep, supporting old DB would be a wart to drag around
