### ISSUE TITLE
Allow configuring the daemon driver

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#776]
It should be possible to configure the driver for the daemon to use. Following the current state of affairs in #756, this should be achievable with `multipass set local.driver <driver>`, where `<driver>` is one of `qemu`, `hyperkit`, `hyper-v`, `libvirt`.

The current driver should be obtainable with `multipass get local.driver`.

(This issue is a sister of #766)

**Comment by ricab** [comment]
The team discussion mentioned [here](https://github.com/CanonicalLtd/multipass/issues/766#issuecomment-491014781) resulted in the following plan:
- as in #766 use `QSettings` directly, now in both client and daemon (file-backed settings, no RPC)
- use a specific file for daemon settings (separate from the client's)
- in the daemon, the file is only read (not written) and only upon startup
- client also reads/writes to the daemon file, which is how the settings get communicated to the daemon (no RPC)
- consider only one local daemon (follows from local in the single supported key)
- have the client restart the daemon when its config changes (Linux only to begin with)
    * with `snapctl restart $SNAP_NAME` if `$SNAP_NAME` ([ref](https://github.com/CanonicalLtd/multipass/blob/fc2d5d6516c0503f4a794c2009d2fa99a0ebddc0/snap/hooks/configure#L67))
    * `pkill multipassd` otherwise (or similar)
    * note: both will require root privileges, which is fine for now, but need to sort out interplay of settings file and sudo (home dir)

**Comment by matthewpaulthomas** [comment]
Should this setting be provided in the GUI as well?

**Comment by ricab** [comment]
I think this is an essential setting, so I guess it would be appropriate. But I'll let @Saviq, @townsend2010, @gerboland comment.

**Comment by Saviq** [comment]
Hey @matthewpaulthomas I posted an RFC for a full `multipass config` experience #756, a lot of that would have to grow into the GUI in the end. I'd love your feedback there, including any remarks you might have for how to ensure GUI-compatibility from the get go.

For this particular one, "not yet" would be the answer.

**Comment by ricab** [comment]
After some more consideration, we decided to drop daemon restarting from the client and replace it with settings-file monitoring in the daemon + exit (or reinit, possibly) on modification.
