### ISSUE TITLE
Image growing well beyond size limit on osx

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#808]
This image is used for builds so there is a lot of file churn.

```
$ /Library/Application\ Support/com.canonical.multipass/bin/qemu-img info ubuntu-18.04-server-cloudimg-amd64.img
image: ubuntu-18.04-server-cloudimg-amd64.img
file format: qcow2
virtual size: 20G (21474836480 bytes)
disk size: 55G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
    refcount bits: 16
    corrupt: false
```

**Comment by Saviq** [comment]
Agreed this is a problem. It may be down to hyperkit's limited qcow support :/

We will try and tweak how we configure hyperkit's qcow support.

**Comment by gerboland** [comment]
There are compacting options in hyperkit's qcow2 support, I'll try explicitly enabling them to see if it helps

**Comment by townsend2010** [comment]
@gerboland, isn't this fixed now?

**Comment by gerboland** [comment]
Depends on https://github.com/CanonicalLtd/multipass-private/pull/159

**Comment by townsend2010** [comment]
@gerboland, ah, right, I thought that had already been merged :smile:

**Comment by townsend2010** [comment]
Closing since CanonicalLtd/multipass-private#159 is now merged.
