### ISSUE TITLE
Add .deb packaging

### ISSUE THREAD

**Issue by zabbal** [canonical/multipass#816]
Would be nice to add support for Ubuntu so usual "apt install multipass" works as expected.

**Comment by Saviq** [comment]
Hi @zadbal, adding another packaging system always adds a maintenance burdern. All the currently supported Ubuntu systems support snaps, allowing us tight control over what is delivered to our users, and timely delivery at that.

What's the reason that you need a .deb package?

If someone wants to package Multipass in a PPA, they're of course welcome, but we don't have plans for that at the moment.

**Comment by zabbal** [comment]
> What's the reason that you need a .deb package?

Precisely because the reasons you've mentioned: "adding another packaging system always adds a maintenance burdern".

Having alternative packaging solution on every machine just to bring along multipass seems like huge overkill.

Anyway, thank you for clarification, will stick with alternative solutions.

**Comment by aytvill** [comment]
> What's the reason that you need a .deb package?

it might come as surprise for you, but snap is less reliable than you are ready to believe. My snap subsystem went bonkers after I have enabled cgroup v.2 within standard Ubuntu stock kernel. All graphical applications turned into pile of binaries I can try to run but never get them running. Snap maintainer tries to fix it, to no avail and it seems it's not going to happen.

The other reason is that many of us live (and earn paycheck too) with dual world of Debian and Ubuntu systems. And Canonical trying to force us on choice between snap-only and leave "my way or highway" just breaks our lives.

So no, we do need .deb at this stage.

**Comment by townsend2010** [comment]
Hi @aytvill,

I'm reading your comments and appreciate them.  I'm trying to understand if the Multipass Snap package did something unexpected to your system or if you are just saying you are not satisfied with Snap packages in general.

Regarding Multipass as a .deb package, the Multipass team not only has to support the Snap package, but we also have to support packaging on macOS and Windows- we can only support so many packaging types.  We also have to use a fork of `qemu`, `grpc`, and `libssh`, so we'd also need to package and maintain those in .deb form as well.

All this said, we would definitely be open to a community contribution of someone packaging Multipass in .deb form.  We would be willing to help answer questions, etc., but we don't have the resources to do this and maintain it at this time unfortunately.

**Comment by zabbal** [comment]
> We also have to use a fork of `qemu`, `grpc`, and `libssh`, so we'd also need to package and maintain those in .deb form as well.

Is there a reason why you don't upstream your changes?

**Comment by townsend2010** [comment]
> Is there a reason why you don't upstream your changes?

One reason is just time to get them in a state that is upstreamable, ie, our `qemu` changes.

Another is in the past, upstream (grpc) has not shown any interest in taking the proposed changes.  

A third reason is that another upstream (libssh) did not understand why we needed to make a change and wanted us to write a bunch of tests to prove that it is an issue in their code of which, again, we never allocated time to do this.

We found that for the time being, the best use of our resources is to just carry our forks and small(ish) patches and rebase on upstream releases as necessary.

**Comment by vladaman** [comment]
Well, we like deb packages and wherever possible we try to avoid Snap. That's reason why we pass on Multipass for now.

The sentiment I've come across on that Reddit thread might stem from these concerns and from a preference for deb packages due to their long-standing nature and tighter integration with Debian-based systems. People are naturally inclined to stick with what they are familiar with and what has worked well for them in the past.
https://www.reddit.com/r/linux4noobs/comments/smzy5g/why_does_everyone_hate_snap_so_much/

**Comment by kamikaze** [comment]
nah, snap... skipping

**Comment by zabbal** [comment]
Canonical keeps repeating the same mistake:
- invent some NIH
- make it hard to use outside of Ubuntu thinking it'll make people come to Ubuntu
- people ignore NIH and use alternatives
- Canonical abandons NIH because it's unpopular and moves on to the next NIH

Upstart, Unity, snap... I hope they'll learn smth from this one day.
