### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by 030** [canonical/multipass#826]
https://chocolatey.org/search?q=multipass

A Chocolatey package seems to unavailable at the moment.

**Comment by digitalcoyote** [comment]
I've got a package almost ready. I'll try to ready a PR with install instructions once it passes moderation.

**Comment by Saviq** [comment]
That's awesome @digitalcoyote!

Thanks a bunch, looking forward to `choco install multipass` :)

**Comment by digitalcoyote** [comment]
> Instructions on how to update the package / repository on new releases would be welcome, too.
I usually mention that, but I guess I forgot this time. I use an AU git repo (AppVeyor CI) that checks for releases and pushes new packages automatically. Additionally, If as maintainer from this repo wants to be a maintainer on the package (gives management rights like delisting versions or pushing updates manually if needed), I can add them on chocolatey (requires a chocolatey account).

**Comment by Saviq** [comment]
Yeah I think it'd be best if it was part of our release process. We'll be adding Windows CI ASAP, so we would integrate with that.

**Comment by digitalcoyote** [comment]
In that case, you'll definitely need a Chocolatey Account created so I can add it as the maintainer (or else the CI cannot push updates). All I need is the username to add it. Let me know how you want the source for the package and I'll get it in a PR as well (eg. './Chocolatey/')

**Comment by Saviq** [comment]
It will take us a bit of time, so if you can import it through AppVeyor for now, it'd be awesome :)

We're preparing a release now, would be great to have `chocolatey install multipass` as part of it! Let us know if there's anything we can do to help this along :)

**Comment by Saviq** [comment]
Hi @digitalcoyote I see [Multipass is in Chocolatey now](https://chocolatey.org/packages/multipass), awesome, thank you!

Let us know please if there's anything we can improve / fix :)
