### ISSUE TITLE
Add support for specifying mounts at launch time

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#833]
At the moment, launching a multipass VM and mounting a directory in to it are two separate commands:

```
multipass launch my-vm
multipass mount /my/path my-vm:/vm/path
```

Often, users will know at launch-time that they intend to mount a directory in to the VM they are launching, so we could reduce the amount of typing they have to do by making this possible:

```
multipass launch --mount /my/path:/vm/path my-vm
```

This has some other benefits that may not be immediately obvious:

* the first code block above becomes buggy if you specify cloud-config which performs apt operations; you have to wait for cloud-init to complete, see #832 for details
* it makes a simple launch-and-mount much easier to script: at the moment the "caller" has to know the name of the VM to be able to mount into it, which means they either have to determine the name and pass it in to `launch` or they have to parse the `launch` output to determine the name selected
* `launch` can take a while if a new image has to be fetched; being able to fire-and-forget a launch-and-mount operation would reduce user friction a little

**Comment by Lasim** [comment]
+1

**Comment by wylswz** [comment]
+10086

**Comment by michaelschem** [comment]
It would also be helpful if this could run before cloud-init so cloud init can run using files in the mounted volume

**Comment by townsend2010** [comment]
I'll add one reason this has to be this way is `cloud-init` is responsible for setting up networking on first boot and mounts require networking to be in place.  I don't see a way to overcome this at the moment.

**Comment by townsend2010** [comment]
Sure, but `multipass launch` would need to be made aware of the cloud-init boot stages and then be able to "pause" cloud-init from proceeding after stage 3 (just when `multipass` is able to connect to the instance to even get status- sounds like it could be race-y), sets up the mount and then signals cloud-init to continue after the mount(s) is/are set up.  This is not trivial by any stretch and I'm not sure if it's even possible to do such thing.
