### ISSUE TITLE
Multipass on windows does not use system proxy and no option to manually configure proxy

### ISSUE THREAD

**Issue by Tyranwyn** [canonical/multipass#885]
I put the proxy in $env:HTTP_PROXY and $env:HTTPS_PROXY but I always get:
```launch failed: Remote "" is unknown or unreachable.```
Any ideas how to solve this?

**Comment by Saviq** [comment]
Hi @Tyranwyn did you set it for the whole system, or just in the console you're running `multipass` in?

It should pick those up by default, but note there is a service that needs these as well. It may behave slightly different on Windows, too.

**Comment by Tyranwyn** [comment]
Well it was the console, but still, it was a system variable. But it's fine, I figured I could just use the guest network. I read that somewhere, so that's going to be neat. Thanks for answering.

**Comment by Saviq** [comment]
I'll actually keep this open for investigation.

**Comment by tdevilleduc** [comment]
Actually I have the exact same issue.
I'm behind a proxy.
http_proxy, https_proxy and no_proxy are correctly set in my system variables for ages
I run "multipass launch ubuntu" in a cmder console and i get :


`launch failed: Remote "" is unknown or unreachable.`

**Comment by townsend2010** [comment]
@jl-massey,

You confirmed the daemon service is not running when the proxy is set?  The `Remote "" is unknown or unreachable.` text comes from the daemon, so I'm wondering if it really has stopped.

**Comment by townsend2010** [comment]
Also, looks like we may need to use `QNetworkProxyFactory::setUseSystemConfiguration(true)` in order for `multipassd` to use any proxies set for the system.  I'll try that and put up a package that could be tested by users affected by this.

**Comment by townsend2010** [comment]
Hi all,

I have a test package here: [multipass-1.1.0-dev.572+g874c82a8.win-win64.exe](https://transfer.sh/MR7uZ/multipass-1.1.0-dev.572+g874c82a8.win-win64.exe)

If anyone affected by this issue could please try this and let me know if it works with a proxy set up, I would greatly appreciate it.  The link will expire 14 days from when I posted this.

Thanks!

**Comment by tdevilleduc** [comment]
> I have a test package here: [multipass-1.1.0-dev.572+g874c82a8.win-win64.exe](https://transfer.sh/MR7uZ/multipass-1.1.0-dev.572+g874c82a8.win-win64.exe)
> 
> If anyone affected by this issue could please try this and let me know if it works with a proxy set up, I would greatly appreciate it. The link will expire 14 days from when I posted this.

I cannot download this package; transfer.sh gives me a Not Found error

**Comment by townsend2010** [comment]
@tdevilleduc,

Hmm, I just tried the link and it worked for me on multiple machines.  I'm not sure what why you can't download it :frowning_face:

**Comment by asishrs** [comment]
I know this is Windows specific thread, I am facing similar issue on Mac `launch failed: Remote "" is unknown or unreachable.` Any trouble shooting help?

**Comment by townsend2010** [comment]
Hi @asishrs,

You are using a proxy on your Mac?  If so, then I can try to build and upload a Mac test package like what I have for Windows.

Thanks!

**Comment by townsend2010** [comment]
Hey all,

I found that `transfer.sh` is having issues, so yeah, the Windows test package is not available.  Please [try this](https://file.io/zJY0Jn) and hopefully it will work.

**Comment by tdevilleduc** [comment]
Hi @townsend2010 !

Thank you for that last link, but it gives me a 404 :(

**Comment by asishrs** [comment]
> Hi @asishrs,
> 
> You are using a proxy on your Mac? If so, then I can try to build and upload a Mac test package like what I have for Windows.
> 
> Thanks!

Yes, I need to use a proxy to connect to internet.

**Comment by townsend2010** [comment]
Hi @tdevilleduc,

Hrmph, not sure what is going on with the various file sharing sites.  Please try https://file.io/Atq1v8.

Thanks!

**Comment by townsend2010** [comment]
Hi @asishrs,

I can work on making a test package available to you much in the same way for the Windows test package.

**Comment by tdevilleduc** [comment]
> Hi @tdevilleduc,
> 
> Hrmph, not sure what is going on with the various file sharing sites. Please try https://file.io/Atq1v8.
> 
> **EDIT** I see, if the file is downloaded once on `file.io` it is automatically deleted unlike what `transfer.sh` does (when it works).
> 
> Thanks!

I had downloaded the file and send it to me by email; I will try tomorrow and tell you

**Comment by townsend2010** [comment]
@tdevilleduc,

Great, thanks!

**Comment by townsend2010** [comment]
Hey all,

Anyone else that may be affected can also try downloading this at https://easyupload.io/7bu9t2.  The link will expire 15 days from today.

Thanks!

**Comment by tdevilleduc** [comment]
So i tried it behind proxy and i have this result :

```
$ multipass version
multipass  1.1.0-dev.564+g8d36348c.win
multipassd 1.1.0-dev.564+g8d36348c.win
```

```
$  multipass find
No images found.
```

```
$  multipass launch ubuntu
launch failed: Remote "" is unknown or unreachable.
```

**Comment by townsend2010** [comment]
Hi @tdevilleduc,

Thanks for trying this.  Too bad it didn't work :frowning_face: 

There should be a message in the Event Log that gives us a bit more information.  It will have `Could not update manifest:` and then a reason for the failure.  Could you please see if you can find this message and post it here?

Also, does your proxy require any sort of authentication?

Thanks for helping with this!

**Comment by townsend2010** [comment]
Hey @tdevilleduc,

Also, could you please share exactly how you set your proxy settings?  Are they just the regular `http_proxy` and friends environment variables or did you use the `proxycfg.exe` tool on Windows?  

And I assume this is system wide such that other Internet applications just pick up the proxy settings automatically, right?

**Comment by tdevilleduc** [comment]
I looked at event log and i get this message
`
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/minimal/releases/xenial/release/ubuntu-16.04-minimal-cloudimg-amd64-disk1.img': Proxy requires authentication
`

About my proxy configuration i have defined HTTP_PROXY and HTTPS_PROXY environment variable (user variables) with login/password in it

**Comment by townsend2010** [comment]
@tdevilleduc,

Great, thanks!  So it is definitely trying to use the proxy and I'm guessing before I put the change in, it didn't even try.  As an experiment to make sure I'm on the right track, could you please try the release version of Multipass and see what that error is?

What happens with your other applications that try to use the proxy?  Do they pop up a window for you to enter the proxy credentials?  I don't think popping up a window is the best solution for this, so I'll have to think about how this can be achieved and/or see if there is some way to workaround this.

**Comment by tdevilleduc** [comment]
I downloaded and installed multipass 1.0.0
Here is evenlogs:
`
[main] calling service ctrl dispatcher
[service_main] registering control handler
[service_main] service is running
[update] Failed to fetch update info: failed to download from 'https://multipass.run/static/latest-release.json': Proxy requires authentication
[rpc] gRPC listening on localhost:50051, SSL:on
[Qt] QIODevice::write (QFile, "C:\Windows\system32\config\systemprofile\AppData\Local\multipassd\cache\vault\multipassd-image-records.json"): device not open
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/releases/streams/v1/index.json': Proxy requires authentication
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/daily/streams/v1/index.json': Proxy requires authentication
[VMImageHost] Could not update manifest: failed to download from 'http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Proxy requires authentication
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/minimal/releases/xenial/release/ubuntu-16.04-minimal-cloudimg-amd64-disk1.img': Proxy requires authentication
`

then when i exec "multipass find" i've got theses
`[VMImageHost] Could not update manifest: failed to download from 'http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Proxy requires authentication
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/minimal/releases/xenial/release/ubuntu-16.04-minimal-cloudimg-amd64-disk1.img': Proxy requires authentication
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/releases/streams/v1/index.json': Proxy requires authentication
[VMImageHost] Could not update manifest: failed to download from 'http://cloud-images.ubuntu.com/daily/streams/v1/index.json': Proxy requires authentication
`


About proxy authentification, like i said there is no popup
My HTTP_PROXY env var is like :
http_proxy=http://<login>:<password>@<proxy-url>:<proxy-port>

**Comment by townsend2010** [comment]
Hey @tdevilleduc,

Thanks so much for the details.  So it looks like even without my change, it was aware of the proxy.

And you already have the credentials in the env vars, so I'll see what we can do to be able to parse that out and use it.

I'll reply here if I have a test package for you to try or any other info.

Thanks again!

**Comment by townsend2010** [comment]
Hi @asishrs,

On your Mac, are you using proxy authentication like in https://github.com/canonical/multipass/issues/885#issuecomment-579775732?

Also, how are you setting your proxy configuration on Mac?

**Comment by asishrs** [comment]
> Hi @asishrs,
> 
> On your Mac, are you using proxy authentication like in [#885 (comment)](https://github.com/canonical/multipass/issues/885#issuecomment-579775732)?
> 
> Also, how are you setting your proxy configuration on Mac?

is that question about the proxy settings system-wide vs console? If so, the setting is for a console.

**Comment by townsend2010** [comment]
Hi @asishrs,

Well, I meant how are you setting up your proxy configuration?  Any details would be helpful as I work on a solution for this.

Thanks!

**Comment by asishrs** [comment]
My proxy settings are as below.
```
http_proxy=url:port
https_proxy=url:port
```

I set this in the console before executing multipass commands.

**Comment by Saviq** [comment]
> My proxy settings are as below.
> 
> ```
> http_proxy=url:port
> https_proxy=url:port
> ```
> 
> I set this in the console before executing multipass commands.

Hey @asishrs, note you will need to set these as system variables, otherwise the Multipass service won't notice them.

**Comment by tkksin1977** [comment]
you can use following  command on the Windwos powerShell to set the http proxy before running multipass comnand 

netsh winhttp set proxy http://<ip>:<port>

**Comment by Saviq** [comment]
@tkksin1977 will that get passed through to the Multipass service though?

**Comment by m4y0nnaise** [comment]
Hi,

Still have the issue on Ubuntu...

````
$ multipass --version                 
multipass   1.10.1
multipassd  1.10.1
````

HTTP_PROXY HTTPS_PROXY NO_PROXY and even http_proxy https_proxy and no_proxy are globaly set.

**Comment by drbjim** [comment]
I was able to set proxy on Mac m1

open plist file
`sudo vi /Library/LaunchDaemons/com.canonical.multipassd.plist`

and add HTTP_PROXY under `EnvironmentVariables`

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>EnvironmentVariables</key>
        <dict>
                <key>HTTP_PROXY</key>
                <string>http://proxy.com:80</string>
                <key>HTTPS_PROXY</key>
                <string>http://proxy.com:80</string>
                <key>PATH</key>
                <string>/Library/Application Support/com.canonical.multipass/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        </dict>
....`

**Comment by florentulve** [comment]
On windows, Is there a way to set proxy without setting system environment variable ? I dont want mess with other app.

**Comment by ricab** [comment]
Hi @florentulve, you might be able to set the variables only to the Multpass service, with something like:

```PowerShell
PS> Stop-Service Multipass
PS> Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\Session Manager\Environment" -Name HTTP_PROXY -Value "<proxy>"
PS> Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\Session Manager\Environment" -Name HTTPS_PROXY -Value "<proxy>
PS> Start-Service Multipass
```
