### ISSUE TITLE
No obvious error when Hyper-V is not enabled on the host

### ISSUE THREAD

**Issue by nobuto-m** [canonical/multipass#921]
Windows Pro has Hyper-V disabled out of the box, and it has to be enabled explicitly. At this moment, `multipass launch` on Windows fails with timeout and doesn't tell us what's wrong.

It would be nice if multipass tells us Hyper-V is not enabled and point us to some documents like the following link from a user experience point of view.
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

**Comment by Saviq** [comment]
Yes, totally. We're planning in #775 to implement extensive "health" checks for exactly this reason.

Before, we were just enabling Hyper-V ourselves (and checking your Windows version is enough), but now we've [added VirtualBox support](https://discourse.ubuntu.com/t/announcing-the-multipass-0-7-0-beta-release/11042) that wasn't an option any more.
