### ISSUE TITLE
Cannot install Multipass pkg on macOS Catalina

### ISSUE THREAD

**Issue by fredldotme** [canonical/multipass#932]
Using the macOS 10.15 Catalina beta it's not possible to install the Multipass pkg file from the GitHub releases page due to missing notarization of the package.

https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

The homebrew variant works though.

**Comment by Saviq** [comment]
Thanks @fredldotme! `brew` uses the same exact installer (even downloaded from the same URL), it's a bit weird that they'd allow that, but not the installer itself…

**Comment by gerboland** [comment]
Thanks for the ping, I've been aware notarization is required by GateKeeper soon. I'd better get on it
