### ISSUE TITLE
Mounts don't appear to be properly restored on host reboot

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#936]
I just rebooted my machine, and when I `multipass exec my-vm /bin/bash`'d my way in to a multipass VM (`my-vm`), a mountpoint (`/my/mountpoint`) that I had configured previously was just an empty directory. To remedy this, I figured I would just perform the mount again:

```
$ multipass mount /the/same/local/path my-vm:/my/mountpoint
mount failed: The following errors occurred:                                    
There is already a mount defined for "my-vm:/my/mountpoint"
```

After this, `/my/mountpoint` had the contents I would expect, and I was able to proceed on with my work.

**Comment by OddBloke** [comment]
I've seen this a couple of times now (I don't use multipass every time I boot my machine, so I can't be sure that it's consistent, though), so if there's any extra debugging info I could provide that would be helpful, let me know and I'll try to grab it next time I see this occur.

**Comment by townsend2010** [comment]
The mount handling has undergone some major changes in #2835 and I believe when that PR is merged, this issue will be fixed.
