### ISSUE TITLE
Document the (CPU|disk|memory) defaults in `multipass help launch`

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#957]
When writing [my blog post](https://write.wrestle.town/oddbloke/using-multipass-to-create-a-writefreely-dev-vm), I wanted to mention the default amount of memory in a multipass VM and had to launch a new VM to check what it was. It would be nice if I didn't have to do that (and for users on more constrained systems, they may want to know the defaults before they launch at all!).

**Comment by townsend2010** [comment]
Good idea, we should document the defaults for each in `multipass launch --help` at the very least.

**Comment by Saviq** [comment]
Yup, note we'll have them configurable through #756 :)

**Comment by makspiechota** [comment]
I would like to take this task.

**Comment by townsend2010** [comment]
@makspiechota,

Hey!  Sure, go right ahead :grinning: Thanks for the upcoming contribution!

**Comment by makspiechota** [comment]
@townsend2010 As far I see there is no information about default values in launch cmd module. If there is any way I can ask daemon about it, would you like me to do it this way? Or just hard code already known values?

**Comment by ricab** [comment]
Hi @makspiechota, thank you for your involvement!

This is static information, so I think communication with the daemon is unnecessary. Having duplicate sources of truth hard coded would not be ideal either. 

I would say this should be in a single place that both the daemon and the client would include. I believe the [constants header](https://github.com/CanonicalLtd/multipass/blob/7948657c162ba6b2b5a70eb80c782dc736b41bb3/include/multipass/constants.h) would be just the place. It is already included in the `launch` command for minimum sizes.

(FWIW, we plan to make this configurable in the future &ndash; see #756 &ndash; but that is a totally separate issue.)

**Comment by makspiechota** [comment]
So maybe I will use those constant and I will always pass a value to daemon (user if specified, default from header if not) to disallow daemon to decide?

**Comment by ricab** [comment]
Hey @makspiechota, that would be one possibility, but then any client asking the daemon to launch would have to specify these values (or the daemon wouldn't know what to do). If they failed to do so, the daemon would have to fail the request (or have its own defaults). 

We'll probably end up going that way for #756 &ndash; those options are part of the client config in that proposal (even if that is not yet set in stone). However, my impression is that this issue should not have to deal with that ATM. 

You could merely report existing defaults without moving them from daemon to client(s). That would be a smaller delta and keep our options open. @townsend2010 WDYT?

**Comment by ricab** [comment]
To be clear, what I had in mind was basically:
1. declare `default_(cpu|disk|mem) = blah;` in `constants.h`
2. include `constants.h` in `daemon.cpp` if not there yet; use those defaults instead of hardcoded values
3. include the same `constants.h` in the CLI client and report those defaults in `launch --help`

**Comment by makspiechota** [comment]
alright, so for now I'll take the second path with daemon taking the constants from header
