### ISSUE TITLE
`multipass launch` pads its output to 80 characters with whitespace

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#958]
You can't _see_ this per se, but copying/pasting whole lines from my console demonstrates the problem:

```shell
% multipass launch bionic
Launched: steady-koel                                                           
```

```python3
>>> len("Launched: steady-koel                                                           ")
80
```

I would expect no trailing whitespace.

**Comment by townsend2010** [comment]
Strange...thanks for reporting this!

**Comment by Saviq** [comment]
I believe this is because we're updating the status on the same line, so we have to overwrite with spaces?
