### ISSUE TITLE
Verbose mode doesn't work for launch

### ISSUE THREAD

**Issue by Andras-Csanyi** [canonical/multipass#962]
I try to figure out why my Virtualbox backed VM doesn't start. Verbose mode doesn't work at all.

```
PS C:\Users\Andras Csanyi> multipass launch ubuntu -n sdf -vvv
launch failed: The following errors occurred:
sdf: timed out waiting for response
PS C:\Users\Andras Csanyi>
```

**Comment by Saviq** [comment]
You're right, somehow we're losing the extended logging info in the `launch` command. Thanks for noticing!
