### ISSUE TITLE
Systray icon integration on macOS

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#968]
Some references for the available APIs:

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html

**Comment by ricab** [comment]
This issue has two parts:
- [ ] Shortcut to Multipass GUI, with the multipass icon and the name "Multipass" (wherever mac shortcuts usually are)
- [ ] Autostarting
