### ISSUE TITLE
The multipass GUI should quit on uninstall

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#969]

**Comment by ricab** [comment]
On windows, trying to quit after uninstall causes it to hang.

**Comment by Saviq** [comment]
I'm not sure we can do anything good to actually _quit_ it on uninstall (except maybe on Windows, where we have an explicit uninstaller), but we should definitely not hang on quit.

**Comment by ricab** [comment]
There is a [remove hook](https://snapcraft.io/docs/supported-snap-hooks) in snaps.

**Comment by Saviq** [comment]
@ricab yeah maybe, if we used `killall` right… Not entirely sure it's the right thing to do. It may very well be snapd that should handle this.

**Comment by Saviq** [comment]
After discussion I don't think we should do this.

**Comment by Saviq** [comment]
I think we don't have a choice on Windows, but `Stop-Process -Name multipass.gui` before uninstallation.

**Comment by ricab** [comment]
Sounds reasonable. It would be great if we could pass the full path, to make sure we were killing the right process.
