### ISSUE TITLE
[libvirt] fails to notice instance is already running

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#993]
```
$ virsh list
 Id   Name                   State
--------------------------------------
 5    snapcraft-subsurface   running

$ multipass ls                       
Name                    State             IPv4             Image
snapcraft-subsurface    Stopped           --               Ubuntu Snapcraft builder for Core 18

$ multipass start snapcraft-subsurface
start failed: Requested operation is not valid: domain is already running
```

**Comment by townsend2010** [comment]
I'm not sure of the repro steps here.

Was multipassd running and then the instance was started via `virsh`?  Was the instance running and then `multipassd` was started?

Could you please provide the exact repro steps?

**Comment by townsend2010** [comment]
Ok, I think I figured out the repro steps.  I'll continue working on this.

**Comment by Saviq** [comment]
Yeah, basically the instance was running when Multipass thought it was not. Not sure how it originally happened, but yes starting with `virsh` does show the problem.
